Cantera: SurfPhase Class Reference
SurfPhase Class Reference
Models of Phases of Matter » Thermodynamic Properties
A simple thermodynamic model for a surface phase, assuming an ideal solution model.
#include <SurfPhase.h>
Public Member Functions
SurfPhase (const std::string &infile="", const std::string &id="")
Construct and initialize a SurfPhase ThermoPhase object directly from an input file.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual doublereal enthalpy_mole () const
Return the Molar Enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Return the Molar Internal Energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Return the Molar Entropy. Units: J/kmol-K.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getActivityConcentrations (doublereal *c) const
Return a vector of activity concentrations for each species.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual double molarVolume () const
Since interface phases have no volume, this returns 0.0.
virtual void setMolarDensity (const double vm)
Since interface phases have no volume, setting this to a value other than 0.0 raises an exception.
double siteDensity () const
Returns the site density.
virtual double size (size_t k) const
Returns the number of sites occupied by one molecule of species k.
void setSiteDensity (doublereal n0)
Set the site density of the surface phase (kmol m-2)
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void getPureGibbs (doublereal *g) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
void setCoverages (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesNoNorm (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesByName (const std::string &cov)
Set the coverages from a string of colon-separated name:value pairs.
void setCoveragesByName (const compositionMap &cov)
Set the coverages from a map of name:value pairs.
void getCoverages (doublereal *theta) const
Return a vector of surface coverages.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_DP (double rho, double p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setTemperature (double temp)
Set the internally stored temperature of the phase (K).
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
void _updateThermo (bool force=false) const
Update the species reference state thermodynamic functions.
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes
double m_n0 = 1.0
Surface site density (kmol m-2)
vector_fp m_speciesSize
Vector of species sizes (number of sites occupied). length m_kk.
doublereal m_logn0
log of the surface site density
double m_press = OneAtm
Current value of the pressure (Pa)
vector_fp m_h0
Temporary storage for the reference state enthalpies.
vector_fp m_s0
Temporary storage for the reference state entropies.
vector_fp m_cp0
Temporary storage for the reference state heat capacities.
vector_fp m_mu0
Temporary storage for the reference state Gibbs energies.
vector_fp m_work
Temporary work array.
vector_fp m_logsize
vector storing the log of the size of each species.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Detailed Description
A simple thermodynamic model for a surface phase, assuming an ideal solution model.
The surface consists of a grid of equivalent sites. Surface species may be defined to occupy one or more sites. The surface species are assumed to be independent, and thus the species form an ideal solution.
The density of surface sites is given by the variable \(n_0 \), which has SI units of kmol m-2.
Specification of Species Standard State Properties
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
Pressure is defined as an independent variable in this phase. However, it has no effect on any quantities, as the molar concentration is a constant.
Therefore, The standard state internal energy for species k is equal to the enthalpy for species k.
  \f[
       u^o_k = h^o_k
  \f]
Also, the standard state chemical potentials, entropy, and heat capacities are independent of pressure. The standard state Gibbs free energy is obtained from the enthalpy and entropy functions.
Specification of Solution Thermodynamic Properties
The activity of species defined in the phase is given by
\[ a_k = \theta_k \]
The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T) + R T \log(\theta_k) \]
Pressure is defined as an independent variable in this phase. However, it has no effect on any quantities, as the molar concentration is a constant.
The internal energy for species k is equal to the enthalpy for species k
\[ u_k = h_k \]
The entropy for the phase is given by the following relation, which is independent of the pressure:
  \f[
       s_k(T,P) = s^o_k(T) - R \log(\theta_k)
  \f]
Application within Kinetics Managers
The activity concentration, \(C^a_k \), used by the kinetics manager, is equal to the actual concentration, \(C^s_k \), and is given by the following expression.
\[ C^a_k = C^s_k = \frac{\theta_k n_0}{s_k} \]
The standard concentration for species k is:
\[ C^0_k = \frac{n_0}{s_k} \]
An example phase definition is given in the YAML API Reference.
Definition at line 97 of file SurfPhase.h.
Constructor & Destructor Documentation
SurfPhase()
SurfPhase (const std::string & infile = "", const std::string & id = "") explicit
Construct and initialize a SurfPhase ThermoPhase object directly from an input file.
Parameters
infile name of the input file. If blank, an empty phase will be created.
id name of the phase id in the file. If this is blank, the first phase in the file is used.
Definition at line 22 of file SurfPhase.cpp.
References ThermoPhase::initThermoFile(), and Phase::setNDim().
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase, and EdgePhase.
Definition at line 109 of file SurfPhase.h.
isCompressible()
virtual bool isCompressible () const inline virtual
Return whether phase represents a compressible substance.
Reimplemented from Phase.
Definition at line 113 of file SurfPhase.h.
enthalpy_mole()
doublereal enthalpy_mole () const virtual
Return the Molar Enthalpy. Units: J/kmol.
For an ideal solution,
\[ \hat h(T,P) = \sum_k X_k \hat h^0_k(T), \]
and is a function only of temperature. The standard-state pure-species Enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 28 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_h0, SurfPhase::m_n0, and Phase::mean_X().
Referenced by SurfPhase::intEnergy_mole().
intEnergy_mole()
doublereal intEnergy_mole () const virtual
Return the Molar Internal Energy. Units: J/kmol.
For a surface phase, the pressure is not a relevant thermodynamic variable, and so the Enthalpy is equal to the Internal Energy.
Reimplemented from ThermoPhase.
Definition at line 37 of file SurfPhase.cpp.
References SurfPhase::enthalpy_mole().
entropy_mole()
doublereal entropy_mole () const virtual
Return the Molar Entropy. Units: J/kmol-K.
\[ \hat s(T,P) = \sum_k X_k (\hat s^0_k(T) - R \log(\theta_k)) \]
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 42 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Phase::concentration(), Cantera::GasConstant, Phase::m_kk, SurfPhase::m_n0, SurfPhase::m_s0, Phase::moleFraction(), SurfPhase::size(), and Cantera::SmallNumber.
cp_mole()
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 53 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_cp0, and Phase::mean_X().
Referenced by SurfPhase::cv_mole().
cv_mole()
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 59 of file SurfPhase.cpp.
References SurfPhase::cp_mole().
getChemPotentials()
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 103 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::getActivityConcentrations(), SurfPhase::logStandardConc(), Phase::m_kk, SurfPhase::m_mu0, SurfPhase::m_work, ThermoPhase::RT(), and Cantera::SmallNumber.
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 64 of file SurfPhase.cpp.
References SurfPhase::getEnthalpy_RT(), Phase::m_kk, and ThermoPhase::RT().
getPartialMolarEntropies()
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 72 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getActivityConcentrations(), SurfPhase::getEntropy_R(), SurfPhase::logStandardConc(), Phase::m_kk, SurfPhase::m_work, and Cantera::SmallNumber.
getPartialMolarCp()
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 82 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getCp_R(), and Phase::m_kk.
getPartialMolarVolumes()
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 92 of file SurfPhase.cpp.
References SurfPhase::getStandardVolumes().
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 97 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), and SurfPhase::m_mu0.
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
Return a vector of activity concentrations for each species.
For this phase the activity concentrations, \(C^a_k \), are defined to be equal to the actual concentrations, \(C^s_k \). Activity concentrations are
 \f[
       C^a_k = C^s_k = \frac{\theta_k  n_0}{s_k}
 \f]
where \(\theta_k \) is the surface site fraction for species k, \(n_0 \) is the surface site density for the phase, and \(s_k \) is the surface size of species k.
\(C^a_k\) that are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages,
Parameters
c vector of activity concentration (kmol m-2).
Reimplemented from ThermoPhase.
Definition at line 113 of file SurfPhase.cpp.
References Phase::getConcentrations().
Referenced by SurfPhase::getChemPotentials(), and SurfPhase::getPartialMolarEntropies().
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (that is, generalized) concentration. For this phase, the standard concentration is species- specific
   \f[
       C^0_k = \frac{n_0}{s_k}
   \f]
This definition implies that the activity is equal to \(\theta_k \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
the standard concentration in units of kmol/m^2 for surface phases or kmol/m for edge phases.
Reimplemented from ThermoPhase.
Definition at line 118 of file SurfPhase.cpp.
References SurfPhase::m_n0, and SurfPhase::size().
logStandardConc()
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 123 of file SurfPhase.cpp.
References SurfPhase::m_logn0, and SurfPhase::m_logsize.
Referenced by SurfPhase::getChemPotentials(), and SurfPhase::getPartialMolarEntropies().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 327 of file SurfPhase.cpp.
References AnyMap::convert(), AnyMap::hasKey(), ThermoPhase::m_input, Phase::m_ndim, and SurfPhase::setSiteDensity().
Referenced by CoverageDependentSurfPhase::initThermo().
getParameters()
void getParameters (AnyMap & phaseNode) const virtual
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
This does not include user-defined fields available in input().
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 336 of file SurfPhase.cpp.
References ThermoPhase::getParameters(), SurfPhase::m_n0, and Phase::m_ndim.
Referenced by CoverageDependentSurfPhase::getParameters().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 185 of file SurfPhase.cpp.
References ThermoPhase::addSpecies(), SurfPhase::m_cp0, SurfPhase::m_h0, Phase::m_kk, SurfPhase::m_logsize, SurfPhase::m_mu0, SurfPhase::m_s0, SurfPhase::m_speciesSize, SurfPhase::m_work, and SurfPhase::setCoverages().
Referenced by CoverageDependentSurfPhase::addSpecies().
molarVolume()
virtual double molarVolume () const inline virtual
Since interface phases have no volume, this returns 0.0.
Reimplemented from Phase.
Definition at line 208 of file SurfPhase.h.
setMolarDensity()
void setMolarDensity (const double vm) virtual
Since interface phases have no volume, setting this to a value other than 0.0 raises an exception.
Deprecated:
Unused. To be removed after Cantera 3.0
Reimplemented from Phase.
Definition at line 204 of file SurfPhase.cpp.
References Cantera::warn_deprecated().
siteDensity()
double siteDensity () const inline
Returns the site density.
Site density kmol m-2
Definition at line 221 of file SurfPhase.h.
References SurfPhase::m_n0.
Referenced by ReactingSurf1D::eval(), Reactor::evalSurfaces(), and InterfaceData::update().
size()
virtual double size (size_t k) const inline virtual
Returns the number of sites occupied by one molecule of species k.
Definition at line 226 of file SurfPhase.h.
References SurfPhase::m_speciesSize.
Referenced by SurfPhase::entropy_mole(), ReactingSurf1D::eval(), MoleReactor::evalSurfaces(), Reactor::evalSurfaces(), SurfPhase::getCoverages(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), and SurfPhase::standardConcentration().
setSiteDensity()
void setSiteDensity (doublereal n0)
Set the site density of the surface phase (kmol m-2)
Parameters
n0 Site density of the surface phase (kmol m-2)
Definition at line 212 of file SurfPhase.cpp.
References Phase::assignDensity(), SurfPhase::m_logn0, SurfPhase::m_n0, and Phase::meanMolecularWeight().
Referenced by SurfPhase::initThermo().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 134 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_mu0, ThermoPhase::RT(), and Cantera::scale().
Referenced by SurfPhase::getGibbs_RT_ref().
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 140 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_h0, ThermoPhase::RT(), and Cantera::scale().
Referenced by SurfPhase::getEnthalpy_RT_ref(), and SurfPhase::getPartialMolarEnthalpies().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 146 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_s0, and Cantera::scale().
Referenced by SurfPhase::getEntropy_R_ref(), and SurfPhase::getPartialMolarEntropies().
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 152 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_cp0, and Cantera::scale().
Referenced by SurfPhase::getCp_R_ref(), and SurfPhase::getPartialMolarCp().
getStandardVolumes()
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 158 of file SurfPhase.cpp.
References Phase::m_kk.
Referenced by SurfPhase::getPartialMolarVolumes().
pressure()
virtual doublereal pressure () const inline virtual
Return the thermodynamic pressure (Pa).
Reimplemented from Phase.
Definition at line 243 of file SurfPhase.h.
References SurfPhase::m_press.
Referenced by ReactingSurf1D::asArray().
setPressure()
virtual void setPressure (doublereal p) inline virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
Parameters
p input Pressure (Pa)
Reimplemented from Phase.
Definition at line 252 of file SurfPhase.h.
References SurfPhase::m_press.
getPureGibbs()
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 128 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), and SurfPhase::m_mu0.
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 165 of file SurfPhase.cpp.
References SurfPhase::getGibbs_RT().
getEnthalpy_RT_ref()
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 170 of file SurfPhase.cpp.
References SurfPhase::getEnthalpy_RT().
getEntropy_R_ref()
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 175 of file SurfPhase.cpp.
References SurfPhase::getEntropy_R().
getCp_R_ref()
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Reimplemented in CoverageDependentSurfPhase.
Definition at line 180 of file SurfPhase.cpp.
References SurfPhase::getCp_R().
setCoverages()
void setCoverages (const doublereal * theta)
Set the surface site fractions to a specified state.
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Parameters
theta This is the surface site fraction for the kth species in the surface phase. This is a dimensionless quantity.
This routine normalizes the theta's to 1, before application
Definition at line 223 of file SurfPhase.cpp.
References Phase::m_kk, SurfPhase::m_work, Phase::setMoleFractions(), and SurfPhase::size().
Referenced by SurfPhase::addSpecies(), ReactingSurf1D::asArray(), ReactingSurf1D::resetBadValues(), and SurfPhase::setCoveragesByName().
setCoveragesNoNorm()
void setCoveragesNoNorm (const doublereal * theta)
Set the surface site fractions to a specified state.
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Parameters
theta This is the surface site fraction for the kth species in the surface phase. This is a dimensionless quantity.
Definition at line 239 of file SurfPhase.cpp.
References Phase::m_kk, SurfPhase::m_work, Phase::setMoleFractions_NoNorm(), and SurfPhase::size().
Referenced by ReactingSurf1D::eval(), and ReactorSurface::syncState().
setCoveragesByName() [1/2]
void setCoveragesByName (const std::string & cov)
Set the coverages from a string of colon-separated name:value pairs.
Parameters
cov String containing colon-separated name:value pairs
Definition at line 271 of file SurfPhase.cpp.
References Cantera::parseCompString(), SurfPhase::setCoveragesByName(), and Phase::speciesNames().
Referenced by ReactorSurface::setCoverages(), SurfPhase::setCoveragesByName(), and SurfPhase::setState().
setCoveragesByName() [2/2]
void setCoveragesByName (const compositionMap & cov)
Set the coverages from a map of name:value pairs.
Definition at line 276 of file SurfPhase.cpp.
References Cantera::getValue(), Phase::m_kk, SurfPhase::setCoverages(), and Phase::speciesName().
getCoverages()
void getCoverages (doublereal * theta) const
Return a vector of surface coverages.
Get the coverages.
Parameters
theta Array theta must be at least as long as the number of species.
Definition at line 257 of file SurfPhase.cpp.
References Phase::getMoleFractions(), Phase::m_kk, and SurfPhase::size().
Referenced by ReactingSurf1D::_getInitialSoln(), CoverageDependentSurfPhase::_updateCovDepThermo(), ReactingSurf1D::resetBadValues(), ReactorSurface::setCoverages(), and ReactorSurface::setKinetics().
setState()
void setState (const AnyMap & state) virtual
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
Accepted keys are:
X (mole fractions)
Y (mass fractions)
T or temperature
P or pressure [Pa]
H or enthalpy [J/kg]
U or internal-energy [J/kg]
S or entropy [J/kg/K]
V or specific-volume [m^3/kg]
D or density [kg/m^3]
Composition can be specified as either an AnyMap of species names to values or as a composition string. All other values can be given as floating point values in Cantera's default units, or as strings with the units specified, which will be converted using the Units class.
If no thermodynamic property pair is given, or only one of temperature or pressure is given, then 298.15 K and 101325 Pa will be used as necessary to fully set the state.
Additionally uses the key coverages to set the fractional coverages.
Reimplemented from ThermoPhase.
Definition at line 294 of file SurfPhase.cpp.
References AnyMap::hasKey(), SurfPhase::setCoveragesByName(), and ThermoPhase::setState().
compositionChanged()
void compositionChanged () protected virtual
Apply changes to the state which are needed after the composition changes.
This function is called after any call to setMassFractions(), setMoleFractions(), or similar. For phases which need to execute a callback after any change to the composition, it should be done by overriding this function rather than overriding all of the composition- setting functions. Derived class implementations of compositionChanged() should call the parent class method as well.
Reimplemented from Phase.
Definition at line 305 of file SurfPhase.cpp.
References Phase::assignDensity(), Phase::compositionChanged(), SurfPhase::m_n0, and Phase::meanMolecularWeight().
_updateThermo()
void _updateThermo (bool force = false) const protected
Update the species reference state thermodynamic functions.
The polynomials for the standard state functions are only reevaluated if the temperature has changed.
Parameters
force Boolean, which if true, forces a reevaluation of the thermo polynomials. default = false.
Definition at line 311 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::m_cp0, SurfPhase::m_h0, Phase::m_kk, SurfPhase::m_mu0, SurfPhase::m_s0, ThermoPhase::m_spthermo, ThermoPhase::m_tlast, Phase::temperature(), and MultiSpeciesThermo::update().
Referenced by CoverageDependentSurfPhase::_updateTotalThermo(), SurfPhase::cp_mole(), SurfPhase::enthalpy_mole(), SurfPhase::entropy_mole(), SurfPhase::getChemPotentials(), SurfPhase::getCp_R(), CoverageDependentSurfPhase::getCp_R_ref(), SurfPhase::getEnthalpy_RT(), CoverageDependentSurfPhase::getEnthalpy_RT_ref(), SurfPhase::getEntropy_R(), CoverageDependentSurfPhase::getEntropy_R_ref(), SurfPhase::getGibbs_RT(), CoverageDependentSurfPhase::getGibbs_RT_ref(), SurfPhase::getPureGibbs(), and SurfPhase::getStandardChemPotentials().
Member Data Documentation
m_n0
double m_n0 = 1.0 protected
Surface site density (kmol m-2)
Definition at line 316 of file SurfPhase.h.
Referenced by SurfPhase::compositionChanged(), SurfPhase::enthalpy_mole(), SurfPhase::entropy_mole(), SurfPhase::getParameters(), SurfPhase::setSiteDensity(), SurfPhase::siteDensity(), and SurfPhase::standardConcentration().
m_speciesSize
vector_fp m_speciesSize protected
Vector of species sizes (number of sites occupied). length m_kk.
Definition at line 319 of file SurfPhase.h.
Referenced by SurfPhase::addSpecies(), and SurfPhase::size().
m_logn0
doublereal m_logn0 protected
log of the surface site density
Definition at line 322 of file SurfPhase.h.
Referenced by SurfPhase::logStandardConc(), and SurfPhase::setSiteDensity().
m_press
double m_press = OneAtm protected
Current value of the pressure (Pa)
Definition at line 325 of file SurfPhase.h.
Referenced by SurfPhase::pressure(), and SurfPhase::setPressure().
m_h0
vector_fp m_h0 mutable protected
Temporary storage for the reference state enthalpies.
Definition at line 328 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), SurfPhase::addSpecies(), SurfPhase::enthalpy_mole(), SurfPhase::getEnthalpy_RT(), and CoverageDependentSurfPhase::getEnthalpy_RT_ref().
m_s0
vector_fp m_s0 mutable protected
Temporary storage for the reference state entropies.
Definition at line 331 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), SurfPhase::addSpecies(), SurfPhase::entropy_mole(), SurfPhase::getEntropy_R(), and CoverageDependentSurfPhase::getEntropy_R_ref().
m_cp0
vector_fp m_cp0 mutable protected
Temporary storage for the reference state heat capacities.
Definition at line 334 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), SurfPhase::addSpecies(), SurfPhase::cp_mole(), SurfPhase::getCp_R(), and CoverageDependentSurfPhase::getCp_R_ref().
m_mu0
vector_fp m_mu0 mutable protected
Temporary storage for the reference state Gibbs energies.
Definition at line 337 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), SurfPhase::addSpecies(), SurfPhase::getChemPotentials(), SurfPhase::getGibbs_RT(), CoverageDependentSurfPhase::getGibbs_RT_ref(), SurfPhase::getPureGibbs(), and SurfPhase::getStandardChemPotentials().
m_work
vector_fp m_work mutable protected
Temporary work array.
Definition at line 340 of file SurfPhase.h.
Referenced by SurfPhase::addSpecies(), SurfPhase::getChemPotentials(), SurfPhase::getPartialMolarEntropies(), SurfPhase::setCoverages(), and SurfPhase::setCoveragesNoNorm().
m_logsize
vector_fp m_logsize mutable protected
vector storing the log of the size of each species.
The size of each species is defined as the number of surface sites each species occupies.
Definition at line 347 of file SurfPhase.h.
Referenced by SurfPhase::addSpecies(), and SurfPhase::logStandardConc().
The documentation for this class was generated from the following files:
SurfPhase.h
SurfPhase.cpp