Cantera: Writing messages to the screen
Writing messages to the screen
Diagnostic Output
Classes
class Application
Class to hold global data.
class ExternalLogger
Logger that delegates to an external source via a callback to produce log output.
class Logger
Base class for 'loggers' that write text messages to log files.
class NoExitLogger
Logger that doesn't exit when an error is thrown.
Functions
void writelog (const std::string &msg)
Write a message to the screen.
void warnlog (const std::string &warning, const std::string &msg)
Write a warning message to the screen.
void setLogger (Logger *logwriter)
Install a logger.
template<typename... Args>
void writelog (const std::string &fmt, const Args &... args)
Write a formatted message to the screen.
template<typename... Args>
void writelogf (const char *fmt, const Args &... args)
Write a formatted message to the screen.
Detailed Description
Function Documentation
writelog() [1/2]
void writelog (const std::string & msg)
Write a message to the screen.
The string may be of any length, and may contain end-of-line characters. This method is used throughout Cantera to write log messages. It can also be called by user programs. The advantage of using writelog over writing directly to the standard output is that messages written with writelog will display correctly even when Cantera is used from MATLAB or other application that do not have a standard output stream.
Parameters
msg c++ string to be written to the screen
Definition at line 69 of file application.cpp.
Referenced by Application::writelog().
warnlog()
void warnlog (const std::string & warning, const std::string & msg)
Write a warning message to the screen.
Parameters
warning String specifying type of warning; see Logger::warn()
msg String to be written to the screen
Definition at line 79 of file application.cpp.
Referenced by Application::warnlog().
setLogger()
void setLogger (Logger * logwriter)
Install a logger.
Called by the language interfaces to install an appropriate logger. The logger is used for the writelog() function
Parameters
logwriter Pointer to a logger object
See also
Logger.
Definition at line 64 of file application.cpp.
Referenced by Application::setLogger().
writelog() [2/2]
void writelog (const std::string & fmt, const Args &... args)
Write a formatted message to the screen.
This function passes its arguments to the fmt library 'format' function to generate a formatted string from a Python-style (curly braces) format string. This method is used throughout Cantera to write log messages. It can also be called by user programs. The advantage of using writelog over writing directly to the standard output is that messages written with writelog will display correctly even when Cantera is used from MATLAB or other application that do not have a standard output stream.
Definition at line 159 of file global.h.
References Cantera::writelog_direct().
Referenced by ReactorNet::advance(), Cantera::BasisOptimize(), MultiNewton::dampStep(), ChemEquil::dampStep(), Cantera::ElemRearrange(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), FuncEval::evalDaeNoThrow(), FuncEval::evalNoThrow(), GasTransport::fitCollisionIntegrals(), GasTransport::fitDiffCoeffs(), IonGasTransport::fitDiffCoeffs(), GasTransport::fitProperties(), MMCollisionInt::init(), ReactorNet::initialize(), FuncEval::preconditioner_setup_nothrow(), FuncEval::preconditioner_solve_nothrow(), solveSP::print_header(), HMWSoln::printCoeffs(), solveSP::printIteration(), AdaptivePreconditioner::printJacobian(), AdaptivePreconditioner::printPreconditioner(), Sim1D::refine(), Sim1D::save(), Sim1D::saveResidual(), ChemEquil::setInitialMoles(), Sim1D::show(), Inlet1D::show(), Surf1D::show(), ReactingSurf1D::show(), Domain1D::show(), StFlow::show(), MultiNewton::solve(), MixtureFugacityTP::solveCubic(), solveSP::solveSurfProb(), OneDim::timeStep(), VCS_SOLVE::vcs_basopt(), VCS_SOLVE::VCS_SOLVE(), ResidEval::writeSolution(), and OneDim::writeStats().
writelogf()
void writelogf (const char * fmt, const Args &... args)
Write a formatted message to the screen.
Using the printf formatting of C, write a message to the screen with variable values.
Here, we format an internal string with the correct values and then feed it into writelog().
Parameters
fmt c format string for the following arguments
args arguments used to interpolate the format string
Definition at line 180 of file global.h.
References Cantera::writelog_direct().
Referenced by Cantera::BasisOptimize(), ChemEquil::dampStep(), Cantera::ElemRearrange(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), GasTransport::fitDiffCoeffs(), IonGasTransport::fitDiffCoeffs(), GasTransport::fitProperties(), MMCollisionInt::init(), Cantera::invert(), solveSP::print_header(), HMWSoln::printCoeffs(), solveSP::printIteration(), ChemEquil::setInitialMoles(), solveSP::solveSurfProb(), and ResidEval::writeSolution().