Cantera: PlogReaction2 Class Reference
PlogReaction2 Class Reference
A pressure-dependent reaction parameterized by logarithmically interpolating between Arrhenius rate expressions at various pressures.
#include <Reaction.h>
Public Member Functions
PlogReaction2 (const Composition &reactants, const Composition &products, const Plog &rate)
virtual std::string type () const
The type of reaction.
virtual void validate ()
Ensure that the rate constant and other parameters for this reaction are valid.
virtual void getParameters (AnyMap &reactionNode) const
Store the parameters of a Reaction needed to reconstruct an identical object using the newReaction(AnyMap&, Kinetics&) function.
virtual void validate ()
Ensure that the rate constant and other parameters for this reaction are valid.
virtual void validate (Kinetics &kin)
Perform validation checks that need access to a complete Kinetics objects, for.
Public Member Functions inherited from Reaction
Reaction (const Composition &reactants, const Composition &products, shared_ptr< ReactionRate > rate={})
Reaction (const AnyMap &node, const Kinetics &kin)
Construct a Reaction and it's corresponding ReactionRate based on AnyMap (YAML) input.
Reaction (int type)
Reaction (int type, const Composition &reactants, const Composition &products)
virtual std::string reactantString () const
The reactant side of the chemical equation for this reaction.
virtual std::string productString () const
The product side of the chemical equation for this reaction.
std::string equation () const
The chemical equation for this reaction.
virtual void setEquation (const std::string &equation, const Kinetics *kin=0)
Set the reactants and products based on the reaction equation.
virtual void calculateRateCoeffUnits (const Kinetics &kin)
Calculate the units of the rate constant.
UnitStack calculateRateCoeffUnits3 (const Kinetics &kin)
Calculate the units of the rate constant.
AnyMap parameters (bool withInput=true) const
Return the parameters such that an identical Reaction could be reconstructed using the newReaction() function.
virtual void setParameters (const AnyMap &node, const Kinetics &kin)
Set up reaction based on AnyMap node
bool valid () const
Get validity flag of reaction.
void setValid (bool valid)
Set validity flag of reaction.
void checkBalance (const Kinetics &kin) const
Check that the specified reaction is balanced (same number of atoms for each element in the reactants and products).
bool checkSpecies (const Kinetics &kin) const
Verify that all species involved in the reaction are defined in the Kinetics object.
bool usesElectrochemistry (const Kinetics &kin) const
Check whether reaction uses electrochemistry.
shared_ptr< ReactionRate > rate ()
Get reaction rate pointer.
void setRate (shared_ptr< ReactionRate > rate)
Set reaction rate pointer.
shared_ptr< ThirdBody > thirdBody ()
Get pointer to third-body.
bool usesLegacy () const
Indicate whether object uses legacy framework.
Public Attributes
Plog rate
Public Attributes inherited from Reaction
int reaction_type
Type of the reaction.
Composition reactants
Reactant species and stoichiometric coefficients.
Composition products
Product species and stoichiometric coefficients.
Composition orders
Forward reaction order with respect to specific species.
std::string id
An identification string for the reaction, used in some filtering operations.
bool reversible
True if the current reaction is reversible. False otherwise.
bool duplicate
True if the current reaction is marked as duplicate.
bool allow_nonreactant_orders
True if reaction orders can be specified for non-reactant species.
bool allow_negative_orders
True if negative reaction orders are allowed. Default is false.
AnyMap input
Input data used for specific models.
Units rate_units
The units of the rate constant.
Additional Inherited Members
Protected Member Functions inherited from Reaction
virtual std::pair< std::vector< std::string >, bool > undeclaredThirdBodies (const Kinetics &kin) const
Protected Attributes inherited from Reaction
bool m_valid
Flag indicating whether reaction is set up correctly.
shared_ptr< ReactionRate > m_rate
Reaction rate used by generic reactions.
shared_ptr< ThirdBody > m_third_body
Relative efficiencies of third-body species in enhancing the reaction rate (if applicable)
Detailed Description
A pressure-dependent reaction parameterized by logarithmically interpolating between Arrhenius rate expressions at various pressures.
Definition at line 364 of file Reaction.h.
Constructor & Destructor Documentation
PlogReaction2() [1/2]
PlogReaction2 ()
Definition at line 834 of file Reaction.cpp.
PlogReaction2() [2/2]
PlogReaction2 (const Composition & reactants, const Composition & products, const Plog & rate)
Definition at line 840 of file Reaction.cpp.
Member Function Documentation
type()
virtual std::string type () const inline virtual
The type of reaction.
Reimplemented from Reaction.
Definition at line 371 of file Reaction.h.
validate() [1/3]
void validate () virtual
Ensure that the rate constant and other parameters for this reaction are valid.
Reimplemented from Reaction.
Definition at line 1830 of file Reaction.cpp.
References Reaction::equation(), and Reaction::validate().
getParameters()
void getParameters (AnyMap & reactionNode) const virtual
Store the parameters of a Reaction needed to reconstruct an identical object using the newReaction(AnyMap&, Kinetics&) function.
Does not include user-defined fields available in the input map.
Reimplemented from Reaction.
Definition at line 848 of file Reaction.cpp.
References Reaction::getParameters(), and Reaction::rate_units.
validate() [2/3]
void validate () virtual
Ensure that the rate constant and other parameters for this reaction are valid.
Reimplemented from Reaction.
Definition at line 78 of file Reaction.cpp.
validate() [3/3]
virtual void validate (Kinetics & kin) inline virtual
Perform validation checks that need access to a complete Kinetics objects, for.
Reimplemented from Reaction.
Definition at line 82 of file Reaction.h.
Member Data Documentation
rate
Plog rate
Definition at line 379 of file Reaction.h.
The documentation for this class was generated from the following files:
Reaction.h
Reaction.cpp