Cantera: FalloffRate Class Reference
FalloffRate Class Reference
Base class for falloff rate calculators.
#include <Falloff.h>
Public Member Functions
FalloffRate (const AnyMap &node, const UnitStack &rate_units={})
void init (const vector_fp &c)
Initialize.
virtual void setFalloffCoeffs (const vector_fp &c)
Set coefficients of the falloff parameterization.
virtual void getFalloffCoeffs (vector_fp &c) const
Retrieve coefficients of the falloff parameterization.
virtual void updateTemp (double T, double *work) const
Update the temperature-dependent portions of the falloff function, if any, and store them in the 'work' array.
virtual double F (double pr, const double *work) const
The falloff function.
double evalF (double T, double conc3b)
Evaluate falloff function at current conditions.
virtual size_t workSize () const
The size of the work array required.
virtual const std::string type () const override
String identifying reaction rate specialization.
virtual size_t nParameters () const
Returns the number of parameters used by this parameterization.
virtual void setParameters (const AnyMap &node, const UnitStack &rate_units) override
Set parameters.
virtual void getParameters (double *params) const
Get the values of the parameters for this object.
virtual void getParameters (AnyMap &node) const override
Get parameters.
double evalFromStruct (const FalloffData &shared_data)
Evaluate reaction rate.
virtual void check (const std::string &equation) override
Check basic syntax and settings of reaction rate expression.
virtual void validate (const std::string &equation, const Kinetics &kin) override
Validate the reaction rate expression.
bool allowNegativePreExponentialFactor () const
Get flag indicating whether negative A values are permitted.
void setAllowNegativePreExponentialFactor (bool value)
Set flag indicating whether negative A values are permitted.
bool chemicallyActivated () const
Get flag indicating whether reaction is chemically activated.
void setChemicallyActivated (bool activated)
Set flag indicating whether reaction is chemically activated.
ArrheniusRate & lowRate ()
Get reaction rate in the low-pressure limit.
void setLowRate (const ArrheniusRate &low)
Set reaction rate in the low-pressure limit.
ArrheniusRate & highRate ()
Get reaction rate in the high-pressure limit.
void setHighRate (const ArrheniusRate &high)
Set reaction rate in the high-pressure limit.
Public Member Functions inherited from ReactionRate
ReactionRate (const ReactionRate &other)
ReactionRate & operator= (const ReactionRate &other)
virtual unique_ptr< MultiRateBase > newMultiRate () const
Create a rate evaluator for reactions of a particular derived type.
virtual const std::string type () const =0
String identifying reaction rate specialization.
virtual const std::string subType () const
String identifying sub-type of reaction rate specialization.
virtual void setParameters (const AnyMap &node, const UnitStack &units)
Set parameters.
AnyMap parameters () const
Return the parameters such that an identical Reaction could be reconstructed using the newReaction() function.
const Units & conversionUnits () const
Get the units for converting the leading term in the reaction rate expression.
virtual void setRateUnits (const UnitStack &rate_units)
Set the units of the reaction rate expression.
virtual void check (const std::string &equation)
Check basic syntax and settings of reaction rate expression.
void check (const std::string &equation, const AnyMap &node)
Check basic syntax and settings of reaction rate expression.
virtual void validate (const std::string &equation, const Kinetics &kin)
Validate the reaction rate expression.
virtual void validate (const std::string &equation)
Validate the reaction rate expression (legacy call)
size_t rateIndex () const
Reaction rate index within kinetics evaluator.
void setRateIndex (size_t idx)
Set reaction rate index within kinetics evaluator.
virtual void setContext (const Reaction &rxn, const Kinetics &kin)
Set context of reaction rate evaluation.
double eval (double T)
Evaluate reaction rate based on temperature.
double eval (double T, double extra)
Evaluate reaction rate based on temperature and an extra parameter.
double eval (double T, const std::vector< double > &extra)
Evaluate reaction rate based on temperature and an extra vector parameter.
bool valid () const
Get flag indicating whether reaction rate is set up correctly.
bool compositionDependent ()
Boolean indicating whether rate has compositional dependence.
void setCompositionDependence (bool comp_dep)
Set rate compositional dependence.
Protected Attributes
ArrheniusRate m_lowRate
The reaction rate in the low-pressure limit.
ArrheniusRate m_highRate
The reaction rate in the high-pressure limit.
bool m_chemicallyActivated = false
Flag labeling reaction as chemically activated.
bool m_negativeA_ok = false
Flag indicating whether negative A values are permitted.
double m_rc_low = NAN
Evaluated reaction rate in the low-pressure limit.
double m_rc_high = NAN
Evaluated reaction rate in the high-pressure limit.
vector_fp m_work
Work vector.
Protected Attributes inherited from ReactionRate
AnyMap m_input
Input data used for specific models.
size_t m_rate_index = npos
Index of reaction rate within kinetics evaluator.
bool m_valid = false
Flag indicating whether reaction rate is set up correctly.
bool m_composition_dependent_rate = false
Flag indicating composition dependent rate.
Units m_conversion_units {0.}
Units of the leading term in the reaction rate expression.
Additional Inherited Members
virtual void getParameters (AnyMap &node) const
Get parameters.
Detailed Description
Base class for falloff rate calculators.
Each instance of a subclass of FalloffRate calculates the falloff reaction rate based on specific implementations of the falloff function.
Definition at line 80 of file Falloff.h.
Constructor & Destructor Documentation
FalloffRate()
FalloffRate (const AnyMap & node, const UnitStack & rate_units = {})
Definition at line 81 of file Falloff.cpp.
Member Function Documentation
init()
void init (const vector_fp & c)
Initialize.
Must be called before any other method is invoked.
Parameters
c Vector of coefficients of the parameterization. The number and meaning of these coefficients is subclass-dependent.
Deprecated:
To be removed after Cantera 3.0; superseded by setFalloffCoeffs()
Definition at line 87 of file Falloff.cpp.
References FalloffRate::setFalloffCoeffs(), and Cantera::warn_deprecated().
setFalloffCoeffs()
void setFalloffCoeffs (const vector_fp & c) virtual
Set coefficients of the falloff parameterization.
Parameters
c Vector of coefficients of the parameterization. The number and meaning of these coefficients is subclass-dependent.
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 120 of file Falloff.cpp.
References ReactionRate::m_input, ReactionRate::m_valid, and AnyMap::size().
Referenced by FalloffRate::init().
getFalloffCoeffs()
void getFalloffCoeffs (vector_fp & c) const virtual
Retrieve coefficients of the falloff parameterization.
Parameters
c Vector of coefficients of the parameterization. The number and meaning of these coefficients is subclass-dependent.
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 130 of file Falloff.cpp.
updateTemp()
virtual void updateTemp (double T, double * work) const inline virtual
Update the temperature-dependent portions of the falloff function, if any, and store them in the 'work' array.
If not overloaded, the default behavior is to do nothing.
Parameters
T Temperature [K].
work storage space for intermediate results.
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 120 of file Falloff.h.
Referenced by FalloffRate::evalF(), and FalloffRate::evalFromStruct().
F()
virtual double F (double pr, const double * work) const inline virtual
The falloff function.
This is defined so that the rate coefficient is
\[ k = F(Pr)\frac{Pr}{1 + Pr}. \]
Here \(Pr \) is the reduced pressure, defined by
\[ Pr = \frac{k_0 [M]}{k_\infty}. \]
Parameters
pr reduced pressure (dimensionless).
work array of size workSize() containing cached temperature-dependent intermediate results from a prior call to updateTemp.
Returns
the value of the falloff function \(F \) defined above
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 139 of file Falloff.h.
Referenced by FalloffRate::evalF(), and FalloffRate::evalFromStruct().
evalF()
double evalF (double T, double conc3b) inline
Evaluate falloff function at current conditions.
Definition at line 144 of file Falloff.h.
References ArrheniusRate::evalRate(), FalloffRate::F(), FalloffRate::m_highRate, FalloffRate::m_lowRate, FalloffRate::m_rc_high, FalloffRate::m_rc_low, FalloffRate::m_work, Cantera::SmallNumber, and FalloffRate::updateTemp().
workSize()
virtual size_t workSize () const inline virtual
The size of the work array required.
Deprecated:
To be removed after Cantera 3.0; unused.
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 158 of file Falloff.h.
References Cantera::warn_deprecated().
type()
virtual const std::string type () const inline override virtual
String identifying reaction rate specialization.
Implements ReactionRate.
Definition at line 164 of file Falloff.h.
References FalloffRate::m_chemicallyActivated.
nParameters()
virtual size_t nParameters () const inline virtual
Returns the number of parameters used by this parameterization.
The values of these parameters can be obtained from getParameters().
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 173 of file Falloff.h.
setParameters()
void setParameters (const AnyMap & node, const UnitStack & units) override virtual
Set parameters.
Parameters
node AnyMap object containing reaction rate specification
units unit definitions specific to rate information
Reimplemented from ReactionRate.
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 135 of file Falloff.cpp.
References AnyMap::empty(), AnyMap::getBool(), AnyMap::hasKey(), UnitStack::join(), FalloffRate::m_chemicallyActivated, FalloffRate::m_highRate, FalloffRate::m_lowRate, FalloffRate::m_negativeA_ok, ArrheniusBase::setAllowNegativePreExponentialFactor(), ReactionRate::setParameters(), UnitStack::size(), and AnyMap::units().
Referenced by TroeRate::setParameters(), SriRate::setParameters(), and TsangRate::setParameters().
getParameters() [1/2]
virtual void getParameters (double * params) const inline virtual
Get the values of the parameters for this object.
params must be an array of at least nParameters() elements.
Deprecated:
To be removed after Cantera 3.0; superseded by getFalloffCoeffs()
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 185 of file Falloff.h.
References Cantera::warn_deprecated().
Referenced by TroeRate::getParameters(), SriRate::getParameters(), and TsangRate::getParameters().
getParameters() [2/2]
void getParameters (AnyMap & node) const override virtual
Get parameters.
Parameters
node AnyMap containing rate information Store the parameters of a ReactionRate needed to reconstruct an identical object. Does not include user-defined fields available in the m_input map.
Reimplemented from ReactionRate.
Reimplemented in TroeRate, SriRate, and TsangRate.
Definition at line 168 of file Falloff.cpp.
References AnyMap::clear(), AnyMap::empty(), ArrheniusBase::getRateParameters(), FalloffRate::m_highRate, FalloffRate::m_lowRate, and FalloffRate::m_negativeA_ok.
evalFromStruct()
double evalFromStruct (const FalloffData & shared_data) inline
Evaluate reaction rate.
Parameters
shared_data data shared by all reactions of a given type
Definition at line 194 of file Falloff.h.
References FalloffData::conc_3b, ArrheniusRate::evalRate(), FalloffRate::F(), ReactionData::logT, FalloffRate::m_chemicallyActivated, FalloffRate::m_highRate, FalloffRate::m_lowRate, ReactionRate::m_rate_index, FalloffRate::m_rc_high, FalloffRate::m_rc_low, FalloffRate::m_work, FalloffData::ready, ReactionData::recipT, Cantera::SmallNumber, ReactionData::temperature, and FalloffRate::updateTemp().
check()
void check (const std::string & equation) override virtual
Check basic syntax and settings of reaction rate expression.
Reimplemented from ReactionRate.
Definition at line 185 of file Falloff.cpp.
References ArrheniusBase::check(), FalloffRate::m_highRate, ReactionRate::m_input, FalloffRate::m_lowRate, ArrheniusBase::preExponentialFactor(), and ReactionRate::valid().
validate()
void validate (const std::string & equation, const Kinetics & kin) override virtual
Validate the reaction rate expression.
Reimplemented from ReactionRate.
Definition at line 200 of file Falloff.cpp.
References CanteraError::getMessage(), FalloffRate::m_highRate, ReactionRate::m_input, FalloffRate::m_lowRate, and ArrheniusBase::validate().
allowNegativePreExponentialFactor()
bool allowNegativePreExponentialFactor () const inline
Get flag indicating whether negative A values are permitted.
Definition at line 222 of file Falloff.h.
References FalloffRate::m_negativeA_ok.
setAllowNegativePreExponentialFactor()
void setAllowNegativePreExponentialFactor (bool value) inline
Set flag indicating whether negative A values are permitted.
Definition at line 227 of file Falloff.h.
References FalloffRate::m_negativeA_ok.
chemicallyActivated()
bool chemicallyActivated () const inline
Get flag indicating whether reaction is chemically activated.
Definition at line 232 of file Falloff.h.
References FalloffRate::m_chemicallyActivated.
setChemicallyActivated()
void setChemicallyActivated (bool activated) inline
Set flag indicating whether reaction is chemically activated.
Definition at line 237 of file Falloff.h.
References FalloffRate::m_chemicallyActivated.
lowRate()
ArrheniusRate & lowRate () inline
Get reaction rate in the low-pressure limit.
Definition at line 242 of file Falloff.h.
References FalloffRate::m_lowRate.
setLowRate()
void setLowRate (const ArrheniusRate & low)
Set reaction rate in the low-pressure limit.
Definition at line 94 of file Falloff.cpp.
References ArrheniusBase::check(), AnyMap::getString(), FalloffRate::m_highRate, ReactionRate::m_input, FalloffRate::m_lowRate, FalloffRate::m_negativeA_ok, ArrheniusBase::preExponentialFactor(), and ArrheniusBase::setAllowNegativePreExponentialFactor().
highRate()
ArrheniusRate & highRate () inline
Get reaction rate in the high-pressure limit.
Definition at line 250 of file Falloff.h.
References FalloffRate::m_highRate.
setHighRate()
void setHighRate (const ArrheniusRate & high)
Set reaction rate in the high-pressure limit.
Definition at line 107 of file Falloff.cpp.
References ArrheniusBase::check(), AnyMap::getString(), FalloffRate::m_highRate, ReactionRate::m_input, FalloffRate::m_lowRate, FalloffRate::m_negativeA_ok, ArrheniusBase::preExponentialFactor(), and ArrheniusBase::setAllowNegativePreExponentialFactor().
Member Data Documentation
m_lowRate
ArrheniusRate m_lowRate protected
The reaction rate in the low-pressure limit.
Definition at line 258 of file Falloff.h.
Referenced by FalloffRate::check(), FalloffRate::evalF(), FalloffRate::evalFromStruct(), FalloffRate::getParameters(), FalloffRate::lowRate(), FalloffRate::setHighRate(), FalloffRate::setLowRate(), FalloffRate::setParameters(), and FalloffRate::validate().
m_highRate
ArrheniusRate m_highRate protected
The reaction rate in the high-pressure limit.
Definition at line 259 of file Falloff.h.
Referenced by FalloffRate::check(), FalloffRate::evalF(), FalloffRate::evalFromStruct(), FalloffRate::getParameters(), FalloffRate::highRate(), FalloffRate::setHighRate(), FalloffRate::setLowRate(), FalloffRate::setParameters(), and FalloffRate::validate().
m_chemicallyActivated
bool m_chemicallyActivated = false protected
Flag labeling reaction as chemically activated.
Definition at line 262 of file Falloff.h.
Referenced by FalloffRate::chemicallyActivated(), FalloffRate::evalFromStruct(), FalloffRate::setChemicallyActivated(), FalloffRate::setParameters(), and FalloffRate::type().
m_negativeA_ok
bool m_negativeA_ok = false protected
Flag indicating whether negative A values are permitted.
Definition at line 264 of file Falloff.h.
Referenced by FalloffRate::allowNegativePreExponentialFactor(), FalloffRate::getParameters(), FalloffRate::setAllowNegativePreExponentialFactor(), FalloffRate::setHighRate(), FalloffRate::setLowRate(), and FalloffRate::setParameters().
m_rc_low
double m_rc_low = NAN protected
Evaluated reaction rate in the low-pressure limit.
Definition at line 266 of file Falloff.h.
Referenced by FalloffRate::evalF(), and FalloffRate::evalFromStruct().
m_rc_high
double m_rc_high = NAN protected
Evaluated reaction rate in the high-pressure limit.
Definition at line 267 of file Falloff.h.
Referenced by FalloffRate::evalF(), and FalloffRate::evalFromStruct().
m_work
vector_fp m_work protected
Work vector.
Definition at line 268 of file Falloff.h.
Referenced by FalloffRate::evalF(), FalloffRate::evalFromStruct(), SriRate::SriRate(), TroeRate::TroeRate(), and TsangRate::TsangRate().
The documentation for this class was generated from the following files:
Falloff.h
Falloff.cpp