var files_dup =
[
    [ "AdaptivePreconditioner.cpp", "d3/d22/AdaptivePreconditioner_8cpp.html", null ],
    [ "AdaptivePreconditioner.h", "d2/d15/AdaptivePreconditioner_8h.html", [
      [ "AdaptivePreconditioner", "d3/dd2/classCantera_1_1AdaptivePreconditioner.html", "d3/dd2/classCantera_1_1AdaptivePreconditioner" ]
    ] ],
    [ "AnyMap.cpp", "de/dfc/AnyMap_8cpp.html", "de/dfc/AnyMap_8cpp" ],
    [ "AnyMap.h", "dd/d2a/AnyMap_8h.html", "dd/d2a/AnyMap_8h" ],
    [ "AnyMap.inl.h", "da/d4c/AnyMap_8inl_8h.html", "da/d4c/AnyMap_8inl_8h" ],
    [ "application.cpp", "df/d7b/application_8cpp.html", "df/d7b/application_8cpp" ],
    [ "application.h", "db/d32/application_8h.html", [
      [ "Messages", "d8/df8/classCantera_1_1Application_1_1Messages.html", "d8/df8/classCantera_1_1Application_1_1Messages" ],
      [ "ThreadMessages", "d9/d14/classCantera_1_1Application_1_1ThreadMessages.html", "d9/d14/classCantera_1_1Application_1_1ThreadMessages" ]
    ] ],
    [ "Array.cpp", "d1/d32/Array_8cpp.html", "d1/d32/Array_8cpp" ],
    [ "Array.h", "df/dd0/Array_8h.html", "df/dd0/Array_8h" ],
    [ "Arrhenius.cpp", "d8/d14/Arrhenius_8cpp.html", null ],
    [ "Arrhenius.h", "d6/dd6/Arrhenius_8h.html", [
      [ "ArrheniusData", "dd/d0f/structCantera_1_1ArrheniusData.html", "dd/d0f/structCantera_1_1ArrheniusData" ]
    ] ],
    [ "BandMatrix.cpp", "df/d79/BandMatrix_8cpp.html", "df/d79/BandMatrix_8cpp" ],
    [ "BandMatrix.h", "de/d7e/BandMatrix_8h.html", "de/d7e/BandMatrix_8h" ],
    [ "BasisOptimize.cpp", "dc/d89/BasisOptimize_8cpp.html", "dc/d89/BasisOptimize_8cpp" ],
    [ "BinarySolutionTabulatedThermo.cpp", "d4/d20/BinarySolutionTabulatedThermo_8cpp.html", null ],
    [ "BinarySolutionTabulatedThermo.h", "d9/d64/BinarySolutionTabulatedThermo_8h.html", null ],
    [ "BlowersMaselRate.cpp", "d4/d81/BlowersMaselRate_8cpp.html", null ],
    [ "BlowersMaselRate.h", "da/dab/BlowersMaselRate_8h.html", [
      [ "BlowersMaselData", "da/d62/structCantera_1_1BlowersMaselData.html", "da/d62/structCantera_1_1BlowersMaselData" ]
    ] ],
    [ "Boundary1D.cpp", "de/d16/Boundary1D_8cpp.html", null ],
    [ "Boundary1D.h", "dc/d7c/Boundary1D_8h.html", "dc/d7c/Boundary1D_8h" ],
    [ "BulkKinetics.cpp", "df/d7d/BulkKinetics_8cpp_source.html", null ],
    [ "BulkKinetics.h", "d2/d78/BulkKinetics_8h.html", null ],
    [ "cantera.bib", "d6/d96/cantera_8bib_source.html", null ],
    [ "CarbonDioxide.cpp", "d0/d64/CarbonDioxide_8cpp.html", "d0/d64/CarbonDioxide_8cpp" ],
    [ "CarbonDioxide.h", "d3/dc4/CarbonDioxide_8h.html", [
      [ "CarbonDioxide", "de/d67/classtpx_1_1CarbonDioxide.html", "de/d67/classtpx_1_1CarbonDioxide" ]
    ] ],
    [ "ChebyshevRate.cpp", "df/df5/ChebyshevRate_8cpp.html", null ],
    [ "ChebyshevRate.h", "d2/d05/ChebyshevRate_8h.html", [
      [ "ChebyshevData", "d4/df5/structCantera_1_1ChebyshevData.html", "d4/df5/structCantera_1_1ChebyshevData" ]
    ] ],
    [ "checkFinite.cpp", "db/d20/checkFinite_8cpp.html", "db/d20/checkFinite_8cpp" ],
    [ "ChemEquil.cpp", "df/df0/ChemEquil_8cpp.html", "df/df0/ChemEquil_8cpp" ],
    [ "ChemEquil.h", "d4/dd4/ChemEquil_8h.html", "d4/dd4/ChemEquil_8h" ],
    [ "clib_defs.h", "dd/d7b/clib__defs_8h.html", "dd/d7b/clib__defs_8h" ],
    [ "clockWC.cpp", "d1/d60/clockWC_8cpp.html", null ],
    [ "clockWC.h", "d1/d88/clockWC_8h.html", null ],
    [ "config.h", "db/d16/config_8h_source.html", null ],
    [ "ConstCpPoly.cpp", "df/d8c/ConstCpPoly_8cpp.html", null ],
    [ "ConstCpPoly.h", "dc/d69/ConstCpPoly_8h.html", null ],
    [ "ConstPressureMoleReactor.cpp", "d2/dcd/ConstPressureMoleReactor_8cpp.html", null ],
    [ "ConstPressureMoleReactor.h", "d5/dd1/ConstPressureMoleReactor_8h.html", null ],
    [ "ConstPressureReactor.cpp", "d7/de6/ConstPressureReactor_8cpp.html", null ],
    [ "ConstPressureReactor.h", "d5/dd6/ConstPressureReactor_8h.html", null ],
    [ "core.h", "d5/dc4/core_8h.html", null ],
    [ "CoverageDependentSurfPhase.cpp", "db/d2d/CoverageDependentSurfPhase_8cpp.html", null ],
    [ "CoverageDependentSurfPhase.h", "db/dda/CoverageDependentSurfPhase_8h.html", [
      [ "CoverageDependentSurfPhase", "db/d25/classCantera_1_1CoverageDependentSurfPhase.html", "db/d25/classCantera_1_1CoverageDependentSurfPhase" ],
      [ "PolynomialDependency", "df/d43/structCantera_1_1CoverageDependentSurfPhase_1_1PolynomialDependency.html", "df/d43/structCantera_1_1CoverageDependentSurfPhase_1_1PolynomialDependency" ],
      [ "InterpolativeDependency", "de/ddc/structCantera_1_1CoverageDependentSurfPhase_1_1InterpolativeDependency.html", "de/ddc/structCantera_1_1CoverageDependentSurfPhase_1_1InterpolativeDependency" ],
      [ "HeatCapacityDependency", "df/db9/structCantera_1_1CoverageDependentSurfPhase_1_1HeatCapacityDependency.html", "df/db9/structCantera_1_1CoverageDependentSurfPhase_1_1HeatCapacityDependency" ]
    ] ],
    [ "ct.h", "d3/dc1/ct_8h.html", "d3/dc1/ct_8h" ],
    [ "ct_defs.h", "d9/ddc/ct__defs_8h.html", "d9/ddc/ct__defs_8h" ],
    [ "ctexceptions.cpp", "d8/d96/ctexceptions_8cpp.html", "d8/d96/ctexceptions_8cpp" ],
    [ "ctexceptions.h", "db/d98/ctexceptions_8h.html", "db/d98/ctexceptions_8h" ],
    [ "ctfunc.h", "df/dd5/ctfunc_8h.html", "df/dd5/ctfunc_8h" ],
    [ "ctlapack.h", "df/d55/ctlapack_8h.html", "df/d55/ctlapack_8h" ],
    [ "ctmatlab.h", "dd/d93/ctmatlab_8h_source.html", null ],
    [ "ctmultiphase.h", "de/db9/ctmultiphase_8h.html", "de/db9/ctmultiphase_8h" ],
    [ "ctonedim.h", "d0/db6/ctonedim_8h.html", "d0/db6/ctonedim_8h" ],
    [ "ctreactor.h", "df/d63/ctreactor_8h.html", "df/d63/ctreactor_8h" ],
    [ "ctrpath.h", "db/dcd/ctrpath_8h.html", "db/dcd/ctrpath_8h" ],
    [ "ctsurf.h", "d6/dd6/ctsurf_8h.html", "d6/dd6/ctsurf_8h" ],
    [ "Custom.cpp", "d5/dc4/Custom_8cpp.html", null ],
    [ "Custom.h", "de/d8f/Custom_8h.html", null ],
    [ "CVodesIntegrator.cpp", "da/d4f/CVodesIntegrator_8cpp.html", "da/d4f/CVodesIntegrator_8cpp" ],
    [ "CVodesIntegrator.h", "d7/dd9/CVodesIntegrator_8h.html", [
      [ "CVodesIntegrator", "d9/d6b/classCantera_1_1CVodesIntegrator.html", "d9/d6b/classCantera_1_1CVodesIntegrator" ]
    ] ],
    [ "DebyeHuckel.cpp", "dc/ddc/DebyeHuckel_8cpp.html", "dc/ddc/DebyeHuckel_8cpp" ],
    [ "DebyeHuckel.h", "de/dd9/DebyeHuckel_8h.html", "de/dd9/DebyeHuckel_8h" ],
    [ "Delegator.h", "d8/d78/Delegator_8h.html", [
      [ "Delegator", "d9/dc6/classCantera_1_1Delegator.html", "d9/dc6/classCantera_1_1Delegator" ]
    ] ],
    [ "DenseMatrix.cpp", "d8/db7/DenseMatrix_8cpp.html", "d8/db7/DenseMatrix_8cpp" ],
    [ "DenseMatrix.h", "d1/df7/DenseMatrix_8h.html", "d1/df7/DenseMatrix_8h" ],
    [ "Domain1D.cpp", "dc/d9c/Domain1D_8cpp.html", null ],
    [ "Domain1D.h", "db/dce/Domain1D_8h.html", "db/dce/Domain1D_8h" ],
    [ "DomainFactory.cpp", "d9/db4/DomainFactory_8cpp.html", null ],
    [ "DomainFactory.h", "db/d68/DomainFactory_8h.html", "db/d68/DomainFactory_8h" ],
    [ "DustyGasTransport.cpp", "d9/de2/DustyGasTransport_8cpp.html", null ],
    [ "DustyGasTransport.h", "d7/dca/DustyGasTransport_8h.html", null ],
    [ "EdgeKinetics.h", "d9/d4b/EdgeKinetics_8h.html", null ],
    [ "EdgePhase.h", "d6/d72/EdgePhase_8h.html", null ],
    [ "eigen_dense.h", "dc/d2e/eigen__dense_8h_source.html", null ],
    [ "eigen_sparse.h", "d9/d42/eigen__sparse_8h_source.html", null ],
    [ "electrolytes.h", "de/d07/electrolytes_8h.html", "de/d07/electrolytes_8h" ],
    [ "Elements.cpp", "de/dfb/Elements_8cpp.html", "de/dfb/Elements_8cpp" ],
    [ "Elements.h", "d9/dda/Elements_8h.html", "d9/dda/Elements_8h" ],
    [ "ExtensionManager.cpp", "dd/d3d/ExtensionManager_8cpp.html", null ],
    [ "ExtensionManager.h", "d8/d0d/ExtensionManager_8h.html", [
      [ "ExternalHandle", "d4/d60/classCantera_1_1ExternalHandle.html", "d4/d60/classCantera_1_1ExternalHandle" ],
      [ "ExtensionManager", "d8/dcb/classCantera_1_1ExtensionManager.html", "d8/dcb/classCantera_1_1ExtensionManager" ]
    ] ],
    [ "ExtensionManagerFactory.cpp", "d6/d69/ExtensionManagerFactory_8cpp.html", null ],
    [ "ExtensionManagerFactory.h", "dd/d4e/ExtensionManagerFactory_8h.html", [
      [ "ExtensionManagerFactory", "d7/d2a/classCantera_1_1ExtensionManagerFactory.html", "d7/d2a/classCantera_1_1ExtensionManagerFactory" ]
    ] ],
    [ "ExternalLogger.h", "d7/db4/ExternalLogger_8h_source.html", null ],
    [ "FactoryBase.h", "d6/dd5/FactoryBase_8h.html", [
      [ "FactoryBase", "da/dac/classCantera_1_1FactoryBase.html", "da/dac/classCantera_1_1FactoryBase" ],
      [ "Factory", "dc/dd4/classCantera_1_1Factory.html", "dc/dd4/classCantera_1_1Factory" ]
    ] ],
    [ "Falloff.cpp", "d7/d8a/Falloff_8cpp.html", null ],
    [ "Falloff.h", "de/d72/Falloff_8h_source.html", null ],
    [ "flowControllers.cpp", "d6/d94/flowControllers_8cpp.html", null ],
    [ "flowControllers.h", "de/d80/flowControllers_8h.html", null ],
    [ "FlowDevice.cpp", "dc/d8f/FlowDevice_8cpp.html", null ],
    [ "FlowDevice.h", "d5/dff/FlowDevice_8h.html", null ],
    [ "FlowDeviceFactory.cpp", "d8/d77/FlowDeviceFactory_8cpp.html", "d8/d77/FlowDeviceFactory_8cpp" ],
    [ "FlowDeviceFactory.h", "d5/d6c/FlowDeviceFactory_8h.html", "d5/d6c/FlowDeviceFactory_8h" ],
    [ "FlowReactor.cpp", "dd/d8f/FlowReactor_8cpp.html", null ],
    [ "FlowReactor.h", "d7/d40/FlowReactor_8h.html", null ],
    [ "fmt.h", "db/def/fmt_8h.html", "db/def/fmt_8h" ],
    [ "Func1.cpp", "d1/d91/Func1_8cpp.html", "d1/d91/Func1_8cpp" ],
    [ "Func1.h", "d2/d9e/Func1_8h.html", "d2/d9e/Func1_8h" ],
    [ "Func1Factory.cpp", "d0/d5a/Func1Factory_8cpp.html", "d0/d5a/Func1Factory_8cpp" ],
    [ "Func1Factory.h", "df/db9/Func1Factory_8h.html", "df/db9/Func1Factory_8h" ],
    [ "FuncEval.cpp", "d3/d10/FuncEval_8cpp_source.html", null ],
    [ "FuncEval.h", "da/d37/FuncEval_8h.html", null ],
    [ "funcs.cpp", "d9/dc7/funcs_8cpp.html", "d9/dc7/funcs_8cpp" ],
    [ "funcs.h", "d1/d96/funcs_8h.html", "d1/d96/funcs_8h" ],
    [ "funcWrapper.h", "d4/d0c/funcWrapper_8h_source.html", null ],
    [ "GasKinetics.h", "db/dac/GasKinetics_8h.html", null ],
    [ "GasTransport.cpp", "d5/de4/GasTransport_8cpp.html", "d5/de4/GasTransport_8cpp" ],
    [ "GasTransport.h", "d1/d2e/GasTransport_8h.html", null ],
    [ "GeneralMatrix.h", "da/d15/GeneralMatrix_8h.html", null ],
    [ "GibbsExcessVPSSTP.cpp", "d1/d54/GibbsExcessVPSSTP_8cpp.html", null ],
    [ "GibbsExcessVPSSTP.h", "d6/d88/GibbsExcessVPSSTP_8h.html", [
      [ "GibbsExcessVPSSTP", "d8/d1a/classCantera_1_1GibbsExcessVPSSTP.html", "d8/d1a/classCantera_1_1GibbsExcessVPSSTP" ]
    ] ],
    [ "global.cpp", "db/d7d/global_8cpp.html", "db/d7d/global_8cpp" ],
    [ "global.h", "d2/d49/global_8h.html", "d2/d49/global_8h" ],
    [ "Group.cpp", "de/d74/Group_8cpp.html", "de/d74/Group_8cpp" ],
    [ "Group.h", "de/d3d/Group_8h.html", [
      [ "Group", "d6/d41/classCantera_1_1Group.html", "d6/d41/classCantera_1_1Group" ]
    ] ],
    [ "gtest_utils.h", "d6/dc2/gtest__utils_8h_source.html", null ],
    [ "Heptane.cpp", "d4/d44/Heptane_8cpp.html", "d4/d44/Heptane_8cpp" ],
    [ "Heptane.h", "d9/d76/Heptane_8h.html", [
      [ "Heptane", "df/d0a/classtpx_1_1Heptane.html", "df/d0a/classtpx_1_1Heptane" ]
    ] ],
    [ "HFC134a.cpp", "d8/da7/HFC134a_8cpp.html", "d8/da7/HFC134a_8cpp" ],
    [ "HFC134a.h", "db/d33/HFC134a_8h.html", [
      [ "HFC134a", "df/df3/classtpx_1_1HFC134a.html", "df/df3/classtpx_1_1HFC134a" ]
    ] ],
    [ "HighPressureGasTransport.cpp", "d2/d89/HighPressureGasTransport_8cpp.html", null ],
    [ "HighPressureGasTransport.h", "d0/de4/HighPressureGasTransport_8h.html", null ],
    [ "HMWSoln.cpp", "d0/d0e/HMWSoln_8cpp.html", "d0/d0e/HMWSoln_8cpp" ],
    [ "HMWSoln.h", "d0/d16/HMWSoln_8h.html", "d0/d16/HMWSoln_8h" ],
    [ "Hydrogen.cpp", "de/d64/Hydrogen_8cpp.html", "de/d64/Hydrogen_8cpp" ],
    [ "Hydrogen.h", "dd/dbf/Hydrogen_8h.html", [
      [ "hydrogen", "d8/d7e/classtpx_1_1hydrogen.html", "d8/d7e/classtpx_1_1hydrogen" ]
    ] ],
    [ "IdasIntegrator.cpp", "d4/d7c/IdasIntegrator_8cpp.html", "d4/d7c/IdasIntegrator_8cpp" ],
    [ "IdasIntegrator.h", "d0/dbd/IdasIntegrator_8h.html", [
      [ "IdasIntegrator", "d6/dae/classCantera_1_1IdasIntegrator.html", "d6/dae/classCantera_1_1IdasIntegrator" ]
    ] ],
    [ "IdealGasConstPressureMoleReactor.cpp", "db/dbf/IdealGasConstPressureMoleReactor_8cpp.html", null ],
    [ "IdealGasConstPressureMoleReactor.h", "d6/dfa/IdealGasConstPressureMoleReactor_8h.html", null ],
    [ "IdealGasConstPressureReactor.cpp", "dc/de4/IdealGasConstPressureReactor_8cpp_source.html", null ],
    [ "IdealGasConstPressureReactor.h", "dd/d76/IdealGasConstPressureReactor_8h_source.html", null ],
    [ "IdealGasMoleReactor.cpp", "d3/d19/IdealGasMoleReactor_8cpp.html", null ],
    [ "IdealGasMoleReactor.h", "d6/db3/IdealGasMoleReactor_8h.html", null ],
    [ "IdealGasPhase.cpp", "d7/dd4/IdealGasPhase_8cpp.html", null ],
    [ "IdealGasPhase.h", "de/dbd/IdealGasPhase_8h.html", null ],
    [ "IdealGasReactor.cpp", "d2/d80/IdealGasReactor_8cpp.html", null ],
    [ "IdealGasReactor.h", "db/d07/IdealGasReactor_8h.html", null ],
    [ "IdealMolalSoln.cpp", "d3/d32/IdealMolalSoln_8cpp.html", null ],
    [ "IdealMolalSoln.h", "d5/db6/IdealMolalSoln_8h.html", null ],
    [ "IdealSolidSolnPhase.cpp", "de/d05/IdealSolidSolnPhase_8cpp.html", null ],
    [ "IdealSolidSolnPhase.h", "d9/d28/IdealSolidSolnPhase_8h.html", null ],
    [ "IdealSolnGasVPSS.cpp", "d6/d7f/IdealSolnGasVPSS_8cpp.html", null ],
    [ "IdealSolnGasVPSS.h", "db/d88/IdealSolnGasVPSS_8h.html", null ],
    [ "ImplicitSurfChem.cpp", "d7/d3f/ImplicitSurfChem_8cpp.html", null ],
    [ "ImplicitSurfChem.h", "da/d1f/ImplicitSurfChem_8h.html", null ],
    [ "Integrator.h", "d8/d97/Integrator_8h.html", "d8/d97/Integrator_8h" ],
    [ "Integrators.cpp", "de/dfe/Integrators_8cpp.html", "de/dfe/Integrators_8cpp" ],
    [ "Interface.cpp", "de/dbe/Interface_8cpp.html", "de/dbe/Interface_8cpp" ],
    [ "Interface.h", "d7/d91/Interface_8h.html", "d7/d91/Interface_8h" ],
    [ "InterfaceKinetics.cpp", "d3/db3/InterfaceKinetics_8cpp.html", null ],
    [ "InterfaceKinetics.h", "d7/d0d/InterfaceKinetics_8h.html", null ],
    [ "InterfaceRate.cpp", "d8/dc2/InterfaceRate_8cpp.html", null ],
    [ "InterfaceRate.h", "df/d45/InterfaceRate_8h.html", "df/d45/InterfaceRate_8h" ],
    [ "IonFlow.cpp", "d4/d57/IonFlow_8cpp.html", null ],
    [ "IonFlow.h", "d7/d4b/IonFlow_8h.html", null ],
    [ "IonGasTransport.cpp", "d2/dc5/IonGasTransport_8cpp.html", null ],
    [ "IonGasTransport.h", "d8/d57/IonGasTransport_8h.html", null ],
    [ "IonsFromNeutralVPSSTP.cpp", "db/dcc/IonsFromNeutralVPSSTP_8cpp.html", "db/dcc/IonsFromNeutralVPSSTP_8cpp" ],
    [ "IonsFromNeutralVPSSTP.h", "de/dd7/IonsFromNeutralVPSSTP_8h.html", "de/dd7/IonsFromNeutralVPSSTP_8h" ],
    [ "Kinetics.cpp", "d7/ddb/Kinetics_8cpp.html", null ],
    [ "Kinetics.h", "d5/db4/Kinetics_8h.html", null ],
    [ "kinetics.h", "d3/d85/kinetics_8h.html", null ],
    [ "kinetics_utils.h", "d4/d89/kinetics__utils_8h_source.html", null ],
    [ "KineticsFactory.cpp", "d3/df8/KineticsFactory_8cpp.html", "d3/df8/KineticsFactory_8cpp" ],
    [ "KineticsFactory.h", "df/d76/KineticsFactory_8h.html", "df/d76/KineticsFactory_8h" ],
    [ "LatticePhase.cpp", "da/d5f/LatticePhase_8cpp.html", null ],
    [ "LatticePhase.h", "d4/d0d/LatticePhase_8h.html", null ],
    [ "LatticeSolidPhase.cpp", "df/dde/LatticeSolidPhase_8cpp.html", null ],
    [ "LatticeSolidPhase.h", "da/dd3/LatticeSolidPhase_8h.html", [
      [ "LatticeSolidPhase", "de/de1/classCantera_1_1LatticeSolidPhase.html", "de/de1/classCantera_1_1LatticeSolidPhase" ]
    ] ],
    [ "logger.h", "d1/d8c/logger_8h.html", null ],
    [ "MargulesVPSSTP.cpp", "dd/d35/MargulesVPSSTP_8cpp.html", null ],
    [ "MargulesVPSSTP.h", "d9/db4/MargulesVPSSTP_8h.html", null ],
    [ "MaskellSolidSolnPhase.cpp", "d0/d82/MaskellSolidSolnPhase_8cpp.html", "d0/d82/MaskellSolidSolnPhase_8cpp" ],
    [ "MaskellSolidSolnPhase.h", "d4/d33/MaskellSolidSolnPhase_8h.html", null ],
    [ "MetalPhase.h", "db/df0/MetalPhase_8h.html", null ],
    [ "Methane.cpp", "d5/d5e/Methane_8cpp.html", "d5/d5e/Methane_8cpp" ],
    [ "Methane.h", "df/d25/Methane_8h.html", [
      [ "methane", "dc/d51/classtpx_1_1methane.html", "dc/d51/classtpx_1_1methane" ]
    ] ],
    [ "MixTransport.cpp", "dd/d16/MixTransport_8cpp.html", null ],
    [ "MixTransport.h", "d5/d57/MixTransport_8h.html", null ],
    [ "MixtureFugacityTP.cpp", "db/d86/MixtureFugacityTP_8cpp.html", null ],
    [ "MixtureFugacityTP.h", "d1/da4/MixtureFugacityTP_8h.html", "d1/da4/MixtureFugacityTP_8h" ],
    [ "MMCollisionInt.cpp", "df/d27/MMCollisionInt_8cpp.html", "df/d27/MMCollisionInt_8cpp" ],
    [ "MMCollisionInt.h", "df/df6/MMCollisionInt_8h.html", null ],
    [ "MolalityVPSSTP.cpp", "db/dd7/MolalityVPSSTP_8cpp.html", null ],
    [ "MolalityVPSSTP.h", "d1/d24/MolalityVPSSTP_8h.html", "d1/d24/MolalityVPSSTP_8h" ],
    [ "MoleReactor.cpp", "db/d2c/MoleReactor_8cpp.html", null ],
    [ "MoleReactor.h", "d2/db6/MoleReactor_8h.html", null ],
    [ "Mu0Poly.cpp", "df/d58/Mu0Poly_8cpp.html", null ],
    [ "Mu0Poly.h", "d0/dbd/Mu0Poly_8h.html", null ],
    [ "MultiJac.cpp", "db/d3a/MultiJac_8cpp.html", null ],
    [ "MultiJac.h", "d5/d60/MultiJac_8h.html", null ],
    [ "MultiNewton.cpp", "d6/dc4/MultiNewton_8cpp.html", "d6/dc4/MultiNewton_8cpp" ],
    [ "MultiNewton.h", "d6/d1e/MultiNewton_8h.html", null ],
    [ "MultiPhase.cpp", "df/d2b/MultiPhase_8cpp.html", "df/d2b/MultiPhase_8cpp" ],
    [ "MultiPhase.h", "d4/d71/MultiPhase_8h.html", "d4/d71/MultiPhase_8h" ],
    [ "MultiPhaseEquil.cpp", "d1/dd3/MultiPhaseEquil_8cpp.html", null ],
    [ "MultiPhaseEquil.h", "d1/d66/MultiPhaseEquil_8h.html", null ],
    [ "MultiRate.h", "d6/d42/MultiRate_8h.html", null ],
    [ "MultiRateBase.h", "dd/d16/MultiRateBase_8h.html", null ],
    [ "MultiSpeciesThermo.cpp", "dd/de9/MultiSpeciesThermo_8cpp.html", null ],
    [ "MultiSpeciesThermo.h", "d6/d7a/MultiSpeciesThermo_8h.html", null ],
    [ "MultiTransport.cpp", "d2/d60/MultiTransport_8cpp.html", "d2/d60/MultiTransport_8cpp" ],
    [ "MultiTransport.h", "da/dd1/MultiTransport_8h.html", null ],
    [ "Nasa9Poly1.cpp", "d8/dee/Nasa9Poly1_8cpp.html", null ],
    [ "Nasa9Poly1.h", "df/df1/Nasa9Poly1_8h.html", null ],
    [ "Nasa9PolyMultiTempRegion.cpp", "d2/d49/Nasa9PolyMultiTempRegion_8cpp.html", null ],
    [ "Nasa9PolyMultiTempRegion.h", "d4/d07/Nasa9PolyMultiTempRegion_8h.html", null ],
    [ "NasaPoly1.h", "d2/d2a/NasaPoly1_8h.html", null ],
    [ "NasaPoly2.cpp", "d6/de1/NasaPoly2_8cpp_source.html", null ],
    [ "NasaPoly2.h", "dc/d53/NasaPoly2_8h.html", null ],
    [ "Nitrogen.cpp", "df/dc0/Nitrogen_8cpp.html", "df/dc0/Nitrogen_8cpp" ],
    [ "Nitrogen.h", "de/d5b/Nitrogen_8h.html", [
      [ "nitrogen", "d9/d26/classtpx_1_1nitrogen.html", "d9/d26/classtpx_1_1nitrogen" ]
    ] ],
    [ "NoExitLogger.h", "db/d3c/NoExitLogger_8h.html", null ],
    [ "OneDim.cpp", "dc/dcd/OneDim_8cpp.html", null ],
    [ "OneDim.h", "de/da1/OneDim_8h.html", null ],
    [ "onedim.h", "d4/d07/onedim_8h.html", null ],
    [ "Oxygen.cpp", "dd/d24/Oxygen_8cpp.html", "dd/d24/Oxygen_8cpp" ],
    [ "Oxygen.h", "d8/df3/Oxygen_8h.html", [
      [ "oxygen", "da/de8/classtpx_1_1oxygen.html", "da/de8/classtpx_1_1oxygen" ]
    ] ],
    [ "PDSS.cpp", "d3/d3c/PDSS_8cpp.html", null ],
    [ "PDSS.h", "d7/dfa/PDSS_8h.html", [
      [ "PDSS_Molar", "d5/d6a/classCantera_1_1PDSS__Molar.html", "d5/d6a/classCantera_1_1PDSS__Molar" ],
      [ "PDSS_Nondimensional", "df/d4c/classCantera_1_1PDSS__Nondimensional.html", "df/d4c/classCantera_1_1PDSS__Nondimensional" ]
    ] ],
    [ "PDSS_ConstVol.cpp", "da/d94/PDSS__ConstVol_8cpp.html", null ],
    [ "PDSS_ConstVol.h", "d1/d0f/PDSS__ConstVol_8h.html", null ],
    [ "PDSS_HKFT.cpp", "d1/d3f/PDSS__HKFT_8cpp.html", null ],
    [ "PDSS_HKFT.h", "db/df3/PDSS__HKFT_8h.html", null ],
    [ "PDSS_IdealGas.cpp", "d3/d44/PDSS__IdealGas_8cpp.html", null ],
    [ "PDSS_IdealGas.h", "de/dea/PDSS__IdealGas_8h.html", null ],
    [ "PDSS_IonsFromNeutral.cpp", "dc/dc2/PDSS__IonsFromNeutral_8cpp.html", null ],
    [ "PDSS_IonsFromNeutral.h", "de/df8/PDSS__IonsFromNeutral_8h.html", null ],
    [ "PDSS_SSVol.cpp", "d2/d42/PDSS__SSVol_8cpp.html", null ],
    [ "PDSS_SSVol.h", "d0/db8/PDSS__SSVol_8h.html", null ],
    [ "PDSS_Water.cpp", "d2/db8/PDSS__Water_8cpp.html", null ],
    [ "PDSS_Water.h", "d8/d6d/PDSS__Water_8h.html", null ],
    [ "PDSSFactory.cpp", "d0/d6d/PDSSFactory_8cpp.html", "d0/d6d/PDSSFactory_8cpp" ],
    [ "PDSSFactory.h", "db/d8c/PDSSFactory_8h.html", "db/d8c/PDSSFactory_8h" ],
    [ "PengRobinson.cpp", "db/db8/PengRobinson_8cpp.html", null ],
    [ "PengRobinson.h", "de/d01/PengRobinson_8h.html", null ],
    [ "Phase.cpp", "de/dd9/Phase_8cpp.html", null ],
    [ "Phase.h", "da/d84/Phase_8h.html", null ],
    [ "PlasmaPhase.cpp", "da/dc4/PlasmaPhase_8cpp.html", null ],
    [ "PlasmaPhase.h", "d6/ded/PlasmaPhase_8h.html", [
      [ "PlasmaPhase", "d5/dd7/classCantera_1_1PlasmaPhase.html", "d5/dd7/classCantera_1_1PlasmaPhase" ]
    ] ],
    [ "PlogRate.cpp", "d8/dcf/PlogRate_8cpp.html", null ],
    [ "PlogRate.h", "dd/d3a/PlogRate_8h.html", [
      [ "PlogData", "d5/d6e/structCantera_1_1PlogData.html", "d5/d6e/structCantera_1_1PlogData" ]
    ] ],
    [ "polyfit.cpp", "d0/de1/polyfit_8cpp.html", "d0/de1/polyfit_8cpp" ],
    [ "polyfit.h", "d7/dcd/polyfit_8h.html", "d7/dcd/polyfit_8h" ],
    [ "PreconditionerBase.h", "d7/ddf/PreconditionerBase_8h.html", "d7/ddf/PreconditionerBase_8h" ],
    [ "PreconditionerFactory.cpp", "dc/d3a/PreconditionerFactory_8cpp.html", "dc/d3a/PreconditionerFactory_8cpp" ],
    [ "PreconditionerFactory.h", "d8/d9a/PreconditionerFactory_8h.html", "d8/d9a/PreconditionerFactory_8h" ],
    [ "PureFluidPhase.cpp", "d8/d53/PureFluidPhase_8cpp.html", null ],
    [ "PureFluidPhase.h", "dd/d2d/PureFluidPhase_8h.html", null ],
    [ "PythonExtensionManager.h", "d2/d92/PythonExtensionManager_8h.html", [
      [ "PythonExtensionManager", "d3/d2f/classCantera_1_1PythonExtensionManager.html", "d3/d2f/classCantera_1_1PythonExtensionManager" ]
    ] ],
    [ "PythonHandle.h", "dd/d6c/PythonHandle_8h.html", [
      [ "PythonHandle", "d4/d17/classCantera_1_1PythonHandle.html", "d4/d17/classCantera_1_1PythonHandle" ]
    ] ],
    [ "Reaction.cpp", "d1/d9f/Reaction_8cpp.html", "d1/d9f/Reaction_8cpp" ],
    [ "Reaction.h", "d8/d5d/Reaction_8h.html", "d8/d5d/Reaction_8h" ],
    [ "ReactionData.h", "d6/d4a/ReactionData_8h.html", null ],
    [ "ReactionPath.cpp", "da/d26/ReactionPath_8cpp.html", "da/d26/ReactionPath_8cpp" ],
    [ "ReactionPath.h", "d2/df0/ReactionPath_8h.html", "d2/df0/ReactionPath_8h" ],
    [ "reactionpaths.h", "d8/df8/reactionpaths_8h_source.html", null ],
    [ "ReactionRate.h", "d8/db0/ReactionRate_8h.html", null ],
    [ "ReactionRateDelegator.cpp", "dd/d06/ReactionRateDelegator_8cpp.html", null ],
    [ "ReactionRateDelegator.h", "df/da5/ReactionRateDelegator_8h.html", [
      [ "ReactionDataDelegator", "d1/dfe/classCantera_1_1ReactionDataDelegator.html", "d1/dfe/classCantera_1_1ReactionDataDelegator" ]
    ] ],
    [ "ReactionRateFactory.cpp", "de/db2/ReactionRateFactory_8cpp.html", "de/db2/ReactionRateFactory_8cpp" ],
    [ "ReactionRateFactory.h", "de/d47/ReactionRateFactory_8h.html", "de/d47/ReactionRateFactory_8h" ],
    [ "Reactor.cpp", "d3/d68/Reactor_8cpp.html", null ],
    [ "Reactor.h", "d2/d25/Reactor_8h.html", null ],
    [ "ReactorBase.cpp", "d3/d1d/ReactorBase_8cpp.html", null ],
    [ "ReactorBase.h", "d6/df1/ReactorBase_8h.html", "d6/df1/ReactorBase_8h" ],
    [ "ReactorDelegator.h", "d7/d6d/ReactorDelegator_8h.html", [
      [ "ReactorAccessor", "df/dea/classCantera_1_1ReactorAccessor.html", "df/dea/classCantera_1_1ReactorAccessor" ]
    ] ],
    [ "ReactorFactory.cpp", "db/d78/ReactorFactory_8cpp.html", "db/d78/ReactorFactory_8cpp" ],
    [ "ReactorFactory.h", "d8/d7e/ReactorFactory_8h.html", "d8/d7e/ReactorFactory_8h" ],
    [ "ReactorNet.cpp", "d0/d1c/ReactorNet_8cpp.html", null ],
    [ "ReactorNet.h", "d8/d69/ReactorNet_8h.html", null ],
    [ "ReactorSurface.cpp", "df/ddb/ReactorSurface_8cpp.html", null ],
    [ "ReactorSurface.h", "dd/dc9/ReactorSurface_8h.html", null ],
    [ "RedlichKisterVPSSTP.cpp", "d1/dec/RedlichKisterVPSSTP_8cpp.html", null ],
    [ "RedlichKisterVPSSTP.h", "d6/d63/RedlichKisterVPSSTP_8h.html", null ],
    [ "RedlichKwongMFTP.cpp", "dd/d0d/RedlichKwongMFTP_8cpp.html", null ],
    [ "RedlichKwongMFTP.h", "d6/d45/RedlichKwongMFTP_8h.html", null ],
    [ "refine.cpp", "dd/d3c/refine_8cpp.html", null ],
    [ "refine.h", "da/dbc/refine_8h_source.html", null ],
    [ "Reservoir.h", "d6/d45/Reservoir_8h.html", null ],
    [ "ResidEval.h", "da/d61/ResidEval_8h.html", "da/d61/ResidEval_8h" ],
    [ "ResidJacEval.cpp", "d8/d98/ResidJacEval_8cpp.html", "d8/d98/ResidJacEval_8cpp" ],
    [ "ResidJacEval.h", "d8/d05/ResidJacEval_8h.html", "d8/d05/ResidJacEval_8h" ],
    [ "ShomatePoly.h", "d9/d16/ShomatePoly_8h.html", null ],
    [ "Sim1D.cpp", "d0/de8/Sim1D_8cpp.html", null ],
    [ "Sim1D.h", "d3/d5d/Sim1D_8h.html", null ],
    [ "SingleSpeciesTP.cpp", "d4/df7/SingleSpeciesTP_8cpp.html", null ],
    [ "SingleSpeciesTP.h", "de/d38/SingleSpeciesTP_8h.html", null ],
    [ "Solution.cpp", "df/d48/Solution_8cpp.html", "df/d48/Solution_8cpp" ],
    [ "Solution.h", "d4/dfa/Solution_8h.html", "d4/dfa/Solution_8h" ],
    [ "SolutionArray.cpp", "dc/d91/SolutionArray_8cpp.html", "dc/d91/SolutionArray_8cpp" ],
    [ "SolutionArray.h", "db/df6/SolutionArray_8h.html", null ],
    [ "solveSP.cpp", "d3/dc9/solveSP_8cpp.html", "d3/dc9/solveSP_8cpp" ],
    [ "solveSP.h", "d2/d25/solveSP_8h.html", "d2/d25/solveSP_8h" ],
    [ "Species.cpp", "d7/d17/Species_8cpp_source.html", null ],
    [ "Species.h", "d7/dd9/Species_8h.html", "d7/dd9/Species_8h" ],
    [ "SpeciesThermoFactory.cpp", "da/d47/SpeciesThermoFactory_8cpp.html", "da/d47/SpeciesThermoFactory_8cpp" ],
    [ "SpeciesThermoFactory.h", "d8/d9a/SpeciesThermoFactory_8h.html", "d8/d9a/SpeciesThermoFactory_8h" ],
    [ "SpeciesThermoInterpType.cpp", "d1/dea/SpeciesThermoInterpType_8cpp.html", null ],
    [ "SpeciesThermoInterpType.h", "d4/d87/SpeciesThermoInterpType_8h.html", null ],
    [ "speciesThermoTypes.h", "d4/d0c/speciesThermoTypes_8h.html", "d4/d0c/speciesThermoTypes_8h" ],
    [ "StFlow.cpp", "d4/d8d/StFlow_8cpp.html", null ],
    [ "StFlow.h", "d7/d7c/StFlow_8h.html", "d7/d7c/StFlow_8h" ],
    [ "StoichManager.h", "dd/dfd/StoichManager_8h.html", "dd/dfd/StoichManager_8h" ],
    [ "StoichSubstance.cpp", "d1/ddb/StoichSubstance_8cpp.html", null ],
    [ "StoichSubstance.h", "d8/dfb/StoichSubstance_8h.html", null ],
    [ "Storage.cpp", "d9/dab/Storage_8cpp.html", null ],
    [ "Storage.h", "db/d6f/Storage_8h.html", [
      [ "Storage", "dd/ded/classCantera_1_1Storage.html", "dd/ded/classCantera_1_1Storage" ]
    ] ],
    [ "stringUtils.cpp", "d5/d22/stringUtils_8cpp.html", "d5/d22/stringUtils_8cpp" ],
    [ "stringUtils.h", "dd/dc3/stringUtils_8h.html", "dd/dc3/stringUtils_8h" ],
    [ "Sub.cpp", "d2/d1f/Sub_8cpp.html", "d2/d1f/Sub_8cpp" ],
    [ "Sub.h", "d5/d68/Sub_8h.html", "d5/d68/Sub_8h" ],
    [ "sundials_headers.h", "d4/de6/sundials__headers_8h_source.html", null ],
    [ "SundialsContext.h", "d4/ddd/SundialsContext_8h.html", [
      [ "SundialsContext", "d8/dba/classCantera_1_1SundialsContext.html", null ]
    ] ],
    [ "SurfPhase.cpp", "d4/d7e/SurfPhase_8cpp.html", null ],
    [ "SurfPhase.h", "d2/de5/SurfPhase_8h.html", null ],
    [ "thermo.h", "df/d32/thermo_8h.html", null ],
    [ "thermo_utils.h", "df/d13/thermo__utils_8h_source.html", null ],
    [ "ThermoFactory.cpp", "d2/d3a/ThermoFactory_8cpp.html", "d2/d3a/ThermoFactory_8cpp" ],
    [ "ThermoFactory.h", "dc/d8e/ThermoFactory_8h.html", "dc/d8e/ThermoFactory_8h" ],
    [ "ThermoPhase.cpp", "df/d7e/ThermoPhase_8cpp.html", null ],
    [ "ThermoPhase.h", "d7/d01/ThermoPhase_8h.html", "d7/d01/ThermoPhase_8h" ],
    [ "ThirdBodyCalc.h", "d9/d77/ThirdBodyCalc_8h.html", "d9/d77/ThirdBodyCalc_8h" ],
    [ "Transport.cpp", "da/dac/Transport_8cpp.html", null ],
    [ "Transport.h", "d8/d5e/Transport_8h.html", "d8/d5e/Transport_8h" ],
    [ "transport.h", "d2/d02/transport_8h.html", null ],
    [ "transport_utils.h", "d3/d20/transport__utils_8h_source.html", null ],
    [ "TransportBase.h", "da/dbb/TransportBase_8h_source.html", null ],
    [ "TransportData.cpp", "da/dc7/TransportData_8cpp.html", "da/dc7/TransportData_8cpp" ],
    [ "TransportData.h", "df/de9/TransportData_8h.html", "df/de9/TransportData_8h" ],
    [ "TransportFactory.cpp", "d2/d33/TransportFactory_8cpp.html", "d2/d33/TransportFactory_8cpp" ],
    [ "TransportFactory.h", "d3/da4/TransportFactory_8h.html", "d3/da4/TransportFactory_8h" ],
    [ "TwoTempPlasmaRate.cpp", "de/d71/TwoTempPlasmaRate_8cpp.html", null ],
    [ "TwoTempPlasmaRate.h", "d6/d27/TwoTempPlasmaRate_8h.html", [
      [ "TwoTempPlasmaData", "d5/df9/structCantera_1_1TwoTempPlasmaData.html", "d5/df9/structCantera_1_1TwoTempPlasmaData" ]
    ] ],
    [ "Units.cpp", "d4/d3b/Units_8cpp.html", "d4/d3b/Units_8cpp" ],
    [ "Units.h", "da/d58/Units_8h.html", null ],
    [ "UnityLewisTransport.h", "db/d48/UnityLewisTransport_8h.html", null ],
    [ "utilities.h", "de/df0/utilities_8h.html", "de/df0/utilities_8h" ],
    [ "utils.cpp", "de/d06/utils_8cpp.html", "de/d06/utils_8cpp" ],
    [ "utils.h", "d5/d60/utils_8h.html", "d5/d60/utils_8h" ],
    [ "utils_utils.h", "de/dd8/utils__utils_8h_source.html", null ],
    [ "ValueCache.cpp", "d3/d11/ValueCache_8cpp.html", null ],
    [ "ValueCache.h", "d6/df6/ValueCache_8h.html", "d6/df6/ValueCache_8h" ],
    [ "vcs_defs.h", "da/d80/vcs__defs_8h.html", "da/d80/vcs__defs_8h" ],
    [ "vcs_internal.h", "df/da3/vcs__internal_8h.html", "df/da3/vcs__internal_8h" ],
    [ "vcs_MultiPhaseEquil.cpp", "dc/d00/vcs__MultiPhaseEquil_8cpp.html", null ],
    [ "vcs_MultiPhaseEquil.h", "d1/dc3/vcs__MultiPhaseEquil_8h.html", null ],
    [ "vcs_solve.cpp", "dc/d88/vcs__solve_8cpp.html", "dc/d88/vcs__solve_8cpp" ],
    [ "vcs_solve.h", "d4/d51/vcs__solve_8h.html", [
      [ "VCS_SOLVE", "d4/d7e/classCantera_1_1VCS__SOLVE.html", "d4/d7e/classCantera_1_1VCS__SOLVE" ]
    ] ],
    [ "vcs_solve_TP.cpp", "d7/dec/vcs__solve__TP_8cpp.html", null ],
    [ "vcs_species_thermo.h", "d0/d1f/vcs__species__thermo_8h.html", "d0/d1f/vcs__species__thermo_8h" ],
    [ "vcs_SpeciesProperties.h", "d0/d2e/vcs__SpeciesProperties_8h.html", [
      [ "vcs_SpeciesProperties", "d5/d0d/classCantera_1_1vcs__SpeciesProperties.html", "d5/d0d/classCantera_1_1vcs__SpeciesProperties" ]
    ] ],
    [ "vcs_util.cpp", "da/ddf/vcs__util_8cpp.html", "da/ddf/vcs__util_8cpp" ],
    [ "vcs_VolPhase.cpp", "dc/d27/vcs__VolPhase_8cpp.html", "dc/d27/vcs__VolPhase_8cpp" ],
    [ "vcs_VolPhase.h", "d7/dfb/vcs__VolPhase_8h.html", "d7/dfb/vcs__VolPhase_8h" ],
    [ "VPStandardStateTP.cpp", "d9/da4/VPStandardStateTP_8cpp.html", null ],
    [ "VPStandardStateTP.h", "df/dfd/VPStandardStateTP_8h.html", null ],
    [ "Wall.cpp", "de/ddf/Wall_8cpp.html", null ],
    [ "Wall.h", "da/dcb/Wall_8h.html", null ],
    [ "WallFactory.cpp", "db/d00/WallFactory_8cpp.html", "db/d00/WallFactory_8cpp" ],
    [ "WallFactory.h", "d1/d07/WallFactory_8h.html", "d1/d07/WallFactory_8h" ],
    [ "Water.cpp", "de/d90/Water_8cpp.html", "de/d90/Water_8cpp" ],
    [ "Water.h", "d2/d02/Water_8h.html", [
      [ "water", "dc/d9d/classtpx_1_1water.html", "dc/d9d/classtpx_1_1water" ]
    ] ],
    [ "WaterProps.cpp", "d4/d61/WaterProps_8cpp.html", null ],
    [ "WaterProps.h", "db/d4b/WaterProps_8h.html", [
      [ "WaterProps", "d2/db1/classCantera_1_1WaterProps.html", "d2/db1/classCantera_1_1WaterProps" ]
    ] ],
    [ "WaterPropsIAPWS.cpp", "d4/d76/WaterPropsIAPWS_8cpp.html", "d4/d76/WaterPropsIAPWS_8cpp" ],
    [ "WaterPropsIAPWS.h", "d2/d86/WaterPropsIAPWS_8h.html", "d2/d86/WaterPropsIAPWS_8h" ],
    [ "WaterPropsIAPWSphi.cpp", "d4/d30/WaterPropsIAPWSphi_8cpp.html", null ],
    [ "WaterPropsIAPWSphi.h", "da/d59/WaterPropsIAPWSphi_8h.html", [
      [ "WaterPropsIAPWSphi", "d2/d40/classCantera_1_1WaterPropsIAPWSphi.html", "d2/d40/classCantera_1_1WaterPropsIAPWSphi" ]
    ] ],
    [ "WaterSSTP.cpp", "db/de5/WaterSSTP_8cpp.html", null ],
    [ "WaterSSTP.h", "dd/da3/WaterSSTP_8h.html", null ],
    [ "WaterTransport.cpp", "d7/d8a/WaterTransport_8cpp.html", null ],
    [ "WaterTransport.h", "df/d3f/WaterTransport_8h.html", null ],
    [ "wrappers.h", "dd/d6c/wrappers_8h_source.html", null ],
    [ "yaml.h", "dc/dfe/yaml_8h_source.html", null ],
    [ "YamlWriter.cpp", "da/d67/YamlWriter_8cpp_source.html", null ],
    [ "YamlWriter.h", "d1/d1b/YamlWriter_8h.html", null ],
    [ "zerodim.h", "dd/d2e/zerodim_8h.html", null ]
];