Cantera: ReactorSurface Class Reference
ReactorSurface Class Reference
Zero-dimensional reactor networks
A surface where reactions can occur that is in contact with the bulk fluid of a Reactor.
#include <ReactorSurface.h>
Public Member Functions
ReactorSurface (const ReactorSurface &)=delete
ReactorSurface & operator= (const ReactorSurface &)=delete
double area () const
Returns the surface area [m^2].
void setArea (double a)
Set the surface area [m^2].
SurfPhase * thermo ()
Accessor for the SurfPhase object.
Kinetics * kinetics ()
Accessor for the InterfaceKinetics object.
void setKinetics (Kinetics *kin)
Set the InterfaceKinetics object for this surface.
void setReactor (ReactorBase *reactor)
Set the reactor that this Surface interacts with.
size_t nSensParams () const
Number of sensitivity parameters associated with reactions on this surface.
void setCoverages (const double *cov)
Set the surface coverages.
void setCoverages (const Composition &cov)
Set the surface coverages by name.
void setCoverages (const std::string &cov)
Set the surface coverages by name.
void getCoverages (double *cov) const
Get the surface coverages.
void syncCoverages ()
Set the coverages in the surface phase object to the values for this surface.
void syncState ()
Set the coverages and temperature in the surface phase object to the values for this surface.
void addSensitivityReaction (size_t i)
Enable calculation of sensitivities with respect to the rate constant for reaction i.
void setSensitivityParameters (const double *params)
Set reaction rate multipliers.
void resetSensitivityParameters ()
Set reaction rate multipliers back to their initial values.
Protected Attributes
double m_area
SurfPhase * m_thermo
Kinetics * m_kinetics
ReactorBase * m_reactor
vector_fp m_cov
std::vector< SensitivityParameter > m_params
Detailed Description
A surface where reactions can occur that is in contact with the bulk fluid of a Reactor.
Definition at line 20 of file ReactorSurface.h.
Constructor & Destructor Documentation
ReactorSurface()
ReactorSurface ()
Definition at line 14 of file ReactorSurface.cpp.
~ReactorSurface()
virtual ~ReactorSurface () inline virtual
Definition at line 24 of file ReactorSurface.h.
Member Function Documentation
area()
double area () const
Returns the surface area [m^2].
Definition at line 22 of file ReactorSurface.cpp.
setArea()
void setArea (double a)
Set the surface area [m^2].
Definition at line 27 of file ReactorSurface.cpp.
thermo()
SurfPhase * thermo () inline
Accessor for the SurfPhase object.
Definition at line 35 of file ReactorSurface.h.
kinetics()
Kinetics * kinetics () inline
Accessor for the InterfaceKinetics object.
Definition at line 40 of file ReactorSurface.h.
setKinetics()
void setKinetics (Kinetics * kin)
Set the InterfaceKinetics object for this surface.
Definition at line 32 of file ReactorSurface.cpp.
References SurfPhase::getCoverages(), Cantera::npos, Kinetics::surfacePhaseIndex(), and Kinetics::thermo().
setReactor()
void setReactor (ReactorBase * reactor)
Set the reactor that this Surface interacts with.
Definition at line 50 of file ReactorSurface.cpp.
nSensParams()
size_t nSensParams () const inline
Number of sensitivity parameters associated with reactions on this surface.
Definition at line 52 of file ReactorSurface.h.
setCoverages() [1/3]
void setCoverages (const double * cov)
Set the surface coverages.
Array cov has length equal to the number of surface species.
Definition at line 55 of file ReactorSurface.cpp.
setCoverages() [2/3]
void setCoverages (const Composition & cov)
Set the surface coverages by name.
Definition at line 60 of file ReactorSurface.cpp.
setCoverages() [3/3]
void setCoverages (const std::string & cov)
Set the surface coverages by name.
Definition at line 66 of file ReactorSurface.cpp.
getCoverages()
void getCoverages (double * cov) const
Get the surface coverages.
Array cov should have length equal to the number of surface species.
Definition at line 72 of file ReactorSurface.cpp.
syncCoverages()
void syncCoverages ()
Set the coverages in the surface phase object to the values for this surface.
Deprecated:
To be removed after Cantera 2.6. Use syncState() instead.
Definition at line 77 of file ReactorSurface.cpp.
References Cantera::warn_deprecated().
syncState()
void syncState ()
Set the coverages and temperature in the surface phase object to the values for this surface.
The temperature is set to match the bulk phase of the attached Reactor.
Definition at line 84 of file ReactorSurface.cpp.
addSensitivityReaction()
void addSensitivityReaction (size_t i)
Enable calculation of sensitivities with respect to the rate constant for reaction i.
Definition at line 90 of file ReactorSurface.cpp.
setSensitivityParameters()
void setSensitivityParameters (const double * params)
Set reaction rate multipliers.
params is the global vector of sensitivity parameters. This function is called within ReactorNet::eval() before the reaction rates are evaluated.
Definition at line 102 of file ReactorSurface.cpp.
resetSensitivityParameters()
void resetSensitivityParameters ()
Set reaction rate multipliers back to their initial values.
This function is called within ReactorNet::eval() after all rates have been evaluated.
Definition at line 110 of file ReactorSurface.cpp.
Member Data Documentation
m_area
double m_area protected
Definition at line 95 of file ReactorSurface.h.
m_thermo
SurfPhase* m_thermo protected
Definition at line 97 of file ReactorSurface.h.
m_kinetics
Kinetics* m_kinetics protected
Definition at line 98 of file ReactorSurface.h.
m_reactor
ReactorBase* m_reactor protected
Definition at line 99 of file ReactorSurface.h.
m_cov
vector_fp m_cov protected
Definition at line 100 of file ReactorSurface.h.
m_params
std::vector<SensitivityParameter> m_params protected
Definition at line 101 of file ReactorSurface.h.
The documentation for this class was generated from the following files:
ReactorSurface.h
ReactorSurface.cpp