Cantera: Arrhenius2 Class Reference
Arrhenius2 Class Reference final
Arrhenius reaction rate type depends only on temperature.
#include <RxnRates.h>
Public Member Functions
Arrhenius2 ()
Default constructor.
Arrhenius2 (doublereal A, doublereal b, doublereal E)
Constructor.
Arrhenius2 (const AnyValue &rate, const UnitSystem &units, const Units &rate_units)
Constructor based on AnyMap content.
Arrhenius2 (const ArrheniusRate &other)
Converting constructor (to facilitate back-ward compatibility)
void setRateParameters (const AnyValue &rate, const UnitSystem &units, const Units &rate_units)
void getParameters (AnyMap &node, const Units &rate_units) const
Return parameters - two-parameter version.
void update_C (const doublereal *c)
Update concentration-dependent parts of the rate coefficient.
doublereal updateLog (doublereal logT, doublereal recipT) const
Update the value of the natural logarithm of the rate constant.
doublereal updateRC (doublereal logT, doublereal recipT) const
Update the value the rate constant.
virtual const std::string type () const override
String identifying reaction rate specialization.
double activationEnergy_R () const
Return the activation energy divided by the gas constant (i.e.
Public Member Functions inherited from ArrheniusRate
unique_ptr< MultiRateBase > newMultiRate () const override
Create a rate evaluator for reactions of a particular derived type.
double evalRate (double logT, double recipT) const
Evaluate reaction rate.
double evalLog (double logT, double recipT) const
Evaluate natural logarithm of the rate constant.
double evalFromStruct (const ArrheniusData &shared_data) const
Evaluate reaction rate.
double ddTScaledFromStruct (const ArrheniusData &shared_data) const
Evaluate derivative of reaction rate with respect to temperature divided by reaction rate.
ArrheniusBase ()
Default constructor.
ArrheniusBase (double A, double b, double Ea)
Constructor.
ArrheniusBase (const AnyValue &rate, const UnitSystem &units, const UnitStack &rate_units)
Constructor based on AnyValue content.
ArrheniusBase (const AnyMap &node, const UnitStack &rate_units={})
Public Member Functions inherited from ArrheniusBase
ArrheniusBase ()
Default constructor.
ArrheniusBase (double A, double b, double Ea)
Constructor.
ArrheniusBase (const AnyValue &rate, const UnitSystem &units, const UnitStack &rate_units)
Constructor based on AnyValue content.
ArrheniusBase (const AnyMap &node, const UnitStack &rate_units={})
void setRateParameters (const AnyValue &rate, const UnitSystem &units, const UnitStack &rate_units)
Perform object setup based on AnyValue node information.
void getRateParameters (AnyMap &node) const
Return parameters.
virtual void setParameters (const AnyMap &node, const UnitStack &rate_units) override
Set parameters.
virtual void getParameters (AnyMap &node) const override
Get parameters.
virtual void check (const std::string &equation, const AnyMap &node) override
Check rate expression.
virtual void validate (const std::string &equation, const Kinetics &kin) override
Validate the reaction rate expression.
virtual double preExponentialFactor () const
Return the pre-exponential factor A (in m, kmol, s to powers depending on the reaction order)
virtual double temperatureExponent () const
Return the temperature exponent b
virtual double activationEnergy () const
Return the activation energy Ea [J/kmol] The value corresponds to the constant specified by input parameters;.
const Units & rateUnits () const
double order () const
Return reaction order associated with the reaction rate.
void setRateUnits (const UnitStack &rate_units)
Set units of the reaction rate expression.
bool allowNegativePreExponentialFactor () const
Get flag indicating whether negative A values are permitted.
void setAllowNegativePreExponentialFactor (bool value)
Set flag indicating whether negative A values are permitted.
Public Member Functions inherited from ReactionRate
ReactionRate (const ReactionRate &other)
ReactionRate & operator= (const ReactionRate &other)
AnyMap parameters () const
Return the parameters such that an identical Reaction could be reconstructed using the newReaction() function.
virtual void validate (const std::string &equation)
Validate the reaction rate expression (legacy call)
size_t rateIndex () const
Reaction rate index within kinetics evaluator.
void setRateIndex (size_t idx)
Set reaction rate index within kinetics evaluator.
virtual void setContext (const Reaction &rxn, const Kinetics &kin)
Set context of reaction rate evaluation.
double eval (double T)
Evaluate reaction rate based on temperature.
double eval (double T, double extra)
Evaluate reaction rate based on temperature and an extra parameter.
double eval (double T, const std::vector< double > &extra)
Evaluate reaction rate based on temperature and an extra vector parameter.
Additional Inherited Members
Protected Attributes inherited from ArrheniusBase
bool m_negativeA_ok
Flag indicating whether negative A values are permitted.
double m_A
Pre-exponential factor.
double m_b
Temperature exponent.
double m_Ea_R
Activation energy (in temperature units)
double m_E4_R
Optional 4th energy parameter (in temperature units)
double m_logA
Logarithm of pre-exponential factor.
double m_order
Reaction order.
std::string m_A_str = "A"
The string for temperature exponent.
std::string m_b_str = "b"
The string for temperature exponent.
std::string m_Ea_str = "Ea"
The string for activation energy.
std::string m_E4_str = ""
The string for an optional 4th parameter.
Units m_rate_units
Reaction rate units.
Protected Attributes inherited from ReactionRate
AnyMap m_input
Input data used for specific models.
size_t m_rate_index
Index of reaction rate within kinetics evaluator.
Detailed Description
Arrhenius reaction rate type depends only on temperature.
A reaction rate coefficient of the following form.
\[ k_f = A T^b \exp (-E/RT) \]
Deprecated:
To be removed after Cantera 2.6. See ArrheniusRate.
Definition at line 41 of file RxnRates.h.
Constructor & Destructor Documentation
Arrhenius2() [1/4]
Arrhenius2 ()
Default constructor.
Definition at line 11 of file RxnRates.cpp.
References ArrheniusBase::m_A, ArrheniusBase::m_b, and ArrheniusBase::m_logA.
Arrhenius2() [2/4]
Arrhenius2 (doublereal A, doublereal b, doublereal E)
Constructor.
Parameters
A pre-exponential. The unit system is (kmol, m, s). The actual units depend on the reaction order and the dimensionality (surface or bulk).
b Temperature exponent. Non-dimensional.
E Activation energy in temperature units. Kelvin.
Todo:
Add deprecation warning pointing out change of activation energy units.
Definition at line 19 of file RxnRates.cpp.
Arrhenius2() [3/4]
Arrhenius2 (const AnyValue & rate, const UnitSystem & units, const Units & rate_units)
Constructor based on AnyMap content.
Definition at line 27 of file RxnRates.cpp.
Arrhenius2() [4/4]
Arrhenius2 (const ArrheniusRate & other)
Converting constructor (to facilitate back-ward compatibility)
Definition at line 33 of file RxnRates.cpp.
Member Function Documentation
setRateParameters()
void setRateParameters (const AnyValue & rate, const UnitSystem & units, const Units & rate_units)
Definition at line 40 of file RxnRates.cpp.
getParameters()
void getParameters (AnyMap & node, const Units & rate_units) const
Return parameters - two-parameter version.
Definition at line 50 of file RxnRates.cpp.
References Units::factor(), ArrheniusBase::m_A, ArrheniusBase::m_b, ArrheniusBase::m_Ea_R, ArrheniusBase::preExponentialFactor(), and AnyMap::setFlowStyle().
Referenced by ElementaryReaction2::getParameters(), and FalloffReaction2::getParameters().
update_C()
void update_C (const doublereal * c) inline
Update concentration-dependent parts of the rate coefficient.
For this class, there are no concentration-dependent parts, so this method does nothing.
Definition at line 78 of file RxnRates.h.
updateLog()
doublereal updateLog (doublereal logT, doublereal recipT) const inline
Update the value of the natural logarithm of the rate constant.
Definition at line 84 of file RxnRates.h.
References ArrheniusBase::m_b, ArrheniusBase::m_Ea_R, and ArrheniusBase::m_logA.
updateRC()
doublereal updateRC (doublereal logT, doublereal recipT) const inline
Update the value the rate constant.
This function returns the actual value of the rate constant. It can be safely called for negative values of the pre-exponential factor.
Definition at line 94 of file RxnRates.h.
References ArrheniusBase::m_A, ArrheniusBase::m_b, and ArrheniusBase::m_Ea_R.
type()
virtual const std::string type () const inline override virtual
String identifying reaction rate specialization.
Reimplemented from ArrheniusRate.
Definition at line 98 of file RxnRates.h.
activationEnergy_R()
double activationEnergy_R () const inline
Return the activation energy divided by the gas constant (i.e.
the activation temperature) [K]
Definition at line 104 of file RxnRates.h.
References ArrheniusBase::m_Ea_R.
Referenced by InterfaceKinetics::buildSurfaceArrhenius().
The documentation for this class was generated from the following files:
RxnRates.h
RxnRates.cpp