Cantera: IonFlow Class Reference
IonFlow Class Reference
One-Dimensional Reacting Flows
This class models the ion transportation in a flame.
#include <IonFlow.h>
Public Member Functions
IonFlow (ThermoPhase *ph=0, size_t nsp=1, size_t points=1)
IonFlow (shared_ptr< Solution > sol, const std::string &id="", size_t points=1)
Create a new flow domain.
virtual string type () const
String indicating the domain implemented.
virtual size_t getSolvingStage () const
Get the solving stage (used by IonFlow specialization)
virtual void setSolvingStage (const size_t stage)
Solving stage mode for handling ionized species (used by IonFlow specialization)
virtual void resize (size_t components, size_t points)
Change the grid size. Called after grid refinement.
virtual bool componentActive (size_t n) const
Returns true if the specified component is an active part of the solver state.
virtual void _finalize (const double *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
virtual void solveElectricField (size_t j=npos)
Set to solve electric field in a point (used by IonFlow specialization)
virtual void fixElectricField (size_t j=npos)
Set to fix voltage in a point (used by IonFlow specialization)
virtual bool doElectricField (size_t j) const
Retrieve flag indicating whether electric field is solved or not (used by IonFlow specialization)
void setElectronTransport (vector_fp &tfix, vector_fp &diff_e, vector_fp &mobi_e)
Sometimes it is desired to carry out the simulation using a specified electron transport profile, rather than assuming it as a constant (0.4).
Public Member Functions inherited from StFlow
StFlow (ThermoPhase *ph=0, size_t nsp=1, size_t points=1)
Create a new flow domain.
StFlow (shared_ptr< ThermoPhase > th, size_t nsp=1, size_t points=1)
Delegating constructor.
StFlow (shared_ptr< Solution > sol, const std::string &id="", size_t points=1)
Create a new flow domain.
virtual string type () const
String indicating the domain implemented.
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
virtual size_t componentIndex (const std::string &name) const
index of component with name name.
virtual bool componentActive (size_t n) const
Returns true if the specified component is an active part of the solver state.
virtual void show (const double *x)
Print the solution.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
void setFreeFlow ()
Set flow configuration for freely-propagating flames, using an internal point with a fixed temperature as the condition to determine the inlet mass flux.
void setAxisymmetricFlow ()
Set flow configuration for axisymmetric counterflow flames, using specified inlet mass fluxes.
void setUnstrainedFlow ()
Set flow configuration for burner-stabilized flames, using specified inlet mass fluxes.
virtual string flowType () const
Return the type of flow domain being represented, either "Free Flame" or "Axisymmetric Stagnation".
void solveEnergyEqn (size_t j=npos)
virtual size_t getSolvingStage () const
Get the solving stage (used by IonFlow specialization)
virtual void setSolvingStage (const size_t stage)
Solving stage mode for handling ionized species (used by IonFlow specialization)
virtual void solveElectricField (size_t j=npos)
Set to solve electric field in a point (used by IonFlow specialization)
virtual void fixElectricField (size_t j=npos)
Set to fix voltage in a point (used by IonFlow specialization)
virtual bool doElectricField (size_t j) const
Retrieve flag indicating whether electric field is solved or not (used by IonFlow specialization)
void enableRadiation (bool doRadiation)
Turn radiation on / off.
bool radiationEnabled () const
Returns true if the radiation term in the energy equation is enabled.
double radiativeHeatLoss (size_t j) const
Return radiative heat loss at grid point j.
void setBoundaryEmissivities (double e_left, double e_right)
Set the emissivities for the boundary values.
double leftEmissivity () const
Return emissivity at left boundary.
double rightEmissivity () const
Return emissivity at right boundary.
void fixTemperature (size_t j=npos)
bool doEnergy (size_t j)
virtual void resize (size_t components, size_t points)
Change the grid size. Called after grid refinement.
void setGas (const doublereal *x, size_t j)
Set the gas object state to be consistent with the solution at point j.
void setGasAtMidpoint (const doublereal *x, size_t j)
Set the gas state to be consistent with the solution at the midpoint between j and j + 1.
doublereal density (size_t j) const
virtual bool fixed_mdot ()
void setViscosityFlag (bool dovisc)
virtual void eval (size_t j, doublereal *x, doublereal *r, integer *mask, doublereal rdt)
virtual void evalRightBoundary (double *x, double *res, int *diag, double rdt)
Evaluate all residual components at the right boundary.
virtual void evalContinuity (size_t j, double *x, double *r, int *diag, double rdt)
Evaluate the residual corresponding to the continuity equation at all interior grid points.
size_t leftExcessSpecies () const
Index of the species on the left boundary with the largest mass fraction.
size_t rightExcessSpecies () const
Index of the species on the right boundary with the largest mass fraction.
virtual void setupGrid (size_t n, const doublereal *z)
called to set up initial grid, and after grid refinement
virtual void resetBadValues (double *xg)
ThermoPhase & phase ()
Kinetics & kinetics ()
void setThermo (ThermoPhase &th)
Set the thermo manager.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
void setKinetics (Kinetics &kin)
Set the kinetics manager.
virtual void setTransport (shared_ptr< Transport > trans)
Set transport model to existing instance.
void setTransport (Transport &trans)
Set transport model to existing instance.
void setTransportModel (const std::string &trans)
Set the transport model.
std::string transportModel () const
Retrieve transport model.
void enableSoret (bool withSoret)
Enable thermal diffusion, also known as Soret diffusion.
bool withSoret () const
void setPressure (doublereal p)
Set the pressure.
doublereal pressure () const
The current pressure [Pa].
virtual void _getInitialSoln (double *x)
Write the initial solution estimate into array x.
void setFixedTempProfile (vector_fp &zfixed, vector_fp &tfixed)
Sometimes it is desired to carry out the simulation using a specified temperature profile, rather than computing it by solving the energy equation.
void setTemperature (size_t j, doublereal t)
doublereal T_fixed (size_t j) const
The fixed temperature value at point j.
Public Member Functions inherited from Domain1D
Domain1D (size_t nv=1, size_t points=1, double time=0.0)
Constructor.
Domain1D (const Domain1D &)=delete
Domain1D & operator= (const Domain1D &)=delete
int domainType ()
Domain type flag.
virtual string type () const
String indicating the domain implemented.
size_t domainIndex ()
The left-to-right location of this domain.
virtual bool isConnector ()
True if the domain is a connector domain.
void setSolution (shared_ptr< Solution > sol)
Set the solution manager.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
virtual void setTransport (shared_ptr< Transport > trans)
Set transport model to existing instance.
const OneDim & container () const
The container holding this domain.
void setContainer (OneDim *c, size_t index)
Specify the container object for this domain, and the position of this domain in the list.
void setBandwidth (int bw=-1)
Set the Jacobian bandwidth. See the discussion of method bandwidth().
size_t bandwidth ()
Set the Jacobian bandwidth for this domain.
virtual void init ()
virtual void setInitialState (doublereal *xlocal=0)
virtual void setState (size_t point, const doublereal *state, doublereal *x)
virtual void resetBadValues (double *xg)
virtual void resize (size_t nv, size_t np)
Refiner & refiner ()
Return a reference to the grid refiner.
size_t nComponents () const
Number of components at each grid point.
void checkComponentIndex (size_t n) const
Check that the specified component index is in range.
void checkComponentArraySize (size_t nn) const
Check that an array size is at least nComponents().
size_t nPoints () const
Number of grid points in this domain.
void checkPointIndex (size_t n) const
Check that the specified point index is in range.
void checkPointArraySize (size_t nn) const
Check that an array size is at least nPoints().
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
void setComponentName (size_t n, const std::string &name)
virtual size_t componentIndex (const std::string &name) const
index of component with name name.
void setBounds (size_t n, doublereal lower, doublereal upper)
void setTransientTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for time-stepping mode.
void setSteadyTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for steady-state mode.
doublereal rtol (size_t n)
Relative tolerance of the nth component.
doublereal atol (size_t n)
Absolute tolerance of the nth component.
double steady_rtol (size_t n)
Steady relative tolerance of the nth component.
double steady_atol (size_t n)
Steady absolute tolerance of the nth component.
double transient_rtol (size_t n)
Transient relative tolerance of the nth component.
double transient_atol (size_t n)
Transient absolute tolerance of the nth component.
doublereal upperBound (size_t n) const
Upper bound on the nth component.
doublereal lowerBound (size_t n) const
Lower bound on the nth component.
void initTimeInteg (doublereal dt, const doublereal *x0)
Prepare to do time stepping with time step dt.
void setSteadyMode ()
Prepare to solve the steady-state problem.
bool steady ()
True if in steady-state mode.
bool transient ()
True if not in steady-state mode.
void needJacUpdate ()
virtual void eval (size_t j, doublereal *x, doublereal *r, integer *mask, doublereal rdt=0.0)
Evaluate the residual function at point j.
size_t index (size_t n, size_t j) const
doublereal value (const doublereal *x, size_t n, size_t j) const
virtual void setJac (MultiJac *jac)
AnyMap serialize (const double *soln) const
Save the state of this domain as an AnyMap.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
shared_ptr< SolutionArray > toArray (bool normalize=false) const
Save the state of this domain to a SolutionArray.
void restore (const AnyMap &state, double *soln, int loglevel)
Restore the solution for this domain from an AnyMap.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
void fromArray (const shared_ptr< SolutionArray > &arr)
Restore the solution for this domain from a SolutionArray.
shared_ptr< Solution > solution () const
Return thermo/kinetics/transport manager used in the domain.
size_t size () const
void locate ()
Find the index of the first grid point in this domain, and the start of its variables in the global solution vector.
virtual size_t loc (size_t j=0) const
Location of the start of the local solution vector in the global solution vector,.
size_t firstPoint () const
The index of the first (that is, left-most) grid point belonging to this domain.
size_t lastPoint () const
The index of the last (that is, right-most) grid point belonging to this domain.
void linkLeft (Domain1D *left)
Set the left neighbor to domain 'left.
void linkRight (Domain1D *right)
Set the right neighbor to domain 'right.'.
void append (Domain1D *right)
Append domain 'right' to this one, and update all links.
Domain1D * left () const
Return a pointer to the left neighbor.
Domain1D * right () const
Return a pointer to the right neighbor.
double prevSoln (size_t n, size_t j) const
Value of component n at point j in the previous solution.
void setID (const std::string &s)
Specify an identifying tag for this domain.
std::string id () const
virtual void showSolution_s (std::ostream &s, const double *x)
virtual void showSolution (const double *x)
Print the solution.
virtual void show (std::ostream &s, const double *x)
Print the solution.
virtual void show (const double *x)
Print the solution.
doublereal z (size_t jlocal) const
doublereal zmin () const
doublereal zmax () const
void setProfile (const std::string &name, double *values, double *soln)
vector_fp & grid ()
const vector_fp & grid () const
doublereal grid (size_t point) const
virtual void setupGrid (size_t n, const doublereal *z)
called to set up initial grid, and after grid refinement
virtual void _getInitialSoln (doublereal *x)
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
virtual doublereal initialValue (size_t n, size_t j)
Initial value of solution component n at grid point j.
virtual void _finalize (const doublereal *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
void forceFullUpdate (bool update)
In some cases, for computational efficiency some properties (such as transport coefficients) may not be updated during Jacobian evaluations.
void setData (shared_ptr< vector< double > > &data)
Set shared data pointer.
Protected Member Functions
virtual void evalResidual (double *x, double *rsd, int *diag, double rdt, size_t jmin, size_t jmax)
virtual void updateTransport (double *x, size_t j0, size_t j1)
Update the transport properties at grid points in the range from j0 to j1, based on solution x.
virtual void updateDiffFluxes (const double *x, size_t j0, size_t j1)
Update the diffusive mass fluxes.
virtual void frozenIonMethod (const double *x, size_t j0, size_t j1)
Solving phase one: the fluxes of charged species are turned off.
virtual void electricFieldMethod (const double *x, size_t j0, size_t j1)
Solving phase two: the electric field equation is added coupled by the electrical drift.
double E (const double *x, size_t j) const
electric field
double dEdz (const double *x, size_t j) const
double ND (const double *x, size_t k, size_t j) const
number density
double rho_e (double *x, size_t j) const
total charge density
Protected Member Functions inherited from StFlow
virtual AnyMap getMeta () const
Retrieve meta data.
virtual void setMeta (const AnyMap &state)
Retrieve meta data.
doublereal wdot (size_t k, size_t j) const
void getWdot (doublereal *x, size_t j)
Write the net production rates at point j into array m_wdot
virtual void updateProperties (size_t jg, double *x, size_t jmin, size_t jmax)
Update the properties (thermo, transport, and diffusion flux).
virtual void evalResidual (double *x, double *rsd, int *diag, double rdt, size_t jmin, size_t jmax)
Evaluate the residual function.
void updateThermo (const doublereal *x, size_t j0, size_t j1)
Update the thermodynamic properties from point j0 to point j1 (inclusive), based on solution x.
doublereal shear (const doublereal *x, size_t j) const
doublereal divHeatFlux (const doublereal *x, size_t j) const
size_t mindex (size_t k, size_t j, size_t m)
virtual void updateDiffFluxes (const doublereal *x, size_t j0, size_t j1)
Update the diffusive mass fluxes.
virtual void grad_hk (const double *x, size_t j)
Get the gradient of species specific molar enthalpies.
virtual void updateTransport (doublereal *x, size_t j0, size_t j1)
Update the transport properties at grid points in the range from j0 to j1, based on solution x.
doublereal T (const doublereal *x, size_t j) const
doublereal & T (doublereal *x, size_t j)
doublereal T_prev (size_t j) const
doublereal rho_u (const doublereal *x, size_t j) const
doublereal u (const doublereal *x, size_t j) const
doublereal V (const doublereal *x, size_t j) const
doublereal V_prev (size_t j) const
doublereal lambda (const doublereal *x, size_t j) const
doublereal Y (const doublereal *x, size_t k, size_t j) const
doublereal & Y (doublereal *x, size_t k, size_t j)
doublereal Y_prev (size_t k, size_t j) const
doublereal X (const doublereal *x, size_t k, size_t j) const
doublereal flux (size_t k, size_t j) const
doublereal dVdz (const doublereal *x, size_t j) const
doublereal dYdz (const doublereal *x, size_t k, size_t j) const
doublereal dTdz (const doublereal *x, size_t j) const
virtual AnyMap getMeta () const
Retrieve meta data.
virtual void setMeta (const AnyMap &meta)
Retrieve meta data.
Protected Attributes
std::vector< bool > m_do_electric_field
flag for solving electric field or not
bool m_import_electron_transport = false
flag for importing transport of electron
vector_fp m_speciesCharge
electrical properties
std::vector< size_t > m_kCharge
index of species with charges
std::vector< size_t > m_kNeutral
index of neutral species
vector_fp m_mobi_e_fix
coefficients of polynomial fitting of fixed electron transport profile
vector_fp m_diff_e_fix
vector_fp m_mobility
mobility
size_t m_stage = 1
solving stage
size_t m_kElectron = npos
index of electron
Protected Attributes inherited from StFlow
double m_press = -1.0
vector_fp m_dz
vector_fp m_rho
vector_fp m_wtm
vector_fp m_wt
vector_fp m_cp
vector_fp m_visc
vector_fp m_tcon
vector_fp m_diff
vector_fp m_multidiff
Array2D m_dthermal
Array2D m_flux
Array2D m_hk
Array of size m_nsp by m_points for saving molar enthalpies.
Array2D m_dhk_dz
Array of size m_nsp by m_points -1 for saving enthalpy fluxes.
Array2D m_wdot
size_t m_nsp
ThermoPhase * m_thermo = nullptr
Kinetics * m_kin = nullptr
Transport * m_trans = nullptr
double m_epsilon_left = 0.0
double m_epsilon_right = 0.0
std::vector< size_t > m_kRadiating
Indices within the ThermoPhase of the radiating species.
std::vector< bool > m_do_energy
bool m_do_soret = false
std::vector< bool > m_do_species
bool m_do_multicomponent = false
bool m_do_radiation = false
flag for the radiative heat loss
vector_fp m_qdotRadiation
radiative heat loss vector
vector_fp m_fixedtemp
vector_fp m_zfix
vector_fp m_tfix
size_t m_kExcessLeft = 0
Index of species with a large mass fraction at each boundary, for which the mass fraction may be calculated as 1 minus the sum of the other mass fractions.
size_t m_kExcessRight = 0
bool m_dovisc
bool m_isFree
bool m_usesLambda
Protected Attributes inherited from Domain1D
shared_ptr< vector< double > > m_state
data pointer shared from OneDim
double m_rdt = 0.0
size_t m_nv = 0
size_t m_points
vector_fp m_slast
vector_fp m_max
vector_fp m_min
vector_fp m_rtol_ss
vector_fp m_rtol_ts
vector_fp m_atol_ss
vector_fp m_atol_ts
vector_fp m_z
OneDim * m_container = nullptr
size_t m_index
int m_type = 0
size_t m_iloc = 0
Starting location within the solution vector for unknowns that correspond to this domain.
size_t m_jstart = 0
Domain1D * m_left = nullptr
Domain1D * m_right = nullptr
std::string m_id
Identity tag for the domain.
std::unique_ptr< Refiner > m_refiner
std::vector< std::string > m_name
int m_bw = -1
bool m_force_full_update = false
shared_ptr< Solution > m_solution
Composite thermo/kinetics/transport handler.
Additional Inherited Members
Public Attributes inherited from StFlow
double m_zfixed = Undef
Location of the point where temperature is fixed.
double m_tfixed = -1.0
Temperature at the point used to fix the flame location.
Detailed Description
This class models the ion transportation in a flame.
There are three stages of the simulation.
The first stage turns off the diffusion of ions due to the fast diffusion rate of electron without internal electric forces (ambi- polar diffusion effect).
The second stage evaluates drift flux from electric field calculated from Poisson's equation, which is solved together with other equations. Poisson's equation is coupled because the total charge densities depends on the species' concentration. Reference: Pederson, Timothy, and R. C. Brown. "Simulation of electric field effects in premixed methane flames." Combustion and Flames 94.4(1993): 433-448.
Definition at line 31 of file IonFlow.h.
Constructor & Destructor Documentation
IonFlow() [1/2]
IonFlow (ThermoPhase * ph = 0, size_t nsp = 1, size_t points = 1)
Definition at line 18 of file IonFlow.cpp.
IonFlow() [2/2]
IonFlow (shared_ptr< Solution > sol, const std::string & id = "", size_t points = 1)
Create a new flow domain.
Parameters
sol Solution object used to evaluate all thermodynamic, kinetic, and transport properties
id name of flow domain
points initial number of grid points
Definition at line 56 of file IonFlow.cpp.
References Domain1D::m_id, Domain1D::m_solution, StFlow::setKinetics(), StFlow::setTransport(), StFlow::setTransportModel(), Transport::transportModel(), and Cantera::warn_deprecated().
Member Function Documentation
type()
string type () const virtual
String indicating the domain implemented.
Since
New in Cantera 3.0.
Todo:
Transition back to domainType after Cantera 3.0
Reimplemented from StFlow.
Definition at line 77 of file IonFlow.cpp.
getSolvingStage()
virtual size_t getSolvingStage () const inline virtual
Get the solving stage (used by IonFlow specialization)
Since
New in Cantera 3.0
Reimplemented from StFlow.
Definition at line 45 of file IonFlow.h.
References IonFlow::m_stage.
setSolvingStage()
void setSolvingStage (const size_t stage) virtual
Solving stage mode for handling ionized species (used by IonFlow specialization)
stage=1: the fluxes of charged species are set to zero
stage=2: the electric field equation is solved, and the drift flux for ionized species is evaluated
Reimplemented from StFlow.
Definition at line 193 of file IonFlow.cpp.
References IonFlow::m_stage.
resize()
void resize (size_t components, size_t points) virtual
Change the grid size. Called after grid refinement.
Reimplemented from StFlow.
Definition at line 87 of file IonFlow.cpp.
References IonFlow::m_do_electric_field, IonFlow::m_mobility, and StFlow::resize().
componentActive()
bool componentActive (size_t n) const virtual
Returns true if the specified component is an active part of the solver state.
Reimplemented from StFlow.
Definition at line 94 of file IonFlow.cpp.
References Cantera::c_offset_E, and StFlow::componentActive().
_finalize()
void _finalize (const double * x) virtual
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
In such cases, the parameters may be set in method _finalize. This method is called just before the Newton solver is called, and the x array is guaranteed to be the local solution vector for this domain that will be used as the initial guess. If no such parameters need to be set, then method _finalize does not need to be overloaded.
Reimplemented from StFlow.
Definition at line 307 of file IonFlow.cpp.
References StFlow::_finalize(), IonFlow::m_do_electric_field, and IonFlow::solveElectricField().
solveElectricField()
void solveElectricField (size_t j = npos) virtual
Set to solve electric field in a point (used by IonFlow specialization)
Reimplemented from StFlow.
Definition at line 240 of file IonFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, IonFlow::m_do_electric_field, Domain1D::needJacUpdate(), and Cantera::npos.
Referenced by IonFlow::_finalize().
fixElectricField()
void fixElectricField (size_t j = npos) virtual
Set to fix voltage in a point (used by IonFlow specialization)
Reimplemented from StFlow.
Definition at line 265 of file IonFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, IonFlow::m_do_electric_field, Domain1D::needJacUpdate(), and Cantera::npos.
doElectricField()
virtual bool doElectricField (size_t j) const inline virtual
Retrieve flag indicating whether electric field is solved or not (used by IonFlow specialization)
Reimplemented from StFlow.
Definition at line 57 of file IonFlow.h.
References IonFlow::m_do_electric_field.
setElectronTransport()
void setElectronTransport (vector_fp & tfix, vector_fp & diff_e, vector_fp & mobi_e)
Sometimes it is desired to carry out the simulation using a specified electron transport profile, rather than assuming it as a constant (0.4).
Reference: Bisetti, Fabrizio, and Mbark El Morsli. "Calculation and analysis of the mobility and diffusion coefficient of thermal electrons in methane/air premixed flames." Combustion and flame 159.12 (2012): 3518-3521. If in the future the class GasTransport is improved, this method may be discarded. This method specifies this profile.
Definition at line 290 of file IonFlow.cpp.
References IonFlow::m_import_electron_transport, IonFlow::m_mobi_e_fix, and Cantera::polyfit().
evalResidual()
void evalResidual (double * x, double * rsd, int * diag, double rdt, size_t jmin, size_t jmax) protected virtual
This function overloads the original function. The residual function of electric field is added.
Reimplemented from StFlow.
Definition at line 205 of file IonFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_Y, IonFlow::E(), Cantera::epsilon_0, StFlow::evalResidual(), IonFlow::m_kCharge, IonFlow::m_stage, and IonFlow::rho_e().
updateTransport()
void updateTransport (double * x, size_t j0, size_t j1) protected virtual
Update the transport properties at grid points in the range from j0 to j1, based on solution x.
Reimplemented from StFlow.
Definition at line 103 of file IonFlow.cpp.
References Transport::getMobilities(), IonFlow::m_import_electron_transport, IonFlow::m_kElectron, IonFlow::m_mobi_e_fix, IonFlow::m_mobility, Cantera::poly5(), StFlow::setGasAtMidpoint(), Phase::temperature(), and StFlow::updateTransport().
updateDiffFluxes()
void updateDiffFluxes (const double * x, size_t j0, size_t j1) protected virtual
Update the diffusive mass fluxes.
Reimplemented from StFlow.
Definition at line 118 of file IonFlow.cpp.
References IonFlow::electricFieldMethod(), IonFlow::frozenIonMethod(), and IonFlow::m_stage.
frozenIonMethod()
void frozenIonMethod (const double * x, size_t j0, size_t j1) protected virtual
Solving phase one: the fluxes of charged species are turned off.
Definition at line 128 of file IonFlow.cpp.
References IonFlow::m_kCharge, and IonFlow::m_kNeutral.
Referenced by IonFlow::updateDiffFluxes().
electricFieldMethod()
void electricFieldMethod (const double * x, size_t j0, size_t j1) protected virtual
Solving phase two: the electric field equation is added coupled by the electrical drift.
Definition at line 155 of file IonFlow.cpp.
References IonFlow::E(), IonFlow::m_kCharge, IonFlow::m_kNeutral, IonFlow::m_mobility, and IonFlow::m_speciesCharge.
Referenced by IonFlow::updateDiffFluxes().
E()
double E (const double * x, size_t j) const inline protected
electric field
Definition at line 119 of file IonFlow.h.
References Cantera::c_offset_E.
Referenced by IonFlow::electricFieldMethod(), and IonFlow::evalResidual().
dEdz()
double dEdz (const double * x, size_t j) const inline protected
Definition at line 123 of file IonFlow.h.
ND()
double ND (const double * x, size_t k, size_t j) const inline protected
number density
Definition at line 128 of file IonFlow.h.
References Cantera::Avogadro.
Referenced by IonFlow::rho_e().
rho_e()
double rho_e (double * x, size_t j) const inline protected
total charge density
Definition at line 133 of file IonFlow.h.
References Cantera::ElectronCharge, IonFlow::m_kCharge, IonFlow::m_speciesCharge, and IonFlow::ND().
Referenced by IonFlow::evalResidual().
Member Data Documentation
m_do_electric_field
std::vector<bool> m_do_electric_field protected
flag for solving electric field or not
Definition at line 91 of file IonFlow.h.
Referenced by IonFlow::_finalize(), IonFlow::doElectricField(), IonFlow::fixElectricField(), IonFlow::resize(), and IonFlow::solveElectricField().
m_import_electron_transport
bool m_import_electron_transport = false protected
flag for importing transport of electron
Definition at line 94 of file IonFlow.h.
Referenced by IonFlow::setElectronTransport(), and IonFlow::updateTransport().
m_speciesCharge
vector_fp m_speciesCharge protected
electrical properties
Definition at line 97 of file IonFlow.h.
Referenced by IonFlow::electricFieldMethod(), and IonFlow::rho_e().
m_kCharge
std::vector<size_t> m_kCharge protected
index of species with charges
Definition at line 100 of file IonFlow.h.
Referenced by IonFlow::electricFieldMethod(), IonFlow::evalResidual(), IonFlow::frozenIonMethod(), and IonFlow::rho_e().
m_kNeutral
std::vector<size_t> m_kNeutral protected
index of neutral species
Definition at line 103 of file IonFlow.h.
Referenced by IonFlow::electricFieldMethod(), and IonFlow::frozenIonMethod().
m_mobi_e_fix
vector_fp m_mobi_e_fix protected
coefficients of polynomial fitting of fixed electron transport profile
Definition at line 106 of file IonFlow.h.
Referenced by IonFlow::setElectronTransport(), and IonFlow::updateTransport().
m_diff_e_fix
vector_fp m_diff_e_fix protected
Definition at line 107 of file IonFlow.h.
m_mobility
vector_fp m_mobility protected
mobility
Definition at line 110 of file IonFlow.h.
Referenced by IonFlow::electricFieldMethod(), IonFlow::resize(), and IonFlow::updateTransport().
m_stage
size_t m_stage = 1 protected
solving stage
Definition at line 113 of file IonFlow.h.
Referenced by IonFlow::evalResidual(), IonFlow::getSolvingStage(), IonFlow::setSolvingStage(), and IonFlow::updateDiffFluxes().
m_kElectron
size_t m_kElectron = npos protected
index of electron
Definition at line 116 of file IonFlow.h.
Referenced by IonFlow::updateTransport().
The documentation for this class was generated from the following files:
IonFlow.h
IonFlow.cpp