Cantera: StFlow Class Reference
StFlow Class Reference
One-Dimensional Reacting Flows
This class represents 1D flow domains that satisfy the one-dimensional similarity solution for chemically-reacting, axisymmetric flows.
#include <StFlow.h>
Public Member Functions
StFlow (ThermoPhase *ph=0, size_t nsp=1, size_t points=1)
Create a new flow domain.
StFlow (shared_ptr< ThermoPhase > th, size_t nsp=1, size_t points=1)
Delegating constructor.
StFlow (shared_ptr< Solution > sol, const std::string &id="", size_t points=1)
Create a new flow domain.
virtual string type () const
String indicating the domain implemented.
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
virtual size_t componentIndex (const std::string &name) const
index of component with name name.
virtual bool componentActive (size_t n) const
Returns true if the specified component is an active part of the solver state.
virtual void show (const double *x)
Print the solution.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
void setFreeFlow ()
Set flow configuration for freely-propagating flames, using an internal point with a fixed temperature as the condition to determine the inlet mass flux.
void setAxisymmetricFlow ()
Set flow configuration for axisymmetric counterflow flames, using specified inlet mass fluxes.
void setUnstrainedFlow ()
Set flow configuration for burner-stabilized flames, using specified inlet mass fluxes.
virtual string flowType () const
Return the type of flow domain being represented, either "Free Flame" or "Axisymmetric Stagnation".
void solveEnergyEqn (size_t j=npos)
virtual size_t getSolvingStage () const
Get the solving stage (used by IonFlow specialization)
virtual void setSolvingStage (const size_t stage)
Solving stage mode for handling ionized species (used by IonFlow specialization)
virtual void solveElectricField (size_t j=npos)
Set to solve electric field in a point (used by IonFlow specialization)
virtual void fixElectricField (size_t j=npos)
Set to fix voltage in a point (used by IonFlow specialization)
virtual bool doElectricField (size_t j) const
Retrieve flag indicating whether electric field is solved or not (used by IonFlow specialization)
void enableRadiation (bool doRadiation)
Turn radiation on / off.
bool radiationEnabled () const
Returns true if the radiation term in the energy equation is enabled.
double radiativeHeatLoss (size_t j) const
Return radiative heat loss at grid point j.
void setBoundaryEmissivities (double e_left, double e_right)
Set the emissivities for the boundary values.
double leftEmissivity () const
Return emissivity at left boundary.
double rightEmissivity () const
Return emissivity at right boundary.
void fixTemperature (size_t j=npos)
bool doEnergy (size_t j)
virtual void resize (size_t components, size_t points)
Change the grid size. Called after grid refinement.
void setGas (const doublereal *x, size_t j)
Set the gas object state to be consistent with the solution at point j.
void setGasAtMidpoint (const doublereal *x, size_t j)
Set the gas state to be consistent with the solution at the midpoint between j and j + 1.
doublereal density (size_t j) const
virtual bool fixed_mdot ()
void setViscosityFlag (bool dovisc)
virtual void eval (size_t j, doublereal *x, doublereal *r, integer *mask, doublereal rdt)
virtual void evalRightBoundary (double *x, double *res, int *diag, double rdt)
Evaluate all residual components at the right boundary.
virtual void evalContinuity (size_t j, double *x, double *r, int *diag, double rdt)
Evaluate the residual corresponding to the continuity equation at all interior grid points.
size_t leftExcessSpecies () const
Index of the species on the left boundary with the largest mass fraction.
size_t rightExcessSpecies () const
Index of the species on the right boundary with the largest mass fraction.
Problem Specification
virtual void setupGrid (size_t n, const doublereal *z)
called to set up initial grid, and after grid refinement
virtual void resetBadValues (double *xg)
ThermoPhase & phase ()
Kinetics & kinetics ()
void setThermo (ThermoPhase &th)
Set the thermo manager.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
void setKinetics (Kinetics &kin)
Set the kinetics manager.
virtual void setTransport (shared_ptr< Transport > trans)
Set transport model to existing instance.
void setTransport (Transport &trans)
Set transport model to existing instance.
void setTransportModel (const std::string &trans)
Set the transport model.
std::string transportModel () const
Retrieve transport model.
void enableSoret (bool withSoret)
Enable thermal diffusion, also known as Soret diffusion.
bool withSoret () const
void setPressure (doublereal p)
Set the pressure.
doublereal pressure () const
The current pressure [Pa].
virtual void _getInitialSoln (double *x)
Write the initial solution estimate into array x.
virtual void _finalize (const doublereal *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
void setFixedTempProfile (vector_fp &zfixed, vector_fp &tfixed)
Sometimes it is desired to carry out the simulation using a specified temperature profile, rather than computing it by solving the energy equation.
void setTemperature (size_t j, doublereal t)
doublereal T_fixed (size_t j) const
The fixed temperature value at point j.
Public Member Functions inherited from Domain1D
Domain1D (size_t nv=1, size_t points=1, double time=0.0)
Constructor.
Domain1D (const Domain1D &)=delete
Domain1D & operator= (const Domain1D &)=delete
int domainType ()
Domain type flag.
virtual string type () const
String indicating the domain implemented.
size_t domainIndex ()
The left-to-right location of this domain.
virtual bool isConnector ()
True if the domain is a connector domain.
void setSolution (shared_ptr< Solution > sol)
Set the solution manager.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
virtual void setTransport (shared_ptr< Transport > trans)
Set transport model to existing instance.
const OneDim & container () const
The container holding this domain.
void setContainer (OneDim *c, size_t index)
Specify the container object for this domain, and the position of this domain in the list.
void setBandwidth (int bw=-1)
Set the Jacobian bandwidth. See the discussion of method bandwidth().
size_t bandwidth ()
Set the Jacobian bandwidth for this domain.
virtual void init ()
virtual void setInitialState (doublereal *xlocal=0)
virtual void setState (size_t point, const doublereal *state, doublereal *x)
virtual void resetBadValues (double *xg)
virtual void resize (size_t nv, size_t np)
Refiner & refiner ()
Return a reference to the grid refiner.
size_t nComponents () const
Number of components at each grid point.
void checkComponentIndex (size_t n) const
Check that the specified component index is in range.
void checkComponentArraySize (size_t nn) const
Check that an array size is at least nComponents().
size_t nPoints () const
Number of grid points in this domain.
void checkPointIndex (size_t n) const
Check that the specified point index is in range.
void checkPointArraySize (size_t nn) const
Check that an array size is at least nPoints().
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
void setComponentName (size_t n, const std::string &name)
virtual size_t componentIndex (const std::string &name) const
index of component with name name.
void setBounds (size_t n, doublereal lower, doublereal upper)
void setTransientTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for time-stepping mode.
void setSteadyTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for steady-state mode.
doublereal rtol (size_t n)
Relative tolerance of the nth component.
doublereal atol (size_t n)
Absolute tolerance of the nth component.
double steady_rtol (size_t n)
Steady relative tolerance of the nth component.
double steady_atol (size_t n)
Steady absolute tolerance of the nth component.
double transient_rtol (size_t n)
Transient relative tolerance of the nth component.
double transient_atol (size_t n)
Transient absolute tolerance of the nth component.
doublereal upperBound (size_t n) const
Upper bound on the nth component.
doublereal lowerBound (size_t n) const
Lower bound on the nth component.
void initTimeInteg (doublereal dt, const doublereal *x0)
Prepare to do time stepping with time step dt.
void setSteadyMode ()
Prepare to solve the steady-state problem.
bool steady ()
True if in steady-state mode.
bool transient ()
True if not in steady-state mode.
void needJacUpdate ()
virtual void eval (size_t j, doublereal *x, doublereal *r, integer *mask, doublereal rdt=0.0)
Evaluate the residual function at point j.
size_t index (size_t n, size_t j) const
doublereal value (const doublereal *x, size_t n, size_t j) const
virtual void setJac (MultiJac *jac)
AnyMap serialize (const double *soln) const
Save the state of this domain as an AnyMap.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
shared_ptr< SolutionArray > toArray (bool normalize=false) const
Save the state of this domain to a SolutionArray.
void restore (const AnyMap &state, double *soln, int loglevel)
Restore the solution for this domain from an AnyMap.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
void fromArray (const shared_ptr< SolutionArray > &arr)
Restore the solution for this domain from a SolutionArray.
shared_ptr< Solution > solution () const
Return thermo/kinetics/transport manager used in the domain.
size_t size () const
void locate ()
Find the index of the first grid point in this domain, and the start of its variables in the global solution vector.
virtual size_t loc (size_t j=0) const
Location of the start of the local solution vector in the global solution vector,.
size_t firstPoint () const
The index of the first (that is, left-most) grid point belonging to this domain.
size_t lastPoint () const
The index of the last (that is, right-most) grid point belonging to this domain.
void linkLeft (Domain1D *left)
Set the left neighbor to domain 'left.
void linkRight (Domain1D *right)
Set the right neighbor to domain 'right.'.
void append (Domain1D *right)
Append domain 'right' to this one, and update all links.
Domain1D * left () const
Return a pointer to the left neighbor.
Domain1D * right () const
Return a pointer to the right neighbor.
double prevSoln (size_t n, size_t j) const
Value of component n at point j in the previous solution.
void setID (const std::string &s)
Specify an identifying tag for this domain.
std::string id () const
virtual void showSolution_s (std::ostream &s, const double *x)
virtual void showSolution (const double *x)
Print the solution.
virtual void show (std::ostream &s, const double *x)
Print the solution.
virtual void show (const double *x)
Print the solution.
doublereal z (size_t jlocal) const
doublereal zmin () const
doublereal zmax () const
void setProfile (const std::string &name, double *values, double *soln)
vector_fp & grid ()
const vector_fp & grid () const
doublereal grid (size_t point) const
virtual void setupGrid (size_t n, const doublereal *z)
called to set up initial grid, and after grid refinement
virtual void _getInitialSoln (doublereal *x)
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
virtual doublereal initialValue (size_t n, size_t j)
Initial value of solution component n at grid point j.
virtual void _finalize (const doublereal *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
void forceFullUpdate (bool update)
In some cases, for computational efficiency some properties (such as transport coefficients) may not be updated during Jacobian evaluations.
void setData (shared_ptr< vector< double > > &data)
Set shared data pointer.
Public Attributes
double m_zfixed = Undef
Location of the point where temperature is fixed.
double m_tfixed = -1.0
Temperature at the point used to fix the flame location.
Protected Member Functions
virtual AnyMap getMeta () const
Retrieve meta data.
virtual void setMeta (const AnyMap &state)
Retrieve meta data.
doublereal wdot (size_t k, size_t j) const
void getWdot (doublereal *x, size_t j)
Write the net production rates at point j into array m_wdot
virtual void updateProperties (size_t jg, double *x, size_t jmin, size_t jmax)
Update the properties (thermo, transport, and diffusion flux).
virtual void evalResidual (double *x, double *rsd, int *diag, double rdt, size_t jmin, size_t jmax)
Evaluate the residual function.
void updateThermo (const doublereal *x, size_t j0, size_t j1)
Update the thermodynamic properties from point j0 to point j1 (inclusive), based on solution x.
doublereal shear (const doublereal *x, size_t j) const
doublereal divHeatFlux (const doublereal *x, size_t j) const
size_t mindex (size_t k, size_t j, size_t m)
virtual void updateDiffFluxes (const doublereal *x, size_t j0, size_t j1)
Update the diffusive mass fluxes.
virtual void grad_hk (const double *x, size_t j)
Get the gradient of species specific molar enthalpies.
virtual void updateTransport (doublereal *x, size_t j0, size_t j1)
Update the transport properties at grid points in the range from j0 to j1, based on solution x.
Solution components
doublereal T (const doublereal *x, size_t j) const
doublereal & T (doublereal *x, size_t j)
doublereal T_prev (size_t j) const
doublereal rho_u (const doublereal *x, size_t j) const
doublereal u (const doublereal *x, size_t j) const
doublereal V (const doublereal *x, size_t j) const
doublereal V_prev (size_t j) const
doublereal lambda (const doublereal *x, size_t j) const
doublereal Y (const doublereal *x, size_t k, size_t j) const
doublereal & Y (doublereal *x, size_t k, size_t j)
doublereal Y_prev (size_t k, size_t j) const
doublereal X (const doublereal *x, size_t k, size_t j) const
doublereal flux (size_t k, size_t j) const
convective spatial derivatives.
These use upwind differencing, assuming u(z) is negative
doublereal dVdz (const doublereal *x, size_t j) const
doublereal dYdz (const doublereal *x, size_t k, size_t j) const
doublereal dTdz (const doublereal *x, size_t j) const
virtual AnyMap getMeta () const
Retrieve meta data.
virtual void setMeta (const AnyMap &meta)
Retrieve meta data.
Protected Attributes
double m_press = -1.0
vector_fp m_dz
vector_fp m_rho
vector_fp m_wtm
vector_fp m_wt
vector_fp m_cp
vector_fp m_visc
vector_fp m_tcon
vector_fp m_diff
vector_fp m_multidiff
Array2D m_dthermal
Array2D m_flux
Array2D m_hk
Array of size m_nsp by m_points for saving molar enthalpies.
Array2D m_dhk_dz
Array of size m_nsp by m_points -1 for saving enthalpy fluxes.
Array2D m_wdot
size_t m_nsp
ThermoPhase * m_thermo = nullptr
Kinetics * m_kin = nullptr
Transport * m_trans = nullptr
double m_epsilon_left = 0.0
double m_epsilon_right = 0.0
std::vector< size_t > m_kRadiating
Indices within the ThermoPhase of the radiating species.
std::vector< bool > m_do_energy
bool m_do_soret = false
std::vector< bool > m_do_species
bool m_do_multicomponent = false
bool m_do_radiation = false
flag for the radiative heat loss
vector_fp m_qdotRadiation
radiative heat loss vector
vector_fp m_fixedtemp
vector_fp m_zfix
vector_fp m_tfix
size_t m_kExcessLeft = 0
Index of species with a large mass fraction at each boundary, for which the mass fraction may be calculated as 1 minus the sum of the other mass fractions.
size_t m_kExcessRight = 0
bool m_dovisc
bool m_isFree
bool m_usesLambda
Protected Attributes inherited from Domain1D
shared_ptr< vector< double > > m_state
data pointer shared from OneDim
double m_rdt = 0.0
size_t m_nv = 0
size_t m_points
vector_fp m_slast
vector_fp m_max
vector_fp m_min
vector_fp m_rtol_ss
vector_fp m_rtol_ts
vector_fp m_atol_ss
vector_fp m_atol_ts
vector_fp m_z
OneDim * m_container = nullptr
size_t m_index
int m_type = 0
size_t m_iloc = 0
Starting location within the solution vector for unknowns that correspond to this domain.
size_t m_jstart = 0
Domain1D * m_left = nullptr
Domain1D * m_right = nullptr
std::string m_id
Identity tag for the domain.
std::unique_ptr< Refiner > m_refiner
std::vector< std::string > m_name
int m_bw = -1
bool m_force_full_update = false
shared_ptr< Solution > m_solution
Composite thermo/kinetics/transport handler.
Private Attributes
vector_fp m_ybar
Detailed Description
This class represents 1D flow domains that satisfy the one-dimensional similarity solution for chemically-reacting, axisymmetric flows.
Definition at line 40 of file StFlow.h.
Constructor & Destructor Documentation
StFlow() [1/3]
StFlow (ThermoPhase * ph = 0, size_t nsp = 1, size_t points = 1)
Create a new flow domain.
Parameters
ph Object representing the gas phase. This object will be used to evaluate all thermodynamic, kinetic, and transport properties.
nsp Number of species.
points Initial number of grid points
Definition at line 19 of file StFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_L, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, Cantera::c_offset_Y, StFlow::m_dhk_dz, StFlow::m_hk, StFlow::m_kRadiating, StFlow::m_qdotRadiation, Domain1D::m_type, ThermoPhase::maxTemp(), Phase::molecularWeights(), Cantera::npos, Phase::nSpecies(), Phase::pressure(), Array2D::resize(), Domain1D::resize(), StFlow::setPressure(), StFlow::setupGrid(), and Phase::speciesIndex().
StFlow() [2/3]
StFlow (shared_ptr< ThermoPhase > th, size_t nsp = 1, size_t points = 1)
Delegating constructor.
Definition at line 93 of file StFlow.cpp.
References Solution::create(), and Domain1D::m_solution.
StFlow() [3/3]
StFlow (shared_ptr< Solution > sol, const std::string & id = "", size_t points = 1)
Create a new flow domain.
Parameters
sol Solution object used to evaluate all thermodynamic, kinetic, and transport properties
id name of flow domain
points initial number of grid points
Definition at line 100 of file StFlow.cpp.
References Domain1D::m_id, Domain1D::m_solution, StFlow::setKinetics(), StFlow::setTransport(), StFlow::setTransportModel(), Transport::transportModel(), and Cantera::warn_deprecated().
~StFlow()
~StFlow ()
Definition at line 121 of file StFlow.cpp.
Member Function Documentation
type()
string type () const virtual
String indicating the domain implemented.
Since
New in Cantera 3.0.
Todo:
Transition back to domainType after Cantera 3.0
Reimplemented from Domain1D.
Reimplemented in IonFlow.
Definition at line 128 of file StFlow.cpp.
Referenced by StFlow::doElectricField(), StFlow::fixElectricField(), StFlow::getSolvingStage(), StFlow::setSolvingStage(), and StFlow::solveElectricField().
setupGrid()
void setupGrid (size_t n, const doublereal * z) virtual
called to set up initial grid, and after grid refinement
Reimplemented from Domain1D.
Definition at line 212 of file StFlow.cpp.
References StFlow::resize().
Referenced by StFlow::fromArray(), and StFlow::StFlow().
resetBadValues()
void resetBadValues (double * xg) virtual
When called, this function should reset "bad" values in the state vector such as negative species concentrations. This function may be called after a failed solution attempt.
Reimplemented from Domain1D.
Definition at line 227 of file StFlow.cpp.
References Cantera::c_offset_Y, Phase::getMassFractions(), Domain1D::loc(), and Phase::setMassFractions().
phase()
ThermoPhase & phase () inline
Definition at line 75 of file StFlow.h.
kinetics()
Kinetics & kinetics () inline
Definition at line 79 of file StFlow.h.
setThermo()
void setThermo (ThermoPhase & th)
Set the thermo manager.
Deprecated:
To be removed after Cantera 3.0 (unused)
Definition at line 138 of file StFlow.cpp.
References Cantera::warn_deprecated().
setKinetics() [1/2]
void setKinetics (shared_ptr< Kinetics > kin) virtual
Set the kinetics manager.
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 143 of file StFlow.cpp.
References Domain1D::m_solution.
Referenced by IonFlow::IonFlow(), and StFlow::StFlow().
setKinetics() [2/2]
void setKinetics (Kinetics & kin)
Set the kinetics manager.
Deprecated:
To be removed after Cantera 3.0; replaced by Domain1D::setKinetics
Definition at line 154 of file StFlow.cpp.
References Cantera::warn_deprecated().
setTransport() [1/2]
void setTransport (shared_ptr< Transport > trans) virtual
Set transport model to existing instance.
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 161 of file StFlow.cpp.
References Domain1D::m_solution, Array2D::resize(), and Transport::transportModel().
Referenced by IonFlow::IonFlow(), and StFlow::StFlow().
setTransport() [2/2]
void setTransport (Transport & trans)
Set transport model to existing instance.
Deprecated:
To be removed after Cantera 3.0; replaced by Domain1D::setKinetics
Definition at line 252 of file StFlow.cpp.
References Array2D::resize(), Transport::transportModel(), and Cantera::warn_deprecated().
setTransportModel()
void setTransportModel (const std::string & trans)
Set the transport model.
Since
New in Cantera 3.0.
Definition at line 237 of file StFlow.cpp.
References Domain1D::m_solution.
Referenced by IonFlow::IonFlow(), StFlow::setMeta(), and StFlow::StFlow().
transportModel()
std::string transportModel () const
Retrieve transport model.
Since
New in Cantera 3.0.
Definition at line 248 of file StFlow.cpp.
References Transport::transportModel().
enableSoret()
void enableSoret (bool withSoret) inline
Enable thermal diffusion, also known as Soret diffusion.
Requires that multicomponent transport properties be enabled to carry out calculations.
Definition at line 113 of file StFlow.h.
withSoret()
bool withSoret () const inline
Definition at line 116 of file StFlow.h.
setPressure()
void setPressure (doublereal p) inline
Set the pressure.
Since the flow equations are for the limit of small Mach number, the pressure is very nearly constant throughout the flow.
Definition at line 122 of file StFlow.h.
Referenced by StFlow::StFlow().
pressure()
doublereal pressure () const inline
The current pressure [Pa].
Definition at line 127 of file StFlow.h.
_getInitialSoln()
void _getInitialSoln (double * x) virtual
Write the initial solution estimate into array x.
Reimplemented from Domain1D.
Definition at line 271 of file StFlow.cpp.
References Phase::density(), Phase::getMassFractions(), and Phase::temperature().
_finalize()
void _finalize (const doublereal * x) virtual
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
In such cases, the parameters may be set in method _finalize. This method is called just before the Newton solver is called, and the x array is guaranteed to be the local solution vector for this domain that will be used as the initial guess. If no such parameters need to be set, then method _finalize does not need to be overloaded.
Reimplemented from Domain1D.
Reimplemented in IonFlow.
Definition at line 304 of file StFlow.cpp.
References Cantera::linearInterp(), StFlow::m_tfixed, StFlow::m_zfixed, and Cantera::Undef.
Referenced by IonFlow::_finalize().
setFixedTempProfile()
void setFixedTempProfile (vector_fp & zfixed, vector_fp & tfixed) inline
Sometimes it is desired to carry out the simulation using a specified temperature profile, rather than computing it by solving the energy equation.
This method specifies this profile.
Definition at line 139 of file StFlow.h.
setTemperature()
void setTemperature (size_t j, doublereal t) inline
Set the temperature fixed point at grid point j, and disable the energy equation so that the solution will be held to this value.
Definition at line 148 of file StFlow.h.
T_fixed()
doublereal T_fixed (size_t j) const inline
The fixed temperature value at point j.
Definition at line 154 of file StFlow.h.
Referenced by StFlow::evalResidual(), and StFlow::evalRightBoundary().
componentName()
string componentName (size_t n) const virtual
Name of the nth component. May be overloaded.
Reimplemented from Domain1D.
Definition at line 682 of file StFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_L, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, Cantera::c_offset_Y, and Phase::speciesName().
Referenced by StFlow::asArray(), StFlow::componentIndex(), and StFlow::fromArray().
componentIndex()
size_t componentIndex (const std::string & name) const virtual
index of component with name name.
Reimplemented from Domain1D.
Definition at line 704 of file StFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_L, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, Cantera::c_offset_Y, and StFlow::componentName().
Referenced by StFlow::asArray().
componentActive()
bool componentActive (size_t n) const virtual
Returns true if the specified component is an active part of the solver state.
Reimplemented in IonFlow.
Definition at line 727 of file StFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_L, and Cantera::c_offset_V.
Referenced by StFlow::asArray(), IonFlow::componentActive(), and StFlow::fromArray().
show()
void show (const double * x) virtual
Print the solution.
Reimplemented from Domain1D.
Definition at line 623 of file StFlow.cpp.
References StFlow::m_do_radiation, StFlow::m_qdotRadiation, Domain1D::show(), and Cantera::writelog().
asArray()
shared_ptr< SolutionArray > asArray (const double * soln) const virtual
Save the state of this domain as a SolutionArray.
Parameters
soln local solution vector for this domain
Todo:
Despite the method's name, data are copied; the intent is to access data directly in future revisions, where a non-const version will be implemented.
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 790 of file StFlow.cpp.
References Cantera::c_offset_Y, StFlow::componentActive(), StFlow::componentIndex(), StFlow::componentName(), SolutionArray::create(), StFlow::getMeta(), StFlow::m_do_radiation, StFlow::m_qdotRadiation, Domain1D::m_solution, Domain1D::nComponents(), and Domain1D::nPoints().
fromArray()
void fromArray (SolutionArray & arr, double * soln) virtual
Restore the solution for this domain from a SolutionArray.
Parameters
[in] arr SolutionArray defining the state of this domain
[out] soln Value of the solution vector, local to this domain
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 824 of file StFlow.cpp.
References AnyValue::as(), StFlow::componentActive(), StFlow::componentName(), SolutionArray::getComponent(), SolutionArray::hasComponent(), Domain1D::loc(), SolutionArray::meta(), Domain1D::nComponents(), Domain1D::nPoints(), Cantera::npos, Phase::pressure(), SolutionArray::setLoc(), Domain1D::setMeta(), StFlow::setMeta(), StFlow::setupGrid(), SolutionArray::thermo(), StFlow::updateProperties(), and Cantera::warn_user().
setFreeFlow()
void setFreeFlow () inline
Set flow configuration for freely-propagating flames, using an internal point with a fixed temperature as the condition to determine the inlet mass flux.
Definition at line 175 of file StFlow.h.
References Domain1D::m_type.
Referenced by DomainFactory::DomainFactory().
setAxisymmetricFlow()
void setAxisymmetricFlow () inline
Set flow configuration for axisymmetric counterflow flames, using specified inlet mass fluxes.
Definition at line 184 of file StFlow.h.
References Domain1D::m_type.
Referenced by DomainFactory::DomainFactory().
setUnstrainedFlow()
void setUnstrainedFlow () inline
Set flow configuration for burner-stabilized flames, using specified inlet mass fluxes.
Definition at line 193 of file StFlow.h.
References Domain1D::m_type.
Referenced by DomainFactory::DomainFactory().
flowType()
string flowType () const virtual
Return the type of flow domain being represented, either "Free Flame" or "Axisymmetric Stagnation".
See also
setFreeFlow setAxisymmetricFlow
Deprecated:
To be removed after Cantera 3.0; replaced by type.
Definition at line 854 of file StFlow.cpp.
References Domain1D::m_type, and Cantera::warn_deprecated().
solveEnergyEqn()
void solveEnergyEqn (size_t j = npos)
Definition at line 922 of file StFlow.cpp.
getSolvingStage()
size_t getSolvingStage () const virtual
Get the solving stage (used by IonFlow specialization)
Since
New in Cantera 3.0
Reimplemented in IonFlow.
Definition at line 946 of file StFlow.cpp.
References StFlow::type().
setSolvingStage()
void setSolvingStage (const size_t stage) virtual
Solving stage mode for handling ionized species (used by IonFlow specialization)
stage=1: the fluxes of charged species are set to zero
stage=2: the electric field equation is solved, and the drift flux for ionized species is evaluated
Reimplemented in IonFlow.
Definition at line 952 of file StFlow.cpp.
References StFlow::type().
solveElectricField()
void solveElectricField (size_t j = npos) virtual
Set to solve electric field in a point (used by IonFlow specialization)
Reimplemented in IonFlow.
Definition at line 958 of file StFlow.cpp.
References StFlow::type().
fixElectricField()
void fixElectricField (size_t j = npos) virtual
Set to fix voltage in a point (used by IonFlow specialization)
Reimplemented in IonFlow.
Definition at line 964 of file StFlow.cpp.
References StFlow::type().
doElectricField()
bool doElectricField (size_t j) const virtual
Retrieve flag indicating whether electric field is solved or not (used by IonFlow specialization)
Reimplemented in IonFlow.
Definition at line 970 of file StFlow.cpp.
References StFlow::type().
enableRadiation()
void enableRadiation (bool doRadiation) inline
Turn radiation on / off.
The simple radiation model used was established by Y. Liu and B. Rogg [Y. Liu and B. Rogg, Modelling of thermally radiating diffusion flames with detailed chemistry and transport, EUROTHERM Seminars, 17:114-127, 1991]. This model considers the radiation of CO2 and H2O.
Definition at line 235 of file StFlow.h.
References StFlow::m_do_radiation.
radiationEnabled()
bool radiationEnabled () const inline
Returns true if the radiation term in the energy equation is enabled.
Definition at line 240 of file StFlow.h.
References StFlow::m_do_radiation.
radiativeHeatLoss()
double radiativeHeatLoss (size_t j) const inline
Return radiative heat loss at grid point j.
Definition at line 245 of file StFlow.h.
References StFlow::m_qdotRadiation.
setBoundaryEmissivities()
void setBoundaryEmissivities (double e_left, double e_right)
Set the emissivities for the boundary values.
Reads the emissivities for the left and right boundary values in the radiative term and writes them into the variables, which are used for the calculation.
Definition at line 976 of file StFlow.cpp.
leftEmissivity()
double leftEmissivity () const inline
Return emissivity at left boundary.
Definition at line 258 of file StFlow.h.
rightEmissivity()
double rightEmissivity () const inline
Return emissivity at right boundary.
Definition at line 261 of file StFlow.h.
fixTemperature()
void fixTemperature (size_t j = npos)
Definition at line 990 of file StFlow.cpp.
doEnergy()
bool doEnergy (size_t j) inline
Definition at line 265 of file StFlow.h.
resize()
void resize (size_t components, size_t points) virtual
Change the grid size. Called after grid refinement.
Reimplemented from Domain1D.
Reimplemented in IonFlow.
Definition at line 186 of file StFlow.cpp.
References StFlow::m_dhk_dz, StFlow::m_hk, StFlow::m_qdotRadiation, Array2D::resize(), and Domain1D::resize().
Referenced by IonFlow::resize(), and StFlow::setupGrid().
setGas()
void setGas (const doublereal * x, size_t j)
Set the gas object state to be consistent with the solution at point j.
Definition at line 280 of file StFlow.cpp.
References Cantera::c_offset_Y, Phase::setMassFractions_NoNorm(), Phase::setPressure(), and Phase::setTemperature().
Referenced by ReactingSurf1D::eval(), StFlow::evalResidual(), StFlow::getWdot(), and StFlow::updateThermo().
setGasAtMidpoint()
void setGasAtMidpoint (const doublereal * x, size_t j)
Set the gas state to be consistent with the solution at the midpoint between j and j + 1.
Definition at line 288 of file StFlow.cpp.
References Cantera::c_offset_Y, Phase::setMassFractions_NoNorm(), Phase::setPressure(), and Phase::setTemperature().
Referenced by IonFlow::updateTransport(), and StFlow::updateTransport().
density()
doublereal density (size_t j) const inline
Definition at line 279 of file StFlow.h.
fixed_mdot()
bool fixed_mdot () virtual
Definition at line 300 of file StFlow.cpp.
setViscosityFlag()
void setViscosityFlag (bool dovisc) inline
Definition at line 285 of file StFlow.h.
eval()
void eval (size_t j, doublereal * x, doublereal * r, integer * mask, doublereal rdt) virtual
Evaluate the residual function for axisymmetric stagnation flow. If j == npos, the residual function is evaluated at all grid points. Otherwise, the residual function is only evaluated at grid points j-1, j, and j+1. This option is used to efficiently evaluate the Jacobian numerically.
Reimplemented from Domain1D.
Definition at line 351 of file StFlow.cpp.
References StFlow::evalResidual(), Domain1D::firstPoint(), Domain1D::lastPoint(), Domain1D::loc(), Cantera::npos, and StFlow::updateProperties().
evalRightBoundary()
void evalRightBoundary (double * x, double * res, int * diag, double rdt) virtual
Evaluate all residual components at the right boundary.
Definition at line 1014 of file StFlow.cpp.
References Cantera::c_offset_L, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, Cantera::c_offset_Y, StFlow::rightExcessSpecies(), and StFlow::T_fixed().
Referenced by StFlow::evalResidual().
evalContinuity()
void evalContinuity (size_t j, double * x, double * r, int * diag, double rdt) virtual
Evaluate the residual corresponding to the continuity equation at all interior grid points.
Definition at line 1045 of file StFlow.cpp.
References Cantera::c_offset_U, StFlow::m_tfixed, and StFlow::m_zfixed.
Referenced by StFlow::evalResidual().
leftExcessSpecies()
size_t leftExcessSpecies () const inline
Index of the species on the left boundary with the largest mass fraction.
Definition at line 309 of file StFlow.h.
References StFlow::m_kExcessLeft.
Referenced by StFlow::evalResidual().
rightExcessSpecies()
size_t rightExcessSpecies () const inline
Index of the species on the right boundary with the largest mass fraction.
Definition at line 314 of file StFlow.h.
Referenced by Outlet1D::eval(), OutletRes1D::eval(), ReactingSurf1D::eval(), and StFlow::evalRightBoundary().
getMeta()
AnyMap getMeta () const protected virtual
Retrieve meta data.
Reimplemented from Domain1D.
Definition at line 741 of file StFlow.cpp.
References AnyValue::asString(), AnyValue::empty(), Domain1D::getMeta(), AnyBase::getMetadata(), ThermoPhase::input(), StFlow::m_do_radiation, StFlow::m_tfixed, StFlow::m_zfixed, Phase::name(), Phase::speciesName(), Transport::transportModel(), and Cantera::Undef.
Referenced by StFlow::asArray().
setMeta()
void setMeta (const AnyMap & meta) protected virtual
Retrieve meta data.
Reimplemented from Domain1D.
Definition at line 866 of file StFlow.cpp.
References AnyValue::asBool(), AnyValue::asVector(), AnyMap::getDouble(), AnyMap::getString(), AnyMap::hasKey(), AnyValue::isScalar(), StFlow::m_do_radiation, StFlow::m_tfixed, StFlow::m_zfixed, Domain1D::nPoints(), Phase::nSpecies(), and StFlow::setTransportModel().
Referenced by StFlow::fromArray().
wdot()
doublereal wdot (size_t k, size_t j) const inline protected
Definition at line 322 of file StFlow.h.
getWdot()
void getWdot (doublereal * x, size_t j) inline protected
Write the net production rates at point j into array m_wdot
Definition at line 327 of file StFlow.h.
References Kinetics::getNetProductionRates(), and StFlow::setGas().
Referenced by StFlow::evalResidual().
updateProperties()
void updateProperties (size_t jg, double * x, size_t jmin, size_t jmax) protected virtual
Update the properties (thermo, transport, and diffusion flux).
This function is called in eval after the points which need to be updated are defined.
Definition at line 379 of file StFlow.cpp.
References Cantera::c_offset_Y, StFlow::m_kExcessLeft, Cantera::npos, StFlow::updateDiffFluxes(), StFlow::updateThermo(), and StFlow::updateTransport().
Referenced by StFlow::eval(), and StFlow::fromArray().
evalResidual()
void evalResidual (double * x, double * rsd, int * diag, double rdt, size_t jmin, size_t jmax) protected virtual
Evaluate the residual function.
This function is called in eval after updateProperties is called.
Reimplemented in IonFlow.
Definition at line 403 of file StFlow.cpp.
References Cantera::c_offset_E, Cantera::c_offset_L, Cantera::c_offset_T, Cantera::c_offset_U, Cantera::c_offset_V, Cantera::c_offset_Y, StFlow::evalContinuity(), StFlow::evalRightBoundary(), StFlow::getWdot(), StFlow::grad_hk(), StFlow::leftExcessSpecies(), StFlow::m_dhk_dz, StFlow::m_do_radiation, StFlow::m_hk, StFlow::m_kRadiating, StFlow::m_qdotRadiation, Cantera::npos, Cantera::OneAtm, StFlow::setGas(), Cantera::StefanBoltz, and StFlow::T_fixed().
Referenced by StFlow::eval(), and IonFlow::evalResidual().
updateThermo()
void updateThermo (const doublereal * x, size_t j0, size_t j1) inline protected
Update the thermodynamic properties from point j0 to point j1 (inclusive), based on solution x.
Definition at line 346 of file StFlow.h.
References ThermoPhase::cp_mass(), Phase::density(), ThermoPhase::getPartialMolarEnthalpies(), StFlow::m_hk, Phase::meanMolecularWeight(), and StFlow::setGas().
Referenced by StFlow::updateProperties().
T() [1/2]
doublereal T (const doublereal * x, size_t j) const inline protected
Definition at line 359 of file StFlow.h.
T() [2/2]
doublereal & T (doublereal * x, size_t j) inline protected
Definition at line 362 of file StFlow.h.
T_prev()
doublereal T_prev (size_t j) const inline protected
Definition at line 365 of file StFlow.h.
rho_u()
doublereal rho_u (const doublereal * x, size_t j) const inline protected
Definition at line 369 of file StFlow.h.
u()
doublereal u (const doublereal * x, size_t j) const inline protected
Definition at line 373 of file StFlow.h.
V()
doublereal V (const doublereal * x, size_t j) const inline protected
Definition at line 377 of file StFlow.h.
V_prev()
doublereal V_prev (size_t j) const inline protected
Definition at line 380 of file StFlow.h.
lambda()
doublereal lambda (const doublereal * x, size_t j) const inline protected
Definition at line 384 of file StFlow.h.
Y() [1/2]
doublereal Y (const doublereal * x, size_t k, size_t j) const inline protected
Definition at line 388 of file StFlow.h.
Y() [2/2]
doublereal & Y (doublereal * x, size_t k, size_t j) inline protected
Definition at line 392 of file StFlow.h.
Y_prev()
doublereal Y_prev (size_t k, size_t j) const inline protected
Definition at line 396 of file StFlow.h.
X()
doublereal X (const doublereal * x, size_t k, size_t j) const inline protected
Definition at line 400 of file StFlow.h.
flux()
doublereal flux (size_t k, size_t j) const inline protected
Definition at line 404 of file StFlow.h.
dVdz()
doublereal dVdz (const doublereal * x, size_t j) const inline protected
Definition at line 413 of file StFlow.h.
dYdz()
doublereal dYdz (const doublereal * x, size_t k, size_t j) const inline protected
Definition at line 418 of file StFlow.h.
dTdz()
doublereal dTdz (const doublereal * x, size_t j) const inline protected
Definition at line 423 of file StFlow.h.
shear()
doublereal shear (const doublereal * x, size_t j) const inline protected
Definition at line 429 of file StFlow.h.
divHeatFlux()
doublereal divHeatFlux (const doublereal * x, size_t j) const inline protected
Definition at line 435 of file StFlow.h.
mindex()
size_t mindex (size_t k, size_t j, size_t m) inline protected
Definition at line 441 of file StFlow.h.
updateDiffFluxes()
void updateDiffFluxes (const doublereal * x, size_t j0, size_t j1) protected virtual
Update the diffusive mass fluxes.
Reimplemented in IonFlow.
Definition at line 640 of file StFlow.cpp.
Referenced by StFlow::updateProperties().
grad_hk()
void grad_hk (const double * x, size_t j) protected virtual
Get the gradient of species specific molar enthalpies.
Definition at line 1081 of file StFlow.cpp.
References StFlow::m_dhk_dz, and StFlow::m_hk.
Referenced by StFlow::evalResidual().
updateTransport()
void updateTransport (doublereal * x, size_t j0, size_t j1) protected virtual
Update the transport properties at grid points in the range from j0 to j1, based on solution x.
Reimplemented in IonFlow.
Definition at line 593 of file StFlow.cpp.
References Phase::density(), Transport::getMixDiffCoeffs(), Transport::getMultiDiffCoeffs(), Transport::getThermalDiffCoeffs(), Phase::meanMolecularWeight(), Array2D::ptrColumn(), StFlow::setGasAtMidpoint(), Transport::thermalConductivity(), and Transport::viscosity().
Referenced by StFlow::updateProperties(), and IonFlow::updateTransport().
Member Data Documentation
m_press
double m_press = -1.0 protected
Definition at line 455 of file StFlow.h.
m_dz
vector_fp m_dz protected
Definition at line 458 of file StFlow.h.
m_rho
vector_fp m_rho protected
Definition at line 461 of file StFlow.h.
m_wtm
vector_fp m_wtm protected
Definition at line 462 of file StFlow.h.
m_wt
vector_fp m_wt protected
Definition at line 465 of file StFlow.h.
m_cp
vector_fp m_cp protected
Definition at line 466 of file StFlow.h.
m_visc
vector_fp m_visc protected
Definition at line 469 of file StFlow.h.
m_tcon
vector_fp m_tcon protected
Definition at line 470 of file StFlow.h.
m_diff
vector_fp m_diff protected
Definition at line 471 of file StFlow.h.
m_multidiff
vector_fp m_multidiff protected
Definition at line 472 of file StFlow.h.
m_dthermal
Array2D m_dthermal protected
Definition at line 473 of file StFlow.h.
m_flux
Array2D m_flux protected
Definition at line 474 of file StFlow.h.
m_hk
Array2D m_hk protected
Array of size m_nsp by m_points for saving molar enthalpies.
Definition at line 477 of file StFlow.h.
Referenced by StFlow::evalResidual(), StFlow::grad_hk(), StFlow::resize(), StFlow::StFlow(), and StFlow::updateThermo().
m_dhk_dz
Array2D m_dhk_dz protected
Array of size m_nsp by m_points -1 for saving enthalpy fluxes.
Definition at line 480 of file StFlow.h.
Referenced by StFlow::evalResidual(), StFlow::grad_hk(), StFlow::resize(), and StFlow::StFlow().
m_wdot
Array2D m_wdot protected
Definition at line 483 of file StFlow.h.
m_nsp
size_t m_nsp protected
Definition at line 485 of file StFlow.h.
m_thermo
ThermoPhase* m_thermo = nullptr protected
Definition at line 487 of file StFlow.h.
m_kin
Kinetics* m_kin = nullptr protected
Definition at line 488 of file StFlow.h.
m_trans
Transport* m_trans = nullptr protected
Definition at line 489 of file StFlow.h.
m_epsilon_left
double m_epsilon_left = 0.0 protected
Definition at line 492 of file StFlow.h.
m_epsilon_right
double m_epsilon_right = 0.0 protected
Definition at line 493 of file StFlow.h.
m_kRadiating
std::vector<size_t> m_kRadiating protected
Indices within the ThermoPhase of the radiating species.
First index is for CO2, second is for H2O.
Definition at line 497 of file StFlow.h.
Referenced by StFlow::evalResidual(), and StFlow::StFlow().
m_do_energy
std::vector<bool> m_do_energy protected
Definition at line 500 of file StFlow.h.
m_do_soret
bool m_do_soret = false protected
Definition at line 501 of file StFlow.h.
m_do_species
std::vector<bool> m_do_species protected
Definition at line 502 of file StFlow.h.
m_do_multicomponent
bool m_do_multicomponent = false protected
Definition at line 503 of file StFlow.h.
m_do_radiation
bool m_do_radiation = false protected
flag for the radiative heat loss
Definition at line 506 of file StFlow.h.
Referenced by StFlow::asArray(), StFlow::enableRadiation(), StFlow::evalResidual(), StFlow::getMeta(), StFlow::radiationEnabled(), StFlow::setMeta(), and StFlow::show().
m_qdotRadiation
vector_fp m_qdotRadiation protected
radiative heat loss vector
Definition at line 509 of file StFlow.h.
Referenced by StFlow::asArray(), StFlow::evalResidual(), StFlow::radiativeHeatLoss(), StFlow::resize(), StFlow::show(), and StFlow::StFlow().
m_fixedtemp
vector_fp m_fixedtemp protected
Definition at line 512 of file StFlow.h.
m_zfix
vector_fp m_zfix protected
Definition at line 513 of file StFlow.h.
m_tfix
vector_fp m_tfix protected
Definition at line 514 of file StFlow.h.
m_kExcessLeft
size_t m_kExcessLeft = 0 protected
Index of species with a large mass fraction at each boundary, for which the mass fraction may be calculated as 1 minus the sum of the other mass fractions.
Definition at line 519 of file StFlow.h.
Referenced by StFlow::leftExcessSpecies(), and StFlow::updateProperties().
m_kExcessRight
size_t m_kExcessRight = 0 protected
Definition at line 520 of file StFlow.h.
m_dovisc
bool m_dovisc protected
Definition at line 522 of file StFlow.h.
m_isFree
bool m_isFree protected
Definition at line 523 of file StFlow.h.
m_usesLambda
bool m_usesLambda protected
Definition at line 524 of file StFlow.h.
m_zfixed
double m_zfixed = Undef
Location of the point where temperature is fixed.
Definition at line 532 of file StFlow.h.
Referenced by StFlow::_finalize(), StFlow::evalContinuity(), Sim1D::fixedTemperatureLocation(), StFlow::getMeta(), Sim1D::setFixedTemperature(), and StFlow::setMeta().
m_tfixed
double m_tfixed = -1.0
Temperature at the point used to fix the flame location.
Definition at line 535 of file StFlow.h.
Referenced by StFlow::_finalize(), StFlow::evalContinuity(), Sim1D::fixedTemperature(), Sim1D::fixedTemperatureLocation(), StFlow::getMeta(), Sim1D::setFixedTemperature(), and StFlow::setMeta().
m_ybar
vector_fp m_ybar private
Definition at line 538 of file StFlow.h.
The documentation for this class was generated from the following files:
StFlow.h
StFlow.cpp