Cantera: ShomatePoly Class Reference
ShomatePoly Class Reference
Models of Phases of Matter » Thermodynamic Properties » Species Reference-State Thermodynamic Properties
The Shomate polynomial parameterization for one temperature range for one species.
#include <ShomatePoly.h>
Public Member Functions
ShomatePoly (double tlow, double thigh, double pref, const double *coeffs)
Constructor with all input data.
void setParameters (const vector_fp &coeffs)
Set array of 7 polynomial coefficients.
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
This utility function returns the type of parameterization and all of the parameters for the species.
virtual void getParameters (AnyMap &thermo) const
Store the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 ()
Restore the original heat of formation for this species.
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)=delete
SpeciesThermoInterpType & operator= (const SpeciesThermoInterpType &b)=delete
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual void setMinTemp (double Tmin)
Set the minimum temperature at which the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual void setMaxTemp (double Tmax)
Set the maximum temperature at which the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void setRefPressure (double Pref)
Set the reference pressure [Pa].
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual size_t nCoeffs () const
This utility function returns the number of coefficients for a given type of species parameterization.
virtual void reportParameters (size_t &index, int &type, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure, doublereal *const coeffs) const
This utility function returns the type of parameterization and all of the parameters for the species.
AnyMap parameters (bool withInput=true) const
Return the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 ()
Restore the original heat of formation for this species.
const AnyMap & input () const
Access input data associated with the species thermo definition.
AnyMap & input ()
Protected Attributes
vector_fp m_coeff
Array of coefficients.
double m_coeff5_orig
Protected Attributes inherited from SpeciesThermoInterpType
double m_lowT = 0.0
lowest valid temperature
double m_highT = 0.0
Highest valid temperature.
double m_Pref = 0.0
Reference state pressure.
AnyMap m_input
Additional Inherited Members
virtual void getParameters (AnyMap &thermo) const
Store the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
Detailed Description
The Shomate polynomial parameterization for one temperature range for one species.
Seven coefficients \((A,\dots,G)\) are used to represent \(c_p^0(T)\), \(h^0(T)\), and \(s^0(T) \) as polynomials in the temperature, \(T \) :
\[ \tilde{c}_p^0(T) = A + B t + C t^2 + D t^3 + \frac{E}{t^2} \]
\[ \tilde{h}^0(T) = A t + \frac{B t^2}{2} + \frac{C t^3}{3} + \frac{D t^4}{4} - \frac{E}{t} + F. \]
\[ \tilde{s}^0(T) = A\ln t + B t + \frac{C t^2}{2} + \frac{D t^3}{3} - \frac{E}{2t^2} + G. \]
In the above expressions, the thermodynamic polynomials are expressed in dimensional units, but the temperature, \(t \), is divided by 1000. The following dimensions are assumed in the above expressions:
\(\tilde{c}_p^0(T)\) = Heat Capacity (J/gmol*K)
\(\tilde{h}^0(T) \) = standard Enthalpy (kJ/gmol)
\(\tilde{s}^0(T) \)= standard Entropy (J/gmol*K)
\(t \)= temperature (K) / 1000.
For more information about Shomate polynomials, see the NIST website, http://webbook.nist.gov/
Before being used within Cantera, the dimensions must be adjusted to those used by Cantera (for example, Joules and kmol).
Definition at line 58 of file ShomatePoly.h.
Constructor & Destructor Documentation
ShomatePoly() [1/2]
ShomatePoly () inline
Definition at line 61 of file ShomatePoly.h.
ShomatePoly() [2/2]
ShomatePoly (double tlow, double thigh, double pref, const double * coeffs) inline
Constructor with all input data.
Parameters
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients, [A,B,C,D,E,F,G], used to set the parameters for the species standard state.
See the class description for the polynomial representation of the thermo functions in terms of \(A, \dots, G \).
Definition at line 74 of file ShomatePoly.h.
References Cantera::GasConstant, and ShomatePoly::m_coeff.
Member Function Documentation
setParameters()
void setParameters (const vector_fp & coeffs) inline
Set array of 7 polynomial coefficients.
Input values are assumed to be on a kJ/mol basis.
Definition at line 86 of file ShomatePoly.h.
References Cantera::GasConstant, and ShomatePoly::m_coeff.
Referenced by ShomatePoly2::setParameters().
reportType()
virtual int reportType () const inline virtual
Returns an integer representing the type of parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 97 of file ShomatePoly.h.
References SHOMATE.
temperaturePolySize()
virtual size_t temperaturePolySize () const inline virtual
Number of terms in the temperature polynomial for this parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 101 of file ShomatePoly.h.
updateTemperaturePoly()
virtual void updateTemperaturePoly (double T, double * T_poly) const inline virtual
Given the temperature T, compute the terms of the temperature polynomial T_poly.
Reimplemented from SpeciesThermoInterpType.
Definition at line 103 of file ShomatePoly.h.
Referenced by ShomatePoly::updatePropertiesTemp(), and ShomatePoly2::updateTemperaturePoly().
updateProperties()
virtual void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
The form and length of the Temperature Polynomial may vary depending on the parameterization.
Parameters
tt vector of evaluated temperature functions
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Form of the temperature polynomial:
t is T/1000.
t[0] = t
t[1] = t*t
t[2] = t[1]*t
t[3] = 1.0/t[1]
t[4] = log(t)
`t[5] = 1.0/t;
Reimplemented from SpeciesThermoInterpType.
Definition at line 125 of file ShomatePoly.h.
References ShomatePoly::m_coeff.
Referenced by ShomatePoly2::updateProperties(), and ShomatePoly::updatePropertiesTemp().
updatePropertiesTemp()
virtual void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non- dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, of the species.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented from SpeciesThermoInterpType.
Definition at line 141 of file ShomatePoly.h.
References ShomatePoly::updateProperties(), and ShomatePoly::updateTemperaturePoly().
Referenced by ShomatePoly::reportHf298(), and ShomatePoly2::updatePropertiesTemp().
reportParameters()
virtual void reportParameters (size_t & index, int & type, doublereal & minTemp, doublereal & maxTemp, doublereal & refPressure, doublereal *const coeffs) const inline virtual
This utility function returns the type of parameterization and all of the parameters for the species.
All parameters are output variables
Parameters
index Species index
type Integer type of the standard type
minTemp output - Minimum temperature
maxTemp output - Maximum temperature
refPressure output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Reimplemented from SpeciesThermoInterpType.
Definition at line 149 of file ShomatePoly.h.
References Cantera::GasConstant, ShomatePoly::m_coeff, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_lowT, SpeciesThermoInterpType::m_Pref, and SHOMATE.
Referenced by ShomatePoly2::reportParameters().
getParameters()
virtual void getParameters (AnyMap & thermo) const inline virtual
Store the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
Reimplemented from SpeciesThermoInterpType.
Definition at line 163 of file ShomatePoly.h.
References Cantera::GasConstant, and ShomatePoly::m_coeff.
Referenced by ShomatePoly2::getParameters().
reportHf298()
virtual doublereal reportHf298 (doublereal *const h298 = 0) const inline virtual
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
h298 If this is nonnull, the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex is returned in h298[m_speciesIndex].
Returns
the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex.
Reimplemented from SpeciesThermoInterpType.
Definition at line 173 of file ShomatePoly.h.
References Cantera::GasConstant, and ShomatePoly::updatePropertiesTemp().
Referenced by ShomatePoly::modifyOneHf298(), ShomatePoly2::modifyOneHf298(), and ShomatePoly2::reportHf298().
modifyOneHf298()
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New) inline virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented from SpeciesThermoInterpType.
Definition at line 179 of file ShomatePoly.h.
References Cantera::GasConstant, ShomatePoly::m_coeff, and ShomatePoly::reportHf298().
Referenced by ShomatePoly2::modifyOneHf298().
resetHf298()
virtual void resetHf298 () inline virtual
Restore the original heat of formation for this species.
Resets changes made by modifyOneHf298().
Reimplemented from SpeciesThermoInterpType.
Definition at line 185 of file ShomatePoly.h.
References ShomatePoly::m_coeff.
Referenced by ShomatePoly2::resetHf298().
Member Data Documentation
m_coeff
vector_fp m_coeff protected
Array of coefficients.
Definition at line 191 of file ShomatePoly.h.
Referenced by ShomatePoly::getParameters(), ShomatePoly::modifyOneHf298(), ShomatePoly::reportParameters(), ShomatePoly::resetHf298(), ShomatePoly::setParameters(), ShomatePoly::ShomatePoly(), and ShomatePoly::updateProperties().
m_coeff5_orig
double m_coeff5_orig protected
Definition at line 192 of file ShomatePoly.h.
The documentation for this class was generated from the following file:
ShomatePoly.h