Cantera: MolalityVPSSTP Class Reference
MolalityVPSSTP Class Reference
#include <MolalityVPSSTP.h>
Public Member Functions
MolalityVPSSTP ()
Default Constructor.
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
void setState_TPM (doublereal t, doublereal p, const compositionMap &m)
Set the temperature (K), pressure (Pa), and molalities.
void setState_TPM (doublereal t, doublereal p, const std::string &m)
Set the temperature (K), pressure (Pa), and molalities.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual std::string report (bool show_thermo=true, doublereal threshold=1e-14) const
returns a summary of the state of the phase as a string
Utilities
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
Utilities for Solvent ID and Molality
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
void setMolalitiesByName (const compositionMap &xMap)
Set the molalities of a phase.
void setMolalitiesByName (const std::string &name)
Set the molalities of a phase.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
int activityConvention () const
We set the convention to molality here.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual double osmoticCoefficient () const
Calculate the osmotic coefficient.
Initialization
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
They are not normally used in application programs. To see how they are used, see importPhase().
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
Public Member Functions inherited from VPStandardStateTP
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
virtual doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual double minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
virtual double maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
VPStandardStateTP ()
Constructor.
virtual ~VPStandardStateTP ()
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
void installPDSS (size_t k, std::unique_ptr< PDSS > &&pdss)
Install a PDSS object for species k
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_DP (double rho, double p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
virtual void getUnscaledMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void applyphScale (doublereal *acMolality) const
Apply the current phScale to a set of activity Coefficients or activities.
Protected Member Functions inherited from VPStandardStateTP
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes
int m_pHScalingType = PHSCALE_PITZER
Scaling to be used for output of single-ion species activity coefficients.
size_t m_indexCLM = npos
Index of the phScale species.
double m_weightSolvent = 18.01528
Molecular weight of the Solvent.
double m_xmolSolventMIN = 0.01
double m_Mnaught = 18.01528E-3
This is the multiplication factor that goes inside log expressions involving the molalities of species.
vector_fp m_molalities
Current value of the molalities of the species in the phase.
Protected Attributes inherited from VPStandardStateTP
double m_Pcurrent = OneAtm
Current value of the pressure - state variable.
double m_minTemp = 0.0
The minimum temperature at which data for all species is valid.
double m_maxTemp = BigNumber
The maximum temperature at which data for all species is valid.
double m_Tlast_ss = -1.0
The last temperature at which the standard state thermodynamic properties were calculated at.
double m_Plast_ss = -1.0
The last pressure at which the Standard State thermodynamic properties were calculated at.
std::vector< std::unique_ptr< PDSS > > m_PDSS_storage
Storage for the PDSS objects for the species.
vector_fp m_h0_RT
Vector containing the species reference enthalpies at T = m_tlast and P = p_ref.
vector_fp m_cp0_R
Vector containing the species reference constant pressure heat capacities at T = m_tlast and P = p_ref.
vector_fp m_g0_RT
Vector containing the species reference Gibbs functions at T = m_tlast and P = p_ref.
vector_fp m_s0_R
Vector containing the species reference entropies at T = m_tlast and P = p_ref.
vector_fp m_V0
Vector containing the species reference molar volumes.
vector_fp m_hss_RT
Vector containing the species Standard State enthalpies at T = m_tlast and P = m_plast.
vector_fp m_cpss_R
Vector containing the species Standard State constant pressure heat capacities at T = m_tlast and P = m_plast.
vector_fp m_gss_RT
Vector containing the species Standard State Gibbs functions at T = m_tlast and P = m_plast.
vector_fp m_sss_R
Vector containing the species Standard State entropies at T = m_tlast and P = m_plast.
vector_fp m_Vss
Vector containing the species standard state volumes at T = m_tlast and P = m_plast.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Private Member Functions
virtual size_t findCLMIndex () const
Returns the index of the Cl- species.
Detailed Description
MolalityVPSSTP is a derived class of ThermoPhase that handles variable pressure standard state methods for calculating thermodynamic properties that are further based on molality-scaled activities. This category incorporates most of the methods for calculating liquid electrolyte thermodynamics that have been developed since the 1970's.
This class adds additional functions onto the ThermoPhase interface that handle molality based standard states. The ThermoPhase class includes a member function, ThermoPhase::activityConvention() that indicates which convention the activities are based on. The default is to assume activities are based on the molar convention. However, classes which derive from the MolalityVPSSTP class return cAC_CONVENTION_MOLALITY from this member function.
The molality of a solute, \(m_i \), is defined as
\[ m_i = \frac{n_i}{\tilde{M}_o n_o} \]
where
\[ \tilde{M}_o = \frac{M_o}{1000} \]
where \(M_o \) is the molecular weight of the solvent. The molality has units of gmol/kg. For the solute, the molality may be considered as the amount of gmol's of solute per kg of solvent, a natural experimental quantity.
The formulas for calculating mole fractions if given the molalities of the solutes is stated below. First calculate \(L^{sum} \), an intermediate quantity.
\[ L^{sum} = \frac{1}{\tilde{M}_o X_o} = \frac{1}{\tilde{M}_o} + \sum_{i\ne o} m_i \]
Then,
\[ X_o = \frac{1}{\tilde{M}_o L^{sum}} \]
\[ X_i = \frac{m_i}{L^{sum}} \]
where \(X_o \) is the mole fraction of solvent, and \(X_o \) is the mole fraction of solute i. Thus, the molality scale and the mole fraction scale offer a one-to-one mapping between each other, except in the limit of a zero solvent mole fraction.
The standard states for thermodynamic objects that derive from MolalityVPSSTP are on the unit molality basis. Chemical potentials of the solutes, \(\mu_k \), and the solvent, \(\mu_o \), which are based on the molality form, have the following general format:
\[ \mu_k = \mu^{\triangle}_k(T,P) + R T ln(\gamma_k^{\triangle} \frac{m_k}{m^\triangle}) \]
\[ \mu_o = \mu^o_o(T,P) + RT ln(a_o) \]
where \(\gamma_k^{\triangle} \) is the molality based activity coefficient for species \(k\).
The chemical potential of the solvent is thus expressed in a different format than the chemical potential of the solutes. Additionally, the activity of the solvent, \(a_o \), is further reexpressed in terms of an osmotic coefficient, \(\phi \).
\[ \phi = \frac{- ln(a_o)}{\tilde{M}_o \sum_{i \ne o} m_i} \]
MolalityVPSSTP::osmoticCoefficient() returns the value of \(\phi \). Note there are a few of definitions of the osmotic coefficient floating around. We use the one defined in (Activity Coefficients in Electrolyte Solutions, K. S. Pitzer CRC Press, Boca Raton, 1991, p. 85, Eqn. 28). This definition is most clearly related to theoretical calculation.
The molar-based activity coefficients \(\gamma_k \) may be calculated from the molality-based activity coefficients, \(\gamma_k^\triangle \) by the following formula.
\[ \gamma_k = \frac{\gamma_k^\triangle}{X_o} \]
For purposes of establishing a convention, the molar activity coefficient of the solvent is set equal to the molality-based activity coefficient of the solvent:
\[ \gamma_o = \gamma_o^\triangle \]
The molality-based and molarity-based standard states may be related to one another by the following formula.
\[ \mu_k^\triangle(T,P) = \mu_k^o(T,P) + R T \ln(\tilde{M}_o m^\triangle) \]
An important convention is followed in all routines that derive from MolalityVPSSTP. Standard state thermodynamic functions and reference state thermodynamic functions return the molality-based quantities. Also all functions which return activities return the molality-based activities. The reason for this convention has been discussed in supporting memos. However, it's important because the term in the equation above is non-trivial. For example it's equal to 2.38 kcal/gmol for water at 298 K.
In order to prevent a singularity, this class includes the concept of a minimum value for the solvent mole fraction. All calculations involving the formulation of activity coefficients and other non-ideal solution behavior adhere to this concept of a minimal value for the solvent mole fraction. This makes sense because these solution behavior were all designed and measured far away from the zero solvent singularity condition and are not applicable in that limit.
This objects add a layer that supports molality. It inherits from VPStandardStateTP.
All objects that derive from this are assumed to have molality based standard states.
Molality based activity coefficients are scaled according to the current pH scale. See the Eq3/6 manual for details.
Activity coefficients for species k may be altered between scales s1 to s2 using the following formula
\[ ln(\gamma_k^{s2}) = ln(\gamma_k^{s1}) + \frac{z_k}{z_j} \left(ln(\gamma_j^{s2}) - ln(\gamma_j^{s1}) \right) \]
where j is any one species. For the NBS scale, j is equal to the Cl- species and
\[ ln(\gamma_{Cl-}^{s2}) = \frac{-A_{\phi} \sqrt{I}}{1.0 + 1.5 \sqrt{I}} \]
The Pitzer scale doesn't actually change anything. The pitzer scale is defined as the raw unscaled activity coefficients produced by the underlying objects.
SetState Strategy
The MolalityVPSSTP object does not have a setState strategy concerning the molalities. It does not keep track of whether the molalities have changed. It's strictly an interfacial layer that writes the current mole fractions to the State object. When molalities are needed it recalculates the molalities from the State object's mole fraction vector.
Todo:
Make two solvent minimum fractions. One would be for calculation of the non-ideal factors. The other one would be for purposes of stoichiometry evaluation. the stoichiometry evaluation one would be a 1E-13 limit. Anything less would create problems with roundoff error.
Definition at line 226 of file MolalityVPSSTP.h.
Constructor & Destructor Documentation
MolalityVPSSTP()
MolalityVPSSTP ()
Default Constructor.
This doesn't do much more than initialize constants with default values for water at 25C. Water molecular weight comes from the default elements definitions. It actually differs slightly from the IAPWS95 value of 18.015268. However, density conservation and therefore element conservation is the more important principle to follow.
Definition at line 21 of file MolalityVPSSTP.cpp.
References ThermoPhase::m_chargeNeutralityNecessary.
Member Function Documentation
phaseOfMatter()
virtual std::string phaseOfMatter () const inline virtual
String indicating the mechanical phase of the matter in this Phase.
All derived phases from MolalityVPSSTP always represent liquids.
Reimplemented from ThermoPhase.
Definition at line 246 of file MolalityVPSSTP.h.
setpHScale()
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
Single ion activity coefficients are not unique in terms of the representing actual measurable quantities.
Parameters
pHscaleType Integer representing the pHscale
Definition at line 31 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_pHScalingType, Cantera::PHSCALE_NBS, and Cantera::PHSCALE_PITZER.
pHScale()
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
Single ion activity coefficients are not unique in terms of the representing actual measurable quantities.
Returns
the pHscale type
Definition at line 40 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_pHScalingType.
setMoleFSolventMin()
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
Note the molality formulation is singular in the limit that the solvent mole fraction goes to zero. Numerically, how this limit is treated and resolved is an ongoing issue within Cantera. The minimum mole fraction must be in the range 0 to 0.9.
Parameters
xmolSolventMIN Input double containing the minimum mole fraction
Definition at line 45 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_xmolSolventMIN.
Referenced by HMWSoln::initThermo(), and IdealMolalSoln::initThermo().
moleFSolventMin()
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
Definition at line 55 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_xmolSolventMIN.
calcMolalities()
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
We calculate the vector of molalities of the species in the phase and store the result internally:
\[ m_i = \frac{X_i}{1000 * M_o * X_{o,p}} \]
where
\(M_o \) is the molecular weight of the solvent
\(X_o \) is the mole fraction of the solvent
\(X_i \) is the mole fraction of the solute.
\(X_{o,p} = \max (X_{o}^{min}, X_o) \)
\(X_{o}^{min} \) = minimum mole fraction of solvent allowed in the denominator.
Definition at line 60 of file MolalityVPSSTP.cpp.
References Phase::getMoleFractions(), Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and MolalityVPSSTP::m_xmolSolventMIN.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), IdealMolalSoln::getActivities(), IdealMolalSoln::getChemPotentials(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getPartialMolarEntropies(), HMWSoln::printCoeffs(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), and MolalityVPSSTP::setMolalitiesByName().
getMolalities()
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
We calculate the vector of molalities of the species in the phase
\[ m_i = \frac{X_i}{1000 * M_o * X_{o,p}} \]
where
\(M_o \) is the molecular weight of the solvent
\(X_o \) is the mole fraction of the solvent
\(X_i \) is the mole fraction of the solute.
\(X_{o,p} = \max (X_{o}^{min}, X_o) \)
\(X_{o}^{min} \) = minimum mole fraction of solvent allowed in the denominator.
Parameters
molal Output vector of molalities. Length: m_kk.
Definition at line 70 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::m_kk, and MolalityVPSSTP::m_molalities.
Referenced by MolalityVPSSTP::getCsvReportData(), MolalityVPSSTP::report(), and vcs_MultiPhaseEquil::reportCSV().
setMolalities()
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
Note, the entry for the solvent is not used. We are supplied with the molalities of all of the solute species. We then calculate the mole fractions of all species and update the ThermoPhase object.
\[ m_i = \frac{X_i}{M_o/1000 * X_{o,p}} \]
where
\(M_o\) is the molecular weight of the solvent
\(X_o\) is the mole fraction of the solvent
\(X_i\) is the mole fraction of the solute.
\(X_{o,p} = \max(X_o^{min}, X_o)\)
\(X_o^{min}\) = minimum mole fraction of solvent allowed in the denominator.
The formulas for calculating mole fractions are
\[ L^{sum} = \frac{1}{\tilde{M}_o X_o} = \frac{1}{\tilde{M}_o} + \sum_{i\ne o} m_i \]
Then,
\[ X_o = \frac{1}{\tilde{M}_o L^{sum}} \]
\[ X_i = \frac{m_i}{L^{sum}} \]
It is currently an error if the solvent mole fraction is attempted to be set to a value lower than \(X_o^{min} \).
Parameters
molal Input vector of molalities. Length: m_kk.
Definition at line 78 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and Phase::setMoleFractions().
Referenced by MolalityVPSSTP::setState_TPM().
setMolalitiesByName() [1/2]
void setMolalitiesByName (const compositionMap & xMap)
Set the molalities of a phase.
Set the molalities of the solutes in a phase. Note, the entry for the solvent is not used.
Parameters
xMap Composition Map containing the molalities.
Definition at line 105 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::charge(), Phase::getMoleFractions(), Cantera::getValue(), Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_xmolSolventMIN, Cantera::npos, Phase::setMoleFractions(), and Phase::speciesName().
Referenced by MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setState(), and MolalityVPSSTP::setState_TPM().
setMolalitiesByName() [2/2]
void setMolalitiesByName (const std::string & name)
Set the molalities of a phase.
Set the molalities of the solutes in a phase. Note, the entry for the solvent is not used.
Parameters
name String containing the information for a composition map.
Definition at line 173 of file MolalityVPSSTP.cpp.
References Cantera::parseCompString(), MolalityVPSSTP::setMolalitiesByName(), and Phase::speciesNames().
activityConvention()
int activityConvention () const virtual
We set the convention to molality here.
Reimplemented from ThermoPhase.
Definition at line 181 of file MolalityVPSSTP.cpp.
References Cantera::cAC_CONVENTION_MOLALITY.
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Reimplemented in DebyeHuckel, HMWSoln, and IdealMolalSoln.
Definition at line 186 of file MolalityVPSSTP.cpp.
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (that is, generalized) concentration. In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (such as surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard concentration. The units are by definition dependent on the ThermoPhase and kinetics manager representation.
Reimplemented from ThermoPhase.
Reimplemented in DebyeHuckel, HMWSoln, and IdealMolalSoln.
Definition at line 191 of file MolalityVPSSTP.cpp.
getActivities()
void getActivities (doublereal * ac) const virtual
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
All standard state properties for molality-based phases are evaluated consistent with the molality scale. Therefore, this function must return molality-based activities.
\[ a_i^\triangle = \gamma_k^{\triangle} \frac{m_k}{m^\triangle} \]
This function must be implemented in derived classes.
Parameters
ac Output vector of molality-based activities. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in DebyeHuckel, HMWSoln, and IdealMolalSoln.
Definition at line 196 of file MolalityVPSSTP.cpp.
Referenced by MolalityVPSSTP::getCsvReportData(), MolalityVPSSTP::osmoticCoefficient(), and MolalityVPSSTP::report().
getActivityCoefficients()
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
These are mole-fraction based activity coefficients. In this object, their calculation is based on translating the values of the molality-based activity coefficients. See Denbigh p. 278 for a thorough discussion.
The molar-based activity coefficients \(\gamma_k \) may be calculated from the molality-based activity coefficients, \(\gamma_k^\triangle \) by the following formula.
\[ \gamma_k = \frac{\gamma_k^\triangle}{X_o} \]
For purposes of establishing a convention, the molar activity coefficient of the solvent is set equal to the molality-based activity coefficient of the solvent:
\[ \gamma_o = \gamma_o^\triangle \]
Derived classes don't need to overload this function. This function is handled at this level.
Parameters
ac Output vector containing the mole-fraction based activity coefficients. length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 201 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::m_kk, MolalityVPSSTP::m_xmolSolventMIN, and Phase::moleFraction().
getMolalityActivityCoefficients()
void getMolalityActivityCoefficients (doublereal * acMolality) const virtual
Get the array of non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
See Denbigh p. 278 for a thorough discussion. This class must be overridden in classes which derive from MolalityVPSSTP. This function takes over from the molar-based activity coefficient calculation, getActivityCoefficients(), in derived classes.
These molality based activity coefficients are scaled according to the current pH scale. See the Eq3/6 manual for details.
Activity coefficients for species k may be altered between scales s1 to s2 using the following formula
\[ ln(\gamma_k^{s2}) = ln(\gamma_k^{s1}) + \frac{z_k}{z_j} \left(ln(\gamma_j^{s2}) - ln(\gamma_j^{s1}) \right) \]
where j is any one species. For the NBS scale, j is equal to the Cl- species and
\[ ln(\gamma_{Cl-}^{s2}) = \frac{-A_{\phi} \sqrt{I}}{1.0 + 1.5 \sqrt{I}} \]
Parameters
acMolality Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in DebyeHuckel, and IdealMolalSoln.
Definition at line 210 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::applyphScale(), and MolalityVPSSTP::getUnscaledMolalityActivityCoefficients().
Referenced by MolalityVPSSTP::getActivityCoefficients(), MolalityVPSSTP::getCsvReportData(), and MolalityVPSSTP::report().
osmoticCoefficient()
doublereal osmoticCoefficient () const virtual
Calculate the osmotic coefficient.
\[ \phi = \frac{- ln(a_o)}{\tilde{M}_o \sum_{i \ne o} m_i} \]
Note there are a few of definitions of the osmotic coefficient floating around. We use the one defined in (Activity Coefficients in Electrolyte Solutions, K. S. Pitzer CRC Press, Boca Raton, 1991, p. 85, Eqn. 28). This definition is most clearly related to theoretical calculation.
units = dimensionless
Definition at line 216 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::getActivities(), Phase::m_kk, MolalityVPSSTP::m_Mnaught, and MolalityVPSSTP::m_molalities.
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Reimplemented from VPStandardStateTP.
Reimplemented in DebyeHuckel, and IdealMolalSoln.
Definition at line 344 of file MolalityVPSSTP.cpp.
References VPStandardStateTP::addSpecies(), Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, MolalityVPSSTP::m_weightSolvent, and Phase::molecularWeight().
Referenced by DebyeHuckel::addSpecies(), and IdealMolalSoln::addSpecies().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from VPStandardStateTP.
Reimplemented in DebyeHuckel, HMWSoln, and IdealMolalSoln.
Definition at line 270 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::findCLMIndex(), VPStandardStateTP::initThermo(), and MolalityVPSSTP::m_indexCLM.
Referenced by DebyeHuckel::initThermo(), HMWSoln::initThermo(), and IdealMolalSoln::initThermo().
setState_TPM() [1/3]
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
Parameters
t Temperature (K)
p Pressure (Pa)
molalities Input vector of molalities of the solutes. Length: m_kk.
Definition at line 234 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalities(), and VPStandardStateTP::setState_TP().
setState_TPM() [2/3]
void setState_TPM (doublereal t, doublereal p, const compositionMap & m)
Set the temperature (K), pressure (Pa), and molalities.
Parameters
t Temperature (K)
p Pressure (Pa)
m compositionMap containing the molalities
Definition at line 241 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalitiesByName(), and VPStandardStateTP::setState_TP().
setState_TPM() [3/3]
void setState_TPM (doublereal t, doublereal p, const std::string & m)
Set the temperature (K), pressure (Pa), and molalities.
Parameters
t Temperature (K)
p Pressure (Pa)
m String which gets translated into a composition map for the molalities of the solutes.
Definition at line 247 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalitiesByName(), and VPStandardStateTP::setState_TP().
setState()
void setState (const AnyMap & state) virtual
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
Accepted keys are:
X (mole fractions)
Y (mass fractions)
T or temperature
P or pressure [Pa]
H or enthalpy [J/kg]
U or internal-energy [J/kg]
S or entropy [J/kg/K]
V or specific-volume [m^3/kg]
D or density [kg/m^3]
Composition can be specified as either an AnyMap of species names to values or as a composition string. All other values can be given as floating point values in Cantera's default units, or as strings with the units specified, which will be converted using the Units class.
If no thermodynamic property pair is given, or only one of temperature or pressure is given, then 298.15 K and 101325 Pa will be used as necessary to fully set the state.
Additionally uses the keys molalities or M to set the molalities.
Reimplemented from ThermoPhase.
Definition at line 253 of file MolalityVPSSTP.cpp.
References AnyValue::asMap(), AnyValue::asString(), AnyMap::hasKey(), AnyValue::is(), MolalityVPSSTP::setMolalitiesByName(), and ThermoPhase::setState().
getdlnActCoeffdlnN()
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) inline virtual
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a species log mole number (with all other species mole numbers held constant). The default treatment in the ThermoPhase object is to set this vector to zero.
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the m-th species with respect to the number of moles of the k-th species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
When implemented, this method is used within the VCS equilibrium solver to calculate the Jacobian elements, which accelerates convergence of the algorithm.
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented from ThermoPhase.
Definition at line 536 of file MolalityVPSSTP.h.
report()
std::string report (bool show_thermo = true, doublereal threshold = 1e-14) const virtual
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
threshold Show information about species with mole fractions greater than threshold.
Reimplemented from ThermoPhase.
Definition at line 358 of file MolalityVPSSTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), MolalityVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), MolalityVPSSTP::getMolalities(), MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::getMoleFractions(), VPStandardStateTP::getStandardChemPotentials(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::m_kk, Phase::meanMolecularWeight(), Phase::name(), Cantera::npos, VPStandardStateTP::pressure(), Cantera::SmallNumber, Phase::speciesIndex(), Phase::speciesName(), Phase::temperature(), and CanteraError::what().
getCsvReportData()
void getCsvReportData (std::vector< std::string > & names, std::vector< vector_fp > & data) const protected virtual
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Deprecated:
To be removed after Cantera 3.0.
Reimplemented from ThermoPhase.
Definition at line 466 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), MolalityVPSSTP::getMolalities(), MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), VPStandardStateTP::getStandardChemPotentials(), and Phase::nSpecies().
getUnscaledMolalityActivityCoefficients()
void getUnscaledMolalityActivityCoefficients (doublereal * acMolality) const protected virtual
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
See Denbigh p. 278 for a thorough discussion. This class must be overridden in classes which derive from MolalityVPSSTP. This function takes over from the molar-based activity coefficient calculation, getActivityCoefficients(), in derived classes.
Parameters
acMolality Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in HMWSoln.
Definition at line 278 of file MolalityVPSSTP.cpp.
Referenced by MolalityVPSSTP::getMolalityActivityCoefficients().
applyphScale()
void applyphScale (doublereal * acMolality) const protected virtual
Apply the current phScale to a set of activity Coefficients or activities.
See the Eq3/6 Manual for a thorough discussion.
Parameters
acMolality input/Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in HMWSoln.
Definition at line 283 of file MolalityVPSSTP.cpp.
Referenced by MolalityVPSSTP::getMolalityActivityCoefficients().
findCLMIndex()
size_t findCLMIndex () const private virtual
Returns the index of the Cl- species.
The Cl- species is special in the sense that its single ion molality- based activity coefficient is used in the specification of the pH scale for single ions. Therefore, we need to know what species index is Cl-. If the species isn't in the species list then this routine returns -1, and we can't use the NBS pH scale.
Right now we use a restrictive interpretation. The species must be named "Cl-". It must consist of exactly one Cl and one E atom.
Definition at line 288 of file MolalityVPSSTP.cpp.
References Phase::elementName(), Phase::m_kk, Phase::nAtoms(), Phase::nElements(), Cantera::npos, and Phase::speciesName().
Referenced by MolalityVPSSTP::initThermo().
Member Data Documentation
m_pHScalingType
int m_pHScalingType = PHSCALE_PITZER protected
Scaling to be used for output of single-ion species activity coefficients.
Index of the species to be used in the single-ion scaling law. This is the identity of the Cl- species for the PHSCALE_NBS scaling. Either PHSCALE_PITZER or PHSCALE_NBS
Definition at line 593 of file MolalityVPSSTP.h.
Referenced by HMWSoln::applyphScale(), MolalityVPSSTP::pHScale(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), and MolalityVPSSTP::setpHScale().
m_indexCLM
size_t m_indexCLM = npos protected
Index of the phScale species.
Index of the species to be used in the single-ion scaling law. This is the identity of the Cl- species for the PHSCALE_NBS scaling
Definition at line 600 of file MolalityVPSSTP.h.
Referenced by HMWSoln::applyphScale(), MolalityVPSSTP::initThermo(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
m_weightSolvent
double m_weightSolvent = 18.01528 protected
Molecular weight of the Solvent.
Definition at line 603 of file MolalityVPSSTP.h.
Referenced by MolalityVPSSTP::addSpecies(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
m_xmolSolventMIN
double m_xmolSolventMIN = 0.01 protected
In any molality implementation, it makes sense to have a minimum solvent mole fraction requirement, since the implementation becomes singular in the xmolSolvent=0 limit. The default is to set it to 0.01. We then modify the molality definition to ensure that molal_solvent = 0 when xmol_solvent = 0.
Definition at line 612 of file MolalityVPSSTP.h.
Referenced by MolalityVPSSTP::calcMolalities(), IdealMolalSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealMolalSoln::getMolalityActivityCoefficients(), MolalityVPSSTP::moleFSolventMin(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), and MolalityVPSSTP::setMoleFSolventMin().
m_Mnaught
double m_Mnaught = 18.01528E-3 protected
This is the multiplication factor that goes inside log expressions involving the molalities of species.
It's equal to Wt_0 / 1000, where Wt_0 = weight of solvent (kg/kmol)
Definition at line 617 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::addSpecies(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), and HMWSoln::standardConcentration().
m_molalities
vector_fp m_molalities mutable protected
Current value of the molalities of the species in the phase.
Note this vector is a mutable quantity. units are (kg/kmol)
Definition at line 621 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::addSpecies(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), IdealMolalSoln::getActivities(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealMolalSoln::getChemPotentials(), MolalityVPSSTP::getMolalities(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and MolalityVPSSTP::setMolalities().
The documentation for this class was generated from the following files:
MolalityVPSSTP.h
MolalityVPSSTP.cpp