Cantera: MoleReactor Class Reference
MoleReactor Class Reference
#include <MoleReactor.h>
Public Member Functions
virtual std::string type () const
String indicating the reactor model implemented.
virtual void initialize (double t0=0.0)
Initialize the reactor.
virtual void getState (double *y)
Get the the current state of the reactor.
virtual void updateState (double *y)
Set the state of the reactor to correspond to the state vector y.
virtual void eval (double t, double *LHS, double *RHS)
Evaluate the reactor governing equations.
size_t componentIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the component named nm.
std::string componentName (size_t k)
Return the name of the solution component with index i.
Public Member Functions inherited from Reactor
virtual std::string type () const
String indicating the reactor model implemented.
virtual bool isOde () const
Indicate whether the governing equations for this reactor type are a system of ODEs or DAEs.
virtual bool timeIsIndependent () const
Indicates whether the governing equations for this reactor are functions of time or a spatial variable.
template<class G >
void insert (G &contents)
Insert something into the reactor.
void insert (shared_ptr< Solution > sol)
virtual void setKineticsMgr (Kinetics &kin)
Specify chemical kinetics governing the reactor.
void setChemistry (bool cflag=true)
Enable or disable changes in reactor composition due to chemical reactions.
bool chemistryEnabled () const
Returns true if changes in the reactor composition due to chemical reactions are enabled.
void setEnergy (int eflag=1)
Set the energy equation on or off.
bool energyEnabled () const
Returns true if solution of the energy equation is enabled.
size_t neq ()
Number of equations (state variables) for this reactor.
virtual void getState (double *y)
Get the the current state of the reactor.
virtual void getStateDae (double *y, double *ydot)
Get the current state and derivative vector of the reactor for a DAE solver.
virtual void initialize (double t0=0.0)
Initialize the reactor.
virtual void eval (double t, double *LHS, double *RHS)
Evaluate the reactor governing equations.
virtual void evalDae (double t, double *y, double *ydot, double *residual)
virtual void getConstraints (double *constraints)
Given a vector of length neq(), mark which variables should be considered algebraic constraints.
virtual void syncState ()
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
virtual void updateState (double *y)
Set the state of the reactor to correspond to the state vector y.
virtual size_t nSensParams ()
Number of sensitivity parameters associated with this reactor (including walls)
virtual void addSensitivityReaction (size_t rxn)
Add a sensitivity parameter associated with the reaction number rxn (in the homogeneous phase).
virtual void addSensitivitySpeciesEnthalpy (size_t k)
Add a sensitivity parameter associated with the enthalpy formation of species k (in the homogeneous phase)
virtual size_t componentIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the component named nm.
virtual std::string componentName (size_t k)
Return the name of the solution component with index i.
void setAdvanceLimits (const double *limits)
Set absolute step size limits during advance.
bool hasAdvanceLimits ()
Check whether Reactor object uses advance limits.
bool getAdvanceLimits (double *limits)
Retrieve absolute step size limits during advance.
void setAdvanceLimit (const std::string &nm, const double limit)
Set individual step size limit for component name nm
virtual Eigen::SparseMatrix< double > jacobian ()
Method to calculate the reactor specific jacobian.
Eigen::SparseMatrix< double > finiteDifferenceJacobian ()
Calculate the reactor-specific Jacobian using a finite difference method.
virtual void setDerivativeSettings (AnyMap &settings)
Use this to set the kinetics objects derivative settings.
virtual void applySensitivity (double *params)
Set reaction rate multipliers based on the sensitivity variables in params.
virtual void resetSensitivity (double *params)
Reset the reaction rate multipliers.
virtual bool preconditionerSupported () const
Return a false if preconditioning is not supported or true otherwise.
Public Member Functions inherited from ReactorBase
ReactorBase (const std::string &name="(none)")
ReactorBase (const ReactorBase &)=delete
ReactorBase & operator= (const ReactorBase &)=delete
virtual std::string type () const
String indicating the reactor model implemented.
std::string name () const
Return the name of this reactor.
void setName (const std::string &name)
Set the name of this reactor.
void restoreState ()
Set the state of the Phase object associated with this reactor to the reactor's current state.
virtual void syncState ()
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
ThermoPhase & contents ()
return a reference to the contents.
const ThermoPhase & contents () const
doublereal residenceTime ()
Return the residence time (s) of the contents of this reactor, based on the outlet mass flow rates and the mass of the reactor contents.
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
void setNetwork (ReactorNet *net)
Set the ReactorNet that this reactor belongs to.
void setInitialVolume (doublereal vol)
Set the initial reactor volume. By default, the volume is 1.0 m^3.
virtual void setThermoMgr (ThermoPhase &thermo)
Specify the mixture contained in the reactor.
void addInlet (FlowDevice &inlet)
Connect an inlet FlowDevice to this reactor.
void addOutlet (FlowDevice &outlet)
Connect an outlet FlowDevice to this reactor.
FlowDevice & inlet (size_t n=0)
Return a reference to the n-th inlet FlowDevice connected to this reactor.
FlowDevice & outlet (size_t n=0)
Return a reference to the n-th outlet FlowDevice connected to this reactor.
size_t nInlets ()
Return the number of inlet FlowDevice objects connected to this reactor.
size_t nOutlets ()
Return the number of outlet FlowDevice objects connected to this reactor.
size_t nWalls ()
Return the number of Wall objects connected to this reactor.
void addWall (WallBase &w, int lr)
Insert a Wall between this reactor and another reactor.
WallBase & wall (size_t n)
Return a reference to the n-th Wall connected to this reactor.
virtual void addSurface (ReactorSurface *surf)
ReactorSurface * surface (size_t n)
Return a reference to the n-th ReactorSurface connected to this reactor.
virtual size_t nSurfs ()
Return the number of surfaces in a reactor.
doublereal volume () const
Returns the current volume (m^3) of the reactor.
doublereal density () const
Returns the current density (kg/m^3) of the reactor's contents.
doublereal temperature () const
Returns the current temperature (K) of the reactor's contents.
doublereal enthalpy_mass () const
Returns the current enthalpy (J/kg) of the reactor's contents.
doublereal intEnergy_mass () const
Returns the current internal energy (J/kg) of the reactor's contents.
doublereal pressure () const
Returns the current pressure (Pa) of the reactor.
doublereal mass () const
Returns the mass (kg) of the reactor's contents.
const doublereal * massFractions () const
Return the vector of species mass fractions.
doublereal massFraction (size_t k) const
Return the mass fraction of the k-th species.
Protected Member Functions
virtual void addSurfaceJacobian (vector< Eigen::Triplet< double > > &triplets)
For each surface in the reactor, update vector of triplets with all relevant surface jacobian derivatives of species with respect to species which are appropriately offset to align with the reactor's state vector.
virtual void getMoles (double *y)
Get moles of the system from mass fractions stored by thermo object.
virtual void setMassFromMoles (double *y)
Set internal mass variable based on moles given.
virtual void evalSurfaces (double *LHS, double *RHS, double *sdot)
Evaluate terms related to surface reactions.
virtual void updateSurfaceState (double *y)
Update the state of SurfPhase objects attached to this reactor.
virtual void getSurfaceInitialConditions (double *y)
Get initial conditions for SurfPhase objects attached to this reactor.
Protected Member Functions inherited from Reactor
virtual size_t speciesIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the species named nm, in either the homogeneous phase or a surface phase, relative to the start of the species terms.
virtual void evalWalls (double t)
Evaluate terms related to Walls.
virtual void evalSurfaces (double *LHS, double *RHS, double *sdot)
Evaluate terms related to surface reactions.
virtual void evalSurfaces (double *RHS, double *sdot)
virtual void updateSurfaceState (double *y)
Update the state of SurfPhase objects attached to this reactor.
virtual void updateConnected (bool updatePressure)
Update the state information needed by connected reactors, flow devices, and reactor walls.
virtual void getSurfaceInitialConditions (double *y)
Get initial conditions for SurfPhase objects attached to this reactor.
Protected Attributes
const size_t m_sidx = 2
const value for the species start index
Protected Attributes inherited from Reactor
Kinetics * m_kin = nullptr
Pointer to the homogeneous Kinetics object that handles the reactions.
double m_vdot = 0.0
net rate of volume change from moving walls [m^3/s]
double m_Qdot = 0.0
net heat transfer into the reactor, through walls [W]
double m_mass = 0.0
total mass
vector_fp m_work
vector_fp m_sdot
Production rates of gas phase species on surfaces [kmol/s].
vector_fp m_wdot
Species net molar production rates.
vector_fp m_uk
Species molar internal energies.
bool m_chem = false
bool m_energy = true
size_t m_nv = 0
size_t m_nv_surf
vector_fp m_advancelimits
!< Number of variables associated with reactor surfaces
std::vector< SensitivityParameter > m_sensParams
std::vector< Eigen::Triplet< double > > m_jac_trips
Vector of triplets representing the jacobian.
Protected Attributes inherited from ReactorBase
size_t m_nsp = 0
Number of homogeneous species in the mixture.
ThermoPhase * m_thermo = nullptr
double m_vol = 1.0
Current volume of the reactor [m^3].
double m_enthalpy = 0.0
Current specific enthalpy of the reactor [J/kg].
double m_intEnergy = 0.0
Current internal energy of the reactor [J/kg].
double m_pressure = 0.0
Current pressure in the reactor [Pa].
vector_fp m_state
std::vector< FlowDevice * > m_inlet
std::vector< FlowDevice * > m_outlet
std::vector< WallBase * > m_wall
std::vector< ReactorSurface * > m_surfaces
vector_int m_lr
Vector of length nWalls(), indicating whether this reactor is on the left (0) or right (1) of each wall.
std::string m_name
ReactorNet * m_net = nullptr
The ReactorNet that this reactor is part of.
Detailed Description
MoleReactor is meant to serve the same purpose as the reactor class but with a state vector composed of moles. It also serves as the base class for other mole reactors.
Definition at line 18 of file MoleReactor.h.
Constructor & Destructor Documentation
MoleReactor()
MoleReactor () inline
Definition at line 21 of file MoleReactor.h.
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the reactor model implemented.
Usually corresponds to the name of the derived class.
Reimplemented from Reactor.
Reimplemented in ConstPressureMoleReactor, IdealGasConstPressureMoleReactor, and IdealGasMoleReactor.
Definition at line 23 of file MoleReactor.h.
initialize()
void initialize (double t0 = 0.0) virtual
Initialize the reactor.
Called automatically by ReactorNet::initialize.
Reimplemented from Reactor.
Reimplemented in ConstPressureMoleReactor, IdealGasConstPressureMoleReactor, and IdealGasMoleReactor.
Definition at line 38 of file MoleReactor.cpp.
References Reactor::initialize().
Referenced by ConstPressureMoleReactor::initialize(), and IdealGasMoleReactor::initialize().
getState()
void getState (double * y) virtual
Get the the current state of the reactor.
Parameters
[out] y state vector representing the initial state of the reactor
Reimplemented from Reactor.
Reimplemented in ConstPressureMoleReactor, IdealGasConstPressureMoleReactor, and IdealGasMoleReactor.
Definition at line 163 of file MoleReactor.cpp.
References Phase::density(), MoleReactor::getMoles(), MoleReactor::getSurfaceInitialConditions(), ThermoPhase::intEnergy_mass(), Reactor::m_mass, ReactorBase::m_nsp, MoleReactor::m_sidx, ReactorBase::m_vol, and Phase::restoreState().
updateState()
void updateState (double * y) virtual
Set the state of the reactor to correspond to the state vector y.
Reimplemented from Reactor.
Reimplemented in ConstPressureMoleReactor, IdealGasConstPressureMoleReactor, and IdealGasMoleReactor.
Definition at line 182 of file MoleReactor.cpp.
References ThermoPhase::intEnergy_mass(), Reactor::m_mass, ReactorBase::m_nsp, MoleReactor::m_sidx, ReactorBase::m_vol, ThermoPhase::maxTemp(), ThermoPhase::minTemp(), Phase::setDensity(), MoleReactor::setMassFromMoles(), Phase::setMolesNoTruncate(), Phase::setState_TD(), Phase::temperature(), Reactor::updateConnected(), and MoleReactor::updateSurfaceState().
eval()
void eval (double t, double * LHS, double * RHS) virtual
Evaluate the reactor governing equations.
Called by ReactorNet::eval.
Parameters
[in] t time.
[out] LHS pointer to start of vector of left-hand side coefficients for governing equations, length m_nv, default values 1
[out] RHS pointer to start of vector of right-hand side coefficients for governing equations, length m_nv, default values 0
Reimplemented from Reactor.
Reimplemented in ConstPressureMoleReactor, IdealGasConstPressureMoleReactor, and IdealGasMoleReactor.
Definition at line 227 of file MoleReactor.cpp.
References FlowDevice::enthalpy_mass(), MoleReactor::evalSurfaces(), Reactor::evalWalls(), Kinetics::getNetProductionRates(), ReactorBase::inlet(), Phase::inverseMolecularWeights(), ReactorBase::m_enthalpy, Reactor::m_kin, ReactorBase::m_nsp, Reactor::m_Qdot, Reactor::m_sdot, MoleReactor::m_sidx, Reactor::m_vdot, ReactorBase::m_vol, Reactor::m_wdot, FlowDevice::massFlowRate(), ReactorBase::outlet(), FlowDevice::outletSpeciesMassFlowRate(), Phase::pressure(), and Phase::restoreState().
componentIndex()
size_t componentIndex (const std::string & nm) const virtual
Return the index in the solution vector for this reactor of the component named nm.
Possible values for nm are "mass", "volume", "int_energy", the name of a homogeneous phase species, or the name of a surface species.
Reimplemented from Reactor.
Definition at line 286 of file MoleReactor.cpp.
References MoleReactor::m_sidx, Cantera::npos, and Reactor::speciesIndex().
componentName()
std::string componentName (size_t k) virtual
Return the name of the solution component with index i.
See also
componentIndex()
Reimplemented from Reactor.
Definition at line 300 of file MoleReactor.cpp.
References MoleReactor::m_sidx, Reactor::neq(), Phase::nSpecies(), and Phase::speciesName().
Referenced by IdealGasMoleReactor::componentName().
addSurfaceJacobian()
void addSurfaceJacobian (vector< Eigen::Triplet< double > > & triplets) protected virtual
For each surface in the reactor, update vector of triplets with all relevant surface jacobian derivatives of species with respect to species which are appropriately offset to align with the reactor's state vector.
Definition at line 87 of file MoleReactor.cpp.
References ReactorBase::m_nsp, ReactorBase::m_vol, and Phase::speciesName().
Referenced by IdealGasConstPressureMoleReactor::jacobian(), and IdealGasMoleReactor::jacobian().
getMoles()
void getMoles (double * y) protected virtual
Get moles of the system from mass fractions stored by thermo object.
Parameters
y vector for moles to be put into
Definition at line 143 of file MoleReactor.cpp.
References Phase::inverseMolecularWeights(), Reactor::m_mass, ReactorBase::m_nsp, and Phase::massFractions().
Referenced by ConstPressureMoleReactor::getState(), IdealGasConstPressureMoleReactor::getState(), IdealGasMoleReactor::getState(), and MoleReactor::getState().
setMassFromMoles()
void setMassFromMoles (double * y) protected virtual
Set internal mass variable based on moles given.
Parameters
y vector of moles of the system
Definition at line 153 of file MoleReactor.cpp.
References Reactor::m_mass, ReactorBase::m_nsp, and Phase::molecularWeights().
Referenced by ConstPressureMoleReactor::updateState(), IdealGasConstPressureMoleReactor::updateState(), IdealGasMoleReactor::updateState(), and MoleReactor::updateState().
evalSurfaces()
void evalSurfaces (double * LHS, double * RHS, double * sdot) protected virtual
Evaluate terms related to surface reactions.
Parameters
[out] LHS Multiplicative factor on the left hand side of ODE for surface species coverages
[out] RHS Right hand side of ODE for surface species coverages
[out] sdot array of production rates of bulk phase species on surfaces [kmol/s]
Reimplemented from Reactor.
Definition at line 61 of file MoleReactor.cpp.
References Kinetics::getNetProductionRates(), Kinetics::kineticsSpeciesIndex(), ReactorBase::m_nsp, Phase::nSpecies(), Kinetics::reactionPhaseIndex(), SurfPhase::size(), and Phase::speciesName().
Referenced by ConstPressureMoleReactor::eval(), IdealGasConstPressureMoleReactor::eval(), IdealGasMoleReactor::eval(), and MoleReactor::eval().
updateSurfaceState()
void updateSurfaceState (double * y) protected virtual
Update the state of SurfPhase objects attached to this reactor.
Reimplemented from Reactor.
Definition at line 44 of file MoleReactor.cpp.
Referenced by ConstPressureMoleReactor::updateState(), IdealGasConstPressureMoleReactor::updateState(), IdealGasMoleReactor::updateState(), and MoleReactor::updateState().
getSurfaceInitialConditions()
void getSurfaceInitialConditions (double * y) protected virtual
Get initial conditions for SurfPhase objects attached to this reactor.
Reimplemented from Reactor.
Definition at line 21 of file MoleReactor.cpp.
Referenced by ConstPressureMoleReactor::getState(), IdealGasConstPressureMoleReactor::getState(), IdealGasMoleReactor::getState(), and MoleReactor::getState().
Member Data Documentation
m_sidx
const size_t m_sidx = 2 protected
const value for the species start index
Definition at line 60 of file MoleReactor.h.
Referenced by IdealGasMoleReactor::componentIndex(), MoleReactor::componentIndex(), MoleReactor::componentName(), IdealGasMoleReactor::eval(), MoleReactor::eval(), IdealGasMoleReactor::getState(), MoleReactor::getState(), IdealGasMoleReactor::jacobian(), IdealGasMoleReactor::updateState(), and MoleReactor::updateState().
The documentation for this class was generated from the following files:
MoleReactor.h
MoleReactor.cpp