Cantera: NasaPoly2 Class Reference
NasaPoly2 Class Reference
Models of Phases of Matter » Thermodynamic Properties » Species Reference-State Thermodynamic Properties
The NASA polynomial parameterization for two temperature ranges.
#include <NasaPoly2.h>
Public Member Functions
NasaPoly2 (doublereal tlow, doublereal thigh, doublereal pref, const doublereal *coeffs)
Constructor with all input data.
virtual void setMinTemp (double Tmin)
Set the minimum temperature at which the thermo parameterization is valid.
virtual void setMaxTemp (double Tmax)
Set the maximum temperature at which the thermo parameterization is valid.
virtual void setRefPressure (double Pref)
Set the reference pressure [Pa].
void setParameters (double Tmid, const vector_fp &low, const vector_fp &high)
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
size_t nCoeffs () const
This utility function returns the number of coefficients for a given type of species parameterization.
void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
This utility function returns the type of parameterization and all of the parameters for the species.
virtual void getParameters (AnyMap &thermo) const
Store the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
void resetHf298 ()
Restore the original heat of formation for this species.
void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)=delete
SpeciesThermoInterpType & operator= (const SpeciesThermoInterpType &b)=delete
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual void setMinTemp (double Tmin)
Set the minimum temperature at which the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual void setMaxTemp (double Tmax)
Set the maximum temperature at which the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void setRefPressure (double Pref)
Set the reference pressure [Pa].
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual size_t nCoeffs () const
This utility function returns the number of coefficients for a given type of species parameterization.
virtual void reportParameters (size_t &index, int &type, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure, doublereal *const coeffs) const
This utility function returns the type of parameterization and all of the parameters for the species.
AnyMap parameters (bool withInput=true) const
Return the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 ()
Restore the original heat of formation for this species.
const AnyMap & input () const
Access input data associated with the species thermo definition.
AnyMap & input ()
Protected Attributes
double m_midT = 0.0
Midrange temperature.
NasaPoly1 mnp_low
NasaPoly1 object for the low temperature region.
NasaPoly1 mnp_high
NasaPoly1 object for the high temperature region.
Protected Attributes inherited from SpeciesThermoInterpType
double m_lowT = 0.0
lowest valid temperature
double m_highT = 0.0
Highest valid temperature.
double m_Pref = 0.0
Reference state pressure.
AnyMap m_input
Additional Inherited Members
virtual void getParameters (AnyMap &thermo) const
Store the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
Detailed Description
The NASA polynomial parameterization for two temperature ranges.
This parameterization expresses the heat capacity as a fourth-order polynomial. Note that this is the form used in the 1971 NASA equilibrium program and by the Chemkin software package, but differs from the form used in the more recent NASA equilibrium program.
Seven coefficients \((a_0,\dots,a_6)\) are used to represent \(c_p^0(T)\), \(h^0(T)\), and \(s^0(T) \) as polynomials in \(T \) :
\[ \frac{c_p(T)}{R} = a_0 + a_1 T + a_2 T^2 + a_3 T^3 + a_4 T^4 \]
\[ \frac{h^0(T)}{RT} = a_0 + \frac{a_1}{2} T + \frac{a_2}{3} T^2 + \frac{a_3}{4} T^3 + \frac{a_4}{5} T^4 + \frac{a_5}{T}. \]
\[ \frac{s^0(T)}{R} = a_0\ln T + a_1 T + \frac{a_2}{2} T^2 + \frac{a_3}{3} T^3 + \frac{a_4}{4} T^4 + a_6. \]
This class is designed specifically for use by the class MultiSpeciesThermo.
Definition at line 48 of file NasaPoly2.h.
Constructor & Destructor Documentation
NasaPoly2()
NasaPoly2 (doublereal tlow, doublereal thigh, doublereal pref, const doublereal * coeffs) inline
Constructor with all input data.
Parameters
tlow output - Minimum temperature
thigh output - Maximum temperature
pref output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state [Tmid, 7 high-T coeffs, 7 low-T coeffs]. This is the coefficient order used in the standard NASA format.
Definition at line 63 of file NasaPoly2.h.
Member Function Documentation
setMinTemp()
virtual void setMinTemp (double Tmin) inline virtual
Set the minimum temperature at which the thermo parameterization is valid.
Reimplemented from SpeciesThermoInterpType.
Definition at line 71 of file NasaPoly2.h.
References NasaPoly2::mnp_low, and SpeciesThermoInterpType::setMinTemp().
setMaxTemp()
virtual void setMaxTemp (double Tmax) inline virtual
Set the maximum temperature at which the thermo parameterization is valid.
Reimplemented from SpeciesThermoInterpType.
Definition at line 76 of file NasaPoly2.h.
References NasaPoly2::mnp_high, and SpeciesThermoInterpType::setMaxTemp().
setRefPressure()
virtual void setRefPressure (double Pref) inline virtual
Set the reference pressure [Pa].
Reimplemented from SpeciesThermoInterpType.
Definition at line 81 of file NasaPoly2.h.
References NasaPoly2::mnp_high, NasaPoly2::mnp_low, and SpeciesThermoInterpType::setRefPressure().
setParameters()
void setParameters (double Tmid, const vector_fp & low, const vector_fp & high)
Parameters
Tmid Temperature [K] at the boundary between the low and high temperature polynomials
low Vector of 7 coefficients for the low temperature polynomial
high Vector of 7 coefficients for the high temperature polynomial
Definition at line 11 of file NasaPoly2.cpp.
References NasaPoly2::m_midT, NasaPoly2::mnp_high, NasaPoly2::mnp_low, SpeciesThermoInterpType::setMaxTemp(), SpeciesThermoInterpType::setMinTemp(), and NasaPoly1::setParameters().
reportType()
virtual int reportType () const inline virtual
Returns an integer representing the type of parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 95 of file NasaPoly2.h.
References NASA2.
temperaturePolySize()
virtual size_t temperaturePolySize () const inline virtual
Number of terms in the temperature polynomial for this parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 99 of file NasaPoly2.h.
updateTemperaturePoly()
virtual void updateTemperaturePoly (double T, double * T_poly) const inline virtual
Given the temperature T, compute the terms of the temperature polynomial T_poly.
Reimplemented from SpeciesThermoInterpType.
Definition at line 101 of file NasaPoly2.h.
References NasaPoly2::mnp_low, and NasaPoly1::updateTemperaturePoly().
updateProperties()
void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
The form and length of the Temperature Polynomial may vary depending on the parameterization.
Parameters
tt vector of evaluated temperature functions
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Temperature Polynomial: tt[0] = t; tt[1] = t*t; tt[2] = m_t[1]*t; tt[3] = m_t[2]*t; tt[4] = 1.0/t; tt[5] = std::log(t);
Reimplemented from SpeciesThermoInterpType.
Definition at line 106 of file NasaPoly2.h.
References NasaPoly2::m_midT, NasaPoly2::mnp_high, NasaPoly2::mnp_low, and NasaPoly1::updateProperties().
updatePropertiesTemp()
void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non- dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, of the species.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented from SpeciesThermoInterpType.
Definition at line 115 of file NasaPoly2.h.
References NasaPoly2::m_midT, NasaPoly2::mnp_high, NasaPoly2::mnp_low, and NasaPoly1::updatePropertiesTemp().
nCoeffs()
size_t nCoeffs () const inline virtual
This utility function returns the number of coefficients for a given type of species parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 126 of file NasaPoly2.h.
reportParameters()
void reportParameters (size_t & index, int & type, doublereal & minTemp, doublereal & maxTemp, doublereal & refPressure, doublereal *const coeffs) const inline virtual
This utility function returns the type of parameterization and all of the parameters for the species.
All parameters are output variables
Parameters
index Species index
type Integer type of the standard type
minTemp output - Minimum temperature
maxTemp output - Maximum temperature
refPressure output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Reimplemented from SpeciesThermoInterpType.
Definition at line 128 of file NasaPoly2.h.
References NasaPoly2::mnp_high, NasaPoly2::mnp_low, NASA2, and NasaPoly1::reportParameters().
getParameters()
void getParameters (AnyMap & thermo) const virtual
Store the parameters of the species thermo object such that an identical species thermo object could be reconstructed using the newSpeciesThermo() function.
Reimplemented from SpeciesThermoInterpType.
Definition at line 20 of file NasaPoly2.cpp.
References NasaPoly1::getParameters(), SpeciesThermoInterpType::getParameters(), SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_lowT, NasaPoly2::m_midT, NasaPoly2::mnp_high, and NasaPoly2::mnp_low.
reportHf298()
doublereal reportHf298 (doublereal *const h298 = 0) const inline virtual
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
h298 If this is nonnull, the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex is returned in h298[m_speciesIndex].
Returns
the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex.
Reimplemented from SpeciesThermoInterpType.
Definition at line 139 of file NasaPoly2.h.
References NasaPoly2::m_midT, NasaPoly2::mnp_high, NasaPoly2::mnp_low, and NasaPoly1::reportHf298().
Referenced by NasaPoly2::modifyOneHf298().
resetHf298()
void resetHf298 () inline virtual
Restore the original heat of formation for this species.
Resets changes made by modifyOneHf298().
Reimplemented from SpeciesThermoInterpType.
Definition at line 152 of file NasaPoly2.h.
References NasaPoly2::mnp_high, NasaPoly2::mnp_low, and NasaPoly1::resetHf298().
modifyOneHf298()
void modifyOneHf298 (const size_t k, const doublereal Hf298New) inline virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented from SpeciesThermoInterpType.
Definition at line 157 of file NasaPoly2.h.
References NasaPoly2::mnp_high, NasaPoly2::mnp_low, NasaPoly1::modifyOneHf298(), NasaPoly1::reportHf298(), and NasaPoly2::reportHf298().
validate()
void validate (const std::string & name) virtual
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
Reimplemented from SpeciesThermoInterpType.
Definition at line 31 of file NasaPoly2.cpp.
References NasaPoly2::m_midT, NasaPoly2::mnp_high, NasaPoly2::mnp_low, Cantera::thermo_warnings_suppressed(), NasaPoly1::updatePropertiesTemp(), and Cantera::warn_user().
Member Data Documentation
m_midT
double m_midT = 0.0 protected
Midrange temperature.
Definition at line 172 of file NasaPoly2.h.
Referenced by NasaPoly2::getParameters(), NasaPoly2::reportHf298(), NasaPoly2::setParameters(), NasaPoly2::updateProperties(), NasaPoly2::updatePropertiesTemp(), and NasaPoly2::validate().
mnp_low
NasaPoly1 mnp_low protected
NasaPoly1 object for the low temperature region.
Definition at line 174 of file NasaPoly2.h.
Referenced by NasaPoly2::getParameters(), NasaPoly2::modifyOneHf298(), NasaPoly2::reportHf298(), NasaPoly2::reportParameters(), NasaPoly2::resetHf298(), NasaPoly2::setMinTemp(), NasaPoly2::setParameters(), NasaPoly2::setRefPressure(), NasaPoly2::updateProperties(), NasaPoly2::updatePropertiesTemp(), NasaPoly2::updateTemperaturePoly(), and NasaPoly2::validate().
mnp_high
NasaPoly1 mnp_high protected
NasaPoly1 object for the high temperature region.
Definition at line 176 of file NasaPoly2.h.
Referenced by NasaPoly2::getParameters(), NasaPoly2::modifyOneHf298(), NasaPoly2::reportHf298(), NasaPoly2::reportParameters(), NasaPoly2::resetHf298(), NasaPoly2::setMaxTemp(), NasaPoly2::setParameters(), NasaPoly2::setRefPressure(), NasaPoly2::updateProperties(), NasaPoly2::updatePropertiesTemp(), and NasaPoly2::validate().
The documentation for this class was generated from the following files:
NasaPoly2.h
NasaPoly2.cpp