Cantera: Phase Class Reference
Phase Class Reference
Models of Phases of Matter
Class Phase is the base class for phases of matter, managing the species and elements in a phase, as well as the independent variables of temperature, mass density (compressible substances) or pressure (incompressible substances), species mass/mole fraction, and other generalized forces and intrinsic properties (such as electric potential) that define the thermodynamic state.
#include <Phase.h>
Public Member Functions
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
Name
Class Phase uses the string name to identify a phase. For phases instantiated from YAML input files, the name is the value of the corresponding key in the phase map.
However, the name field may be changed to another value during the course of a calculation. For example, if duplicates of a phase object are instantiated and used in multiple places (such as a ReactorNet), they will have the same constitutive input, that is, the names of the phases will be the same. Note that this is not a problem for Cantera internally; however, a user may want to rename phase objects in order to clarify.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
virtual std::string type () const
String indicating the thermodynamic model implemented.
Element and Species Information
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
Set Thermodynamic State
Set the internal thermodynamic state by setting the internally stored temperature, density and species composition.
Note that the composition is always set first.
Temperature and density are held constant if not explicitly set.
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
Composition
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
Thermodynamic Properties
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double pressure () const
Return the thermodynamic pressure (Pa).
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setPressure (double p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setTemperature (double temp)
Set the internally stored temperature of the phase (K).
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
Mean Properties
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
Adding Elements and Species
These methods are used to add new elements or species.
These are not usually called by user programs.
Since species are checked to insure that they are only composed of declared elements, it is necessary to first add all elements before adding any species.
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Private Member Functions
size_t findSpeciesLower (const std::string &nameStr) const
Find lowercase species name in m_speciesIndices when case sensitive species names are not enforced and a user specifies a non-canonical species name.
Private Attributes
std::string m_name
Name of the phase.
double m_temp = 0.001
Temperature (K). This is an independent variable.
double m_dens = 0.001
Density (kg m-3).
double m_mmw = 0.0
mean molecular weight of the mixture (kg kmol-1)
vector_fp m_ym
m_ym[k] = mole fraction of species k divided by the mean molecular weight of mixture.
vector_fp m_y
Mass fractions of the species.
vector_fp m_molwts
species molecular weights (kg kmol-1)
vector_fp m_rmolwts
inverse of species molecular weights (kmol kg-1)
int m_stateNum = -1
State Change variable.
std::vector< std::string > m_speciesNames
Vector of the species names.
std::map< std::string, size_t > m_speciesIndices
Map of species names to indices.
std::map< std::string, size_t > m_speciesLower
Map of lower-case species names to indices.
size_t m_mm = 0
Number of elements.
vector_fp m_atomicWeights
element atomic weights (kg kmol-1)
vector_int m_atomicNumbers
element atomic numbers
std::vector< std::string > m_elementNames
element names
vector_int m_elem_type
Vector of element types.
vector_fp m_entropy298
Entropy at 298.15 K and 1 bar of stable state pure elements (J kmol-1)
Detailed Description
Class Phase is the base class for phases of matter, managing the species and elements in a phase, as well as the independent variables of temperature, mass density (compressible substances) or pressure (incompressible substances), species mass/mole fraction, and other generalized forces and intrinsic properties (such as electric potential) that define the thermodynamic state.
Class Phase provides information about the elements and species in a phase - names, index numbers (location in arrays), atomic or molecular weights, etc. The set of elements must include all those that compose the species, but may include additional elements.
It also stores an array of species molecular weights, which are used to convert between mole and mass representations of the composition. For efficiency in mass/mole conversion, the vector of mass fractions divided by molecular weight \(Y_k/M_k \) is also stored.
Class Phase is not usually used directly. Its primary use is as a base class for class ThermoPhase. It is not generally necessary to overloaded any of class Phase's methods, which handles both compressible and incompressible phases. For incompressible phases, the density is replaced by the pressure as the independent variable, and can no longer be set directly. In this case, the density needs to be calculated from a suitable equation of state, and assigned to the object using the assignDensity() method. This also applies for nearly-incompressible phases or phases which utilize standard states based on a T and P, in which case they need to overload these functions too.
Class Phase contains a number of utility functions that will set the state of the phase in its entirety, by first setting the composition, and then temperature and pressure. An example of this is the function Phase::setState_TPY(double t, double p, const double* y).
For bulk (3-dimensional) phases, the mass density has units of kg/m^3, and the molar density and concentrations have units of kmol/m^3, and the units listed in the methods of the Phase class assume a bulk phase. However, for surface (2-dimensional) phases have units of kg/m^2 and kmol/m^2, respectively. And for edge (1-dimensional) phases, these units kg/m and kmol/m.
Class Phase contains methods for saving and restoring the full internal state of a given phase. These are saveState() and restoreState(). These functions operate on a state vector, which by default uses the first two entries for temperature and density (compressible substances) or temperature and pressure (incompressible substances). If the substance is not pure in a thermodynamic sense (that is, it may contain multiple species), the state also contains nSpecies() entries that specify the composition by corresponding mass fractions. Default definitions can be overloaded by derived classes. For any phase, the native definition of its thermodynamic state is defined the method nativeState(), with the length of the state vector returned by by stateSize(). In addition, methods isPure() and isCompressible() provide information on the implementation of a Phase object.
A species name is referred to via speciesName(), which is unique within a given phase. Note that within multiphase mixtures (MultiPhase()), both a phase name/index as well as species name are required to access information about a species in a particular phase. For surfaces, the species names are unique among the phases.
Todo:
Specify that the input mole, mass, and volume fraction vectors must sum to one on entry to the set state routines. Non-conforming mole/mass fraction vectors are not thermodynamically consistent. Moreover, unless we do this, the calculation of Jacobians will be altered whenever the treatment of non- conforming mole fractions is changed. Add setState functions corresponding to specifying mole numbers, which is actually what is being done (well one of the options, there are many) when non- conforming mole fractions are input. Note, we realize that most numerical Jacobian and some analytical Jacobians use non-conforming calculations. These can easily be changed to the set mole number setState functions.
Definition at line 106 of file Phase.h.
Constructor & Destructor Documentation
Phase()
Phase () default
Default constructor.
Member Function Documentation
name()
std::string name () const
Return the name of the phase.
Names are unique within a Cantera problem.
Definition at line 20 of file Phase.cpp.
References Phase::m_name.
Referenced by MultiPhase::addPhase(), Phase::addSpeciesAlias(), ReactingSurf1D::asArray(), Phase::assertCompressible(), Phase::findIsomers(), Phase::findSpeciesLower(), Phase::getCompositionFromMap(), StFlow::getMeta(), ThermoPhase::getParameters(), CoverageDependentSurfPhase::getSpeciesParameters(), DebyeHuckel::getSpeciesParameters(), IdealSolidSolnPhase::getSpeciesParameters(), LatticePhase::getSpeciesParameters(), LatticeSolidPhase::getSpeciesParameters(), PengRobinson::getSpeciesParameters(), RedlichKwongMFTP::getSpeciesParameters(), StoichSubstance::getSpeciesParameters(), VPStandardStateTP::getSpeciesParameters(), BinarySolutionTabulatedThermo::initThermo(), LatticeSolidPhase::initThermo(), PengRobinson::initThermo(), PureFluidPhase::initThermo(), RedlichKwongMFTP::initThermo(), Kinetics::kineticsSpeciesIndex(), Phase::nativeMode(), Cantera::operator<<(), ThermoPhase::report(), MolalityVPSSTP::report(), PureFluidPhase::report(), vcs_MultiPhaseEquil::reportCSV(), LatticeSolidPhase::setLatticeStoichiometry(), Phase::setName(), MaskellSolidSolnPhase::setProductSpecies(), PureFluidPhase::setSubstance(), Phase::species(), vcs_VolPhase::transferElementsFM(), and VCS_SOLVE::VCS_SOLVE().
setName()
void setName (const std::string & nm)
Sets the string name for the phase.
Parameters
nm String name of the phase
Definition at line 25 of file Phase.cpp.
References Phase::m_name, and Phase::name().
Referenced by Cantera::setupPhase().
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented in BinarySolutionTabulatedThermo, CoverageDependentSurfPhase, DebyeHuckel, EdgePhase, HMWSoln, IdealGasPhase, IdealMolalSoln, IdealSolidSolnPhase, IdealSolnGasVPSS, IonsFromNeutralVPSSTP, LatticePhase, LatticeSolidPhase, MargulesVPSSTP, MaskellSolidSolnPhase, MetalPhase, MixtureFugacityTP, PengRobinson, PlasmaPhase, PureFluidPhase, RedlichKisterVPSSTP, RedlichKwongMFTP, SingleSpeciesTP, StoichSubstance, SurfPhase, ThermoPhase, and WaterSSTP.
Definition at line 145 of file Phase.h.
Referenced by Phase::assertCompressible(), Phase::pressure(), Phase::setElectronTemperature(), and Phase::setPressure().
elementName()
string elementName (size_t m) const
Name of the element with index m.
Parameters
m Element index.
Definition at line 49 of file Phase.cpp.
References Phase::checkElementIndex(), and Phase::m_elementNames.
Referenced by MultiPhase::addPhase(), Reaction::checkBalance(), PDSS_HKFT::convertDGFormation(), Phase::elementIndex(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), ThermoPhase::getParameters(), ChemEquil::initialize(), ChemEquil::setInitialMoles(), and vcs_VolPhase::transferElementsFM().
elementIndex()
size_t elementIndex (const std::string & name) const
Return the index of element named 'name'.
The index is an integer assigned to each element in the order it was added. Returns npos if the specified element is not found.
Parameters
name Name of the element
Definition at line 55 of file Phase.cpp.
References Phase::elementName(), Phase::m_elementNames, Phase::m_mm, and Cantera::npos.
Referenced by Phase::addSpecies(), MultiPhase::init(), WaterSSTP::initThermo(), PDSS_HKFT::LookupGe(), ThermoPhase::mixtureFraction(), ThermoPhase::o2Present(), and ThermoPhase::o2Required().
elementNames()
const vector< string > & elementNames () const
Return a read-only reference to the vector of element names.
Definition at line 65 of file Phase.cpp.
References Phase::m_elementNames.
Referenced by ThermoPhase::getParameters().
atomicWeight()
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
Parameters
m Element index
Definition at line 70 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by Phase::elementalMassFraction(), ChemEquil::initialize(), and WaterSSTP::initThermo().
entropyElement298()
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
If no entropy value was provided when the phase was constructed, returns the value ENTROPY298_UNKNOWN.
Parameters
m Element index
Definition at line 75 of file Phase.cpp.
References Phase::checkElementIndex(), and Phase::m_entropy298.
Referenced by PDSS_HKFT::LookupGe().
atomicNumber()
int atomicNumber (size_t m) const
Atomic number of element m.
Parameters
m Element index
Definition at line 86 of file Phase.cpp.
References Phase::m_atomicNumbers.
Referenced by MultiPhase::addPhase().
elementType()
int elementType (size_t m) const
Return the element constraint type Possible types include:
CT_ELEM_TYPE_TURNEDOFF -1
CT_ELEM_TYPE_ABSPOS 0
CT_ELEM_TYPE_ELECTRONCHARGE 1
CT_ELEM_TYPE_CHARGENEUTRALITY 2
CT_ELEM_TYPE_LATTICERATIO 3
CT_ELEM_TYPE_KINETICFROZEN 4
CT_ELEM_TYPE_SURFACECONSTRAINT 5
CT_ELEM_TYPE_OTHERCONSTRAINT 6
The default is CT_ELEM_TYPE_ABSPOS.
Parameters
m Element index
Returns
the element type
Definition at line 91 of file Phase.cpp.
References Phase::m_elem_type.
Referenced by vcs_VolPhase::transferElementsFM().
changeElementType()
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
Parameters
m Element index
elem_type New elem type to be assigned
Returns
the old element type
Definition at line 96 of file Phase.cpp.
References Phase::m_elem_type.
atomicWeights()
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
Definition at line 81 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by Phase::addSpecies().
nElements()
size_t nElements () const
Number of elements.
Definition at line 30 of file Phase.cpp.
References Phase::m_mm.
Referenced by MultiPhase::addPhase(), Phase::addSpecies(), Reaction::checkBalance(), PDSS_HKFT::convertDGFormation(), Phase::elementalMoleFraction(), ChemEquil::equilibrate(), MolalityVPSSTP::findCLMIndex(), ThermoPhase::getParameters(), ChemEquil::initialize(), IonsFromNeutralVPSSTP::initThermo(), LatticeSolidPhase::setLatticeStoichiometry(), vcs_VolPhase::transferElementsFM(), and VCS_SOLVE::VCS_SOLVE().
checkElementIndex()
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
Throws an exception if m is greater than nElements()-1
Definition at line 35 of file Phase.cpp.
References Phase::m_mm.
Referenced by Phase::elementalMassFraction(), Phase::elementalMoleFraction(), Phase::elementName(), Phase::entropyElement298(), and Phase::nAtoms().
checkElementArraySize()
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
Throws an exception if mm is less than nElements(). Used before calls which take an array pointer.
Definition at line 42 of file Phase.cpp.
References Phase::m_mm.
nAtoms()
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
Parameters
k species index
m element index
Definition at line 103 of file Phase.cpp.
References Phase::checkElementIndex(), Phase::checkSpeciesIndex(), Phase::m_mm, and Phase::m_speciesComp.
Referenced by Reaction::checkBalance(), PDSS_HKFT::convertDGFormation(), Phase::elementalMassFraction(), Phase::elementalMoleFraction(), MolalityVPSSTP::findCLMIndex(), MultiPhase::init(), ChemEquil::initialize(), IonsFromNeutralVPSSTP::initThermo(), ThermoPhase::mixtureFraction(), ThermoPhase::o2Present(), ThermoPhase::o2Required(), and vcs_VolPhase::transferElementsFM().
getAtoms()
void getAtoms (size_t k, double * atomArray) const
Get a vector containing the atomic composition of species k.
Parameters
k species index
atomArray vector containing the atomic number in the species. Length: m_mm
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 110 of file Phase.cpp.
References Phase::m_mm, Phase::m_speciesComp, and Cantera::warn_deprecated().
speciesIndex()
size_t speciesIndex (const std::string & name) const
Returns the index of a species named 'name' within the Phase object.
The first species in the phase will have an index 0, and the last one will have an index of nSpecies() - 1.
Parameters
name String name of the species. It may also be in the form phaseName:speciesName
Returns
The index of the species. If the name is not found, the value npos is returned.
Definition at line 138 of file Phase.cpp.
References Phase::findSpeciesLower(), Phase::m_caseSensitiveSpecies, Phase::m_speciesIndices, and Cantera::npos.
Referenced by RedlichKisterVPSSTP::addBinaryInteraction(), MargulesVPSSTP::addBinaryInteraction(), Phase::addSpeciesAlias(), Reaction::checkBalance(), IonGasTransport::fitDiffCoeffs(), Phase::getCompositionFromMap(), CoverageDependentSurfPhase::getSpeciesParameters(), DebyeHuckel::getSpeciesParameters(), IdealSolidSolnPhase::getSpeciesParameters(), LatticePhase::getSpeciesParameters(), PengRobinson::getSpeciesParameters(), RedlichKwongMFTP::getSpeciesParameters(), StoichSubstance::getSpeciesParameters(), VPStandardStateTP::getSpeciesParameters(), BinarySolutionTabulatedThermo::initThermo(), CoverageDependentSurfPhase::initThermo(), HMWSoln::initThermo(), PengRobinson::initThermo(), RedlichKwongMFTP::initThermo(), FlowDevice::install(), Kinetics::kineticsSpeciesIndex(), Phase::massFraction(), Phase::moleFraction(), MolalityVPSSTP::report(), DebyeHuckel::setBeta(), PengRobinson::setBinaryCoeffs(), RedlichKwongMFTP::setBinaryCoeffs(), StickingCoverage::setContext(), MaskellSolidSolnPhase::setProductSpecies(), PengRobinson::setSpeciesCoeffs(), RedlichKwongMFTP::setSpeciesCoeffs(), Phase::species(), Reactor::speciesIndex(), Kinetics::speciesPhase(), StFlow::StFlow(), and Reaction::usesElectrochemistry().
speciesName()
string speciesName (size_t k) const
Name of the species with index k.
Parameters
k index of the species
Definition at line 151 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_speciesNames.
Referenced by Reactor::addSensitivitySpeciesEnthalpy(), MoleReactor::addSurfaceJacobian(), ConstPressureMoleReactor::componentName(), ConstPressureReactor::componentName(), IdealGasConstPressureMoleReactor::componentName(), MoleReactor::componentName(), Reactor::componentName(), FlowReactor::componentName(), ReactingSurf1D::componentName(), StFlow::componentName(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MoleReactor::evalSurfaces(), Reactor::evalSurfaces(), MolalityVPSSTP::findCLMIndex(), IonGasTransport::fitDiffCoeffs(), Phase::getMassFractionsByName(), StFlow::getMeta(), Phase::getMoleFractionsByName(), BinarySolutionTabulatedThermo::getParameters(), DebyeHuckel::getParameters(), HMWSoln::getParameters(), MargulesVPSSTP::getParameters(), MaskellSolidSolnPhase::getParameters(), RedlichKisterVPSSTP::getParameters(), ThermoPhase::getParameters(), CoverageDependentSurfPhase::getSpeciesParameters(), MultiPhase::init(), ChemEquil::initialize(), PDSS_HKFT::initThermo(), StoichSubstance::initThermo(), FlowDevice::install(), Kinetics::kineticsSpeciesName(), Phase::modifySpecies(), ThermoPhase::modifySpecies(), HMWSoln::printCoeffs(), ThermoPhase::report(), MolalityVPSSTP::report(), vcs_MultiPhaseEquil::reportCSV(), ThermoPhase::reportCSV(), SurfPhase::setCoveragesByName(), ChemEquil::setInitialMoles(), MolalityVPSSTP::setMolalitiesByName(), Transport::setThermo(), ReactingSurf1D::show(), Phase::species(), Phase::speciesSPName(), ChemEquil::update(), and RedlichKwongMFTP::updateMixingExpressions().
speciesSPName()
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
Parameters
k Species index within the phase
Returns
The "phaseName:speciesName" string
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 176 of file Phase.cpp.
References Phase::m_name, Phase::speciesName(), and Cantera::warn_deprecated().
speciesNames()
const vector< string > & speciesNames () const
Return a const reference to the vector of species names.
Definition at line 157 of file Phase.cpp.
References Phase::m_speciesNames.
Referenced by ThermoPhase::getParameters(), InterfaceRateBase::setContext(), SurfPhase::setCoveragesByName(), MolalityVPSSTP::setMolalitiesByName(), and HighPressureGasTransport::viscosity().
nSpecies()
size_t nSpecies () const inline
Returns the number of species in the phase.
Definition at line 256 of file Phase.h.
References Phase::m_kk.
Referenced by MultiPhase::addPhase(), Reactor::addSensitivitySpeciesEnthalpy(), MultiPhase::calcElemAbundances(), ConstPressureMoleReactor::componentName(), ConstPressureReactor::componentName(), IdealGasConstPressureMoleReactor::componentName(), MoleReactor::componentName(), Reactor::componentName(), FlowReactor::componentName(), MultiPhaseEquil::computeReactionSteps(), MargulesVPSSTP::cp_mole(), MargulesVPSSTP::enthalpy_mole(), MargulesVPSSTP::entropy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), FlowReactor::evalDae(), MoleReactor::evalSurfaces(), Reactor::evalSurfaces(), ThermoPhase::getActivities(), MetalPhase::getActivityConcentrations(), HighPressureGasTransport::getBinaryDiffCoeffs(), MetalPhase::getChemPotentials(), ImplicitSurfChem::getConcSpecies(), MolalityVPSSTP::getCsvReportData(), ThermoPhase::getCsvReportData(), MetalPhase::getEnthalpy_RT(), MetalPhase::getEntropy_R(), MultiTransport::getMassFluxes(), MultiTransport::getMolarFluxes(), MultiPhase::getMoles(), HighPressureGasTransport::getMultiDiffCoeffs(), MetalPhase::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), MetalPhase::getStandardChemPotentials(), Cantera::hasChargedSpecies(), ImplicitSurfChem::ImplicitSurfChem(), MultiPhase::init(), OutletRes1D::init(), IonGasTransport::init(), GasTransport::init(), ChemEquil::initialize(), DustyGasTransport::initialize(), BinarySolutionTabulatedThermo::initThermo(), DebyeHuckel::initThermo(), IdealMolalSoln::initThermo(), FlowDevice::install(), InterfaceKinetics::interfaceCurrent(), vcs_MultiPhaseEquil::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::resetHf298(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), Kinetics::selectPhase(), ImplicitSurfChem::setConcSpecies(), ReactorSurface::setKinetics(), ReactingSurf1D::setKinetics(), ReactingSurf1D::setKineticsMgr(), StFlow::setMeta(), MultiPhase::setMoles(), MultiPhase::setPhaseMoleFractions(), Transport::setThermo(), ReactorBase::setThermoMgr(), Cantera::setupPhase(), solveSP::solveSP(), Reactor::speciesIndex(), Phase::stateSize(), StFlow::StFlow(), HighPressureGasTransport::thermalConductivity(), vcs_VolPhase::transferElementsFM(), MixTransport::update_T(), MultiTransport::update_T(), InterfaceKinetics::updateMu0(), MultiTransport::updateThermal_T(), MultiPhase::uploadMoleFractionsFromPhases(), VCS_SOLVE::vcs_prob_specifyFully(), VCS_SOLVE::VCS_SOLVE(), and HighPressureGasTransport::viscosity().
checkSpeciesIndex()
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
Throws an exception if k is greater than nSpecies()-1
Definition at line 162 of file Phase.cpp.
References Phase::m_kk.
Referenced by Phase::concentration(), DebyeHuckel::getSpeciesParameters(), PengRobinson::getSpeciesParameters(), RedlichKwongMFTP::getSpeciesParameters(), Phase::massFraction(), Phase::molecularWeight(), Phase::moleFraction(), Phase::nAtoms(), Phase::species(), and Phase::speciesName().
checkSpeciesArraySize()
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
Throws an exception if kk is less than nSpecies(). Used before calls which take an array pointer.
Definition at line 169 of file Phase.cpp.
References Phase::m_kk.
isPure()
virtual bool isPure () const inline virtual
Return whether phase represents a pure (single species) substance.
Reimplemented in PureFluidPhase, and SingleSpeciesTP.
Definition at line 272 of file Phase.h.
Referenced by Phase::fullStates(), Phase::nativeState(), Phase::partialStates(), and Phase::stateSize().
hasPhaseTransition()
virtual bool hasPhaseTransition () const inline virtual
Return whether phase represents a substance with phase transitions.
Reimplemented in PureFluidPhase.
Definition at line 277 of file Phase.h.
isCompressible()
virtual bool isCompressible () const inline virtual
Return whether phase represents a compressible substance.
Reimplemented in IdealSolidSolnPhase, LatticePhase, LatticeSolidPhase, MetalPhase, StoichSubstance, SurfPhase, and VPStandardStateTP.
Definition at line 282 of file Phase.h.
Referenced by Phase::assertCompressible(), Phase::fullStates(), Phase::nativeState(), Phase::partialStates(), Phase::restoreState(), and Phase::saveState().
nativeState()
std::map< std::string, size_t > nativeState () const virtual
Return a map of properties defining the native state of a substance.
By default, entries include "T", "D", "Y" for a compressible substance and "T", "P", "Y" for an incompressible substance, with offsets 0, 1 and 2, respectively. Mass fractions "Y" are omitted for pure species. In all cases, offsets into the state vector are used by saveState() and restoreState().
Reimplemented in LatticePhase, and LatticeSolidPhase.
Definition at line 182 of file Phase.cpp.
References Phase::isCompressible(), and Phase::isPure().
Referenced by ThermoPhase::getParameters(), Phase::nativeMode(), Phase::restoreState(), and Phase::saveState().
nativeMode()
string nativeMode () const
Return string acronym representing the native state of a Phase.
Examples: "TP", "TDY", "TPY".
See also
nativeState
Since
New in Cantera 3.0
Definition at line 199 of file Phase.cpp.
References Phase::name(), and Phase::nativeState().
fullStates()
vector< std::string > fullStates () const virtual
Return a vector containing full states defining a phase.
Full states list combinations of properties that allow for the specification of a thermodynamic state based on user input. Properties and states are represented by single letter acronyms, and combinations of letters, respectively (for example, "TDY", "TPX", "SVX"). Supported property acronyms are: "T": temperature "P": pressure "D": density "X": mole fractions "Y": mass fractions "T": temperature "U": specific internal energy "V": specific volume "H": specific enthalpy "S": specific entropy "Q": vapor fraction
Reimplemented in PureFluidPhase.
Definition at line 212 of file Phase.cpp.
References Phase::isCompressible(), and Phase::isPure().
partialStates()
vector< std::string > partialStates () const virtual
Return a vector of settable partial property sets within a phase.
Partial states encompass all valid combinations of properties that allow for the specification of a state while ignoring species concentrations (such as "TD", "TP", "SV").
Reimplemented in PureFluidPhase.
Definition at line 230 of file Phase.cpp.
References Phase::isCompressible(), and Phase::isPure().
stateSize()
size_t stateSize () const virtual
Return size of vector defining internal state of the phase.
Used by saveState() and restoreState().
Definition at line 243 of file Phase.cpp.
References Phase::isPure(), and Phase::nSpecies().
Referenced by ReactingSurf1D::asArray(), Phase::restoreState(), and Phase::saveState().
saveState() [1/2]
void saveState (vector_fp & state) const
Save the current internal state of the phase.
Write to vector 'state' the current internal state.
Parameters
state output vector. Will be resized to stateSize().
Definition at line 251 of file Phase.cpp.
References Phase::saveState(), and Phase::stateSize().
Referenced by BulkKinetics::applyEquilibriumConstants_ddT(), ReactingSurf1D::asArray(), ThermoPhase::equilibrate(), ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), TransportFactory::newTransport(), Phase::saveState(), ReactorBase::setThermoMgr(), ReactorBase::syncState(), Reactor::updateConnected(), and FlowReactor::updateState().
saveState() [2/2]
void saveState (size_t lenstate, doublereal * state) const virtual
Write to array 'state' the current internal state.
Parameters
lenstate length of the state array. Must be >= stateSize()
state output vector. Must be of length stateSizes() or greater.
Definition at line 257 of file Phase.cpp.
References Phase::density(), Phase::getMassFractions(), Phase::getMoleFractions(), Phase::isCompressible(), Phase::nativeState(), Phase::pressure(), and Phase::temperature().
restoreState() [1/2]
void restoreState (const vector_fp & state)
Restore a state saved on a previous call to saveState.
Parameters
state State vector containing the previously saved state.
Definition at line 275 of file Phase.cpp.
References Phase::restoreState().
Referenced by BulkKinetics::applyEquilibriumConstants_ddT(), ThermoPhase::equilibrate(), ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), ConstPressureMoleReactor::eval(), ConstPressureReactor::eval(), IdealGasConstPressureMoleReactor::eval(), IdealGasConstPressureReactor::eval(), IdealGasMoleReactor::eval(), IdealGasReactor::eval(), MoleReactor::eval(), Reactor::eval(), FlowReactor::evalDae(), MultiTransport::getMassFluxes(), ConstPressureMoleReactor::getState(), IdealGasConstPressureMoleReactor::getState(), IdealGasMoleReactor::getState(), MoleReactor::getState(), Reactor::getState(), ConstPressureReactor::getState(), IdealGasConstPressureReactor::getState(), IdealGasReactor::getState(), FlowReactor::getStateDae(), Reactor::initialize(), FlowReactor::initialize(), TransportFactory::newTransport(), ReactorBase::restoreState(), and Phase::restoreState().
restoreState() [2/2]
void restoreState (size_t lenstate, const doublereal * state) virtual
Restore the state of the phase from a previously saved state vector.
Parameters
lenstate Length of the state vector
state Vector of state conditions.
Definition at line 280 of file Phase.cpp.
References Phase::compositionChanged(), Phase::isCompressible(), Phase::nativeState(), Phase::setDensity(), Phase::setMassFractions_NoNorm(), Phase::setMoleFractions_NoNorm(), Phase::setPressure(), Phase::setTemperature(), and Phase::stateSize().
setMoleFractionsByName() [1/2]
void setMoleFractionsByName (const compositionMap & xMap)
Set the species mole fractions by name.
Species not listed by name in xMap are set to zero.
Parameters
xMap map from species names to mole fraction values.
Definition at line 345 of file Phase.cpp.
References Phase::getCompositionFromMap(), and Phase::setMoleFractions().
Referenced by OutletRes1D::setMoleFractions(), Phase::setMoleFractionsByName(), ThermoPhase::setState(), ThermoPhase::setState_RPX(), ThermoPhase::setState_TPX(), and Phase::setState_TRX().
setMoleFractionsByName() [2/2]
void setMoleFractionsByName (const std::string & x)
Set the mole fractions of a group of species by name.
Species which are not listed by name in the composition map are set to zero.
Parameters
x string x in the form of a composition map
Definition at line 351 of file Phase.cpp.
References Cantera::parseCompString(), and Phase::setMoleFractionsByName().
setMassFractionsByName() [1/2]
void setMassFractionsByName (const compositionMap & yMap)
Set the species mass fractions by name.
Species not listed by name in yMap are set to zero.
Parameters
yMap map from species names to mass fraction values.
Definition at line 381 of file Phase.cpp.
References Phase::getCompositionFromMap(), and Phase::setMassFractions().
Referenced by Phase::setMassFractionsByName(), ThermoPhase::setState(), ThermoPhase::setState_RPY(), ThermoPhase::setState_TPY(), and Phase::setState_TRY().
setMassFractionsByName() [2/2]
void setMassFractionsByName (const std::string & x)
Set the species mass fractions by name.
Species not listed by name in x are set to zero.
Parameters
x String containing a composition map
Definition at line 387 of file Phase.cpp.
References Cantera::parseCompString(), and Phase::setMassFractionsByName().
setState_TRX() [1/2]
void setState_TRX (doublereal t, doublereal dens, const doublereal * x)
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x vector of species mole fractions, length m_kk
Deprecated:
To be removed after Cantera 3.0; replaceable by calls to setMoleFractions() and setState_TD().
Definition at line 392 of file Phase.cpp.
References Phase::setMoleFractions(), Phase::setState_TD(), and Cantera::warn_deprecated().
setState_TRX() [2/2]
void setState_TRX (doublereal t, doublereal dens, const compositionMap & x)
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x Composition Map containing the mole fractions. Species not included in the map are assumed to have a zero mole fraction.
Deprecated:
To be removed after Cantera 3.0; replaceable by calls to setMoleFractionsByName() and setState_TD().
Definition at line 410 of file Phase.cpp.
References Phase::setMoleFractionsByName(), Phase::setState_TD(), and Cantera::warn_deprecated().
setState_TRY() [1/2]
void setState_TRY (doublereal t, doublereal dens, const doublereal * y)
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y vector of species mass fractions, length m_kk
Deprecated:
To be removed after Cantera 3.0; replaceable by calls to setMassFractions() and setState_TD().
Definition at line 419 of file Phase.cpp.
References Phase::setMassFractions(), Phase::setState_TD(), and Cantera::warn_deprecated().
setState_TRY() [2/2]
void setState_TRY (doublereal t, doublereal dens, const compositionMap & y)
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y Composition Map containing the mass fractions. Species not included in the map are assumed to have a zero mass fraction.
Deprecated:
To be removed after Cantera 3.0; replaceable by calls to setMassFractionsByName() and setState_TD().
Definition at line 428 of file Phase.cpp.
References Phase::setMassFractionsByName(), Phase::setState_TD(), and Cantera::warn_deprecated().
setState_TNX()
void setState_TNX (doublereal t, doublereal n, const doublereal * x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
Parameters
t Temperature in kelvin
n molar density (kmol/m^3)
x vector of species mole fractions, length m_kk
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 401 of file Phase.cpp.
References Phase::setMolarDensity(), Phase::setMoleFractions(), Phase::setTemperature(), and Cantera::warn_deprecated().
setState_TR()
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
Parameters
t Temperature in kelvin
rho Density (kg/m^3)
Deprecated:
To be removed after Cantera 3.0; renamed to setState_TD()
Definition at line 437 of file Phase.cpp.
References Phase::setState_TD(), and Cantera::warn_deprecated().
setState_TD()
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
Parameters
t Temperature in kelvin
rho Density (kg/m^3)
Since
New in Cantera 3.0.
Definition at line 444 of file Phase.cpp.
References Phase::setDensity(), and Phase::setTemperature().
Referenced by MixtureFugacityTP::calculatePsat(), MixtureFugacityTP::corr0(), ThermoPhase::setState(), PureFluidPhase::setState_HP(), PureFluidPhase::setState_PV(), PureFluidPhase::setState_SH(), PureFluidPhase::setState_SP(), PureFluidPhase::setState_ST(), PureFluidPhase::setState_SV(), PureFluidPhase::setState_TH(), ThermoPhase::setState_TP(), Phase::setState_TR(), Phase::setState_TRX(), Phase::setState_TRY(), PureFluidPhase::setState_TV(), PureFluidPhase::setState_UP(), PureFluidPhase::setState_UV(), PureFluidPhase::setState_VH(), IdealGasMoleReactor::updateState(), MoleReactor::updateState(), Reactor::updateState(), and IdealGasReactor::updateState().
setState_TX()
void setState_TX (doublereal t, doublereal * x)
Set the internally stored temperature (K) and mole fractions.
Parameters
t Temperature in kelvin
x vector of species mole fractions, length m_kk
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 450 of file Phase.cpp.
References Phase::setMoleFractions(), Phase::setTemperature(), and Cantera::warn_deprecated().
setState_TY()
void setState_TY (doublereal t, doublereal * y)
Set the internally stored temperature (K) and mass fractions.
Parameters
t Temperature in kelvin
y vector of species mass fractions, length m_kk
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 458 of file Phase.cpp.
References Phase::setMassFractions(), Phase::setTemperature(), and Cantera::warn_deprecated().
setState_RX()
void setState_RX (doublereal rho, doublereal * x)
Set the density (kg/m^3) and mole fractions.
Parameters
rho Density (kg/m^3)
x vector of species mole fractions, length m_kk
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 466 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractions(), and Cantera::warn_deprecated().
setState_RY()
void setState_RY (doublereal rho, doublereal * y)
Set the density (kg/m^3) and mass fractions.
Parameters
rho Density (kg/m^3)
y vector of species mass fractions, length m_kk
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 474 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractions(), and Cantera::warn_deprecated().
molecularWeight()
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
Parameters
k index of species k
Returns
the molecular weight of species k.
Definition at line 482 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_molwts.
Referenced by IdealSolidSolnPhase::addSpecies(), LatticePhase::addSpecies(), MolalityVPSSTP::addSpecies(), SingleSpeciesTP::cv_mole(), Phase::elementalMassFraction(), SingleSpeciesTP::getPartialMolarVolumes(), IdealSolidSolnPhase::getSpeciesParameters(), LatticePhase::getSpeciesParameters(), SingleSpeciesTP::getStandardVolumes(), IonGasTransport::init(), VPStandardStateTP::installPDSS(), ThermoPhase::mixtureFraction(), StickingCoverage::setContext(), and VCS_SOLVE::VCS_SOLVE().
getMolecularWeights() [1/2]
void getMolecularWeights (vector_fp & weights) const
Copy the vector of molecular weights into vector weights.
Parameters
weights Output vector of molecular weights (kg/kmol)
Deprecated:
Unused. To be removed after Cantera 3.0
Definition at line 488 of file Phase.cpp.
References Phase::molecularWeights(), and Cantera::warn_deprecated().
getMolecularWeights() [2/2]
void getMolecularWeights (doublereal * weights) const
Copy the vector of molecular weights into array weights.
Parameters
weights Output array of molecular weights (kg/kmol)
Definition at line 495 of file Phase.cpp.
References Phase::molecularWeights().
molecularWeights()
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
units = kg / kmol
Definition at line 501 of file Phase.cpp.
References Phase::m_molwts.
Referenced by ConstPressureReactor::eval(), IdealGasConstPressureReactor::eval(), IdealGasReactor::eval(), Reactor::eval(), ReactingSurf1D::eval(), FlowReactor::evalDae(), Phase::getMolecularWeights(), MixTransport::getSpeciesFluxes(), FlowReactor::getStateDae(), IonGasTransport::init(), DustyGasTransport::initialize(), ThermoPhase::o2Present(), ThermoPhase::o2Required(), MoleReactor::setMassFromMoles(), and StFlow::StFlow().
inverseMolecularWeights()
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
units = kmol / kg
Definition at line 506 of file Phase.cpp.
References Phase::m_rmolwts.
Referenced by ConstPressureMoleReactor::eval(), IdealGasConstPressureMoleReactor::eval(), IdealGasMoleReactor::eval(), MoleReactor::eval(), and MoleReactor::getMoles().
getCharges()
void getCharges (double * charges) const
Copy the vector of species charges into array charges.
Parameters
charges Output array of species charges (elem. charge)
Definition at line 511 of file Phase.cpp.
References Phase::m_speciesCharge.
Referenced by InterfaceKinetics::interfaceCurrent().
getMoleFractionsByName()
compositionMap getMoleFractionsByName (double threshold = 0.0) const
Get the mole fractions by name.
Parameters
threshold Exclude species with mole fractions less than or equal to this threshold.
Returns
Map of species names to mole fractions
Definition at line 516 of file Phase.cpp.
References Phase::m_kk, Phase::moleFraction(), and Phase::speciesName().
moleFraction() [1/2]
double moleFraction (size_t k) const
Return the mole fraction of a single species.
Parameters
k species index
Returns
Mole fraction of the species
Definition at line 545 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_mmw, and Phase::m_ym.
Referenced by BinarySolutionTabulatedThermo::_updateThermo(), BinarySolutionTabulatedThermo::calcDensity(), Phase::chargeDensity(), Phase::elementalMoleFraction(), MaskellSolidSolnPhase::enthalpy_mole(), PlasmaPhase::enthalpy_mole(), CoverageDependentSurfPhase::entropy_mole(), MaskellSolidSolnPhase::entropy_mole(), SurfPhase::entropy_mole(), ChemEquil::equilibrate(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), IdealMolalSoln::getActivities(), MaskellSolidSolnPhase::getActivityCoefficients(), MolalityVPSSTP::getActivityCoefficients(), MixtureFugacityTP::getActivityConcentrations(), IdealSolnGasVPSS::getActivityConcentrations(), MaskellSolidSolnPhase::getActivityConcentrations(), PengRobinson::getChemPotentials(), PlasmaPhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), LatticePhase::getChemPotentials(), MaskellSolidSolnPhase::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), IdealMolalSoln::getMolalityActivityCoefficients(), Phase::getMoleFractionsByName(), ThermoPhase::getParameters(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), Phase::moleFraction(), vcs_MultiPhaseEquil::reportCSV(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and ChemEquil::setInitialMoles().
moleFraction() [2/2]
double moleFraction (const std::string & name) const
Return the mole fraction of a single species.
Parameters
name String name of the species
Returns
Mole fraction of the species
Definition at line 551 of file Phase.cpp.
References Phase::moleFraction(), Cantera::npos, and Phase::speciesIndex().
getMassFractionsByName()
compositionMap getMassFractionsByName (double threshold = 0.0) const
Get the mass fractions by name.
Parameters
threshold Exclude species with mass fractions less than or equal to this threshold.
Returns
Map of species names to mass fractions
Definition at line 528 of file Phase.cpp.
References Phase::m_kk, Phase::massFraction(), and Phase::speciesName().
massFraction() [1/2]
double massFraction (size_t k) const
Return the mass fraction of a single species.
Parameters
k species index
Returns
Mass fraction of the species
Definition at line 568 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_y.
Referenced by Phase::elementalMassFraction(), Phase::getMassFractionsByName(), and ThermoPhase::getParameters().
massFraction() [2/2]
double massFraction (const std::string & name) const
Return the mass fraction of a single species.
Parameters
name String name of the species
Returns
Mass Fraction of the species
Definition at line 574 of file Phase.cpp.
References Phase::massFractions(), Cantera::npos, and Phase::speciesIndex().
getMoleFractions()
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
Parameters
x On return, x contains the mole fractions. Must have a length greater than or equal to the number of species.
Definition at line 540 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::scale().
Referenced by MaskellSolidSolnPhase::calcDensity(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), GibbsExcessVPSSTP::compositionChanged(), MixtureFugacityTP::compositionChanged(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), GibbsExcessVPSSTP::getActivities(), IdealSolidSolnPhase::getActivityConcentrations(), LatticePhase::getActivityConcentrations(), HighPressureGasTransport::getBinaryDiffCoeffs(), SurfPhase::getCoverages(), MolalityVPSSTP::getCsvReportData(), ThermoPhase::getCsvReportData(), MultiTransport::getMassFluxes(), LatticeSolidPhase::getMoleFractions(), HighPressureGasTransport::getMultiDiffCoeffs(), DustyGasTransport::initialize(), HMWSoln::initThermo(), HMWSoln::printCoeffs(), HMWSoln::relative_molal_enthalpy(), ThermoPhase::report(), MolalityVPSSTP::report(), ThermoPhase::reportCSV(), Phase::saveState(), MolalityVPSSTP::setMolalitiesByName(), MultiPhase::setMoles(), HighPressureGasTransport::thermalConductivity(), ChemEquil::update(), MixTransport::update_C(), MultiTransport::update_C(), solveSP::updateMFKinSpecies(), DustyGasTransport::updateTransport_C(), MultiPhase::uploadMoleFractionsFromPhases(), and HighPressureGasTransport::viscosity().
setMoleFractions()
void setMoleFractions (const double *const x) virtual
Set the mole fractions to the specified values.
There is no restriction on the sum of the mole fraction vector. Internally, the Phase object will normalize this vector before storing its contents.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species, m_kk.
Reimplemented in LatticeSolidPhase, and SingleSpeciesTP.
Definition at line 304 of file Phase.cpp.
References Phase::compositionChanged(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, and Phase::m_ym.
Referenced by ChemEquil::calcEmoles(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), HMWSoln::initThermo(), SurfPhase::setCoverages(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), OutletRes1D::setMoleFractions(), LatticeSolidPhase::setMoleFractions(), Phase::setMoleFractionsByName(), ThermoPhase::setState_PX(), ThermoPhase::setState_RPX(), Phase::setState_RX(), Phase::setState_TNX(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), Phase::setState_TX(), IdealSolnGasVPSS::setToEquilState(), IdealGasPhase::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
setMoleFractions_NoNorm()
void setMoleFractions_NoNorm (const double *const x) virtual
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Definition at line 336 of file Phase.cpp.
References Phase::compositionChanged(), Cantera::dot(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Cantera::scale().
Referenced by Phase::restoreState(), and SurfPhase::setCoveragesNoNorm().
getMassFractions()
void getMassFractions (double *const y) const
Get the species mass fractions.
Parameters
[out] y Array of mass fractions, length nSpecies()
Definition at line 584 of file Phase.cpp.
References Phase::m_y.
Referenced by StFlow::_getInitialSoln(), ThermoPhase::getCsvReportData(), Reactor::getState(), ConstPressureReactor::getState(), IdealGasConstPressureReactor::getState(), IdealGasReactor::getState(), FlowReactor::getStateDae(), ThermoPhase::report(), StFlow::resetBadValues(), Phase::saveState(), and OutletRes1D::setMoleFractions().
massFractions()
const double * massFractions () const inline
Return a const pointer to the mass fraction array.
Definition at line 546 of file Phase.h.
References Phase::m_y.
Referenced by ThermoPhase::equivalenceRatio(), ConstPressureReactor::eval(), IdealGasConstPressureReactor::eval(), IdealGasReactor::eval(), Reactor::eval(), MultiTransport::getMassFluxes(), MoleReactor::getMoles(), MixTransport::getSpeciesFluxes(), MultiTransport::getSpeciesFluxes(), Phase::massFraction(), and ThermoPhase::mixtureFraction().
setMassFractions()
void setMassFractions (const double *const y) virtual
Set the mass fractions to the specified values and normalize them.
Parameters
[in] y Array of unnormalized mass fraction values. Length must be greater than or equal to the number of species. The Phase object will normalize this vector before storing its contents.
Reimplemented in LatticeSolidPhase, and SingleSpeciesTP.
Definition at line 356 of file Phase.cpp.
References Phase::compositionChanged(), Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Cantera::scale().
Referenced by StFlow::resetBadValues(), ThermoPhase::setEquivalenceRatio(), Phase::setMassFractionsByName(), ThermoPhase::setState_PY(), ThermoPhase::setState_RPY(), Phase::setState_RY(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), and Phase::setState_TY().
setMassFractions_NoNorm()
void setMassFractions_NoNorm (const double *const y) virtual
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented in LatticeSolidPhase.
Definition at line 370 of file Phase.cpp.
References Phase::compositionChanged(), Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, and Phase::m_ym.
Referenced by Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), ThermoPhase::setMixtureFraction(), Reactor::updateState(), FlowReactor::updateState(), ConstPressureReactor::updateState(), IdealGasConstPressureReactor::updateState(), and IdealGasReactor::updateState().
getConcentrations()
void getConcentrations (double *const c) const virtual
Get the species concentrations (kmol/m^3).
Parameters
[out] c The vector of species concentrations. Units are kmol/m^3. The length of the vector must be greater than or equal to the number of species within the phase.
Reimplemented in LatticeSolidPhase.
Definition at line 595 of file Phase.cpp.
References Phase::m_dens, Phase::m_ym, and Cantera::scale().
Referenced by InterfaceKinetics::_update_rates_C(), IdealGasPhase::getActivityConcentrations(), SurfPhase::getActivityConcentrations(), and ImplicitSurfChem::getConcSpecies().
concentration()
double concentration (const size_t k) const virtual
Concentration of species k.
If k is outside the valid range, an exception will be thrown.
Parameters
[in] k Index of the species within the phase.
Returns
the concentration of species k (kmol m-3).
Reimplemented in LatticeSolidPhase.
Definition at line 589 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_dens, Phase::m_rmolwts, and Phase::m_y.
Referenced by PlasmaPhase::electronPressure(), and SurfPhase::entropy_mole().
setConcentrations()
void setConcentrations (const double *const conc) virtual
Set the concentrations to the specified values within the phase.
We set the concentrations here and therefore we set the overall density of the phase. We hold the temperature constant during this operation. Therefore, we have possibly changed the pressure of the phase by calling this routine.
Parameters
[in] conc Array of concentrations in dimensional units. For bulk phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the number of species in the phase.
Reimplemented in LatticeSolidPhase.
Definition at line 600 of file Phase.cpp.
References Phase::assertCompressible(), Phase::compositionChanged(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Phase::setDensity().
Referenced by ImplicitSurfChem::setConcSpecies().
setConcentrationsNoNorm()
void setConcentrationsNoNorm (const double *const conc) virtual
Set the concentrations without ignoring negative concentrations.
Definition at line 622 of file Phase.cpp.
References Phase::assertCompressible(), Phase::compositionChanged(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Phase::setDensity().
setMolesNoTruncate()
void setMolesNoTruncate (const double *const N) virtual
Set the state of the object with moles in [kmol].
Definition at line 641 of file Phase.cpp.
References Phase::compositionChanged(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Cantera::scale().
Referenced by ConstPressureMoleReactor::updateState(), IdealGasConstPressureMoleReactor::updateState(), IdealGasMoleReactor::updateState(), and MoleReactor::updateState().
elementalMassFraction()
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
The elemental mass fraction \(Z_{\mathrm{mass},m}\) of element \(m\) is defined as
\[ Z_{\mathrm{mass},m} = \sum_k \frac{a_{m,k} M_m}{M_k} Y_k \]
with \(a_{m,k}\) being the number of atoms of element \(m\) in species \(k\), \(M_m\) the atomic weight of element \(m\), \(M_k\) the molecular weight of species \(k\), and \(Y_k\) the mass fraction of species \(k\).
Parameters
[in] m Index of the element within the phase. If m is outside the valid range, an exception will be thrown.
Returns
the elemental mass fraction of element m.
Definition at line 660 of file Phase.cpp.
References Phase::atomicWeight(), Phase::checkElementIndex(), Phase::m_kk, Phase::massFraction(), Phase::molecularWeight(), and Phase::nAtoms().
elementalMoleFraction()
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
The elemental mole fraction \(Z_{\mathrm{mole},m}\) of element \(m\) is the number of atoms of element m divided by the total number of atoms. It is defined as:
\[ Z_{\mathrm{mole},m} = \frac{\sum_k a_{m,k} X_k} {\sum_k \sum_j a_{j,k} X_k} \]
with \(a_{m,k}\) being the number of atoms of element \(m\) in species \(k\), \(\sum_j\) being a sum over all elements, and \(X_k\) being the mole fraction of species \(k\).
Parameters
[in] m Index of the element within the phase. If m is outside the valid range, an exception will be thrown.
Returns
the elemental mole fraction of element m.
Definition at line 671 of file Phase.cpp.
References Phase::checkElementIndex(), Phase::m_kk, Phase::moleFraction(), Phase::nAtoms(), and Phase::nElements().
moleFractdivMMW()
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
This array is the array of mole fractions, each divided by the mean molecular weight.
Deprecated:
To be removed after Cantera 3.0. Generally replaceable by using getMoleFractions() and meanMolecularWeight().
Definition at line 561 of file Phase.cpp.
References Phase::m_ym, and Cantera::warn_deprecated().
charge()
doublereal charge (size_t k) const inline
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
Parameters
k species index
Definition at line 649 of file Phase.h.
References Phase::m_speciesCharge.
Referenced by RedlichKisterVPSSTP::addBinaryInteraction(), HMWSoln::applyphScale(), HMWSoln::calcMolalitiesCropped(), Phase::chargeDensity(), ThermoPhase::getElectrochemPotentials(), HMWSoln::getParameters(), DebyeHuckel::getSpeciesParameters(), Cantera::hasChargedSpecies(), IonGasTransport::init(), HMWSoln::initThermo(), PDSS_HKFT::initThermo(), HMWSoln::printCoeffs(), HMWSoln::relative_molal_enthalpy(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), InterfaceRateBase::setContext(), MolalityVPSSTP::setMolalitiesByName(), vcs_VolPhase::transferElementsFM(), InterfaceKinetics::updateMu0(), Reaction::usesElectrochemistry(), and VCS_SOLVE::VCS_SOLVE().
chargeDensity()
doublereal chargeDensity () const
Charge density [C/m^3].
Definition at line 728 of file Phase.cpp.
References Phase::charge(), Cantera::Faraday, Phase::m_kk, and Phase::moleFraction().
nDim()
size_t nDim () const inline
Returns the number of spatial dimensions (1, 2, or 3)
Definition at line 657 of file Phase.h.
References Phase::m_ndim.
Referenced by Kinetics::addPhase(), Kinetics::addThermo(), Reaction::checkBalance(), InterfaceKinetics::init(), Reaction::Reaction(), Reaction::setEquation(), IdealMolalSoln::standardConcentrationUnits(), IdealSolidSolnPhase::standardConcentrationUnits(), ThermoPhase::standardConcentrationUnits(), and VCS_SOLVE::VCS_SOLVE().
setNDim()
void setNDim (size_t ndim) inline
Set the number of spatial dimensions (1, 2, or 3).
The number of spatial dimensions is used for vector involving directions.
Parameters
ndim Input number of dimensions.
Definition at line 664 of file Phase.h.
References Phase::m_ndim.
Referenced by CoverageDependentSurfPhase::CoverageDependentSurfPhase(), EdgePhase::EdgePhase(), and SurfPhase::SurfPhase().
temperature()
doublereal temperature () const inline
Temperature (K).
Returns
The temperature of the phase
Definition at line 673 of file Phase.h.
References Phase::m_temp.
Referenced by StFlow::_getInitialSoln(), InterfaceKinetics::_update_rates_T(), CoverageDependentSurfPhase::_updateCovDepThermo(), MixtureFugacityTP::_updateReferenceStateThermo(), VPStandardStateTP::_updateStandardStateThermo(), BinarySolutionTabulatedThermo::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), LatticePhase::_updateThermo(), LatticeSolidPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), SurfPhase::_updateThermo(), DebyeHuckel::A_Debye_TP(), HMWSoln::A_Debye_TP(), MultiPhase::addPhase(), HMWSoln::ADebye_J(), HMWSoln::ADebye_L(), HMWSoln::ADebye_V(), BulkKinetics::applyEquilibriumConstants_ddT(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcDensity(), PengRobinson::calculatePressureDerivatives(), MixtureFugacityTP::calculatePsat(), PengRobinson::cp_mole(), RedlichKwongMFTP::cp_mole(), HMWSoln::cv_mole(), PengRobinson::cv_mole(), RedlichKwongMFTP::cv_mole(), SingleSpeciesTP::cv_mole(), DebyeHuckel::d2A_DebyedT2_TP(), HMWSoln::d2A_DebyedT2_TP(), PengRobinson::d2aAlpha_dT2(), DebyeHuckel::dA_DebyedP_TP(), HMWSoln::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), HMWSoln::dA_DebyedT_TP(), PengRobinson::daAlpha_dT(), PengRobinson::densSpinodalGas(), RedlichKwongMFTP::densSpinodalGas(), PengRobinson::densSpinodalLiquid(), RedlichKwongMFTP::densSpinodalLiquid(), WaterSSTP::dthermalExpansionCoeffdT(), PlasmaPhase::enthalpy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MaskellSolidSolnPhase::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), WaterSSTP::getCp_R_ref(), MargulesVPSSTP::getdlnActCoeffds(), PureFluidPhase::getEnthalpy_RT_ref(), WaterSSTP::getEnthalpy_RT_ref(), PureFluidPhase::getEntropy_R_ref(), WaterSSTP::getEntropy_R_ref(), PlasmaPhase::getGibbs_ref(), PureFluidPhase::getGibbs_RT_ref(), WaterSSTP::getGibbs_RT_ref(), ThermoPhase::getParameters(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), PengRobinson::getPartialMolarEnthalpies(), PlasmaPhase::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), PengRobinson::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), WaterSSTP::getStandardChemPotentials(), PlasmaPhase::getStandardVolumes_ref(), WaterSSTP::getStandardVolumes_ref(), IdealGasConstPressureMoleReactor::getState(), IdealGasMoleReactor::getState(), IdealGasConstPressureReactor::getState(), IdealGasReactor::getState(), ThermoPhase::gibbs_mole(), PengRobinson::hresid(), RedlichKwongMFTP::hresid(), FlowReactor::initialize(), IdealGasConstPressureMoleReactor::jacobian(), IdealGasMoleReactor::jacobian(), PureFluidPhase::phaseOfMatter(), MixtureFugacityTP::phaseState(), PlasmaPhase::PlasmaPhase(), IdealGasPhase::pressure(), PengRobinson::pressure(), RedlichKwongMFTP::pressure(), RedlichKwongMFTP::pressureDerivatives(), ThermoPhase::report(), MolalityVPSSTP::report(), PureFluidPhase::report(), ThermoPhase::RT(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), MargulesVPSSTP::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::satPressure(), WaterSSTP::satPressure(), Phase::saveState(), WaterSSTP::setDensity(), ChemEquil::setInitialMoles(), MixtureFugacityTP::setPressure(), PureFluidPhase::setPressure(), VPStandardStateTP::setPressure(), WaterSSTP::setPressure(), vcs_VolPhase::setPtrThermoPhase(), PengRobinson::setSpeciesCoeffs(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), ThermoPhase::setState_TP(), SingleSpeciesTP::setState_UV(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), IdealGasPhase::soundSpeed(), RedlichKwongMFTP::sresid(), FlowReactor::syncState(), HighPressureGasTransport::thermalConductivity(), WaterTransport::thermalConductivity(), IdealGasPhase::thermalExpansionCoeff(), InterfaceData::update(), ArrheniusData::update(), ChebyshevData::update(), FalloffData::update(), PlogData::update(), TwoTempPlasmaData::update(), ChemEquil::update(), MixTransport::update_T(), MultiTransport::update_T(), PengRobinson::updateMixingExpressions(), RedlichKwongMFTP::updateMixingExpressions(), VPStandardStateTP::updateStandardStateThermo(), MoleReactor::updateState(), Reactor::updateState(), MultiTransport::updateThermal_T(), IdealGasPhase::updateThermo(), PlasmaPhase::updateThermo(), IonFlow::updateTransport(), DustyGasTransport::updateTransport_T(), WaterSSTP::vaporFraction(), HighPressureGasTransport::viscosity(), and WaterTransport::viscosity().
electronTemperature()
virtual double electronTemperature () const inline virtual
Electron Temperature (K)
Returns
The electron temperature of the phase
Reimplemented in PlasmaPhase.
Definition at line 679 of file Phase.h.
References Phase::m_temp.
Referenced by TwoTempPlasmaData::update().
pressure()
virtual double pressure () const inline virtual
Return the thermodynamic pressure (Pa).
This method must be overloaded in derived classes. Within Cantera, the independent variable is either density or pressure. If the state is defined by temperature, density, and mass fractions, this method should use these values to implement the mechanical equation of state \(P(T, \rho, Y_1, \dots, Y_K) \). Alternatively, it returns a stored value.
Reimplemented in IdealGasPhase, IdealSolidSolnPhase, LatticePhase, LatticeSolidPhase, MaskellSolidSolnPhase, MetalPhase, PengRobinson, PureFluidPhase, RedlichKwongMFTP, StoichSubstance, SurfPhase, VPStandardStateTP, and WaterSSTP.
Definition at line 691 of file Phase.h.
References Phase::type().
Referenced by MultiPhase::addPhase(), BulkKinetics::applyEquilibriumConstants_ddT(), OutletRes1D::asArray(), IonGasTransport::electricalConductivity(), MixtureFugacityTP::entropy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MoleReactor::eval(), Reactor::eval(), StFlow::fromArray(), MixtureFugacityTP::getActivityConcentrations(), HighPressureGasTransport::getBinaryDiffCoeffs(), MixtureFugacityTP::getEntropy_R(), MixtureFugacityTP::getGibbs_RT(), MultiTransport::getMassFluxes(), IonGasTransport::getMixDiffCoeffs(), IonGasTransport::getMobilities(), HighPressureGasTransport::getMultiDiffCoeffs(), ThermoPhase::getParameters(), MixtureFugacityTP::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), FlowReactor::initialize(), ThermoPhase::intEnergy_mole(), ThermoPhase::report(), Phase::saveState(), ThermoPhase::setEquivalenceRatio(), ChemEquil::setInitialMoles(), ThermoPhase::setMixtureFraction(), ReactorBase::setThermoMgr(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), StFlow::StFlow(), ReactorBase::syncState(), FlowReactor::syncState(), ChebyshevData::update(), PlogData::update(), Reactor::updateConnected(), HighPressureGasTransport::viscosity(), and MixtureFugacityTP::z().
density()
virtual double density () const inline virtual
Density (kg/m^3).
Returns
The density of the phase
Definition at line 698 of file Phase.h.
References Phase::m_dens.
Referenced by StFlow::_getInitialSoln(), MixtureFugacityTP::calculatePsat(), SingleSpeciesTP::cv_mole(), WaterSSTP::dthermalExpansionCoeffdT(), ChemEquil::equilibrate(), FlowReactor::evalDae(), WaterSSTP::getCp_R_ref(), PureFluidPhase::getEnthalpy_RT_ref(), WaterSSTP::getEnthalpy_RT_ref(), PureFluidPhase::getEntropy_R_ref(), WaterSSTP::getEntropy_R_ref(), PureFluidPhase::getGibbs_RT_ref(), WaterSSTP::getGibbs_RT_ref(), MultiTransport::getMassFluxes(), UnityLewisTransport::getMixDiffCoeffs(), UnityLewisTransport::getMixDiffCoeffsMass(), MetalPhase::getParameters(), ThermoPhase::getParameters(), SingleSpeciesTP::getPartialMolarVolumes(), MultiTransport::getSpeciesFluxes(), StoichSubstance::getSpeciesParameters(), SingleSpeciesTP::getStandardVolumes(), WaterSSTP::getStandardVolumes_ref(), ConstPressureMoleReactor::getState(), IdealGasConstPressureMoleReactor::getState(), IdealGasMoleReactor::getState(), MoleReactor::getState(), Reactor::getState(), ConstPressureReactor::getState(), IdealGasConstPressureReactor::getState(), IdealGasReactor::getState(), RedlichKwongMFTP::hresid(), FlowReactor::initialize(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), ThermoPhase::report(), MolalityVPSSTP::report(), PureFluidPhase::report(), WaterSSTP::satPressure(), Phase::saveState(), FlowReactor::setMassFlowRate(), MixtureFugacityTP::setPressure(), WaterSSTP::setPressure(), ThermoPhase::setState_TP(), WaterSSTP::setTemperature(), RedlichKwongMFTP::sresid(), Reactor::syncState(), FlowReactor::syncState(), WaterTransport::thermalConductivity(), BlowersMaselData::update(), ChemEquil::update(), ConstPressureMoleReactor::updateState(), IdealGasConstPressureMoleReactor::updateState(), ConstPressureReactor::updateState(), IdealGasConstPressureReactor::updateState(), StFlow::updateThermo(), StFlow::updateTransport(), WaterSSTP::vaporFraction(), WaterTransport::viscosity(), and MixtureFugacityTP::z().
molarDensity()
double molarDensity () const virtual
Molar density (kmol/m^3).
Returns
The molar density of the phase
Definition at line 689 of file Phase.cpp.
References Phase::density(), and Phase::meanMolecularWeight().
Referenced by solveSP::calc_t(), BulkKinetics::calculateCompositionDerivatives(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), StoichSubstance::getEnthalpy_RT(), StoichSubstance::getIntEnergy_RT(), StoichSubstance::getIntEnergy_RT_ref(), IdealGasPhase::getPartialMolarVolumes(), PureFluidPhase::getPartialMolarVolumes(), MixTransport::getSpeciesFluxes(), IdealGasPhase::getStandardVolumes(), IdealSolidSolnPhase::gibbs_mole(), Phase::molarVolume(), IdealGasPhase::pressure(), BulkKinetics::process_ddC(), and FalloffData::update().
molarVolume()
double molarVolume () const virtual
Molar volume (m^3/kmol).
Returns
The molar volume of the phase
Reimplemented in SurfPhase.
Definition at line 702 of file Phase.cpp.
References Phase::molarDensity().
Referenced by PengRobinson::calculatePressureDerivatives(), PengRobinson::cp_mole(), RedlichKwongMFTP::cp_mole(), HMWSoln::cv_mole(), RedlichKwongMFTP::cv_mole(), PengRobinson::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), PengRobinson::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), PengRobinson::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), PengRobinson::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), PengRobinson::hresid(), MetalPhase::intEnergy_mole(), ThermoPhase::intEnergy_mole(), PengRobinson::isothermalCompressibility(), RedlichKwongMFTP::isothermalCompressibility(), IdealGasConstPressureMoleReactor::jacobian(), PengRobinson::pressure(), RedlichKwongMFTP::pressureDerivatives(), PengRobinson::soundSpeed(), RedlichKwongMFTP::soundSpeed(), PengRobinson::sresid(), HighPressureGasTransport::thermalConductivity(), PengRobinson::thermalExpansionCoeff(), and RedlichKwongMFTP::thermalExpansionCoeff().
setDensity()
void setDensity (const double density_) virtual
Set the internally stored density (kg/m^3) of the phase.
Note the density of a phase is an independent variable.
Parameters
[in] density_ density (kg/m^3).
Reimplemented in PureFluidPhase, and WaterSSTP.
Definition at line 707 of file Phase.cpp.
References Phase::assertCompressible(), and Phase::m_dens.
Referenced by WaterSSTP::initThermo(), Phase::restoreState(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), PureFluidPhase::setDensity(), WaterSSTP::setDensity(), IdealGasPhase::setPressure(), MixtureFugacityTP::setPressure(), PureFluidPhase::setPressure(), IdealGasPhase::setState_DP(), ThermoPhase::setState_HPorUV(), PureFluidPhase::setState_Psat(), Phase::setState_RX(), Phase::setState_RY(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), Phase::setState_TD(), PureFluidPhase::setState_Tsat(), SingleSpeciesTP::setState_UV(), MoleReactor::updateState(), and Reactor::updateState().
setMolarDensity()
void setMolarDensity (const double molarDensity) virtual
Set the internally stored molar density (kmol/m^3) of the phase.
Parameters
[in] molarDensity Input molar density (kmol/m^3).
Deprecated:
Unused. To be removed after Cantera 3.0
Reimplemented in SurfPhase.
Definition at line 694 of file Phase.cpp.
References Phase::assertCompressible(), Phase::m_dens, Phase::meanMolecularWeight(), and Cantera::warn_deprecated().
Referenced by Phase::setState_TNX().
setPressure()
virtual void setPressure (double p) inline virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
This method must be reimplemented in derived classes, where it may involve the solution of a nonlinear equation. Within Cantera, the independent variable is either density or pressure. Therefore, this function may either solve for the density that will yield the desired input pressure or set an independent variable. The temperature and composition are held constant during this process.
Parameters
p input Pressure (Pa)
Reimplemented in IdealGasPhase, IdealSolidSolnPhase, IdealSolnGasVPSS, LatticePhase, LatticeSolidPhase, MaskellSolidSolnPhase, MixtureFugacityTP, PureFluidPhase, StoichSubstance, SurfPhase, VPStandardStateTP, WaterSSTP, and MetalPhase.
Definition at line 732 of file Phase.h.
References Phase::type().
Referenced by ChemEquil::calcEmoles(), ChemEquil::estimateEP_Brinkley(), Phase::restoreState(), ThermoPhase::setEquivalenceRatio(), StFlow::setGas(), StFlow::setGasAtMidpoint(), ThermoPhase::setMixtureFraction(), ThermoPhase::setState_conditional_TP(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_PX(), ThermoPhase::setState_PY(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), ThermoPhase::setState_TP(), ConstPressureMoleReactor::updateState(), and ConstPressureReactor::updateState().
setTemperature()
virtual void setTemperature (double temp) inline virtual
Set the internally stored temperature of the phase (K).
Parameters
temp Temperature in Kelvin
Reimplemented in PureFluidPhase, MixtureFugacityTP, VPStandardStateTP, and WaterSSTP.
Definition at line 739 of file Phase.h.
References Phase::m_temp.
Referenced by ChemEquil::equilibrate(), ReactingSurf1D::eval(), WaterSSTP::initThermo(), Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), ThermoPhase::setState_conditional_TP(), IdealGasPhase::setState_DP(), PureFluidPhase::setState_Psat(), SingleSpeciesTP::setState_SV(), Phase::setState_TD(), Phase::setState_TNX(), ThermoPhase::setState_TP(), VPStandardStateTP::setState_TP(), PureFluidPhase::setState_Tsat(), Phase::setState_TX(), Phase::setState_TY(), SingleSpeciesTP::setState_UV(), PureFluidPhase::setTemperature(), MixtureFugacityTP::setTemperature(), WaterSSTP::setTemperature(), ChemEquil::setToEquilState(), and ReactorSurface::syncState().
setElectronTemperature()
virtual void setElectronTemperature (double etemp) inline virtual
Set the internally stored electron temperature of the phase (K).
Parameters
etemp Electron temperature in Kelvin
Reimplemented in PlasmaPhase.
Definition at line 750 of file Phase.h.
References Phase::type().
mean_X() [1/2]
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
\[ \sum_k X_k Q_k. \]
Q should contain pure-species molar property values.
Parameters
[in] Q Array of length m_kk that is to be averaged.
Returns
mole-fraction-weighted mean of Q
Definition at line 737 of file Phase.cpp.
References Phase::m_mmw, and Phase::m_ym.
Referenced by DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IdealMolalSoln::calcDensity(), IdealSolidSolnPhase::calcDensity(), IdealSolnGasVPSS::calcDensity(), CoverageDependentSurfPhase::cp_mole(), DebyeHuckel::cp_mole(), HMWSoln::cp_mole(), IdealGasPhase::cp_mole(), IdealMolalSoln::cp_mole(), IdealSolidSolnPhase::cp_mole(), IdealSolnGasVPSS::cp_mole(), IonsFromNeutralVPSSTP::cp_mole(), LatticePhase::cp_mole(), PengRobinson::cp_mole(), RedlichKwongMFTP::cp_mole(), SurfPhase::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), RedlichKwongMFTP::cv_mole(), CoverageDependentSurfPhase::enthalpy_mole(), DebyeHuckel::enthalpy_mole(), HMWSoln::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), IdealMolalSoln::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), IdealSolnGasVPSS::enthalpy_mole(), IonsFromNeutralVPSSTP::enthalpy_mole(), LatticePhase::enthalpy_mole(), MaskellSolidSolnPhase::enthalpy_mole(), MixtureFugacityTP::enthalpy_mole(), SurfPhase::enthalpy_mole(), DebyeHuckel::entropy_mole(), HMWSoln::entropy_mole(), IdealGasPhase::entropy_mole(), IdealMolalSoln::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), IdealSolnGasVPSS::entropy_mole(), IonsFromNeutralVPSSTP::entropy_mole(), LatticePhase::entropy_mole(), MaskellSolidSolnPhase::entropy_mole(), MixtureFugacityTP::entropy_mole(), DebyeHuckel::gibbs_mole(), HMWSoln::gibbs_mole(), IdealMolalSoln::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), IonsFromNeutralVPSSTP::gibbs_mole(), IdealMolalSoln::intEnergy_mole(), and HMWSoln::relative_enthalpy().
mean_X() [2/2]
doublereal mean_X (const vector_fp & Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
\[ \sum_k X_k Q_k. \]
Q should contain pure-species molar property values.
Parameters
[in] Q Array of length m_kk that is to be averaged.
Returns
mole-fraction-weighted mean of Q
Definition at line 742 of file Phase.cpp.
References Phase::m_mmw, and Phase::m_ym.
meanMolecularWeight()
doublereal meanMolecularWeight () const inline
The mean molecular weight. Units: (kg/kmol)
Definition at line 771 of file Phase.h.
References Phase::m_mmw.
Referenced by BinarySolutionTabulatedThermo::calcDensity(), DebyeHuckel::calcDensity(), GibbsExcessVPSSTP::calcDensity(), HMWSoln::calcDensity(), IdealMolalSoln::calcDensity(), IdealSolidSolnPhase::calcDensity(), IdealSolnGasVPSS::calcDensity(), LatticePhase::calcDensity(), MaskellSolidSolnPhase::calcDensity(), MixtureFugacityTP::calculatePsat(), SurfPhase::compositionChanged(), ThermoPhase::cp_mass(), MixtureFugacityTP::critDensity(), ThermoPhase::cv_mass(), PengRobinson::densityCalc(), RedlichKwongMFTP::densityCalc(), MixtureFugacityTP::densityCalc(), PengRobinson::densSpinodalGas(), RedlichKwongMFTP::densSpinodalGas(), PengRobinson::densSpinodalLiquid(), RedlichKwongMFTP::densSpinodalLiquid(), ThermoPhase::enthalpy_mass(), ThermoPhase::entropy_mass(), IonGasTransport::getMixDiffCoeffs(), HighPressureGasTransport::getMultiDiffCoeffs(), MultiTransport::getMultiDiffCoeffs(), StoichSubstance::getSpeciesParameters(), WaterSSTP::getStandardVolumes_ref(), FlowReactor::getStateDae(), ThermoPhase::gibbs_mass(), RedlichKwongMFTP::hresid(), StoichSubstance::initThermo(), ThermoPhase::intEnergy_mass(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), ThermoPhase::report(), MolalityVPSSTP::report(), PureFluidPhase::report(), Phase::setMolarDensity(), IdealGasPhase::setPressure(), SurfPhase::setSiteDensity(), IdealGasPhase::setState_DP(), IdealGasPhase::soundSpeed(), PengRobinson::soundSpeed(), RedlichKwongMFTP::soundSpeed(), RedlichKwongMFTP::sresid(), StFlow::updateThermo(), StFlow::updateTransport(), HighPressureGasTransport::viscosity(), and MixtureFugacityTP::z().
sum_xlogx()
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
Returns
The indicated sum. Dimensionless.
Definition at line 747 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_ym, and Cantera::SmallNumber.
Referenced by IdealGasPhase::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), IdealSolnGasVPSS::entropy_mole(), LatticePhase::entropy_mole(), MixtureFugacityTP::entropy_mole(), and IdealSolidSolnPhase::gibbs_mole().
addElement()
size_t addElement (const std::string & symbol, doublereal weight = -12345.0, int atomicNumber = 0, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS)
Add an element.
Parameters
symbol Atomic symbol std::string.
weight Atomic mass in amu.
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which is interpreted as an unknown, and if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, that is, an element.
Returns
index of the element added
Definition at line 756 of file Phase.cpp.
References AnyMap::convert(), CT_ELEM_TYPE_ELECTRONCHARGE, ENTROPY298_UNKNOWN, AnyMap::fromYamlFile(), Cantera::getElementWeight(), Phase::m_atomicNumbers, Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_entropy298, Phase::m_kk, Phase::m_mm, and Phase::m_speciesComp.
Referenced by LatticeSolidPhase::addLattice(), Phase::addSpecies(), and LatticeSolidPhase::setLatticeStoichiometry().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Reimplemented in BinarySolutionTabulatedThermo, CoverageDependentSurfPhase, DebyeHuckel, GibbsExcessVPSSTP, IdealGasPhase, IdealMolalSoln, IdealSolidSolnPhase, IdealSolnGasVPSS, IonsFromNeutralVPSSTP, LatticePhase, LatticeSolidPhase, MixtureFugacityTP, MolalityVPSSTP, PengRobinson, PlasmaPhase, RedlichKwongMFTP, SingleSpeciesTP, SurfPhase, ThermoPhase, VPStandardStateTP, and VPStandardStateTP.
Definition at line 823 of file Phase.cpp.
References Phase::addElement(), Phase::atomicWeights(), CT_ELEM_TYPE_ELECTRONCHARGE, Phase::elementIndex(), Phase::invalidateCache(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_name, Phase::m_rmolwts, Phase::m_speciesCharge, Phase::m_speciesComp, Phase::m_speciesIndices, Phase::m_speciesLower, Phase::m_speciesNames, Phase::m_undefinedElementBehavior, Phase::m_y, Phase::m_ym, Phase::nElements(), Cantera::npos, Cantera::Tiny, and Cantera::toLowerCopy().
Referenced by ThermoPhase::addSpecies(), and VPStandardStateTP::addSpecies().
modifySpecies()
void modifySpecies (size_t k, shared_ptr< Species > spec) virtual
Modify the thermodynamic data associated with a species.
The species name, elemental composition, and type of thermo parameterization must be unchanged. If there are Kinetics objects that depend on this phase, Kinetics::invalidateCache() should be called on those objects after calling this function.
Reimplemented in ThermoPhase.
Definition at line 927 of file Phase.cpp.
References Phase::invalidateCache(), and Phase::speciesName().
Referenced by ThermoPhase::modifySpecies().
addSpeciesAlias()
void addSpeciesAlias (const std::string & name, const std::string & alias)
Add a species alias (that is, a user-defined alternative species name).
Aliases are case-sensitive.
Parameters
name original species name
alias alternate name
Definition at line 944 of file Phase.cpp.
References Phase::m_speciesIndices, Phase::name(), Cantera::npos, and Phase::speciesIndex().
findIsomers() [1/2]
vector< std::string > findIsomers (const compositionMap & compMap) const virtual
Return a vector with isomers names matching a given composition map.
Parameters
compMap compositionMap of the species.
Returns
A vector of species names for matching species.
Definition at line 960 of file Phase.cpp.
References Phase::name(), and Phase::species().
Referenced by Phase::findIsomers().
findIsomers() [2/2]
vector< std::string > findIsomers (const std::string & comp) const virtual
Return a vector with isomers names matching a given composition string.
Parameters
comp String containing a composition map
Returns
A vector of species names for matching species.
Definition at line 973 of file Phase.cpp.
References Phase::findIsomers(), and Cantera::parseCompString().
species() [1/2]
shared_ptr< Species > species (const std::string & name) const
Return the Species object for the named species.
Changes to this object do not affect the ThermoPhase object until the modifySpecies function is called.
Definition at line 978 of file Phase.cpp.
References Phase::name(), Cantera::npos, Phase::speciesIndex(), and Phase::speciesName().
Referenced by Phase::findIsomers(), IdealSolidSolnPhase::getSpeciesParameters(), LatticePhase::getSpeciesParameters(), PengRobinson::getSpeciesParameters(), StoichSubstance::getSpeciesParameters(), DebyeHuckel::initThermo(), HMWSoln::initThermo(), MargulesVPSSTP::initThermo(), PengRobinson::initThermo(), RedlichKisterVPSSTP::initThermo(), RedlichKwongMFTP::initThermo(), StoichSubstance::initThermo(), VPStandardStateTP::installPDSS(), LatticePhase::setSiteDensity(), PengRobinson::setSpeciesCoeffs(), RedlichKwongMFTP::setSpeciesCoeffs(), and Cantera::setupPhase().
species() [2/2]
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
Changes to this object do not affect the ThermoPhase object until the modifySpecies function is called.
Definition at line 989 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_speciesNames.
ignoreUndefinedElements()
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
Definition at line 995 of file Phase.cpp.
References Phase::m_undefinedElementBehavior.
Referenced by Cantera::setupPhase().
addUndefinedElements()
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
This is the default behavior.
Definition at line 999 of file Phase.cpp.
References Phase::m_undefinedElementBehavior.
Referenced by Cantera::setupPhase().
throwUndefinedElements()
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Definition at line 1003 of file Phase.cpp.
References Phase::m_undefinedElementBehavior.
Referenced by Cantera::setupPhase().
ready()
bool ready () const virtual
Returns a bool indicating whether the object is ready for use.
Returns
true if the object is ready for calculation, false otherwise.
Reimplemented in BinarySolutionTabulatedThermo.
Definition at line 1007 of file Phase.cpp.
References Phase::m_kk.
Referenced by IdealSolidSolnPhase::addSpecies().
stateMFNumber()
int stateMFNumber () const inline
Return the State Mole Fraction Number.
Definition at line 877 of file Phase.h.
References Phase::m_stateNum.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), BinarySolutionTabulatedThermo::_updateThermo(), HMWSoln::calcDensity(), MaskellSolidSolnPhase::getActivityCoefficients(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), InterfaceData::update(), and FalloffData::update().
invalidateCache()
void invalidateCache () virtual
Invalidate any cached values which are normally updated only when a change in state is detected.
Reimplemented in ThermoPhase, and VPStandardStateTP.
Definition at line 1012 of file Phase.cpp.
References ValueCache::clear(), Phase::m_cache, and Phase::m_stateNum.
Referenced by Phase::addSpecies(), ThermoPhase::invalidateCache(), and Phase::modifySpecies().
caseSensitiveSpecies()
bool caseSensitiveSpecies () const inline
Returns true if case sensitive species names are enforced.
Definition at line 886 of file Phase.h.
References Phase::m_caseSensitiveSpecies.
setCaseSensitiveSpecies()
void setCaseSensitiveSpecies (bool cflag = true) inline
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
Definition at line 892 of file Phase.h.
References Phase::m_caseSensitiveSpecies.
getCompositionFromMap()
vector_fp getCompositionFromMap (const compositionMap & comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
Parameters
[in] comp compositionMap containing the mixture composition
Returns
vector with length m_kk
Definition at line 1031 of file Phase.cpp.
References Phase::m_kk, Phase::name(), Cantera::npos, and Phase::speciesIndex().
Referenced by ThermoPhase::equivalenceRatio(), ThermoPhase::mixtureFraction(), ThermoPhase::setEquivalenceRatio(), Phase::setMassFractionsByName(), ThermoPhase::setMixtureFraction(), Phase::setMoleFractionsByName(), and ThermoPhase::stoichAirFuelRatio().
massFractionsToMoleFractions()
void massFractionsToMoleFractions (const double * Y, double * X) const
Converts a mixture composition from mole fractions to mass fractions.
Parameters
[in] Y mixture composition in mass fractions (length m_kk)
[out] X mixture composition in mole fractions (length m_kk)
Definition at line 1045 of file Phase.cpp.
References Phase::m_kk, and Phase::m_molwts.
moleFractionsToMassFractions()
void moleFractionsToMassFractions (const double * X, double * Y) const
Converts a mixture composition from mass fractions to mole fractions.
Parameters
[in] X mixture composition in mole fractions (length m_kk)
[out] Y mixture composition in mass fractions (length m_kk)
Definition at line 1060 of file Phase.cpp.
References Cantera::dot(), Phase::m_kk, and Phase::m_molwts.
Referenced by ThermoPhase::equivalenceRatio(), ThermoPhase::mixtureFraction(), ThermoPhase::setEquivalenceRatio(), ThermoPhase::setMixtureFraction(), and ThermoPhase::stoichAirFuelRatio().
assertCompressible()
void assertCompressible (const std::string & setter) const inline protected
Ensure that phase is compressible.
An error is raised if the state is incompressible
Parameters
setter name of setter (used for exception handling)
Definition at line 918 of file Phase.h.
References Phase::isCompressible(), Phase::name(), and Phase::type().
Referenced by Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), Phase::setDensity(), Phase::setMolarDensity(), ThermoPhase::setState_SV(), and ThermoPhase::setState_UV().
assignDensity()
void assignDensity (const double density_) protected
Set the internally stored constant density (kg/m^3) of the phase.
Used for incompressible phases where the density is not an independent variable, that is, density does not affect pressure in state calculations.
Parameters
[in] density_ density (kg/m^3).
Definition at line 718 of file Phase.cpp.
References Phase::m_dens.
Referenced by BinarySolutionTabulatedThermo::calcDensity(), DebyeHuckel::calcDensity(), GibbsExcessVPSSTP::calcDensity(), HMWSoln::calcDensity(), IdealMolalSoln::calcDensity(), IdealSolidSolnPhase::calcDensity(), IdealSolnGasVPSS::calcDensity(), IonsFromNeutralVPSSTP::calcDensity(), LatticePhase::calcDensity(), LatticeSolidPhase::calcDensity(), MaskellSolidSolnPhase::calcDensity(), SurfPhase::compositionChanged(), MetalPhase::initThermo(), StoichSubstance::initThermo(), and SurfPhase::setSiteDensity().
setMolecularWeight()
void setMolecularWeight (const int k, const double mw) protected
Set the molecular weight of a single species to a given value.
Used by phases where the equation of state is defined for a specific value of the molecular weight which may not exactly correspond to the value computed from the chemical formula.
Parameters
k id of the species
mw Molecular Weight (kg kmol-1)
Definition at line 1017 of file Phase.cpp.
References Phase::m_mmw, Phase::m_molwts, Phase::m_rmolwts, Phase::m_y, and Phase::m_ym.
Referenced by PureFluidPhase::initThermo(), and WaterSSTP::initThermo().
compositionChanged()
void compositionChanged () protected virtual
Apply changes to the state which are needed after the composition changes.
This function is called after any call to setMassFractions(), setMoleFractions(), or similar. For phases which need to execute a callback after any change to the composition, it should be done by overriding this function rather than overriding all of the composition- setting functions. Derived class implementations of compositionChanged() should call the parent class method as well.
Reimplemented in BinarySolutionTabulatedThermo, GibbsExcessVPSSTP, IdealSolidSolnPhase, IonsFromNeutralVPSSTP, LatticePhase, MixtureFugacityTP, and SurfPhase.
Definition at line 1027 of file Phase.cpp.
References Phase::m_stateNum.
Referenced by GibbsExcessVPSSTP::compositionChanged(), IdealSolidSolnPhase::compositionChanged(), LatticePhase::compositionChanged(), MixtureFugacityTP::compositionChanged(), SurfPhase::compositionChanged(), Phase::restoreState(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), and Phase::setMolesNoTruncate().
findSpeciesLower()
size_t findSpeciesLower (const std::string & nameStr) const private
Find lowercase species name in m_speciesIndices when case sensitive species names are not enforced and a user specifies a non-canonical species name.
Raise exception if lowercase name is not unique.
Definition at line 119 of file Phase.cpp.
References Phase::m_speciesLower, Phase::name(), Cantera::npos, and Cantera::toLowerCopy().
Referenced by Phase::speciesIndex().
Member Data Documentation
m_cache
ValueCache m_cache mutable protected
Cached for saved calculations within each ThermoPhase.
For more information on how to use this, see examples within the source code and documentation for this within ValueCache class itself.
Definition at line 938 of file Phase.h.
Referenced by BinarySolutionTabulatedThermo::_updateThermo(), HMWSoln::A_Debye_TP(), HMWSoln::calcDensity(), HMWSoln::dA_DebyedP_TP(), MaskellSolidSolnPhase::getActivityCoefficients(), Phase::invalidateCache(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), IdealGasPhase::updateThermo(), and PlasmaPhase::updateThermo().
m_kk
size_t m_kk = 0 protected
Number of species in the phase.
Definition at line 958 of file Phase.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), CoverageDependentSurfPhase::_updateCovDepThermo(), MixtureFugacityTP::_updateReferenceStateThermo(), VPStandardStateTP::_updateStandardStateThermo(), BinarySolutionTabulatedThermo::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), LatticePhase::_updateThermo(), SurfPhase::_updateThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), Phase::addElement(), BinarySolutionTabulatedThermo::addSpecies(), GibbsExcessVPSSTP::addSpecies(), IdealGasPhase::addSpecies(), IdealSolidSolnPhase::addSpecies(), IonsFromNeutralVPSSTP::addSpecies(), LatticePhase::addSpecies(), MixtureFugacityTP::addSpecies(), MolalityVPSSTP::addSpecies(), PengRobinson::addSpecies(), Phase::addSpecies(), PlasmaPhase::addSpecies(), RedlichKwongMFTP::addSpecies(), SingleSpeciesTP::addSpecies(), SurfPhase::addSpecies(), ThermoPhase::addSpecies(), VPStandardStateTP::addSpecies(), HMWSoln::applyphScale(), GibbsExcessVPSSTP::calcDensity(), MaskellSolidSolnPhase::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), PengRobinson::calculateAB(), RedlichKwongMFTP::calculateAB(), Phase::chargeDensity(), GibbsExcessVPSSTP::checkMFSum(), Phase::checkSpeciesArraySize(), Phase::checkSpeciesIndex(), HMWSoln::counterIJ_setup(), RedlichKisterVPSSTP::cp_mole(), PengRobinson::d2aAlpha_dT2(), PengRobinson::daAlpha_dT(), Phase::elementalMassFraction(), Phase::elementalMoleFraction(), RedlichKisterVPSSTP::enthalpy_mole(), CoverageDependentSurfPhase::entropy_mole(), RedlichKisterVPSSTP::entropy_mole(), SurfPhase::entropy_mole(), ThermoPhase::equivalenceRatio(), MolalityVPSSTP::findCLMIndex(), DebyeHuckel::getActivities(), GibbsExcessVPSSTP::getActivities(), HMWSoln::getActivities(), IdealMolalSoln::getActivities(), PengRobinson::getActivityCoefficients(), GibbsExcessVPSSTP::getActivityCoefficients(), IdealGasPhase::getActivityCoefficients(), IdealSolidSolnPhase::getActivityCoefficients(), IdealSolnGasVPSS::getActivityCoefficients(), IonsFromNeutralVPSSTP::getActivityCoefficients(), LatticePhase::getActivityCoefficients(), LatticeSolidPhase::getActivityCoefficients(), MolalityVPSSTP::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), ThermoPhase::getActivityCoefficients(), MixtureFugacityTP::getActivityConcentrations(), DebyeHuckel::getActivityConcentrations(), HMWSoln::getActivityConcentrations(), IdealMolalSoln::getActivityConcentrations(), IdealSolidSolnPhase::getActivityConcentrations(), IdealSolnGasVPSS::getActivityConcentrations(), MaskellSolidSolnPhase::getActivityConcentrations(), CoverageDependentSurfPhase::getChemPotentials(), PengRobinson::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), LatticePhase::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), SurfPhase::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), MaskellSolidSolnPhase::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), VPStandardStateTP::getChemPotentials_RT(), Phase::getCompositionFromMap(), SurfPhase::getCoverages(), IdealSolidSolnPhase::getCp_R_ref(), MargulesVPSSTP::getd2lnActCoeffdT2(), RedlichKisterVPSSTP::getd2lnActCoeffdT2(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), MargulesVPSSTP::getdlnActCoeffdlnN(), RedlichKisterVPSSTP::getdlnActCoeffdlnN(), ThermoPhase::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), MargulesVPSSTP::getdlnActCoeffdlnN_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), MargulesVPSSTP::getdlnActCoeffdlnX_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffdT(), RedlichKisterVPSSTP::getdlnActCoeffdT(), ThermoPhase::getElectrochemPotentials(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT_ref(), CoverageDependentSurfPhase::getEntropy_R(), PlasmaPhase::getEntropy_R(), IdealGasPhase::getEntropy_R(), MixtureFugacityTP::getEntropy_R(), IdealSolidSolnPhase::getEntropy_R_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), VPStandardStateTP::getGibbs_ref(), WaterSSTP::getGibbs_ref(), CoverageDependentSurfPhase::getGibbs_RT(), PlasmaPhase::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), MixtureFugacityTP::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT_ref(), LatticePhase::getGibbs_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT(), MixtureFugacityTP::getIntEnergy_RT(), VPStandardStateTP::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), MargulesVPSSTP::getLnActivityCoefficients(), RedlichKisterVPSSTP::getLnActivityCoefficients(), ThermoPhase::getLnActivityCoefficients(), Phase::getMassFractionsByName(), MolalityVPSSTP::getMolalities(), DebyeHuckel::getMolalityActivityCoefficients(), IdealMolalSoln::getMolalityActivityCoefficients(), Phase::getMoleFractionsByName(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), DebyeHuckel::getParameters(), HMWSoln::getParameters(), ThermoPhase::getParameters(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), IdealSolidSolnPhase::getPartialMolarCp(), IdealSolnGasVPSS::getPartialMolarCp(), LatticePhase::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), SurfPhase::getPartialMolarCp(), PengRobinson::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), IdealSolidSolnPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), SurfPhase::getPartialMolarEnthalpies(), CoverageDependentSurfPhase::getPartialMolarEntropies(), PengRobinson::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), SurfPhase::getPartialMolarEntropies(), PengRobinson::getPartialMolarIntEnergies(), PlasmaPhase::getPartialMolarIntEnergies(), IdealMolalSoln::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), PengRobinson::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), CoverageDependentSurfPhase::getPureGibbs(), IdealGasPhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), LatticePhase::getPureGibbs(), MaskellSolidSolnPhase::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), VPStandardStateTP::getPureGibbs(), RedlichKwongMFTP::getSpeciesParameters(), CoverageDependentSurfPhase::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), VPStandardStateTP::getStandardChemPotentials(), IdealGasPhase::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes(), SurfPhase::getStandardVolumes(), IdealGasPhase::getStandardVolumes_ref(), MixtureFugacityTP::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), HMWSoln::initLengths(), MargulesVPSSTP::initLengths(), RedlichKisterVPSSTP::initLengths(), HMWSoln::initThermo(), IonsFromNeutralVPSSTP::initThermo(), RedlichKwongMFTP::initThermo(), StoichSubstance::initThermo(), ThermoPhase::initThermo(), VPStandardStateTP::initThermo(), Phase::massFractionsToMoleFractions(), ThermoPhase::mixtureFraction(), Phase::moleFractionsToMassFractions(), Phase::nSpecies(), ThermoPhase::o2Present(), ThermoPhase::o2Required(), MolalityVPSSTP::osmoticCoefficient(), HMWSoln::printCoeffs(), Phase::ready(), HMWSoln::relative_enthalpy(), HMWSoln::relative_molal_enthalpy(), ThermoPhase::report(), MolalityVPSSTP::report(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), RedlichKwongMFTP::setBinaryCoeffs(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), SurfPhase::setCoverages(), SurfPhase::setCoveragesByName(), SurfPhase::setCoveragesNoNorm(), DebyeHuckel::setDebyeHuckelModel(), DebyeHuckel::setDefaultIonicRadius(), ThermoPhase::setEquivalenceRatio(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), ThermoPhase::setMixtureFraction(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), Phase::setMolesNoTruncate(), LatticePhase::setSiteDensity(), PengRobinson::setSpeciesCoeffs(), RedlichKwongMFTP::setSpeciesCoeffs(), IdealSolnGasVPSS::setToEquilState(), IdealGasPhase::setToEquilState(), IdealSolidSolnPhase::setToEquilState(), IdealSolidSolnPhase::standardConcentration(), ThermoPhase::stoichAirFuelRatio(), Phase::sum_xlogx(), PengRobinson::updateMixingExpressions(), RedlichKwongMFTP::updateMixingExpressions(), and IdealGasPhase::updateThermo().
m_ndim
size_t m_ndim = 3 protected
Dimensionality of the phase.
Volumetric phases have dimensionality 3 and surface phases have dimensionality 2.
Definition at line 962 of file Phase.h.
Referenced by SurfPhase::getParameters(), SurfPhase::initThermo(), Phase::nDim(), and Phase::setNDim().
m_speciesComp
vector_fp m_speciesComp protected
Atomic composition of the species.
The number of atoms of element i in species k is equal to m_speciesComp[k * m_mm + i] The length of this vector is equal to m_kk * m_mm
Definition at line 967 of file Phase.h.
Referenced by Phase::addElement(), Phase::addSpecies(), Phase::getAtoms(), Phase::nAtoms(), and LatticeSolidPhase::setLatticeStoichiometry().
m_speciesCharge
vector_fp m_speciesCharge protected
Vector of species charges. length m_kk.
Definition at line 969 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::charge(), Phase::getCharges(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
m_species
std::map<std::string, shared_ptr<Species> > m_species protected
Definition at line 971 of file Phase.h.
m_undefinedElementBehavior
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add protected
Flag determining behavior when adding species with an undefined element.
Definition at line 974 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::addUndefinedElements(), Phase::ignoreUndefinedElements(), and Phase::throwUndefinedElements().
m_caseSensitiveSpecies
bool m_caseSensitiveSpecies = false protected
Flag determining whether case sensitive species names are enforced.
Definition at line 977 of file Phase.h.
Referenced by Phase::caseSensitiveSpecies(), Phase::setCaseSensitiveSpecies(), and Phase::speciesIndex().
m_name
std::string m_name private
Name of the phase.
Initially, this is the name specified in the YAML input file. It may be changed to another value during the course of a calculation.
Definition at line 988 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::name(), Phase::setName(), and Phase::speciesSPName().
m_temp
double m_temp = 0.001 private
Temperature (K). This is an independent variable.
Definition at line 990 of file Phase.h.
Referenced by Phase::electronTemperature(), Phase::setTemperature(), and Phase::temperature().
m_dens
double m_dens = 0.001 private
Density (kg m-3).
This is an independent variable except in the case of incompressible phases, where it has to be changed using the assignDensity() method. For compressible substances, the pressure is determined from this variable rather than other way round.
Definition at line 996 of file Phase.h.
Referenced by Phase::assignDensity(), Phase::concentration(), Phase::density(), Phase::getConcentrations(), Phase::setDensity(), and Phase::setMolarDensity().
m_mmw
double m_mmw = 0.0 private
mean molecular weight of the mixture (kg kmol-1)
Definition at line 998 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::getMoleFractions(), Phase::mean_X(), Phase::meanMolecularWeight(), Phase::moleFraction(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMolecularWeight(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), Phase::setMolesNoTruncate(), and Phase::sum_xlogx().
m_ym
vector_fp m_ym mutable private
m_ym[k] = mole fraction of species k divided by the mean molecular weight of mixture.
Definition at line 1002 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::getConcentrations(), Phase::getMoleFractions(), Phase::mean_X(), Phase::moleFractdivMMW(), Phase::moleFraction(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMolecularWeight(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), Phase::setMolesNoTruncate(), and Phase::sum_xlogx().
m_y
vector_fp m_y mutable private
Mass fractions of the species.
Note, this vector Length is m_kk
Definition at line 1009 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::concentration(), Phase::getMassFractions(), Phase::massFraction(), Phase::massFractions(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMolecularWeight(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), and Phase::setMolesNoTruncate().
m_molwts
vector_fp m_molwts private
species molecular weights (kg kmol-1)
Definition at line 1011 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::massFractionsToMoleFractions(), Phase::molecularWeight(), Phase::molecularWeights(), Phase::moleFractionsToMassFractions(), Phase::setConcentrations(), Phase::setConcentrationsNoNorm(), Phase::setMolecularWeight(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), and Phase::setMolesNoTruncate().
m_rmolwts
vector_fp m_rmolwts private
inverse of species molecular weights (kmol kg-1)
Definition at line 1013 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::concentration(), Phase::inverseMolecularWeights(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), and Phase::setMolecularWeight().
m_stateNum
int m_stateNum = -1 private
State Change variable.
Whenever the mole fraction vector changes, this int is incremented.
Definition at line 1017 of file Phase.h.
Referenced by Phase::compositionChanged(), Phase::invalidateCache(), and Phase::stateMFNumber().
m_speciesNames
std::vector<std::string> m_speciesNames private
Vector of the species names.
Definition at line 1020 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::species(), Phase::speciesName(), and Phase::speciesNames().
m_speciesIndices
std::map<std::string, size_t> m_speciesIndices private
Map of species names to indices.
Definition at line 1023 of file Phase.h.
Referenced by Phase::addSpecies(), Phase::addSpeciesAlias(), and Phase::speciesIndex().
m_speciesLower
std::map<std::string, size_t> m_speciesLower private
Map of lower-case species names to indices.
Definition at line 1026 of file Phase.h.
Referenced by Phase::addSpecies(), and Phase::findSpeciesLower().
m_mm
size_t m_mm = 0 private
Number of elements.
Definition at line 1028 of file Phase.h.
Referenced by Phase::addElement(), Phase::checkElementArraySize(), Phase::checkElementIndex(), Phase::elementIndex(), Phase::getAtoms(), Phase::nAtoms(), and Phase::nElements().
m_atomicWeights
vector_fp m_atomicWeights private
element atomic weights (kg kmol-1)
Definition at line 1029 of file Phase.h.
Referenced by Phase::addElement(), Phase::atomicWeight(), and Phase::atomicWeights().
m_atomicNumbers
vector_int m_atomicNumbers private
element atomic numbers
Definition at line 1030 of file Phase.h.
Referenced by Phase::addElement(), and Phase::atomicNumber().
m_elementNames
std::vector<std::string> m_elementNames private
element names
Definition at line 1031 of file Phase.h.
Referenced by Phase::addElement(), Phase::elementIndex(), Phase::elementName(), and Phase::elementNames().
m_elem_type
vector_int m_elem_type private
Vector of element types.
Definition at line 1032 of file Phase.h.
Referenced by Phase::addElement(), Phase::changeElementType(), and Phase::elementType().
m_entropy298
vector_fp m_entropy298 private
Entropy at 298.15 K and 1 bar of stable state pure elements (J kmol-1)
Definition at line 1035 of file Phase.h.
Referenced by Phase::addElement(), and Phase::entropyElement298().
The documentation for this class was generated from the following files:
Phase.h
Phase.cpp