Cantera: ThirdBody Class Reference
ThirdBody Class Reference
A class for managing third-body efficiencies, including default values.
#include <Reaction.h>
Public Member Functions
ThirdBody (const std::string &third_body)
ThirdBody (const AnyMap &node)
ThirdBody (double default_efficiency)
std::string name () const
Name of the third body collider.
void setName (const std::string &third_body)
Set name of the third body collider.
void setEfficiencies (const AnyMap &node)
Set third-body efficiencies from AnyMap node
void setParameters (const AnyMap &node)
Set third-body efficiencies from AnyMap node
void getParameters (AnyMap &node) const
Get third-body efficiencies from AnyMap node
double efficiency (const std::string &k) const
Get the third-body efficiency for species k
std::string collider () const
Suffix representing the third body collider in reaction equation, for example + M or (+M)
bool checkSpecies (const Reaction &rxn, const Kinetics &kin) const
Verify that all species involved in collision efficiencies are defined in the Kinetics object.
Public Attributes
Composition efficiencies
Map of species to third body efficiency.
double default_efficiency = 1.
The default third body efficiency for species not listed in efficiencies.
bool mass_action = true
Third body is used by law of mass action (true for three-body reactions, false for falloff reactions)
bool explicit_3rd = false
Flag indicating whether third body requires explicit serialization.
Protected Attributes
std::string m_name = "M"
Name of the third body collider.
Detailed Description
A class for managing third-body efficiencies, including default values.
Definition at line 213 of file Reaction.h.
Constructor & Destructor Documentation
ThirdBody() [1/4]
ThirdBody () inline explicit
Definition at line 216 of file Reaction.h.
ThirdBody() [2/4]
ThirdBody (const std::string & third_body)
Definition at line 715 of file Reaction.cpp.
ThirdBody() [3/4]
ThirdBody (const AnyMap & node)
Definition at line 748 of file Reaction.cpp.
ThirdBody() [4/4]
ThirdBody (double default_efficiency)
Deprecated:
To be removed after Cantera 3.0; instantiate using string instead
Definition at line 707 of file Reaction.cpp.
References Cantera::warn_deprecated().
Member Function Documentation
name()
std::string name () const inline
Name of the third body collider.
Since
New in Cantera 3.0
Definition at line 225 of file Reaction.h.
References ThirdBody::m_name.
Referenced by ThirdBody::setName().
setName()
void setName (const std::string & third_body)
Set name of the third body collider.
Since
New in Cantera 3.0
Definition at line 720 of file Reaction.cpp.
References ThirdBody::default_efficiency, ThirdBody::efficiencies, ThirdBody::m_name, ThirdBody::mass_action, and ThirdBody::name().
setEfficiencies()
void setEfficiencies (const AnyMap & node)
Set third-body efficiencies from AnyMap node
Deprecated:
To be removed after Cantera 3.0; renamed to setParameters
Definition at line 753 of file Reaction.cpp.
References ThirdBody::setParameters(), and Cantera::warn_deprecated().
setParameters()
void setParameters (const AnyMap & node)
Set third-body efficiencies from AnyMap node
Since
New in Cantera 3.0
Definition at line 760 of file Reaction.cpp.
References ThirdBody::default_efficiency, ThirdBody::efficiencies, AnyMap::hasKey(), and ThirdBody::m_name.
Referenced by ThirdBody::setEfficiencies().
getParameters()
void getParameters (AnyMap & node) const
Get third-body efficiencies from AnyMap node
Parameters
node AnyMap receiving serialized parameters
Since
New in Cantera 3.0
Definition at line 782 of file Reaction.cpp.
References ThirdBody::default_efficiency, ThirdBody::efficiencies, ThirdBody::explicit_3rd, ThirdBody::m_name, and AnyMap::setFlowStyle().
efficiency()
double efficiency (const std::string & k) const
Get the third-body efficiency for species k
Definition at line 795 of file Reaction.cpp.
References ThirdBody::default_efficiency, ThirdBody::efficiencies, and Cantera::getValue().
Referenced by Kinetics::checkDuplicates().
collider()
std::string collider () const
Suffix representing the third body collider in reaction equation, for example + M or (+M)
Since
New in Cantera 3.0
Definition at line 800 of file Reaction.cpp.
References ThirdBody::m_name, and ThirdBody::mass_action.
checkSpecies()
bool checkSpecies (const Reaction & rxn, const Kinetics & kin) const
Verify that all species involved in collision efficiencies are defined in the Kinetics object.
The function returns true if all species are found, and raises an exception unless the Kinetics object is configured to skip undeclared species, in which case false is returned.
Parameters
rxn Reaction object
kin Kinetics object
Since
New in Cantera 3.0
Definition at line 808 of file Reaction.cpp.
References ThirdBody::efficiencies, Reaction::equation(), AnyMap::hasKey(), Reaction::input, ThirdBody::m_name, Kinetics::skipUndeclaredSpecies(), and Kinetics::skipUndeclaredThirdBodies().
Member Data Documentation
efficiencies
Composition efficiencies
Map of species to third body efficiency.
Definition at line 264 of file Reaction.h.
Referenced by ThirdBody::checkSpecies(), ThirdBody::efficiency(), ThirdBody::getParameters(), ThirdBody::setName(), and ThirdBody::setParameters().
default_efficiency
double default_efficiency = 1.
The default third body efficiency for species not listed in efficiencies.
Definition at line 267 of file Reaction.h.
Referenced by ThirdBody::efficiency(), ThirdBody::getParameters(), ThirdBody::setName(), and ThirdBody::setParameters().
mass_action
bool mass_action = true
Third body is used by law of mass action (true for three-body reactions, false for falloff reactions)
Definition at line 271 of file Reaction.h.
Referenced by ThirdBody::collider(), and ThirdBody::setName().
explicit_3rd
bool explicit_3rd = false
Flag indicating whether third body requires explicit serialization.
Definition at line 274 of file Reaction.h.
Referenced by ThirdBody::getParameters().
m_name
std::string m_name = "M" protected
Name of the third body collider.
Definition at line 278 of file Reaction.h.
Referenced by ThirdBody::checkSpecies(), ThirdBody::collider(), ThirdBody::getParameters(), ThirdBody::name(), ThirdBody::setName(), and ThirdBody::setParameters().
The documentation for this class was generated from the following files:
Reaction.h
Reaction.cpp