Cantera: Kinetics Class Reference
Kinetics Class Reference
Chemical Kinetics » Kinetics Managers
Public interface for kinetics managers.
#include <Kinetics.h>
Public Member Functions
virtual std::pair< size_t, size_t > checkDuplicates (bool throw_err=true) const
Check for unmarked duplicate reactions and unmatched marked duplicates.
void selectPhase (const double *data, const ThermoPhase *phase, double *phase_data)
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
shared_ptr< Solution > root () const
Get the Solution object containing this Kinetics object and associated ThermoPhase objects.
virtual double reactionEnthalpy (const Composition &reactants, const Composition &products)
Calculate the reaction enthalpy of a reaction which has not necessarily been added into the Kinetics object.
Constructors and General Information about Mechanism
Kinetics ()=default
Default constructor.
virtual ~Kinetics ()=default
Kinetics (const Kinetics &)=delete
Kinetics objects are not copyable or assignable.
Kinetics & operator= (const Kinetics &)=delete
virtual std::string kineticsType () const
Identifies the Kinetics manager type.
virtual void resizeReactions ()
Finalize Kinetics object and associated objects.
size_t nReactions () const
Number of reactions in the reaction mechanism.
void checkReactionIndex (size_t m) const
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
void checkReactionArraySize (size_t ii) const
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t mm) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Information/Lookup Functions about Phases and Species
size_t nPhases () const
The number of phases participating in the reaction mechanism.
void checkPhaseIndex (size_t m) const
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
void checkPhaseArraySize (size_t mm) const
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
size_t phaseIndex (const std::string &ph) const
Return the phase index of a phase in the list of phases defined within the object.
size_t surfacePhaseIndex () const
This returns the integer index of the phase which has ThermoPhase type cSurf.
size_t reactionPhaseIndex () const
Phase where the reactions occur.
shared_ptr< ThermoPhase > reactionPhase () const
Return pointer to phase where the reactions occur.
ThermoPhase & thermo (size_t n=0)
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
const ThermoPhase & thermo (size_t n=0) const
size_t nTotalSpecies () const
The total number of species in all phases participating in the kinetics mechanism.
size_t kineticsSpeciesIndex (size_t k, size_t n) const
The location of species k of phase n in species arrays.
std::string kineticsSpeciesName (size_t k) const
Return the name of the kth species in the kinetics manager.
size_t kineticsSpeciesIndex (const std::string &nm) const
This routine will look up a species number based on the input std::string nm.
size_t kineticsSpeciesIndex (const std::string &nm, const std::string &ph) const
This routine will look up a species number based on the input std::string nm.
ThermoPhase & speciesPhase (const std::string &nm)
This function looks up the name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
const ThermoPhase & speciesPhase (const std::string &nm) const
ThermoPhase & speciesPhase (size_t k)
This function takes as an argument the kineticsSpecies index (that is, the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
size_t speciesPhaseIndex (size_t k) const
This function takes as an argument the kineticsSpecies index (that is, the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
Reaction Rates Of Progress
virtual void getFwdRatesOfProgress (doublereal *fwdROP)
Return the forward rates of progress of the reactions.
virtual void getRevRatesOfProgress (doublereal *revROP)
Return the Reverse rates of progress of the reactions.
virtual void getNetRatesOfProgress (doublereal *netROP)
Net rates of progress.
virtual void getEquilibriumConstants (doublereal *kc)
Return a vector of Equilibrium constants.
virtual void getReactionDelta (const double *property, double *deltaProperty) const
Change in species properties.
virtual void getRevReactionDelta (const double *g, double *dg) const
Given an array of species properties 'g', return in array 'dg' the change in this quantity in the reversible reactions.
virtual void getDeltaGibbs (doublereal *deltaG)
Return the vector of values for the reaction Gibbs free energy change.
virtual void getDeltaElectrochemPotentials (doublereal *deltaM)
Return the vector of values for the reaction electrochemical free energy change.
virtual void getDeltaEnthalpy (doublereal *deltaH)
Return the vector of values for the reactions change in enthalpy.
virtual void getDeltaEntropy (doublereal *deltaS)
Return the vector of values for the reactions change in entropy.
virtual void getDeltaSSGibbs (doublereal *deltaG)
Return the vector of values for the reaction standard state Gibbs free energy change.
virtual void getDeltaSSEnthalpy (doublereal *deltaH)
Return the vector of values for the change in the standard state enthalpies of reaction.
virtual void getDeltaSSEntropy (doublereal *deltaS)
Return the vector of values for the change in the standard state entropies for each reaction.
virtual void getThirdBodyConcentrations (double *concm)
Return a vector of values of effective concentrations of third-body collision partners of any reaction.
virtual const vector_fp & thirdBodyConcentrations () const
Provide direct access to current third-body concentration values.
Species Production Rates
virtual void getCreationRates (doublereal *cdot)
Species creation rates [kmol/m^3/s or kmol/m^2/s].
virtual void getDestructionRates (doublereal *ddot)
Species destruction rates [kmol/m^3/s or kmol/m^2/s].
virtual void getNetProductionRates (doublereal *wdot)
Species net production rates [kmol/m^3/s or kmol/m^2/s].
Routines to Calculate Derivatives (Jacobians)
Derivatives are calculated with respect to temperature, pressure, molar concentrations and species mole fractions for forward/reverse/net rates of progress as well as creation/destruction and net production of species.
The following suffixes are used to indicate derivatives:
_ddT: derivative with respect to temperature (a vector)
_ddP: derivative with respect to pressure (a vector)
_ddC: derivative with respect to molar concentration (a vector)
_ddX: derivative with respect to species mole fractions (a matrix)
_ddCi: derivative with respect to species concentrations (a matrix)
Settings for derivative evaluation are set by keyword/value pairs using the methods getDerivativeSettings() and setDerivativeSettings().
For BulkKinetics, the following keyword/value pairs are supported:
skip-third-bodies (boolean) ... if false (default), third body concentrations are considered for the evaluation of jacobians
skip-falloff (boolean) ... if false (default), third-body effects on rate constants are considered for the evaluation of derivatives.
rtol-delta (double) ... relative tolerance used to perturb properties when calculating numerical derivatives. The default value is 1e-8.
For InterfaceKinetics, the following keyword/value pairs are supported:
skip-coverage-dependence (boolean) ... if false (default), rate constant coverage dependence is not considered when evaluating derivatives.
skip-electrochemistry (boolean) ... if false (default), electrical charge is not considered in evaluating the derivatives and these reactions are treated as normal surface reactions.
rtol-delta (double) ... relative tolerance used to perturb properties when calculating numerical derivatives. The default value is 1e-8.
Warning
The calculation of derivatives is an experimental part of the Cantera API and may be changed or removed without notice.
virtual void getDerivativeSettings (AnyMap &settings) const
Retrieve derivative settings.
virtual void setDerivativeSettings (const AnyMap &settings)
Set/modify derivative settings.
virtual void getFwdRateConstants_ddT (double *dkfwd)
Calculate derivatives for forward rate constants with respect to temperature at constant pressure, molar concentration and mole fractions.
virtual void getFwdRateConstants_ddP (double *dkfwd)
Calculate derivatives for forward rate constants with respect to pressure at constant temperature, molar concentration and mole fractions.
virtual void getFwdRateConstants_ddC (double *dkfwd)
Calculate derivatives for forward rate constants with respect to molar concentration at constant temperature, pressure and mole fractions.
virtual void getFwdRatesOfProgress_ddT (double *drop)
Calculate derivatives for forward rates-of-progress with respect to temperature at constant pressure, molar concentration and mole fractions.
virtual void getFwdRatesOfProgress_ddP (double *drop)
Calculate derivatives for forward rates-of-progress with respect to pressure at constant temperature, molar concentration and mole fractions.
virtual void getFwdRatesOfProgress_ddC (double *drop)
Calculate derivatives for forward rates-of-progress with respect to molar concentration at constant temperature, pressure and mole fractions.
virtual Eigen::SparseMatrix< double > fwdRatesOfProgress_ddX ()
Calculate derivatives for forward rates-of-progress with respect to species mole fractions at constant temperature, pressure and molar concentration.
virtual Eigen::SparseMatrix< double > fwdRatesOfProgress_ddCi ()
Calculate derivatives for forward rates-of-progress with respect to species concentration at constant temperature, pressure and remaining species concentrations.
virtual void getRevRatesOfProgress_ddT (double *drop)
Calculate derivatives for reverse rates-of-progress with respect to temperature at constant pressure, molar concentration and mole fractions.
virtual void getRevRatesOfProgress_ddP (double *drop)
Calculate derivatives for reverse rates-of-progress with respect to pressure at constant temperature, molar concentration and mole fractions.
virtual void getRevRatesOfProgress_ddC (double *drop)
Calculate derivatives for reverse rates-of-progress with respect to molar concentration at constant temperature, pressure and mole fractions.
virtual Eigen::SparseMatrix< double > revRatesOfProgress_ddX ()
Calculate derivatives for reverse rates-of-progress with respect to species mole fractions at constant temperature, pressure and molar concentration.
virtual Eigen::SparseMatrix< double > revRatesOfProgress_ddCi ()
Calculate derivatives for forward rates-of-progress with respect to species concentration at constant temperature, pressure and remaining species concentrations.
virtual void getNetRatesOfProgress_ddT (double *drop)
Calculate derivatives for net rates-of-progress with respect to temperature at constant pressure, molar concentration and mole fractions.
virtual void getNetRatesOfProgress_ddP (double *drop)
Calculate derivatives for net rates-of-progress with respect to pressure at constant temperature, molar concentration and mole fractions.
virtual void getNetRatesOfProgress_ddC (double *drop)
Calculate derivatives for net rates-of-progress with respect to molar concentration at constant temperature, pressure and mole fractions.
virtual Eigen::SparseMatrix< double > netRatesOfProgress_ddX ()
Calculate derivatives for net rates-of-progress with respect to species mole fractions at constant temperature, pressure and molar concentration.
virtual Eigen::SparseMatrix< double > netRatesOfProgress_ddCi ()
Calculate derivatives for net rates-of-progress with respect to species concentration at constant temperature, pressure, and remaining species concentrations.
void getCreationRates_ddT (double *dwdot)
Calculate derivatives for species creation rates with respect to temperature at constant pressure, molar concentration and mole fractions.
void getCreationRates_ddP (double *dwdot)
Calculate derivatives for species creation rates with respect to pressure at constant temperature, molar concentration and mole fractions.
void getCreationRates_ddC (double *dwdot)
Calculate derivatives for species creation rates with respect to molar concentration at constant temperature, pressure and mole fractions.
Eigen::SparseMatrix< double > creationRates_ddX ()
Calculate derivatives for species creation rates with respect to species mole fractions at constant temperature, pressure and molar concentration.
Eigen::SparseMatrix< double > creationRates_ddCi ()
Calculate derivatives for species creation rates with respect to species concentration at constant temperature, pressure, and concentration of all other species.
void getDestructionRates_ddT (double *dwdot)
Calculate derivatives for species destruction rates with respect to temperature at constant pressure, molar concentration and mole fractions.
void getDestructionRates_ddP (double *dwdot)
Calculate derivatives for species destruction rates with respect to pressure at constant temperature, molar concentration and mole fractions.
void getDestructionRates_ddC (double *dwdot)
Calculate derivatives for species destruction rates with respect to molar concentration at constant temperature, pressure and mole fractions.
Eigen::SparseMatrix< double > destructionRates_ddX ()
Calculate derivatives for species destruction rates with respect to species mole fractions at constant temperature, pressure and molar concentration.
Eigen::SparseMatrix< double > destructionRates_ddCi ()
Calculate derivatives for species destruction rates with respect to species concentration at constant temperature, pressure, and concentration of all other species.
void getNetProductionRates_ddT (double *dwdot)
Calculate derivatives for species net production rates with respect to temperature at constant pressure, molar concentration and mole fractions.
void getNetProductionRates_ddP (double *dwdot)
Calculate derivatives for species net production rates with respect to pressure at constant temperature, molar concentration and mole fractions.
void getNetProductionRates_ddC (double *dwdot)
Calculate derivatives for species net production rates with respect to molar concentration at constant temperature, pressure and mole fractions.
Eigen::SparseMatrix< double > netProductionRates_ddX ()
Calculate derivatives for species net production rates with respect to species mole fractions at constant temperature, pressure and molar concentration.
Eigen::SparseMatrix< double > netProductionRates_ddCi ()
Calculate derivatives for species net production rates with respect to species concentration at constant temperature, pressure, and concentration of all other species.
Reaction Mechanism Informational Query Routines
virtual double reactantStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a reactant in reaction i.
Eigen::SparseMatrix< double > reactantStoichCoeffs () const
Stoichiometric coefficient matrix for reactants.
virtual double productStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a product in reaction i.
Eigen::SparseMatrix< double > productStoichCoeffs () const
Stoichiometric coefficient matrix for products.
Eigen::SparseMatrix< double > revProductStoichCoeffs () const
Stoichiometric coefficient matrix for products of reversible reactions.
virtual doublereal reactantOrder (size_t k, size_t i) const
Reactant order of species k in reaction i.
virtual doublereal productOrder (int k, int i) const
product Order of species k in reaction i.
virtual void getActivityConcentrations (doublereal *const conc)
Get the vector of activity concentrations used in the kinetics object.
virtual std::string reactionType (size_t i) const
String specifying the type of reaction.
virtual std::string reactionTypeStr (size_t i) const
String specifying the type of reaction.
virtual bool isReversible (size_t i)
True if reaction i has been declared to be reversible.
std::string reactionString (size_t i) const
Return a string representing the reaction.
std::string reactantString (size_t i) const
Returns a string containing the reactants side of the reaction equation.
std::string productString (size_t i) const
Returns a string containing the products side of the reaction equation.
virtual void getFwdRateConstants (double *kfwd)
Return the forward rate constants.
virtual void getRevRateConstants (double *krev, bool doIrreversible=false)
Return the reverse rate constants.
Reaction Mechanism Construction
virtual void addThermo (shared_ptr< ThermoPhase > thermo)
Add a phase to the kinetics manager object.
virtual void addPhase (ThermoPhase &thermo)
virtual void init ()
Prepare the class for the addition of reactions, after all phases have been added.
AnyMap parameters ()
Return the parameters for a phase definition which are needed to reconstruct an identical object using the newKinetics function.
virtual void resizeSpecies ()
Resize arrays with sizes that depend on the total number of species.
virtual bool addReaction (shared_ptr< Reaction > r, bool resize=true)
Add a single reaction to the mechanism.
virtual void modifyReaction (size_t i, shared_ptr< Reaction > rNew)
Modify the rate expression associated with a reaction.
shared_ptr< Reaction > reaction (size_t i)
Return the Reaction object for reaction i.
shared_ptr< const Reaction > reaction (size_t i) const
void skipUndeclaredSpecies (bool skip)
Determine behavior when adding a new reaction that contains species not defined in any of the phases associated with this kinetics manager.
bool skipUndeclaredSpecies () const
void skipUndeclaredThirdBodies (bool skip)
Determine behavior when adding a new reaction that contains third-body efficiencies for species not defined in any of the phases associated with this kinetics manager.
bool skipUndeclaredThirdBodies () const
Altering Reaction Rates
These methods alter reaction rates.
They are designed primarily for carrying out sensitivity analysis, but may be used for any purpose requiring dynamic alteration of rate constants. For each reaction, a real-valued multiplier may be defined that multiplies the reaction rate coefficient. The multiplier may be set to zero to completely remove a reaction from the mechanism.
doublereal multiplier (size_t i) const
The current value of the multiplier for reaction i.
virtual void setMultiplier (size_t i, doublereal f)
Set the multiplier for reaction i to f.
virtual void invalidateCache ()
Protected Member Functions
virtual void updateROP ()
double checkDuplicateStoich (std::map< int, double > &r1, std::map< int, double > &r2) const
Check whether r1 and r2 represent duplicate stoichiometries This function returns a ratio if two reactions are duplicates of one another, and 0.0 otherwise.
Protected Attributes
ValueCache m_cache
Cache for saved calculations within each Kinetics object.
bool m_ready = false
Boolean indicating whether Kinetics object is fully configured.
size_t m_kk = 0
The number of species in all of the phases that participate in this kinetics mechanism.
vector_fp m_perturb
Vector of perturbation factors for each reaction's rate of progress vector.
std::vector< shared_ptr< Reaction > > m_reactions
Vector of Reaction objects represented by this Kinetics manager.
std::vector< ThermoPhase * > m_thermo
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
vector< shared_ptr< ThermoPhase > > m_sharedThermo
vector of shared pointers,
std::vector< size_t > m_start
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
std::map< std::string, size_t > m_phaseindex
Mapping of the phase name to the position of the phase within the kinetics object.
size_t m_surfphase = npos
Index in the list of phases of the one surface phase.
size_t m_rxnphase = npos
Phase Index where reactions are assumed to be taking place.
size_t m_mindim = 4
number of spatial dimensions of lowest-dimensional phase.
vector_fp m_rfn
Forward rate constant for each reaction.
vector_fp m_delta_gibbs0
Delta G^0 for all reactions.
vector_fp m_rkcn
Reciprocal of the equilibrium constant in concentration units.
vector_fp m_ropf
Forward rate-of-progress for each reaction.
vector_fp m_ropr
Reverse rate-of-progress for each reaction.
vector_fp m_ropnet
Net rate-of-progress for each reaction.
vector_fp m_dH
The enthalpy change for each reaction to calculate Blowers-Masel rates.
vector_fp m_rbuf
Buffer used for storage of intermediate reaction-specific results.
bool m_skipUndeclaredSpecies = false
See skipUndeclaredSpecies()
bool m_skipUndeclaredThirdBodies = false
See skipUndeclaredThirdBodies()
std::weak_ptr< Solution > m_root
reference to Solution
Stoichiometry management
These objects and functions handle turning reaction extents into species production rates and also handle turning thermo properties into reaction thermo properties.
StoichManagerN m_reactantStoich
Stoichiometry manager for the reactants for each reaction.
StoichManagerN m_productStoich
Stoichiometry manager for the products for each reaction.
StoichManagerN m_revProductStoich
Stoichiometry manager for the products of reversible reactions.
Eigen::SparseMatrix< double > m_stoichMatrix
Net stoichiometry (products - reactants)
Detailed Description
Public interface for kinetics managers.
This class serves as a base class to derive 'kinetics managers', which are classes that manage homogeneous chemistry within one phase, or heterogeneous chemistry at one interface. The virtual methods of this class are meant to be overloaded in subclasses. The non-virtual methods perform generic functions and are implemented in Kinetics. They should not be overloaded. Only those methods required by a subclass need to be overloaded; the rest will throw exceptions if called.
When the nomenclature "kinetics species index" is used below, this means that the species index ranges over all species in all phases handled by the kinetics manager.
Definition at line 113 of file Kinetics.h.
Constructor & Destructor Documentation
Kinetics() [1/2]
Kinetics () default
Default constructor.
Kinetics() [2/2]
Kinetics (const Kinetics &) delete
Kinetics objects are not copyable or assignable.
Member Function Documentation
kineticsType()
virtual std::string kineticsType () const inline virtual
Identifies the Kinetics manager type.
Each class derived from Kinetics should override this method to return a meaningful identifier.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented in EdgeKinetics, GasKinetics, InterfaceKinetics, and BulkKinetics.
Definition at line 133 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Cantera::addReactions(), Kinetics::fwdRatesOfProgress_ddCi(), Kinetics::fwdRatesOfProgress_ddX(), Kinetics::getDerivativeSettings(), Kinetics::getFwdRateConstants_ddC(), Kinetics::getFwdRateConstants_ddP(), Kinetics::getFwdRateConstants_ddT(), Kinetics::getFwdRatesOfProgress_ddC(), Kinetics::getFwdRatesOfProgress_ddP(), Kinetics::getFwdRatesOfProgress_ddT(), Kinetics::getNetRatesOfProgress_ddC(), Kinetics::getNetRatesOfProgress_ddP(), Kinetics::getNetRatesOfProgress_ddT(), Kinetics::getRevRatesOfProgress_ddC(), Kinetics::getRevRatesOfProgress_ddP(), Kinetics::getRevRatesOfProgress_ddT(), Kinetics::getThirdBodyConcentrations(), Kinetics::netRatesOfProgress_ddCi(), Kinetics::netRatesOfProgress_ddX(), Kinetics::parameters(), Kinetics::revRatesOfProgress_ddCi(), Kinetics::revRatesOfProgress_ddX(), Kinetics::setDerivativeSettings(), and Kinetics::thirdBodyConcentrations().
resizeReactions()
void resizeReactions () virtual
Finalize Kinetics object and associated objects.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 35 of file Kinetics.cpp.
References Kinetics::m_kk, Kinetics::m_productStoich, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::m_ready, Kinetics::m_revProductStoich, Kinetics::m_stoichMatrix, Kinetics::nReactions(), StoichManagerN::resizeCoeffs(), and StoichManagerN::stoichCoeffs().
Referenced by Kinetics::addReaction(), Cantera::addReactions(), InterfaceKinetics::resizeReactions(), and BulkKinetics::resizeReactions().
nReactions()
size_t nReactions () const inline
Number of reactions in the reaction mechanism.
Definition at line 141 of file Kinetics.h.
References Kinetics::m_reactions.
Referenced by InterfaceKinetics::addReaction(), Kinetics::addReaction(), BulkKinetics::addReaction(), ReactorSurface::addSensitivityReaction(), Reactor::addSensitivityReaction(), BulkKinetics::applyEquilibriumConstants(), InterfaceKinetics::applyEquilibriumConstants(), BulkKinetics::calculateCompositionDerivatives(), Kinetics::checkReactionArraySize(), Kinetics::checkReactionIndex(), Kinetics::getCreationRates_ddC(), Kinetics::getCreationRates_ddP(), Kinetics::getCreationRates_ddT(), InterfaceKinetics::getDeltaGibbs(), Kinetics::getDestructionRates_ddC(), Kinetics::getDestructionRates_ddP(), Kinetics::getDestructionRates_ddT(), BulkKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::getFwdRateConstants(), Kinetics::getNetProductionRates_ddC(), Kinetics::getNetProductionRates_ddP(), Kinetics::getNetProductionRates_ddT(), BulkKinetics::getNetRatesOfProgress_ddC(), BulkKinetics::getNetRatesOfProgress_ddT(), Kinetics::getReactionDelta(), BulkKinetics::getRevRateConstants(), InterfaceKinetics::getRevRateConstants(), BulkKinetics::getRevRatesOfProgress_ddT(), Kinetics::getRevReactionDelta(), Kinetics::parameters(), BulkKinetics::process_ddC(), InterfaceKinetics::resizeReactions(), Kinetics::resizeReactions(), BulkKinetics::resizeReactions(), InterfaceKinetics::resizeSpecies(), BulkKinetics::resizeSpecies(), Reactor::setKineticsMgr(), InterfaceKinetics::updateKc(), and InterfaceKinetics::updateROP().
checkReactionIndex()
void checkReactionIndex (size_t m) const
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
Definition at line 27 of file Kinetics.cpp.
References Kinetics::nReactions().
Referenced by Kinetics::modifyReaction(), and Kinetics::reaction().
checkReactionArraySize()
void checkReactionArraySize (size_t ii) const
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
Used before calls which take an array pointer.
Definition at line 54 of file Kinetics.cpp.
References Kinetics::nReactions().
checkSpeciesIndex()
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 93 of file Kinetics.cpp.
References Kinetics::m_kk.
checkSpeciesArraySize()
void checkSpeciesArraySize (size_t mm) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 100 of file Kinetics.cpp.
References Kinetics::m_kk.
nPhases()
size_t nPhases () const inline
The number of phases participating in the reaction mechanism.
For a homogeneous reaction mechanism, this will always return 1, but for a heterogeneous mechanism it will return the total number of phases in the mechanism.
Definition at line 173 of file Kinetics.h.
References Kinetics::m_thermo.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::_update_rates_T(), Kinetics::addPhase(), InterfaceKinetics::addReaction(), BulkKinetics::addReaction(), Kinetics::addThermo(), Kinetics::checkPhaseArraySize(), Kinetics::checkPhaseIndex(), ReactingSurf1D::eval(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), ImplicitSurfChem::ImplicitSurfChem(), Reaction::Reaction(), Kinetics::reactionEnthalpy(), InterfaceKinetics::resizeReactions(), BulkKinetics::resizeReactions(), InterfaceKinetics::resizeSpecies(), Kinetics::resizeSpecies(), BulkKinetics::resizeSpecies(), Kinetics::selectPhase(), InterfaceData::update(), solveSP::updateMFKinSpecies(), InterfaceKinetics::updateMu0(), InterfaceKinetics::updateROP(), and Reaction::usesElectrochemistry().
checkPhaseIndex()
void checkPhaseIndex (size_t m) const
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
Definition at line 62 of file Kinetics.cpp.
References Kinetics::nPhases().
Referenced by InterfaceKinetics::phaseExistence(), InterfaceKinetics::phaseStability(), InterfaceKinetics::setPhaseExistence(), and InterfaceKinetics::setPhaseStability().
checkPhaseArraySize()
void checkPhaseArraySize (size_t mm) const
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
Used before calls which take an array pointer.
Definition at line 69 of file Kinetics.cpp.
References Kinetics::nPhases().
phaseIndex()
size_t phaseIndex (const std::string & ph) const inline
Return the phase index of a phase in the list of phases defined within the object.
Parameters
ph std::string name of the phase
If a -1 is returned, then the phase is not defined in the Kinetics object.
Definition at line 195 of file Kinetics.h.
References Kinetics::m_phaseindex, and Cantera::npos.
surfacePhaseIndex()
size_t surfacePhaseIndex () const
This returns the integer index of the phase which has ThermoPhase type cSurf.
For heterogeneous mechanisms, this identifies the one surface phase. For homogeneous mechanisms, this returns -1.
Deprecated:
To be removed after Cantera 3.0. Use reactionPhaseIndex instead.
Definition at line 76 of file Kinetics.cpp.
References Kinetics::m_surfphase, and Cantera::warn_deprecated().
reactionPhaseIndex()
size_t reactionPhaseIndex () const inline
Phase where the reactions occur.
For heterogeneous mechanisms, one of the phases in the list of phases represents the 2D interface or 1D edge at which the reactions take place. This method returns the index of the phase with the smallest spatial dimension (1, 2, or 3) among the list of phases. If there is more than one, the index of the first one is returned. For homogeneous mechanisms, the value 0 is returned.
Deprecated:
Starting in Cantera 3.0, the reacting phase will always be the first phase in the InterfaceKinetics object. To be removed after Cantera 3.1.
Definition at line 223 of file Kinetics.h.
References Kinetics::m_rxnphase.
Referenced by InterfaceKinetics::_update_rates_T(), solveSP::calc_t(), Reaction::calculateRateCoeffUnits(), Reaction::checkBalance(), FlowReactor::evalDae(), MoleReactor::evalSurfaces(), Reactor::evalSurfaces(), solveSP::fun_eval(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::init(), Reaction::Reaction(), StickingCoverage::setContext(), Reaction::setEquation(), ReactorSurface::setKinetics(), ReactingSurf1D::setKineticsMgr(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), solveSP::solveSP(), InterfaceData::update(), InterfaceKinetics::updateKc(), and InterfaceKinetics::updateMu0().
reactionPhase()
shared_ptr< ThermoPhase > reactionPhase () const
Return pointer to phase where the reactions occur.
Since
New in Cantera 3.0
Definition at line 83 of file Kinetics.cpp.
References Kinetics::m_rxnphase, and Kinetics::m_sharedThermo.
thermo() [1/2]
ThermoPhase & thermo (size_t n = 0) inline
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase object may be called. For homogeneous mechanisms, there is only one object, and this method can be called without an argument to access it.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 242 of file Kinetics.h.
References Kinetics::m_thermo.
Referenced by InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::addPhase(), Kinetics::addPhase(), InterfaceKinetics::addThermo(), Kinetics::addThermo(), BulkKinetics::applyEquilibriumConstants_ddT(), BulkKinetics::assertDerivativesValid(), BulkKinetics::BulkKinetics(), solveSP::calc_t(), BulkKinetics::calculateCompositionDerivatives(), Reaction::calculateRateCoeffUnits(), Reaction::checkBalance(), ReactingSurf1D::eval(), FlowReactor::evalDae(), GasKinetics::GasKinetics(), InterfaceKinetics::getDeltaElectrochemPotentials(), BulkKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEnthalpy(), BulkKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaEntropy(), BulkKinetics::getDeltaGibbs(), BulkKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), BulkKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), BulkKinetics::getDeltaSSGibbs(), InterfaceKinetics::getDeltaSSGibbs(), BulkKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), ImplicitSurfChem::ImplicitSurfChem(), InterfaceKinetics::init(), InterfaceKinetics::interfaceCurrent(), InterfaceKinetics::InterfaceKinetics(), Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), BulkKinetics::process_ddC(), Reaction::Reaction(), Kinetics::reactionEnthalpy(), BulkKinetics::resizeReactions(), InterfaceRateBase::setContext(), StickingCoverage::setContext(), InterfaceKinetics::setElectricPotential(), Reaction::setEquation(), ReactorSurface::setKinetics(), ReactingSurf1D::setKineticsMgr(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), solveSP::solveSP(), Kinetics::speciesPhase(), InterfaceData::update(), InterfaceKinetics::updateKc(), solveSP::updateMFKinSpecies(), InterfaceKinetics::updateMu0(), and Reaction::usesElectrochemistry().
thermo() [2/2]
const ThermoPhase & thermo (size_t n = 0) const inline
Definition at line 245 of file Kinetics.h.
nTotalSpecies()
size_t nTotalSpecies () const inline
The total number of species in all phases participating in the kinetics mechanism.
This is useful to dimension arrays for use in calls to methods that return the species production rates, for example.
Definition at line 254 of file Kinetics.h.
References Kinetics::m_kk.
Referenced by Kinetics::checkDuplicates(), ReactingSurf1D::init(), Kinetics::reactionEnthalpy(), InterfaceKinetics::resizeReactions(), and BulkKinetics::resizeReactions().
kineticsSpeciesIndex() [1/3]
size_t kineticsSpeciesIndex (size_t k, size_t n) const inline
The location of species k of phase n in species arrays.
Kinetics manager classes return species production rates in flat arrays, with the species of each phases following one another, in the order the phases were added. This method is useful to find the value for a particular species of a particular phase in arrays returned from methods like getCreationRates that return an array of species-specific quantities.
Example: suppose a heterogeneous mechanism involves three phases. The first contains 12 species, the second 26, and the third 3. Then species arrays must have size at least 41, and positions 0 - 11 are the values for the species in the first phase, positions 12 - 37 are the values for the species in the second phase, etc. Then kineticsSpeciesIndex(7, 0) = 7, kineticsSpeciesIndex(4, 1) = 16, and kineticsSpeciesIndex(2, 2) = 40.
Parameters
k species index
n phase index for the species
Definition at line 276 of file Kinetics.h.
References Kinetics::m_start.
Referenced by InterfaceKinetics::addReaction(), Kinetics::addReaction(), solveSP::calc_t(), Kinetics::checkDuplicates(), ReactingSurf1D::eval(), FlowReactor::evalDae(), MoleReactor::evalSurfaces(), Reactor::evalSurfaces(), solveSP::fun_eval(), Kinetics::kineticsSpeciesIndex(), Cantera::parseReactionEquation(), Kinetics::reactionEnthalpy(), InterfaceRateBase::setContext(), StickingCoverage::setContext(), BlowersMaselRate::setContext(), Reaction::setParameters(), solveSP::solveSP(), InterfaceData::update(), solveSP::updateMFKinSpecies(), and Reaction::usesElectrochemistry().
kineticsSpeciesName()
string kineticsSpeciesName (size_t k) const
Return the name of the kth species in the kinetics manager.
k is an integer from 0 to ktot - 1, where ktot is the number of species in the kinetics manager, which is the sum of the number of species in all phases participating in the kinetics manager. If k is out of bounds, the string "<unknown>" is returned.
Parameters
k species index
Definition at line 259 of file Kinetics.cpp.
References Kinetics::m_start, Cantera::npos, Phase::speciesName(), and Kinetics::thermo().
Referenced by Kinetics::checkDuplicates().
kineticsSpeciesIndex() [2/3]
size_t kineticsSpeciesIndex (const std::string & nm) const
This routine will look up a species number based on the input std::string nm.
The lookup of species will occur for all phases listed in the kinetics object.
return
If a match is found, the position in the species list is returned.
If no match is found, the value -1 is returned.
Parameters
nm Input string name of the species
Definition at line 269 of file Kinetics.cpp.
References Kinetics::m_start, Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
kineticsSpeciesIndex() [3/3]
size_t kineticsSpeciesIndex (const std::string & nm, const std::string & ph) const
This routine will look up a species number based on the input std::string nm.
The lookup of species will occur in the specified phase of the object, or all phases if ph is "<any>".
return
If a match is found, the position in the species list is returned.
If no match is found, the value npos (-1) is returned.
Parameters
nm Input string name of the species
ph Input string name of the phase.
Deprecated:
To be removed after Cantera 3.0. Species names should be unique across all phases.
Definition at line 281 of file Kinetics.cpp.
References Kinetics::kineticsSpeciesIndex(), Kinetics::m_start, Kinetics::m_thermo, Phase::name(), Cantera::npos, Phase::speciesIndex(), Kinetics::thermo(), and Cantera::warn_deprecated().
speciesPhase() [1/3]
ThermoPhase & speciesPhase (const std::string & nm)
This function looks up the name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
Will throw an error if the species doesn't match.
Parameters
nm String containing the name of the species.
Definition at line 304 of file Kinetics.cpp.
References Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
Referenced by Reaction::calculateRateCoeffUnits(), and Reaction::checkBalance().
speciesPhase() [2/3]
const ThermoPhase & speciesPhase (const std::string & nm) const
Definition at line 315 of file Kinetics.cpp.
speciesPhase() [3/3]
ThermoPhase & speciesPhase (size_t k) inline
This function takes as an argument the kineticsSpecies index (that is, the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
Parameters
k Species index
Definition at line 338 of file Kinetics.h.
References Kinetics::speciesPhaseIndex(), and Kinetics::thermo().
speciesPhaseIndex()
size_t speciesPhaseIndex (size_t k) const
This function takes as an argument the kineticsSpecies index (that is, the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
Parameters
k Species index
Definition at line 325 of file Kinetics.cpp.
References Kinetics::m_start, and Cantera::npos.
Referenced by InterfaceKinetics::addReaction(), InterfaceRateBase::setContext(), StickingCoverage::setContext(), Kinetics::speciesPhase(), and Reaction::usesElectrochemistry().
getFwdRatesOfProgress()
void getFwdRatesOfProgress (doublereal * fwdROP) virtual
Return the forward rates of progress of the reactions.
Forward rates of progress. Return the forward rates of progress in array fwdROP, which must be dimensioned at least as large as the total number of reactions.
Parameters
fwdROP Output vector containing forward rates of progress of the reactions. Length: nReactions().
Definition at line 376 of file Kinetics.cpp.
References Kinetics::m_ropf.
getRevRatesOfProgress()
void getRevRatesOfProgress (doublereal * revROP) virtual
Return the Reverse rates of progress of the reactions.
Return the reverse rates of progress in array revROP, which must be dimensioned at least as large as the total number of reactions.
Parameters
revROP Output vector containing reverse rates of progress of the reactions. Length: nReactions().
Definition at line 382 of file Kinetics.cpp.
References Kinetics::m_ropr.
getNetRatesOfProgress()
void getNetRatesOfProgress (doublereal * netROP) virtual
Net rates of progress.
Return the net (forward - reverse) rates of progress in array netROP, which must be dimensioned at least as large as the total number of reactions.
Parameters
netROP Output vector of the net ROP. Length: nReactions().
Definition at line 388 of file Kinetics.cpp.
References Kinetics::m_ropnet.
getEquilibriumConstants()
virtual void getEquilibriumConstants (doublereal * kc) inline virtual
Return a vector of Equilibrium constants.
Return the equilibrium constants of the reactions in concentration units in array kc, which must be dimensioned at least as large as the total number of reactions.
\[ Kc_i = exp [ \Delta G_{ss,i} ] prod(Cs_k) exp(\sum_k \nu_{k,i} F \phi_n) ] \]
Parameters
kc Output vector containing the equilibrium constants. Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 398 of file Kinetics.h.
getReactionDelta()
void getReactionDelta (const double * property, double * deltaProperty) const virtual
Change in species properties.
Given an array of molar species property values \(z_k, k = 1, \dots, K \), return the array of reaction values
\[ \Delta Z_i = \sum_k \nu_{k,i} z_k, i = 1, \dots, I. \]
For example, if this method is called with the array of standard-state molar Gibbs free energies for the species, then the values returned in array deltaProperty would be the standard-state Gibbs free energies of reaction for each reaction.
Parameters
property Input vector of property value. Length: m_kk.
deltaProperty Output vector of deltaRxn. Length: nReactions().
Definition at line 394 of file Kinetics.cpp.
References Kinetics::m_productStoich, Kinetics::m_reactantStoich, and Kinetics::nReactions().
Referenced by InterfaceKinetics::_update_rates_T(), InterfaceKinetics::getDeltaElectrochemPotentials(), BulkKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEnthalpy(), BulkKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaEntropy(), BulkKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaGibbs(), BulkKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), BulkKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), BulkKinetics::getDeltaSSGibbs(), InterfaceKinetics::getDeltaSSGibbs(), BulkKinetics::getEquilibriumConstants(), and InterfaceKinetics::getEquilibriumConstants().
getRevReactionDelta()
void getRevReactionDelta (const double * g, double * dg) const virtual
Given an array of species properties 'g', return in array 'dg' the change in this quantity in the reversible reactions.
Array 'g' must have a length at least as great as the number of species, and array 'dg' must have a length as great as the total number of reactions. This method only computes 'dg' for the reversible reactions, and the entries of 'dg' for the irreversible reactions are unaltered. This is primarily designed for use in calculating reverse rate coefficients from thermochemistry for reversible reactions.
Definition at line 403 of file Kinetics.cpp.
References Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, and Kinetics::nReactions().
Referenced by BulkKinetics::applyEquilibriumConstants_ddT(), and InterfaceKinetics::updateKc().
getDeltaGibbs()
virtual void getDeltaGibbs (doublereal * deltaG) inline virtual
Return the vector of values for the reaction Gibbs free energy change.
(virtual from Kinetics.h) These values depend upon the concentration of the solution.
units = J kmol-1
Parameters
deltaG Output vector of deltaG's for reactions Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 440 of file Kinetics.h.
getDeltaElectrochemPotentials()
virtual void getDeltaElectrochemPotentials (doublereal * deltaM) inline virtual
Return the vector of values for the reaction electrochemical free energy change.
These values depend upon the concentration of the solution and the voltage of the phases
units = J kmol-1
Parameters
deltaM Output vector of deltaM's for reactions Length: nReactions().
Reimplemented in InterfaceKinetics.
Definition at line 455 of file Kinetics.h.
getDeltaEnthalpy()
virtual void getDeltaEnthalpy (doublereal * deltaH) inline virtual
Return the vector of values for the reactions change in enthalpy.
These values depend upon the concentration of the solution.
units = J kmol-1
Parameters
deltaH Output vector of deltaH's for reactions Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 468 of file Kinetics.h.
getDeltaEntropy()
virtual void getDeltaEntropy (doublereal * deltaS) inline virtual
Return the vector of values for the reactions change in entropy.
These values depend upon the concentration of the solution.
units = J kmol-1 Kelvin-1
Parameters
deltaS Output vector of deltaS's for reactions Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 481 of file Kinetics.h.
getDeltaSSGibbs()
virtual void getDeltaSSGibbs (doublereal * deltaG) inline virtual
Return the vector of values for the reaction standard state Gibbs free energy change.
These values don't depend upon the concentration of the solution.
units = J kmol-1
Parameters
deltaG Output vector of ss deltaG's for reactions Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 495 of file Kinetics.h.
getDeltaSSEnthalpy()
virtual void getDeltaSSEnthalpy (doublereal * deltaH) inline virtual
Return the vector of values for the change in the standard state enthalpies of reaction.
These values don't depend upon the concentration of the solution.
units = J kmol-1
Parameters
deltaH Output vector of ss deltaH's for reactions Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 509 of file Kinetics.h.
getDeltaSSEntropy()
virtual void getDeltaSSEntropy (doublereal * deltaS) inline virtual
Return the vector of values for the change in the standard state entropies for each reaction.
These values don't depend upon the concentration of the solution.
units = J kmol-1 Kelvin-1
Parameters
deltaS Output vector of ss deltaS's for reactions Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 523 of file Kinetics.h.
getThirdBodyConcentrations()
virtual void getThirdBodyConcentrations (double * concm) inline virtual
Return a vector of values of effective concentrations of third-body collision partners of any reaction.
Entries for reactions not involving third-body collision partners are not defined and set to not-a-number.
Parameters
concm Output vector of effective third-body concentrations. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 535 of file Kinetics.h.
References Kinetics::kineticsType().
thirdBodyConcentrations()
virtual const vector_fp & thirdBodyConcentrations () const inline virtual
Provide direct access to current third-body concentration values.
See also
getThirdBodyConcentrations.
Reimplemented in BulkKinetics.
Definition at line 545 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by FalloffData::update().
getCreationRates()
void getCreationRates (doublereal * cdot) virtual
Species creation rates [kmol/m^3/s or kmol/m^2/s].
Return the species creation rates in array cdot, which must be dimensioned at least as large as the total number of species in all phases.
See also
nTotalSpecies.
Parameters
cdot Output vector of creation rates. Length: m_kk.
Definition at line 412 of file Kinetics.cpp.
References Kinetics::m_kk, Kinetics::m_productStoich, Kinetics::m_reactantStoich, Kinetics::m_ropf, and Kinetics::m_ropr.
getDestructionRates()
void getDestructionRates (doublereal * ddot) virtual
Species destruction rates [kmol/m^3/s or kmol/m^2/s].
Return the species destruction rates in array ddot, which must be dimensioned at least as large as the total number of species.
See also
nTotalSpecies.
Parameters
ddot Output vector of destruction rates. Length: m_kk.
Definition at line 426 of file Kinetics.cpp.
References Kinetics::m_kk, Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, Kinetics::m_ropf, and Kinetics::m_ropr.
getNetProductionRates()
void getNetProductionRates (doublereal * wdot) virtual
Species net production rates [kmol/m^3/s or kmol/m^2/s].
Return the species net production rates (creation - destruction) in array wdot, which must be dimensioned at least as large as the total number of species.
See also
nTotalSpecies.
Parameters
wdot Output vector of net production rates. Length: m_kk.
Definition at line 437 of file Kinetics.cpp.
References Kinetics::m_kk, Kinetics::m_productStoich, Kinetics::m_reactantStoich, and Kinetics::m_ropnet.
Referenced by solveSP::calc_t(), ConstPressureMoleReactor::eval(), ConstPressureReactor::eval(), IdealGasConstPressureMoleReactor::eval(), IdealGasConstPressureReactor::eval(), IdealGasMoleReactor::eval(), IdealGasReactor::eval(), MoleReactor::eval(), Reactor::eval(), ReactingSurf1D::eval(), FlowReactor::evalDae(), MoleReactor::evalSurfaces(), Reactor::evalSurfaces(), solveSP::fun_eval(), FlowReactor::getStateDae(), StFlow::getWdot(), InterfaceKinetics::interfaceCurrent(), IdealGasConstPressureMoleReactor::jacobian(), and IdealGasMoleReactor::jacobian().
getDerivativeSettings()
virtual void getDerivativeSettings (AnyMap & settings) const inline virtual
Retrieve derivative settings.
Parameters
settings AnyMap containing settings determining derivative evaluation.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 626 of file Kinetics.h.
References Kinetics::kineticsType().
setDerivativeSettings()
virtual void setDerivativeSettings (const AnyMap & settings) inline virtual
Set/modify derivative settings.
Parameters
settings AnyMap containing settings determining derivative evaluation.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 637 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Reactor::setDerivativeSettings().
getFwdRateConstants_ddT()
virtual void getFwdRateConstants_ddT (double * dkfwd) inline virtual
Calculate derivatives for forward rate constants with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] dkfwd Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 648 of file Kinetics.h.
References Kinetics::kineticsType().
getFwdRateConstants_ddP()
virtual void getFwdRateConstants_ddP (double * dkfwd) inline virtual
Calculate derivatives for forward rate constants with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] dkfwd Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 659 of file Kinetics.h.
References Kinetics::kineticsType().
getFwdRateConstants_ddC()
virtual void getFwdRateConstants_ddC (double * dkfwd) inline virtual
Calculate derivatives for forward rate constants with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] dkfwd Output vector of derivatives. Length: nReactions().
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 673 of file Kinetics.h.
References Kinetics::kineticsType().
getFwdRatesOfProgress_ddT()
virtual void getFwdRatesOfProgress_ddT (double * drop) inline virtual
Calculate derivatives for forward rates-of-progress with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 684 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getCreationRates_ddT(), and Kinetics::getDestructionRates_ddT().
getFwdRatesOfProgress_ddP()
virtual void getFwdRatesOfProgress_ddP (double * drop) inline virtual
Calculate derivatives for forward rates-of-progress with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 695 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getCreationRates_ddP(), and Kinetics::getDestructionRates_ddP().
getFwdRatesOfProgress_ddC()
virtual void getFwdRatesOfProgress_ddC (double * drop) inline virtual
Calculate derivatives for forward rates-of-progress with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 709 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getCreationRates_ddC(), and Kinetics::getDestructionRates_ddC().
fwdRatesOfProgress_ddX()
virtual Eigen::SparseMatrix< double > fwdRatesOfProgress_ddX () inline virtual
Calculate derivatives for forward rates-of-progress with respect to species mole fractions at constant temperature, pressure and molar concentration.
The method returns a matrix with nReactions rows and nTotalSpecies columns. For a derivative with respect to \(X_i\), all other \(X_j\) are held constant, rather than enforcing \(\sum X_j = 1\).
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 726 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::creationRates_ddX(), and Kinetics::destructionRates_ddX().
fwdRatesOfProgress_ddCi()
virtual Eigen::SparseMatrix< double > fwdRatesOfProgress_ddCi () inline virtual
Calculate derivatives for forward rates-of-progress with respect to species concentration at constant temperature, pressure and remaining species concentrations.
The method returns a matrix with nReactions rows and nTotalSpecies columns. For a derivative with respect to \(c_i\), all other \(c_j\) are held constant.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Since
New in Cantera 3.0.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 746 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::creationRates_ddCi(), and Kinetics::destructionRates_ddCi().
getRevRatesOfProgress_ddT()
virtual void getRevRatesOfProgress_ddT (double * drop) inline virtual
Calculate derivatives for reverse rates-of-progress with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 757 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getCreationRates_ddT(), and Kinetics::getDestructionRates_ddT().
getRevRatesOfProgress_ddP()
virtual void getRevRatesOfProgress_ddP (double * drop) inline virtual
Calculate derivatives for reverse rates-of-progress with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 768 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getCreationRates_ddP(), and Kinetics::getDestructionRates_ddP().
getRevRatesOfProgress_ddC()
virtual void getRevRatesOfProgress_ddC (double * drop) inline virtual
Calculate derivatives for reverse rates-of-progress with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 782 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getCreationRates_ddC(), and Kinetics::getDestructionRates_ddC().
revRatesOfProgress_ddX()
virtual Eigen::SparseMatrix< double > revRatesOfProgress_ddX () inline virtual
Calculate derivatives for reverse rates-of-progress with respect to species mole fractions at constant temperature, pressure and molar concentration.
The method returns a matrix with nReactions rows and nTotalSpecies columns. For a derivative with respect to \(X_i\), all other \(X_j\) are held constant, rather than enforcing \(\sum X_j = 1\).
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 799 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::creationRates_ddX(), and Kinetics::destructionRates_ddX().
revRatesOfProgress_ddCi()
virtual Eigen::SparseMatrix< double > revRatesOfProgress_ddCi () inline virtual
Calculate derivatives for forward rates-of-progress with respect to species concentration at constant temperature, pressure and remaining species concentrations.
The method returns a matrix with nReactions rows and nTotalSpecies columns. For a derivative with respect to \(c_i\), all other \(c_j\) are held constant.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Since
New in Cantera 3.0.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 819 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::creationRates_ddCi(), and Kinetics::destructionRates_ddCi().
getNetRatesOfProgress_ddT()
virtual void getNetRatesOfProgress_ddT (double * drop) inline virtual
Calculate derivatives for net rates-of-progress with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 830 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getNetProductionRates_ddT().
getNetRatesOfProgress_ddP()
virtual void getNetRatesOfProgress_ddP (double * drop) inline virtual
Calculate derivatives for net rates-of-progress with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Reimplemented in BulkKinetics.
Definition at line 841 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getNetProductionRates_ddP().
getNetRatesOfProgress_ddC()
virtual void getNetRatesOfProgress_ddC (double * drop) inline virtual
Calculate derivatives for net rates-of-progress with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] drop Output vector of derivatives. Length: nReactions().
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 855 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::getNetProductionRates_ddC().
netRatesOfProgress_ddX()
virtual Eigen::SparseMatrix< double > netRatesOfProgress_ddX () inline virtual
Calculate derivatives for net rates-of-progress with respect to species mole fractions at constant temperature, pressure and molar concentration.
The method returns a matrix with nReactions rows and nTotalSpecies columns. For a derivative with respect to \(X_i\), all other \(X_j\) are held constant, rather than enforcing \(\sum X_j = 1\).
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented in BulkKinetics.
Definition at line 872 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::netProductionRates_ddX().
netRatesOfProgress_ddCi()
virtual Eigen::SparseMatrix< double > netRatesOfProgress_ddCi () inline virtual
Calculate derivatives for net rates-of-progress with respect to species concentration at constant temperature, pressure, and remaining species concentrations.
The method returns a matrix with nReactions rows and nTotalSpecies columns. For a derivative with respect to \(c_i\), all other \(c_j\) are held constant.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Since
New in Cantera 3.0.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 892 of file Kinetics.h.
References Kinetics::kineticsType().
Referenced by Kinetics::netProductionRates_ddCi().
getCreationRates_ddT()
void getCreationRates_ddT (double * dwdot)
Calculate derivatives for species creation rates with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Definition at line 448 of file Kinetics.cpp.
References Kinetics::getFwdRatesOfProgress_ddT(), Kinetics::getRevRatesOfProgress_ddT(), Kinetics::m_kk, Kinetics::m_productStoich, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::nReactions(), and StoichManagerN::stoichCoeffs().
getCreationRates_ddP()
void getCreationRates_ddP (double * dwdot)
Calculate derivatives for species creation rates with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Definition at line 460 of file Kinetics.cpp.
References Kinetics::getFwdRatesOfProgress_ddP(), Kinetics::getRevRatesOfProgress_ddP(), Kinetics::m_kk, Kinetics::m_productStoich, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::nReactions(), and StoichManagerN::stoichCoeffs().
getCreationRates_ddC()
void getCreationRates_ddC (double * dwdot)
Calculate derivatives for species creation rates with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 472 of file Kinetics.cpp.
References Kinetics::getFwdRatesOfProgress_ddC(), Kinetics::getRevRatesOfProgress_ddC(), Kinetics::m_kk, Kinetics::m_productStoich, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::nReactions(), and StoichManagerN::stoichCoeffs().
creationRates_ddX()
Eigen::SparseMatrix< double > creationRates_ddX ()
Calculate derivatives for species creation rates with respect to species mole fractions at constant temperature, pressure and molar concentration.
The method returns a matrix with nTotalSpecies rows and nTotalSpecies columns. For a derivative with respect to \(X_i\), all other \(X_j\) are held constant, rather than enforcing \(\sum X_j = 1\).
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 484 of file Kinetics.cpp.
References Kinetics::fwdRatesOfProgress_ddX(), Kinetics::m_productStoich, Kinetics::m_reactantStoich, Kinetics::revRatesOfProgress_ddX(), and StoichManagerN::stoichCoeffs().
creationRates_ddCi()
Eigen::SparseMatrix< double > creationRates_ddCi ()
Calculate derivatives for species creation rates with respect to species concentration at constant temperature, pressure, and concentration of all other species.
The method returns a matrix with nTotalSpecies rows and nTotalSpecies columns. For a derivative with respect to \(c_i\), all other \(c_j\) are held constant.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Since
New in Cantera 3.0.
Definition at line 494 of file Kinetics.cpp.
References Kinetics::fwdRatesOfProgress_ddCi(), Kinetics::m_productStoich, Kinetics::m_reactantStoich, Kinetics::revRatesOfProgress_ddCi(), and StoichManagerN::stoichCoeffs().
getDestructionRates_ddT()
void getDestructionRates_ddT (double * dwdot)
Calculate derivatives for species destruction rates with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Definition at line 504 of file Kinetics.cpp.
References Kinetics::getFwdRatesOfProgress_ddT(), Kinetics::getRevRatesOfProgress_ddT(), Kinetics::m_kk, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, Kinetics::nReactions(), and StoichManagerN::stoichCoeffs().
getDestructionRates_ddP()
void getDestructionRates_ddP (double * dwdot)
Calculate derivatives for species destruction rates with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Definition at line 516 of file Kinetics.cpp.
References Kinetics::getFwdRatesOfProgress_ddP(), Kinetics::getRevRatesOfProgress_ddP(), Kinetics::m_kk, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, Kinetics::nReactions(), and StoichManagerN::stoichCoeffs().
getDestructionRates_ddC()
void getDestructionRates_ddC (double * dwdot)
Calculate derivatives for species destruction rates with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 528 of file Kinetics.cpp.
References Kinetics::getFwdRatesOfProgress_ddC(), Kinetics::getRevRatesOfProgress_ddC(), Kinetics::m_kk, Kinetics::m_rbuf, Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, Kinetics::nReactions(), and StoichManagerN::stoichCoeffs().
destructionRates_ddX()
Eigen::SparseMatrix< double > destructionRates_ddX ()
Calculate derivatives for species destruction rates with respect to species mole fractions at constant temperature, pressure and molar concentration.
The method returns a matrix with nTotalSpecies rows and nTotalSpecies columns. For a derivative with respect to \(X_i\), all other \(X_j\) are held constant, rather than enforcing \(\sum X_j = 1\).
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 540 of file Kinetics.cpp.
References Kinetics::fwdRatesOfProgress_ddX(), Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, Kinetics::revRatesOfProgress_ddX(), and StoichManagerN::stoichCoeffs().
destructionRates_ddCi()
Eigen::SparseMatrix< double > destructionRates_ddCi ()
Calculate derivatives for species destruction rates with respect to species concentration at constant temperature, pressure, and concentration of all other species.
The method returns a matrix with nTotalSpecies rows and nTotalSpecies columns. For a derivative with respect to \(c_i\), all other \(c_j\) are held constant.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Since
New in Cantera 3.0.
Definition at line 550 of file Kinetics.cpp.
References Kinetics::fwdRatesOfProgress_ddCi(), Kinetics::m_reactantStoich, Kinetics::m_revProductStoich, Kinetics::revRatesOfProgress_ddCi(), and StoichManagerN::stoichCoeffs().
getNetProductionRates_ddT()
void getNetProductionRates_ddT (double * dwdot)
Calculate derivatives for species net production rates with respect to temperature at constant pressure, molar concentration and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Definition at line 560 of file Kinetics.cpp.
References Kinetics::getNetRatesOfProgress_ddT(), Kinetics::m_kk, Kinetics::m_rbuf, Kinetics::m_stoichMatrix, and Kinetics::nReactions().
getNetProductionRates_ddP()
void getNetProductionRates_ddP (double * dwdot)
Calculate derivatives for species net production rates with respect to pressure at constant temperature, molar concentration and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Definition at line 568 of file Kinetics.cpp.
References Kinetics::getNetRatesOfProgress_ddP(), Kinetics::m_kk, Kinetics::m_rbuf, Kinetics::m_stoichMatrix, and Kinetics::nReactions().
getNetProductionRates_ddC()
void getNetProductionRates_ddC (double * dwdot)
Calculate derivatives for species net production rates with respect to molar concentration at constant temperature, pressure and mole fractions.
Parameters
[out] dwdot Output vector of derivatives. Length: m_kk.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 576 of file Kinetics.cpp.
References Kinetics::getNetRatesOfProgress_ddC(), Kinetics::m_kk, Kinetics::m_rbuf, Kinetics::m_stoichMatrix, and Kinetics::nReactions().
netProductionRates_ddX()
Eigen::SparseMatrix< double > netProductionRates_ddX ()
Calculate derivatives for species net production rates with respect to species mole fractions at constant temperature, pressure and molar concentration.
The method returns a matrix with nTotalSpecies rows and nTotalSpecies columns. For a derivative with respect to \(X_i\), all other \(X_j\) are held constant, rather than enforcing \(\sum X_j = 1\).
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 584 of file Kinetics.cpp.
References Kinetics::m_stoichMatrix, and Kinetics::netRatesOfProgress_ddX().
netProductionRates_ddCi()
Eigen::SparseMatrix< double > netProductionRates_ddCi ()
Calculate derivatives for species net production rates with respect to species concentration at constant temperature, pressure, and concentration of all other species.
The method returns a matrix with nTotalSpecies rows and nTotalSpecies columns. For a derivative with respect to \(c_i\), all other \(c_j\) are held constant.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Since
New in Cantera 3.0.
Definition at line 589 of file Kinetics.cpp.
References Kinetics::m_stoichMatrix, and Kinetics::netRatesOfProgress_ddCi().
Referenced by IdealGasConstPressureMoleReactor::jacobian(), and IdealGasMoleReactor::jacobian().
reactantStoichCoeff()
double reactantStoichCoeff (size_t k, size_t i) const virtual
Stoichiometric coefficient of species k as a reactant in reaction i.
Parameters
k kinetic species index
i reaction index
Definition at line 336 of file Kinetics.cpp.
References Kinetics::m_reactantStoich, and StoichManagerN::stoichCoeffs().
reactantStoichCoeffs()
Eigen::SparseMatrix< double > reactantStoichCoeffs () const inline
Stoichiometric coefficient matrix for reactants.
Definition at line 1072 of file Kinetics.h.
References Kinetics::m_reactantStoich, and StoichManagerN::stoichCoeffs().
productStoichCoeff()
double productStoichCoeff (size_t k, size_t i) const virtual
Stoichiometric coefficient of species k as a product in reaction i.
Parameters
k kinetic species index
i reaction index
Definition at line 341 of file Kinetics.cpp.
References Kinetics::m_productStoich, and StoichManagerN::stoichCoeffs().
productStoichCoeffs()
Eigen::SparseMatrix< double > productStoichCoeffs () const inline
Stoichiometric coefficient matrix for products.
Definition at line 1087 of file Kinetics.h.
References Kinetics::m_productStoich, and StoichManagerN::stoichCoeffs().
revProductStoichCoeffs()
Eigen::SparseMatrix< double > revProductStoichCoeffs () const inline
Stoichiometric coefficient matrix for products of reversible reactions.
Definition at line 1094 of file Kinetics.h.
References Kinetics::m_revProductStoich, and StoichManagerN::stoichCoeffs().
reactantOrder()
virtual doublereal reactantOrder (size_t k, size_t i) const inline virtual
Reactant order of species k in reaction i.
This is the nominal order of the activity concentration in determining the forward rate of progress of the reaction
Parameters
k kinetic species index
i reaction index
Definition at line 1106 of file Kinetics.h.
productOrder()
virtual doublereal productOrder (int k, int i) const inline virtual
product Order of species k in reaction i.
This is the nominal order of the activity concentration of species k in determining the reverse rate of progress of the reaction i
For irreversible reactions, this will all be zero.
Parameters
k kinetic species index
i reaction index
Definition at line 1120 of file Kinetics.h.
getActivityConcentrations()
virtual void getActivityConcentrations (doublereal *const conc) inline virtual
Get the vector of activity concentrations used in the kinetics object.
Parameters
[out] conc Vector of activity concentrations. Length is equal to the number of species in the kinetics object
Reimplemented in InterfaceKinetics.
Definition at line 1129 of file Kinetics.h.
reactionType()
std::string reactionType (size_t i) const virtual
String specifying the type of reaction.
Parameters
i reaction index
Since
Method returned magic number prior to Cantera 3.0.
Deprecated:
To be removed after Cantera 3.0. Replace with kin->reaction(i)->type()
Definition at line 346 of file Kinetics.cpp.
References Kinetics::m_reactions, and Cantera::warn_deprecated().
Referenced by Kinetics::reactionTypeStr().
reactionTypeStr()
std::string reactionTypeStr (size_t i) const virtual
String specifying the type of reaction.
Parameters
i reaction index
Deprecated:
To be removed after Cantera 3.0.
Definition at line 351 of file Kinetics.cpp.
References Kinetics::reactionType(), and Cantera::warn_deprecated().
isReversible()
virtual bool isReversible (size_t i) inline virtual
True if reaction i has been declared to be reversible.
If isReversible(i) is false, then the reverse rate of progress for reaction i is always zero.
Parameters
i reaction index
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 1158 of file Kinetics.h.
reactionString()
std::string reactionString (size_t i) const
Return a string representing the reaction.
Parameters
i reaction index
Deprecated:
To be removed after Cantera 3.0. Replace with kin->reaction(i)->equation().
Definition at line 356 of file Kinetics.cpp.
References Kinetics::m_reactions, and Cantera::warn_deprecated().
reactantString()
std::string reactantString (size_t i) const
Returns a string containing the reactants side of the reaction equation.
Deprecated:
To be removed after Cantera 3.0. Replace with kin->reaction(i)->reactantString()
Definition at line 363 of file Kinetics.cpp.
References Kinetics::m_reactions, and Cantera::warn_deprecated().
productString()
std::string productString (size_t i) const
Returns a string containing the products side of the reaction equation.
Deprecated:
To be removed after Cantera 3.0. Replace with kin->reaction(i)->productString()
Definition at line 370 of file Kinetics.cpp.
References Kinetics::m_reactions, and Cantera::warn_deprecated().
getFwdRateConstants()
virtual void getFwdRateConstants (double * kfwd) inline virtual
Return the forward rate constants.
The computed values include all temperature-dependent and pressure-dependent contributions. By default, third-body concentrations are only considered if they are part of the reaction rate definition; for a legacy implementation that includes third-body concentrations see Cantera::use_legacy_rate_constants(). Length is the number of reactions. Units are a combination of kmol, m^3 and s, that depend on the rate expression for the reaction.
Parameters
kfwd Output vector containing the forward reaction rate constants. Length: nReactions().
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 1194 of file Kinetics.h.
getRevRateConstants()
virtual void getRevRateConstants (double * krev, bool doIrreversible = false) inline virtual
Return the reverse rate constants.
The computed values include all temperature-dependent and pressure-dependent contributions. By default, third-body concentrations are only considered if they are part of the reaction rate definition; for a legacy implementation that includes third-body concentrations see Cantera::use_legacy_rate_constants(). Length is the number of reactions. Units are a combination of kmol, m^3 and s, that depend on the rate expression for the reaction. Note, this routine will return rate constants for irreversible reactions if the default for doIrreversible is overridden.
Parameters
krev Output vector of reverse rate constants
doIrreversible boolean indicating whether irreversible reactions should be included.
Reimplemented in BulkKinetics, and InterfaceKinetics.
Definition at line 1214 of file Kinetics.h.
addThermo()
void addThermo (shared_ptr< ThermoPhase > thermo) virtual
Add a phase to the kinetics manager object.
This must be done before the function init() is called or before any reactions are input. The following fields are updated:
m_start -> vector of integers, containing the starting position of the species for each phase in the kinetics mechanism.
m_rxnphase -> index of the phase where reactions occur, which is the lowest- dimensional phase in the system, for example the surface in a surface mechanism.
m_thermo -> vector of pointers to ThermoPhase phases that participate in the kinetics mechanism.
m_phaseindex -> map containing the std::string id of each ThermoPhase phase as a key and the index of the phase within the kinetics manager object as the value.
Parameters
thermo Reference to the ThermoPhase to be added.
Since
New in Cantera 3.0. Replaces addPhase.
Reimplemented in InterfaceKinetics.
Definition at line 594 of file Kinetics.cpp.
References Kinetics::m_mindim, Kinetics::m_phaseindex, Kinetics::m_rxnphase, Kinetics::m_sharedThermo, Kinetics::m_surfphase, Kinetics::m_thermo, Phase::nDim(), Kinetics::nPhases(), Kinetics::resizeSpecies(), Kinetics::thermo(), ThermoPhase::type(), and Cantera::warn_deprecated().
Referenced by InterfaceKinetics::addThermo().
addPhase()
void addPhase (ThermoPhase & thermo) virtual
See also
Kinetics::addThermo(shared_ptr<ThermoPhase>)
Deprecated:
To be removed after Cantera 3.0. Replaced by addThermo pointer.
Reimplemented in InterfaceKinetics.
Definition at line 618 of file Kinetics.cpp.
References Kinetics::kineticsType(), Kinetics::m_mindim, Kinetics::m_phaseindex, Kinetics::m_rxnphase, Kinetics::m_surfphase, Kinetics::m_thermo, Phase::nDim(), Kinetics::nPhases(), Kinetics::resizeSpecies(), Kinetics::thermo(), ThermoPhase::type(), and Cantera::warn_deprecated().
Referenced by InterfaceKinetics::addPhase(), BulkKinetics::BulkKinetics(), and GasKinetics::GasKinetics().
init()
virtual void init () inline virtual
Prepare the class for the addition of reactions, after all phases have been added.
This method is called automatically when the first reaction is added. It needs to be called directly only in the degenerate case where there are no reactions. The base class method does nothing, but derived classes may use this to perform any initialization (allocating arrays, etc.) that requires knowing the phases.
Reimplemented in InterfaceKinetics.
Definition at line 1257 of file Kinetics.h.
Referenced by Kinetics::addReaction().
parameters()
AnyMap parameters ()
Return the parameters for a phase definition which are needed to reconstruct an identical object using the newKinetics function.
This excludes the reaction definitions, which are handled separately.
Definition at line 639 of file Kinetics.cpp.
References Kinetics::kineticsType(), and Kinetics::nReactions().
resizeSpecies()
void resizeSpecies () virtual
Resize arrays with sizes that depend on the total number of species.
Automatically called before adding each Reaction and Phase.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 652 of file Kinetics.cpp.
References Kinetics::m_kk, Kinetics::m_start, Kinetics::m_thermo, and Kinetics::nPhases().
Referenced by Kinetics::addPhase(), Kinetics::addReaction(), Kinetics::addThermo(), InterfaceKinetics::resizeSpecies(), and BulkKinetics::resizeSpecies().
addReaction()
bool addReaction (shared_ptr< Reaction > r, bool resize = true) virtual
Add a single reaction to the mechanism.
Derived classes should call the base class method in addition to handling their own specialized behavior.
Parameters
r Pointer to the Reaction object to be added.
resize If true, resizeReactions is called after reaction is added.
Returns
true if the reaction is added or false if it was skipped
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 664 of file Kinetics.cpp.
References StoichManagerN::add(), Kinetics::init(), Kinetics::kineticsSpeciesIndex(), Kinetics::m_delta_gibbs0, Kinetics::m_dH, Kinetics::m_kk, Kinetics::m_perturb, Kinetics::m_productStoich, Kinetics::m_reactantStoich, Kinetics::m_reactions, Kinetics::m_ready, Kinetics::m_revProductStoich, Kinetics::m_rfn, Kinetics::m_rkcn, Kinetics::m_ropf, Kinetics::m_ropnet, Kinetics::m_ropr, Kinetics::nReactions(), Kinetics::resizeReactions(), and Kinetics::resizeSpecies().
Referenced by InterfaceKinetics::addReaction(), BulkKinetics::addReaction(), and Cantera::addReactions().
modifyReaction()
void modifyReaction (size_t i, shared_ptr< Reaction > rNew) virtual
Modify the rate expression associated with a reaction.
The stoichiometric equation, type of the reaction, reaction orders, third body efficiencies, reversibility, etc. must be unchanged.
Parameters
i Index of the reaction to be modified
rNew Reaction with the new rate expressions
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 752 of file Kinetics.cpp.
References Kinetics::checkReactionIndex(), and Kinetics::m_reactions.
Referenced by InterfaceKinetics::modifyReaction(), and BulkKinetics::modifyReaction().
reaction() [1/2]
shared_ptr< Reaction > reaction (size_t i)
Return the Reaction object for reaction i.
Changes to this object do not affect the Kinetics object until the modifyReaction function is called.
Definition at line 783 of file Kinetics.cpp.
References Kinetics::checkReactionIndex(), and Kinetics::m_reactions.
Referenced by ReactorSurface::addSensitivityReaction(), and Reactor::addSensitivityReaction().
reaction() [2/2]
shared_ptr< const Reaction > reaction (size_t i) const
Definition at line 789 of file Kinetics.cpp.
skipUndeclaredSpecies() [1/2]
void skipUndeclaredSpecies (bool skip) inline
Determine behavior when adding a new reaction that contains species not defined in any of the phases associated with this kinetics manager.
If set to true, the reaction will silently be ignored. If false, (the default) an exception will be raised.
Definition at line 1303 of file Kinetics.h.
References Kinetics::m_skipUndeclaredSpecies.
Referenced by Cantera::addReactions(), Reaction::checkSpecies(), and ThirdBody::checkSpecies().
skipUndeclaredSpecies() [2/2]
bool skipUndeclaredSpecies () const inline
Definition at line 1306 of file Kinetics.h.
skipUndeclaredThirdBodies() [1/2]
void skipUndeclaredThirdBodies (bool skip) inline
Determine behavior when adding a new reaction that contains third-body efficiencies for species not defined in any of the phases associated with this kinetics manager.
If set to true, the given third-body efficiency will be ignored. If false, (the default) an exception will be raised.
Definition at line 1315 of file Kinetics.h.
References Kinetics::m_skipUndeclaredThirdBodies.
Referenced by Cantera::addReactions(), and ThirdBody::checkSpecies().
skipUndeclaredThirdBodies() [2/2]
bool skipUndeclaredThirdBodies () const inline
Definition at line 1318 of file Kinetics.h.
multiplier()
doublereal multiplier (size_t i) const inline
The current value of the multiplier for reaction i.
Parameters
i index of the reaction
Definition at line 1337 of file Kinetics.h.
References Kinetics::m_perturb.
Referenced by Reactor::applySensitivity(), and ReactorSurface::setSensitivityParameters().
setMultiplier()
virtual void setMultiplier (size_t i, doublereal f) inline virtual
Set the multiplier for reaction i to f.
Parameters
i index of the reaction
f value of the multiplier.
Reimplemented in InterfaceKinetics, and BulkKinetics.
Definition at line 1346 of file Kinetics.h.
References Kinetics::m_perturb.
Referenced by Reactor::applySensitivity(), Reactor::resetSensitivity(), ReactorSurface::resetSensitivityParameters(), InterfaceKinetics::setMultiplier(), BulkKinetics::setMultiplier(), and ReactorSurface::setSensitivityParameters().
invalidateCache()
virtual void invalidateCache () inline virtual
Definition at line 1350 of file Kinetics.h.
checkDuplicates()
std::pair< size_t, size_t > checkDuplicates (bool throw_err = true) const virtual
Check for unmarked duplicate reactions and unmatched marked duplicates.
If throw_err is true, then an exception will be thrown if either any unmarked duplicate reactions are found, or if any marked duplicate reactions do not have a matching duplicate reaction. If throw_err is false, the indices of the first pair of duplicate reactions found will be returned, or the index of the unmatched duplicate will be returned as both elements of the pair. If no unmarked duplicates or unmatched marked duplicate reactions are found, returns (npos, npos).
Definition at line 107 of file Kinetics.cpp.
References Kinetics::checkDuplicateStoich(), Reaction::duplicate, ThirdBody::efficiency(), Reaction::equation(), Reaction::input, Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), Kinetics::m_reactions, Cantera::npos, Kinetics::nTotalSpecies(), Reaction::products, Reaction::rate(), Reaction::reactants, Reaction::reversible, Reaction::thirdBody(), Reaction::type(), and Reaction::usesThirdBody().
Referenced by Cantera::addReactions().
selectPhase()
void selectPhase (const double * data, const ThermoPhase * phase, double * phase_data)
Takes as input an array of properties for all species in the mechanism and copies those values belonging to a particular phase to the output array.
Parameters
data Input data array.
phase Pointer to one of the phase objects participating in this reaction mechanism
phase_data Output array where the values for the the specified phase are to be written.
Deprecated:
Unused. To be removed after Cantera 3.0.
Definition at line 244 of file Kinetics.cpp.
References Kinetics::m_start, Kinetics::m_thermo, Kinetics::nPhases(), Phase::nSpecies(), and Cantera::warn_deprecated().
setRoot()
virtual void setRoot (std::shared_ptr< Solution > root) inline virtual
Set root Solution holding all phase information.
Definition at line 1382 of file Kinetics.h.
References Kinetics::m_root, and Kinetics::root().
root()
shared_ptr< Solution > root () const inline
Get the Solution object containing this Kinetics object and associated ThermoPhase objects.
Definition at line 1388 of file Kinetics.h.
References Kinetics::m_root.
Referenced by Kinetics::setRoot(), ReactionDataDelegator::update(), and ReactionRateDelegator::validate().
reactionEnthalpy()
double reactionEnthalpy (const Composition & reactants, const Composition & products) virtual
Calculate the reaction enthalpy of a reaction which has not necessarily been added into the Kinetics object.
Deprecated:
To be removed after Cantera 3.0
Definition at line 795 of file Kinetics.cpp.
References ThermoPhase::getPartialMolarEnthalpies(), Kinetics::kineticsSpeciesIndex(), Kinetics::m_start, Kinetics::nPhases(), Kinetics::nTotalSpecies(), Kinetics::thermo(), and Cantera::warn_deprecated().
updateROP()
virtual void updateROP () inline protected virtual
Reimplemented in InterfaceKinetics.
Definition at line 1403 of file Kinetics.h.
Member Data Documentation
m_cache
ValueCache m_cache protected
Cache for saved calculations within each Kinetics object.
Definition at line 1400 of file Kinetics.h.
m_reactantStoich
StoichManagerN m_reactantStoich protected
Stoichiometry manager for the reactants for each reaction.
Definition at line 1431 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::creationRates_ddCi(), Kinetics::creationRates_ddX(), Kinetics::destructionRates_ddCi(), Kinetics::destructionRates_ddX(), InterfaceKinetics::fwdRatesOfProgress_ddCi(), BulkKinetics::fwdRatesOfProgress_ddCi(), BulkKinetics::fwdRatesOfProgress_ddX(), Kinetics::getCreationRates(), Kinetics::getCreationRates_ddC(), Kinetics::getCreationRates_ddP(), Kinetics::getCreationRates_ddT(), Kinetics::getDestructionRates(), Kinetics::getDestructionRates_ddC(), Kinetics::getDestructionRates_ddP(), Kinetics::getDestructionRates_ddT(), BulkKinetics::getFwdRateConstants_ddC(), BulkKinetics::getFwdRatesOfProgress_ddC(), Kinetics::getNetProductionRates(), BulkKinetics::getNetRatesOfProgress_ddC(), Kinetics::getReactionDelta(), Kinetics::getRevReactionDelta(), InterfaceKinetics::netRatesOfProgress_ddCi(), BulkKinetics::netRatesOfProgress_ddCi(), BulkKinetics::netRatesOfProgress_ddX(), Kinetics::reactantStoichCoeff(), Kinetics::reactantStoichCoeffs(), Kinetics::resizeReactions(), and InterfaceKinetics::updateROP().
m_productStoich
StoichManagerN m_productStoich protected
Stoichiometry manager for the products for each reaction.
Definition at line 1434 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::creationRates_ddCi(), Kinetics::creationRates_ddX(), Kinetics::getCreationRates(), Kinetics::getCreationRates_ddC(), Kinetics::getCreationRates_ddP(), Kinetics::getCreationRates_ddT(), Kinetics::getNetProductionRates(), Kinetics::getReactionDelta(), Kinetics::productStoichCoeff(), Kinetics::productStoichCoeffs(), and Kinetics::resizeReactions().
m_revProductStoich
StoichManagerN m_revProductStoich protected
Stoichiometry manager for the products of reversible reactions.
Definition at line 1437 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::destructionRates_ddCi(), Kinetics::destructionRates_ddX(), Kinetics::getDestructionRates(), Kinetics::getDestructionRates_ddC(), Kinetics::getDestructionRates_ddP(), Kinetics::getDestructionRates_ddT(), BulkKinetics::getNetRatesOfProgress_ddC(), BulkKinetics::getRevRatesOfProgress_ddC(), Kinetics::getRevReactionDelta(), InterfaceKinetics::netRatesOfProgress_ddCi(), BulkKinetics::netRatesOfProgress_ddCi(), BulkKinetics::netRatesOfProgress_ddX(), Kinetics::resizeReactions(), Kinetics::revProductStoichCoeffs(), InterfaceKinetics::revRatesOfProgress_ddCi(), BulkKinetics::revRatesOfProgress_ddCi(), BulkKinetics::revRatesOfProgress_ddX(), and InterfaceKinetics::updateROP().
m_stoichMatrix
Eigen::SparseMatrix<double> m_stoichMatrix protected
Net stoichiometry (products - reactants)
Definition at line 1440 of file Kinetics.h.
Referenced by Kinetics::getNetProductionRates_ddC(), Kinetics::getNetProductionRates_ddP(), Kinetics::getNetProductionRates_ddT(), Kinetics::netProductionRates_ddCi(), Kinetics::netProductionRates_ddX(), and Kinetics::resizeReactions().
m_ready
bool m_ready = false protected
Boolean indicating whether Kinetics object is fully configured.
Definition at line 1444 of file Kinetics.h.
Referenced by Kinetics::addReaction(), BulkKinetics::addReaction(), and Kinetics::resizeReactions().
m_kk
size_t m_kk = 0 protected
The number of species in all of the phases that participate in this kinetics mechanism.
Definition at line 1448 of file Kinetics.h.
Referenced by InterfaceKinetics::addReaction(), Kinetics::addReaction(), BulkKinetics::addReaction(), Kinetics::checkSpeciesArraySize(), Kinetics::checkSpeciesIndex(), Kinetics::getCreationRates(), Kinetics::getCreationRates_ddC(), Kinetics::getCreationRates_ddP(), Kinetics::getCreationRates_ddT(), BulkKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), BulkKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), Kinetics::getDestructionRates(), Kinetics::getDestructionRates_ddC(), Kinetics::getDestructionRates_ddP(), Kinetics::getDestructionRates_ddT(), Kinetics::getNetProductionRates(), Kinetics::getNetProductionRates_ddC(), Kinetics::getNetProductionRates_ddP(), Kinetics::getNetProductionRates_ddT(), InterfaceKinetics::interfaceCurrent(), Kinetics::nTotalSpecies(), Kinetics::resizeReactions(), InterfaceKinetics::resizeSpecies(), Kinetics::resizeSpecies(), and BulkKinetics::resizeSpecies().
m_perturb
vector_fp m_perturb protected
Vector of perturbation factors for each reaction's rate of progress vector.
It is initialized to one.
Definition at line 1452 of file Kinetics.h.
Referenced by Kinetics::addReaction(), InterfaceKinetics::getFwdRateConstants(), Kinetics::multiplier(), Kinetics::setMultiplier(), and InterfaceKinetics::updateROP().
m_reactions
std::vector<shared_ptr<Reaction> > m_reactions protected
Vector of Reaction objects represented by this Kinetics manager.
Definition at line 1455 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::checkDuplicates(), Kinetics::modifyReaction(), Kinetics::nReactions(), Kinetics::productString(), Kinetics::reactantString(), Kinetics::reaction(), Kinetics::reactionString(), and Kinetics::reactionType().
m_thermo
std::vector<ThermoPhase*> m_thermo protected
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
For homogeneous kinetics applications, this vector will only have one entry. For interfacial reactions, this vector will consist of multiple entries; some of them will be surface phases, and the other ones will be bulk phases. The order that the objects are listed determines the order in which the species comprising each phase are listed in the source term vector, originating from the reaction mechanism.
Note that this kinetics object doesn't own these ThermoPhase objects and is not responsible for creating or deleting them.
Definition at line 1470 of file Kinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), Kinetics::addPhase(), Kinetics::addThermo(), InterfaceKinetics::getDeltaGibbs(), Kinetics::kineticsSpeciesIndex(), Kinetics::nPhases(), Kinetics::resizeSpecies(), Kinetics::selectPhase(), Kinetics::speciesPhase(), and Kinetics::thermo().
m_sharedThermo
vector<shared_ptr<ThermoPhase> > m_sharedThermo protected
vector of shared pointers,
See also
m_thermo
Todo:
replace m_thermo with shared version after Cantera 3.0
Definition at line 1474 of file Kinetics.h.
Referenced by Kinetics::addThermo(), and Kinetics::reactionPhase().
m_start
std::vector<size_t> m_start protected
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
Definition at line 1480 of file Kinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::interfaceCurrent(), Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), Kinetics::reactionEnthalpy(), Kinetics::resizeSpecies(), Kinetics::selectPhase(), Kinetics::speciesPhaseIndex(), and InterfaceKinetics::updateMu0().
m_phaseindex
std::map<std::string, size_t> m_phaseindex protected
Mapping of the phase name to the position of the phase within the kinetics object.
Positions start with the value of 1. The member function, phaseIndex() decrements by one before returning the index value, so that missing phases return -1.
Definition at line 1488 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::addThermo(), and Kinetics::phaseIndex().
m_surfphase
size_t m_surfphase = npos protected
Index in the list of phases of the one surface phase.
Deprecated:
To be removed after Cantera 3.0.
Definition at line 1492 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::addThermo(), and Kinetics::surfacePhaseIndex().
m_rxnphase
size_t m_rxnphase = npos protected
Phase Index where reactions are assumed to be taking place.
We calculate this by assuming that the phase with the lowest dimensionality is the phase where reactions are taking place.
Definition at line 1499 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::addThermo(), Kinetics::reactionPhase(), and Kinetics::reactionPhaseIndex().
m_mindim
size_t m_mindim = 4 protected
number of spatial dimensions of lowest-dimensional phase.
Definition at line 1502 of file Kinetics.h.
Referenced by Kinetics::addPhase(), and Kinetics::addThermo().
m_rfn
vector_fp m_rfn protected
Forward rate constant for each reaction.
Definition at line 1505 of file Kinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), Kinetics::addReaction(), BulkKinetics::calculateCompositionDerivatives(), BulkKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRateConstants(), BulkKinetics::getFwdRateConstants_ddC(), BulkKinetics::getFwdRateConstants_ddP(), BulkKinetics::getFwdRateConstants_ddT(), BulkKinetics::process_ddC(), BulkKinetics::process_ddP(), BulkKinetics::process_ddT(), and InterfaceKinetics::updateROP().
m_delta_gibbs0
vector_fp m_delta_gibbs0 protected
Delta G^0 for all reactions.
Definition at line 1508 of file Kinetics.h.
Referenced by Kinetics::addReaction(), and BulkKinetics::applyEquilibriumConstants_ddT().
m_rkcn
vector_fp m_rkcn protected
Reciprocal of the equilibrium constant in concentration units.
Definition at line 1511 of file Kinetics.h.
Referenced by Kinetics::addReaction(), BulkKinetics::applyEquilibriumConstants(), InterfaceKinetics::applyEquilibriumConstants(), BulkKinetics::getRevRateConstants(), InterfaceKinetics::getRevRateConstants(), InterfaceKinetics::updateKc(), and InterfaceKinetics::updateROP().
m_ropf
vector_fp m_ropf protected
Forward rate-of-progress for each reaction.
Definition at line 1514 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::getCreationRates(), Kinetics::getDestructionRates(), Kinetics::getFwdRatesOfProgress(), BulkKinetics::getFwdRatesOfProgress_ddC(), BulkKinetics::getFwdRatesOfProgress_ddP(), BulkKinetics::getFwdRatesOfProgress_ddT(), BulkKinetics::getNetRatesOfProgress_ddC(), and InterfaceKinetics::updateROP().
m_ropr
vector_fp m_ropr protected
Reverse rate-of-progress for each reaction.
Definition at line 1517 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::getCreationRates(), Kinetics::getDestructionRates(), BulkKinetics::getNetRatesOfProgress_ddC(), BulkKinetics::getNetRatesOfProgress_ddT(), Kinetics::getRevRatesOfProgress(), BulkKinetics::getRevRatesOfProgress_ddC(), BulkKinetics::getRevRatesOfProgress_ddP(), BulkKinetics::getRevRatesOfProgress_ddT(), and InterfaceKinetics::updateROP().
m_ropnet
vector_fp m_ropnet protected
Net rate-of-progress for each reaction.
Definition at line 1520 of file Kinetics.h.
Referenced by Kinetics::addReaction(), Kinetics::getNetProductionRates(), Kinetics::getNetRatesOfProgress(), BulkKinetics::getNetRatesOfProgress_ddP(), BulkKinetics::getNetRatesOfProgress_ddT(), InterfaceKinetics::getRevRateConstants(), and InterfaceKinetics::updateROP().
m_dH
vector_fp m_dH protected
The enthalpy change for each reaction to calculate Blowers-Masel rates.
Definition at line 1523 of file Kinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and Kinetics::addReaction().
m_rbuf
vector_fp m_rbuf protected
Buffer used for storage of intermediate reaction-specific results.
Definition at line 1526 of file Kinetics.h.
Referenced by Kinetics::getCreationRates_ddC(), Kinetics::getCreationRates_ddP(), Kinetics::getCreationRates_ddT(), InterfaceKinetics::getDeltaGibbs(), Kinetics::getDestructionRates_ddC(), Kinetics::getDestructionRates_ddP(), Kinetics::getDestructionRates_ddT(), Kinetics::getNetProductionRates_ddC(), Kinetics::getNetProductionRates_ddP(), Kinetics::getNetProductionRates_ddT(), and Kinetics::resizeReactions().
m_skipUndeclaredSpecies
bool m_skipUndeclaredSpecies = false protected
See skipUndeclaredSpecies()
Definition at line 1529 of file Kinetics.h.
Referenced by Kinetics::skipUndeclaredSpecies().
m_skipUndeclaredThirdBodies
bool m_skipUndeclaredThirdBodies = false protected
See skipUndeclaredThirdBodies()
Definition at line 1532 of file Kinetics.h.
Referenced by Kinetics::skipUndeclaredThirdBodies().
m_root
std::weak_ptr<Solution> m_root protected
reference to Solution
Definition at line 1535 of file Kinetics.h.
Referenced by Kinetics::root(), and Kinetics::setRoot().
The documentation for this class was generated from the following files:
Kinetics.h
Kinetics.cpp