Cantera: StickingCoverage Class Reference
StickingCoverage Class Reference
Base class for rate parameterizations that implement sticking coefficients.
#include <InterfaceRate.h>
Public Member Functions
void setStickingParameters (const AnyMap &node)
Perform object setup based on AnyMap node information.
void getStickingParameters (AnyMap &node) const
Store parameters needed to reconstruct an identical object.
bool motzWiseCorrection () const
Get flag indicating whether sticking rate uses the correction factor developed by Motz & Wise for reactions with high (near-unity) sticking coefficients.
void setMotzWiseCorrection (bool motz_wise)
Set flag for Motz & Wise correction factor.
string stickingSpecies () const
Get sticking species.
void setStickingSpecies (const string &stickingSpecies)
Set sticking species.
double stickingOrder ()
Get exponent applied to site density (sticking order)
void setStickingOrder (double order)
Set exponent applied to site density (sticking order)
double stickingWeight ()
Get the molecular weight of the sticking species.
void setStickingWeight (double weight)
Set the molecular weight of the sticking species.
void setContext (const Reaction &rxn, const Kinetics &kin)
Build rate-specific parameters based on Reaction and Kinetics context.
Public Member Functions inherited from InterfaceRateBase
void setParameters (const AnyMap &node)
Perform object setup based on AnyMap node information.
void getParameters (AnyMap &node) const
Store parameters needed to reconstruct an identical object.
void setCoverageDependencies (const AnyMap &dependencies, const UnitSystem &units=UnitSystem())
Set coverage dependencies based on AnyMap node information.
void getCoverageDependencies (AnyMap &dependencies, bool asVector=false) const
Store parameters needed to reconstruct coverage dependencies.
virtual void addCoverageDependence (const string &sp, double a, double m, const vector_fp &e)
Add a coverage dependency for species sp, with exponential dependence a, power-law exponent m, and activation energy dependence e, where e is in Kelvin, that is, energy divided by the molar gas constant.
bool exchangeCurrentDensityFormulation ()
Boolean indicating whether rate uses exchange current density formulation.
void setContext (const Reaction &rxn, const Kinetics &kin)
Build rate-specific parameters based on Reaction and Kinetics context.
void setSpecies (const vector< string > &species)
Set association with an ordered list of all species associated with a given Kinetics object.
void updateFromStruct (const InterfaceData &shared_data)
Update reaction rate parameters.
double voltageCorrection () const
Calculate modifications for the forward reaction rate for interfacial charge transfer reactions.
bool usesElectrochemistry ()
Boolean indicating whether rate uses electrochemistry.
double beta () const
Return the charge transfer beta parameter.
double siteDensity () const
Return site density [kmol/m^2].
void setSiteDensity (double siteDensity)
Set site density [kmol/m^2].
Protected Attributes
bool m_motzWise
boolean indicating whether Motz & Wise correction is used
bool m_explicitMotzWise
Correction cannot be overriden by default.
string m_stickingSpecies
string identifying sticking species
bool m_explicitSpecies
Boolean flag.
double m_surfaceOrder
exponent applied to site density term
double m_multiplier
multiplicative factor in rate expression
double m_factor
cached factor
Protected Attributes inherited from InterfaceRateBase
double m_siteDensity
Site density [kmol/m^2].
double m_acov
Coverage contribution to pre-exponential factor.
double m_ecov
Coverage contribution to activation energy.
double m_mcov
Coverage term in reaction rate.
bool m_chargeTransfer
Boolean indicating use of electrochemistry.
bool m_exchangeCurrentDensityFormulation
double m_beta
Electrochemistry only.
double m_deltaPotential_RT
Normalized electric potential energy change.
double m_deltaGibbs0_RT
Normalized standard state Gibbs free energy change.
double m_prodStandardConcentrations
Products of standard concentrations.
map< size_t, size_t > m_indices
Map from coverage dependencies stored in this object to the index of the coverage species in the Kinetics object.
vector< string > m_cov
Vector holding names of coverage species.
vector_fp m_ac
Vector holding coverage-specific exponential dependence.
vector< vector_fp > m_ec
Vector holding coverage-specific activation energy dependence as a 5-membered array of polynomial coeffcients starting from 0th-order to 4th-order coefficients.
vector< bool > m_lindep
Vector holding boolean for linear dependence.
vector_fp m_mc
Vector holding coverage-specific power-law exponents.
Detailed Description
Base class for rate parameterizations that implement sticking coefficients.
The StickingCoverage class enhances Coverage to accommodate sticking coefficients.
Definition at line 277 of file InterfaceRate.h.
Constructor & Destructor Documentation
StickingCoverage()
StickingCoverage ()
Definition at line 324 of file InterfaceRate.cpp.
Member Function Documentation
setStickingParameters()
void setStickingParameters (const AnyMap & node)
Perform object setup based on AnyMap node information.
Parameters
node Sticking coefficient parameters
Definition at line 335 of file InterfaceRate.cpp.
References AnyMap::getBool(), AnyMap::getString(), AnyMap::hasKey(), StickingCoverage::m_explicitMotzWise, StickingCoverage::m_explicitSpecies, StickingCoverage::m_motzWise, and StickingCoverage::m_stickingSpecies.
getStickingParameters()
void getStickingParameters (AnyMap & node) const
Store parameters needed to reconstruct an identical object.
Parameters
node Sticking coefficient parameters
Definition at line 343 of file InterfaceRate.cpp.
References StickingCoverage::m_explicitMotzWise, StickingCoverage::m_explicitSpecies, StickingCoverage::m_motzWise, and StickingCoverage::m_stickingSpecies.
motzWiseCorrection()
bool motzWiseCorrection () const inline
Get flag indicating whether sticking rate uses the correction factor developed by Motz & Wise for reactions with high (near-unity) sticking coefficients.
Defaults to 'false'.
Definition at line 293 of file InterfaceRate.h.
References StickingCoverage::m_motzWise.
setMotzWiseCorrection()
void setMotzWiseCorrection (bool motz_wise) inline
Set flag for Motz & Wise correction factor.
Definition at line 298 of file InterfaceRate.h.
References StickingCoverage::m_explicitMotzWise, and StickingCoverage::m_motzWise.
stickingSpecies()
string stickingSpecies () const inline
Get sticking species.
Definition at line 304 of file InterfaceRate.h.
References StickingCoverage::m_stickingSpecies.
Referenced by StickingCoverage::setStickingSpecies().
setStickingSpecies()
void setStickingSpecies (const string & stickingSpecies) inline
Set sticking species.
For reactions with multiple non-surface species, the sticking species needs to be explicitly identified. Note that species have to be specified prior to adding a reaction to a Kinetics object.
Definition at line 314 of file InterfaceRate.h.
References StickingCoverage::m_explicitSpecies, StickingCoverage::m_stickingSpecies, and StickingCoverage::stickingSpecies().
stickingOrder()
double stickingOrder () inline
Get exponent applied to site density (sticking order)
Definition at line 320 of file InterfaceRate.h.
References StickingCoverage::m_surfaceOrder.
setStickingOrder()
void setStickingOrder (double order) inline
Set exponent applied to site density (sticking order)
Note
This method is used for internal testing purposes only as the value is determined automatically by setContext.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 332 of file InterfaceRate.h.
References StickingCoverage::m_surfaceOrder.
stickingWeight()
double stickingWeight () inline
Get the molecular weight of the sticking species.
Definition at line 337 of file InterfaceRate.h.
References Cantera::GasConstant, StickingCoverage::m_multiplier, and Cantera::Pi.
setStickingWeight()
void setStickingWeight (double weight) inline
Set the molecular weight of the sticking species.
Note
This method is used for internal testing purposes only as the value is determined automatically by setContext.
Warning
This method is an experimental part of the Cantera API and may be changed or removed without notice.
Definition at line 349 of file InterfaceRate.h.
References Cantera::GasConstant, StickingCoverage::m_multiplier, and Cantera::Pi.
setContext()
void setContext (const Reaction & rxn, const Kinetics & kin)
Build rate-specific parameters based on Reaction and Kinetics context.
Parameters
rxn Reaction associated with the sticking coefficient
kin Kinetics object associated with the sticking coefficient Parameters can be accessed using the method stickingSpecies, stickingOrder and stickingWeight.
Definition at line 353 of file InterfaceRate.cpp.
References Reaction::equation(), Cantera::GasConstant, AnyMap::getBool(), Cantera::getValue(), Reaction::input, ThermoPhase::input(), Kinetics::kineticsSpeciesIndex(), StickingCoverage::m_explicitMotzWise, StickingCoverage::m_motzWise, StickingCoverage::m_multiplier, InterfaceRateBase::m_siteDensity, StickingCoverage::m_stickingSpecies, StickingCoverage::m_surfaceOrder, Phase::molecularWeight(), Reaction::orders, ThermoPhase::phaseOfMatter(), Cantera::Pi, Reaction::reactants, Kinetics::reactionPhaseIndex(), Phase::speciesIndex(), Kinetics::speciesPhaseIndex(), ThermoPhase::standardConcentration(), and Kinetics::thermo().
Member Data Documentation
m_motzWise
bool m_motzWise protected
boolean indicating whether Motz & Wise correction is used
Definition at line 361 of file InterfaceRate.h.
Referenced by StickingRate< RateType, DataType >::evalFromStruct(), StickingCoverage::getStickingParameters(), StickingCoverage::motzWiseCorrection(), StickingCoverage::setContext(), StickingCoverage::setMotzWiseCorrection(), and StickingCoverage::setStickingParameters().
m_explicitMotzWise
bool m_explicitMotzWise protected
Correction cannot be overriden by default.
Definition at line 362 of file InterfaceRate.h.
Referenced by StickingCoverage::getStickingParameters(), StickingCoverage::setContext(), StickingCoverage::setMotzWiseCorrection(), and StickingCoverage::setStickingParameters().
m_stickingSpecies
string m_stickingSpecies protected
string identifying sticking species
Definition at line 363 of file InterfaceRate.h.
Referenced by StickingCoverage::getStickingParameters(), StickingCoverage::setContext(), StickingCoverage::setStickingParameters(), StickingCoverage::setStickingSpecies(), and StickingCoverage::stickingSpecies().
m_explicitSpecies
bool m_explicitSpecies protected
Boolean flag.
Definition at line 364 of file InterfaceRate.h.
Referenced by StickingCoverage::getStickingParameters(), StickingCoverage::setStickingParameters(), and StickingCoverage::setStickingSpecies().
m_surfaceOrder
double m_surfaceOrder protected
exponent applied to site density term
Definition at line 365 of file InterfaceRate.h.
Referenced by StickingCoverage::setContext(), StickingCoverage::setStickingOrder(), StickingCoverage::stickingOrder(), and StickingRate< RateType, DataType >::updateFromStruct().
m_multiplier
double m_multiplier protected
multiplicative factor in rate expression
Definition at line 366 of file InterfaceRate.h.
Referenced by StickingRate< RateType, DataType >::evalFromStruct(), StickingCoverage::setContext(), StickingCoverage::setStickingWeight(), and StickingCoverage::stickingWeight().
m_factor
double m_factor protected
cached factor
Definition at line 367 of file InterfaceRate.h.
Referenced by StickingRate< RateType, DataType >::evalFromStruct(), and StickingRate< RateType, DataType >::updateFromStruct().
The documentation for this class was generated from the following files:
InterfaceRate.h
InterfaceRate.cpp