Cantera: ReactorNet Class Reference
ReactorNet Class Reference
Zero-dimensional reactor networks
A class representing a network of connected reactors.
#include <ReactorNet.h>
Public Member Functions
ReactorNet (const ReactorNet &)=delete
ReactorNet & operator= (const ReactorNet &)=delete
Public Member Functions inherited from FuncEval
virtual void eval (double t, double *y, double *ydot, double *p)
Evaluate the right-hand-side ODE function.
virtual void evalDae (double t, double *y, double *ydot, double *p, double *residual)
Evaluate the right-hand-side DAE function.
virtual void getConstraints (double *constraints)
Given a vector of length neq(), mark which variables should be considered algebraic constraints.
int evalNoThrow (double t, double *y, double *ydot)
Evaluate the right-hand side using return code to indicate status.
int evalDaeNoThrow (double t, double *y, double *ydot, double *residual)
Evaluate the right-hand side using return code to indicate status.
virtual void preconditionerSetup (double t, double *y, double gamma)
virtual void preconditionerSolve (double *rhs, double *output)
virtual void updatePreconditioner (double gamma)
Update the preconditioner based on already computed jacobian values.
int preconditioner_setup_nothrow (double t, double *y, double gamma)
int preconditioner_solve_nothrow (double *rhs, double *output)
virtual void getState (double *y)
Fill in the vector y with the current state of the system.
virtual void getStateDae (double *y, double *ydot)
Fill in the vectors y and ydot with the current state of the system.
virtual size_t neq ()=0
Number of equations.
virtual size_t nparams ()
Number of sensitivity parameters.
void suppressErrors (bool suppress)
Enable or disable suppression of errors when calling eval()
bool suppressErrors () const
Get current state of error suppression.
std::string getErrors () const
Return a string containing the text of any suppressed errors.
void clearErrors ()
Clear any previously-stored suppressed errors.
Methods to set up a simulation
std::vector< Reactor * > m_reactors
std::unique_ptr< Integrator > m_integ
double m_time = 0.0
The independent variable in the system.
double m_initial_time = 0.0
The initial value of the independent variable in the system.
bool m_init = false
bool m_integrator_init = false
True if integrator initialization is current.
size_t m_nv = 0
std::vector< size_t > m_start
m_start[n] is the starting point in the state vector for reactor n
vector_fp m_atol
double m_rtol = 1.0e-9
double m_rtolsens = 1.0e-4
double m_atols = 1.0e-15
double m_atolsens = 1.0e-6
shared_ptr< PreconditionerBase > m_precon
string m_linearSolverType
double m_maxstep = 0.0
Maximum integrator internal timestep. Default of 0.0 means infinity.
bool m_verbose = false
bool m_timeIsIndependent = true
Indicates whether time or space is the independent variable.
std::vector< std::string > m_paramNames
Names corresponding to each sensitivity parameter.
vector_fp m_ydot
vector_fp m_yest
vector_fp m_advancelimits
vector_fp m_LHS
m_LHS is a vector representing the coefficients on the "left hand side" of each governing equation
vector_fp m_RHS
void setLinearSolverType (const std::string &linSolverType="DENSE")
Set the type of linear solver used in the integration.
void setPreconditioner (shared_ptr< PreconditionerBase > preconditioner)
Set preconditioner used by the linear solver.
void setInitialTime (double time)
Set the initial value of the independent variable (typically time).
double getInitialTime () const
Get the initial value of the independent variable (typically time).
double maxTimeStep ()
Get the maximum integrator step.
void setMaxTimeStep (double maxstep)
Set the maximum integrator step.
void setMaxErrTestFails (int nmax)
Set the maximum number of error test failures permitted by the CVODES integrator in a single step.
void setTolerances (double rtol, double atol)
Set the relative and absolute tolerances for the integrator.
void setSensitivityTolerances (double rtol, double atol)
Set the relative and absolute tolerances for integrating the sensitivity equations.
double time ()
Current value of the simulation time [s], for reactor networks that are solved in the time domain.
double distance ()
Current position [m] along the length of the reactor network, for reactors that are solved as a function of space.
double rtol ()
Relative tolerance.
double atol ()
Absolute integration tolerance.
double rtolSensitivity () const
Relative sensitivity tolerance.
double atolSensitivity () const
Absolute sensitivity tolerance.
std::string linearSolverType () const
Problem type of integrator.
int maxSteps ()
Returns the maximum number of internal integration steps the integrator will take before reaching the next output point.
void advance (double t)
Advance the state of all reactors in the independent variable (time or space).
double advance (double t, bool applylimit)
Advance the state of all reactors in the independent variable (time or space).
double step ()
Advance the state of all reactors with respect to the independent variable (time or space).
void addReactor (Reactor &r)
Add the reactor r to this reactor network.
Reactor & reactor (int n)
Return a reference to the n-th reactor in this network.
bool verbose () const
Returns true if verbose logging output is enabled.
void setVerbose (bool v=true)
Enable or disable verbose logging while setting up and integrating the reactor network.
Integrator & integrator ()
Return a reference to the integrator.
void updateState (double *y)
Update the state of all the reactors in the network to correspond to the values in the solution vector y.
double sensitivity (size_t k, size_t p)
Return the sensitivity of the k-th solution component with respect to the p-th sensitivity parameter.
double sensitivity (const std::string &component, size_t p, int reactor=0)
Return the sensitivity of the component named component with respect to the p-th sensitivity parameter.
void evalJacobian (double t, double *y, double *ydot, double *p, Array2D *j)
Evaluate the Jacobian matrix for the reactor network.
virtual size_t neq ()
Number of equations.
size_t nReactors ()
virtual void eval (double t, double *y, double *ydot, double *p)
Evaluate the right-hand-side ODE function.
virtual void evalDae (double t, double *y, double *ydot, double *p, double *residaul)
eval coupling for IDA / DAEs
virtual void getState (double *y)
Fill in the vector y with the current state of the system.
virtual void getStateDae (double *y, double *ydot)
Fill in the vectors y and ydot with the current state of the system.
virtual void getDerivative (int k, double *dky)
Return k-th derivative at the current state of the system.
virtual void getConstraints (double *constraints)
Given a vector of length neq(), mark which variables should be considered algebraic constraints.
virtual size_t nparams ()
Number of sensitivity parameters.
size_t globalComponentIndex (const std::string &component, size_t reactor=0)
Return the index corresponding to the component named component in the reactor with index reactor in the global state vector for the reactor network.
std::string componentName (size_t i) const
Return the name of the i-th component of the global state vector.
size_t registerSensitivityParameter (const std::string &name, double value, double scale)
Used by Reactor and Wall objects to register the addition of sensitivity parameters so that the ReactorNet can keep track of the order in which sensitivity parameters are added.
const std::string & sensitivityParameterName (size_t p)
The name of the p-th sensitivity parameter added to this ReactorNet.
void initialize ()
Initialize the reactor network.
void reinitialize ()
Reinitialize the integrator.
void setNeedsReinit ()
Called to trigger integrator reinitialization before further integration.
virtual void setMaxSteps (int nmax)
Set the maximum number of internal integration steps the integrator will take before reaching the next output point.
void setAdvanceLimits (const double *limits)
Set absolute step size limits during advance.
bool hasAdvanceLimits ()
Check whether ReactorNet object uses advance limits.
bool getAdvanceLimits (double *limits)
Retrieve absolute step size limits during advance.
virtual void preconditionerSetup (double t, double *y, double gamma)
virtual void preconditionerSolve (double *rhs, double *output)
AnyMap solverStats () const
Get solver stats from integrator.
virtual void setDerivativeSettings (AnyMap &settings)
Set derivative settings of all reactors.
virtual void checkPreconditionerSupported ()
Check that preconditioning is supported by all reactors in the network.
virtual void updatePreconditioner (double gamma)
Update the preconditioner based on the already computed jacobian values.
virtual void getEstimate (double time, int k, double *yest)
Estimate a future state based on current derivatives.
virtual int lastOrder ()
Returns the order used for last solution step of the ODE integrator The function is intended for internal use by ReactorNet::advance and deliberately not exposed in external interfaces.
Additional Inherited Members
Public Attributes inherited from FuncEval
vector_fp m_sens_params
Values for the problem parameters for which sensitivities are computed This is the array which is perturbed and passed back as the fourth argument to eval().
vector_fp m_paramScales
Scaling factors for each sensitivity parameter.
Protected Attributes inherited from FuncEval
bool m_suppress_errors = false
std::vector< std::string > m_errors
Errors occurring during function evaluations.
Detailed Description
A class representing a network of connected reactors.
This class is used to integrate the governing equations for a network of reactors that are time dependent (Reactor, ConstPressureReactor) connected by various means, for example Wall, MassFlowController, Valve, or PressureController; or reactors dependent on a single spatial variable (FlowReactor).
Definition at line 29 of file ReactorNet.h.
Constructor & Destructor Documentation
ReactorNet()
ReactorNet ()
Definition at line 19 of file ReactorNet.cpp.
~ReactorNet()
~ReactorNet () virtual
Definition at line 24 of file ReactorNet.cpp.
Member Function Documentation
setLinearSolverType()
void setLinearSolverType (const std::string & linSolverType = "DENSE")
Set the type of linear solver used in the integration.
Parameters
linSolverType type of linear solver. Default type: "DENSE" Other options include: "DIAG", "DENSE", "GMRES", "BAND"
Definition at line 151 of file ReactorNet.cpp.
References ReactorNet::m_integrator_init.
setPreconditioner()
void setPreconditioner (shared_ptr< PreconditionerBase > preconditioner)
Set preconditioner used by the linear solver.
Parameters
preconditioner preconditioner object used for the linear solver
Definition at line 157 of file ReactorNet.cpp.
References ReactorNet::m_integrator_init.
setInitialTime()
void setInitialTime (double time)
Set the initial value of the independent variable (typically time).
Default = 0.0 s. Restarts integration from this value using the current mixture state as the initial condition.
Definition at line 28 of file ReactorNet.cpp.
References ReactorNet::m_initial_time, ReactorNet::m_integrator_init, ReactorNet::m_time, and ReactorNet::time().
getInitialTime()
double getInitialTime () const inline
Get the initial value of the independent variable (typically time).
Since
New in Cantera 3.0.
Definition at line 58 of file ReactorNet.h.
References ReactorNet::m_initial_time.
maxTimeStep()
double maxTimeStep () inline
Get the maximum integrator step.
Definition at line 63 of file ReactorNet.h.
References ReactorNet::m_maxstep.
setMaxTimeStep()
void setMaxTimeStep (double maxstep)
Set the maximum integrator step.
Definition at line 35 of file ReactorNet.cpp.
References ReactorNet::integrator(), ReactorNet::m_maxstep, and Integrator::setMaxStepSize().
setMaxErrTestFails()
void setMaxErrTestFails (int nmax)
Set the maximum number of error test failures permitted by the CVODES integrator in a single step.
Definition at line 41 of file ReactorNet.cpp.
References ReactorNet::integrator(), and Integrator::setMaxErrTestFails().
setTolerances()
void setTolerances (double rtol, double atol)
Set the relative and absolute tolerances for the integrator.
Definition at line 46 of file ReactorNet.cpp.
References ReactorNet::atol(), and ReactorNet::rtol().
setSensitivityTolerances()
void setSensitivityTolerances (double rtol, double atol)
Set the relative and absolute tolerances for integrating the sensitivity equations.
Definition at line 57 of file ReactorNet.cpp.
References ReactorNet::atol(), and ReactorNet::rtol().
time()
double time ()
Current value of the simulation time [s], for reactor networks that are solved in the time domain.
Definition at line 68 of file ReactorNet.cpp.
References ReactorNet::m_time, and ReactorNet::m_timeIsIndependent.
Referenced by ReactorNet::advance(), Reactor::finiteDifferenceJacobian(), ReactorNet::getEstimate(), IdealGasConstPressureMoleReactor::jacobian(), IdealGasMoleReactor::jacobian(), ReactorNet::setInitialTime(), and Reactor::updateConnected().
distance()
double distance ()
Current position [m] along the length of the reactor network, for reactors that are solved as a function of space.
Definition at line 77 of file ReactorNet.cpp.
References ReactorNet::m_time, and ReactorNet::m_timeIsIndependent.
Referenced by FlowReactor::distance(), and Reactor::updateConnected().
rtol()
double rtol () inline
Relative tolerance.
Definition at line 90 of file ReactorNet.h.
Referenced by ReactorNet::setSensitivityTolerances(), and ReactorNet::setTolerances().
atol()
double atol () inline
Absolute integration tolerance.
Definition at line 95 of file ReactorNet.h.
Referenced by Reactor::finiteDifferenceJacobian(), ReactorNet::setSensitivityTolerances(), and ReactorNet::setTolerances().
rtolSensitivity()
double rtolSensitivity () const inline
Relative sensitivity tolerance.
Definition at line 100 of file ReactorNet.h.
atolSensitivity()
double atolSensitivity () const inline
Absolute sensitivity tolerance.
Definition at line 105 of file ReactorNet.h.
linearSolverType()
std::string linearSolverType () const
Problem type of integrator.
Definition at line 511 of file ReactorNet.cpp.
maxSteps()
int maxSteps ()
Returns the maximum number of internal integration steps the integrator will take before reaching the next output point.
Definition at line 168 of file ReactorNet.cpp.
References ReactorNet::integrator(), and Integrator::maxSteps().
advance() [1/2]
void advance (double t)
Advance the state of all reactors in the independent variable (time or space).
Take as many internal steps as necessary to reach t.
Parameters
t Time/distance to advance to (s or m).
Definition at line 173 of file ReactorNet.cpp.
References ReactorNet::initialize(), ReactorNet::m_integrator_init, ReactorNet::m_time, ReactorNet::reinitialize(), ReactorNet::time(), and ReactorNet::updateState().
Referenced by ReactorNet::advance().
advance() [2/2]
double advance (double t, bool applylimit)
Advance the state of all reactors in the independent variable (time or space).
Take as many internal steps as necessary towards t. If applylimit is true, the advance step will be automatically reduced if needed to stay within limits (set by setAdvanceLimit). Returns the time/distance at the end of integration.
Parameters
t Time/distance to advance to (s or m).
applylimit Limit advance step (boolean).
Definition at line 185 of file ReactorNet.cpp.
References ReactorNet::advance(), ReactorNet::getAdvanceLimits(), ReactorNet::getEstimate(), ReactorNet::hasAdvanceLimits(), ReactorNet::initialize(), ReactorNet::lastOrder(), ReactorNet::m_integrator_init, ReactorNet::m_time, ReactorNet::reinitialize(), ReactorNet::step(), ReactorNet::time(), and Cantera::writelog().
step()
double step ()
Advance the state of all reactors with respect to the independent variable (time or space).
Returns the new value of the independent variable [s or m].
Definition at line 240 of file ReactorNet.cpp.
References ReactorNet::initialize(), ReactorNet::m_integrator_init, ReactorNet::m_time, ReactorNet::reinitialize(), and ReactorNet::updateState().
Referenced by ReactorNet::advance().
addReactor()
void addReactor (Reactor & r)
Add the reactor r to this reactor network.
Definition at line 284 of file ReactorNet.cpp.
References Cantera::BDF_Method, Reactor::isOde(), ReactorNet::m_timeIsIndependent, ReactorBase::setNetwork(), Reactor::timeIsIndependent(), and Reactor::type().
reactor()
Reactor & reactor (int n) inline
Return a reference to the n-th reactor in this network.
The reactor indices are determined by the order in which the reactors were added to the reactor network.
Definition at line 144 of file ReactorNet.h.
Referenced by ReactorNet::checkPreconditionerSupported(), ReactorNet::globalComponentIndex(), and ReactorNet::sensitivity().
verbose()
bool verbose () const inline
Returns true if verbose logging output is enabled.
Definition at line 149 of file ReactorNet.h.
setVerbose()
void setVerbose (bool v = true) inline
Enable or disable verbose logging while setting up and integrating the reactor network.
Definition at line 155 of file ReactorNet.h.
References FuncEval::suppressErrors().
integrator()
Integrator & integrator ()
Return a reference to the integrator.
Only valid after adding at least one reactor to the network.
Definition at line 310 of file ReactorNet.cpp.
Referenced by ReactorNet::maxSteps(), ReactorNet::setMaxErrTestFails(), ReactorNet::setMaxSteps(), and ReactorNet::setMaxTimeStep().
updateState()
void updateState (double * y)
Update the state of all the reactors in the network to correspond to the values in the solution vector y.
Definition at line 399 of file ReactorNet.cpp.
References Cantera::checkFinite(), and ReactorNet::m_start.
Referenced by ReactorNet::advance(), ReactorNet::eval(), ReactorNet::evalDae(), ReactorNet::preconditionerSetup(), and ReactorNet::step().
sensitivity() [1/2]
double sensitivity (size_t k, size_t p)
Return the sensitivity of the k-th solution component with respect to the p-th sensitivity parameter.
The sensitivity coefficient \(S_{ki} \) of solution variable \(y_k \) with respect to sensitivity parameter \(p_i \) is defined as:
\[ S_{ki} = \frac{1}{y_k} \frac{\partial y_k}{\partial p_i} \]
For reaction sensitivities, the parameter is a multiplier on the forward rate constant (and implicitly on the reverse rate constant for reversible reactions) which has a nominal value of 1.0, and the sensitivity is nondimensional.
For species enthalpy sensitivities, the parameter is a perturbation to the molar enthalpy of formation, such that the dimensions of the sensitivity are kmol/J.
Definition at line 360 of file ReactorNet.cpp.
References ReactorNet::initialize(), FuncEval::m_sens_params, and Cantera::SmallNumber.
Referenced by ReactorNet::sensitivity().
sensitivity() [2/2]
double sensitivity (const std::string & component, size_t p, int reactor = 0) inline
Return the sensitivity of the component named component with respect to the p-th sensitivity parameter.
The sensitivity coefficient \(S_{ki} \) of solution variable \(y_k \) with respect to sensitivity parameter \(p_i \) is defined as:
\[ S_{ki} = \frac{1}{y_k} \frac{\partial y_k}{\partial p_i} \]
For reaction sensitivities, the parameter is a multiplier on the forward rate constant (and implicitly on the reverse rate constant for reversible reactions) which has a nominal value of 1.0, and the sensitivity is nondimensional.
For species enthalpy sensitivities, the parameter is a perturbation to the molar enthalpy of formation, such that the dimensions of the sensitivity are kmol/J.
Definition at line 190 of file ReactorNet.h.
References ReactorNet::globalComponentIndex(), ReactorNet::reactor(), and ReactorNet::sensitivity().
evalJacobian()
void evalJacobian (double t, double * y, double * ydot, double * p, Array2D * j)
Evaluate the Jacobian matrix for the reactor network.
Parameters
[in] t Time/distance at which to evaluate the Jacobian
[in] y Global state vector at t
[out] ydot Derivative of the state vector evaluated at t, with respect to t.
[in] p sensitivity parameter vector (unused?)
[out] j Jacobian matrix, size neq() by neq().
Definition at line 376 of file ReactorNet.cpp.
References ReactorNet::eval(), and Array2D::value().
neq()
virtual size_t neq () inline virtual
Number of equations.
Implements FuncEval.
Definition at line 208 of file ReactorNet.h.
Referenced by ReactorNet::componentName(), and ReactorNet::initialize().
nReactors()
size_t nReactors () inline
Definition at line 212 of file ReactorNet.h.
eval()
void eval (double t, double * y, double * ydot, double * p) virtual
Evaluate the right-hand-side ODE function.
Called by the integrator.
Parameters
[in] t time.
[in] y solution vector, length neq()
[out] ydot rate of change of solution vector, length neq()
[in] p sensitivity parameter vector, length nparams()
Reimplemented from FuncEval.
Definition at line 318 of file ReactorNet.cpp.
References Cantera::checkFinite(), ReactorNet::m_LHS, ReactorNet::m_start, ReactorNet::m_time, and ReactorNet::updateState().
Referenced by ReactorNet::evalJacobian().
evalDae()
void evalDae (double t, double * y, double * ydot, double * p, double * residaul) virtual
eval coupling for IDA / DAEs
Reimplemented from FuncEval.
Definition at line 341 of file ReactorNet.cpp.
References Cantera::checkFinite(), ReactorNet::m_time, and ReactorNet::updateState().
getState()
void getState (double * y) virtual
Fill in the vector y with the current state of the system.
Used for getting the initial state for ODE systems.
Reimplemented from FuncEval.
Definition at line 446 of file ReactorNet.cpp.
References ReactorNet::m_start.
Referenced by ReactorNet::preconditionerSetup().
getStateDae()
void getStateDae (double * y, double * ydot) virtual
Fill in the vectors y and ydot with the current state of the system.
Used for getting the initial state for DAE systems.
Reimplemented from FuncEval.
Definition at line 453 of file ReactorNet.cpp.
References ReactorNet::m_start.
getDerivative()
void getDerivative (int k, double * dky) virtual
Return k-th derivative at the current state of the system.
Definition at line 407 of file ReactorNet.cpp.
References ReactorNet::initialize(), and ReactorNet::m_time.
getConstraints()
void getConstraints (double * constraints) virtual
Given a vector of length neq(), mark which variables should be considered algebraic constraints.
Reimplemented from FuncEval.
Definition at line 353 of file ReactorNet.cpp.
References ReactorNet::m_start.
nparams()
virtual size_t nparams () inline virtual
Number of sensitivity parameters.
Reimplemented from FuncEval.
Definition at line 230 of file ReactorNet.h.
References FuncEval::m_sens_params.
globalComponentIndex()
size_t globalComponentIndex (const std::string & component, size_t reactor = 0)
Return the index corresponding to the component named component in the reactor with index reactor in the global state vector for the reactor network.
Definition at line 460 of file ReactorNet.cpp.
References ReactorNet::initialize(), ReactorNet::m_start, and ReactorNet::reactor().
Referenced by ReactorNet::sensitivity().
componentName()
std::string componentName (size_t i) const
Return the name of the i-th component of the global state vector.
The name returned includes both the name of the reactor and the specific component, for example ‘'reactor1: CH4’`.
Definition at line 468 of file ReactorNet.cpp.
References ReactorNet::neq().
registerSensitivityParameter()
size_t registerSensitivityParameter (const std::string & name, double value, double scale)
Used by Reactor and Wall objects to register the addition of sensitivity parameters so that the ReactorNet can keep track of the order in which sensitivity parameters are added.
Parameters
name A name describing the parameter, for example the reaction string
value The nominal value of the parameter
scale A scaling factor to be applied to the sensitivity coefficient
Returns
the index of this parameter in the vector of sensitivity parameters (global across all reactors)
Definition at line 480 of file ReactorNet.cpp.
References ReactorNet::m_integrator_init, ReactorNet::m_paramNames, FuncEval::m_paramScales, FuncEval::m_sens_params, and Cantera::scale().
Referenced by ReactorSurface::addSensitivityReaction(), Reactor::addSensitivityReaction(), and Reactor::addSensitivitySpeciesEnthalpy().
sensitivityParameterName()
const std::string & sensitivityParameterName (size_t p) inline
The name of the p-th sensitivity parameter added to this ReactorNet.
Definition at line 257 of file ReactorNet.h.
References ReactorNet::m_paramNames.
initialize()
void initialize ()
Initialize the reactor network.
Called automatically the first time advance or step is called.
Definition at line 86 of file ReactorNet.cpp.
References ReactorNet::checkPreconditionerSupported(), Cantera::debuglog(), Reactor::initialize(), ReactorNet::m_integrator_init, ReactorNet::m_maxstep, ReactorNet::m_start, ReactorNet::m_time, Reactor::neq(), ReactorNet::neq(), Reactor::nSensParams(), Reactor::type(), and Cantera::writelog().
Referenced by ReactorNet::advance(), ReactorNet::getDerivative(), ReactorNet::getEstimate(), ReactorNet::globalComponentIndex(), ReactorNet::reinitialize(), ReactorNet::sensitivity(), Reactor::setAdvanceLimit(), ReactorNet::setAdvanceLimits(), and ReactorNet::step().
reinitialize()
void reinitialize ()
Reinitialize the integrator.
Used to solve a new problem (different initial conditions) but with the same configuration of the reactor network. Can be called manually, or automatically after calling setInitialTime or modifying a reactor's contents.
Definition at line 137 of file ReactorNet.cpp.
References ReactorNet::checkPreconditionerSupported(), Cantera::debuglog(), ReactorNet::initialize(), ReactorNet::m_integrator_init, and ReactorNet::m_time.
Referenced by ReactorNet::advance(), and ReactorNet::step().
setNeedsReinit()
void setNeedsReinit () inline
Called to trigger integrator reinitialization before further integration.
Definition at line 273 of file ReactorNet.h.
References ReactorNet::m_integrator_init.
Referenced by ReactorBase::syncState().
setMaxSteps()
void setMaxSteps (int nmax) virtual
Set the maximum number of internal integration steps the integrator will take before reaching the next output point.
Parameters
nmax The maximum number of steps, setting this value to zero disables this option.
Definition at line 163 of file ReactorNet.cpp.
References ReactorNet::integrator(), and Integrator::setMaxSteps().
setAdvanceLimits()
void setAdvanceLimits (const double * limits)
Set absolute step size limits during advance.
Definition at line 418 of file ReactorNet.cpp.
References ReactorNet::initialize(), and ReactorNet::m_start.
hasAdvanceLimits()
bool hasAdvanceLimits ()
Check whether ReactorNet object uses advance limits.
Definition at line 428 of file ReactorNet.cpp.
Referenced by ReactorNet::advance().
getAdvanceLimits()
bool getAdvanceLimits (double * limits)
Retrieve absolute step size limits during advance.
Definition at line 437 of file ReactorNet.cpp.
References ReactorNet::m_start.
Referenced by ReactorNet::advance().
preconditionerSetup()
void preconditionerSetup (double t, double * y, double gamma) virtual
Evaluate the setup processes for the Jacobian preconditioner.
Parameters
[in] t time.
[in] y solution vector, length neq()
gamma the gamma in M=I-gamma*J
Warning
This function is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented from FuncEval.
Definition at line 529 of file ReactorNet.cpp.
References ReactorNet::getState(), ReactorNet::m_start, and ReactorNet::updateState().
preconditionerSolve()
void preconditionerSolve (double * rhs, double * output) virtual
Evaluate the linear system Ax=b where A is the preconditioner.
Parameters
[in] rhs right hand side vector used in linear system
[out] output output vector for solution
Warning
This function is an experimental part of the Cantera API and may be changed or removed without notice.
Reimplemented from FuncEval.
Definition at line 520 of file ReactorNet.cpp.
solverStats()
AnyMap solverStats () const
Get solver stats from integrator.
Definition at line 502 of file ReactorNet.cpp.
setDerivativeSettings()
void setDerivativeSettings (AnyMap & settings) virtual
Set derivative settings of all reactors.
Parameters
settings the settings map propagated to all reactors and kinetics objects
Definition at line 494 of file ReactorNet.cpp.
checkPreconditionerSupported()
void checkPreconditionerSupported () protected virtual
Check that preconditioning is supported by all reactors in the network.
Definition at line 572 of file ReactorNet.cpp.
References Reactor::preconditionerSupported(), ReactorNet::reactor(), and Reactor::type().
Referenced by ReactorNet::initialize(), and ReactorNet::reinitialize().
updatePreconditioner()
void updatePreconditioner (double gamma) protected virtual
Update the preconditioner based on the already computed jacobian values.
Reimplemented from FuncEval.
Definition at line 561 of file ReactorNet.cpp.
getEstimate()
void getEstimate (double time, int k, double * yest) protected virtual
Estimate a future state based on current derivatives.
The function is intended for internal use by ReactorNet::advance and deliberately not exposed in external interfaces.
Definition at line 252 of file ReactorNet.cpp.
References ReactorNet::initialize(), ReactorNet::m_time, and ReactorNet::time().
Referenced by ReactorNet::advance().
lastOrder()
int lastOrder () protected virtual
Returns the order used for last solution step of the ODE integrator The function is intended for internal use by ReactorNet::advance and deliberately not exposed in external interfaces.
Definition at line 275 of file ReactorNet.cpp.
Referenced by ReactorNet::advance().
Member Data Documentation
m_reactors
std::vector<Reactor*> m_reactors protected
Definition at line 320 of file ReactorNet.h.
m_integ
std::unique_ptr<Integrator> m_integ protected
Definition at line 321 of file ReactorNet.h.
m_time
double m_time = 0.0 protected
The independent variable in the system.
May be either time or space depending on the type of reactors in the network.
Definition at line 325 of file ReactorNet.h.
Referenced by ReactorNet::advance(), ReactorNet::distance(), ReactorNet::eval(), ReactorNet::evalDae(), ReactorNet::getDerivative(), ReactorNet::getEstimate(), ReactorNet::initialize(), ReactorNet::reinitialize(), ReactorNet::setInitialTime(), ReactorNet::step(), and ReactorNet::time().
m_initial_time
double m_initial_time = 0.0 protected
The initial value of the independent variable in the system.
Definition at line 328 of file ReactorNet.h.
Referenced by ReactorNet::getInitialTime(), and ReactorNet::setInitialTime().
m_init
bool m_init = false protected
Definition at line 330 of file ReactorNet.h.
m_integrator_init
bool m_integrator_init = false protected
True if integrator initialization is current.
Definition at line 331 of file ReactorNet.h.
Referenced by ReactorNet::advance(), ReactorNet::initialize(), ReactorNet::registerSensitivityParameter(), ReactorNet::reinitialize(), ReactorNet::setInitialTime(), ReactorNet::setLinearSolverType(), ReactorNet::setNeedsReinit(), ReactorNet::setPreconditioner(), and ReactorNet::step().
m_nv
size_t m_nv = 0 protected
Definition at line 332 of file ReactorNet.h.
m_start
std::vector<size_t> m_start protected
m_start[n] is the starting point in the state vector for reactor n
Definition at line 335 of file ReactorNet.h.
Referenced by ReactorNet::eval(), ReactorNet::getAdvanceLimits(), ReactorNet::getConstraints(), ReactorNet::getState(), ReactorNet::getStateDae(), ReactorNet::globalComponentIndex(), ReactorNet::initialize(), ReactorNet::preconditionerSetup(), ReactorNet::setAdvanceLimits(), and ReactorNet::updateState().
m_atol
vector_fp m_atol protected
Definition at line 337 of file ReactorNet.h.
m_rtol
double m_rtol = 1.0e-9 protected
Definition at line 338 of file ReactorNet.h.
m_rtolsens
double m_rtolsens = 1.0e-4 protected
Definition at line 339 of file ReactorNet.h.
m_atols
double m_atols = 1.0e-15 protected
Definition at line 340 of file ReactorNet.h.
m_atolsens
double m_atolsens = 1.0e-6 protected
Definition at line 341 of file ReactorNet.h.
m_precon
shared_ptr<PreconditionerBase> m_precon protected
Definition at line 342 of file ReactorNet.h.
m_linearSolverType
string m_linearSolverType protected
Definition at line 343 of file ReactorNet.h.
m_maxstep
double m_maxstep = 0.0 protected
Maximum integrator internal timestep. Default of 0.0 means infinity.
Definition at line 346 of file ReactorNet.h.
Referenced by ReactorNet::initialize(), ReactorNet::maxTimeStep(), and ReactorNet::setMaxTimeStep().
m_verbose
bool m_verbose = false protected
Definition at line 348 of file ReactorNet.h.
m_timeIsIndependent
bool m_timeIsIndependent = true protected
Indicates whether time or space is the independent variable.
Definition at line 351 of file ReactorNet.h.
Referenced by ReactorNet::addReactor(), ReactorNet::distance(), and ReactorNet::time().
m_paramNames
std::vector<std::string> m_paramNames protected
Names corresponding to each sensitivity parameter.
Definition at line 354 of file ReactorNet.h.
Referenced by ReactorNet::registerSensitivityParameter(), and ReactorNet::sensitivityParameterName().
m_ydot
vector_fp m_ydot protected
Definition at line 356 of file ReactorNet.h.
m_yest
vector_fp m_yest protected
Definition at line 357 of file ReactorNet.h.
m_advancelimits
vector_fp m_advancelimits protected
Definition at line 358 of file ReactorNet.h.
m_LHS
vector_fp m_LHS protected
m_LHS is a vector representing the coefficients on the "left hand side" of each governing equation
Definition at line 361 of file ReactorNet.h.
Referenced by ReactorNet::eval().
m_RHS
vector_fp m_RHS protected
Definition at line 362 of file ReactorNet.h.
The documentation for this class was generated from the following files:
ReactorNet.h
ReactorNet.cpp