Cantera: CVodesIntegrator Class Reference
CVodesIntegrator Class Reference
Wrapper class for 'cvodes' integrator from LLNL.
#include <CVodesIntegrator.h>
Public Member Functions
CVodesIntegrator ()
Constructor.
virtual void setTolerances (double reltol, size_t n, double *abstol)
Set error tolerances.
virtual void setTolerances (double reltol, double abstol)
Set error tolerances.
virtual void setSensitivityTolerances (double reltol, double abstol)
Set the sensitivity error tolerances.
virtual void initialize (double t0, FuncEval &func)
Initialize the integrator for a new problem.
virtual void reinitialize (double t0, FuncEval &func)
virtual void integrate (double tout)
Integrate the system of equations.
virtual doublereal step (double tout)
Integrate the system of equations.
virtual double & solution (size_t k)
The current value of the solution of equation k.
virtual double * solution ()
The current value of the solution of the system of equations.
virtual double * derivative (double tout, int n)
n-th derivative of the output function at time tout.
virtual int lastOrder () const
Order used during the last solution step.
virtual int nEquations () const
The number of equations.
virtual int nEvals () const
The number of function evaluations.
virtual void setMaxOrder (int n)
Set the maximum integration order that will be used.
virtual void setMethod (MethodType t)
Set the solution method.
virtual void setMaxStepSize (double hmax)
Set the maximum step size.
virtual void setMinStepSize (double hmin)
Set the minimum step size.
virtual void setMaxSteps (int nmax)
Set the maximum number of time-steps the integrator can take before reaching the next output time.
virtual int maxSteps ()
Returns the maximum number of time-steps the integrator can take before reaching the next output time.
virtual void setMaxErrTestFails (int n)
Set the maximum permissible number of error test failures.
virtual AnyMap solverStats () const
Get solver stats from integrator.
void setLinearSolverType (const std::string &linSolverType)
Set the linear solver type.
virtual std::string linearSolverType () const
Return the integrator problem type.
virtual void setBandwidth (int N_Upper, int N_Lower)
virtual int nSensParams ()
virtual double sensitivity (size_t k, size_t p)
virtual void setProblemType (int probtype)
Set the problem type.
virtual std::string getErrorInfo (int N)
Returns a string listing the weighted error estimates associated with each solution component.
Public Member Functions inherited from Integrator
Integrator ()
Default Constructor.
virtual ~Integrator ()
Destructor.
virtual void setTolerances (double reltol, size_t n, double *abstol)
Set error tolerances.
virtual void setTolerances (double reltol, double abstol)
Set error tolerances.
virtual void setSensitivityTolerances (double reltol, double abstol)
Set the sensitivity error tolerances.
virtual void setProblemType (int probtype)
Set the problem type.
virtual void setLinearSolverType (const std::string &linSolverType)
Set the linear solver type.
virtual void setPreconditioner (shared_ptr< PreconditionerBase > preconditioner)
Set preconditioner used by the linear solver.
virtual void preconditionerSolve (size_t stateSize, double *rhs, double *output)
Solve a linear system Ax=b where A is the preconditioner.
virtual PreconditionerSide preconditionerSide ()
Return the side of the system on which the preconditioner is applied.
virtual shared_ptr< PreconditionerBase > preconditioner ()
Return preconditioner reference to object.
virtual std::string linearSolverType () const
Return the integrator problem type.
virtual void initialize (double t0, FuncEval &func)
Initialize the integrator for a new problem.
virtual void reinitialize (double t0, FuncEval &func)
virtual void integrate (double tout)
Integrate the system of equations.
virtual double step (double tout)
Integrate the system of equations.
virtual double & solution (size_t k)
The current value of the solution of equation k.
virtual double * solution ()
The current value of the solution of the system of equations.
virtual double * derivative (double tout, int n)
n-th derivative of the output function at time tout.
virtual int lastOrder () const
Order used during the last solution step.
virtual int nEquations () const
The number of equations.
virtual int nEvals () const
The number of function evaluations.
virtual int maxOrder () const
virtual void setMaxOrder (int n)
Set the maximum integration order that will be used.
virtual void setMethod (MethodType t)
Set the solution method.
virtual void setMaxStepSize (double hmax)
Set the maximum step size.
virtual void setMinStepSize (double hmin)
Set the minimum step size.
virtual void setMaxErrTestFails (int n)
Set the maximum permissible number of error test failures.
virtual void setMaxSteps (int nmax)
Set the maximum number of time-steps the integrator can take before reaching the next output time.
virtual int maxSteps ()
Returns the maximum number of time-steps the integrator can take before reaching the next output time.
virtual void setBandwidth (int N_Upper, int N_Lower)
virtual int nSensParams ()
virtual double sensitivity (size_t k, size_t p)
virtual AnyMap solverStats () const
Get solver stats from integrator.
virtual int maxNonlinIterations () const
virtual void setMaxNonlinIterations (int n)
virtual int maxNonlinConvFailures () const
virtual void setMaxNonlinConvFailures (int n)
virtual bool algebraicInErrorTest () const
virtual void includeAlgebraicInErrorTest (bool yesno)
Public Attributes
std::string m_error_message
Error message information provide by CVodes.
Protected Member Functions
void applyOptions ()
Applies user-specified options to the underlying CVODES solver.
Private Member Functions
void sensInit (double t0, FuncEval &func)
Private Attributes
size_t m_neq = 0
void * m_cvode_mem = nullptr
SundialsContext m_sundials_ctx
SUNContext object for Sundials>=6.0.
void * m_linsol = nullptr
Sundials linear solver object.
void * m_linsol_matrix = nullptr
matrix used by Sundials
FuncEval * m_func = nullptr
double m_t0 = 0.0
double m_time
The current integrator time.
N_Vector m_y = nullptr
N_Vector m_abstol = nullptr
N_Vector m_dky = nullptr
string m_type = "DENSE"
int m_itol
int m_method
int m_maxord = 0
double m_reltol = 1e-9
double m_abstols = 1e-15
double m_reltolsens = 1e-5
double m_abstolsens = 1e-4
size_t m_nabs = 0
double m_hmax = 0.0
double m_hmin = 0.0
int m_maxsteps = 20000
int m_maxErrTestFails = 0
N_Vector * m_yS = nullptr
size_t m_np = 0
int m_mupper = 0
int m_mlower = 0
bool m_sens_ok = false
Indicates whether the sensitivities stored in m_yS have been updated for at the current integrator time.
Additional Inherited Members
Protected Attributes inherited from Integrator
shared_ptr< PreconditionerBase > m_preconditioner
Pointer to preconditioner object used in integration which is set by setPreconditioner and initialized inside of ReactorNet::initialize()
PreconditionerSide m_prec_side = PreconditionerSide::NO_PRECONDITION
Type of preconditioning used in applyOptions.
Detailed Description
Wrapper class for 'cvodes' integrator from LLNL.
See FuncEval.h. Classes that use CVodesIntegrator: ImplicitSurfChem, ReactorNet
Definition at line 26 of file CVodesIntegrator.h.
Constructor & Destructor Documentation
CVodesIntegrator()
CVodesIntegrator ()
Constructor.
Default settings: dense Jacobian, no user-supplied Jacobian function, Newton iteration.
Definition at line 79 of file CVodesIntegrator.cpp.
~CVodesIntegrator()
~CVodesIntegrator () virtual
Definition at line 85 of file CVodesIntegrator.cpp.
Member Function Documentation
setTolerances() [1/2]
void setTolerances (double reltol, size_t n, double * abstol) virtual
Set error tolerances.
Parameters
reltol scalar relative tolerance
n Number of equations
abstol array of N absolute tolerance values
Reimplemented from Integrator.
Definition at line 126 of file CVodesIntegrator.cpp.
References CVodesIntegrator::m_sundials_ctx.
setTolerances() [2/2]
void setTolerances (double reltol, double abstol) virtual
Set error tolerances.
Parameters
reltol scalar relative tolerance
abstol scalar absolute tolerance
Reimplemented from Integrator.
Definition at line 142 of file CVodesIntegrator.cpp.
setSensitivityTolerances()
void setSensitivityTolerances (double reltol, double abstol) virtual
Set the sensitivity error tolerances.
Parameters
reltol scalar relative tolerance
abstol scalar absolute tolerance
Reimplemented from Integrator.
Definition at line 149 of file CVodesIntegrator.cpp.
initialize()
void initialize (double t0, FuncEval & func) virtual
Initialize the integrator for a new problem.
Call after all options have been set.
Parameters
t0 initial time
func RHS evaluator object for system of equations.
Reimplemented from Integrator.
Definition at line 252 of file CVodesIntegrator.cpp.
References CVodesIntegrator::applyOptions(), FuncEval::clearErrors(), Cantera::cvodes_err(), Cantera::cvodes_rhs(), FuncEval::getState(), FuncEval::m_paramScales, Integrator::m_prec_side, Integrator::m_preconditioner, FuncEval::m_sens_params, CVodesIntegrator::m_sundials_ctx, CVodesIntegrator::m_time, FuncEval::neq(), and FuncEval::nparams().
reinitialize()
void reinitialize (double t0, FuncEval & func) virtual
Reimplemented from Integrator.
Definition at line 350 of file CVodesIntegrator.cpp.
integrate()
void integrate (double tout) virtual
Integrate the system of equations.
Parameters
tout Integrate to this time. Note that this is the absolute time value, not a time interval.
Reimplemented from Integrator.
Definition at line 511 of file CVodesIntegrator.cpp.
References CVodesIntegrator::getErrorInfo(), FuncEval::getErrors(), CVodesIntegrator::m_error_message, CVodesIntegrator::m_sens_ok, and CVodesIntegrator::m_time.
step()
double step (double tout) virtual
Integrate the system of equations.
Parameters
tout integrate to this time. Note that this is the absolute time value, not a time interval.
Reimplemented from Integrator.
Definition at line 531 of file CVodesIntegrator.cpp.
References CVodesIntegrator::getErrorInfo(), FuncEval::getErrors(), CVodesIntegrator::m_error_message, CVodesIntegrator::m_sens_ok, and CVodesIntegrator::m_time.
solution() [1/2]
double & solution (size_t k) virtual
The current value of the solution of equation k.
Reimplemented from Integrator.
Definition at line 116 of file CVodesIntegrator.cpp.
solution() [2/2]
double * solution () virtual
The current value of the solution of the system of equations.
Reimplemented from Integrator.
Definition at line 121 of file CVodesIntegrator.cpp.
derivative()
double * derivative (double tout, int n) virtual
n-th derivative of the output function at time tout.
Reimplemented from Integrator.
Definition at line 550 of file CVodesIntegrator.cpp.
References FuncEval::getErrors(), and CVodesIntegrator::m_error_message.
lastOrder()
int lastOrder () const virtual
Order used during the last solution step.
Reimplemented from Integrator.
Definition at line 566 of file CVodesIntegrator.cpp.
Referenced by CVodesIntegrator::solverStats().
nEquations()
virtual int nEquations () const inline virtual
The number of equations.
Reimplemented from Integrator.
Definition at line 46 of file CVodesIntegrator.h.
nEvals()
int nEvals () const virtual
The number of function evaluations.
Reimplemented from Integrator.
Definition at line 573 of file CVodesIntegrator.cpp.
setMaxOrder()
virtual void setMaxOrder (int n) inline virtual
Set the maximum integration order that will be used.
Reimplemented from Integrator.
Definition at line 50 of file CVodesIntegrator.h.
setMethod()
void setMethod (MethodType t) virtual
Set the solution method.
Reimplemented from Integrator.
Definition at line 173 of file CVodesIntegrator.cpp.
References Cantera::Adams_Method, and Cantera::BDF_Method.
setMaxStepSize()
void setMaxStepSize (double hmax) virtual
Set the maximum step size.
Reimplemented from Integrator.
Definition at line 184 of file CVodesIntegrator.cpp.
setMinStepSize()
void setMinStepSize (double hmin) virtual
Set the minimum step size.
Reimplemented from Integrator.
Definition at line 192 of file CVodesIntegrator.cpp.
setMaxSteps()
void setMaxSteps (int nmax) virtual
Set the maximum number of time-steps the integrator can take before reaching the next output time.
Parameters
nmax The maximum number of steps, setting this value to zero disables this option.
Reimplemented from Integrator.
Definition at line 200 of file CVodesIntegrator.cpp.
maxSteps()
int maxSteps () virtual
Returns the maximum number of time-steps the integrator can take before reaching the next output time.
Reimplemented from Integrator.
Definition at line 208 of file CVodesIntegrator.cpp.
setMaxErrTestFails()
void setMaxErrTestFails (int n) virtual
Set the maximum permissible number of error test failures.
Reimplemented from Integrator.
Definition at line 213 of file CVodesIntegrator.cpp.
solverStats()
AnyMap solverStats () const virtual
Get solver stats from integrator.
Reimplemented from Integrator.
Definition at line 580 of file CVodesIntegrator.cpp.
References CVodesIntegrator::lastOrder(), and Cantera::warn_user().
setLinearSolverType()
void setLinearSolverType (const std::string & linSolverType) inline virtual
Set the linear solver type.
Parameters
linSolverType Type of the linear solver
Reimplemented from Integrator.
Definition at line 60 of file CVodesIntegrator.h.
Referenced by CVodesIntegrator::setProblemType().
linearSolverType()
virtual std::string linearSolverType () const inline virtual
Return the integrator problem type.
Reimplemented from Integrator.
Definition at line 63 of file CVodesIntegrator.h.
setBandwidth()
virtual void setBandwidth (int N_Upper, int N_Lower) inline virtual
Reimplemented from Integrator.
Definition at line 66 of file CVodesIntegrator.h.
nSensParams()
virtual int nSensParams () inline virtual
Reimplemented from Integrator.
Definition at line 70 of file CVodesIntegrator.h.
sensitivity()
double sensitivity (size_t k, size_t p) virtual
Reimplemented from Integrator.
Definition at line 639 of file CVodesIntegrator.cpp.
setProblemType()
void setProblemType (int probtype) virtual
Set the problem type.
Parameters
probtype Type of the problem
Deprecated:
This function is to be removed along with the integer constants used in conditionals to set the problem type currently. This includes DENSE, JAC, NOJAC, BAND, and DIAG
Reimplemented from Integrator.
Definition at line 155 of file CVodesIntegrator.cpp.
References CVodesIntegrator::setLinearSolverType(), and Cantera::warn_deprecated().
getErrorInfo()
string getErrorInfo (int N) virtual
Returns a string listing the weighted error estimates associated with each solution component.
This information can be used to identify which variables are responsible for integrator failures or unexpected small timesteps.
Definition at line 665 of file CVodesIntegrator.cpp.
References CVodesIntegrator::m_sundials_ctx.
Referenced by CVodesIntegrator::integrate(), and CVodesIntegrator::step().
applyOptions()
void applyOptions () protected
Applies user-specified options to the underlying CVODES solver.
Called during integrator initialization or reinitialization.
Definition at line 369 of file CVodesIntegrator.cpp.
References CVodesIntegrator::m_linsol, CVodesIntegrator::m_linsol_matrix, Integrator::m_prec_side, and CVodesIntegrator::m_sundials_ctx.
Referenced by CVodesIntegrator::initialize().
sensInit()
void sensInit (double t0, FuncEval & func) private
Definition at line 221 of file CVodesIntegrator.cpp.
Member Data Documentation
m_error_message
std::string m_error_message
Error message information provide by CVodes.
Definition at line 83 of file CVodesIntegrator.h.
Referenced by Cantera::cvodes_err(), CVodesIntegrator::derivative(), CVodesIntegrator::integrate(), and CVodesIntegrator::step().
m_neq
size_t m_neq = 0 private
Definition at line 93 of file CVodesIntegrator.h.
m_cvode_mem
void* m_cvode_mem = nullptr private
Definition at line 94 of file CVodesIntegrator.h.
m_sundials_ctx
SundialsContext m_sundials_ctx private
SUNContext object for Sundials>=6.0.
Definition at line 95 of file CVodesIntegrator.h.
Referenced by CVodesIntegrator::applyOptions(), CVodesIntegrator::getErrorInfo(), CVodesIntegrator::initialize(), and CVodesIntegrator::setTolerances().
m_linsol
void* m_linsol = nullptr private
Sundials linear solver object.
Definition at line 96 of file CVodesIntegrator.h.
Referenced by CVodesIntegrator::applyOptions().
m_linsol_matrix
void* m_linsol_matrix = nullptr private
matrix used by Sundials
Definition at line 97 of file CVodesIntegrator.h.
Referenced by CVodesIntegrator::applyOptions().
m_func
FuncEval* m_func = nullptr private
Definition at line 98 of file CVodesIntegrator.h.
m_t0
double m_t0 = 0.0 private
Definition at line 99 of file CVodesIntegrator.h.
m_time
double m_time private
The current integrator time.
Definition at line 100 of file CVodesIntegrator.h.
Referenced by CVodesIntegrator::initialize(), CVodesIntegrator::integrate(), and CVodesIntegrator::step().
m_y
N_Vector m_y = nullptr private
Definition at line 101 of file CVodesIntegrator.h.
m_abstol
N_Vector m_abstol = nullptr private
Definition at line 102 of file CVodesIntegrator.h.
m_dky
N_Vector m_dky = nullptr private
Definition at line 103 of file CVodesIntegrator.h.
m_type
string m_type = "DENSE" private
Definition at line 104 of file CVodesIntegrator.h.
m_itol
int m_itol private
Definition at line 105 of file CVodesIntegrator.h.
m_method
int m_method private
Definition at line 106 of file CVodesIntegrator.h.
m_maxord
int m_maxord = 0 private
Definition at line 107 of file CVodesIntegrator.h.
m_reltol
double m_reltol = 1e-9 private
Definition at line 108 of file CVodesIntegrator.h.
m_abstols
double m_abstols = 1e-15 private
Definition at line 109 of file CVodesIntegrator.h.
m_reltolsens
double m_reltolsens = 1e-5 private
Definition at line 110 of file CVodesIntegrator.h.
m_abstolsens
double m_abstolsens = 1e-4 private
Definition at line 111 of file CVodesIntegrator.h.
m_nabs
size_t m_nabs = 0 private
Definition at line 112 of file CVodesIntegrator.h.
m_hmax
double m_hmax = 0.0 private
Definition at line 113 of file CVodesIntegrator.h.
m_hmin
double m_hmin = 0.0 private
Definition at line 114 of file CVodesIntegrator.h.
m_maxsteps
int m_maxsteps = 20000 private
Definition at line 115 of file CVodesIntegrator.h.
m_maxErrTestFails
int m_maxErrTestFails = 0 private
Definition at line 116 of file CVodesIntegrator.h.
m_yS
N_Vector* m_yS = nullptr private
Definition at line 117 of file CVodesIntegrator.h.
m_np
size_t m_np = 0 private
Definition at line 118 of file CVodesIntegrator.h.
m_mupper
int m_mupper = 0 private
Definition at line 119 of file CVodesIntegrator.h.
m_mlower
int m_mlower = 0 private
Definition at line 120 of file CVodesIntegrator.h.
m_sens_ok
bool m_sens_ok = false private
Indicates whether the sensitivities stored in m_yS have been updated for at the current integrator time.
Definition at line 123 of file CVodesIntegrator.h.
Referenced by CVodesIntegrator::integrate(), and CVodesIntegrator::step().
The documentation for this class was generated from the following files:
CVodesIntegrator.h
CVodesIntegrator.cpp