Cantera: StoichSubstance Class Reference
StoichSubstance Class Reference
Models of Phases of Matter » Thermodynamic Properties
Class StoichSubstance represents a stoichiometric (fixed composition) incompressible substance.
#include <StoichSubstance.h>
Public Member Functions
StoichSubstance (const std::string &infile="", const std::string &id="")
Construct and initialize a StoichSubstance ThermoPhase object directly from an input file.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
Mechanical Equation of State
virtual doublereal pressure () const
Report the Pressure. Units: Pa.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature. Units: Pa.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
Activities, Standard States, and Activity Concentrations
This section is largely handled by parent classes, since there is only one species.
Therefore, the activity is equal to one.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
Properties of the Standard State of the Species in the Solution
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Public Member Functions inherited from SingleSpeciesTP
SingleSpeciesTP ()=default
Base empty constructor.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *murt) const
Get the array of non-dimensional species chemical potentials.
virtual void getChemPotentials (doublereal *mu) const
Get the array of chemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar internal energies. Units: J/kmol.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropy. Units: J/kmol K.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the species partial molar Heat Capacities. Units: J/ kmol /K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vbar) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void setMassFractions (const doublereal *const y)
Mass fractions are fixed, with Y[0] = 1.0.
virtual void setMoleFractions (const doublereal *const x)
Mole fractions are fixed, with x[0] = 1.0.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_DP (double rho, double p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (double temp)
Set the internally stored temperature of the phase (K).
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Additional Inherited Members
Protected Member Functions inherited from SingleSpeciesTP
void _updateThermo () const
This internal routine calculates new species Cp0, H0, and S0 whenever the temperature has changed.
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes inherited from SingleSpeciesTP
double m_press = OneAtm
The current pressure of the solution (Pa). It gets initialized to 1 atm.
double m_p0 = OneAtm
double m_h0_RT
Dimensionless enthalpy at the (mtlast, m_p0)
double m_cp0_R
Dimensionless heat capacity at the (mtlast, m_p0)
double m_s0_R
Dimensionless entropy at the (mtlast, m_p0)
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Detailed Description
Class StoichSubstance represents a stoichiometric (fixed composition) incompressible substance.
This class internally changes the independent degree of freedom from density to pressure. This is necessary because the phase is incompressible. It uses a constant volume approximation.
Specification of Species Standard State Properties
This class inherits from SingleSpeciesTP. It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_0 \hat v\) is subtracted from the specified molar enthalpy to compute the molar internal energy. The entropy is assumed to be independent of the pressure.
The enthalpy function is given by the following relation.
  \f[
         h^o_k(T,P) =
             h^{ref}_k(T) + \tilde v \left( P - P_{ref} \right)
  \f]
For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_{ref} \tilde v\) is subtracted from the specified reference molar enthalpy to compute the molar internal energy.
  \f[
       u^o_k(T,P) = h^{ref}_k(T) - P_{ref} \tilde v
  \f]
The standard state heat capacity and entropy are independent of pressure. The standard state Gibbs free energy is obtained from the enthalpy and entropy functions.
Specification of Solution Thermodynamic Properties
All solution properties are obtained from the standard state species functions, since there is only one species in the phase.
Application within Kinetics Managers
The standard concentration is equal to 1.0. This means that the kinetics operator works on an (activities basis). Since this is a stoichiometric substance, this means that the concentration of this phase drops out of kinetics expressions.
An example of a reaction using this is a sticking coefficient reaction of a substance in an ideal gas phase on a surface with a bulk phase species in this phase. In this case, the rate of progress for this reaction, \(R_s \), may be expressed via the following equation:
\[ R_s = k_s C_{gas} \]
where the units for \(R_s \) are kmol m-2 s-1. \(C_{gas} \) has units of kmol m-3. Therefore, the kinetic rate constant, \(k_s \), has units of m s-1. Nowhere does the concentration of the bulk phase appear in the rate constant expression, since it's a stoichiometric phase and the activity is always equal to 1.0.
Definition at line 88 of file StoichSubstance.h.
Constructor & Destructor Documentation
StoichSubstance()
StoichSubstance (const std::string & infile = "", const std::string & id = "") explicit
Construct and initialize a StoichSubstance ThermoPhase object directly from an input file.
Parameters
infile name of the input file. If blank, an empty phase will be created.
id name of the phase id in the file. If this is blank, the first phase in the file is used.
Definition at line 20 of file StoichSubstance.cpp.
References ThermoPhase::initThermoFile().
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from SingleSpeciesTP.
Definition at line 102 of file StoichSubstance.h.
isCompressible()
virtual bool isCompressible () const inline virtual
Return whether phase represents a compressible substance.
Reimplemented from Phase.
Definition at line 106 of file StoichSubstance.h.
pressure()
doublereal pressure () const virtual
Report the Pressure. Units: Pa.
For an incompressible substance, the density is independent of pressure. This method simply returns the stored pressure value.
Reimplemented from Phase.
Definition at line 27 of file StoichSubstance.cpp.
References SingleSpeciesTP::m_press.
setPressure()
void setPressure (doublereal p) virtual
Set the pressure at constant temperature. Units: Pa.
For an incompressible substance, the density is independent of pressure. Therefore, this method only stores the specified pressure value. It does not modify the density.
Parameters
p Pressure (units - Pa)
Reimplemented from Phase.
Definition at line 32 of file StoichSubstance.cpp.
References SingleSpeciesTP::m_press.
isothermalCompressibility()
doublereal isothermalCompressibility () const virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented from ThermoPhase.
Definition at line 37 of file StoichSubstance.cpp.
thermalExpansionCoeff()
doublereal thermalExpansionCoeff () const virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented from ThermoPhase.
Definition at line 42 of file StoichSubstance.cpp.
standardConcentrationUnits()
Units standardConcentrationUnits () const virtual
Returns the units of the "standard concentration" for this phase.
These are the units of the values returned by the functions getActivityConcentrations() and standardConcentration(), which can vary between different ThermoPhase-derived classes, or change within a single class depending on input options. See the documentation for standardConcentration() for the derived class for specific details.
Reimplemented from ThermoPhase.
Definition at line 49 of file StoichSubstance.cpp.
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions.
For a stoichiometric substance, there is only one species, and the generalized concentration is 1.0.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 54 of file StoichSubstance.cpp.
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (that is, generalized) concentration. This phase assumes that the kinetics operator works on an dimensionless basis. Thus, the standard concentration is equal to 1.0.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns The standard Concentration as 1.0
Reimplemented from ThermoPhase.
Definition at line 59 of file StoichSubstance.cpp.
logStandardConc()
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 64 of file StoichSubstance.cpp.
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu0) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
For a stoichiometric substance, there is no activity term in the chemical potential expression, and therefore the standard chemical potential and the chemical potential are both equal to the molar Gibbs function.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu0 Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 71 of file StoichSubstance.cpp.
References StoichSubstance::getGibbs_RT(), and ThermoPhase::RT().
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 77 of file StoichSubstance.cpp.
References SingleSpeciesTP::getEnthalpy_RT_ref(), SingleSpeciesTP::m_press, Phase::molarDensity(), and ThermoPhase::RT().
Referenced by StoichSubstance::getGibbs_RT().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 84 of file StoichSubstance.cpp.
References SingleSpeciesTP::getEntropy_R_ref().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 89 of file StoichSubstance.cpp.
References StoichSubstance::getEnthalpy_RT(), and SingleSpeciesTP::m_s0_R.
Referenced by StoichSubstance::getStandardChemPotentials().
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 95 of file StoichSubstance.cpp.
References SingleSpeciesTP::_updateThermo(), and SingleSpeciesTP::m_cp0_R.
getIntEnergy_RT()
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_{ref} \hat v\) is subtracted from the specified reference molar enthalpy to compute the standard state molar internal energy.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 101 of file StoichSubstance.cpp.
References SingleSpeciesTP::_updateThermo(), SingleSpeciesTP::m_h0_RT, Phase::molarDensity(), and ThermoPhase::RT().
getIntEnergy_RT_ref()
void getIntEnergy_RT_ref (doublereal * urt) const virtual
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 109 of file StoichSubstance.cpp.
References SingleSpeciesTP::_updateThermo(), SingleSpeciesTP::m_h0_RT, Phase::molarDensity(), and ThermoPhase::RT().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from ThermoPhase.
Definition at line 117 of file StoichSubstance.cpp.
References Phase::assignDensity(), AnyMap::convert(), AnyMap::hasKey(), ThermoPhase::initThermo(), ThermoPhase::input(), ThermoPhase::m_input, Phase::m_kk, Phase::meanMolecularWeight(), ThermoPhase::refPressure(), Phase::species(), and Phase::speciesName().
getSpeciesParameters()
void getSpeciesParameters (const std::string & name, AnyMap & speciesNode) const virtual
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
Parameters
name Name of the species
speciesNode Mapping to be populated with parameters
Reimplemented from ThermoPhase.
Definition at line 153 of file StoichSubstance.cpp.
References Phase::density(), ThermoPhase::getSpeciesParameters(), Phase::meanMolecularWeight(), Phase::name(), Phase::species(), and Phase::speciesIndex().
The documentation for this class was generated from the following files:
StoichSubstance.h
StoichSubstance.cpp