Cantera: TimesConstant1 Class Reference
TimesConstant1 Class Reference
Functor Objects » Modified Functors
Implements the product of a function and a constant.
#include <Func1.h>
Public Member Functions
TimesConstant1 (Func1 &f1, double a)
TimesConstant1 (shared_ptr< Func1 > f1, double a)
TimesConstant1 (const TimesConstant1 &b)
TimesConstant1 & operator= (const TimesConstant1 &right)
virtual int ID () const
virtual string type () const
Returns a string describing the type of the function.
virtual doublereal isProportional (TimesConstant1 &other)
virtual doublereal isProportional (Func1 &other)
virtual doublereal eval (doublereal t) const
Evaluate the function.
virtual Func1 & duplicate () const
Duplicate the current function.
virtual Func1 & derivative () const
Creates a derivative to the current function.
virtual shared_ptr< Func1 > derivative3 () const
Creates a derivative to the current function.
virtual std::string write (const std::string &arg) const
Write LaTeX string describing function.
virtual int order () const
Return the order of the function, if it makes sense.
Public Member Functions inherited from Func1
Func1 (shared_ptr< Func1 > f1, shared_ptr< Func1 > f2)
Func1 (shared_ptr< Func1 > f1, double A)
Func1 (const Func1 &right)
Func1 & operator= (const Func1 &right)
virtual Func1 & duplicate () const
Duplicate the current function.
virtual int ID () const
virtual string type () const
Returns a string describing the type of the function.
string typeName () const
Returns a string with the class name of the functor.
doublereal operator() (doublereal t) const
Calls method eval to evaluate the function.
virtual doublereal eval (doublereal t) const
Evaluate the function.
virtual Func1 & derivative () const
Creates a derivative to the current function.
virtual shared_ptr< Func1 > derivative3 () const
Creates a derivative to the current function.
bool isIdentical (Func1 &other) const
Routine to determine if two functions are the same.
virtual doublereal isProportional (TimesConstant1 &other)
virtual doublereal isProportional (Func1 &other)
virtual std::string write (const std::string &arg) const
Write LaTeX string describing function.
doublereal c () const
Accessor function for the stored constant.
void setC (doublereal c)
Function to set the stored constant.
Func1 & func1 () const
accessor function for m_f1
shared_ptr< Func1 > func1_shared () const
Accessor function for m_f1_shared.
Func1 & func2 () const
accessor function for m_f2
shared_ptr< Func1 > func2_shared () const
Accessor function for m_f2_shared.
virtual int order () const
Return the order of the function, if it makes sense.
Func1 & func1_dup () const
Func1 & func2_dup () const
Func1 * parent () const
void setParent (Func1 *p)
Additional Inherited Members
Protected Attributes inherited from Func1
double m_c = 0.0
Func1 * m_f1 = nullptr
Func1 * m_f2 = nullptr
Func1 * m_parent = nullptr
shared_ptr< Func1 > m_f1_shared
shared_ptr< Func1 > m_f2_shared
Detailed Description
Implements the product of a function and a constant.
The functor class with type "times-constant" returns \(f(x) = a f_1(x) \).
Parameters
f1 Functor \(f_1(x) \)
a Constant \(a \)
Definition at line 801 of file Func1.h.
Constructor & Destructor Documentation
TimesConstant1() [1/3]
TimesConstant1 (Func1 & f1, double a) inline
Definition at line 804 of file Func1.h.
TimesConstant1() [2/3]
TimesConstant1 (shared_ptr< Func1 > f1, double a) inline
Definition at line 810 of file Func1.h.
~TimesConstant1()
virtual ~TimesConstant1 () inline virtual
Definition at line 812 of file Func1.h.
TimesConstant1() [3/3]
TimesConstant1 (const TimesConstant1 & b) inline
Definition at line 818 of file Func1.h.
Member Function Documentation
operator=()
TimesConstant1 & operator= (const TimesConstant1 & right) inline
Definition at line 823 of file Func1.h.
ID()
virtual int ID () const inline virtual
Deprecated:
To be removed after Cantera 3.0. Replaced by type.
Reimplemented from Func1.
Definition at line 833 of file Func1.h.
type()
virtual string type () const inline virtual
Returns a string describing the type of the function.
Since
New in Cantera 3.0.
Reimplemented from Func1.
Definition at line 836 of file Func1.h.
isProportional() [1/2]
virtual doublereal isProportional (TimesConstant1 & other) inline virtual
Reimplemented from Func1.
Definition at line 840 of file Func1.h.
isProportional() [2/2]
virtual doublereal isProportional (Func1 & other) inline virtual
Reimplemented from Func1.
Definition at line 848 of file Func1.h.
eval()
virtual doublereal eval (doublereal t) const inline virtual
Evaluate the function.
Reimplemented from Func1.
Definition at line 856 of file Func1.h.
References Func1::eval().
duplicate()
Func1 & duplicate () const virtual
Duplicate the current function.
This duplicates the current function, returning a reference to the newly created function.
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Reimplemented from Func1.
Definition at line 830 of file Func1.cpp.
References Func1::duplicate(), and Cantera::warn_deprecated().
derivative()
Func1 & derivative () const virtual
Creates a derivative to the current function.
This will create a new derivative function and return a reference to the function.
Deprecated:
To be changed after Cantera 3.0; for new behavior, see derivative3.
Reimplemented from Func1.
Definition at line 838 of file Func1.cpp.
References Func1::derivative(), and Cantera::warn_deprecated().
derivative3()
virtual shared_ptr< Func1 > derivative3 () const inline virtual
Creates a derivative to the current function.
This will create a new derivative function
Returns
shared pointer to new derivative function.
Since
New in Cantera 3.0.
Reimplemented from Func1.
Definition at line 863 of file Func1.h.
write()
string write (const std::string & arg) const virtual
Write LaTeX string describing function.
Reimplemented from Func1.
Definition at line 811 of file Func1.cpp.
References Func1::order(), TimesConstant1::order(), and Func1::write().
order()
virtual int order () const inline virtual
Return the order of the function, if it makes sense.
Reimplemented from Func1.
Definition at line 869 of file Func1.h.
Referenced by TimesConstant1::write().
The documentation for this class was generated from the following files:
Func1.h
Func1.cpp