Cantera: DomainFactory Class Reference
DomainFactory Class Reference
One-Dimensional Reacting Flows
Factory class to create domain objects.
#include <DomainFactory.h>
Public Member Functions
virtual void deleteFactory ()
Virtual abstract function that deletes the factory.
Public Member Functions inherited from Factory< Domain1D, shared_ptr< Solution >, const string & >
Domain1D * create (const std::string &name, Args... args)
Create an object using the object construction function corresponding to "name" and the provided constructor arguments.
void reg (const std::string &name, std::function< Domain1D *(Args...)> f)
Register a new object construction function.
void addAlias (const std::string &original, const std::string &alias)
Add an alias for an existing registered type.
std::string canonicalize (const std::string &name)
Get the canonical name registered for a type.
bool exists (const std::string &name) const
Returns true if name is registered with this factory.
Public Member Functions inherited from FactoryBase
virtual ~FactoryBase ()
destructor
Static Public Member Functions
static DomainFactory * factory ()
Return a pointer to the factory.
Static Public Member Functions inherited from FactoryBase
static void deleteFactories ()
static function that deletes all factories in the internal registry maintained in a static variable
Private Member Functions
DomainFactory ()
default constructor, which is defined as private
Static Private Attributes
static DomainFactory * s_factory = 0
Pointer to the single instance of the factory.
static std::mutex domain_mutex
Mutex for use when calling the factory.
Additional Inherited Members
Protected Member Functions inherited from Factory< Domain1D, shared_ptr< Solution >, const string & >
void addDeprecatedAlias (const std::string &original, const std::string &alias)
Add a deprecated alias for an existing registered type.
Protected Member Functions inherited from FactoryBase
FactoryBase ()
Constructor.
virtual void deleteFactory ()=0
Virtual abstract function that deletes the factory.
Detailed Description
Factory class to create domain objects.
This class is mainly used via the newDomain() function, for example:
shared_ptr<Domain1D> d1 = newDomain("Inlet", sol, "reactants");
Definition at line 24 of file DomainFactory.h.
Constructor & Destructor Documentation
DomainFactory()
DomainFactory () private
default constructor, which is defined as private
Definition at line 18 of file DomainFactory.cpp.
References Factory< Domain1D, shared_ptr< Solution >, const string & >::reg(), StFlow::setAxisymmetricFlow(), StFlow::setFreeFlow(), and StFlow::setUnstrainedFlow().
Referenced by DomainFactory::factory().
Member Function Documentation
factory()
DomainFactory * factory () static
Return a pointer to the factory.
On the first call, a new instance is created. Since there is no need to instantiate more than one factory, on all subsequent calls, a pointer to the existing factory is returned.
Definition at line 79 of file DomainFactory.cpp.
References DomainFactory::domain_mutex, DomainFactory::DomainFactory(), and DomainFactory::s_factory.
Referenced by Cantera::newDomain().
deleteFactory()
void deleteFactory () virtual
Virtual abstract function that deletes the factory.
This must be properly defined in child objects.
Implements FactoryBase.
Definition at line 88 of file DomainFactory.cpp.
References DomainFactory::domain_mutex, and DomainFactory::s_factory.
Member Data Documentation
s_factory
DomainFactory * s_factory = 0 static private
Pointer to the single instance of the factory.
Definition at line 38 of file DomainFactory.h.
Referenced by DomainFactory::deleteFactory(), and DomainFactory::factory().
domain_mutex
std::mutex domain_mutex static private
Mutex for use when calling the factory.
Definition at line 44 of file DomainFactory.h.
Referenced by DomainFactory::deleteFactory(), and DomainFactory::factory().
The documentation for this class was generated from the following files:
DomainFactory.h
DomainFactory.cpp