Cantera: Domain1D Class Reference
Domain1D Class Reference
One-Dimensional Reacting Flows
Base class for one-dimensional domains.
#include <Domain1D.h>
Public Member Functions
Domain1D (size_t nv=1, size_t points=1, double time=0.0)
Constructor.
Domain1D (const Domain1D &)=delete
Domain1D & operator= (const Domain1D &)=delete
int domainType ()
Domain type flag.
virtual string type () const
String indicating the domain implemented.
size_t domainIndex ()
The left-to-right location of this domain.
virtual bool isConnector ()
True if the domain is a connector domain.
void setSolution (shared_ptr< Solution > sol)
Set the solution manager.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
virtual void setTransport (shared_ptr< Transport > trans)
Set transport model to existing instance.
const OneDim & container () const
The container holding this domain.
void setContainer (OneDim *c, size_t index)
Specify the container object for this domain, and the position of this domain in the list.
void setBandwidth (int bw=-1)
Set the Jacobian bandwidth. See the discussion of method bandwidth().
size_t bandwidth ()
Set the Jacobian bandwidth for this domain.
virtual void init ()
virtual void setInitialState (doublereal *xlocal=0)
virtual void setState (size_t point, const doublereal *state, doublereal *x)
virtual void resetBadValues (double *xg)
virtual void resize (size_t nv, size_t np)
Refiner & refiner ()
Return a reference to the grid refiner.
size_t nComponents () const
Number of components at each grid point.
void checkComponentIndex (size_t n) const
Check that the specified component index is in range.
void checkComponentArraySize (size_t nn) const
Check that an array size is at least nComponents().
size_t nPoints () const
Number of grid points in this domain.
void checkPointIndex (size_t n) const
Check that the specified point index is in range.
void checkPointArraySize (size_t nn) const
Check that an array size is at least nPoints().
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
void setComponentName (size_t n, const std::string &name)
virtual size_t componentIndex (const std::string &name) const
index of component with name name.
void setBounds (size_t n, doublereal lower, doublereal upper)
void setTransientTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for time-stepping mode.
void setSteadyTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for steady-state mode.
doublereal rtol (size_t n)
Relative tolerance of the nth component.
doublereal atol (size_t n)
Absolute tolerance of the nth component.
double steady_rtol (size_t n)
Steady relative tolerance of the nth component.
double steady_atol (size_t n)
Steady absolute tolerance of the nth component.
double transient_rtol (size_t n)
Transient relative tolerance of the nth component.
double transient_atol (size_t n)
Transient absolute tolerance of the nth component.
doublereal upperBound (size_t n) const
Upper bound on the nth component.
doublereal lowerBound (size_t n) const
Lower bound on the nth component.
void initTimeInteg (doublereal dt, const doublereal *x0)
Prepare to do time stepping with time step dt.
void setSteadyMode ()
Prepare to solve the steady-state problem.
bool steady ()
True if in steady-state mode.
bool transient ()
True if not in steady-state mode.
void needJacUpdate ()
virtual void eval (size_t j, doublereal *x, doublereal *r, integer *mask, doublereal rdt=0.0)
Evaluate the residual function at point j.
size_t index (size_t n, size_t j) const
doublereal value (const doublereal *x, size_t n, size_t j) const
virtual void setJac (MultiJac *jac)
AnyMap serialize (const double *soln) const
Save the state of this domain as an AnyMap.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
shared_ptr< SolutionArray > toArray (bool normalize=false) const
Save the state of this domain to a SolutionArray.
void restore (const AnyMap &state, double *soln, int loglevel)
Restore the solution for this domain from an AnyMap.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
void fromArray (const shared_ptr< SolutionArray > &arr)
Restore the solution for this domain from a SolutionArray.
shared_ptr< Solution > solution () const
Return thermo/kinetics/transport manager used in the domain.
size_t size () const
void locate ()
Find the index of the first grid point in this domain, and the start of its variables in the global solution vector.
virtual size_t loc (size_t j=0) const
Location of the start of the local solution vector in the global solution vector,.
size_t firstPoint () const
The index of the first (that is, left-most) grid point belonging to this domain.
size_t lastPoint () const
The index of the last (that is, right-most) grid point belonging to this domain.
void linkLeft (Domain1D *left)
Set the left neighbor to domain 'left.
void linkRight (Domain1D *right)
Set the right neighbor to domain 'right.'.
void append (Domain1D *right)
Append domain 'right' to this one, and update all links.
Domain1D * left () const
Return a pointer to the left neighbor.
Domain1D * right () const
Return a pointer to the right neighbor.
double prevSoln (size_t n, size_t j) const
Value of component n at point j in the previous solution.
void setID (const std::string &s)
Specify an identifying tag for this domain.
std::string id () const
virtual void showSolution_s (std::ostream &s, const double *x)
virtual void showSolution (const double *x)
Print the solution.
virtual void show (std::ostream &s, const double *x)
Print the solution.
virtual void show (const double *x)
Print the solution.
doublereal z (size_t jlocal) const
doublereal zmin () const
doublereal zmax () const
void setProfile (const std::string &name, double *values, double *soln)
vector_fp & grid ()
const vector_fp & grid () const
doublereal grid (size_t point) const
virtual void setupGrid (size_t n, const doublereal *z)
called to set up initial grid, and after grid refinement
virtual void _getInitialSoln (doublereal *x)
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
virtual doublereal initialValue (size_t n, size_t j)
Initial value of solution component n at grid point j.
virtual void _finalize (const doublereal *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
void forceFullUpdate (bool update)
In some cases, for computational efficiency some properties (such as transport coefficients) may not be updated during Jacobian evaluations.
void setData (shared_ptr< vector< double > > &data)
Set shared data pointer.
Protected Member Functions
virtual AnyMap getMeta () const
Retrieve meta data.
virtual void setMeta (const AnyMap &meta)
Retrieve meta data.
Protected Attributes
shared_ptr< vector< double > > m_state
data pointer shared from OneDim
double m_rdt = 0.0
size_t m_nv = 0
size_t m_points
vector_fp m_slast
vector_fp m_max
vector_fp m_min
vector_fp m_rtol_ss
vector_fp m_rtol_ts
vector_fp m_atol_ss
vector_fp m_atol_ts
vector_fp m_z
OneDim * m_container = nullptr
size_t m_index
int m_type = 0
size_t m_iloc = 0
Starting location within the solution vector for unknowns that correspond to this domain.
size_t m_jstart = 0
Domain1D * m_left = nullptr
Domain1D * m_right = nullptr
std::string m_id
Identity tag for the domain.
std::unique_ptr< Refiner > m_refiner
std::vector< std::string > m_name
int m_bw = -1
bool m_force_full_update = false
shared_ptr< Solution > m_solution
Composite thermo/kinetics/transport handler.
Detailed Description
Base class for one-dimensional domains.
Definition at line 40 of file Domain1D.h.
Constructor & Destructor Documentation
Domain1D()
Domain1D (size_t nv = 1, size_t points = 1, double time = 0.0)
Constructor.
Parameters
nv Number of variables at each grid point.
points Number of grid points.
time (unused)
Definition at line 17 of file Domain1D.cpp.
References Domain1D::resize().
~Domain1D()
~Domain1D () virtual
Definition at line 22 of file Domain1D.cpp.
Member Function Documentation
domainType()
int domainType ()
Domain type flag.
Deprecated:
To be changed after Cantera 3.0; for new behavior, see type.
Definition at line 26 of file Domain1D.cpp.
References Domain1D::m_type, and Cantera::warn_deprecated().
type()
virtual string type () const inline virtual
String indicating the domain implemented.
Since
New in Cantera 3.0.
Todo:
Transition back to domainType after Cantera 3.0
Reimplemented in Boundary1D, Inlet1D, Empty1D, Symm1D, Outlet1D, OutletRes1D, Surf1D, ReactingSurf1D, IonFlow, and StFlow.
Definition at line 62 of file Domain1D.h.
Referenced by Domain1D::getMeta(), and Sim1D::show().
domainIndex()
size_t domainIndex () inline
The left-to-right location of this domain.
Definition at line 67 of file Domain1D.h.
Referenced by Surf1D::show().
isConnector()
virtual bool isConnector () inline virtual
True if the domain is a connector domain.
Reimplemented in Boundary1D.
Definition at line 72 of file Domain1D.h.
setSolution()
void setSolution (shared_ptr< Solution > sol) inline
Set the solution manager.
Since
New in Cantera 3.0.
Definition at line 78 of file Domain1D.h.
References Domain1D::m_solution.
setKinetics()
virtual void setKinetics (shared_ptr< Kinetics > kin) inline virtual
Set the kinetics manager.
Since
New in Cantera 3.0.
Reimplemented in ReactingSurf1D, and StFlow.
Definition at line 84 of file Domain1D.h.
setTransport()
virtual void setTransport (shared_ptr< Transport > trans) inline virtual
Set transport model to existing instance.
Since
New in Cantera 3.0.
Reimplemented in StFlow.
Definition at line 90 of file Domain1D.h.
container()
const OneDim & container () const inline
The container holding this domain.
Definition at line 95 of file Domain1D.h.
setContainer()
void setContainer (OneDim * c, size_t index) inline
Specify the container object for this domain, and the position of this domain in the list.
Definition at line 101 of file Domain1D.h.
Referenced by OneDim::addDomain().
setBandwidth()
void setBandwidth (int bw = -1) inline
Set the Jacobian bandwidth. See the discussion of method bandwidth().
Definition at line 107 of file Domain1D.h.
bandwidth()
size_t bandwidth () inline
Set the Jacobian bandwidth for this domain.
When class OneDim computes the bandwidth of the overall multi-domain problem (in OneDim::resize()), it calls this method for the bandwidth of each domain. If setBandwidth has not been called, then a negative bandwidth is returned, in which case OneDim assumes that this domain is dense – that is, at each point, all components depend on the value of all other components at that point. In this case, the bandwidth is bw = 2*nComponents() - 1. However, if this domain contains some components that are uncoupled from other components at the same point, then this default bandwidth may greatly overestimate the true bandwidth, with a substantial penalty in performance. For such domains, use method setBandwidth to specify the bandwidth before passing this domain to the Sim1D or OneDim constructor.
Definition at line 126 of file Domain1D.h.
Referenced by OneDim::resize().
init()
virtual void init () inline virtual
Initialize. This method is called by OneDim::init() for each domain once at the beginning of a simulation. Base class method does nothing, but may be overloaded.
Reimplemented in Boundary1D, Inlet1D, Empty1D, Symm1D, Outlet1D, OutletRes1D, Surf1D, and ReactingSurf1D.
Definition at line 135 of file Domain1D.h.
Referenced by OneDim::init().
setInitialState()
virtual void setInitialState (doublereal * xlocal = 0) inline virtual
Definition at line 137 of file Domain1D.h.
setState()
virtual void setState (size_t point, const doublereal * state, doublereal * x) inline virtual
Definition at line 138 of file Domain1D.h.
resetBadValues()
virtual void resetBadValues (double * xg) inline virtual
When called, this function should reset "bad" values in the state vector such as negative species concentrations. This function may be called after a failed solution attempt.
Reimplemented in ReactingSurf1D, and StFlow.
Definition at line 145 of file Domain1D.h.
resize()
void resize (size_t nv, size_t np) virtual
Resize the domain to have nv components and np grid points. This method is virtual so that subclasses can perform other actions required to resize the domain.
Reimplemented in IonFlow, and StFlow.
Definition at line 33 of file Domain1D.cpp.
References Domain1D::locate().
Referenced by Domain1D::Domain1D(), Domain1D::fromArray(), StFlow::resize(), Domain1D::setupGrid(), and StFlow::StFlow().
refiner()
Refiner & refiner () inline
Return a reference to the grid refiner.
Definition at line 155 of file Domain1D.h.
Referenced by Sim1D::getRefineCriteria(), Sim1D::maxGridPoints(), Sim1D::refine(), Sim1D::setGridMin(), Sim1D::setMaxGridPoints(), and Sim1D::setRefineCriteria().
nComponents()
size_t nComponents () const inline
Number of components at each grid point.
Definition at line 160 of file Domain1D.h.
Referenced by StFlow::asArray(), OneDim::component(), Domain1D::componentIndex(), Outlet1D::eval(), OutletRes1D::eval(), Surf1D::eval(), ReactingSurf1D::eval(), Domain1D::fromArray(), StFlow::fromArray(), Domain1D::getMeta(), Sim1D::refine(), OneDim::resize(), Sim1D::setFixedTemperature(), Sim1D::setInitialGuess(), Domain1D::setMeta(), and MultiNewton::step().
checkComponentIndex()
void checkComponentIndex (size_t n) const inline
Check that the specified component index is in range.
Throws an exception if n is greater than nComponents()-1
Definition at line 166 of file Domain1D.h.
checkComponentArraySize()
void checkComponentArraySize (size_t nn) const inline
Check that an array size is at least nComponents().
Throws an exception if nn is less than nComponents(). Used before calls which take an array pointer.
Definition at line 175 of file Domain1D.h.
nPoints()
size_t nPoints () const inline
Number of grid points in this domain.
Definition at line 182 of file Domain1D.h.
Referenced by StFlow::asArray(), Outlet1D::eval(), OutletRes1D::eval(), ReactingSurf1D::eval(), StFlow::fromArray(), Domain1D::getMeta(), Sim1D::refine(), OneDim::resize(), Sim1D::setFixedTemperature(), Sim1D::setFlatProfile(), StFlow::setMeta(), Sim1D::setProfile(), and MultiNewton::step().
checkPointIndex()
void checkPointIndex (size_t n) const inline
Check that the specified point index is in range.
Throws an exception if n is greater than nPoints()-1
Definition at line 188 of file Domain1D.h.
checkPointArraySize()
void checkPointArraySize (size_t nn) const inline
Check that an array size is at least nPoints().
Throws an exception if nn is less than nPoints(). Used before calls which take an array pointer.
Definition at line 197 of file Domain1D.h.
componentName()
std::string componentName (size_t n) const virtual
Name of the nth component. May be overloaded.
Reimplemented in ReactingSurf1D, and StFlow.
Definition at line 56 of file Domain1D.cpp.
Referenced by OneDim::component(), Domain1D::componentIndex(), Domain1D::getMeta(), Sim1D::setInitialGuess(), Domain1D::setMeta(), Domain1D::show(), and MultiNewton::step().
setComponentName()
void setComponentName (size_t n, const std::string & name) inline
Definition at line 206 of file Domain1D.h.
componentIndex()
size_t componentIndex (const std::string & name) const virtual
index of component with name name.
Reimplemented in StFlow.
Definition at line 65 of file Domain1D.cpp.
References Domain1D::componentName(), and Domain1D::nComponents().
setBounds()
void setBounds (size_t n, doublereal lower, doublereal upper) inline
Definition at line 213 of file Domain1D.h.
setTransientTolerances()
void setTransientTolerances (doublereal rtol, doublereal atol, size_t n = npos)
Set tolerances for time-stepping mode.
Parameters
rtol Relative tolerance
atol Absolute tolerance
n component index these tolerances apply to. If set to -1 (the default), these tolerances will be applied to all solution components.
Definition at line 76 of file Domain1D.cpp.
References Domain1D::atol(), Cantera::npos, and Domain1D::rtol().
setSteadyTolerances()
void setSteadyTolerances (doublereal rtol, doublereal atol, size_t n = npos)
Set tolerances for steady-state mode.
Parameters
rtol Relative tolerance
atol Absolute tolerance
n component index these tolerances apply to. If set to -1 (the default), these tolerances will be applied to all solution components.
Definition at line 89 of file Domain1D.cpp.
References Domain1D::atol(), Cantera::npos, and Domain1D::rtol().
rtol()
doublereal rtol (size_t n) inline
Relative tolerance of the nth component.
Definition at line 239 of file Domain1D.h.
Referenced by Domain1D::setSteadyTolerances(), and Domain1D::setTransientTolerances().
atol()
doublereal atol (size_t n) inline
Absolute tolerance of the nth component.
Definition at line 244 of file Domain1D.h.
Referenced by Domain1D::setSteadyTolerances(), and Domain1D::setTransientTolerances().
steady_rtol()
double steady_rtol (size_t n) inline
Steady relative tolerance of the nth component.
Definition at line 249 of file Domain1D.h.
steady_atol()
double steady_atol (size_t n) inline
Steady absolute tolerance of the nth component.
Definition at line 254 of file Domain1D.h.
transient_rtol()
double transient_rtol (size_t n) inline
Transient relative tolerance of the nth component.
Definition at line 259 of file Domain1D.h.
transient_atol()
double transient_atol (size_t n) inline
Transient absolute tolerance of the nth component.
Definition at line 264 of file Domain1D.h.
upperBound()
doublereal upperBound (size_t n) const inline
Upper bound on the nth component.
Definition at line 269 of file Domain1D.h.
lowerBound()
doublereal lowerBound (size_t n) const inline
Lower bound on the nth component.
Definition at line 274 of file Domain1D.h.
initTimeInteg()
void initTimeInteg (doublereal dt, const doublereal * x0) inline
Prepare to do time stepping with time step dt.
Copy the internally-stored solution at the last time step to array x0.
Definition at line 282 of file Domain1D.h.
References Domain1D::loc().
Referenced by OneDim::initTimeInteg().
setSteadyMode()
void setSteadyMode () inline
Prepare to solve the steady-state problem.
Set the internally-stored reciprocal of the time step to 0.0
Definition at line 291 of file Domain1D.h.
Referenced by OneDim::setSteadyMode().
steady()
bool steady () inline
True if in steady-state mode.
Definition at line 296 of file Domain1D.h.
transient()
bool transient () inline
True if not in steady-state mode.
Definition at line 301 of file Domain1D.h.
needJacUpdate()
void needJacUpdate ()
Set this if something has changed in the governing equations (for example, the value of a constant has been changed, so that the last-computed Jacobian is no longer valid.
Definition at line 102 of file Domain1D.cpp.
References OneDim::jacobian(), OneDim::saveStats(), and MultiJac::setAge().
Referenced by IonFlow::fixElectricField(), OutletRes1D::setMoleFractions(), and IonFlow::solveElectricField().
eval()
virtual void eval (size_t j, doublereal * x, doublereal * r, integer * mask, doublereal rdt = 0.0) inline virtual
Evaluate the residual function at point j.
If j == npos, evaluate the residual function at all points.
This function must be implemented in classes derived from Domain1D.
Parameters
j Grid point at which to update the residual
[in] x State vector
[out] r residual vector
[out] mask Boolean mask indicating whether each solution component has a time derivative (1) or not (0).
[in] rdt Reciprocal of the timestep (rdt=0 implies steady- state.)
Reimplemented in StFlow, Inlet1D, Empty1D, Symm1D, Outlet1D, OutletRes1D, Surf1D, and ReactingSurf1D.
Definition at line 325 of file Domain1D.h.
index()
size_t index (size_t n, size_t j) const inline
Definition at line 330 of file Domain1D.h.
value()
doublereal value (const doublereal * x, size_t n, size_t j) const inline
Definition at line 333 of file Domain1D.h.
setJac()
virtual void setJac (MultiJac * jac) inline virtual
Definition at line 337 of file Domain1D.h.
serialize()
AnyMap serialize (const double * soln) const
Save the state of this domain as an AnyMap.
Parameters
soln local solution vector for this domain
Deprecated:
To be removed after Cantera 3.0; superseded by asArray.
Definition at line 138 of file Domain1D.cpp.
References Domain1D::asArray(), and Cantera::warn_deprecated().
asArray()
virtual shared_ptr< SolutionArray > asArray (const double * soln) const inline virtual
Save the state of this domain as a SolutionArray.
Parameters
soln local solution vector for this domain
Todo:
Despite the method's name, data are copied; the intent is to access data directly in future revisions, where a non-const version will be implemented.
Since
New in Cantera 3.0.
Reimplemented in Inlet1D, Empty1D, Symm1D, Outlet1D, OutletRes1D, Surf1D, ReactingSurf1D, and StFlow.
Definition at line 355 of file Domain1D.h.
Referenced by Domain1D::serialize(), and Domain1D::toArray().
toArray()
shared_ptr< SolutionArray > toArray (bool normalize = false) const
Save the state of this domain to a SolutionArray.
This method serves as an external interface for high-level API's; it does not provide direct access to memory.
Parameters
normalize If true, normalize concentrations (default=false)
Since
New in Cantera 3.0.
Definition at line 148 of file Domain1D.cpp.
References Domain1D::asArray(), Domain1D::m_iloc, and Domain1D::m_state.
restore()
void restore (const AnyMap & state, double * soln, int loglevel)
Restore the solution for this domain from an AnyMap.
Parameters
[in] state AnyMap defining the state of this domain
[out] soln Value of the solution vector, local to this domain
[in] loglevel 0 to suppress all output; 1 to show warnings; 2 for verbose output
Deprecated:
To be removed after Cantera 3.0; restore from SolutionArray instead.
Definition at line 204 of file Domain1D.cpp.
References SolutionArray::create(), Domain1D::fromArray(), Domain1D::solution(), and Cantera::warn_deprecated().
fromArray() [1/2]
virtual void fromArray (SolutionArray & arr, double * soln) inline virtual
Restore the solution for this domain from a SolutionArray.
Parameters
[in] arr SolutionArray defining the state of this domain
[out] soln Value of the solution vector, local to this domain
Since
New in Cantera 3.0.
Reimplemented in Inlet1D, Empty1D, Symm1D, Outlet1D, OutletRes1D, Surf1D, ReactingSurf1D, and StFlow.
Definition at line 387 of file Domain1D.h.
Referenced by Domain1D::fromArray(), and Domain1D::restore().
fromArray() [2/2]
void fromArray (const shared_ptr< SolutionArray > & arr)
Restore the solution for this domain from a SolutionArray.
This method serves as an external interface for high-level API's.
Parameters
arr SolutionArray defining the state of this domain
Since
New in Cantera 3.0.
Definition at line 160 of file Domain1D.cpp.
References Domain1D::_finalize(), Domain1D::fromArray(), Domain1D::m_iloc, Domain1D::m_state, Domain1D::nComponents(), OneDim::resize(), and Domain1D::resize().
solution()
shared_ptr< Solution > solution () const inline
Return thermo/kinetics/transport manager used in the domain.
Since
New in Cantera 3.0.
Definition at line 401 of file Domain1D.h.
References Domain1D::m_solution.
Referenced by Domain1D::linkLeft(), Domain1D::linkRight(), and Domain1D::restore().
size()
size_t size () const inline
Definition at line 405 of file Domain1D.h.
locate()
void locate ()
Find the index of the first grid point in this domain, and the start of its variables in the global solution vector.
Definition at line 213 of file Domain1D.cpp.
References Domain1D::lastPoint(), Domain1D::loc(), Domain1D::locate(), and Domain1D::m_iloc.
Referenced by Domain1D::linkLeft(), Domain1D::locate(), and Domain1D::resize().
loc()
virtual size_t loc (size_t j = 0) const inline virtual
Location of the start of the local solution vector in the global solution vector,.
Definition at line 419 of file Domain1D.h.
References Domain1D::m_iloc.
Referenced by StFlow::eval(), Outlet1D::eval(), OutletRes1D::eval(), Surf1D::eval(), ReactingSurf1D::eval(), StFlow::fromArray(), Domain1D::initTimeInteg(), Domain1D::locate(), OneDim::pointDomain(), ReactingSurf1D::resetBadValues(), StFlow::resetBadValues(), OneDim::resize(), Sim1D::setValue(), MultiNewton::step(), and Sim1D::value().
firstPoint()
size_t firstPoint () const inline
The index of the first (that is, left-most) grid point belonging to this domain.
Definition at line 427 of file Domain1D.h.
Referenced by StFlow::eval(), Outlet1D::eval(), OutletRes1D::eval(), Surf1D::eval(), and ReactingSurf1D::eval().
lastPoint()
size_t lastPoint () const inline
The index of the last (that is, right-most) grid point belonging to this domain.
Definition at line 435 of file Domain1D.h.
Referenced by StFlow::eval(), Outlet1D::eval(), OutletRes1D::eval(), Surf1D::eval(), ReactingSurf1D::eval(), and Domain1D::locate().
linkLeft()
void linkLeft (Domain1D * left) inline
Set the left neighbor to domain 'left.
' Method 'locate' is called to update the global positions of this domain and all those to its right.
Definition at line 443 of file Domain1D.h.
References Domain1D::left(), Domain1D::locate(), Domain1D::m_solution, and Domain1D::solution().
Referenced by Domain1D::append().
linkRight()
void linkRight (Domain1D * right) inline
Set the right neighbor to domain 'right.'.
Definition at line 452 of file Domain1D.h.
References Domain1D::m_solution, Domain1D::right(), and Domain1D::solution().
Referenced by Domain1D::append().
append()
void append (Domain1D * right) inline
Append domain 'right' to this one, and update all links.
Definition at line 460 of file Domain1D.h.
References Domain1D::linkLeft(), Domain1D::linkRight(), and Domain1D::right().
left()
Domain1D * left () const inline
Return a pointer to the left neighbor.
Definition at line 466 of file Domain1D.h.
Referenced by Domain1D::linkLeft(), and OneDim::pointDomain().
right()
Domain1D * right () const inline
Return a pointer to the right neighbor.
Definition at line 471 of file Domain1D.h.
Referenced by Domain1D::append(), OneDim::init(), OneDim::initTimeInteg(), Domain1D::linkRight(), and OneDim::setSteadyMode().
prevSoln()
double prevSoln (size_t n, size_t j) const inline
Value of component n at point j in the previous solution.
Definition at line 476 of file Domain1D.h.
Referenced by ReactingSurf1D::eval().
setID()
void setID (const std::string & s) inline
Specify an identifying tag for this domain.
Definition at line 481 of file Domain1D.h.
References Domain1D::m_id.
id()
std::string id () const inline
Definition at line 485 of file Domain1D.h.
showSolution_s()
void showSolution_s (std::ostream & s, const double * x) virtual
Deprecated:
To be removed after Cantera 3.0; replaced by show
Definition at line 243 of file Domain1D.cpp.
References Domain1D::show(), and Cantera::warn_deprecated().
showSolution()
void showSolution (const double * x) virtual
Print the solution.
Deprecated:
To be removed after Cantera 3.0; replaced by show
Definition at line 250 of file Domain1D.cpp.
References Domain1D::show(), and Cantera::warn_deprecated().
show() [1/2]
virtual void show (std::ostream & s, const double * x) inline virtual
Print the solution.
Reimplemented in Surf1D.
Definition at line 501 of file Domain1D.h.
Referenced by StFlow::show(), Sim1D::show(), Domain1D::showSolution(), and Domain1D::showSolution_s().
show() [2/2]
void show (const double * x) virtual
Print the solution.
Reimplemented in Inlet1D, Empty1D, OutletRes1D, Surf1D, ReactingSurf1D, and StFlow.
Definition at line 257 of file Domain1D.cpp.
References Domain1D::componentName(), and Cantera::writelog().
z()
doublereal z (size_t jlocal) const inline
Definition at line 506 of file Domain1D.h.
zmin()
doublereal zmin () const inline
Definition at line 509 of file Domain1D.h.
zmax()
doublereal zmax () const inline
Definition at line 512 of file Domain1D.h.
setProfile()
void setProfile (const std::string & name, double * values, double * soln)
Definition at line 293 of file Domain1D.cpp.
grid() [1/3]
vector_fp & grid () inline
Definition at line 518 of file Domain1D.h.
grid() [2/3]
const vector_fp & grid () const inline
Definition at line 521 of file Domain1D.h.
grid() [3/3]
doublereal grid (size_t point) const inline
Definition at line 524 of file Domain1D.h.
setupGrid()
void setupGrid (size_t n, const doublereal * z) virtual
called to set up initial grid, and after grid refinement
Reimplemented in Boundary1D, and StFlow.
Definition at line 233 of file Domain1D.cpp.
References Domain1D::resize().
Referenced by Sim1D::refine(), Sim1D::restoreSteadySolution(), and Sim1D::setFixedTemperature().
_getInitialSoln()
void _getInitialSoln (doublereal * x) virtual
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
This method is called by the Sim1D constructor, and allows default values or ones that have been set locally prior to installing this domain into the container to be written to the global solution vector.
Reimplemented in ReactingSurf1D, and StFlow.
Definition at line 306 of file Domain1D.cpp.
References Domain1D::initialValue().
Referenced by Sim1D::Sim1D().
initialValue()
doublereal initialValue (size_t n, size_t j) virtual
Initial value of solution component n at grid point j.
Definition at line 315 of file Domain1D.cpp.
Referenced by Domain1D::_getInitialSoln().
_finalize()
virtual void _finalize (const doublereal * x) inline virtual
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
In such cases, the parameters may be set in method _finalize. This method is called just before the Newton solver is called, and the x array is guaranteed to be the local solution vector for this domain that will be used as the initial guess. If no such parameters need to be set, then method _finalize does not need to be overloaded.
Reimplemented in ReactingSurf1D, IonFlow, and StFlow.
Definition at line 551 of file Domain1D.h.
Referenced by Sim1D::finalize(), and Domain1D::fromArray().
forceFullUpdate()
void forceFullUpdate (bool update) inline
In some cases, for computational efficiency some properties (such as transport coefficients) may not be updated during Jacobian evaluations.
Set this to true to force these properties to be updated even while calculating Jacobian elements.
Definition at line 559 of file Domain1D.h.
setData()
void setData (shared_ptr< vector< double > > & data) inline
Set shared data pointer.
Definition at line 564 of file Domain1D.h.
References Domain1D::m_state.
Referenced by OneDim::addDomain().
getMeta()
AnyMap getMeta () const protected virtual
Retrieve meta data.
Reimplemented in StFlow.
Definition at line 110 of file Domain1D.cpp.
References Domain1D::componentName(), Domain1D::nComponents(), Domain1D::nPoints(), and Domain1D::type().
Referenced by Outlet1D::asArray(), OutletRes1D::asArray(), Surf1D::asArray(), ReactingSurf1D::asArray(), and StFlow::getMeta().
setMeta()
void setMeta (const AnyMap & meta) protected virtual
Retrieve meta data.
Reimplemented in StFlow.
Definition at line 172 of file Domain1D.cpp.
References Domain1D::componentName(), AnyValue::hasKey(), AnyMap::hasKey(), Domain1D::nComponents(), and Cantera::warn_user().
Referenced by OutletRes1D::fromArray(), Surf1D::fromArray(), ReactingSurf1D::fromArray(), and StFlow::fromArray().
Member Data Documentation
m_state
shared_ptr<vector<double> > m_state protected
data pointer shared from OneDim
Definition at line 575 of file Domain1D.h.
Referenced by Domain1D::fromArray(), Domain1D::setData(), and Domain1D::toArray().
m_rdt
double m_rdt = 0.0 protected
Definition at line 577 of file Domain1D.h.
m_nv
size_t m_nv = 0 protected
Definition at line 578 of file Domain1D.h.
m_points
size_t m_points protected
Definition at line 579 of file Domain1D.h.
m_slast
vector_fp m_slast protected
Definition at line 580 of file Domain1D.h.
m_max
vector_fp m_max protected
Definition at line 581 of file Domain1D.h.
m_min
vector_fp m_min protected
Definition at line 582 of file Domain1D.h.
m_rtol_ss
vector_fp m_rtol_ss protected
Definition at line 583 of file Domain1D.h.
m_rtol_ts
vector_fp m_rtol_ts protected
Definition at line 583 of file Domain1D.h.
m_atol_ss
vector_fp m_atol_ss protected
Definition at line 584 of file Domain1D.h.
m_atol_ts
vector_fp m_atol_ts protected
Definition at line 584 of file Domain1D.h.
m_z
vector_fp m_z protected
Definition at line 585 of file Domain1D.h.
m_container
OneDim* m_container = nullptr protected
Definition at line 586 of file Domain1D.h.
m_index
size_t m_index protected
Definition at line 587 of file Domain1D.h.
m_type
int m_type = 0 protected
Deprecated:
To be removed after Cantera 3.0
Definition at line 588 of file Domain1D.h.
Referenced by Domain1D::domainType(), StFlow::flowType(), StFlow::setAxisymmetricFlow(), StFlow::setFreeFlow(), StFlow::setUnstrainedFlow(), and StFlow::StFlow().
m_iloc
size_t m_iloc = 0 protected
Starting location within the solution vector for unknowns that correspond to this domain.
Remember there may be multiple domains associated with this problem
Definition at line 595 of file Domain1D.h.
Referenced by Domain1D::fromArray(), Domain1D::loc(), Domain1D::locate(), and Domain1D::toArray().
m_jstart
size_t m_jstart = 0 protected
Definition at line 597 of file Domain1D.h.
m_left
Domain1D* m_left = nullptr protected
Definition at line 599 of file Domain1D.h.
m_right
Domain1D* m_right = nullptr protected
Definition at line 600 of file Domain1D.h.
m_id
std::string m_id protected
Identity tag for the domain.
Definition at line 603 of file Domain1D.h.
Referenced by IonFlow::IonFlow(), Domain1D::setID(), and StFlow::StFlow().
m_refiner
std::unique_ptr<Refiner> m_refiner protected
Definition at line 604 of file Domain1D.h.
m_name
std::vector<std::string> m_name protected
Definition at line 605 of file Domain1D.h.
m_bw
int m_bw = -1 protected
Definition at line 606 of file Domain1D.h.
m_force_full_update
bool m_force_full_update = false protected
Definition at line 607 of file Domain1D.h.
m_solution
shared_ptr<Solution> m_solution protected
Composite thermo/kinetics/transport handler.
Definition at line 610 of file Domain1D.h.
Referenced by Outlet1D::asArray(), OutletRes1D::asArray(), Surf1D::asArray(), ReactingSurf1D::asArray(), StFlow::asArray(), IonFlow::IonFlow(), Domain1D::linkLeft(), Domain1D::linkRight(), ReactingSurf1D::setKinetics(), StFlow::setKinetics(), Domain1D::setSolution(), StFlow::setTransport(), StFlow::setTransportModel(), Domain1D::solution(), and StFlow::StFlow().
The documentation for this class was generated from the following files:
Domain1D.h
Domain1D.cpp