Cantera: YamlWriter Class Reference
YamlWriter Class Reference
A class for generating full YAML input files from multiple data sources.
#include <YamlWriter.h>
Public Member Functions
void setHeader (const AnyMap &header)
Include top-level information used in YAML header block.
void addPhase (shared_ptr< Solution > soln, bool includeAdjacent=true)
Include a phase definition for the specified Solution object.
void addPhase (shared_ptr< ThermoPhase > thermo, shared_ptr< Kinetics > kin={}, shared_ptr< Transport > tran={})
Include a phase definition using the specified ThermoPhase, (optional) Kinetics, and (optional) Transport objects.
std::string toYamlString () const
Return a YAML string that contains the definitions for the added phases, species, and reactions.
void toYamlFile (const std::string &filename) const
Write the definitions for the added phases, species and reactions to the specified file.
void setPrecision (long int n)
For output floating point values, set the maximum number of digits to the right of the decimal point.
void skipUserDefined (bool skip=true)
By default user-defined data present in the input is preserved on output.
void setUnits (const std::map< std::string, std::string > &units={})
Set the units to be used in the output file.
void setUnitSystem (const UnitSystem &units=UnitSystem())
Set the units to be used in the output file.
Protected Attributes
AnyMap m_header
Top-level information used in YAML header block.
std::vector< shared_ptr< Solution > > m_phases
long int m_float_precision = 15
See setPrecision()
bool m_skip_user_defined = false
See skipUserDefined()
UnitSystem m_output_units
Top-level units directive for the output file.
Detailed Description
A class for generating full YAML input files from multiple data sources.
Definition at line 22 of file YamlWriter.h.
Member Function Documentation
setHeader()
void setHeader (const AnyMap & header)
Include top-level information used in YAML header block.
Definition at line 19 of file YamlWriter.cpp.
References YamlWriter::m_header.
addPhase() [1/2]
void addPhase (shared_ptr< Solution > soln, bool includeAdjacent = true)
Include a phase definition for the specified Solution object.
Definition at line 23 of file YamlWriter.cpp.
References YamlWriter::addPhase().
Referenced by YamlWriter::addPhase().
addPhase() [2/2]
void addPhase (shared_ptr< ThermoPhase > thermo, shared_ptr< Kinetics > kin = {}, shared_ptr< Transport > tran = {})
Include a phase definition using the specified ThermoPhase, (optional) Kinetics, and (optional) Transport objects.
Definition at line 45 of file YamlWriter.cpp.
References YamlWriter::addPhase(), and Solution::create().
toYamlString()
std::string toYamlString () const
Return a YAML string that contains the definitions for the added phases, species, and reactions.
Definition at line 55 of file YamlWriter.cpp.
References Cantera::gitCommit(), AnyMap::hasKey(), YamlWriter::m_float_precision, YamlWriter::m_header, YamlWriter::m_output_units, YamlWriter::m_skip_user_defined, AnyBase::setLoc(), AnyMap::setMetadata(), AnyMap::setUnits(), AnyMap::size(), and Cantera::trimCopy().
Referenced by YamlWriter::toYamlFile().
toYamlFile()
void toYamlFile (const std::string & filename) const
Write the definitions for the added phases, species and reactions to the specified file.
Definition at line 189 of file YamlWriter.cpp.
References YamlWriter::toYamlString().
setPrecision()
void setPrecision (long int n) inline
For output floating point values, set the maximum number of digits to the right of the decimal point.
The default is 15 digits.
Definition at line 48 of file YamlWriter.h.
References YamlWriter::m_float_precision.
skipUserDefined()
void skipUserDefined (bool skip = true) inline
By default user-defined data present in the input is preserved on output.
This method can be used to skip output of user-defined data fields which are not directly used by Cantera.
Definition at line 55 of file YamlWriter.h.
References YamlWriter::m_skip_user_defined.
setUnits()
void setUnits (const std::map< std::string, std::string > & units = {})
Set the units to be used in the output file.
Dimensions not specified will use Cantera's defaults.
Parameters
units A map where keys are dimensions (mass, length, time, quantity, pressure, energy, activation-energy) and the values are corresponding units supported by the UnitSystem class.
Definition at line 195 of file YamlWriter.cpp.
References YamlWriter::m_output_units, and UnitSystem::setDefaults().
setUnitSystem()
void setUnitSystem (const UnitSystem & units = UnitSystem())
Set the units to be used in the output file.
Dimensions not specified will use Cantera's defaults.
Parameters
units A UnitSystem object specifying dimensions (mass, length, time, quantity, pressure, energy, activation-energy).
Definition at line 201 of file YamlWriter.cpp.
References YamlWriter::m_output_units.
Member Data Documentation
m_header
AnyMap m_header protected
Top-level information used in YAML header block.
Definition at line 74 of file YamlWriter.h.
Referenced by YamlWriter::setHeader(), and YamlWriter::toYamlString().
m_phases
std::vector<shared_ptr<Solution> > m_phases protected
Definition at line 76 of file YamlWriter.h.
m_float_precision
long int m_float_precision = 15 protected
See setPrecision()
Definition at line 79 of file YamlWriter.h.
Referenced by YamlWriter::setPrecision(), and YamlWriter::toYamlString().
m_skip_user_defined
bool m_skip_user_defined = false protected
See skipUserDefined()
Definition at line 82 of file YamlWriter.h.
Referenced by YamlWriter::skipUserDefined(), and YamlWriter::toYamlString().
m_output_units
UnitSystem m_output_units protected
Top-level units directive for the output file.
Defaults to Cantera's native SI+kmol system.
Definition at line 86 of file YamlWriter.h.
Referenced by YamlWriter::setUnits(), YamlWriter::setUnitSystem(), and YamlWriter::toYamlString().
The documentation for this class was generated from the following files:
YamlWriter.h
YamlWriter.cpp