Cantera: Func1 Class Reference
Func1 Class Reference
Functor Objects
Base class for 'functor' classes that evaluate a function of one variable.
#include <Func1.h>
Public Member Functions
Func1 (shared_ptr< Func1 > f1, shared_ptr< Func1 > f2)
Func1 (shared_ptr< Func1 > f1, double A)
Func1 (const Func1 &right)
Func1 & operator= (const Func1 &right)
virtual Func1 & duplicate () const
Duplicate the current function.
virtual int ID () const
virtual string type () const
Returns a string describing the type of the function.
string typeName () const
Returns a string with the class name of the functor.
doublereal operator() (doublereal t) const
Calls method eval to evaluate the function.
virtual doublereal eval (doublereal t) const
Evaluate the function.
virtual Func1 & derivative () const
Creates a derivative to the current function.
virtual shared_ptr< Func1 > derivative3 () const
Creates a derivative to the current function.
bool isIdentical (Func1 &other) const
Routine to determine if two functions are the same.
virtual doublereal isProportional (TimesConstant1 &other)
virtual doublereal isProportional (Func1 &other)
virtual std::string write (const std::string &arg) const
Write LaTeX string describing function.
doublereal c () const
Accessor function for the stored constant.
void setC (doublereal c)
Function to set the stored constant.
Func1 & func1 () const
accessor function for m_f1
shared_ptr< Func1 > func1_shared () const
Accessor function for m_f1_shared.
Func1 & func2 () const
accessor function for m_f2
shared_ptr< Func1 > func2_shared () const
Accessor function for m_f2_shared.
virtual int order () const
Return the order of the function, if it makes sense.
Func1 & func1_dup () const
Func1 & func2_dup () const
Func1 * parent () const
void setParent (Func1 *p)
Protected Attributes
double m_c = 0.0
Func1 * m_f1 = nullptr
Func1 * m_f2 = nullptr
Func1 * m_parent = nullptr
shared_ptr< Func1 > m_f1_shared
shared_ptr< Func1 > m_f2_shared
Detailed Description
Base class for 'functor' classes that evaluate a function of one variable.
Definition at line 94 of file Func1.h.
Constructor & Destructor Documentation
Func1() [1/3]
Func1 (shared_ptr< Func1 > f1, shared_ptr< Func1 > f2) inline
Definition at line 99 of file Func1.h.
Func1() [2/3]
Func1 (shared_ptr< Func1 > f1, double A) inline
Definition at line 106 of file Func1.h.
Func1() [3/3]
Func1 (const Func1 & right)
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 16 of file Func1.cpp.
Member Function Documentation
operator=()
Func1 & operator= (const Func1 & right)
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 24 of file Func1.cpp.
duplicate()
Func1 & duplicate () const virtual
Duplicate the current function.
This duplicates the current function, returning a reference to the newly created function.
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Reimplemented in Sin1, Cos1, Exp1, Pow1, Tabulated1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, Composite1, Gaussian, Poly1, Fourier1, Arrhenius1, and Periodic1.
Definition at line 36 of file Func1.cpp.
References Cantera::warn_deprecated().
Referenced by Product1::derivative(), Ratio1::derivative(), Composite1::derivative(), Sum1::duplicate(), Diff1::duplicate(), Product1::duplicate(), TimesConstant1::duplicate(), PlusConstant1::duplicate(), Ratio1::duplicate(), Composite1::duplicate(), Func1::func1_dup(), and Func1::func2_dup().
ID()
int ID () const virtual
Deprecated:
To be removed after Cantera 3.0. Replaced by type.
Reimplemented in Sin1, Cos1, Exp1, Pow1, Tabulated1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, and Composite1.
Definition at line 44 of file Func1.cpp.
Referenced by Func1::derivative(), and Func1::isIdentical().
type()
virtual string type () const inline virtual
Returns a string describing the type of the function.
Since
New in Cantera 3.0.
Reimplemented in Sin1, Cos1, Exp1, Log1, Pow1, Tabulated1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, Composite1, Gaussian1, Poly1, Fourier1, Arrhenius1, and Periodic1.
Definition at line 131 of file Func1.h.
Referenced by Func1::write().
typeName()
string typeName () const
Returns a string with the class name of the functor.
Since
New in Cantera 3.0.
Definition at line 49 of file Func1.cpp.
References Cantera::demangle().
operator()()
doublereal operator() (doublereal t) const
Calls method eval to evaluate the function.
Definition at line 55 of file Func1.cpp.
References Func1::eval().
eval()
doublereal eval (doublereal t) const virtual
Evaluate the function.
Reimplemented in Log1, Tabulated1, Sin1, Cos1, Exp1, Pow1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, Composite1, Gaussian1, Poly1, Fourier1, Arrhenius1, and Periodic1.
Definition at line 61 of file Func1.cpp.
Referenced by Sum1::eval(), Diff1::eval(), Product1::eval(), TimesConstant1::eval(), PlusConstant1::eval(), Ratio1::eval(), Composite1::eval(), Periodic1::eval(), OneDim::eval(), FlowDevice::evalPressureFunction(), FlowDevice::evalTimeFunction(), Func1::operator()(), OneDim::timeStep(), MassFlowController::updateMassFlowRate(), PressureController::updateMassFlowRate(), and Valve::updateMassFlowRate().
derivative()
Func1 & derivative () const virtual
Creates a derivative to the current function.
This will create a new derivative function and return a reference to the function.
Deprecated:
To be changed after Cantera 3.0; for new behavior, see derivative3.
Reimplemented in Sin1, Cos1, Exp1, Pow1, Tabulated1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, and Composite1.
Definition at line 66 of file Func1.cpp.
References Func1::ID(), Cantera::warn_deprecated(), and Func1::write().
Referenced by Sum1::derivative(), Diff1::derivative(), Product1::derivative(), TimesConstant1::derivative(), PlusConstant1::derivative(), Ratio1::derivative(), and Composite1::derivative().
derivative3()
shared_ptr< Func1 > derivative3 () const virtual
Creates a derivative to the current function.
This will create a new derivative function
Returns
shared pointer to new derivative function.
Since
New in Cantera 3.0.
Reimplemented in Sin1, Cos1, Exp1, Log1, Pow1, Tabulated1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, and Composite1.
Definition at line 75 of file Func1.cpp.
isIdentical()
bool isIdentical (Func1 & other) const
Routine to determine if two functions are the same.
Two functions are the same if they are the same function. This means that the ID and stored constant is the same. This means that the m_f1 and m_f2 are identical if they are non-null.
Definition at line 81 of file Func1.cpp.
References Func1::ID(), and Func1::isIdentical().
Referenced by Func1::isIdentical().
isProportional() [1/2]
doublereal isProportional (TimesConstant1 & other) virtual
Definition at line 869 of file Func1.cpp.
isProportional() [2/2]
doublereal isProportional (Func1 & other) virtual
Definition at line 876 of file Func1.cpp.
write()
string write (const std::string & arg) const virtual
Write LaTeX string describing function.
Reimplemented in Sin1, Cos1, Exp1, Pow1, Tabulated1, Const1, Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, Composite1, and Log1.
Definition at line 618 of file Func1.cpp.
References Func1::type().
Referenced by Func1::derivative(), Sum1::write(), Diff1::write(), Product1::write(), TimesConstant1::write(), PlusConstant1::write(), Ratio1::write(), and Composite1::write().
c()
doublereal c () const
Accessor function for the stored constant.
accessor function for the returned constant
Definition at line 106 of file Func1.cpp.
Referenced by Sin1::derivative(), Sin1::derivative3(), and Func1::setC().
setC()
void setC (doublereal c)
Function to set the stored constant.
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 112 of file Func1.cpp.
References Func1::c().
func1()
Func1 & func1 () const
accessor function for m_f1
Deprecated:
To be removed after Cantera 3.0; replaced by func1_shared.
Definition at line 118 of file Func1.cpp.
func1_shared()
shared_ptr< Func1 > func1_shared () const inline
Accessor function for m_f1_shared.
Since
New in Cantera 3.0.
Definition at line 188 of file Func1.h.
func2()
Func1 & func2 () const
accessor function for m_f2
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 123 of file Func1.cpp.
func2_shared()
shared_ptr< Func1 > func2_shared () const inline
Accessor function for m_f2_shared.
Since
New in Cantera 3.0.
Definition at line 198 of file Func1.h.
order()
int order () const virtual
Return the order of the function, if it makes sense.
Reimplemented in Sum1, Diff1, Product1, TimesConstant1, PlusConstant1, Ratio1, and Composite1.
Definition at line 128 of file Func1.cpp.
Referenced by Product1::write(), and TimesConstant1::write().
func1_dup()
Func1 & func1_dup () const
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 133 of file Func1.cpp.
References Func1::duplicate().
func2_dup()
Func1 & func2_dup () const
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 138 of file Func1.cpp.
References Func1::duplicate().
parent()
Func1 * parent () const
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 143 of file Func1.cpp.
setParent()
void setParent (Func1 * p)
Deprecated:
To be removed after Cantera 3.0. Only used by deprecated methods.
Definition at line 148 of file Func1.cpp.
Member Data Documentation
m_c
double m_c = 0.0 protected
Definition at line 218 of file Func1.h.
m_f1
Func1* m_f1 = nullptr protected
Definition at line 219 of file Func1.h.
m_f2
Func1* m_f2 = nullptr protected
Definition at line 220 of file Func1.h.
m_parent
Func1* m_parent = nullptr protected
Definition at line 221 of file Func1.h.
m_f1_shared
shared_ptr<Func1> m_f1_shared protected
Definition at line 223 of file Func1.h.
m_f2_shared
shared_ptr<Func1> m_f2_shared protected
Definition at line 224 of file Func1.h.
The documentation for this class was generated from the following files:
Func1.h
Func1.cpp