Cantera: ReactionPathDiagram Class Reference
ReactionPathDiagram Class Reference
Reaction path diagrams (graphs).
#include <ReactionPath.h>
Public Member Functions
virtual ~ReactionPathDiagram ()
Destructor.
doublereal maxFlow ()
The largest one-way flow value in any path.
doublereal netFlow (size_t k1, size_t k2)
The net flow from node k1 to node k2.
doublereal flow (size_t k1, size_t k2)
The one-way flow from node k1 to node k2.
bool hasNode (size_t k)
True if a node for species k exists.
void writeData (std::ostream &s)
void exportToDot (std::ostream &s)
Export the reaction path diagram.
void add (ReactionPathDiagram &d)
SpeciesNode * node (size_t k)
Path * path (size_t k1, size_t k2)
Path * path (size_t n)
size_t nPaths ()
size_t nNodes ()
void addNode (size_t k, const std::string &nm, doublereal x=0.0)
void displayOnly (size_t k=npos)
void linkNodes (size_t k1, size_t k2, size_t rxn, doublereal value, std::string legend="")
void include (const std::string &aaname)
void exclude (const std::string &aaname)
void include (std::vector< std::string > &names)
void exclude (std::vector< std::string > &names)
std::vector< std::string > & included ()
std::vector< std::string > & excluded ()
std::vector< size_t > species ()
vector_int reactions ()
void findMajorPaths (doublereal threshold, size_t lda, doublereal *a)
void setFont (const std::string &font)
Public Attributes
string title
string bold_color = "blue"
string normal_color = "steelblue"
string dashed_color = "gray"
string element
string m_font = "Helvetica"
double threshold = 0.005
double bold_min = 0.2
double dashed_max = 0.0
double label_min = 0.0
double x_size = -1.0
double y_size = -1.0
string name = "reaction_paths"
string dot_options = "center=1;"
flow_t flow_type = NetFlow
double scale = -1
double arrow_width = -5.0
bool show_details = false
double arrow_hue = 0.6666
Protected Attributes
double m_flxmax = 0.0
std::map< size_t, std::map< size_t, Path * > > m_paths
map< size_t, SpeciesNode * > m_nodes
map of species index to SpeciesNode
std::vector< Path * > m_pathlist
std::vector< std::string > m_include
std::vector< std::string > m_exclude
std::vector< size_t > m_speciesNumber
set< size_t > m_rxns
Indices of reactions that are included in the diagram.
size_t m_local = npos
Detailed Description
Reaction path diagrams (graphs).
Definition at line 160 of file ReactionPath.h.
Constructor & Destructor Documentation
~ReactionPathDiagram()
~ReactionPathDiagram () virtual
Destructor.
Deletes all nodes and paths in the diagram.
Definition at line 82 of file ReactionPath.cpp.
References ReactionPathDiagram::m_nodes.
Member Function Documentation
maxFlow()
doublereal maxFlow () inline
The largest one-way flow value in any path.
Definition at line 171 of file ReactionPath.h.
netFlow()
doublereal netFlow (size_t k1, size_t k2) inline
The net flow from node k1 to node k2.
Definition at line 176 of file ReactionPath.h.
References ReactionPathDiagram::flow().
Referenced by ReactionPathDiagram::exportToDot().
flow()
doublereal flow (size_t k1, size_t k2) inline
The one-way flow from node k1 to node k2.
Definition at line 181 of file ReactionPath.h.
References ReactionPathDiagram::flow().
Referenced by ReactionPathDiagram::exportToDot(), ReactionPathDiagram::flow(), and ReactionPathDiagram::netFlow().
hasNode()
bool hasNode (size_t k) inline
True if a node for species k exists.
Definition at line 186 of file ReactionPath.h.
References ReactionPathDiagram::m_nodes.
writeData()
void writeData (std::ostream & s)
Definition at line 153 of file ReactionPath.cpp.
exportToDot()
void exportToDot (std::ostream & s)
Export the reaction path diagram.
This method writes to stream s the commands for the 'dot' program in the GraphViz package from AT&T. (GraphViz may be downloaded from www.graphviz.org.)
To generate a postscript reaction path diagram from the output of this method saved in file paths.dot, for example, give the command:
dot -Tps paths.dot > paths.ps
To generate a GIF image, replace -Tps with -Tgif
Definition at line 173 of file ReactionPath.cpp.
References ReactionPathDiagram::flow(), ReactionPathDiagram::m_nodes, SpeciesNode::name, ReactionPathDiagram::netFlow(), Cantera::npos, and SpeciesNode::visible.
add()
void add (ReactionPathDiagram & d)
Definition at line 119 of file ReactionPath.cpp.
node()
SpeciesNode * node (size_t k) inline
Definition at line 207 of file ReactionPath.h.
path() [1/2]
Path * path (size_t k1, size_t k2) inline
Definition at line 210 of file ReactionPath.h.
path() [2/2]
Path * path (size_t n) inline
Definition at line 213 of file ReactionPath.h.
nPaths()
size_t nPaths () inline
Definition at line 216 of file ReactionPath.h.
nNodes()
size_t nNodes () inline
Definition at line 219 of file ReactionPath.h.
addNode()
void addNode (size_t k, const std::string & nm, doublereal x = 0.0)
Definition at line 356 of file ReactionPath.cpp.
displayOnly()
void displayOnly (size_t k = npos) inline
Definition at line 225 of file ReactionPath.h.
linkNodes()
void linkNodes (size_t k1, size_t k2, size_t rxn, doublereal value, std::string legend = "")
Definition at line 367 of file ReactionPath.cpp.
include() [1/2]
void include (const std::string & aaname) inline
Definition at line 232 of file ReactionPath.h.
exclude() [1/2]
void exclude (const std::string & aaname) inline
Definition at line 235 of file ReactionPath.h.
include() [2/2]
void include (std::vector< std::string > & names) inline
Definition at line 238 of file ReactionPath.h.
exclude() [2/2]
void exclude (std::vector< std::string > & names) inline
Definition at line 243 of file ReactionPath.h.
included()
std::vector< std::string > & included () inline
Definition at line 248 of file ReactionPath.h.
excluded()
std::vector< std::string > & excluded () inline
Definition at line 251 of file ReactionPath.h.
species()
std::vector< size_t > species ()
Definition at line 381 of file ReactionPath.cpp.
reactions()
vector_int reactions ()
Definition at line 96 of file ReactionPath.cpp.
findMajorPaths()
void findMajorPaths (doublereal threshold, size_t lda, doublereal * a)
Definition at line 129 of file ReactionPath.cpp.
setFont()
void setFont (const std::string & font) inline
Definition at line 257 of file ReactionPath.h.
Member Data Documentation
title
string title
Definition at line 262 of file ReactionPath.h.
bold_color
string bold_color = "blue"
Definition at line 263 of file ReactionPath.h.
normal_color
string normal_color = "steelblue"
Definition at line 264 of file ReactionPath.h.
dashed_color
string dashed_color = "gray"
Definition at line 265 of file ReactionPath.h.
element
string element
Definition at line 266 of file ReactionPath.h.
m_font
string m_font = "Helvetica"
Definition at line 267 of file ReactionPath.h.
threshold
double threshold = 0.005
Definition at line 268 of file ReactionPath.h.
bold_min
double bold_min = 0.2
Definition at line 269 of file ReactionPath.h.
dashed_max
double dashed_max = 0.0
Definition at line 270 of file ReactionPath.h.
label_min
double label_min = 0.0
Definition at line 271 of file ReactionPath.h.
x_size
double x_size = -1.0
Definition at line 272 of file ReactionPath.h.
y_size
double y_size = -1.0
Definition at line 273 of file ReactionPath.h.
name
string name = "reaction_paths"
Definition at line 274 of file ReactionPath.h.
dot_options
string dot_options = "center=1;"
Definition at line 275 of file ReactionPath.h.
flow_type
flow_t flow_type = NetFlow
Definition at line 276 of file ReactionPath.h.
scale
double scale = -1
Definition at line 277 of file ReactionPath.h.
arrow_width
double arrow_width = -5.0
Definition at line 278 of file ReactionPath.h.
show_details
bool show_details = false
Definition at line 279 of file ReactionPath.h.
arrow_hue
double arrow_hue = 0.6666
Definition at line 280 of file ReactionPath.h.
m_flxmax
double m_flxmax = 0.0 protected
Definition at line 283 of file ReactionPath.h.
m_paths
std::map<size_t, std::map<size_t, Path*> > m_paths protected
Definition at line 284 of file ReactionPath.h.
m_nodes
map<size_t, SpeciesNode*> m_nodes protected
map of species index to SpeciesNode
Definition at line 287 of file ReactionPath.h.
Referenced by ReactionPathDiagram::exportToDot(), ReactionPathDiagram::hasNode(), and ReactionPathDiagram::~ReactionPathDiagram().
m_pathlist
std::vector<Path*> m_pathlist protected
Definition at line 288 of file ReactionPath.h.
m_include
std::vector<std::string> m_include protected
Definition at line 289 of file ReactionPath.h.
m_exclude
std::vector<std::string> m_exclude protected
Definition at line 290 of file ReactionPath.h.
m_speciesNumber
std::vector<size_t> m_speciesNumber protected
Definition at line 291 of file ReactionPath.h.
m_rxns
set<size_t> m_rxns protected
Indices of reactions that are included in the diagram.
Definition at line 294 of file ReactionPath.h.
m_local
size_t m_local = npos protected
Definition at line 295 of file ReactionPath.h.
The documentation for this class was generated from the following files:
ReactionPath.h
ReactionPath.cpp