Cantera: PDSS_ConstVol Class Reference
PDSS_ConstVol Class Reference
Models of Phases of Matter » Thermodynamic Properties » Species Standard-State Thermodynamic Properties
Class for pressure dependent standard states that use a constant volume model.
#include <PDSS_ConstVol.h>
Public Member Functions
PDSS_ConstVol ()=default
Default Constructor.
Molar Thermodynamic Properties of the Species Standard State
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
Mechanical Equation of State Properties
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (double temp, double rho)
Set the internal temperature and density.
virtual doublereal satPressure (doublereal t)
saturation pressure
Initialization of the Object
virtual void initThermo ()
Initialization routine.
virtual void getParameters (AnyMap &eosNode) const
Store the parameters needed to reconstruct a copy of this PDSS object.
void setMolarVolume (double v)
Set the (constant) molar volume [m3/kmol] of the species.
Public Member Functions inherited from PDSS_Nondimensional
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal gibbs_mole () const
Return the molar Gibbs free energy in units of J kmol-1.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
virtual double enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual double entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual double gibbs_RT_ref () const
Return the molar Gibbs free energy divided by RT at reference pressure.
virtual double cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual double molarVolume_ref () const
Return the molar volume at reference pressure.
virtual double enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual double entropy_R () const
Return the standard state entropy divided by RT.
virtual double gibbs_RT () const
Return the molar Gibbs free energy divided by RT.
virtual double cp_R () const
Return the molar const pressure heat capacity divided by RT.
virtual double molarVolume () const
Return the molar volume at standard state.
virtual double density () const
Return the standard state density at standard state.
Public Member Functions inherited from PDSS
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual doublereal temperature () const
Return the current stored temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal T)
saturation pressure
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
PDSS ()=default
Default Constructor.
PDSS (const PDSS &b)=delete
PDSS & operator= (const PDSS &b)=delete
virtual ~PDSS ()=default
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state Gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setReferenceThermo (shared_ptr< SpeciesThermoInterpType > stit)
Set the SpeciesThermoInterpType object used to calculate reference state properties.
virtual void setParent (VPStandardStateTP *phase, size_t k)
Set the parent VPStandardStateTP object of this PDSS object.
void setParameters (const AnyMap &node)
Set model parameters from an AnyMap phase description, for example from the equation-of-state field of a species definition.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
Private Attributes
doublereal m_constMolarVolume
Value of the constant molar volume for the species.
Additional Inherited Members
Protected Attributes inherited from PDSS_Nondimensional
double m_h0_RT
Reference state enthalpy divided by RT.
double m_cp0_R
Reference state heat capacity divided by R.
double m_s0_R
Reference state entropy divided by R.
double m_g0_RT
Reference state Gibbs free energy divided by RT.
double m_V0
Reference state molar volume (m^3/kmol)
double m_hss_RT
Standard state enthalpy divided by RT.
double m_cpss_R
Standard state heat capacity divided by R.
double m_sss_R
Standard state entropy divided by R.
double m_gss_RT
Standard state Gibbs free energy divided by RT.
double m_Vss
Standard State molar volume (m^3/kmol)
Protected Attributes inherited from PDSS
double m_temp = -1.0
Current temperature used by the PDSS object.
double m_pres = -1.0
State of the system - pressure.
double m_p0 = -1.0
Reference state pressure of the species.
double m_minTemp = -1.0
Minimum temperature.
double m_maxTemp = 10000.0
Maximum temperature.
double m_mw = 0.0
Molecular Weight of the species.
AnyMap m_input
Input data supplied via setParameters.
shared_ptr< SpeciesThermoInterpType > m_spthermo
Pointer to the species thermodynamic property manager.
Detailed Description
Class for pressure dependent standard states that use a constant volume model.
Definition at line 22 of file PDSS_ConstVol.h.
Constructor & Destructor Documentation
PDSS_ConstVol()
PDSS_ConstVol () default
Default Constructor.
Member Function Documentation
intEnergy_mole()
doublereal intEnergy_mole () const virtual
Return the molar internal Energy in units of J kmol-1.
Returns
The species standard state internal Energy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 48 of file PDSS_ConstVol.cpp.
References Cantera::GasConstant, PDSS_Nondimensional::m_h0_RT, PDSS::m_pres, PDSS::m_temp, and PDSS_Nondimensional::m_Vss.
cv_mole()
doublereal cv_mole () const virtual
Return the molar const volume heat capacity in units of J kmol-1 K-1.
Returns
The species standard state Cv in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 54 of file PDSS_ConstVol.cpp.
References PDSS_Nondimensional::cp_mole(), and PDSS_Nondimensional::m_V0.
setPressure()
void setPressure (doublereal pres) virtual
Sets the pressure in the object.
Currently, this sets the pressure in the PDSS object. It is indeterminant what happens to the owning VPStandardStateTP object.
Parameters
pres Pressure to be set (Pascal)
Reimplemented from PDSS.
Definition at line 59 of file PDSS_ConstVol.cpp.
References Cantera::GasConstant, PDSS_Nondimensional::m_gss_RT, PDSS_Nondimensional::m_h0_RT, PDSS_Nondimensional::m_hss_RT, PDSS::m_p0, PDSS::m_pres, PDSS_Nondimensional::m_sss_R, PDSS::m_temp, and PDSS_Nondimensional::m_Vss.
Referenced by PDSS_ConstVol::setState_TP().
setTemperature()
void setTemperature (doublereal temp) virtual
Set the internal temperature.
Parameters
temp Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 67 of file PDSS_ConstVol.cpp.
References Cantera::GasConstant, PDSS_Nondimensional::m_cp0_R, PDSS_Nondimensional::m_cpss_R, PDSS_Nondimensional::m_g0_RT, PDSS_Nondimensional::m_gss_RT, PDSS_Nondimensional::m_h0_RT, PDSS_Nondimensional::m_hss_RT, PDSS::m_p0, PDSS::m_pres, PDSS_Nondimensional::m_s0_R, PDSS::m_spthermo, PDSS_Nondimensional::m_sss_R, PDSS::m_temp, and PDSS_Nondimensional::m_Vss.
Referenced by PDSS_ConstVol::setState_TP(), and PDSS_ConstVol::setState_TR().
setState_TP()
void setState_TP (doublereal temp, doublereal pres) virtual
Set the internal temperature and pressure.
Parameters
temp Temperature (Kelvin)
pres pressure (Pascals)
Reimplemented from PDSS.
Definition at line 81 of file PDSS_ConstVol.cpp.
References PDSS_ConstVol::setPressure(), and PDSS_ConstVol::setTemperature().
setState_TR()
void setState_TR (double temp, double rho) virtual
Set the internal temperature and density.
Parameters
temp Temperature (Kelvin)
rho Density (kg m-3)
Deprecated:
To be removed after Cantera 3.0
Reimplemented from PDSS.
Definition at line 87 of file PDSS_ConstVol.cpp.
References PDSS_ConstVol::m_constMolarVolume, PDSS::m_mw, PDSS_ConstVol::setTemperature(), and Cantera::warn_deprecated().
satPressure()
doublereal satPressure (doublereal T) virtual
saturation pressure
Parameters
T Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 98 of file PDSS_ConstVol.cpp.
initThermo()
void initThermo () virtual
Initialization routine.
This is a cascading call, where each level should call the the parent level.
Reimplemented from PDSS.
Definition at line 17 of file PDSS_ConstVol.cpp.
References AnyMap::convert(), AnyMap::hasKey(), PDSS::initThermo(), PDSS_ConstVol::m_constMolarVolume, PDSS::m_input, PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_mw, PDSS::m_p0, PDSS::m_spthermo, PDSS_Nondimensional::m_V0, PDSS_Nondimensional::m_Vss, and PDSS_ConstVol::setMolarVolume().
getParameters()
void getParameters (AnyMap & eosNode) const virtual
Store the parameters needed to reconstruct a copy of this PDSS object.
Reimplemented from PDSS.
Definition at line 34 of file PDSS_ConstVol.cpp.
References PDSS::getParameters(), AnyMap::hasKey(), PDSS_ConstVol::m_constMolarVolume, PDSS::m_input, and PDSS::m_mw.
setMolarVolume()
void setMolarVolume (double v) inline
Set the (constant) molar volume [m3/kmol] of the species.
Must be called before initThermo().
Definition at line 54 of file PDSS_ConstVol.h.
References PDSS_ConstVol::m_constMolarVolume.
Referenced by PDSS_ConstVol::initThermo().
Member Data Documentation
m_constMolarVolume
doublereal m_constMolarVolume private
Value of the constant molar volume for the species.
m3 / kmol
Definition at line 65 of file PDSS_ConstVol.h.
Referenced by PDSS_ConstVol::getParameters(), PDSS_ConstVol::initThermo(), PDSS_ConstVol::setMolarVolume(), and PDSS_ConstVol::setState_TR().
The documentation for this class was generated from the following files:
PDSS_ConstVol.h
PDSS_ConstVol.cpp