Cantera: ReactingSurf1D Class Reference
ReactingSurf1D Class Reference
One-Dimensional Reacting Flows
A reacting surface.
#include <Boundary1D.h>
Public Member Functions
ReactingSurf1D (shared_ptr< Solution > solution, const std::string &id="")
virtual string type () const
String indicating the domain implemented.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
void setKineticsMgr (InterfaceKinetics *kin)
void enableCoverageEquations (bool docov)
bool coverageEnabled ()
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
virtual void init ()
virtual void resetBadValues (double *xg)
virtual void eval (size_t jg, double *xg, double *rg, integer *diagg, double rdt)
Evaluate the residual function at point j.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
virtual void _getInitialSoln (double *x)
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
virtual void _finalize (const double *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
virtual void show (const double *x)
Print the solution.
Public Member Functions inherited from Boundary1D
virtual void init ()
virtual string type () const
String indicating the domain implemented.
virtual bool isConnector ()
True if the domain is a connector domain.
virtual void setTemperature (double t)
Set the temperature.
virtual double temperature ()
Temperature [K].
virtual size_t nSpecies ()
virtual void setMoleFractions (const std::string &xin)
Set the mole fractions by specifying a std::string.
virtual void setMoleFractions (const double *xin)
Set the mole fractions by specifying an array.
virtual double massFraction (size_t k)
Mass fraction of species k.
virtual void setMdot (double mdot)
Set the total mass flow rate.
virtual void setSpreadRate (double V0)
Set tangential velocity gradient [1/s] at this boundary.
virtual double spreadRate ()
Tangential velocity gradient [1/s] at this boundary.
virtual double mdot ()
The total mass flow rate [kg/m2/s].
virtual void setupGrid (size_t n, const double *z)
called to set up initial grid, and after grid refinement
Public Member Functions inherited from Domain1D
Domain1D (size_t nv=1, size_t points=1, double time=0.0)
Constructor.
Domain1D (const Domain1D &)=delete
Domain1D & operator= (const Domain1D &)=delete
int domainType ()
Domain type flag.
virtual string type () const
String indicating the domain implemented.
size_t domainIndex ()
The left-to-right location of this domain.
virtual bool isConnector ()
True if the domain is a connector domain.
void setSolution (shared_ptr< Solution > sol)
Set the solution manager.
virtual void setKinetics (shared_ptr< Kinetics > kin)
Set the kinetics manager.
virtual void setTransport (shared_ptr< Transport > trans)
Set transport model to existing instance.
const OneDim & container () const
The container holding this domain.
void setContainer (OneDim *c, size_t index)
Specify the container object for this domain, and the position of this domain in the list.
void setBandwidth (int bw=-1)
Set the Jacobian bandwidth. See the discussion of method bandwidth().
size_t bandwidth ()
Set the Jacobian bandwidth for this domain.
virtual void init ()
virtual void setInitialState (doublereal *xlocal=0)
virtual void setState (size_t point, const doublereal *state, doublereal *x)
virtual void resetBadValues (double *xg)
virtual void resize (size_t nv, size_t np)
Refiner & refiner ()
Return a reference to the grid refiner.
size_t nComponents () const
Number of components at each grid point.
void checkComponentIndex (size_t n) const
Check that the specified component index is in range.
void checkComponentArraySize (size_t nn) const
Check that an array size is at least nComponents().
size_t nPoints () const
Number of grid points in this domain.
void checkPointIndex (size_t n) const
Check that the specified point index is in range.
void checkPointArraySize (size_t nn) const
Check that an array size is at least nPoints().
virtual std::string componentName (size_t n) const
Name of the nth component. May be overloaded.
void setComponentName (size_t n, const std::string &name)
virtual size_t componentIndex (const std::string &name) const
index of component with name name.
void setBounds (size_t n, doublereal lower, doublereal upper)
void setTransientTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for time-stepping mode.
void setSteadyTolerances (doublereal rtol, doublereal atol, size_t n=npos)
Set tolerances for steady-state mode.
doublereal rtol (size_t n)
Relative tolerance of the nth component.
doublereal atol (size_t n)
Absolute tolerance of the nth component.
double steady_rtol (size_t n)
Steady relative tolerance of the nth component.
double steady_atol (size_t n)
Steady absolute tolerance of the nth component.
double transient_rtol (size_t n)
Transient relative tolerance of the nth component.
double transient_atol (size_t n)
Transient absolute tolerance of the nth component.
doublereal upperBound (size_t n) const
Upper bound on the nth component.
doublereal lowerBound (size_t n) const
Lower bound on the nth component.
void initTimeInteg (doublereal dt, const doublereal *x0)
Prepare to do time stepping with time step dt.
void setSteadyMode ()
Prepare to solve the steady-state problem.
bool steady ()
True if in steady-state mode.
bool transient ()
True if not in steady-state mode.
void needJacUpdate ()
virtual void eval (size_t j, doublereal *x, doublereal *r, integer *mask, doublereal rdt=0.0)
Evaluate the residual function at point j.
size_t index (size_t n, size_t j) const
doublereal value (const doublereal *x, size_t n, size_t j) const
virtual void setJac (MultiJac *jac)
AnyMap serialize (const double *soln) const
Save the state of this domain as an AnyMap.
virtual shared_ptr< SolutionArray > asArray (const double *soln) const
Save the state of this domain as a SolutionArray.
shared_ptr< SolutionArray > toArray (bool normalize=false) const
Save the state of this domain to a SolutionArray.
void restore (const AnyMap &state, double *soln, int loglevel)
Restore the solution for this domain from an AnyMap.
virtual void fromArray (SolutionArray &arr, double *soln)
Restore the solution for this domain from a SolutionArray.
void fromArray (const shared_ptr< SolutionArray > &arr)
Restore the solution for this domain from a SolutionArray.
shared_ptr< Solution > solution () const
Return thermo/kinetics/transport manager used in the domain.
size_t size () const
void locate ()
Find the index of the first grid point in this domain, and the start of its variables in the global solution vector.
virtual size_t loc (size_t j=0) const
Location of the start of the local solution vector in the global solution vector,.
size_t firstPoint () const
The index of the first (that is, left-most) grid point belonging to this domain.
size_t lastPoint () const
The index of the last (that is, right-most) grid point belonging to this domain.
void linkLeft (Domain1D *left)
Set the left neighbor to domain 'left.
void linkRight (Domain1D *right)
Set the right neighbor to domain 'right.'.
void append (Domain1D *right)
Append domain 'right' to this one, and update all links.
Domain1D * left () const
Return a pointer to the left neighbor.
Domain1D * right () const
Return a pointer to the right neighbor.
double prevSoln (size_t n, size_t j) const
Value of component n at point j in the previous solution.
void setID (const std::string &s)
Specify an identifying tag for this domain.
std::string id () const
virtual void showSolution_s (std::ostream &s, const double *x)
virtual void showSolution (const double *x)
Print the solution.
virtual void show (std::ostream &s, const double *x)
Print the solution.
virtual void show (const double *x)
Print the solution.
doublereal z (size_t jlocal) const
doublereal zmin () const
doublereal zmax () const
void setProfile (const std::string &name, double *values, double *soln)
vector_fp & grid ()
const vector_fp & grid () const
doublereal grid (size_t point) const
virtual void setupGrid (size_t n, const doublereal *z)
called to set up initial grid, and after grid refinement
virtual void _getInitialSoln (doublereal *x)
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
virtual doublereal initialValue (size_t n, size_t j)
Initial value of solution component n at grid point j.
virtual void _finalize (const doublereal *x)
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
void forceFullUpdate (bool update)
In some cases, for computational efficiency some properties (such as transport coefficients) may not be updated during Jacobian evaluations.
void setData (shared_ptr< vector< double > > &data)
Set shared data pointer.
Protected Attributes
InterfaceKinetics * m_kin = nullptr
SurfPhase * m_sphase = nullptr
size_t m_surfindex = 0
size_t m_nsp = 0
bool m_enabled = false
vector_fp m_work
vector_fp m_fixed_cov
Protected Attributes inherited from Boundary1D
StFlow * m_flow_left = nullptr
StFlow * m_flow_right = nullptr
size_t m_ilr = 0
size_t m_left_nv = 0
size_t m_right_nv = 0
size_t m_left_loc = 0
size_t m_right_loc = 0
size_t m_left_points = 0
size_t m_left_nsp = 0
size_t m_right_nsp = 0
size_t m_sp_left = 0
size_t m_sp_right = 0
size_t m_start_left = 0
size_t m_start_right = 0
ThermoPhase * m_phase_left = nullptr
ThermoPhase * m_phase_right = nullptr
double m_temp = 0.0
double m_mdot = 0.0
Protected Attributes inherited from Domain1D
shared_ptr< vector< double > > m_state
data pointer shared from OneDim
double m_rdt = 0.0
size_t m_nv = 0
size_t m_points
vector_fp m_slast
vector_fp m_max
vector_fp m_min
vector_fp m_rtol_ss
vector_fp m_rtol_ts
vector_fp m_atol_ss
vector_fp m_atol_ts
vector_fp m_z
OneDim * m_container = nullptr
size_t m_index
int m_type = 0
size_t m_iloc = 0
Starting location within the solution vector for unknowns that correspond to this domain.
size_t m_jstart = 0
Domain1D * m_left = nullptr
Domain1D * m_right = nullptr
std::string m_id
Identity tag for the domain.
std::unique_ptr< Refiner > m_refiner
std::vector< std::string > m_name
int m_bw = -1
bool m_force_full_update = false
shared_ptr< Solution > m_solution
Composite thermo/kinetics/transport handler.
Additional Inherited Members
Protected Member Functions inherited from Boundary1D
void _init (size_t n)
Protected Member Functions inherited from Domain1D
virtual AnyMap getMeta () const
Retrieve meta data.
virtual void setMeta (const AnyMap &meta)
Retrieve meta data.
Detailed Description
A reacting surface.
Definition at line 344 of file Boundary1D.h.
Constructor & Destructor Documentation
ReactingSurf1D() [1/2]
ReactingSurf1D ()
Definition at line 595 of file Boundary1D.cpp.
ReactingSurf1D() [2/2]
ReactingSurf1D (shared_ptr< Solution > solution, const std::string & id = "")
Definition at line 603 of file Boundary1D.cpp.
Member Function Documentation
type()
virtual string type () const inline virtual
String indicating the domain implemented.
Since
New in Cantera 3.0.
Todo:
Transition back to domainType after Cantera 3.0
Reimplemented from Boundary1D.
Definition at line 350 of file Boundary1D.h.
setKinetics()
void setKinetics (shared_ptr< Kinetics > kin) virtual
Set the kinetics manager.
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 626 of file Boundary1D.cpp.
References Solution::create(), Domain1D::m_solution, and Phase::nSpecies().
setKineticsMgr()
void setKineticsMgr (InterfaceKinetics * kin)
Deprecated:
To be removed after Cantera 3.0; replaced by setKinetics
Definition at line 639 of file Boundary1D.cpp.
References Phase::nSpecies(), Kinetics::reactionPhaseIndex(), Kinetics::thermo(), and Cantera::warn_deprecated().
enableCoverageEquations()
void enableCoverageEquations (bool docov) inline
Definition at line 359 of file Boundary1D.h.
coverageEnabled()
bool coverageEnabled () inline
Definition at line 363 of file Boundary1D.h.
componentName()
string componentName (size_t n) const virtual
Name of the nth component. May be overloaded.
Reimplemented from Domain1D.
Definition at line 650 of file Boundary1D.cpp.
References Phase::speciesName().
init()
void init () virtual
Initialize. This method is called by OneDim::init() for each domain once at the beginning of a simulation. Base class method does nothing, but may be overloaded.
Reimplemented from Boundary1D.
Definition at line 659 of file Boundary1D.cpp.
References Kinetics::nTotalSpecies().
resetBadValues()
void resetBadValues (double * xg) virtual
When called, this function should reset "bad" values in the state vector such as negative species concentrations. This function may be called after a failed solution attempt.
Reimplemented from Domain1D.
Definition at line 672 of file Boundary1D.cpp.
References SurfPhase::getCoverages(), Domain1D::loc(), and SurfPhase::setCoverages().
eval()
void eval (size_t j, double * x, double * r, integer * mask, double rdt) virtual
Evaluate the residual function at point j.
If j == npos, evaluate the residual function at all points.
This function must be implemented in classes derived from Domain1D.
Parameters
j Grid point at which to update the residual
[in] x State vector
[out] r residual vector
[out] mask Boolean mask indicating whether each solution component has a time derivative (1) or not (0).
[in] rdt Reciprocal of the timestep (rdt=0 implies steady- state.)
Reimplemented from Domain1D.
Definition at line 678 of file Boundary1D.cpp.
References Cantera::c_offset_T, Cantera::c_offset_Y, Domain1D::firstPoint(), Kinetics::getNetProductionRates(), Kinetics::kineticsSpeciesIndex(), Domain1D::lastPoint(), Domain1D::loc(), Phase::molecularWeights(), Domain1D::nComponents(), Kinetics::nPhases(), Domain1D::nPoints(), Cantera::npos, Domain1D::prevSoln(), StFlow::rightExcessSpecies(), SurfPhase::setCoveragesNoNorm(), StFlow::setGas(), Phase::setTemperature(), SurfPhase::siteDensity(), SurfPhase::size(), and Kinetics::thermo().
asArray()
shared_ptr< SolutionArray > asArray (const double * soln) const virtual
Save the state of this domain as a SolutionArray.
Parameters
soln local solution vector for this domain
Todo:
Despite the method's name, data are copied; the intent is to access data directly in future revisions, where a non-const version will be implemented.
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 762 of file Boundary1D.cpp.
References AnyValue::asString(), SolutionArray::create(), AnyValue::empty(), Domain1D::getMeta(), AnyBase::getMetadata(), ThermoPhase::input(), Domain1D::m_solution, Phase::name(), SurfPhase::pressure(), Phase::saveState(), SurfPhase::setCoverages(), ThermoPhase::setState_TP(), and Phase::stateSize().
fromArray()
void fromArray (SolutionArray & arr, double * soln) virtual
Restore the solution for this domain from a SolutionArray.
Parameters
[in] arr SolutionArray defining the state of this domain
[out] soln Value of the solution vector, local to this domain
Since
New in Cantera 3.0.
Reimplemented from Domain1D.
Definition at line 781 of file Boundary1D.cpp.
References SolutionArray::meta(), SolutionArray::setLoc(), Domain1D::setMeta(), and SolutionArray::thermo().
_getInitialSoln()
virtual void _getInitialSoln (double * x) inline virtual
Writes some or all initial solution values into the global solution array, beginning at the location pointed to by x.
This method is called by the Sim1D constructor, and allows default values or ones that have been set locally prior to installing this domain into the container to be written to the global solution vector.
Reimplemented from Domain1D.
Definition at line 378 of file Boundary1D.h.
References SurfPhase::getCoverages().
_finalize()
virtual void _finalize (const double * x) inline virtual
In some cases, a domain may need to set parameters that depend on the initial solution estimate.
In such cases, the parameters may be set in method _finalize. This method is called just before the Newton solver is called, and the x array is guaranteed to be the local solution vector for this domain that will be used as the initial guess. If no such parameters need to be set, then method _finalize does not need to be overloaded.
Reimplemented from Domain1D.
Definition at line 382 of file Boundary1D.h.
show()
void show (const double * x) virtual
Print the solution.
Reimplemented from Domain1D.
Definition at line 794 of file Boundary1D.cpp.
References Phase::speciesName(), and Cantera::writelog().
Member Data Documentation
m_kin
InterfaceKinetics* m_kin = nullptr protected
Definition at line 389 of file Boundary1D.h.
m_sphase
SurfPhase* m_sphase = nullptr protected
Definition at line 390 of file Boundary1D.h.
m_surfindex
size_t m_surfindex = 0 protected
Definition at line 391 of file Boundary1D.h.
m_nsp
size_t m_nsp = 0 protected
Definition at line 392 of file Boundary1D.h.
m_enabled
bool m_enabled = false protected
Definition at line 393 of file Boundary1D.h.
m_work
vector_fp m_work protected
Definition at line 394 of file Boundary1D.h.
m_fixed_cov
vector_fp m_fixed_cov protected
Definition at line 395 of file Boundary1D.h.
The documentation for this class was generated from the following files:
Boundary1D.h
Boundary1D.cpp