Cantera: Sim1D Class Reference
Sim1D Class Reference
One-Dimensional Reacting Flows
One-dimensional simulations.
#include <Sim1D.h>
Public Member Functions
Sim1D ()
Default constructor.
Sim1D (vector< shared_ptr< Domain1D > > &domains)
Standard constructor.
Sim1D (std::vector< Domain1D * > &domains)
const doublereal * solution ()
void setTimeStep (double stepsize, size_t n, const int *tsteps)
void solve (int loglevel=0, bool refine_grid=true)
void eval (doublereal rdt=-1.0, int count=1)
void getResidual (double rdt, double *resid)
int refine (int loglevel=0)
Refine the grid in all domains.
int setFixedTemperature (double t)
Add node for fixed temperature point of freely propagating flame.
double fixedTemperature ()
Return temperature at the point used to fix the flame location.
double fixedTemperatureLocation ()
Return location of the point where temperature is fixed.
void setRefineCriteria (int dom=-1, double ratio=10.0, double slope=0.8, double curve=0.8, double prune=-0.1)
Set grid refinement criteria.
vector_fp getRefineCriteria (int dom)
Get the grid refinement criteria.
void setMaxGridPoints (int dom, int npoints)
Set the maximum number of grid points in the domain.
size_t maxGridPoints (size_t dom)
Get the maximum number of grid points in this domain.
void setGridMin (int dom, double gridmin)
Set the minimum grid spacing in the specified domain(s).
void restoreTimeSteppingSolution ()
Set the current solution vector to the last successful time-stepping solution.
void restoreSteadySolution ()
Set the current solution vector and grid to the last successful steady- state solution.
void getInitialSoln ()
void setSolution (const doublereal *soln)
const doublereal * solution () const
doublereal jacobian (int i, int j)
void evalSSJacobian ()
void solveAdjoint (const double *b, double *lambda)
Solve the equation \(J^T \lambda = b \).
virtual void resize ()
Call after one or more grids has changed size, for example after being refined.
void setSteadyCallback (Func1 *callback)
Set a function that will be called after each successful steady-state solve, before regridding.
Setting initial values
These methods are used to set the initial values of solution components.
void setInitialGuess (const std::string &component, vector_fp &locs, vector_fp &vals)
Set initial guess for one component for all domains.
void setValue (size_t dom, size_t comp, size_t localPoint, doublereal value)
Set a single value in the solution vector.
doublereal value (size_t dom, size_t comp, size_t localPoint) const
Get one entry in the solution vector.
doublereal workValue (size_t dom, size_t comp, size_t localPoint) const
void setProfile (size_t dom, size_t comp, const vector_fp &pos, const vector_fp &values)
Specify a profile for one component of one domain.
void setFlatProfile (size_t dom, size_t comp, doublereal v)
Set component 'comp' of domain 'dom' to value 'v' at all points.
Logging, saving and restoring of solutions
void showSolution (std::ostream &s)
Output information on current solution for all domains to stream.
void showSolution ()
Show logging information on current solution for all domains.
void show (std::ostream &s)
Output information on current solution for all domains to stream.
void show ()
Show logging information on current solution for all domains.
void save (const std::string &fname, const std::string &id, const std::string &desc, int loglevel)
Save the current solution to a container file.
void save (const std::string &fname, const std::string &name, const std::string &desc, bool overwrite=false, int compression=0, const string &basis="")
Save current simulation data to a container file or CSV format.
void saveResidual (const std::string &fname, const std::string &id, const std::string &desc, int loglevel)
Save the residual of the current solution to a container file.
void saveResidual (const std::string &fname, const std::string &name, const std::string &desc, bool overwrite=false, int compression=0)
Save the residual of the current solution to a container file.
AnyMap restore (const std::string &fname, const std::string &id, int loglevel)
Initialize the solution with a previously-saved solution.
AnyMap restore (const std::string &fname, const std::string &name)
Retrieve data and settings from a previously saved simulation.
Public Member Functions inherited from OneDim
OneDim (vector< shared_ptr< Domain1D > > &domains)
Construct a OneDim container for the domains in the list domains.
OneDim (std::vector< Domain1D * > domains)
OneDim (const OneDim &)=delete
OneDim & operator= (const OneDim &)=delete
void addDomain (shared_ptr< Domain1D > d)
Add a domain. Domains are added left-to-right.
void addDomain (Domain1D *d)
MultiJac & jacobian ()
Return a reference to the Jacobian evaluator.
MultiNewton & newton ()
Return a reference to the Newton iterator.
int solve (doublereal *x0, doublereal *x1, int loglevel)
Solve F(x) = 0, where F(x) is the multi-domain residual function.
size_t nDomains () const
Number of domains.
Domain1D & domain (size_t i) const
Return a reference to domain i.
size_t domainIndex (const std::string &name)
void checkDomainIndex (size_t n) const
Check that the specified domain index is in range.
void checkDomainArraySize (size_t nn) const
Check that an array size is at least nDomains().
size_t start (size_t i) const
The index of the start of domain i in the solution vector.
size_t size () const
Total solution vector length;.
Domain1D * left ()
Pointer to left-most domain (first added).
Domain1D * right ()
Pointer to right-most domain (last added).
size_t nVars (size_t jg)
Number of solution components at global point jg.
size_t loc (size_t jg)
Location in the solution vector of the first component of global point jg.
std::tuple< std::string, size_t, std::string > component (size_t i)
Return the domain, local point index, and component name for the i-th component of the global solution vector.
size_t bandwidth () const
Jacobian bandwidth.
void init ()
size_t points ()
Total number of points.
doublereal ssnorm (doublereal *x, doublereal *r)
Steady-state max norm (infinity norm) of the residual evaluated using solution x.
doublereal rdt () const
Reciprocal of the time step.
void initTimeInteg (doublereal dt, doublereal *x)
Prepare for time stepping beginning with solution x and timestep dt.
bool transient () const
True if transient mode.
bool steady () const
True if steady mode.
void setSteadyMode ()
void eval (size_t j, double *x, double *r, doublereal rdt=-1.0, int count=1)
Evaluate the multi-domain residual function.
Domain1D * pointDomain (size_t i)
Return a pointer to the domain global point i belongs to.
virtual void resize ()
Call after one or more grids has changed size, for example after being refined.
vector_int & transientMask ()
double timeStep (int nsteps, double dt, double *x, double *r, int loglevel)
void resetBadValues (double *x)
void writeStats (int printTime=1)
Write statistics about the number of iterations and Jacobians at each grid level.
AnyMap serialize (const double *soln) const
void setMinTimeStep (doublereal tmin)
void setMaxTimeStep (doublereal tmax)
void setTimeStepFactor (doublereal tfactor)
void setMaxTimeStepCount (int nmax)
Set the maximum number of timeteps allowed before successful steady-state solve.
int maxTimeStepCount () const
Return the maximum number of timeteps allowed before successful steady-state solve.
void setJacAge (int ss_age, int ts_age=-1)
void saveStats ()
Save statistics on function and Jacobian evaluation, and reset the counters.
void clearStats ()
Clear saved statistics.
const std::vector< size_t > & gridSizeStats ()
Return total grid size in each call to solve()
const vector_fp & jacobianTimeStats ()
Return CPU time spent evaluating Jacobians in each call to solve()
const vector_fp & evalTimeStats ()
Return CPU time spent on non-Jacobian function evaluations in each call to solve()
const vector_int & jacobianCountStats ()
Return number of Jacobian evaluations made in each call to solve()
const vector_int & evalCountStats ()
Return number of non-Jacobian function evaluations made in each call to solve()
const vector_int & timeStepStats ()
Return number of time steps taken in each call to solve()
void setInterrupt (Func1 *interrupt)
Set a function that will be called every time eval is called.
void setTimeStepCallback (Func1 *callback)
Set a function that will be called after each successful timestep.
Protected Attributes
vector_fp m_xlast_ts
the solution vector after the last successful timestepping
vector_fp m_xlast_ss
the solution vector after the last successful steady-state solve (stored before grid refinement)
std::vector< vector_fp > m_grid_last_ss
the grids for each domain after the last successful steady-state solve (stored before grid refinement)
vector_fp m_xnew
a work array used to hold the residual or the new solution
doublereal m_tstep
timestep
vector_int m_steps
array of number of steps to take before re-attempting the steady-state solution
Func1 * m_steady_callback
User-supplied function called after a successful steady-state solve.
Protected Attributes inherited from OneDim
double m_tmin = 1e-16
minimum timestep size
double m_tmax = 1e+08
maximum timestep size
double m_tfactor = 0.5
factor time step is multiplied by if time stepping fails (< 1)
shared_ptr< vector< double > > m_state
Solution vector.
std::unique_ptr< MultiJac > m_jac
Jacobian evaluator.
std::unique_ptr< MultiNewton > m_newt
Newton iterator.
double m_rdt = 0.0
reciprocal of time step
bool m_jac_ok = false
if true, Jacobian is current
size_t m_bw = 0
Jacobian bandwidth.
size_t m_size = 0
solution vector size
vector< shared_ptr< Domain1D > > m_sharedDom
vector< shared_ptr< Domain1D > > m_sharedConnect
vector< shared_ptr< Domain1D > > m_sharedBulk
vector< Domain1D * > m_dom
vector< Domain1D * > m_connect
vector< Domain1D * > m_bulk
bool m_init = false
std::vector< size_t > m_nvars
std::vector< size_t > m_loc
vector_int m_mask
size_t m_pts = 0
int m_ss_jac_age = 20
int m_ts_jac_age = 20
Func1 * m_interrupt = nullptr
Function called at the start of every call to eval.
Func1 * m_time_step_callback = nullptr
User-supplied function called after each successful timestep.
int m_nsteps = 0
Number of time steps taken in the current call to solve()
int m_nsteps_max = 500
Maximum number of timesteps allowed per call to solve()
Private Member Functions
void finalize ()
Calls method _finalize in each domain.
int newtonSolve (int loglevel)
Wrapper around the Newton solver.
Additional Inherited Members
Protected Member Functions inherited from OneDim
void evalSSJacobian (doublereal *x, doublereal *xnew)
Detailed Description
One-dimensional simulations.
Class Sim1D extends class OneDim by storing the solution vector, and by adding a hybrid Newton/time-stepping solver.
Definition at line 21 of file Sim1D.h.
Constructor & Destructor Documentation
Sim1D() [1/3]
Sim1D () inline
Default constructor.
This constructor is provided to make the class default-constructible, but is not meant to be used in most applications. Use the next constructor
Definition at line 29 of file Sim1D.h.
Sim1D() [2/3]
Sim1D (vector< shared_ptr< Domain1D > > & domains)
Standard constructor.
Parameters
domains A vector of shared pointers to the domains to be linked together. The domain pointers must be entered in left-to-right order — that is, the pointer to the leftmost domain is domain[0], the pointer to the domain to its right is domain[1], etc.
Definition at line 25 of file Sim1D.cpp.
References Domain1D::_getInitialSoln(), OneDim::domain(), OneDim::m_state, Sim1D::m_steps, Sim1D::m_tstep, OneDim::nDomains(), Sim1D::resize(), and OneDim::start().
Sim1D() [3/3]
Sim1D (std::vector< Domain1D * > & domains)
Deprecated:
To be removed after Cantera 3.0; superseded by Sim1D() using shared_ptr
Definition at line 41 of file Sim1D.cpp.
References Domain1D::_getInitialSoln(), OneDim::domain(), OneDim::m_state, Sim1D::m_steps, Sim1D::m_tstep, OneDim::nDomains(), Sim1D::resize(), OneDim::start(), and Cantera::warn_deprecated().
Member Function Documentation
setInitialGuess()
void setInitialGuess (const std::string & component, vector_fp & locs, vector_fp & vals)
Set initial guess for one component for all domains.
Parameters
component component name
locs A vector of relative positions, beginning with 0.0 at the left of the domain, and ending with 1.0 at the right of the domain.
vals A vector of values corresponding to the relative position locations.
Definition at line 61 of file Sim1D.cpp.
References OneDim::component(), Domain1D::componentName(), OneDim::domain(), Domain1D::nComponents(), OneDim::nDomains(), and Sim1D::setProfile().
setValue()
void setValue (size_t dom, size_t comp, size_t localPoint, doublereal value)
Set a single value in the solution vector.
Parameters
dom domain number, beginning with 0 for the leftmost domain.
comp component number
localPoint grid point within the domain, beginning with 0 for the leftmost grid point in the domain.
value the value.
Definition at line 74 of file Sim1D.cpp.
References AssertThrowMsg, OneDim::domain(), Domain1D::loc(), OneDim::m_state, OneDim::size(), and Sim1D::value().
Referenced by Sim1D::setFlatProfile(), and Sim1D::setProfile().
value()
doublereal value (size_t dom, size_t comp, size_t localPoint) const
Get one entry in the solution vector.
Parameters
dom domain number, beginning with 0 for the leftmost domain.
comp component number
localPoint grid point within the domain, beginning with 0 for the leftmost grid point in the domain.
Definition at line 82 of file Sim1D.cpp.
References AssertThrowMsg, OneDim::domain(), Domain1D::loc(), OneDim::m_state, and OneDim::size().
Referenced by Sim1D::refine(), Sim1D::setFixedTemperature(), and Sim1D::setValue().
workValue()
doublereal workValue (size_t dom, size_t comp, size_t localPoint) const
Definition at line 90 of file Sim1D.cpp.
setProfile()
void setProfile (size_t dom, size_t comp, const vector_fp & pos, const vector_fp & values)
Specify a profile for one component of one domain.
Parameters
dom domain number, beginning with 0 for the leftmost domain.
comp component number
pos A vector of relative positions, beginning with 0.0 at the left of the domain, and ending with 1.0 at the right of the domain.
values A vector of values corresponding to the relative position locations.
Note that the vector pos and values can have lengths different than the number of grid points, but their lengths must be equal. The values at the grid points will be linearly interpolated based on the (pos, values) specification.
Definition at line 98 of file Sim1D.cpp.
References OneDim::domain(), Cantera::linearInterp(), Domain1D::nPoints(), and Sim1D::setValue().
Referenced by Sim1D::setInitialGuess().
setFlatProfile()
void setFlatProfile (size_t dom, size_t comp, doublereal v)
Set component 'comp' of domain 'dom' to value 'v' at all points.
Definition at line 349 of file Sim1D.cpp.
References OneDim::domain(), Domain1D::nPoints(), and Sim1D::setValue().
showSolution() [1/2]
void showSolution (std::ostream & s)
Output information on current solution for all domains to stream.
Parameters
s Output stream
Deprecated:
To be removed after Cantera 3.0; replaced by show
Definition at line 357 of file Sim1D.cpp.
References Sim1D::show(), and Cantera::warn_deprecated().
showSolution() [2/2]
void showSolution ()
Show logging information on current solution for all domains.
Deprecated:
To be removed after Cantera 3.0; replaced by show
Definition at line 364 of file Sim1D.cpp.
References Sim1D::show(), and Cantera::warn_deprecated().
show() [1/2]
void show (std::ostream & s)
Output information on current solution for all domains to stream.
Parameters
s Output stream
Since
New in Cantera 3.0.
Definition at line 371 of file Sim1D.cpp.
References OneDim::domain(), OneDim::m_state, OneDim::nDomains(), Domain1D::show(), OneDim::start(), and Domain1D::type().
show() [2/2]
void show ()
Show logging information on current solution for all domains.
Since
New in Cantera 3.0.
Definition at line 380 of file Sim1D.cpp.
References OneDim::domain(), OneDim::m_state, OneDim::nDomains(), Domain1D::show(), OneDim::start(), Domain1D::type(), and Cantera::writelog().
Referenced by Sim1D::showSolution().
save() [1/2]
void save (const std::string & fname, const std::string & id, const std::string & desc, int loglevel)
Save the current solution to a container file.
Parameters
fname Name of output container file
id Identifier of solution within the container file
desc Description of the solution
loglevel Level of diagnostic output
Deprecated:
To be removed after Cantera 3.0; loglevel is deprecated.
Definition at line 117 of file Sim1D.cpp.
References Sim1D::save(), Cantera::warn_deprecated(), and Cantera::writelog().
Referenced by Sim1D::save(), and Sim1D::saveResidual().
save() [2/2]
void save (const std::string & fname, const std::string & name, const std::string & desc, bool overwrite = false, int compression = 0, const string & basis = "")
Save current simulation data to a container file or CSV format.
In order to save the content of a Sim1D object, individual domains are converted to SolutionArray objects and saved using the SolutionArray::save() method. For HDF and YAML output, all domains are written to a single container file with shared header information. Simulation settings of individual domains are preserved as meta data of the corresponding SolutionArray objects. For CSV files, only state and auxiliary data of the main 1D domain are saved.
The complete state of the current object can be restored from HDF and YAML container files using the restore() method, while individual domains can be loaded using SolutionArray::restore() for further analysis. While CSV do not contain complete information, they can still be used for setting initial states of individual simulation objects for some Cantera API's.
Parameters
fname Name of output file (CSV, YAML or HDF)
name Identifier of storage location within the container file; this node/group contains header information and multiple subgroups holding domain-specific SolutionArray data (YAML/HDF only)
desc Custom comment describing the dataset to be stored (YAML/HDF only)
overwrite Force overwrite if file/name exists; optional (default=false)
compression Compression level (0-9); optional (default=0; HDF only)
basis Output mass ("Y"/"mass") or mole ("X"/"mole") fractions; if not specified (default=""), the native basis of the underlying ThermoPhase manager is used -
See also
nativeState (CSV only)
Definition at line 128 of file Sim1D.cpp.
References AnyMap::clearCachedFile(), Cantera::dot(), AnyMap::fromYamlFile(), OneDim::m_dom, OneDim::m_state, Cantera::npos, Cantera::toLowerCopy(), Cantera::warn_user(), and SolutionArray::writeHeader().
saveResidual() [1/2]
void saveResidual (const std::string & fname, const std::string & id, const std::string & desc, int loglevel)
Save the residual of the current solution to a container file.
Parameters
fname Name of output container file
id Identifier of solution within the container file
desc Description of the solution
loglevel Level of diagnostic output
Deprecated:
To be removed after Cantera 3.0; loglevel is deprecated.
Definition at line 178 of file Sim1D.cpp.
References Sim1D::saveResidual(), Cantera::warn_deprecated(), and Cantera::writelog().
Referenced by Sim1D::saveResidual().
saveResidual() [2/2]
void saveResidual (const std::string & fname, const std::string & name, const std::string & desc, bool overwrite = false, int compression = 0)
Save the residual of the current solution to a container file.
Parameters
fname Name of output container file
name Identifier of solution within the container file
desc Description of the solution
overwrite Force overwrite if name exists; optional (default=false)
compression Compression level (optional; HDF only)
Definition at line 189 of file Sim1D.cpp.
References OneDim::eval(), OneDim::m_state, Cantera::npos, and Sim1D::save().
restore() [1/2]
AnyMap restore (const std::string & fname, const std::string & id, int loglevel)
Initialize the solution with a previously-saved solution.
Parameters
fname Name of container file
id Identifier of solution within the container file
loglevel Level of diagnostic output
Deprecated:
To be removed after Cantera 3.0; loglevel is deprecated.
Returns
AnyMap containing header information
Definition at line 289 of file Sim1D.cpp.
References Sim1D::restore(), and Cantera::warn_deprecated().
Referenced by Sim1D::restore().
restore() [2/2]
AnyMap restore (const std::string & fname, const std::string & name)
Retrieve data and settings from a previously saved simulation.
This method restores a simulation object from YAML or HDF data previously saved using the save() method.
Parameters
fname Name of container file (YAML or HDF)
name Identifier of location within the container file; this node/group contains header information and subgroups with domain-specific SolutionArray data
Returns
AnyMap containing header information
Definition at line 296 of file Sim1D.cpp.
References SolutionArray::create(), Cantera::dot(), Sim1D::finalize(), AnyMap::fromYamlFile(), AnyMap::hasKey(), OneDim::m_dom, OneDim::m_state, Sim1D::m_xlast_ts, Cantera::npos, SolutionArray::readHeader(), Sim1D::resize(), and Cantera::toLowerCopy().
solution() [1/2]
const doublereal * solution () inline
Definition at line 224 of file Sim1D.h.
setTimeStep()
void setTimeStep (double stepsize, size_t n, const int * tsteps)
Definition at line 427 of file Sim1D.cpp.
solve()
void solve (int loglevel = 0, bool refine_grid = true)
Definition at line 450 of file Sim1D.cpp.
eval()
void eval (doublereal rdt = -1.0, int count = 1) inline
Definition at line 234 of file Sim1D.h.
getResidual()
void getResidual (double rdt, double * resid) inline
Definition at line 239 of file Sim1D.h.
refine()
int refine (int loglevel = 0)
Refine the grid in all domains.
Definition at line 561 of file Sim1D.cpp.
References OneDim::domain(), Sim1D::finalize(), Sim1D::m_grid_last_ss, OneDim::m_state, Sim1D::m_xlast_ss, Domain1D::nComponents(), OneDim::nDomains(), Domain1D::nPoints(), Domain1D::refiner(), Sim1D::resize(), Domain1D::setupGrid(), OneDim::start(), Sim1D::value(), and Cantera::writelog().
setFixedTemperature()
int setFixedTemperature (double t)
Add node for fixed temperature point of freely propagating flame.
Definition at line 650 of file Sim1D.cpp.
References OneDim::domain(), Sim1D::finalize(), OneDim::m_state, StFlow::m_tfixed, StFlow::m_zfixed, Domain1D::nComponents(), OneDim::nDomains(), Domain1D::nPoints(), Cantera::npos, Sim1D::resize(), Domain1D::setupGrid(), and Sim1D::value().
fixedTemperature()
double fixedTemperature ()
Return temperature at the point used to fix the flame location.
Definition at line 740 of file Sim1D.cpp.
References OneDim::domain(), StFlow::m_tfixed, and OneDim::nDomains().
fixedTemperatureLocation()
double fixedTemperatureLocation ()
Return location of the point where temperature is fixed.
Definition at line 753 of file Sim1D.cpp.
References OneDim::domain(), StFlow::m_tfixed, StFlow::m_zfixed, and OneDim::nDomains().
setRefineCriteria()
void setRefineCriteria (int dom = -1, double ratio = 10.0, double slope = 0.8, double curve = 0.8, double prune = -0.1)
Set grid refinement criteria.
If dom >= 0, then the settings apply only to the specified domain. If dom < 0, the settings are applied to each domain.
See also
Refiner::setCriteria.
Definition at line 766 of file Sim1D.cpp.
References OneDim::domain(), OneDim::nDomains(), Domain1D::refiner(), and Refiner::setCriteria().
getRefineCriteria()
vector_fp getRefineCriteria (int dom)
Get the grid refinement criteria.
dom must be greater than or equal to zero (that is, the domain must be specified).
See also
Refiner::getCriteria
Definition at line 780 of file Sim1D.cpp.
References OneDim::domain(), Refiner::getCriteria(), and Domain1D::refiner().
setMaxGridPoints()
void setMaxGridPoints (int dom, int npoints)
Set the maximum number of grid points in the domain.
If dom >= 0, then the settings apply only to the specified domain. If dom < 0, the settings are applied to each domain.
See also
Refiner::setMaxPoints.
Definition at line 804 of file Sim1D.cpp.
References OneDim::domain(), OneDim::nDomains(), Domain1D::refiner(), and Refiner::setMaxPoints().
maxGridPoints()
size_t maxGridPoints (size_t dom)
Get the maximum number of grid points in this domain.
See also
Refiner::maxPoints
Parameters
dom domain number, beginning with 0 for the leftmost domain.
Definition at line 817 of file Sim1D.cpp.
References OneDim::domain(), Refiner::maxPoints(), and Domain1D::refiner().
setGridMin()
void setGridMin (int dom, double gridmin)
Set the minimum grid spacing in the specified domain(s).
Parameters
dom Domain index. If dom == -1, the specified spacing is applied to all domains.
gridmin The minimum allowable grid spacing [m]
Definition at line 791 of file Sim1D.cpp.
References OneDim::domain(), OneDim::nDomains(), Domain1D::refiner(), and Refiner::setGridMin().
restoreTimeSteppingSolution()
void restoreTimeSteppingSolution ()
Set the current solution vector to the last successful time-stepping solution.
This can be used to examine the solver progress after a failed integration.
Definition at line 391 of file Sim1D.cpp.
References OneDim::m_state, and Sim1D::m_xlast_ts.
restoreSteadySolution()
void restoreSteadySolution ()
Set the current solution vector and grid to the last successful steady- state solution.
This can be used to examine the solver progress after a failure during grid refinement.
Definition at line 400 of file Sim1D.cpp.
References OneDim::domain(), Sim1D::m_grid_last_ss, OneDim::m_state, Sim1D::m_xlast_ss, OneDim::nDomains(), and Domain1D::setupGrid().
getInitialSoln()
void getInitialSoln ()
Definition at line 413 of file Sim1D.cpp.
setSolution()
void setSolution (const doublereal * soln) inline
Definition at line 306 of file Sim1D.h.
solution() [2/2]
const doublereal * solution () const inline
Definition at line 313 of file Sim1D.h.
jacobian()
doublereal jacobian (int i, int j)
Definition at line 823 of file Sim1D.cpp.
evalSSJacobian()
void evalSSJacobian ()
Definition at line 828 of file Sim1D.cpp.
solveAdjoint()
void solveAdjoint (const double * b, double * lambda)
Solve the equation \(J^T \lambda = b \).
Here, \(J = \partial f/\partial x \) is the Jacobian matrix of the system of equations \(f(x,p)=0 \). This can be used to efficiently solve for the sensitivities of a scalar objective function \(g(x,p) \) to a vector of parameters \(p \) by solving:
\[ J^T \lambda = \left(\frac{\partial g}{\partial x} \right)^T \]
for \(\lambda \) and then computing:
\[ \left.\frac{dg}{dp}\right|_{f=0} = \frac{\partial g}{\partial p} - \lambda^T \frac{\partial f}{\partial p} \]
Definition at line 833 of file Sim1D.cpp.
References OneDim::bandwidth(), OneDim::m_dom, OneDim::m_jac, OneDim::size(), and BandMatrix::solve().
resize()
void resize () virtual
Call after one or more grids has changed size, for example after being refined.
Reimplemented from OneDim.
Definition at line 857 of file Sim1D.cpp.
References Sim1D::m_xnew, OneDim::resize(), and OneDim::size().
Referenced by Sim1D::refine(), Sim1D::restore(), Sim1D::setFixedTemperature(), and Sim1D::Sim1D().
setSteadyCallback()
void setSteadyCallback (Func1 * callback) inline
Set a function that will be called after each successful steady-state solve, before regridding.
Intended to be used for observing solver progress for debugging purposes.
Definition at line 343 of file Sim1D.h.
References Sim1D::m_steady_callback.
finalize()
void finalize () private
Calls method _finalize in each domain.
Definition at line 420 of file Sim1D.cpp.
References Domain1D::_finalize(), OneDim::domain(), OneDim::m_state, OneDim::nDomains(), and OneDim::start().
Referenced by Sim1D::refine(), Sim1D::restore(), and Sim1D::setFixedTemperature().
newtonSolve()
int newtonSolve (int loglevel) private
Wrapper around the Newton solver.
Returns
0 if successful, -1 on failure
Definition at line 436 of file Sim1D.cpp.
References OneDim::m_state, Sim1D::m_xnew, and OneDim::solve().
Member Data Documentation
m_xlast_ts
vector_fp m_xlast_ts protected
the solution vector after the last successful timestepping
Definition at line 349 of file Sim1D.h.
Referenced by Sim1D::restore(), and Sim1D::restoreTimeSteppingSolution().
m_xlast_ss
vector_fp m_xlast_ss protected
the solution vector after the last successful steady-state solve (stored before grid refinement)
Definition at line 353 of file Sim1D.h.
Referenced by Sim1D::refine(), and Sim1D::restoreSteadySolution().
m_grid_last_ss
std::vector<vector_fp> m_grid_last_ss protected
the grids for each domain after the last successful steady-state solve (stored before grid refinement)
Definition at line 357 of file Sim1D.h.
Referenced by Sim1D::refine(), and Sim1D::restoreSteadySolution().
m_xnew
vector_fp m_xnew protected
a work array used to hold the residual or the new solution
Definition at line 360 of file Sim1D.h.
Referenced by Sim1D::newtonSolve(), and Sim1D::resize().
m_tstep
doublereal m_tstep protected
timestep
Definition at line 363 of file Sim1D.h.
Referenced by Sim1D::Sim1D().
m_steps
vector_int m_steps protected
array of number of steps to take before re-attempting the steady-state solution
Definition at line 367 of file Sim1D.h.
Referenced by Sim1D::Sim1D().
m_steady_callback
Func1* m_steady_callback protected
User-supplied function called after a successful steady-state solve.
Definition at line 370 of file Sim1D.h.
Referenced by Sim1D::setSteadyCallback().
The documentation for this class was generated from the following files:
Sim1D.h
Sim1D.cpp