Cantera: Zero-dimensional reactor networks
Zero-dimensional reactor networks
See https://cantera.org/science/reactors.html for a description of the governing equations for specific reactor types and the methods used for solving networks of.
Classes
class FlowDevice
Base class for 'flow devices' (valves, pressure regulators, etc.) connecting reactors.
class FlowDeviceFactory
Factory class to create FlowDevice objects.
class Reactor
Class Reactor is a general-purpose class for stirred reactors.
class ReactorBase
Base class for stirred reactors.
class ReactorFactory
Factory class to create reactor objects.
class ReactorNet
A class representing a network of connected reactors.
class ReactorSurface
A surface where reactions can occur that is in contact with the bulk fluid of a Reactor.
class WallBase
Base class for 'walls' (walls, pistons, etc.) connecting reactors.
class WallFactory
Factory class to create WallBase objects.
Functions
FlowDevice * newFlowDevice (const string &model)
Create a FlowDevice object of the specified type.
shared_ptr< FlowDevice > newFlowDevice3 (const string &model)
Create a FlowDevice object of the specified type.
ReactorBase * newReactor (const string &model)
Create a Reactor object of the specified type.
shared_ptr< ReactorBase > newReactor3 (const string &model)
Create a Reactor object of the specified type.
WallBase * newWall (const string &model)
Create a WallBase object of the specified type.
shared_ptr< WallBase > newWall3 (const string &model)
Create a WallBase object of the specified type.
Detailed Description
See https://cantera.org/science/reactors.html for a description of the governing equations for specific reactor types and the methods used for solving networks of.
Function Documentation
newFlowDevice()
FlowDevice * newFlowDevice (const string & model)
Create a FlowDevice object of the specified type.
Deprecated:
To be changed after Cantera 3.0; for new behavior, see newFlowDevice3.
Definition at line 44 of file FlowDeviceFactory.cpp.
References Cantera::warn_deprecated().
newFlowDevice3()
shared_ptr< FlowDevice > newFlowDevice3 (const string & model)
Create a FlowDevice object of the specified type.
Since
New in Cantera 3.0.
Todo:
Transition back to newFlowDevice after Cantera 3.0
Definition at line 51 of file FlowDeviceFactory.cpp.
newReactor()
ReactorBase * newReactor (const string & model)
Create a Reactor object of the specified type.
Deprecated:
To be changed after Cantera 3.0; for new behavior, see newReactor3.
Definition at line 76 of file ReactorFactory.cpp.
References Cantera::warn_deprecated().
newReactor3()
shared_ptr< ReactorBase > newReactor3 (const string & model)
Create a Reactor object of the specified type.
Since
New in Cantera 3.0.
Todo:
Transition back to newReactor after Cantera 3.0
Definition at line 83 of file ReactorFactory.cpp.
newWall()
WallBase * newWall (const string & model)
Create a WallBase object of the specified type.
Deprecated:
To be changed after Cantera 3.0; for new behavior, see newWall3.
Definition at line 41 of file WallFactory.cpp.
References Cantera::warn_deprecated().
newWall3()
shared_ptr< WallBase > newWall3 (const string & model)
Create a WallBase object of the specified type.
Since
New in Cantera 3.0.
Todo:
Transition back to newWall after Cantera 3.0
Definition at line 48 of file WallFactory.cpp.