Cantera: CoverageDependentSurfPhase Class Reference
CoverageDependentSurfPhase Class Reference
A thermodynamic model for a coverage-dependent surface phase, applying surface species lateral interaction correction factors to the ideal surface phase properties.
#include <CoverageDependentSurfPhase.h>
Classes
struct HeatCapacityDependency
A struct to store sets of parameters used in coverage-dependent heat capacity calculations by a log-quadratic equation in CoverageDependentSurfPhase.
struct InterpolativeDependency
A struct to store sets of parameters used in coverage-dependent enthalpy and entropy calculations by a interpolative equation or a piecewise-linear equation in CoverageDependentSurfPhase.
struct PolynomialDependency
A struct to store sets of parameters used in coverage-dependent enthalpy and entropy calculations by a polynomial equation or a linear equation in CoverageDependentSurfPhase.
Public Member Functions
CoverageDependentSurfPhase (const std::string &infile="", const std::string &id="")
Construct and initialize a CoverageDependentSurfPhase ThermoPhase object directly from an ASCII input file.
virtual std::string type () const
String indicating the thermodynamic model implemented.
void addInterpolativeDependency (const InterpolativeDependency &int_deps)
Add interpolative coverage dependence parameters for a species.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
Methods calculating reference state thermodynamic properties
Reference state properties are evaluated at \(T \text{ and } \theta^{ref} \).
With coverage fixed at a reference value, reference state properties are effectively only dependent on temperature.
virtual void getEnthalpy_RT_ref (double *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (double *sr) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (double *cpr) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getGibbs_RT_ref (double *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Methods calculating standard state thermodynamic properties
Standard state properties are evaluated at \(T \text{ and } \theta \), and thus are dependent both on temperature and coverage.
virtual void getEnthalpy_RT (double *hrt) const
Get the nondimensionalized standard state enthalpy vector.
virtual void getEntropy_R (double *sr) const
Get the nondimensionalized standard state entropy vector.
virtual void getCp_R (double *cpr) const
Get the nondimensionalized standard state heat capacity vector.
virtual void getGibbs_RT (double *grt) const
Get the nondimensionalized standard state gibbs free energy vector.
virtual void getPureGibbs (double *g) const
Get the standard state gibbs free energy vector. Units: J/kmol.
virtual void getStandardChemPotentials (double *mu0) const
Get the standard state chemical potential vector. Units: J/kmol.
Methods calculating partial molar thermodynamic properties
Partial molar properties are evaluated at \(T \text{ and } \theta \), and thus are dependent both on temperature and coverage.
virtual void getPartialMolarEnthalpies (double *hbar) const
Get the partial molar enthalpy vector. Units: J/kmol.
virtual void getPartialMolarEntropies (double *sbar) const
Get the partial molar entropy vector. Units: J/kmol/K.
virtual void getPartialMolarCp (double *cpbar) const
Get the partial molar heat capacity vector. Units: J/kmol/K.
virtual void getChemPotentials (double *mu) const
Get the chemical potential vector. Units: J/kmol.
Methods calculating Phase thermodynamic properties
Phase properties are evaluated at \(T \text{ and } \theta \), and thus are dependent both on temperature and coverage.
virtual double enthalpy_mole () const
Return the solution's molar enthalpy. Units: J/kmol.
virtual double entropy_mole () const
Return the solution's molar entropy. Units: J/kmol/K.
virtual double cp_mole () const
Return the solution's molar heat capacity. Units: J/kmol/K.
Public Member Functions inherited from SurfPhase
SurfPhase (const std::string &infile="", const std::string &id="")
Construct and initialize a SurfPhase ThermoPhase object directly from an input file.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual doublereal enthalpy_mole () const
Return the Molar Enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Return the Molar Internal Energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Return the Molar Entropy. Units: J/kmol-K.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getActivityConcentrations (doublereal *c) const
Return a vector of activity concentrations for each species.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual double molarVolume () const
Since interface phases have no volume, this returns 0.0.
virtual void setMolarDensity (const double vm)
Since interface phases have no volume, setting this to a value other than 0.0 raises an exception.
double siteDensity () const
Returns the site density.
virtual double size (size_t k) const
Returns the number of sites occupied by one molecule of species k.
void setSiteDensity (doublereal n0)
Set the site density of the surface phase (kmol m-2)
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void getPureGibbs (doublereal *g) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
void setCoverages (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesNoNorm (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesByName (const std::string &cov)
Set the coverages from a string of colon-separated name:value pairs.
void setCoveragesByName (const compositionMap &cov)
Set the coverages from a map of name:value pairs.
void getCoverages (doublereal *theta) const
Return a vector of surface coverages.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_DP (double rho, double p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setTemperature (double temp)
Set the internally stored temperature of the phase (K).
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Attributes
vector_fp m_cov
Temporary storage for the coverages.
vector_fp m_h_cov
Temporary storage for the coverage-dependent enthalpies.
vector_fp m_s_cov
Temporary storage for the coverage-dependent entropies.
vector_fp m_cp_cov
Temporary storage for the coverage-dependent heat capacities.
vector_fp m_mu_cov
Temporary storage for the coverage-dependent chemical potentials.
vector_fp m_enthalpy
Temporary storage for the sum of reference state enthalpies and coverage-dependent enthalpies.
vector_fp m_entropy
Temporary storage for the sum of reference state entropies and coverage-dependent entropies.
vector_fp m_heatcapacity
Temporary storage for the sum of reference state heat capacities and coverage-dependent heat capacities.
vector_fp m_chempot
Temporary storage for the sum of reference state chemical potentials and coverage-dependent chemical potentials.
std::vector< PolynomialDependency > m_PolynomialDependency
Array of enthalpy and entropy coverage dependency parameters used in the linear and polynomial dependency equations.
std::vector< InterpolativeDependency > m_InterpolativeDependency
Array of enthalpy and entropy coverage dependency parameters used in the piecewise-linear and interpolative dependency equations.
std::vector< HeatCapacityDependency > m_HeatCapacityDependency
Array of heat capacity coverage dependency parameters.
Protected Attributes inherited from SurfPhase
double m_n0 = 1.0
Surface site density (kmol m-2)
vector_fp m_speciesSize
Vector of species sizes (number of sites occupied). length m_kk.
doublereal m_logn0
log of the surface site density
double m_press = OneAtm
Current value of the pressure (Pa)
vector_fp m_h0
Temporary storage for the reference state enthalpies.
vector_fp m_s0
Temporary storage for the reference state entropies.
vector_fp m_cp0
Temporary storage for the reference state heat capacities.
vector_fp m_mu0
Temporary storage for the reference state Gibbs energies.
vector_fp m_work
Temporary work array.
vector_fp m_logsize
vector storing the log of the size of each species.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Private Member Functions
void _updateCovDepThermo () const
Update the species coverage-dependent thermodynamic functions.
void _updateTotalThermo () const
Update the total (reference state + coverage-dependent) thermodynamic functions.
Private Attributes
double m_theta_ref
Storage for the user-defined reference state coverage which has to be greater than 0.0 and less than or equal to 1.0.
int m_stateNumlast
Last value of the state number processed.
Additional Inherited Members
Protected Member Functions inherited from SurfPhase
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
void _updateThermo (bool force=false) const
Update the species reference state thermodynamic functions.
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Detailed Description
A thermodynamic model for a coverage-dependent surface phase, applying surface species lateral interaction correction factors to the ideal surface phase properties.
The ideal surface phase assumes no lateral interaction among surface species. This coverage-dependent surface phase allows adding lateral interaction correction terms to the ideal surface phase (SurfPhase) thermodynamic properties so that more accurate surface species thermochemistry can be achieved.
Coverage-dependent Thermodynamic Properties Formulations
At a low-coverage limit, a surface species thermochemistry is the same as that of ideal surface species since there are no adsorbates in the vicinity to cause lateral interaction. Therefore, it is logical to set ideal surface species properties as the low-coverage limit and add lateral interaction terms to them as excess properties. Accordingly, standard state coverage-dependent enthalpy, entropy, and heat capacity of a surface species \(k \) can be formulated as follows.
\[ h_k^o(T,\theta) = \underbrace{h_k^{o,ideal}(T) + \int_{298}^{T}c_{p,k}^{o,ideal}(T)dT}_{\text{low-coverage limit}} + \underbrace{h_k^{o,cov}(T,\theta) + \int_{298}^{T}c_{p,k}^{o,cov}(T,\theta)dT}_{\text{coverage dependence}} \]
\[ s_k^o(T,\theta) = \underbrace{s_k^{o,ideal}(T) + \int_{298}^{T}\frac{c_{p,k}^{o,ideal}(T)}{T}dT}_{\text{low-coverage limit}} + \underbrace{s_k^{o,cov}(T,\theta) + \int_{298}^{T}\frac{c_{p,k}^{o,cov}(T,\theta)}{T}dT}_{\text{coverage dependence}} \]
\[ c_{p,k}^o(T,\theta) = \underbrace{c_{p,k}^{o,ideal}(T)}_{\text{low-coverage limit}} + \underbrace{c_{p,k}^{o,cov}(T,\theta)}_{\text{coverage dependence}} \]
Mathematical Models for Coverage-dependent Correction Terms
Coverage-dependent correction terms for enthalpy and entropy can be calculated with one of the four algebraic models: linear dependecy model, polynomial dependency model, piecewise-linear, and interpolative dependency model. In the dependency model equations, a coverage-dependent correction term is denoted by \(f^{cov} \) where \(f \) can be either enthalpy (\(h^{cov} \)) or entropy (\(s^{cov} \)). Because lateral interaction can compose of both self- and cross- interactions, the total correction term of species \(k \) is a sum of all interacting species \(j \) which can include itself. Coefficients \(c^{(1)}_{k,j}-c^{(6)}_{k,j} \) are user-provided parameters that can be given in a input yaml.
Linear dependency model:
\[ f^{cov}_k(\theta) = \sum_j c^{(1)}_{k,j} \theta_j \]
Polynomial dependency model:
\[ f^{cov}_k(\theta) = \sum_j \left[c^{(1)}_{k,j}\theta_j + c^{(2)}_{k,j}\theta_j^2 + c^{(3)}_{k,j}\theta_j^3 + c^{(4)}_{k,j}\theta_j^4\right] \]
Piecewise-linear dependency model:
\[ f^{cov}_k(\theta) = \sum_j \left\{ \begin{array}{ll} c^{(5)}_{k,j}\theta_j & \text{, } \theta_j \leq \theta^\text{change}_{k,j} \\ \left[c^{(6)}_{k,j}(\theta_j - \theta^\text{change}_{k,j}) + (c^{(5)}_{k,j}\theta^\text{change}_{k,j})\right] & \text{, } \theta_j > \theta^\text{change}_{k,j} \\ \end{array} \right. \]
Interpolative dependency model:
\[ f^{cov}_k(\theta) = \sum_j \left[\frac{f^{cov}_k(\theta^{higher}_j) - f^{cov}_k(\theta^{lower}_j)} {\theta^{higher}_j - \theta^{lower}_j}(\theta_j - \theta^{lower}_j) + f^{cov}_k (\theta^{lower}_j)\right] \\ \text{where } \theta^{lower}_j \leq \theta_j < \theta^{higher}_j \]
Coverage-dependent heat capacity is calculated using an equation with a quadratic dependence on coverages and a logarithmic dependence on temperature. Temperature is nondimensionalized with a reference temperature of 1 K. The coverage-dependent heat capacity of species \(k \) is a sum of all quantities dependent on coverage of species \(j \). Coefficients \(c^{(a)}_{k,j} \text{ and } c^{(b)}_{k,j} \) are user-provided parameters that can be given in an input yaml.
Coverage-dependent heat capacity model:
\[ c^{cov}_{p,k}(\theta) = \sum_j \left(c^{(a)}_{k,j} \ln\left(\frac{T}{1\text{ K}}\right) + c^{(b)}_{k,j}\right) \theta_j^2 \]
Definition at line 126 of file CoverageDependentSurfPhase.h.
Constructor & Destructor Documentation
CoverageDependentSurfPhase()
CoverageDependentSurfPhase (const std::string & infile = "", const std::string & id = "") explicit
Construct and initialize a CoverageDependentSurfPhase ThermoPhase object directly from an ASCII input file.
Parameters
infile name of the input file. If blank, an empty phase will be created.
id name of the phase id in the file. If blank, the first phase in the file is used.
Definition at line 25 of file CoverageDependentSurfPhase.cpp.
References ThermoPhase::initThermoFile(), and Phase::setNDim().
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from SurfPhase.
Definition at line 314 of file CoverageDependentSurfPhase.h.
addInterpolativeDependency()
void addInterpolativeDependency (const InterpolativeDependency & int_deps)
Add interpolative coverage dependence parameters for a species.
Parameters
int_deps list of parameters as an InterpolativeDependency object
Definition at line 34 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::InterpolativeDependency::enthalpy_map, CoverageDependentSurfPhase::InterpolativeDependency::entropy_map, and CoverageDependentSurfPhase::m_InterpolativeDependency.
Referenced by CoverageDependentSurfPhase::initThermo().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from SurfPhase.
Definition at line 58 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::addInterpolativeDependency(), CoverageDependentSurfPhase::HeatCapacityDependency::coeff_a, CoverageDependentSurfPhase::HeatCapacityDependency::coeff_b, AnyMap::hasKey(), SurfPhase::initThermo(), CoverageDependentSurfPhase::m_HeatCapacityDependency, ThermoPhase::m_input, CoverageDependentSurfPhase::m_PolynomialDependency, CoverageDependentSurfPhase::m_theta_ref, Cantera::npos, and Phase::speciesIndex().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Reimplemented from SurfPhase.
Definition at line 116 of file CoverageDependentSurfPhase.cpp.
References SurfPhase::addSpecies(), CoverageDependentSurfPhase::m_chempot, CoverageDependentSurfPhase::m_cov, CoverageDependentSurfPhase::m_cp_cov, CoverageDependentSurfPhase::m_enthalpy, CoverageDependentSurfPhase::m_entropy, CoverageDependentSurfPhase::m_h_cov, CoverageDependentSurfPhase::m_heatcapacity, CoverageDependentSurfPhase::m_mu_cov, and CoverageDependentSurfPhase::m_s_cov.
getParameters()
void getParameters (AnyMap & phaseNode) const virtual
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
This does not include user-defined fields available in input().
Reimplemented from SurfPhase.
Definition at line 133 of file CoverageDependentSurfPhase.cpp.
References SurfPhase::getParameters(), and CoverageDependentSurfPhase::m_theta_ref.
getSpeciesParameters()
void getSpeciesParameters (const std::string & name, AnyMap & speciesNode) const virtual
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
Parameters
name Name of the species
speciesNode Mapping to be populated with parameters
Reimplemented from ThermoPhase.
Definition at line 139 of file CoverageDependentSurfPhase.cpp.
References ThermoPhase::getSpeciesParameters(), CoverageDependentSurfPhase::m_HeatCapacityDependency, CoverageDependentSurfPhase::m_InterpolativeDependency, CoverageDependentSurfPhase::m_PolynomialDependency, Phase::name(), Phase::speciesIndex(), and Phase::speciesName().
getEnthalpy_RT_ref()
void getEnthalpy_RT_ref (double * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies. Length: m_kk.
Reimplemented from SurfPhase.
Definition at line 230 of file CoverageDependentSurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_h0, ThermoPhase::RT(), and Cantera::scale().
getEntropy_R_ref()
void getEntropy_R_ref (double * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from SurfPhase.
Definition at line 236 of file CoverageDependentSurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_s0, and Cantera::scale().
getCp_R_ref()
void getCp_R_ref (double * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from SurfPhase.
Definition at line 242 of file CoverageDependentSurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_cp0, and Cantera::scale().
getGibbs_RT_ref()
void getGibbs_RT_ref (double * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from SurfPhase.
Definition at line 224 of file CoverageDependentSurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_mu0, ThermoPhase::RT(), and Cantera::scale().
getEnthalpy_RT()
void getEnthalpy_RT (double * hrt) const virtual
Get the nondimensionalized standard state enthalpy vector.
\[ \frac{h^o_k(T,\theta)}{RT} = \frac{h^{ref}_k(T) + h^{cov}_k(T,\theta) + \int_{298}^{T} c^{cov}_{p,k}(T,\theta)dT}{RT} \]
Reimplemented from SurfPhase.
Definition at line 248 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::m_enthalpy, ThermoPhase::RT(), and Cantera::scale().
getEntropy_R()
void getEntropy_R (double * sr) const virtual
Get the nondimensionalized standard state entropy vector.
\[ \frac{s^o_k(T,\theta)}{R} = \frac{s^{ref}_k(T) + s^{cov}_k(T,\theta) + \int_{298}^{T}\frac{c^{cov}_{p,k}(T,\theta)}{T}dT}{R} - \ln\left(\frac{1}{\theta_{ref}}\right) \]
Reimplemented from SurfPhase.
Definition at line 254 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), Cantera::GasConstant, CoverageDependentSurfPhase::m_entropy, Phase::m_kk, CoverageDependentSurfPhase::m_theta_ref, and Cantera::scale().
getCp_R()
void getCp_R (double * cpr) const virtual
Get the nondimensionalized standard state heat capacity vector.
\[ \frac{c^o_{p,k}(T,\theta)}{RT} = \frac{c^{ref}_{p,k}(T) + c^{cov}_{p,k}(T,\theta)}{RT} \]
Reimplemented from SurfPhase.
Definition at line 266 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), Cantera::GasConstant, CoverageDependentSurfPhase::m_heatcapacity, and Cantera::scale().
getGibbs_RT()
void getGibbs_RT (double * grt) const virtual
Get the nondimensionalized standard state gibbs free energy vector.
\[ \frac{g^o_k(T,\theta)}{RT} = \frac{h^o_k(T,\theta)}{RT} + \frac{s^o_k(T,\theta)}{R} \]
Reimplemented from SurfPhase.
Definition at line 272 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::m_chempot, Phase::m_kk, CoverageDependentSurfPhase::m_theta_ref, ThermoPhase::RT(), and Cantera::scale().
Referenced by CoverageDependentSurfPhase::getPureGibbs().
getPureGibbs()
void getPureGibbs (double * g) const virtual
Get the standard state gibbs free energy vector. Units: J/kmol.
\[ g^o_k(T,\theta) = h^o_k(T,\theta) + Ts^o_k(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 284 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::getGibbs_RT(), Phase::m_kk, and ThermoPhase::RT().
getStandardChemPotentials()
void getStandardChemPotentials (double * mu0) const virtual
Get the standard state chemical potential vector. Units: J/kmol.
\[ \mu^o_k(T,\theta) = h^o_k(T,\theta) + Ts^o_k(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 292 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::m_chempot, Phase::m_kk, CoverageDependentSurfPhase::m_theta_ref, and ThermoPhase::RT().
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (double * hbar) const virtual
Get the partial molar enthalpy vector. Units: J/kmol.
\[ \tilde{h}_k(T,\theta) = h^o_k(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 304 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), and CoverageDependentSurfPhase::m_enthalpy.
getPartialMolarEntropies()
void getPartialMolarEntropies (double * sbar) const virtual
Get the partial molar entropy vector. Units: J/kmol/K.
\[ \tilde{s}_k(T,\theta) = s^o_k(T,\theta) - R\ln(\theta_k) \]
Reimplemented from SurfPhase.
Definition at line 310 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), Cantera::GasConstant, CoverageDependentSurfPhase::m_cov, CoverageDependentSurfPhase::m_entropy, Phase::m_kk, CoverageDependentSurfPhase::m_theta_ref, and Cantera::SmallNumber.
getPartialMolarCp()
void getPartialMolarCp (double * cpbar) const virtual
Get the partial molar heat capacity vector. Units: J/kmol/K.
\[ \tilde{c}_{p,k}(T,\theta) = c^o_{p,k}(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 319 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), and CoverageDependentSurfPhase::m_heatcapacity.
getChemPotentials()
void getChemPotentials (double * mu) const virtual
Get the chemical potential vector. Units: J/kmol.
\[ \mu_k(T,\theta) = \mu^o_k(T,\theta) + RT\ln(\theta_k) \]
Reimplemented from SurfPhase.
Definition at line 325 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::m_chempot, CoverageDependentSurfPhase::m_cov, Phase::m_kk, CoverageDependentSurfPhase::m_theta_ref, ThermoPhase::RT(), and Cantera::SmallNumber.
enthalpy_mole()
double enthalpy_mole () const virtual
Return the solution's molar enthalpy. Units: J/kmol.
\[ \hat h(T,\theta) = \sum_k \theta_k \tilde{h}_k(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 334 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::m_enthalpy, and Phase::mean_X().
entropy_mole()
double entropy_mole () const virtual
Return the solution's molar entropy. Units: J/kmol/K.
\[ \hat s(T,\theta) = \sum_k \theta_k \tilde{s}_k(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 340 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), Cantera::GasConstant, CoverageDependentSurfPhase::m_cov, CoverageDependentSurfPhase::m_entropy, Phase::m_kk, CoverageDependentSurfPhase::m_theta_ref, Phase::moleFraction(), and Cantera::SmallNumber.
cp_mole()
double cp_mole () const virtual
Return the solution's molar heat capacity. Units: J/kmol/K.
\[ \hat{c_p}(T,\theta) = \sum_k \theta_k \tilde{c_p}_k(T,\theta) \]
Reimplemented from SurfPhase.
Definition at line 351 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::m_heatcapacity, and Phase::mean_X().
_updateCovDepThermo()
void _updateCovDepThermo () const private
Update the species coverage-dependent thermodynamic functions.
The coverage-dependent enthalpy and entropy are only re-evaluated if the coverage has changed. The coverage-dependent heat capacity is only re-evaluated if the coverage or temperature has changed.
Definition at line 357 of file CoverageDependentSurfPhase.cpp.
References AssertThrowMsg, SurfPhase::getCoverages(), CoverageDependentSurfPhase::m_cov, CoverageDependentSurfPhase::m_cp_cov, CoverageDependentSurfPhase::m_h_cov, CoverageDependentSurfPhase::m_HeatCapacityDependency, CoverageDependentSurfPhase::m_InterpolativeDependency, Phase::m_kk, CoverageDependentSurfPhase::m_mu_cov, CoverageDependentSurfPhase::m_PolynomialDependency, CoverageDependentSurfPhase::m_s_cov, CoverageDependentSurfPhase::m_stateNumlast, ThermoPhase::m_tlast, Cantera::poly4(), Phase::stateMFNumber(), and Phase::temperature().
Referenced by CoverageDependentSurfPhase::_updateTotalThermo().
_updateTotalThermo()
void _updateTotalThermo () const private
Update the total (reference state + coverage-dependent) thermodynamic functions.
Calls subroutines for both ideal species thermodynamic update and coverage-dependent species thermodynamic update.
Definition at line 431 of file CoverageDependentSurfPhase.cpp.
References CoverageDependentSurfPhase::_updateCovDepThermo(), SurfPhase::_updateThermo(), CoverageDependentSurfPhase::m_chempot, SurfPhase::m_cp0, CoverageDependentSurfPhase::m_cp_cov, CoverageDependentSurfPhase::m_enthalpy, CoverageDependentSurfPhase::m_entropy, SurfPhase::m_h0, CoverageDependentSurfPhase::m_h_cov, CoverageDependentSurfPhase::m_heatcapacity, Phase::m_kk, SurfPhase::m_mu0, CoverageDependentSurfPhase::m_mu_cov, SurfPhase::m_s0, and CoverageDependentSurfPhase::m_s_cov.
Referenced by CoverageDependentSurfPhase::cp_mole(), CoverageDependentSurfPhase::enthalpy_mole(), CoverageDependentSurfPhase::entropy_mole(), CoverageDependentSurfPhase::getChemPotentials(), CoverageDependentSurfPhase::getCp_R(), CoverageDependentSurfPhase::getEnthalpy_RT(), CoverageDependentSurfPhase::getEntropy_R(), CoverageDependentSurfPhase::getGibbs_RT(), CoverageDependentSurfPhase::getPartialMolarCp(), CoverageDependentSurfPhase::getPartialMolarEnthalpies(), CoverageDependentSurfPhase::getPartialMolarEntropies(), and CoverageDependentSurfPhase::getStandardChemPotentials().
Member Data Documentation
m_cov
vector_fp m_cov mutable protected
Temporary storage for the coverages.
Definition at line 473 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::addSpecies(), CoverageDependentSurfPhase::entropy_mole(), CoverageDependentSurfPhase::getChemPotentials(), and CoverageDependentSurfPhase::getPartialMolarEntropies().
m_h_cov
vector_fp m_h_cov mutable protected
Temporary storage for the coverage-dependent enthalpies.
Definition at line 476 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), and CoverageDependentSurfPhase::addSpecies().
m_s_cov
vector_fp m_s_cov mutable protected
Temporary storage for the coverage-dependent entropies.
Definition at line 479 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), and CoverageDependentSurfPhase::addSpecies().
m_cp_cov
vector_fp m_cp_cov mutable protected
Temporary storage for the coverage-dependent heat capacities.
Definition at line 482 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), and CoverageDependentSurfPhase::addSpecies().
m_mu_cov
vector_fp m_mu_cov mutable protected
Temporary storage for the coverage-dependent chemical potentials.
Definition at line 485 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::_updateTotalThermo(), and CoverageDependentSurfPhase::addSpecies().
m_enthalpy
vector_fp m_enthalpy mutable protected
Temporary storage for the sum of reference state enthalpies and coverage-dependent enthalpies.
Definition at line 489 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::addSpecies(), CoverageDependentSurfPhase::enthalpy_mole(), CoverageDependentSurfPhase::getEnthalpy_RT(), and CoverageDependentSurfPhase::getPartialMolarEnthalpies().
m_entropy
vector_fp m_entropy mutable protected
Temporary storage for the sum of reference state entropies and coverage-dependent entropies.
Definition at line 493 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::addSpecies(), CoverageDependentSurfPhase::entropy_mole(), CoverageDependentSurfPhase::getEntropy_R(), and CoverageDependentSurfPhase::getPartialMolarEntropies().
m_heatcapacity
vector_fp m_heatcapacity mutable protected
Temporary storage for the sum of reference state heat capacities and coverage-dependent heat capacities.
Definition at line 497 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::addSpecies(), CoverageDependentSurfPhase::cp_mole(), CoverageDependentSurfPhase::getCp_R(), and CoverageDependentSurfPhase::getPartialMolarCp().
m_chempot
vector_fp m_chempot mutable protected
Temporary storage for the sum of reference state chemical potentials and coverage-dependent chemical potentials.
Definition at line 501 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateTotalThermo(), CoverageDependentSurfPhase::addSpecies(), CoverageDependentSurfPhase::getChemPotentials(), CoverageDependentSurfPhase::getGibbs_RT(), and CoverageDependentSurfPhase::getStandardChemPotentials().
m_PolynomialDependency
std::vector<PolynomialDependency> m_PolynomialDependency protected
Array of enthalpy and entropy coverage dependency parameters used in the linear and polynomial dependency equations.
Definition at line 505 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::getSpeciesParameters(), and CoverageDependentSurfPhase::initThermo().
m_InterpolativeDependency
std::vector<InterpolativeDependency> m_InterpolativeDependency protected
Array of enthalpy and entropy coverage dependency parameters used in the piecewise-linear and interpolative dependency equations.
Definition at line 509 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::addInterpolativeDependency(), and CoverageDependentSurfPhase::getSpeciesParameters().
m_HeatCapacityDependency
std::vector<HeatCapacityDependency> m_HeatCapacityDependency protected
Array of heat capacity coverage dependency parameters.
Definition at line 512 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo(), CoverageDependentSurfPhase::getSpeciesParameters(), and CoverageDependentSurfPhase::initThermo().
m_theta_ref
double m_theta_ref private
Storage for the user-defined reference state coverage which has to be greater than 0.0 and less than or equal to 1.0.
default = 1.0.
Definition at line 517 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::entropy_mole(), CoverageDependentSurfPhase::getChemPotentials(), CoverageDependentSurfPhase::getEntropy_R(), CoverageDependentSurfPhase::getGibbs_RT(), CoverageDependentSurfPhase::getParameters(), CoverageDependentSurfPhase::getPartialMolarEntropies(), CoverageDependentSurfPhase::getStandardChemPotentials(), and CoverageDependentSurfPhase::initThermo().
m_stateNumlast
int m_stateNumlast mutable private
Last value of the state number processed.
Definition at line 520 of file CoverageDependentSurfPhase.h.
Referenced by CoverageDependentSurfPhase::_updateCovDepThermo().
The documentation for this class was generated from the following files:
CoverageDependentSurfPhase.h
CoverageDependentSurfPhase.cpp