Cantera: IonGasTransport Class Reference
IonGasTransport Class Reference
Models of Phases of Matter » Transport Properties for Species in Phases
Class IonGasTransport implements Stockmayer-(n,6,4) model for transport of ions.
#include <IonGasTransport.h>
Public Member Functions
virtual std::string transportModel () const
Identifies the model represented by this Transport object.
virtual void init (ThermoPhase *thermo, int mode, int log_level)
Initialize a transport manager.
virtual double viscosity ()
Viscosity of the mixture (kg/m/s).
virtual double thermalConductivity ()
Returns the mixture thermal conductivity (W/m/K).
virtual void getMobilities (double *const mobi)
The mobilities for ions in gas.
virtual void getMixDiffCoeffs (double *const d)
The mixture transport for ionized gas.
virtual double electricalConductivity ()
Public Member Functions inherited from MixTransport
MixTransport ()=default
Default constructor.
virtual std::string transportModel () const
Identifies the model represented by this Transport object.
virtual void getThermalDiffCoeffs (doublereal *const dt)
Return the thermal diffusion coefficients.
virtual doublereal thermalConductivity ()
Returns the mixture thermal conductivity (W/m /K)
virtual void getMobilities (doublereal *const mobil)
Get the Electrical mobilities (m^2/V/s).
virtual void update_T ()
Update the internal parameters whenever the temperature has changed.
virtual void update_C ()
Update the internal parameters whenever the concentrations have changed.
virtual void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void init (ThermoPhase *thermo, int mode=0, int log_level=0)
Initialize a transport manager.
Public Member Functions inherited from GasTransport
virtual doublereal viscosity ()
Viscosity of the mixture (kg /m /s)
virtual void getSpeciesViscosities (doublereal *const visc)
Get the pure-species viscosities.
virtual void getBinaryDiffCoeffs (const size_t ld, doublereal *const d)
Returns the matrix of binary diffusion coefficients.
virtual void getMixDiffCoeffs (doublereal *const d)
Returns the Mixture-averaged diffusion coefficients [m^2/s].
virtual void getMixDiffCoeffsMole (doublereal *const d)
Returns the mixture-averaged diffusion coefficients [m^2/s].
virtual void getMixDiffCoeffsMass (doublereal *const d)
Returns the mixture-averaged diffusion coefficients [m^2/s].
virtual void getViscosityPolynomial (size_t i, double *coeffs) const
Return the polynomial fits to the viscosity of species i.
virtual void getConductivityPolynomial (size_t i, double *coeffs) const
Return the temperature fits of the heat conductivity of species i.
virtual void getBinDiffusivityPolynomial (size_t i, size_t j, double *coeffs) const
Return the polynomial fits to the binary diffusivity of species pair (i, j)
virtual void getCollisionIntegralPolynomial (size_t i, size_t j, double *astar_coeffs, double *bstar_coeffs, double *cstar_coeffs) const
Return the polynomial fits to the collision integral of species pair (i, j)
virtual void setViscosityPolynomial (size_t i, double *coeffs)
Modify the polynomial fits to the viscosity of species i.
virtual void setConductivityPolynomial (size_t i, double *coeffs)
Modify the temperature fits of the heat conductivity of species i.
virtual void setBinDiffusivityPolynomial (size_t i, size_t j, double *coeffs)
Modify the polynomial fits to the binary diffusivity of species pair (i, j)
virtual void setCollisionIntegralPolynomial (size_t i, size_t j, double *astar_coeffs, double *bstar_coeffs, double *cstar_coeffs, bool actualT)
Modify the polynomial fits to the collision integral of species pair (i, j)
virtual void init (ThermoPhase *thermo, int mode=0, int log_level=0)
Initialize a transport manager.
bool CKMode () const
Boolean indicating the form of the transport properties polynomial fits.
Public Member Functions inherited from Transport
Transport (ThermoPhase *thermo=0, size_t ndim=npos)
Constructor.
Transport (const Transport &)=delete
Transport & operator= (const Transport &)=delete
virtual std::string transportModel () const
Identifies the model represented by this Transport object.
std::string transportType () const
Identifies the Transport object type.
ThermoPhase & thermo ()
bool ready ()
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
virtual double getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const double *grad_T, int ldx, const double *grad_X, int ldf, const double *grad_V, double *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxes (size_t ndim, const double *const grad_T, size_t ldx, const double *const grad_X, size_t ldf, double *const fluxes)
Get the species diffusive mass fluxes wrt to the specified solution averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesFluxesES (size_t ndim, const double *grad_T, size_t ldx, const double *grad_X, size_t ldf, const double *grad_Phi, double *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const double *grad_T, int ldx, const double *grad_X, int ldf, double *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const double *grad_T, int ldx, const double *grad_X, int ldf, const double *grad_Phi, double *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void getMolarFluxes (const double *const state1, const double *const state2, const double delta, double *const cfluxes)
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
virtual void getMassFluxes (const double *state1, const double *state2, double delta, double *mfluxes)
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
virtual void getThermalDiffCoeffs (double *const dt)
Return a vector of Thermal diffusion coefficients [kg/m/sec].
virtual void getBinaryDiffCoeffs (const size_t ld, double *const d)
Returns the matrix of binary diffusion coefficients [m^2/s].
virtual void getMultiDiffCoeffs (const size_t ld, double *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void getMixDiffCoeffs (double *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMole (double *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMass (double *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getViscosityPolynomial (size_t i, double *coeffs) const
Return the polynomial fits to the viscosity of species i.
virtual void getConductivityPolynomial (size_t i, double *coeffs) const
Return the temperature fits of the heat conductivity of species i.
virtual void getBinDiffusivityPolynomial (size_t i, size_t j, double *coeffs) const
Return the polynomial fits to the binary diffusivity of species pair (i, j)
virtual void getCollisionIntegralPolynomial (size_t i, size_t j, double *astar_coeffs, double *bstar_coeffs, double *cstar_coeffs) const
Return the polynomial fits to the collision integral of species pair (i, j)
virtual void setViscosityPolynomial (size_t i, double *coeffs)
Modify the polynomial fits to the viscosity of species i.
virtual void setConductivityPolynomial (size_t i, double *coeffs)
Modify the temperature fits of the heat conductivity of species i.
virtual void setBinDiffusivityPolynomial (size_t i, size_t j, double *coeffs)
Modify the polynomial fits to the binary diffusivity of species pair (i, j)
virtual void setCollisionIntegralPolynomial (size_t i, size_t j, double *astar_coeffs, double *bstar_coeffs, double *cstar_coeffs, bool flag)
Modify the polynomial fits to the collision integral of species pair (i, j)
virtual void setParameters (const int type, const int k, const double *const p)
Set model parameters for derived classes.
AnyMap parameters () const
Return the parameters for a phase definition which are needed to reconstruct an identical object using the newTransport function.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
virtual double bulkViscosity ()
The bulk viscosity in Pa-s.
virtual double ionConductivity ()
The ionic conductivity in 1/ohm/m.
virtual void getSpeciesIonConductivity (double *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual void getFluidMobilities (double *const mobil_f)
Get the fluid mobilities (s kmol/kg).
virtual void setThermo (ThermoPhase &thermo)
Specifies the ThermoPhase object.
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
Protected Member Functions
void setupN64 ()
setup parameters for n64 model
virtual void fitDiffCoeffs (MMCollisionInt &integrals)
Generate polynomial fits to the binary diffusion coefficients.
double omega11_n64 (const double tstar, const double gamma)
Protected Member Functions inherited from MixTransport
void updateCond_T ()
Update the temperature dependent parts of the species thermal conductivities.
Protected Member Functions inherited from GasTransport
GasTransport (ThermoPhase *thermo=0)
virtual void update_T ()
virtual void update_C ()=0
virtual void updateViscosity_T ()
Update the temperature-dependent viscosity terms.
virtual void updateSpeciesViscosities ()
Update the pure-species viscosities.
virtual void updateDiff_T ()
Update the binary diffusion coefficients.
virtual void setupCollisionParameters ()
Setup parameters for a new kinetic-theory-based transport manager for low-density gases.
void setupCollisionIntegral ()
Setup range for polynomial fits to collision integrals of Monchick & Mason.
void getTransportData ()
Read the transport database.
void makePolarCorrections (size_t i, size_t j, doublereal &f_eps, doublereal &f_sigma)
Corrections for polar-nonpolar binary diffusion coefficients.
void fitCollisionIntegrals (MMCollisionInt &integrals)
Generate polynomial fits to collision integrals.
virtual void fitProperties (MMCollisionInt &integrals)
Generate polynomial fits to the viscosity and conductivity.
void getBinDiffCorrection (doublereal t, MMCollisionInt &integrals, size_t k, size_t j, doublereal xk, doublereal xj, doublereal &fkj, doublereal &fjk)
Second-order correction to the binary diffusion coefficients.
Protected Member Functions inherited from Transport
void finalize ()
Enable the transport object for use.
Protected Attributes
vector_fp m_speciesCharge
electrical properties
std::vector< size_t > m_kIon
index of ions (exclude electron.)
std::vector< size_t > m_kNeutral
index of neutral species
size_t m_kElectron = npos
index of electron
DenseMatrix m_gamma
parameter of omega11 of n64
vector_fp m_om11_O2
polynomial of the collision integral for O2/O2-
Protected Attributes inherited from MixTransport
vector_fp m_cond
vector of species thermal conductivities (W/m /K)
double m_lambda = 0.0
Internal storage for the calculated mixture thermal conductivity.
bool m_spcond_ok = false
Update boolean for the species thermal conductivities.
bool m_condmix_ok = false
Update boolean for the mixture rule for the mixture thermal conductivity.
Protected Attributes inherited from GasTransport
vector_fp m_molefracs
Vector of species mole fractions.
double m_viscmix = 0.0
Internal storage for the viscosity of the mixture (kg /m /s)
bool m_visc_ok = false
Update boolean for mixture rule for the mixture viscosity.
bool m_viscwt_ok = false
Update boolean for the weighting factors for the mixture viscosity.
bool m_spvisc_ok = false
Update boolean for the species viscosities.
bool m_bindiff_ok = false
Update boolean for the binary diffusivities at unit pressure.
int m_mode = 0
Type of the polynomial fits to temperature.
DenseMatrix m_phi
m_phi is a Viscosity Weighting Function. size = m_nsp * n_nsp
vector_fp m_spwork
work space length = m_kk
vector_fp m_visc
vector of species viscosities (kg /m /s).
std::vector< vector_fp > m_visccoeffs
Polynomial fits to the viscosity of each species.
vector_fp m_mw
Local copy of the species molecular weights.
DenseMatrix m_wratjk
Holds square roots of molecular weight ratios.
DenseMatrix m_wratkj1
Holds square roots of molecular weight ratios.
vector_fp m_sqvisc
vector of square root of species viscosities sqrt(kg /m /s).
vector_fp m_polytempvec
Powers of the ln temperature, up to fourth order.
double m_temp = -1.0
Current value of the temperature at which the properties in this object are calculated (Kelvin).
double m_kbt = 0.0
Current value of Boltzmann constant times the temperature (Joules)
double m_sqrt_t = 0.0
current value of temperature to 1/2 power
double m_logt = 0.0
Current value of the log of the temperature.
double m_t14 = 0.0
Current value of temperature to 1/4 power.
std::vector< vector_fp > m_diffcoeffs
Polynomial fits to the binary diffusivity of each species.
DenseMatrix m_bdiff
Matrix of binary diffusion coefficients at the reference pressure and the current temperature Size is nsp x nsp.
std::vector< vector_fp > m_condcoeffs
temperature fits of the heat conduction
std::vector< vector_int > m_poly
Indices for the (i,j) interaction in collision integral fits.
std::vector< vector_fp > m_omega22_poly
Fit for omega22 collision integral.
std::vector< vector_int > m_star_poly_uses_actualT
Flag to indicate for which (i,j) interaction pairs the actual temperature is used instead of the reduced temperature.
std::vector< vector_fp > m_astar_poly
Fit for astar collision integral.
std::vector< vector_fp > m_bstar_poly
Fit for bstar collision integral.
std::vector< vector_fp > m_cstar_poly
Fit for cstar collision integral.
vector_fp m_zrot
Rotational relaxation number for each species.
vector_fp m_crot
Dimensionless rotational heat capacity of each species.
std::vector< bool > m_polar
Vector of booleans indicating whether a species is a polar molecule.
vector_fp m_alpha
Polarizability of each species in the phase.
vector_fp m_eps
Lennard-Jones well-depth of the species in the current phase.
vector_fp m_sigma
Lennard-Jones diameter of the species in the current phase.
DenseMatrix m_reducedMass
This is the reduced mass of the interaction between species i and j.
DenseMatrix m_diam
hard-sphere diameter for (i,j) collision
DenseMatrix m_epsilon
The effective well depth for (i,j) collisions.
DenseMatrix m_dipole
The effective dipole moment for (i,j) collisions.
DenseMatrix m_delta
Reduced dipole moment of the interaction between two species.
vector_fp m_w_ac
Pitzer acentric factor.
vector_fp m_disp
Dispersion coefficient.
vector_fp m_quad_polar
Quadrupole polarizability.
int m_log_level = 0
Level of verbose printing during initialization.
Protected Attributes inherited from Transport
ThermoPhase * m_thermo
pointer to the object representing the phase
bool m_ready = false
true if finalize has been called
size_t m_nsp = 0
Number of species.
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis = VB_MASSAVG
Velocity basis from which diffusion velocities are computed.
std::weak_ptr< Solution > m_root
reference to Solution
Detailed Description
Class IonGasTransport implements Stockmayer-(n,6,4) model for transport of ions.
As implemented here, only binary transport between neutrals and ions is considered for calculating mixture-average diffusion coefficients and mobilities. When polarizability is not provide for an ion, LJ model is used instead of n64 model. Only neutral species are considered for thermal conductivity and viscosity.
References for Stockmayer-(n,6,4) model:
Selle, Stefan, and Uwe Riedel. "Transport properties of ionized species." Annals of the New York Academy of Sciences 891.1 (1999): 72-80.
Selle, Stefan, and Uwe Riedel. "Transport coefficients of reacting air at high temperatures." 38th Aerospace Sciences Meeting and Exhibit. 1999.
Han, Jie, et al. "Numerical modelling of ion transport in flames." Combustion Theory and Modelling 19.6 (2015): 744-772. DOI: 10.1080/13647830.2015.1090018
Chiflikian, R. V. "The analog of Blancs law for drift velocities of electrons in gas mixtures in weakly ionized plasma." Physics of Plasmas 2.10 (1995): 3902-3909.
Viehland, L. A., et al. "Tables of transport collision integrals for (n, 6, 4) ion-neutral potentials." Atomic Data and Nuclear Data Tables 16.6 (1975): 495-514.
Stockmayer-(n,6,4) model is not suitable for collision between O2/O2- due to resonant charge transfer. Therefore, an experimental collision data is used instead.
Data taken from:
Prager, Jens. Modeling and simulation of charged species in lean methane-oxygen flames. Diss. 2005. Page 104.
Definition at line 49 of file IonGasTransport.h.
Member Function Documentation
transportModel()
virtual std::string transportModel () const inline virtual
Identifies the model represented by this Transport object.
Each derived class should override this method to return a meaningful identifier.
Since
New in Cantera 3.0. The name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from MixTransport.
Definition at line 54 of file IonGasTransport.h.
init()
void init (ThermoPhase * thermo, int mode, int log_level) virtual
Initialize a transport manager.
This routine sets up a transport manager. It calculates the collision integrals and populates species-dependent data structures.
Parameters
thermo Pointer to the ThermoPhase object
mode Chemkin compatible mode or not. This alters the specification of the collision integrals. defaults to no.
log_level Defaults to zero, no logging
Reimplemented from MixTransport.
Definition at line 17 of file IonGasTransport.cpp.
References Phase::charge(), Cantera::getElementWeight(), GasTransport::m_bdiff, MixTransport::m_cond, IonGasTransport::m_kElectron, IonGasTransport::m_kIon, IonGasTransport::m_kNeutral, GasTransport::m_log_level, GasTransport::m_mode, GasTransport::m_molefracs, GasTransport::m_mw, Transport::m_nsp, IonGasTransport::m_om11_O2, GasTransport::m_phi, IonGasTransport::m_speciesCharge, GasTransport::m_spwork, GasTransport::m_sqvisc, Transport::m_thermo, GasTransport::m_visc, GasTransport::m_wratjk, GasTransport::m_wratkj1, Phase::molecularWeight(), Phase::molecularWeights(), Phase::nSpecies(), Cantera::polyfit(), DenseMatrix::resize(), GasTransport::setupCollisionIntegral(), GasTransport::setupCollisionParameters(), IonGasTransport::setupN64(), and Transport::thermo().
viscosity()
double viscosity () virtual
Viscosity of the mixture (kg/m/s).
Only Neutral species contribute to Viscosity.
Reimplemented from GasTransport.
Definition at line 96 of file IonGasTransport.cpp.
References IonGasTransport::m_kNeutral, GasTransport::m_molefracs, GasTransport::m_phi, GasTransport::m_spwork, GasTransport::m_visc, GasTransport::m_visc_ok, GasTransport::m_viscmix, GasTransport::m_viscwt_ok, Cantera::multiply(), MixTransport::update_C(), MixTransport::update_T(), and GasTransport::updateViscosity_T().
thermalConductivity()
double thermalConductivity () virtual
Returns the mixture thermal conductivity (W/m/K).
Only Neutral species contribute to thermal conductivity.
Reimplemented from MixTransport.
Definition at line 120 of file IonGasTransport.cpp.
References MixTransport::m_cond, MixTransport::m_condmix_ok, IonGasTransport::m_kNeutral, MixTransport::m_lambda, GasTransport::m_molefracs, MixTransport::m_spcond_ok, MixTransport::update_C(), MixTransport::update_T(), and MixTransport::updateCond_T().
getMobilities()
void getMobilities (double *const mobi) virtual
The mobilities for ions in gas.
The ion mobilities are calculated by Blanc's law.
Reimplemented from MixTransport.
Definition at line 382 of file IonGasTransport.cpp.
References Cantera::ElectronCharge, GasTransport::m_bdiff, GasTransport::m_bindiff_ok, GasTransport::m_kbt, IonGasTransport::m_kElectron, IonGasTransport::m_kIon, IonGasTransport::m_kNeutral, GasTransport::m_molefracs, Transport::m_nsp, Transport::m_thermo, Phase::pressure(), MixTransport::update_C(), MixTransport::update_T(), and GasTransport::updateDiff_T().
Referenced by IonGasTransport::electricalConductivity().
getMixDiffCoeffs()
void getMixDiffCoeffs (double *const d) virtual
The mixture transport for ionized gas.
The binary transport between two charged species is neglected.
Reimplemented from GasTransport.
Definition at line 347 of file IonGasTransport.cpp.
References Cantera::ElectronCharge, GasTransport::m_bdiff, GasTransport::m_bindiff_ok, GasTransport::m_kbt, IonGasTransport::m_kElectron, IonGasTransport::m_kNeutral, GasTransport::m_molefracs, GasTransport::m_mw, Transport::m_nsp, Transport::m_thermo, Phase::meanMolecularWeight(), Phase::pressure(), MixTransport::update_C(), MixTransport::update_T(), and GasTransport::updateDiff_T().
electricalConductivity()
double electricalConductivity () virtual
The electrical conductivity (Siemens/m).
\[ \sigma = \sum_k{\left|C_k\right| \mu_k \frac{X_k P}{k_b T}} \]
Reimplemented from Transport.
Definition at line 139 of file IonGasTransport.cpp.
References Cantera::ElectronCharge, IonGasTransport::getMobilities(), GasTransport::m_kbt, IonGasTransport::m_kElectron, IonGasTransport::m_kIon, GasTransport::m_molefracs, Transport::m_nsp, IonGasTransport::m_speciesCharge, Transport::m_thermo, Cantera::npos, and Phase::pressure().
setupN64()
void setupN64 () protected
setup parameters for n64 model
Definition at line 247 of file IonGasTransport.cpp.
References Cantera::ElectronCharge, Cantera::epsilon_0, GasTransport::m_alpha, GasTransport::m_diam, GasTransport::m_disp, GasTransport::m_epsilon, IonGasTransport::m_gamma, IonGasTransport::m_kIon, IonGasTransport::m_kNeutral, Transport::m_nsp, GasTransport::m_quad_polar, IonGasTransport::m_speciesCharge, Cantera::Pi, and DenseMatrix::resize().
Referenced by IonGasTransport::init().
fitDiffCoeffs()
void fitDiffCoeffs (MMCollisionInt & integrals) protected virtual
Generate polynomial fits to the binary diffusion coefficients.
Use Stockmayer-(n,6,4) model for collision between charged and neutral species.
Reimplemented from GasTransport.
Definition at line 156 of file IonGasTransport.cpp.
References Cantera::Boltzmann, GasTransport::fitDiffCoeffs(), GasTransport::m_alpha, GasTransport::m_diam, GasTransport::m_diffcoeffs, GasTransport::m_epsilon, IonGasTransport::m_gamma, IonGasTransport::m_kElectron, GasTransport::m_log_level, Transport::m_nsp, IonGasTransport::m_om11_O2, GasTransport::m_reducedMass, IonGasTransport::m_speciesCharge, Transport::m_thermo, ThermoPhase::maxTemp(), ThermoPhase::minTemp(), IonGasTransport::omega11_n64(), Cantera::Pi, Cantera::poly4(), Cantera::poly5(), Cantera::polyfit(), Phase::speciesIndex(), Phase::speciesName(), Cantera::vec2str(), Cantera::writelog(), and Cantera::writelogf().
omega11_n64()
double omega11_n64 (const double tstar, const double gamma) protected
Collision integral of omega11 of n64 collision model. The collision integral was fitted by Han et al. using the table by Viehlan et al. Note: Han release the range to 1000, but Selle suggested that a high temperature model is needed for T* > 10.
Definition at line 315 of file IonGasTransport.cpp.
Referenced by IonGasTransport::fitDiffCoeffs().
Member Data Documentation
m_speciesCharge
vector_fp m_speciesCharge protected
electrical properties
Definition at line 101 of file IonGasTransport.h.
Referenced by IonGasTransport::electricalConductivity(), IonGasTransport::fitDiffCoeffs(), IonGasTransport::init(), and IonGasTransport::setupN64().
m_kIon
std::vector<size_t> m_kIon protected
index of ions (exclude electron.)
Definition at line 104 of file IonGasTransport.h.
Referenced by IonGasTransport::electricalConductivity(), IonGasTransport::getMobilities(), IonGasTransport::init(), and IonGasTransport::setupN64().
m_kNeutral
std::vector<size_t> m_kNeutral protected
index of neutral species
Definition at line 107 of file IonGasTransport.h.
Referenced by IonGasTransport::getMixDiffCoeffs(), IonGasTransport::getMobilities(), IonGasTransport::init(), IonGasTransport::setupN64(), IonGasTransport::thermalConductivity(), and IonGasTransport::viscosity().
m_kElectron
size_t m_kElectron = npos protected
index of electron
Definition at line 110 of file IonGasTransport.h.
Referenced by IonGasTransport::electricalConductivity(), IonGasTransport::fitDiffCoeffs(), IonGasTransport::getMixDiffCoeffs(), IonGasTransport::getMobilities(), and IonGasTransport::init().
m_gamma
DenseMatrix m_gamma protected
parameter of omega11 of n64
Definition at line 113 of file IonGasTransport.h.
Referenced by IonGasTransport::fitDiffCoeffs(), and IonGasTransport::setupN64().
m_om11_O2
vector_fp m_om11_O2 protected
polynomial of the collision integral for O2/O2-
Definition at line 116 of file IonGasTransport.h.
Referenced by IonGasTransport::fitDiffCoeffs(), and IonGasTransport::init().
The documentation for this class was generated from the following files:
IonGasTransport.h
IonGasTransport.cpp