Cantera: WaterSSTP Class Reference
WaterSSTP Class Reference
Models of Phases of Matter » Thermodynamic Properties
Class for single-component water.
#include <WaterSSTP.h>
Public Member Functions
WaterSSTP (const std::string &inputFile="", const std::string &id="")
Full constructor for a water phase.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setDensity (const doublereal dens)
Set the density of the phase.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
WaterPropsIAPWS * getWater ()
Get a pointer to a changeable WaterPropsIAPWS object.
WaterProps * getWaterProps ()
Get a pointer to a changeable WaterPropsIAPWS object.
void _allowGasPhase (bool flag)
Switch that enables calculations in the gas phase.
Molar Thermodynamic Properties of the Solution
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Mechanical Equation of State Properties
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual doublereal dthermalExpansionCoeffdT () const
Return the derivative of the volumetric thermal expansion coefficient.
Properties of the Standard State of the Species in the Solution
virtual void getStandardChemPotentials (doublereal *gss) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Thermodynamic Values for the Species Reference State
All functions in this group need to be overridden, because the m_spthermo MultiSpeciesThermo function is not adequate for the real equation of state.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Public Member Functions inherited from SingleSpeciesTP
SingleSpeciesTP ()=default
Base empty constructor.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *murt) const
Get the array of non-dimensional species chemical potentials.
virtual void getChemPotentials (doublereal *mu) const
Get the array of chemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar internal energies. Units: J/kmol.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropy. Units: J/kmol K.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the species partial molar Heat Capacities. Units: J/ kmol /K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vbar) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void setMassFractions (const doublereal *const y)
Mass fractions are fixed, with Y[0] = 1.0.
virtual void setMoleFractions (const doublereal *const x)
Mole fractions are fixed, with x[0] = 1.0.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_DP (double rho, double p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual double molarVolume () const
Molar volume (m^3/kmol).
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
void _updateThermo () const
This routine must be overridden because it is not applicable.
Protected Member Functions inherited from SingleSpeciesTP
void _updateThermo () const
This internal routine calculates new species Cp0, H0, and S0 whenever the temperature has changed.
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Private Attributes
WaterPropsIAPWS m_sub
WaterPropsIAPWS that calculates the real properties of water.
std::unique_ptr< WaterProps > m_waterProps
Pointer to the WaterProps object.
double m_mw = 0.0
Molecular weight of Water -> Cantera assumption.
double EW_Offset = 0.0
Offset constants used to obtain consistency with the NIST database.
double SW_Offset = 0.0
Offset constant used to obtain consistency with NIST convention.
bool m_ready = false
Boolean is true if object has been properly initialized for calculation.
bool m_allowGasPhase = false
Since this phase represents a liquid (or supercritical) phase, it is an error to return a gas-phase answer.
Additional Inherited Members
Protected Attributes inherited from SingleSpeciesTP
double m_press = OneAtm
The current pressure of the solution (Pa). It gets initialized to 1 atm.
double m_p0 = OneAtm
double m_h0_RT
Dimensionless enthalpy at the (mtlast, m_p0)
double m_cp0_R
Dimensionless heat capacity at the (mtlast, m_p0)
double m_s0_R
Dimensionless entropy at the (mtlast, m_p0)
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Detailed Description
Class for single-component water.
This is designed to cover just the liquid and supercritical phases of water.
The reference is W. Wagner, A. Pruss, "The IAPWS Formulation 1995 for the Thermodynamic Properties of Ordinary Water Substance for General and Scientific Use," J. Phys. Chem. Ref. Dat, 31, 387, 2002.
Specification of Species Standard State Properties
The offsets used in the steam tables are different than NIST's. They assume u_liq(TP) = 0.0, s_liq(TP) = 0.0, where TP is the triple point conditions:
 -  u(273.16, rho)    = 0.0
 -  s(273.16, rho)    = 0.0
 -  psat(273.16)      = 611.655 Pascal
 -  rho(273.16, psat) = 999.793 kg m-3
These "steam table" assumptions are used by the WaterPropsIAPWS class. Therefore, offsets must be calculated to make the thermodynamic properties calculated within this class to be consistent with thermo properties within Cantera.
The thermodynamic base state for water is set to the NIST basis here by specifying constants, EW_Offset and SW_Offset, one for energy quantities and one for entropy quantities. The offsets are specified so that the following properties hold:
Delta_Hfo_idealgas(298.15) = -241.826 kJ/gmol
So_idealgas(298.15, 1bar) = 188.835 J/gmolK
(From http://webbook.nist.gov)
The "o" here refers to a hypothetical ideal gas state. The way we achieve this in practice is to evaluate at a very low pressure and then use the theoretical ideal gas results to scale up to higher pressures:
Ho(1bar) = H(P0)
So(1bar) = S(P0) + RT ln(1bar/P0)
Application within Kinetics Managers
This is unimplemented.
Definition at line 68 of file WaterSSTP.h.
Constructor & Destructor Documentation
WaterSSTP()
WaterSSTP (const std::string & inputFile = "", const std::string & id = "") explicit
Full constructor for a water phase.
Parameters
inputFile String name of the input file
id string id of the phase name
Definition at line 16 of file WaterSSTP.cpp.
References ThermoPhase::initThermoFile().
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from SingleSpeciesTP.
Definition at line 79 of file WaterSSTP.h.
phaseOfMatter()
std::string phaseOfMatter () const virtual
String indicating the mechanical phase of the matter in this Phase.
Options for the string are:
unspecified
supercritical
gas
liquid
solid
solid-liquid-mix
solid-gas-mix
liquid-gas-mix
solid-liquid-gas-mix
unspecified is the default and should be used when the Phase does not distinguish between mechanical phases or does not have enough information to determine which mechanical phase(s) are present.
Todo:
Needs to be implemented for all phase types. Currently only implemented for PureFluidPhase.
Reimplemented from ThermoPhase.
Definition at line 21 of file WaterSSTP.cpp.
References WaterSSTP::m_sub, and WaterPropsIAPWS::phaseState().
cv_mole()
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from SingleSpeciesTP.
Definition at line 126 of file WaterSSTP.cpp.
References WaterPropsIAPWS::cv_mass(), WaterSSTP::m_mw, and WaterSSTP::m_sub.
pressure()
doublereal pressure () const virtual
Return the thermodynamic pressure (Pa).
This method must be overloaded in derived classes. Within Cantera, the independent variable is either density or pressure. If the state is defined by temperature, density, and mass fractions, this method should use these values to implement the mechanical equation of state \(P(T, \rho, Y_1, \dots, Y_K) \). Alternatively, it returns a stored value.
Reimplemented from Phase.
Definition at line 238 of file WaterSSTP.cpp.
References WaterSSTP::m_sub, and WaterPropsIAPWS::pressure().
Referenced by WaterSSTP::dthermalExpansionCoeffdT(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), and WaterSSTP::getStandardVolumes_ref().
setPressure()
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
This method must be reimplemented in derived classes, where it may involve the solution of a nonlinear equation. Within Cantera, the independent variable is either density or pressure. Therefore, this function may either solve for the density that will yield the desired input pressure or set an independent variable. The temperature and composition are held constant during this process.
Parameters
p input Pressure (Pa)
Reimplemented from Phase.
Definition at line 243 of file WaterSSTP.cpp.
References Phase::density(), WaterPropsIAPWS::density(), WaterSSTP::m_allowGasPhase, WaterSSTP::m_sub, WaterPropsIAPWS::psat(), WaterSSTP::setDensity(), WaterPropsIAPWS::Tcrit(), and Phase::temperature().
isothermalCompressibility()
doublereal isothermalCompressibility () const virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented from ThermoPhase.
Definition at line 267 of file WaterSSTP.cpp.
References WaterPropsIAPWS::isothermalCompressibility(), and WaterSSTP::m_sub.
thermalExpansionCoeff()
doublereal thermalExpansionCoeff () const virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented from ThermoPhase.
Definition at line 272 of file WaterSSTP.cpp.
References WaterPropsIAPWS::coeffThermExp(), and WaterSSTP::m_sub.
dthermalExpansionCoeffdT()
doublereal dthermalExpansionCoeffdT () const virtual
Return the derivative of the volumetric thermal expansion coefficient.
Units: 1/K2.
Definition at line 277 of file WaterSSTP.cpp.
References WaterPropsIAPWS::coeffThermExp(), Phase::density(), WaterPropsIAPWS::density(), WaterSSTP::m_sub, WaterSSTP::pressure(), WaterPropsIAPWS::setState_TD(), and Phase::temperature().
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 112 of file WaterSSTP.cpp.
References WaterSSTP::EW_Offset, WaterPropsIAPWS::gibbs_mass(), WaterSSTP::m_mw, WaterSSTP::m_ready, WaterSSTP::m_sub, WaterSSTP::SW_Offset, and Phase::temperature().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 103 of file WaterSSTP.cpp.
References WaterSSTP::EW_Offset, Cantera::GasConstant, WaterPropsIAPWS::gibbs_mass(), WaterSSTP::m_mw, WaterSSTP::m_ready, WaterSSTP::m_sub, ThermoPhase::RT(), and WaterSSTP::SW_Offset.
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 88 of file WaterSSTP.cpp.
References WaterPropsIAPWS::enthalpy_mass(), WaterSSTP::EW_Offset, WaterSSTP::m_mw, WaterSSTP::m_sub, and ThermoPhase::RT().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 98 of file WaterSSTP.cpp.
References WaterPropsIAPWS::entropy_mass(), Cantera::GasConstant, WaterSSTP::m_mw, WaterSSTP::m_sub, and WaterSSTP::SW_Offset.
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 121 of file WaterSSTP.cpp.
References WaterPropsIAPWS::cp_mass(), Cantera::GasConstant, WaterSSTP::m_mw, and WaterSSTP::m_sub.
getIntEnergy_RT()
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 93 of file WaterSSTP.cpp.
References WaterSSTP::EW_Offset, WaterPropsIAPWS::intEnergy_mass(), WaterSSTP::m_mw, WaterSSTP::m_sub, and ThermoPhase::RT().
getEnthalpy_RT_ref()
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies. Length: m_kk.
Reimplemented from SingleSpeciesTP.
Definition at line 131 of file WaterSSTP.cpp.
References Phase::density(), WaterPropsIAPWS::density(), WaterPropsIAPWS::enthalpy_mass(), WaterSSTP::EW_Offset, WaterSSTP::m_mw, WaterSSTP::m_sub, Cantera::OneAtm, WaterSSTP::pressure(), WaterPropsIAPWS::Rhocrit(), ThermoPhase::RT(), and Phase::temperature().
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from SingleSpeciesTP.
Definition at line 150 of file WaterSSTP.cpp.
References Phase::density(), WaterPropsIAPWS::density(), WaterSSTP::EW_Offset, WaterPropsIAPWS::gibbs_mass(), WaterSSTP::m_mw, WaterSSTP::m_sub, Cantera::OneAtm, WaterSSTP::pressure(), WaterPropsIAPWS::Rhocrit(), ThermoPhase::RT(), WaterPropsIAPWS::setState_TD(), WaterSSTP::SW_Offset, and Phase::temperature().
Referenced by WaterSSTP::getGibbs_ref().
getGibbs_ref()
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from SingleSpeciesTP.
Definition at line 170 of file WaterSSTP.cpp.
References WaterSSTP::getGibbs_RT_ref(), Phase::m_kk, and ThermoPhase::RT().
getEntropy_R_ref()
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from SingleSpeciesTP.
Definition at line 178 of file WaterSSTP.cpp.
References Phase::density(), WaterPropsIAPWS::density(), WaterPropsIAPWS::entropy_mass(), Cantera::GasConstant, WaterSSTP::m_mw, WaterSSTP::m_sub, Cantera::OneAtm, WaterSSTP::pressure(), WaterPropsIAPWS::Rhocrit(), WaterPropsIAPWS::setState_TD(), WaterSSTP::SW_Offset, and Phase::temperature().
getCp_R_ref()
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from SingleSpeciesTP.
Definition at line 200 of file WaterSSTP.cpp.
References WaterPropsIAPWS::cp_mass(), Phase::density(), WaterPropsIAPWS::density(), Cantera::GasConstant, WaterSSTP::m_mw, WaterSSTP::m_sub, Cantera::OneAtm, WaterSSTP::pressure(), WaterPropsIAPWS::Rhocrit(), WaterPropsIAPWS::setState_TD(), and Phase::temperature().
getStandardVolumes_ref()
void getStandardVolumes_ref (doublereal * vol) const virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 220 of file WaterSSTP.cpp.
References Phase::density(), WaterPropsIAPWS::density(), WaterSSTP::m_sub, Phase::meanMolecularWeight(), Cantera::OneAtm, WaterSSTP::pressure(), WaterPropsIAPWS::Rhocrit(), and Phase::temperature().
critTemperature()
doublereal critTemperature () const virtual
Critical temperature (K).
Reimplemented from ThermoPhase.
Definition at line 294 of file WaterSSTP.cpp.
References WaterSSTP::m_sub, and WaterPropsIAPWS::Tcrit().
critPressure()
doublereal critPressure () const virtual
Critical pressure (Pa).
Reimplemented from ThermoPhase.
Definition at line 299 of file WaterSSTP.cpp.
References WaterSSTP::m_sub, and WaterPropsIAPWS::Pcrit().
critDensity()
doublereal critDensity () const virtual
Critical density (kg/m3).
Reimplemented from ThermoPhase.
Definition at line 304 of file WaterSSTP.cpp.
References WaterSSTP::m_sub, and WaterPropsIAPWS::Rhocrit().
satPressure()
doublereal satPressure (doublereal t) virtual
Return the saturation pressure given the temperature.
Parameters
t Temperature (Kelvin)
Reimplemented from ThermoPhase.
Definition at line 326 of file WaterSSTP.cpp.
References Phase::density(), WaterSSTP::m_sub, WaterPropsIAPWS::psat(), WaterPropsIAPWS::setState_TD(), and Phase::temperature().
compatibleWithMultiPhase()
virtual bool compatibleWithMultiPhase () const inline virtual
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
Returns false for special phase types which already represent multi-phase mixtures, namely PureFluidPhase.
Reimplemented from ThermoPhase.
Definition at line 136 of file WaterSSTP.h.
vaporFraction()
doublereal vaporFraction () const virtual
Return the fraction of vapor at the current conditions.
Below Tcrit, this routine will always return 0, by definition of the functionality of the routine. Above Tcrit, we query the density to toggle between 0 and 1.
Reimplemented from ThermoPhase.
Definition at line 334 of file WaterSSTP.cpp.
References Phase::density(), WaterSSTP::m_sub, WaterPropsIAPWS::Rhocrit(), WaterPropsIAPWS::Tcrit(), and Phase::temperature().
setTemperature()
void setTemperature (const doublereal temp) virtual
Set the temperature of the phase.
The density and composition of the phase is constant during this operator.
Parameters
temp Temperature (Kelvin)
Reimplemented from Phase.
Definition at line 309 of file WaterSSTP.cpp.
References Phase::density(), WaterSSTP::m_sub, WaterPropsIAPWS::setState_TD(), and Phase::setTemperature().
Referenced by WaterSSTP::initThermo().
setDensity()
void setDensity (const doublereal dens) virtual
Set the density of the phase.
The temperature and composition of the phase is constant during this operator.
Parameters
dens value of the density in kg m-3
Reimplemented from Phase.
Definition at line 320 of file WaterSSTP.cpp.
References WaterSSTP::m_sub, Phase::setDensity(), WaterPropsIAPWS::setState_TD(), and Phase::temperature().
Referenced by WaterSSTP::initThermo(), and WaterSSTP::setPressure().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from ThermoPhase.
Definition at line 28 of file WaterSSTP.cpp.
References Phase::atomicWeight(), WaterPropsIAPWS::density(), Phase::elementIndex(), SingleSpeciesTP::enthalpy_mole(), SingleSpeciesTP::entropy_mole(), WaterSSTP::EW_Offset, Cantera::GasConstant, ThermoPhase::initThermo(), WaterSSTP::m_mw, WaterSSTP::m_ready, WaterSSTP::m_sub, WaterSSTP::m_waterProps, Cantera::npos, Cantera::OneAtm, Phase::setDensity(), WaterSSTP::setDensity(), Phase::setMolecularWeight(), WaterSSTP::setTemperature(), Phase::setTemperature(), and WaterSSTP::SW_Offset.
getWater()
WaterPropsIAPWS * getWater () inline
Get a pointer to a changeable WaterPropsIAPWS object.
Definition at line 169 of file WaterSSTP.h.
References WaterSSTP::m_sub.
getWaterProps()
WaterProps * getWaterProps () inline
Get a pointer to a changeable WaterPropsIAPWS object.
Definition at line 174 of file WaterSSTP.h.
References WaterSSTP::m_waterProps.
_allowGasPhase()
void _allowGasPhase (bool flag) inline
Switch that enables calculations in the gas phase.
Since this phase represents a liquid (or supercritical) phase, it is an error to return a gas-phase answer. The sole intended use for this member function is to check the thermodynamic consistency of the underlying WaterProps class with ideal-gas thermo functions.
Definition at line 185 of file WaterSSTP.h.
References WaterSSTP::m_allowGasPhase.
_updateThermo()
void _updateThermo () const protected
This routine must be overridden because it is not applicable.
Member Data Documentation
m_sub
WaterPropsIAPWS m_sub mutable private
WaterPropsIAPWS that calculates the real properties of water.
Definition at line 193 of file WaterSSTP.h.
Referenced by WaterSSTP::critDensity(), WaterSSTP::critPressure(), WaterSSTP::critTemperature(), WaterSSTP::cv_mole(), WaterSSTP::dthermalExpansionCoeffdT(), WaterSSTP::getCp_R(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getIntEnergy_RT(), WaterSSTP::getStandardChemPotentials(), WaterSSTP::getStandardVolumes_ref(), WaterSSTP::getWater(), WaterSSTP::initThermo(), WaterSSTP::isothermalCompressibility(), WaterSSTP::phaseOfMatter(), WaterSSTP::pressure(), WaterSSTP::satPressure(), WaterSSTP::setDensity(), WaterSSTP::setPressure(), WaterSSTP::setTemperature(), WaterSSTP::thermalExpansionCoeff(), and WaterSSTP::vaporFraction().
m_waterProps
std::unique_ptr<WaterProps> m_waterProps private
Pointer to the WaterProps object.
This class is used to house several approximation routines for properties of water. This object owns m_waterProps, and the WaterPropsIAPWS object used by WaterProps is m_sub, which is defined above.
Definition at line 201 of file WaterSSTP.h.
Referenced by WaterSSTP::getWaterProps(), and WaterSSTP::initThermo().
m_mw
double m_mw = 0.0 private
Molecular weight of Water -> Cantera assumption.
Definition at line 204 of file WaterSSTP.h.
Referenced by WaterSSTP::cv_mole(), WaterSSTP::getCp_R(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getIntEnergy_RT(), WaterSSTP::getStandardChemPotentials(), and WaterSSTP::initThermo().
EW_Offset
double EW_Offset = 0.0 private
Offset constants used to obtain consistency with the NIST database.
This is added to all internal energy and enthalpy results. units = J kmol-1.
Definition at line 211 of file WaterSSTP.h.
Referenced by WaterSSTP::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getIntEnergy_RT(), WaterSSTP::getStandardChemPotentials(), and WaterSSTP::initThermo().
SW_Offset
double SW_Offset = 0.0 private
Offset constant used to obtain consistency with NIST convention.
This is added to all internal entropy results. units = J kmol-1 K-1.
Definition at line 218 of file WaterSSTP.h.
Referenced by WaterSSTP::getEntropy_R(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getStandardChemPotentials(), and WaterSSTP::initThermo().
m_ready
bool m_ready = false private
Boolean is true if object has been properly initialized for calculation.
Definition at line 221 of file WaterSSTP.h.
Referenced by WaterSSTP::getGibbs_RT(), WaterSSTP::getStandardChemPotentials(), and WaterSSTP::initThermo().
m_allowGasPhase
bool m_allowGasPhase = false private
Since this phase represents a liquid (or supercritical) phase, it is an error to return a gas-phase answer.
However, if the below is true, then a gas-phase answer is allowed. This is used to check the thermodynamic consistency with ideal-gas thermo functions for example.
Definition at line 229 of file WaterSSTP.h.
Referenced by WaterSSTP::_allowGasPhase(), and WaterSSTP::setPressure().
The documentation for this class was generated from the following files:
WaterSSTP.h
WaterSSTP.cpp