Cantera: LatticeSolidPhase Class Reference
LatticeSolidPhase Class Reference
A phase that is comprised of a fixed additive combination of other lattice phases.
#include <LatticeSolidPhase.h>
Public Member Functions
LatticeSolidPhase ()=default
Base empty constructor.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual doublereal enthalpy_mole () const
Return the Molar Enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Return the Molar Internal Energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Return the Molar Entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Return the Molar Gibbs energy. Units: J/kmol.
virtual doublereal cp_mole () const
Return the constant pressure heat capacity. Units: J/kmol/K.
virtual doublereal cv_mole () const
Return the constant volume heat capacity. Units: J/kmol/K.
virtual doublereal pressure () const
Report the Pressure. Units: Pa.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature. Units: Pa.
doublereal calcDensity ()
Calculate the density of the solid mixture.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0 for each of the subphases.
virtual void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual doublereal moleFraction (const int k) const
virtual void getMassFractions (doublereal *const y) const
virtual doublereal massFraction (const int k) const
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
virtual doublereal concentration (size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Returns an array of partial molar Heat Capacities at constant pressure of the species in the solution.
virtual void getPartialMolarVolumes (doublereal *vbar) const
returns an array of partial molar volumes of the species in the solution.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of standard state chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
void addLattice (shared_ptr< ThermoPhase > lattice)
Add a lattice to this phase.
void setLatticeStoichiometry (const compositionMap &comp)
Set the lattice stoichiometric coefficients, \(\theta_i \).
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
void setLatticeMoleFractionsByName (int n, const std::string &x)
Set the Lattice mole fractions using a string.
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
Thermodynamic Values for the Species Reference States
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_DP (double rho, double p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double electronTemperature () const
Electron Temperature (K)
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (double temp)
Set the internally stored temperature of the phase (K).
virtual void setElectronTemperature (double etemp)
Set the internally stored electron temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Attributes
double m_press = -1.0
Current value of the pressure.
double m_molar_density = 0.0
Current value of the molar density.
std::vector< shared_ptr< ThermoPhase > > m_lattice
Vector of sublattice ThermoPhase objects.
vector_fp m_x
Vector of mole fractions.
vector_fp theta_
Lattice stoichiometric coefficients.
vector_fp tmpV_
Temporary vector.
std::vector< size_t > lkstart_
AnyMap m_rootNode
Root node of the AnyMap which contains this phase definition.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Private Member Functions
void _updateThermo () const
Update the reference thermodynamic functions.
Additional Inherited Members
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Detailed Description
A phase that is comprised of a fixed additive combination of other lattice phases.
This is the main way Cantera describes semiconductors and other solid phases. This ThermoPhase object calculates its properties as a sum over other LatticePhase objects. Each of the LatticePhase objects is a ThermoPhase object by itself.
The results from this LatticeSolidPhase model reduces to the LatticePhase model when there is one lattice phase and the molar densities of the sublattice and the molar density within the LatticeSolidPhase have the same values.
The mole fraction vector is redefined within the LatticeSolidPhase object. Each of the mole fractions sum to one on each of the sublattices. The routine getMoleFraction() and setMoleFraction() have been redefined to use this convention.
Specification of Species Standard State Properties
The standard state properties are calculated in the normal way for each of the sublattices. The normal way here means that a thermodynamic polynomial in temperature is developed. Also, a constant volume approximation for the pressure dependence is assumed. All of these properties are on a Joules per kmol of sublattice constituent basis.
Specification of Solution Thermodynamic Properties
The sum over the LatticePhase objects is carried out by weighting each LatticePhase object value with the molar density (kmol m-3) of its LatticePhase. Then the resulting quantity is divided by the molar density of the total compound. The LatticeSolidPhase object therefore only contains a listing of the number of LatticePhase object that comprises the solid, and it contains a value for the molar density of the entire mixture. This is the same thing as saying that
\[ L_i = L^{solid} \theta_i \]
\(L_i \) is the molar volume of the ith lattice. \(L^{solid} \) is the molar volume of the entire solid. \(\theta_i \) is a fixed weighting factor for the ith lattice representing the lattice stoichiometric coefficient. For this object the \(\theta_i \) values are fixed.
Let's take FeS2 as an example, which may be thought of as a combination of two lattices: Fe and S lattice. The Fe sublattice has a molar density of 1 gmol cm-3. The S sublattice has a molar density of 2 gmol cm-3. We then define the LatticeSolidPhase object as having a nominal composition of FeS2, and having a molar density of 1 gmol cm-3. All quantities pertaining to the FeS2 compound will be have weights associated with the sublattices. The Fe sublattice will have a weight of 1.0 associated with it. The S sublattice will have a weight of 2.0 associated with it.
Specification of Solution Density Properties
Currently, molar density is not a constant within the object, even though the species molar volumes are a constant. The basic idea is that a swelling of one of the sublattices will result in a swelling of of all of the lattices. Therefore, the molar volumes of the individual lattices are not independent of one another.
The molar volume of the Lattice solid is calculated from the following formula
\[ V = \sum_i{ \theta_i V_i^{lattice}} \]
where \(V_i^{lattice} \) is the molar volume of the ith sublattice. This is calculated from the following standard formula.
\[ V_i = \sum_k{ X_k V_k} \]
where k is a species in the ith sublattice.
The mole fraction vector is redefined within the the LatticeSolidPhase object. Each of the mole fractions sum to one on each of the sublattices. The routine getMoleFraction() and setMoleFraction() have been redefined to use this convention.
(This object is still under construction)
Definition at line 104 of file LatticeSolidPhase.h.
Constructor & Destructor Documentation
LatticeSolidPhase()
LatticeSolidPhase () default
Base empty constructor.
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from ThermoPhase.
Definition at line 110 of file LatticeSolidPhase.h.
phaseOfMatter()
virtual std::string phaseOfMatter () const inline virtual
String indicating the mechanical phase of the matter in this Phase.
LatticeSolid phases only represent solids.
Reimplemented from ThermoPhase.
Definition at line 118 of file LatticeSolidPhase.h.
isCompressible()
virtual bool isCompressible () const inline virtual
Return whether phase represents a compressible substance.
Reimplemented from Phase.
Definition at line 122 of file LatticeSolidPhase.h.
nativeState()
std::map< std::string, size_t > nativeState () const inline virtual
Return a map of properties defining the native state of a substance.
By default, entries include "T", "D", "Y" for a compressible substance and "T", "P", "Y" for an incompressible substance, with offsets 0, 1 and 2, respectively. Mass fractions "Y" are omitted for pure species. In all cases, offsets into the state vector are used by saveState() and restoreState().
Reimplemented from Phase.
Definition at line 126 of file LatticeSolidPhase.h.
minTemp()
doublereal minTemp (size_t k = npos) const virtual
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented from ThermoPhase.
Definition at line 26 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::m_lattice, and Cantera::npos.
maxTemp()
doublereal maxTemp (size_t k = npos) const virtual
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented from ThermoPhase.
Definition at line 43 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::m_lattice, and Cantera::npos.
refPressure()
doublereal refPressure () const virtual
Returns the reference pressure in Pa.
This function is a wrapper that calls the species thermo refPressure function.
Reimplemented from ThermoPhase.
Definition at line 60 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::m_lattice.
standardStateConvention()
virtual int standardStateConvention () const inline virtual
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
All of the thermo is determined by slave ThermoPhase routines.
Reimplemented from ThermoPhase.
Definition at line 140 of file LatticeSolidPhase.h.
References Cantera::cSS_CONVENTION_SLAVE.
enthalpy_mole()
doublereal enthalpy_mole () const virtual
Return the Molar Enthalpy. Units: J/kmol.
The molar enthalpy is determined by the following formula, where \(\theta_n \) is the lattice stoichiometric coefficient of the nth lattice
\[ \tilde h(T,P) = {\sum_n \theta_n \tilde h_n(T,P) } \]
\(\tilde h_n(T,P) \) is the enthalpy of the nth lattice.
units J/kmol
Reimplemented from ThermoPhase.
Definition at line 65 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
intEnergy_mole()
doublereal intEnergy_mole () const virtual
Return the Molar Internal Energy. Units: J/kmol.
The molar enthalpy is determined by the following formula, where \(\theta_n \) is the lattice stoichiometric coefficient of the nth lattice
\[ \tilde u(T,P) = {\sum_n \theta_n \tilde u_n(T,P) } \]
\(\tilde u_n(T,P) \) is the internal energy of the nth lattice.
units J/kmol
Reimplemented from ThermoPhase.
Definition at line 75 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
entropy_mole()
doublereal entropy_mole () const virtual
Return the Molar Entropy. Units: J/kmol/K.
The molar enthalpy is determined by the following formula, where \(\theta_n \) is the lattice stoichiometric coefficient of the nth lattice
\[ \tilde s(T,P) = \sum_n \theta_n \tilde s_n(T,P) \]
\(\tilde s_n(T,P) \) is the molar entropy of the nth lattice.
units J/kmol/K
Reimplemented from ThermoPhase.
Definition at line 85 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
gibbs_mole()
doublereal gibbs_mole () const virtual
Return the Molar Gibbs energy. Units: J/kmol.
The molar Gibbs free energy is determined by the following formula, where \(\theta_n \) is the lattice stoichiometric coefficient of the nth lattice
\[ \tilde h(T,P) = {\sum_n \theta_n \tilde h_n(T,P) } \]
\(\tilde h_n(T,P) \) is the enthalpy of the nth lattice.
units J/kmol
Reimplemented from ThermoPhase.
Definition at line 95 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
cp_mole()
doublereal cp_mole () const virtual
Return the constant pressure heat capacity. Units: J/kmol/K.
The molar constant pressure heat capacity is determined by the following formula, where \(C_n \) is the lattice molar density of the nth lattice, and \(C_T \) is the molar density of the solid compound.
\[ \tilde c_{p,n}(T,P) = \frac{\sum_n C_n \tilde c_{p,n}(T,P) }{C_T}, \]
\(\tilde c_{p,n}(T,P) \) is the heat capacity of the nth lattice.
units J/kmol/K
Reimplemented from ThermoPhase.
Definition at line 105 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
Referenced by LatticeSolidPhase::cv_mole().
cv_mole()
virtual doublereal cv_mole () const inline virtual
Return the constant volume heat capacity. Units: J/kmol/K.
The molar constant volume heat capacity is determined by the following formula, where \(C_n \) is the lattice molar density of the nth lattice, and \(C_T \) is the molar density of the solid compound.
\[ \tilde c_{v,n}(T,P) = \frac{\sum_n C_n \tilde c_{v,n}(T,P) }{C_T}, \]
\(\tilde c_{v,n}(T,P) \) is the heat capacity of the nth lattice.
units J/kmol/K
Reimplemented from ThermoPhase.
Definition at line 235 of file LatticeSolidPhase.h.
References LatticeSolidPhase::cp_mole().
pressure()
virtual doublereal pressure () const inline virtual
Report the Pressure. Units: Pa.
This method simply returns the stored pressure value.
Reimplemented from Phase.
Definition at line 243 of file LatticeSolidPhase.h.
References LatticeSolidPhase::m_press.
setPressure()
void setPressure (doublereal p) virtual
Set the pressure at constant temperature. Units: Pa.
Parameters
p Pressure (units - Pa)
Reimplemented from Phase.
Definition at line 147 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::calcDensity(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::m_press.
calcDensity()
doublereal calcDensity ()
Calculate the density of the solid mixture.
The formula for this is
\[ \rho = \sum_n{ \rho_n \theta_n } \]
where \(\rho_n \) is the density of the nth sublattice
Definition at line 156 of file LatticeSolidPhase.cpp.
References Phase::assignDensity(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
Referenced by LatticeSolidPhase::setMoleFractions(), and LatticeSolidPhase::setPressure().
setMoleFractions()
void setMoleFractions (const doublereal *const x) virtual
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0 for each of the subphases.
On input, the mole fraction vector is assumed to sum to one for each of the sublattices. The sublattices are updated with this mole fraction vector. The mole fractions are also stored within this object, after they are normalized to one by dividing by the number of sublattices.
Parameters
x Input vector of mole fractions. There is no restriction on the sum of the mole fraction vector. Internally, this object will pass portions of this vector to the sublattices which assume that the portions individually sum to one. Length is m_kk.
Reimplemented from Phase.
Definition at line 166 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::calcDensity(), LatticeSolidPhase::m_lattice, LatticeSolidPhase::m_x, and Phase::setMoleFractions().
Referenced by LatticeSolidPhase::initThermo(), and LatticeSolidPhase::setLatticeMoleFractionsByName().
getMoleFractions()
void getMoleFractions (doublereal *const x) const virtual
Get the species mole fraction vector.
On output the mole fraction vector will sum to one for each of the subphases which make up this phase.
Parameters
x On return, x contains the mole fractions. Must have a length greater than or equal to the number of species.
Definition at line 181 of file LatticeSolidPhase.cpp.
References Phase::getMoleFractions(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::m_x.
Referenced by LatticeSolidPhase::_updateThermo().
moleFraction()
virtual doublereal moleFraction (const int k) const inline virtual
Definition at line 290 of file LatticeSolidPhase.h.
getMassFractions()
virtual void getMassFractions (doublereal *const y) const inline virtual
Definition at line 294 of file LatticeSolidPhase.h.
massFraction()
virtual doublereal massFraction (const int k) const inline virtual
Definition at line 298 of file LatticeSolidPhase.h.
setMassFractions()
virtual void setMassFractions (const doublereal *const y) inline virtual
Set the mass fractions to the specified values and normalize them.
Parameters
[in] y Array of unnormalized mass fraction values. Length must be greater than or equal to the number of species. The Phase object will normalize this vector before storing its contents.
Reimplemented from Phase.
Definition at line 302 of file LatticeSolidPhase.h.
setMassFractions_NoNorm()
virtual void setMassFractions_NoNorm (const doublereal *const y) inline virtual
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented from Phase.
Definition at line 306 of file LatticeSolidPhase.h.
getConcentrations()
virtual void getConcentrations (doublereal *const c) const inline virtual
Get the species concentrations (kmol/m^3).
Parameters
[out] c The vector of species concentrations. Units are kmol/m^3. The length of the vector must be greater than or equal to the number of species within the phase.
Reimplemented from Phase.
Definition at line 310 of file LatticeSolidPhase.h.
concentration()
virtual doublereal concentration (size_t k) const inline virtual
Concentration of species k.
If k is outside the valid range, an exception will be thrown.
Parameters
[in] k Index of the species within the phase.
Returns
the concentration of species k (kmol m-3).
Reimplemented from Phase.
Definition at line 314 of file LatticeSolidPhase.h.
setConcentrations()
virtual void setConcentrations (const doublereal *const conc) inline virtual
Set the concentrations to the specified values within the phase.
We set the concentrations here and therefore we set the overall density of the phase. We hold the temperature constant during this operation. Therefore, we have possibly changed the pressure of the phase by calling this routine.
Parameters
[in] conc Array of concentrations in dimensional units. For bulk phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the number of species in the phase.
Reimplemented from Phase.
Definition at line 318 of file LatticeSolidPhase.h.
standardConcentrationUnits()
Units standardConcentrationUnits () const virtual
Returns the units of the "standard concentration" for this phase.
These are the units of the values returned by the functions getActivityConcentrations() and standardConcentration(), which can vary between different ThermoPhase-derived classes, or change within a single class depending on input options. See the documentation for standardConcentration() for the derived class for specific details.
Reimplemented from ThermoPhase.
Definition at line 115 of file LatticeSolidPhase.cpp.
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 120 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
getActivityCoefficients()
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 130 of file LatticeSolidPhase.cpp.
References Phase::m_kk.
getChemPotentials()
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
This returns the underlying lattice chemical potentials, as the units are kmol-1 of the sublattice species.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 209 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol). For this phase, the partial molar enthalpies are equal to the pure species enthalpies
\[ \bar h_k(T,P) = \hat h^{ref}_k(T) + (P - P_{ref}) \hat V^0_k \]
The reference-state pure-species enthalpies, \(\hat h^{ref}_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See also
MultiSpeciesThermo
Parameters
hbar Output vector containing partial molar enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 220 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
getPartialMolarEntropies()
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K. For this phase, the partial molar entropies are equal to the pure species entropies plus the ideal solution contribution.
\[ \bar s_k(T,P) = \hat s^0_k(T) - R log(X_k) \]
The reference-state pure-species entropies, \(\hat s^{ref}_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See also
MultiSpeciesThermo
Parameters
sbar Output vector containing partial molar entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 231 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
getPartialMolarCp()
void getPartialMolarCp (doublereal * cpbar) const virtual
Returns an array of partial molar Heat Capacities at constant pressure of the species in the solution.
Units: J/kmol/K. For this phase, the partial molar heat capacities are equal to the standard state heat capacities.
Parameters
cpbar Output vector of partial heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 242 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
getPartialMolarVolumes()
void getPartialMolarVolumes (doublereal * vbar) const virtual
returns an array of partial molar volumes of the species in the solution.
Units: m^3 kmol-1.
For this solution, the partial molar volumes are equal to the constant species molar volumes.
Parameters
vbar Output vector of partial molar volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 253 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu0) const virtual
Get the array of standard state chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution.
This returns the underlying lattice standard chemical potentials, as the units are kmol-1 of the sublattice species.
Parameters
mu0 Output vector of chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 264 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (that is, generalized) concentration. In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (such as surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard concentration. The units are by definition dependent on the ThermoPhase and kinetics manager representation.
Reimplemented from ThermoPhase.
Definition at line 137 of file LatticeSolidPhase.cpp.
logStandardConc()
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 142 of file LatticeSolidPhase.cpp.
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 274 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), and LatticeSolidPhase::m_lattice.
Referenced by LatticeSolidPhase::getGibbs_ref().
getGibbs_ref()
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 282 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::getGibbs_RT_ref(), Phase::m_kk, and ThermoPhase::RT().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Reimplemented from ThermoPhase.
Definition at line 345 of file LatticeSolidPhase.cpp.
addLattice()
void addLattice (shared_ptr< ThermoPhase > lattice)
Add a lattice to this phase.
Definition at line 351 of file LatticeSolidPhase.cpp.
References Phase::addElement(), ThermoPhase::addSpecies(), LatticeSolidPhase::m_lattice, LatticeSolidPhase::m_x, LatticeSolidPhase::theta_, and LatticeSolidPhase::tmpV_.
Referenced by LatticeSolidPhase::initThermo().
setLatticeStoichiometry()
void setLatticeStoichiometry (const compositionMap & comp)
Set the lattice stoichiometric coefficients, \(\theta_i \).
Definition at line 378 of file LatticeSolidPhase.cpp.
References Phase::addElement(), CT_ELEM_TYPE_LATTICERATIO, Cantera::getValue(), LatticeSolidPhase::m_lattice, Phase::m_speciesComp, Phase::name(), Phase::nElements(), and LatticeSolidPhase::theta_.
Referenced by LatticeSolidPhase::initThermo().
setParameters()
void setParameters (const AnyMap & phaseNode, const AnyMap & rootNode = AnyMap()) virtual
Set equation of state parameters from an AnyMap phase description.
Phases that need additional parameters from the root node should override this method.
Reimplemented from ThermoPhase.
Definition at line 290 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::m_rootNode, and ThermoPhase::setParameters().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from ThermoPhase.
Definition at line 297 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::addLattice(), AnyMap::hasKey(), ThermoPhase::initThermo(), ThermoPhase::m_input, LatticeSolidPhase::m_rootNode, LatticeSolidPhase::m_x, Phase::name(), Cantera::newThermo(), LatticeSolidPhase::setLatticeStoichiometry(), and LatticeSolidPhase::setMoleFractions().
getParameters()
void getParameters (AnyMap & phaseNode) const virtual
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
This does not include user-defined fields available in input().
Reimplemented from ThermoPhase.
Definition at line 312 of file LatticeSolidPhase.cpp.
References AnyMap::erase(), ThermoPhase::getParameters(), LatticeSolidPhase::m_lattice, and LatticeSolidPhase::theta_.
getSpeciesParameters()
void getSpeciesParameters (const std::string & name, AnyMap & speciesNode) const virtual
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
Parameters
name Name of the species
speciesNode Mapping to be populated with parameters
Reimplemented from ThermoPhase.
Definition at line 332 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::m_lattice, Phase::name(), and Cantera::npos.
setLatticeMoleFractionsByName()
void setLatticeMoleFractionsByName (int n, const std::string & x)
Set the Lattice mole fractions using a string.
Parameters
n Integer value of the lattice whose mole fractions are being set
x string containing Name:value pairs that will specify the mole fractions of species on a particular lattice
Definition at line 414 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::m_lattice, LatticeSolidPhase::m_x, and LatticeSolidPhase::setMoleFractions().
modifyOneHf298SS()
void modifyOneHf298SS (const size_t k, const doublereal Hf298New) virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented from ThermoPhase.
Definition at line 429 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), ThermoPhase::invalidateCache(), LatticeSolidPhase::m_lattice, and MultiSpeciesThermo::modifyOneHf298().
resetHf298()
void resetHf298 (const size_t k = npos) virtual
Restore the original heat of formation of one or more species.
Resets changes made by modifyOneHf298SS(). If the species index is not specified, the heats of formation for all species are restored.
Reimplemented from ThermoPhase.
Definition at line 442 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::_updateThermo(), ThermoPhase::invalidateCache(), LatticeSolidPhase::m_lattice, and Cantera::npos.
_updateThermo()
void _updateThermo () const private
Update the reference thermodynamic functions.
Definition at line 398 of file LatticeSolidPhase.cpp.
References LatticeSolidPhase::getMoleFractions(), LatticeSolidPhase::m_lattice, LatticeSolidPhase::m_press, ThermoPhase::m_tlast, LatticeSolidPhase::m_x, and Phase::temperature().
Referenced by LatticeSolidPhase::cp_mole(), LatticeSolidPhase::enthalpy_mole(), LatticeSolidPhase::entropy_mole(), LatticeSolidPhase::getActivityConcentrations(), LatticeSolidPhase::getChemPotentials(), LatticeSolidPhase::getGibbs_RT_ref(), LatticeSolidPhase::getPartialMolarCp(), LatticeSolidPhase::getPartialMolarEnthalpies(), LatticeSolidPhase::getPartialMolarEntropies(), LatticeSolidPhase::getPartialMolarVolumes(), LatticeSolidPhase::getStandardChemPotentials(), LatticeSolidPhase::gibbs_mole(), LatticeSolidPhase::intEnergy_mole(), LatticeSolidPhase::modifyOneHf298SS(), and LatticeSolidPhase::resetHf298().
Member Data Documentation
m_press
double m_press = -1.0 protected
Current value of the pressure.
Definition at line 454 of file LatticeSolidPhase.h.
Referenced by LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::pressure(), and LatticeSolidPhase::setPressure().
m_molar_density
double m_molar_density = 0.0 protected
Current value of the molar density.
Definition at line 457 of file LatticeSolidPhase.h.
m_lattice
std::vector<shared_ptr<ThermoPhase> > m_lattice protected
Vector of sublattice ThermoPhase objects.
Definition at line 460 of file LatticeSolidPhase.h.
Referenced by LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::addLattice(), LatticeSolidPhase::calcDensity(), LatticeSolidPhase::cp_mole(), LatticeSolidPhase::enthalpy_mole(), LatticeSolidPhase::entropy_mole(), LatticeSolidPhase::getActivityConcentrations(), LatticeSolidPhase::getChemPotentials(), LatticeSolidPhase::getGibbs_RT_ref(), LatticeSolidPhase::getMoleFractions(), LatticeSolidPhase::getParameters(), LatticeSolidPhase::getPartialMolarCp(), LatticeSolidPhase::getPartialMolarEnthalpies(), LatticeSolidPhase::getPartialMolarEntropies(), LatticeSolidPhase::getPartialMolarVolumes(), LatticeSolidPhase::getSpeciesParameters(), LatticeSolidPhase::getStandardChemPotentials(), LatticeSolidPhase::gibbs_mole(), LatticeSolidPhase::intEnergy_mole(), LatticeSolidPhase::maxTemp(), LatticeSolidPhase::minTemp(), LatticeSolidPhase::modifyOneHf298SS(), LatticeSolidPhase::refPressure(), LatticeSolidPhase::resetHf298(), LatticeSolidPhase::setLatticeMoleFractionsByName(), LatticeSolidPhase::setLatticeStoichiometry(), LatticeSolidPhase::setMoleFractions(), and LatticeSolidPhase::setPressure().
m_x
vector_fp m_x mutable protected
Vector of mole fractions.
Note these mole fractions sum to one when summed over all phases. However, this is not what's passed down to the lower m_lattice objects.
Definition at line 467 of file LatticeSolidPhase.h.
Referenced by LatticeSolidPhase::_updateThermo(), LatticeSolidPhase::addLattice(), LatticeSolidPhase::getMoleFractions(), LatticeSolidPhase::initThermo(), LatticeSolidPhase::setLatticeMoleFractionsByName(), and LatticeSolidPhase::setMoleFractions().
theta_
vector_fp theta_ protected
Lattice stoichiometric coefficients.
Definition at line 470 of file LatticeSolidPhase.h.
Referenced by LatticeSolidPhase::addLattice(), LatticeSolidPhase::calcDensity(), LatticeSolidPhase::cp_mole(), LatticeSolidPhase::enthalpy_mole(), LatticeSolidPhase::entropy_mole(), LatticeSolidPhase::getParameters(), LatticeSolidPhase::gibbs_mole(), LatticeSolidPhase::intEnergy_mole(), and LatticeSolidPhase::setLatticeStoichiometry().
tmpV_
vector_fp tmpV_ mutable protected
Temporary vector.
Definition at line 473 of file LatticeSolidPhase.h.
Referenced by LatticeSolidPhase::addLattice().
lkstart_
std::vector<size_t> lkstart_ protected
Definition at line 475 of file LatticeSolidPhase.h.
m_rootNode
AnyMap m_rootNode protected
Root node of the AnyMap which contains this phase definition.
Used to look up the phase definitions for the constituent phases.
Definition at line 479 of file LatticeSolidPhase.h.
Referenced by LatticeSolidPhase::initThermo(), and LatticeSolidPhase::setParameters().
The documentation for this class was generated from the following files:
LatticeSolidPhase.h
LatticeSolidPhase.cpp