Cantera: Composite Objects
Composite Objects
Composite objects create a high-level interface to Cantera's core objects.
Classes
class Interface
A container class for chemically-reacting interfaces.
class Solution
A container class for chemically-reacting solutions.
class SolutionArray
A container class holding arrays of state information.
Functions
shared_ptr< Interface > newInterface (const std::string &infile, const std::string &name="", const std::vector< std::string > &adjacent={})
Create and initialize a new Interface from an input file.
shared_ptr< Interface > newInterface (const std::string &infile, const std::string &name, const std::vector< shared_ptr< Solution > > &adjacent)
Create and initialize a new Interface from an input file.
shared_ptr< Interface > newInterface (AnyMap &phaseNode, const AnyMap &rootNode=AnyMap(), const std::vector< shared_ptr< Solution > > &adjacent={})
Create and initialize a new Interface from AnyMap objects.
shared_ptr< Solution > newSolution (const std::string &infile, const std::string &name, const std::string &transport, const std::vector< std::string > &adjacent)
Create and initialize a new Solution from an input file.
shared_ptr< Solution > newSolution (const std::string &infile, const std::string &name="", const std::string &transport="", const std::vector< shared_ptr< Solution > > &adjacent={})
Create and initialize a new Solution manager from an input file.
shared_ptr< Solution > newSolution (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap(), const std::string &transport="", const std::vector< shared_ptr< Solution > > &adjacent={}, const std::map< std::string, shared_ptr< Solution > > &related={})
Create and initialize a new Solution manager from AnyMap objects.
Detailed Description
Composite objects create a high-level interface to Cantera's core objects.
Function Documentation
newInterface() [1/3]
shared_ptr< Interface > newInterface (const std::string & infile, const std::string & name = "", const std::vector< std::string > & adjacent = {})
Create and initialize a new Interface from an input file.
This constructor wraps newThermo() and newKinetics()
Parameters
infile name of the input file
name name of the surface phase in the file. If this is blank, the first phase in the file is used.
adjacent vector containing names of adjacent phases that participate in this phases kinetics. If empty, adjacent phases will be instantiated based on the phase definition.
Returns
an initialized Interface object.
Definition at line 35 of file Interface.cpp.
References AnyMap::fromYamlFile(), and Cantera::newSolution().
Referenced by Cantera::newInterface().
newInterface() [2/3]
shared_ptr< Interface > newInterface (const std::string & infile, const std::string & name, const std::vector< shared_ptr< Solution > > & adjacent)
Create and initialize a new Interface from an input file.
This constructor wraps newThermo() and newKinetics()
Parameters
infile name of the input file
name name of the phase in the file. If this is the empty string, the first phase in the file is used.
adjacent vector containing adjacent Solution objects. If empty, adjacent phases will be instantiated based on the phase definition.
Returns
an initialized Interface object.
Definition at line 49 of file Interface.cpp.
References AnyMap::fromYamlFile(), and Cantera::newInterface().
newInterface() [3/3]
shared_ptr< Interface > newInterface (AnyMap & phaseNode, const AnyMap & rootNode = AnyMap(), const std::vector< shared_ptr< Solution > > & adjacent = {})
Create and initialize a new Interface from AnyMap objects.
This constructor wraps newThermo() and newKinetics()
Parameters
phaseNode the node containing the phase definition (that is, thermo model, list of species, and initial state)
rootNode the root node of the tree containing the phase definition, which will be used as the default location from which to read species definitions.
adjacent vector containing adjacent Solution objects. If empty, adjacent phases will be instantiated based on the phase definition.
Returns
an initialized Interface object.
Definition at line 57 of file Interface.cpp.
References Cantera::newSolution().
newSolution() [1/3]
shared_ptr< Solution > newSolution (const std::string & infile, const std::string & name, const std::string & transport, const std::vector< std::string > & adjacent)
Create and initialize a new Solution from an input file.
This constructor wraps newThermo(), newKinetics() and newTransport() routines for initialization.
Parameters
infile name of the input file
name name of the phase in the file. If this is blank, the first phase in the file is used.
transport name of the transport model. If blank, the transport model specified in the phase definition is used.
adjacent vector containing names of adjacent phases that participate in this phases kinetics. If empty, adjacent phases will be instantiated based on the phase definition.
Returns
an initialized Solution object.
Definition at line 203 of file Solution.cpp.
References AnyMap::fromYamlFile(), and Cantera::newSolution().
newSolution() [2/3]
shared_ptr< Solution > newSolution (const std::string & infile, const std::string & name = "", const std::string & transport = "", const std::vector< shared_ptr< Solution > > & adjacent = {})
Create and initialize a new Solution manager from an input file.
This constructor wraps newThermo(), newKinetics() and newTransport() routines for initialization.
Parameters
infile name of the input file
name name of the phase in the file. If this is blank, the first phase in the file is used.
transport name of the transport model.
adjacent vector containing adjacent Solution objects. If empty, adjacent phases will be instantiated based on the phase definition.
Returns
an initialized Solution object.
Definition at line 178 of file Solution.cpp.
References Cantera::dot(), AnyMap::fromYamlFile(), Cantera::newSolution(), Cantera::npos, and Cantera::toLowerCopy().
Referenced by Cantera::newInterface(), and Cantera::newSolution().
newSolution() [3/3]
shared_ptr< Solution > newSolution (const AnyMap & phaseNode, const AnyMap & rootNode = AnyMap(), const std::string & transport = "", const std::vector< shared_ptr< Solution > > & adjacent = {}, const std::map< std::string, shared_ptr< Solution > > & related = {})
Create and initialize a new Solution manager from AnyMap objects.
This constructor wraps newThermo(), newKinetics() and newTransport() routines for initialization.
Parameters
phaseNode the node containing the phase definition (that is, thermo model, list of species, and initial state)
rootNode the root node of the tree containing the phase definition, which will be used as the default location from which to read species definitions.
transport name of the transport model.
adjacent vector containing adjacent Solution objects. If empty, adjacent phases will be instantiated based on the phase definition.
related vector of phases related to the same root Solution object. Used internally by newSolution() when creating complex interfaces where a phase may be adjacent to multiple other phases but should be instantiated only once.
Returns
an initialized Solution object.
Definition at line 218 of file Solution.cpp.
References Interface::create(), Solution::create(), AnyMap::fromYamlFile(), AnyValue::getMapWhere(), AnyMap::getString(), AnyMap::hasKey(), Cantera::newKinetics(), Cantera::newSolution(), and Cantera::newThermo().