Cantera: PDSS_Molar Class Reference
PDSS_Molar Class Reference
Base class for PDSS classes which compute molar properties directly.
#include <PDSS.h>
Public Member Functions
virtual doublereal enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual doublereal entropy_R () const
Return the standard state entropy divided by RT.
virtual doublereal gibbs_RT () const
Return the molar Gibbs free energy divided by RT.
virtual doublereal cp_R () const
Return the molar const pressure heat capacity divided by RT.
Public Member Functions inherited from PDSS
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual doublereal temperature () const
Return the current stored temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal T)
saturation pressure
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
PDSS ()=default
Default Constructor.
PDSS (const PDSS &b)=delete
PDSS & operator= (const PDSS &b)=delete
virtual ~PDSS ()=default
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal gibbs_mole () const
Return the molar Gibbs free energy in units of J kmol-1.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
virtual doublereal molarVolume () const
Return the molar volume at standard state.
virtual doublereal density () const
Return the standard state density at standard state.
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state Gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal gibbs_RT_ref () const
Return the molar Gibbs free energy divided by RT at reference pressure.
virtual doublereal enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual doublereal entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual doublereal cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual doublereal molarVolume_ref () const
Return the molar volume at reference pressure.
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setReferenceThermo (shared_ptr< SpeciesThermoInterpType > stit)
Set the SpeciesThermoInterpType object used to calculate reference state properties.
virtual void setParent (VPStandardStateTP *phase, size_t k)
Set the parent VPStandardStateTP object of this PDSS object.
virtual void initThermo ()
Initialization routine.
void setParameters (const AnyMap &node)
Set model parameters from an AnyMap phase description, for example from the equation-of-state field of a species definition.
virtual void getParameters (AnyMap &eosNode) const
Store the parameters needed to reconstruct a copy of this PDSS object.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
Additional Inherited Members
Protected Attributes inherited from PDSS
double m_temp = -1.0
Current temperature used by the PDSS object.
double m_pres = -1.0
State of the system - pressure.
double m_p0 = -1.0
Reference state pressure of the species.
double m_minTemp = -1.0
Minimum temperature.
double m_maxTemp = 10000.0
Maximum temperature.
double m_mw = 0.0
Molecular Weight of the species.
AnyMap m_input
Input data supplied via setParameters.
shared_ptr< SpeciesThermoInterpType > m_spthermo
Pointer to the species thermodynamic property manager.
Detailed Description
Base class for PDSS classes which compute molar properties directly.
Definition at line 476 of file PDSS.h.
Member Function Documentation
enthalpy_RT()
doublereal enthalpy_RT () const virtual
Return the standard state molar enthalpy divided by RT.
Returns
The dimensionless species standard state enthalpy divided at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 208 of file PDSS.cpp.
References PDSS::enthalpy_mole(), Cantera::GasConstant, and PDSS::temperature().
Referenced by PDSS_HKFT::enthalpy_RT_ref(), and PDSS_HKFT::intEnergy_mole().
entropy_R()
doublereal entropy_R () const virtual
Return the standard state entropy divided by RT.
Returns
The species standard state entropy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 213 of file PDSS.cpp.
References PDSS::entropy_mole(), and Cantera::GasConstant.
Referenced by PDSS_HKFT::entropy_R_ref().
gibbs_RT()
doublereal gibbs_RT () const virtual
Return the molar Gibbs free energy divided by RT.
Returns
The species standard state Gibbs free energy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 218 of file PDSS.cpp.
References Cantera::GasConstant, PDSS::gibbs_mole(), and PDSS::temperature().
Referenced by PDSS_HKFT::gibbs_RT_ref().
cp_R()
doublereal cp_R () const virtual
Return the molar const pressure heat capacity divided by RT.
Returns
The species standard state Cp divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 223 of file PDSS.cpp.
References PDSS::cp_mole(), and Cantera::GasConstant.
Referenced by PDSS_HKFT::cp_R_ref().
The documentation for this class was generated from the following files:
PDSS.h
PDSS.cpp