Cantera: ExtensionManagerFactory Class Reference
ExtensionManagerFactory Class Reference
A factory class for creating ExtensionManager objects.
#include <ExtensionManagerFactory.h>
Public Member Functions
virtual void deleteFactory ()
Delete the static instance of this factory.
Public Member Functions inherited from Factory< ExtensionManager >
ExtensionManager * create (const std::string &name, Args... args)
Create an object using the object construction function corresponding to "name" and the provided constructor arguments.
void reg (const std::string &name, std::function< ExtensionManager *(Args...)> f)
Register a new object construction function.
void addAlias (const std::string &original, const std::string &alias)
Add an alias for an existing registered type.
std::string canonicalize (const std::string &name)
Get the canonical name registered for a type.
bool exists (const std::string &name) const
Returns true if name is registered with this factory.
Public Member Functions inherited from FactoryBase
virtual ~FactoryBase ()
destructor
Static Public Member Functions
static shared_ptr< ExtensionManager > build (const std::string &extensionType)
Create a new ExtensionManager.
static ExtensionManagerFactory & factory ()
Static function that returns the static instance of the factory, creating it if necessary.
Static Public Member Functions inherited from FactoryBase
static void deleteFactories ()
static function that deletes all factories in the internal registry maintained in a static variable
Private Member Functions
ExtensionManagerFactory ()=default
Private constructor prevents direct usage.
Static Private Attributes
static ExtensionManagerFactory * s_factory = 0
static member of the single factory instance
static std::mutex s_mutex
Decl for locking mutex for thermo factory singleton.
Additional Inherited Members
Protected Member Functions inherited from Factory< ExtensionManager >
void addDeprecatedAlias (const std::string &original, const std::string &alias)
Add a deprecated alias for an existing registered type.
Protected Member Functions inherited from FactoryBase
FactoryBase ()
Constructor.
virtual void deleteFactory ()=0
Virtual abstract function that deletes the factory.
Detailed Description
A factory class for creating ExtensionManager objects.
Since
New in Cantera 3.0
Definition at line 18 of file ExtensionManagerFactory.h.
Constructor & Destructor Documentation
ExtensionManagerFactory()
ExtensionManagerFactory () private default
Private constructor prevents direct usage.
Referenced by ExtensionManagerFactory::factory().
Member Function Documentation
build()
static shared_ptr< ExtensionManager > build (const std::string & extensionType) inline static
Create a new ExtensionManager.
Definition at line 22 of file ExtensionManagerFactory.h.
References Factory< ExtensionManager >::create(), and ExtensionManagerFactory::factory().
Referenced by Application::loadExtension().
deleteFactory()
void deleteFactory () virtual
Delete the static instance of this factory.
Implements FactoryBase.
Definition at line 25 of file ExtensionManagerFactory.cpp.
References ExtensionManagerFactory::s_factory, and ExtensionManagerFactory::s_mutex.
factory()
ExtensionManagerFactory & factory () static
Static function that returns the static instance of the factory, creating it if necessary.
Definition at line 16 of file ExtensionManagerFactory.cpp.
References ExtensionManagerFactory::ExtensionManagerFactory(), ExtensionManagerFactory::s_factory, and ExtensionManagerFactory::s_mutex.
Referenced by ExtensionManagerFactory::build(), and Application::loadExtension().
Member Data Documentation
s_factory
ExtensionManagerFactory * s_factory = 0 static private
static member of the single factory instance
Definition at line 35 of file ExtensionManagerFactory.h.
Referenced by ExtensionManagerFactory::deleteFactory(), and ExtensionManagerFactory::factory().
s_mutex
mutex s_mutex static private
Decl for locking mutex for thermo factory singleton.
Definition at line 41 of file ExtensionManagerFactory.h.
Referenced by ExtensionManagerFactory::deleteFactory(), and ExtensionManagerFactory::factory().
The documentation for this class was generated from the following files:
ExtensionManagerFactory.h
ExtensionManagerFactory.cpp