Cantera: Math1FactoryB Class Reference
Math1FactoryB Class Reference
Factory class to create Func1 compound objects - version B.
#include <Func1Factory.h>
Public Member Functions
virtual void deleteFactory ()
Virtual abstract function that deletes the factory.
Public Member Functions inherited from Factory< Func1, const shared_ptr< Func1 >, double >
Func1 * create (const std::string &name, Args... args)
Create an object using the object construction function corresponding to "name" and the provided constructor arguments.
void reg (const std::string &name, std::function< Func1 *(Args...)> f)
Register a new object construction function.
void addAlias (const std::string &original, const std::string &alias)
Add an alias for an existing registered type.
std::string canonicalize (const std::string &name)
Get the canonical name registered for a type.
bool exists (const std::string &name) const
Returns true if name is registered with this factory.
Public Member Functions inherited from FactoryBase
virtual ~FactoryBase ()
destructor
Static Public Member Functions
static Math1FactoryB * factory ()
Return a pointer to the factory.
Static Public Member Functions inherited from FactoryBase
static void deleteFactories ()
static function that deletes all factories in the internal registry maintained in a static variable
Private Member Functions
Math1FactoryB ()
default constructor, which is defined as private
Static Private Attributes
static Math1FactoryB * s_factory = 0
Pointer to the single instance of the factory.
static std::mutex s_mutex
Mutex for use when calling the factory.
Additional Inherited Members
Protected Member Functions inherited from Factory< Func1, const shared_ptr< Func1 >, double >
void addDeprecatedAlias (const std::string &original, const std::string &alias)
Add a deprecated alias for an existing registered type.
Protected Member Functions inherited from FactoryBase
FactoryBase ()
Constructor.
virtual void deleteFactory ()=0
Virtual abstract function that deletes the factory.
Detailed Description
Factory class to create Func1 compound objects - version B.
This class is mainly used via the newFunc1(const string&, const shared_ptr<Func1>, double) function, for example:
shared_ptr<Func1> d1 = newFunc1("plus-constant", f, 1.);
Since
New in Cantera 3.0
Definition at line 90 of file Func1Factory.h.
Constructor & Destructor Documentation
Math1FactoryB()
Math1FactoryB () private
default constructor, which is defined as private
Definition at line 116 of file Func1Factory.cpp.
References Factory< Func1, const shared_ptr< Func1 >, double >::reg().
Referenced by Math1FactoryB::factory().
Member Function Documentation
factory()
Math1FactoryB * factory () static
Return a pointer to the factory.
On the first call, a new instance is created. Since there is no need to instantiate more than one factory, on all subsequent calls, a pointer to the existing factory is returned.
Definition at line 129 of file Func1Factory.cpp.
References Math1FactoryB::Math1FactoryB(), Math1FactoryB::s_factory, and Math1FactoryB::s_mutex.
Referenced by Cantera::newFunc1().
deleteFactory()
void deleteFactory () virtual
Virtual abstract function that deletes the factory.
This must be properly defined in child objects.
Implements FactoryBase.
Definition at line 138 of file Func1Factory.cpp.
References Math1FactoryB::s_factory, and Math1FactoryB::s_mutex.
Member Data Documentation
s_factory
Math1FactoryB * s_factory = 0 static private
Pointer to the single instance of the factory.
Definition at line 104 of file Func1Factory.h.
Referenced by Math1FactoryB::deleteFactory(), and Math1FactoryB::factory().
s_mutex
std::mutex s_mutex static private
Mutex for use when calling the factory.
Definition at line 110 of file Func1Factory.h.
Referenced by Math1FactoryB::deleteFactory(), and Math1FactoryB::factory().
The documentation for this class was generated from the following files:
Func1Factory.h
Func1Factory.cpp