Cantera: Transport Class Reference
Transport Class Reference
Models of Phases of Matter » Transport Properties for Species in Phases
Base class for transport property managers.
#include <Transport.h>
Public Member Functions
Transport (ThermoPhase *thermo=0, size_t ndim=npos)
Constructor.
Transport (const Transport &)=delete
Transport & operator= (const Transport &)=delete
virtual std::string transportModel () const
Identifies the model represented by this Transport object.
std::string transportType () const
Identifies the Transport object type.
ThermoPhase & thermo ()
bool ready ()
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
virtual double getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const double *grad_T, int ldx, const double *grad_X, int ldf, const double *grad_V, double *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxes (size_t ndim, const double *const grad_T, size_t ldx, const double *const grad_X, size_t ldf, double *const fluxes)
Get the species diffusive mass fluxes wrt to the specified solution averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesFluxesES (size_t ndim, const double *grad_T, size_t ldx, const double *grad_X, size_t ldf, const double *grad_Phi, double *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const double *grad_T, int ldx, const double *grad_X, int ldf, double *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const double *grad_T, int ldx, const double *grad_X, int ldf, const double *grad_Phi, double *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void getMolarFluxes (const double *const state1, const double *const state2, const double delta, double *const cfluxes)
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
virtual void getMassFluxes (const double *state1, const double *state2, double delta, double *mfluxes)
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
virtual void getThermalDiffCoeffs (double *const dt)
Return a vector of Thermal diffusion coefficients [kg/m/sec].
virtual void getBinaryDiffCoeffs (const size_t ld, double *const d)
Returns the matrix of binary diffusion coefficients [m^2/s].
virtual void getMultiDiffCoeffs (const size_t ld, double *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void getMixDiffCoeffs (double *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMole (double *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMass (double *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getViscosityPolynomial (size_t i, double *coeffs) const
Return the polynomial fits to the viscosity of species i.
virtual void getConductivityPolynomial (size_t i, double *coeffs) const
Return the temperature fits of the heat conductivity of species i.
virtual void getBinDiffusivityPolynomial (size_t i, size_t j, double *coeffs) const
Return the polynomial fits to the binary diffusivity of species pair (i, j)
virtual void getCollisionIntegralPolynomial (size_t i, size_t j, double *astar_coeffs, double *bstar_coeffs, double *cstar_coeffs) const
Return the polynomial fits to the collision integral of species pair (i, j)
virtual void setViscosityPolynomial (size_t i, double *coeffs)
Modify the polynomial fits to the viscosity of species i.
virtual void setConductivityPolynomial (size_t i, double *coeffs)
Modify the temperature fits of the heat conductivity of species i.
virtual void setBinDiffusivityPolynomial (size_t i, size_t j, double *coeffs)
Modify the polynomial fits to the binary diffusivity of species pair (i, j)
virtual void setCollisionIntegralPolynomial (size_t i, size_t j, double *astar_coeffs, double *bstar_coeffs, double *cstar_coeffs, bool flag)
Modify the polynomial fits to the collision integral of species pair (i, j)
virtual void setParameters (const int type, const int k, const double *const p)
Set model parameters for derived classes.
AnyMap parameters () const
Return the parameters for a phase definition which are needed to reconstruct an identical object using the newTransport function.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
Transport Properties
virtual double viscosity ()
virtual void getSpeciesViscosities (double *const visc)
Returns the pure species viscosities.
virtual double bulkViscosity ()
The bulk viscosity in Pa-s.
virtual double ionConductivity ()
The ionic conductivity in 1/ohm/m.
virtual void getSpeciesIonConductivity (double *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual double thermalConductivity ()
Returns the mixture thermal conductivity in W/m/K.
virtual double electricalConductivity ()
The electrical conductivity (Siemens/m).
virtual void getMobilities (double *const mobil_e)
Get the Electrical mobilities (m^2/V/s).
virtual void getFluidMobilities (double *const mobil_f)
Get the fluid mobilities (s kmol/kg).
Protected Attributes
ThermoPhase * m_thermo
pointer to the object representing the phase
bool m_ready = false
true if finalize has been called
size_t m_nsp = 0
Number of species.
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis = VB_MASSAVG
Velocity basis from which diffusion velocities are computed.
std::weak_ptr< Solution > m_root
reference to Solution
Transport manager construction
These methods are used during construction.
virtual void init (ThermoPhase *thermo, int mode=0, int log_level=0)
Initialize a transport manager.
virtual void setThermo (ThermoPhase &thermo)
Specifies the ThermoPhase object.
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
virtual bool CKMode () const
Boolean indicating the form of the transport properties polynomial fits.
void finalize ()
Enable the transport object for use.
Detailed Description
Base class for transport property managers.
All classes that compute transport properties for a single phase derive from this class. Class Transport is meant to be used as a base class only. It is possible to instantiate it, but its methods throw exceptions if called.
Relationship of the Transport class to the ThermoPhase Class
This section describes how calculations are carried out within the Transport class. The Transport class and derived classes of the the Transport class necessarily use the ThermoPhase class to obtain the list of species and the thermodynamic state of the phase.
No state information is stored within Transport classes. Queries to the underlying ThermoPhase object must be made to obtain the state of the system.
An exception to this however is the state information concerning the the gradients of variables. This information is not stored within the ThermoPhase objects. It may be collected within the Transport objects. In fact, the meaning of const operations within the Transport class refers to calculations which do not change the state of the system nor the state of the first order gradients of the system.
When a const operation is evoked within the Transport class, it is also implicitly assumed that the underlying state within the ThermoPhase object has not changed its values.
Diffusion Fluxes and their Relationship to Reference Velocities
The diffusion fluxes must be referenced to a particular reference fluid velocity. Most typical is to reference the diffusion fluxes to the mass averaged velocity, but referencing to the mole averaged velocity is suitable for some liquid flows, and referencing to a single species is suitable for solid phase transport within a lattice. Currently, the identity of the reference velocity is coded into each transport object as a typedef named VelocityBasis, which is equated to an integer. Negative values of this variable refer to mass or mole-averaged velocities. Zero or positive quantities refers to the reference velocity being referenced to a particular species. Below are the predefined constants for its value.
VB_MASSAVG Diffusion velocities are based on the mass averaged velocity
VB_MOLEAVG Diffusion velocities are based on the mole averaged velocities
VB_SPECIES_0 Diffusion velocities are based on the relative motion wrt species 0
...
VB_SPECIES_3 Diffusion velocities are based on the relative motion wrt species 3
All transport managers specify a default reference velocity in their default constructors. All gas phase transport managers by default specify the mass- averaged velocity as their reference velocities.
Todo:
Provide a general mechanism to store the gradients of state variables within the system.
Definition at line 146 of file Transport.h.
Constructor & Destructor Documentation
Transport()
Transport (ThermoPhase * thermo = 0, size_t ndim = npos)
Constructor.
New transport managers should be created using TransportFactory, not by calling the constructor directly.
Parameters
thermo Pointer to the ThermoPhase class representing this phase.
ndim Dimension of the flux vector used in the calculation.
Deprecated:
The thermo and ndim parameters will be removed after Cantera 3.0. The ThermoPhase object should be specifed when calling the init method.
See also
TransportFactory
Definition at line 15 of file Transport.cpp.
References Transport::m_nDim, Cantera::npos, Transport::thermo(), and Cantera::warn_deprecated().
~Transport()
virtual ~Transport () inline virtual
Definition at line 164 of file Transport.h.
Member Function Documentation
transportModel()
virtual std::string transportModel () const inline virtual
Identifies the model represented by this Transport object.
Each derived class should override this method to return a meaningful identifier.
Since
New in Cantera 3.0. The name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented in DustyGasTransport, HighPressureGasTransport, IonGasTransport, MixTransport, MultiTransport, UnityLewisTransport, and WaterTransport.
Definition at line 174 of file Transport.h.
Referenced by Transport::bulkViscosity(), Transport::CKMode(), Transport::electricalConductivity(), Transport::getBinaryDiffCoeffs(), Transport::getBinDiffusivityPolynomial(), Transport::getCollisionIntegralPolynomial(), Transport::getConductivityPolynomial(), Transport::getElectricConduct(), Transport::getElectricCurrent(), Transport::getFluidMobilities(), Transport::getMassFluxes(), StFlow::getMeta(), Transport::getMixDiffCoeffs(), Transport::getMixDiffCoeffsMass(), Transport::getMixDiffCoeffsMole(), Transport::getMobilities(), Transport::getMolarFluxes(), Transport::getMultiDiffCoeffs(), Transport::getSpeciesFluxes(), Transport::getSpeciesIonConductivity(), Transport::getSpeciesMobilityRatio(), Transport::getSpeciesVdiff(), Transport::getSpeciesViscosities(), Transport::getThermalDiffCoeffs(), Transport::getViscosityPolynomial(), Transport::ionConductivity(), IonFlow::IonFlow(), Transport::mobilityRatio(), Transport::parameters(), Transport::setBinDiffusivityPolynomial(), Transport::setCollisionIntegralPolynomial(), Transport::setConductivityPolynomial(), Transport::setParameters(), StFlow::setTransport(), Transport::setViscosityPolynomial(), StFlow::StFlow(), Transport::thermalConductivity(), StFlow::transportModel(), Transport::transportType(), and Transport::viscosity().
transportType()
std::string transportType () const inline
Identifies the Transport object type.
Each derived class should override this method to return a meaningful identifier.
Deprecated:
To be removed after Cantera 3.0. Replaced by transportModel
Definition at line 181 of file Transport.h.
References Transport::transportModel(), and Cantera::warn_deprecated().
thermo()
ThermoPhase & thermo () inline
Phase object. Every transport manager is designed to compute properties for a specific phase of a mixture, which might be a liquid solution, a gas mixture, a surface, etc. This method returns a reference to the object representing the phase itself.
Definition at line 193 of file Transport.h.
References Transport::m_thermo.
Referenced by IonGasTransport::init(), MixTransport::init(), MultiTransport::init(), WaterTransport::init(), DustyGasTransport::setThermo(), Transport::setThermo(), Transport::Transport(), and WaterTransport::WaterTransport().
ready()
bool ready ()
Returns true if the transport manager is ready for use.
Deprecated:
To be removed after Cantera 3.0.
Definition at line 32 of file Transport.cpp.
References Transport::m_ready, and Cantera::warn_deprecated().
Referenced by Transport::finalize(), and Transport::setThermo().
setNDim()
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
Parameters
ndim Number of dimensions in flux expressions
Deprecated:
Unused. To be removed after Cantera 3.0.
Definition at line 38 of file Transport.cpp.
References Transport::m_nDim, and Cantera::warn_deprecated().
nDim()
size_t nDim () const inline
Return the number of dimensions in flux expressions.
Deprecated:
Unused. To be removed after Cantera 3.0.
Definition at line 212 of file Transport.h.
References Transport::m_nDim.
checkSpeciesIndex()
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
Throws an exception if k is greater than nSpecies()
Definition at line 44 of file Transport.cpp.
References Transport::m_nsp.
checkSpeciesArraySize()
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
Throws an exception if kk is less than nSpecies(). Used before calls which take an array pointer.
Definition at line 51 of file Transport.cpp.
References Transport::m_nsp.
viscosity()
virtual double viscosity () inline virtual
The viscosity in Pa-s.
Reimplemented in GasTransport, HighPressureGasTransport, IonGasTransport, and WaterTransport.
Definition at line 231 of file Transport.h.
References Transport::transportModel().
Referenced by StFlow::updateTransport().
getSpeciesViscosities()
virtual void getSpeciesViscosities (double *const visc) inline virtual
Returns the pure species viscosities.
The units are Pa-s and the length is the number of species
Parameters
visc Vector of viscosities
Reimplemented in GasTransport.
Definition at line 242 of file Transport.h.
References Transport::transportModel().
bulkViscosity()
virtual double bulkViscosity () inline virtual
The bulk viscosity in Pa-s.
The bulk viscosity is only non-zero in rare cases. Most transport managers either overload this method to return zero, or do not implement it, in which case an exception is thrown if called.
Reimplemented in WaterTransport.
Definition at line 253 of file Transport.h.
References Transport::transportModel().
ionConductivity()
virtual double ionConductivity () inline virtual
The ionic conductivity in 1/ohm/m.
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 260 of file Transport.h.
References Transport::transportModel().
getSpeciesIonConductivity()
virtual void getSpeciesIonConductivity (double *const ionCond) inline virtual
Returns the pure species ionic conductivity.
The units are 1/ohm/m and the length is the number of species
Parameters
ionCond Vector of ionic conductivities
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 273 of file Transport.h.
References Transport::transportModel().
mobilityRatio()
virtual void mobilityRatio (double * mobRat) inline virtual
Returns the pointer to the mobility ratios of the species in the phase.
Parameters
mobRat Returns a matrix of mobility ratios for the current problem. The mobility ratio mobRat(i,j) is defined as the ratio of the mobility of species i to species j.
mobRat(i,j) = mu_i / mu_j
It is returned in fortran-ordering format. That is, it is returned as mobRat[k], where
   k = j * nsp + i
The size of mobRat must be at least equal to nsp*nsp
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 295 of file Transport.h.
References Transport::transportModel().
getSpeciesMobilityRatio()
virtual void getSpeciesMobilityRatio (double ** mobRat) inline virtual
Returns the pure species limit of the mobility ratios.
The value is dimensionless and the length is the number of species
Parameters
mobRat Vector of mobility ratios
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 308 of file Transport.h.
References Transport::transportModel().
thermalConductivity()
virtual double thermalConductivity () inline virtual
Returns the mixture thermal conductivity in W/m/K.
Units are in W / m K or equivalently kg m / s3 K
Returns
thermal conductivity in W/m/K.
Reimplemented in HighPressureGasTransport, IonGasTransport, MixTransport, MultiTransport, and WaterTransport.
Definition at line 319 of file Transport.h.
References Transport::transportModel().
Referenced by StFlow::updateTransport().
electricalConductivity()
virtual double electricalConductivity () inline virtual
The electrical conductivity (Siemens/m).
Reimplemented in IonGasTransport.
Definition at line 325 of file Transport.h.
References Transport::transportModel().
getMobilities()
virtual void getMobilities (double *const mobil_e) inline virtual
Get the Electrical mobilities (m^2/V/s).
This function returns the mobilities. In some formulations this is equal to the normal mobility multiplied by Faraday's constant.
Frequently, but not always, the mobility is calculated from the diffusion coefficient using the Einstein relation
\[ \mu^e_k = \frac{F D_k}{R T} \]
Parameters
mobil_e Returns the mobilities of the species in array mobil_e. The array must be dimensioned at least as large as the number of species.
Reimplemented in IonGasTransport, and MixTransport.
Definition at line 346 of file Transport.h.
References Transport::transportModel().
Referenced by IonFlow::updateTransport().
getFluidMobilities()
virtual void getFluidMobilities (double *const mobil_f) inline virtual
Get the fluid mobilities (s kmol/kg).
This function returns the fluid mobilities. Usually, you have to multiply Faraday's constant into the resulting expression to general a species flux expression.
Frequently, but not always, the mobility is calculated from the diffusion coefficient using the Einstein relation
\[ \mu^f_k = \frac{D_k}{R T} \]
Parameters
mobil_f Returns the mobilities of the species in array mobil. The array must be dimensioned at least as large as the number of species.
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 370 of file Transport.h.
References Transport::transportModel().
getElectricConduct()
virtual double getElectricConduct () inline virtual
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
The electrical conductivity, \(\sigma \), relates the electric current density, J, to the electric field, E.
\[ \vec{J} = \sigma \vec{E} \]
We assume here that the mixture electrical conductivity is an isotropic quantity, at this stage. Tensors may be included at a later time.
The conductivity is the reciprocal of the resistivity.
The units are Siemens m-1, where 1 S = 1 A / volt = 1 s^3 A^2 /kg /m^2
Deprecated:
To be removed after Cantera 3.0. Replaced by electricalConductivity()
Definition at line 396 of file Transport.h.
References Transport::transportModel().
getElectricCurrent()
virtual void getElectricCurrent (int ndim, const double * grad_T, int ldx, const double * grad_X, int ldf, const double * grad_V, double * current) inline virtual
Compute the electric current density in A/m^2.
Calculates the electric current density as a vector, given the gradients of the field variables.
Parameters
ndim The number of spatial dimensions (1, 2, or 3).
grad_T The temperature gradient (ignored in this model).
ldx Leading dimension of the grad_X array.
grad_X The gradient of the mole fraction
ldf Leading dimension of the grad_V and current vectors.
grad_V The electrostatic potential gradient.
current The electric current in A/m^2. This is a vector of length ndim
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 416 of file Transport.h.
References Transport::transportModel().
getSpeciesFluxes()
virtual void getSpeciesFluxes (size_t ndim, const double *const grad_T, size_t ldx, const double *const grad_X, size_t ldf, double *const fluxes) inline virtual
Get the species diffusive mass fluxes wrt to the specified solution averaged velocity, given the gradients in mole fraction and temperature.
Units for the returned fluxes are kg m-2 s-1.
Usually the specified solution average velocity is the mass averaged velocity. This is changed in some subclasses, however.
Parameters
ndim Number of dimensions in the flux expressions
grad_T Gradient of the temperature (length = ndim)
ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
grad_X Gradients of the mole fraction Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
fluxes Output of the diffusive mass fluxes. Flat vector with the m_nsp in the inner loop. length = ldx * ndim
Reimplemented in MixTransport, and MultiTransport.
Definition at line 446 of file Transport.h.
References Transport::transportModel().
Referenced by Transport::getSpeciesFluxesES().
getSpeciesFluxesES()
virtual void getSpeciesFluxesES (size_t ndim, const double * grad_T, size_t ldx, const double * grad_X, size_t ldf, const double * grad_Phi, double * fluxes) inline virtual
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
Units for the returned fluxes are kg m-2 s-1.
Parameters
[in] ndim Number of dimensions in the flux expressions
[in] grad_T Gradient of the temperature. (length = ndim)
[in] ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
[in] grad_X Gradients of the mole fraction. Flat vector with the m_nsp in the inner loop. length = ldx * ndim.
[in] ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always).
[in] grad_Phi Gradients of the electrostatic potential (length = ndim)
[out] fluxes The diffusive mass fluxes. Flat vector with the m_nsp in the inner loop. length = ldx * ndim.
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 473 of file Transport.h.
References Transport::getSpeciesFluxes().
getSpeciesVdiff()
virtual void getSpeciesVdiff (size_t ndim, const double * grad_T, int ldx, const double * grad_X, int ldf, double * Vdiff) inline virtual
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
Parameters
[in] ndim Number of dimensions in the flux expressions
[in] grad_T Gradient of the temperature (length = ndim)
[in] ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
[in] grad_X Gradients of the mole fraction. Flat vector with the m_nsp in the inner loop. length = ldx * ndim
[in] ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
[out] Vdiff Diffusive velocities wrt the mass- averaged velocity. Flat vector with the m_nsp in the inner loop. length = ldx * ndim. units are m / s.
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 500 of file Transport.h.
References Transport::transportModel().
Referenced by Transport::getSpeciesVdiffES().
getSpeciesVdiffES()
virtual void getSpeciesVdiffES (size_t ndim, const double * grad_T, int ldx, const double * grad_X, int ldf, const double * grad_Phi, double * Vdiff) inline virtual
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
Parameters
[in] ndim Number of dimensions in the flux expressions
[in] grad_T Gradient of the temperature (length = ndim)
[in] ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
[in] grad_X Gradients of the mole fraction. Flat vector with the m_nsp in the inner loop. length = ldx * ndim.
[in] ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
[in] grad_Phi Gradients of the electrostatic potential (length = ndim)
[out] Vdiff Diffusive velocities wrt the mass-averaged velocity. Flat vector with the m_nsp in the inner loop. length = ldx
ndim. units are m / s.
Deprecated:
To be removed after Cantera 3.0. Not implemented by any model.
Definition at line 530 of file Transport.h.
References Transport::getSpeciesVdiff().
getMolarFluxes()
virtual void getMolarFluxes (const double *const state1, const double *const state2, const double delta, double *const cfluxes) inline virtual
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
Parameters
[in] state1 Array of temperature, density, and mass fractions for state 1.
[in] state2 Array of temperature, density, and mass fractions for state 2.
[in] delta Distance from state 1 to state 2 (m).
[out] cfluxes Output array containing the diffusive molar fluxes of species from state1 to state2. This is a flat vector with m_nsp in the inner loop. length = ldx * ndim. Units are [kmol/m^2/s].
Reimplemented in DustyGasTransport, and MultiTransport.
Definition at line 553 of file Transport.h.
References Transport::transportModel().
getMassFluxes()
virtual void getMassFluxes (const double * state1, const double * state2, double delta, double * mfluxes) inline virtual
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
Parameters
[in] state1 Array of temperature, density, and mass fractions for state 1.
[in] state2 Array of temperature, density, and mass fractions for state 2.
[in] delta Distance from state 1 to state 2 (m).
[out] mfluxes Output array containing the diffusive mass fluxes of species from state1 to state2. This is a flat vector with m_nsp in the inner loop. length = ldx * ndim. Units are [kg/m^2/s].
Reimplemented in MultiTransport.
Definition at line 573 of file Transport.h.
References Transport::transportModel().
getThermalDiffCoeffs()
virtual void getThermalDiffCoeffs (double *const dt) inline virtual
Return a vector of Thermal diffusion coefficients [kg/m/sec].
The thermal diffusion coefficient \(D^T_k \) is defined so that the diffusive mass flux of species k induced by the local temperature gradient is given by the following formula:
\[ M_k J_k = -D^T_k \nabla \ln T. \]
The thermal diffusion coefficient can be either positive or negative.
Parameters
dt On return, dt will contain the species thermal diffusion coefficients. Dimension dt at least as large as the number of species. Units are kg/m/s.
Reimplemented in HighPressureGasTransport, MixTransport, and MultiTransport.
Definition at line 596 of file Transport.h.
References Transport::transportModel().
Referenced by StFlow::updateTransport().
getBinaryDiffCoeffs()
virtual void getBinaryDiffCoeffs (const size_t ld, double *const d) inline virtual
Returns the matrix of binary diffusion coefficients [m^2/s].
Parameters
[in] ld Inner stride for writing the two dimension diffusion coefficients into a one dimensional vector
[out] d Diffusion coefficient matrix (must be at least m_k * m_k in length.
Reimplemented in GasTransport, and HighPressureGasTransport.
Definition at line 608 of file Transport.h.
References Transport::transportModel().
getMultiDiffCoeffs()
virtual void getMultiDiffCoeffs (const size_t ld, double *const d) inline virtual
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
If the transport manager implements a multicomponent diffusion model, then this method returns the array of multicomponent diffusion coefficients. Otherwise it throws an exception.
Parameters
[in] ld The dimension of the inner loop of d (usually equal to m_nsp)
[out] d flat vector of diffusion coefficients, fortran ordering. d[ld*j+i] is the D_ij diffusion coefficient (the diffusion coefficient for species i due to concentration gradients in species j). Units: m^2/s
Reimplemented in DustyGasTransport, HighPressureGasTransport, and MultiTransport.
Definition at line 625 of file Transport.h.
References Transport::transportModel().
Referenced by StFlow::updateTransport().
getMixDiffCoeffs()
virtual void getMixDiffCoeffs (double *const d) inline virtual
Returns a vector of mixture averaged diffusion coefficients.
Mixture-averaged diffusion coefficients [m^2/s]. If the transport manager implements a mixture-averaged diffusion model, then this method returns the array of mixture-averaged diffusion coefficients. Otherwise it throws an exception.
Parameters
d Return vector of mixture averaged diffusion coefficients Units = m2/s. Length = n_sp
Reimplemented in IonGasTransport, UnityLewisTransport, and GasTransport.
Definition at line 640 of file Transport.h.
References Transport::transportModel().
Referenced by StFlow::updateTransport().
getMixDiffCoeffsMole()
virtual void getMixDiffCoeffsMole (double *const d) inline virtual
Returns a vector of mixture averaged diffusion coefficients.
Reimplemented in UnityLewisTransport, and GasTransport.
Definition at line 646 of file Transport.h.
References Transport::transportModel().
getMixDiffCoeffsMass()
virtual void getMixDiffCoeffsMass (double *const d) inline virtual
Returns a vector of mixture averaged diffusion coefficients.
Reimplemented in UnityLewisTransport, and GasTransport.
Definition at line 652 of file Transport.h.
References Transport::transportModel().
getViscosityPolynomial()
virtual void getViscosityPolynomial (size_t i, double * coeffs) const inline virtual
Return the polynomial fits to the viscosity of species i.
Reimplemented in GasTransport.
Definition at line 658 of file Transport.h.
References Transport::transportModel().
getConductivityPolynomial()
virtual void getConductivityPolynomial (size_t i, double * coeffs) const inline virtual
Return the temperature fits of the heat conductivity of species i.
Reimplemented in GasTransport.
Definition at line 664 of file Transport.h.
References Transport::transportModel().
getBinDiffusivityPolynomial()
virtual void getBinDiffusivityPolynomial (size_t i, size_t j, double * coeffs) const inline virtual
Return the polynomial fits to the binary diffusivity of species pair (i, j)
Reimplemented in GasTransport.
Definition at line 670 of file Transport.h.
References Transport::transportModel().
getCollisionIntegralPolynomial()
virtual void getCollisionIntegralPolynomial (size_t i, size_t j, double * astar_coeffs, double * bstar_coeffs, double * cstar_coeffs) const inline virtual
Return the polynomial fits to the collision integral of species pair (i, j)
Reimplemented in GasTransport.
Definition at line 676 of file Transport.h.
References Transport::transportModel().
setViscosityPolynomial()
virtual void setViscosityPolynomial (size_t i, double * coeffs) inline virtual
Modify the polynomial fits to the viscosity of species i.
Reimplemented in GasTransport.
Definition at line 685 of file Transport.h.
References Transport::transportModel().
setConductivityPolynomial()
virtual void setConductivityPolynomial (size_t i, double * coeffs) inline virtual
Modify the temperature fits of the heat conductivity of species i.
Reimplemented in GasTransport.
Definition at line 691 of file Transport.h.
References Transport::transportModel().
setBinDiffusivityPolynomial()
virtual void setBinDiffusivityPolynomial (size_t i, size_t j, double * coeffs) inline virtual
Modify the polynomial fits to the binary diffusivity of species pair (i, j)
Reimplemented in GasTransport.
Definition at line 697 of file Transport.h.
References Transport::transportModel().
setCollisionIntegralPolynomial()
virtual void setCollisionIntegralPolynomial (size_t i, size_t j, double * astar_coeffs, double * bstar_coeffs, double * cstar_coeffs, bool flag) inline virtual
Modify the polynomial fits to the collision integral of species pair (i, j)
Reimplemented in GasTransport.
Definition at line 703 of file Transport.h.
References Transport::transportModel().
setParameters()
virtual void setParameters (const int type, const int k, const double *const p) inline virtual
Set model parameters for derived classes.
This method may be derived in subclasses to set model-specific parameters. The primary use of this class is to set parameters while in the middle of a calculation without actually having to dynamically cast the base Transport pointer.
Parameters
type Specifies the type of parameters to set 0 : Diffusion coefficient 1 : Thermal Conductivity The rest are currently unused.
k Species index to set the parameters on
p Vector of parameters. The length of the vector varies with the parameterization
Deprecated:
To be removed after Cantera 3.0.
Definition at line 727 of file Transport.h.
References Transport::transportModel().
parameters()
AnyMap parameters () const
Return the parameters for a phase definition which are needed to reconstruct an identical object using the newTransport function.
This excludes the individual species transport properties, which are handled separately.
Definition at line 58 of file Transport.cpp.
References Factory< T, Args >::canonicalize(), TransportFactory::factory(), and Transport::transportModel().
setVelocityBasis()
void setVelocityBasis (VelocityBasis ivb) inline
Sets the velocity basis.
What the transport object does with this parameter is up to the individual operator. Currently, this is not functional for most transport operators including all of the gas-phase operators.
Parameters
ivb Species the velocity basis
Deprecated:
To be removed after Cantera 3.0.
Definition at line 747 of file Transport.h.
References Transport::m_velocityBasis.
getVelocityBasis()
VelocityBasis getVelocityBasis () const inline
Gets the velocity basis.
What the transport object does with this parameter is up to the individual operator. Currently, this is not functional for most transport operators including all of the gas-phase operators.
Returns
the velocity basis
Deprecated:
To be removed after Cantera 3.0.
Definition at line 760 of file Transport.h.
References Transport::m_velocityBasis.
init()
virtual void init (ThermoPhase * thermo, int mode = 0, int log_level = 0) inline virtual
Initialize a transport manager.
This routine sets up a transport manager. It calculates the collision integrals and populates species-dependent data structures.
Parameters
thermo Pointer to the ThermoPhase object
mode Chemkin compatible mode or not. This alters the specification of the collision integrals. defaults to no.
log_level Defaults to zero, no logging
Reimplemented in IonGasTransport, GasTransport, MixTransport, MultiTransport, and WaterTransport.
Definition at line 779 of file Transport.h.
Referenced by TransportFactory::newTransport().
setThermo()
void setThermo (ThermoPhase & thermo) virtual
Specifies the ThermoPhase object.
We have relaxed this operation so that it will succeed when the underlying old and new ThermoPhase objects have the same number of species and the same names of the species in the same order. The idea here is to allow copy constructors and duplicators to work. In order for them to work, we need a method to switch the internal pointer within the Transport object after the duplication takes place. Also, different thermodynamic instantiations of the same species should also work.
Parameters
thermo Reference to the ThermoPhase object that the transport object will use
Deprecated:
To be removed after Cantera 3.0. The ThermoPhase object should be set as part of the call to init.
Reimplemented in DustyGasTransport.
Definition at line 68 of file Transport.cpp.
References Transport::m_nsp, Transport::m_thermo, Phase::nSpecies(), Transport::ready(), Phase::speciesName(), Transport::thermo(), and Cantera::warn_deprecated().
Referenced by DustyGasTransport::setThermo().
setRoot()
void setRoot (std::shared_ptr< Solution > root) virtual
Set root Solution holding all phase information.
Deprecated:
Unused. To be removed after Cantera 3.0.
Definition at line 95 of file Transport.cpp.
References Transport::m_root, and Cantera::warn_deprecated().
CKMode()
virtual bool CKMode () const inline virtual
Boolean indicating the form of the transport properties polynomial fits.
Returns true if the Chemkin form is used.
Reimplemented in GasTransport.
Definition at line 804 of file Transport.h.
References Transport::transportModel().
finalize()
void finalize () protected
Enable the transport object for use.
Once finalize() has been called, the transport manager should be ready to compute any supported transport property, and no further modifications to the model parameters should be made.
Deprecated:
To be removed after Cantera 3.0.
Definition at line 101 of file Transport.cpp.
References Transport::m_ready, Transport::ready(), and Cantera::warn_deprecated().
Member Data Documentation
m_thermo
ThermoPhase* m_thermo protected
pointer to the object representing the phase
Definition at line 822 of file Transport.h.
Referenced by IonGasTransport::electricalConductivity(), IonGasTransport::fitDiffCoeffs(), HighPressureGasTransport::getBinaryDiffCoeffs(), MultiTransport::getMassFluxes(), IonGasTransport::getMixDiffCoeffs(), UnityLewisTransport::getMixDiffCoeffs(), UnityLewisTransport::getMixDiffCoeffsMass(), IonGasTransport::getMobilities(), DustyGasTransport::getMolarFluxes(), MultiTransport::getMolarFluxes(), HighPressureGasTransport::getMultiDiffCoeffs(), MultiTransport::getMultiDiffCoeffs(), MixTransport::getSpeciesFluxes(), MultiTransport::getSpeciesFluxes(), IonGasTransport::init(), WaterTransport::init(), DustyGasTransport::initialize(), Transport::setThermo(), HighPressureGasTransport::thermalConductivity(), WaterTransport::thermalConductivity(), Transport::thermo(), MixTransport::update_C(), MultiTransport::update_C(), MixTransport::update_T(), MultiTransport::update_T(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_C(), DustyGasTransport::updateTransport_T(), HighPressureGasTransport::viscosity(), and WaterTransport::viscosity().
m_ready
bool m_ready = false protected
true if finalize has been called
Deprecated:
To be removed after Cantera 3.0
Definition at line 826 of file Transport.h.
Referenced by Transport::finalize(), and Transport::ready().
m_nsp
size_t m_nsp = 0 protected
Number of species.
Definition at line 829 of file Transport.h.
Referenced by Transport::checkSpeciesArraySize(), Transport::checkSpeciesIndex(), IonGasTransport::electricalConductivity(), DustyGasTransport::eval_H_matrix(), MultiTransport::eval_L0000(), MultiTransport::eval_L0010(), MultiTransport::eval_L1000(), IonGasTransport::fitDiffCoeffs(), MultiTransport::getMassFluxes(), IonGasTransport::getMixDiffCoeffs(), UnityLewisTransport::getMixDiffCoeffs(), UnityLewisTransport::getMixDiffCoeffsMass(), IonGasTransport::getMobilities(), MixTransport::getMobilities(), DustyGasTransport::getMolarFluxes(), DustyGasTransport::getMultiDiffCoeffs(), HighPressureGasTransport::getMultiDiffCoeffs(), MultiTransport::getMultiDiffCoeffs(), MixTransport::getSpeciesFluxes(), MultiTransport::getSpeciesFluxes(), MixTransport::getThermalDiffCoeffs(), MultiTransport::getThermalDiffCoeffs(), IonGasTransport::init(), MixTransport::init(), MultiTransport::init(), DustyGasTransport::initialize(), Transport::setThermo(), IonGasTransport::setupN64(), HighPressureGasTransport::thermalConductivity(), MixTransport::thermalConductivity(), MultiTransport::thermalConductivity(), MixTransport::update_C(), MultiTransport::update_C(), MixTransport::update_T(), MultiTransport::update_T(), DustyGasTransport::updateBinaryDiffCoeffs(), MixTransport::updateCond_T(), DustyGasTransport::updateKnudsenDiffCoeffs(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_C(), and HighPressureGasTransport::viscosity().
m_nDim
size_t m_nDim protected
Number of dimensions used in flux expressions.
Deprecated:
To be removed after Cantera 3.0
Definition at line 833 of file Transport.h.
Referenced by Transport::nDim(), Transport::setNDim(), and Transport::Transport().
m_velocityBasis
int m_velocityBasis = VB_MASSAVG protected
Velocity basis from which diffusion velocities are computed.
Defaults to the mass averaged basis = -2
Deprecated:
To be removed after Cantera 3.0.
Definition at line 838 of file Transport.h.
Referenced by Transport::getVelocityBasis(), and Transport::setVelocityBasis().
m_root
std::weak_ptr<Solution> m_root protected
reference to Solution
Deprecated:
To be removed after Cantera 3.0
Definition at line 842 of file Transport.h.
Referenced by Transport::setRoot().
The documentation for this class was generated from the following files:
Transport.h
Transport.cpp