Cantera: WaterPropsIAPWS Class Reference
WaterPropsIAPWS Class Reference
Models of Phases of Matter » Thermodynamic Properties
Class for calculating the equation of state of water.
#include <WaterPropsIAPWS.h>
Public Member Functions
WaterPropsIAPWS ()=default
Base constructor.
WaterPropsIAPWS (const WaterPropsIAPWS &right)=delete
WaterPropsIAPWS & operator= (const WaterPropsIAPWS &right)=delete
void setState_TR (doublereal temperature, doublereal rho)
Set the internal state of the object wrt temperature and density.
void setState_TD (double temperature, double rho)
Set the internal state of the object wrt temperature and density.
double gibbs_mass () const
Get the Gibbs free energy (J/kg) at the current temperature and density.
double enthalpy_mass () const
Get the enthalpy (J/kg) at the current temperature and density.
double intEnergy_mass () const
Get the internal energy (J/kg) at the current temperature and density.
double entropy_mass () const
Get the entropy (J/kg/K) at the current temperature and density.
double cv_mass () const
Get the constant volume heat capacity (J/kg/K) at the current temperature and density.
double cp_mass () const
Get the constant pressure heat capacity (J/kg/K) at the current temperature and density.
doublereal helmholtzFE () const
Calculate the Helmholtz free energy in mks units of J kmol-1 K-1, using the last temperature and density.
doublereal Gibbs () const
Calculate the Gibbs free energy in mks units of J kmol-1 K-1.
doublereal enthalpy () const
Calculate the enthalpy in mks units of J kmol-1 using the last temperature and density.
doublereal intEnergy () const
Calculate the internal energy in mks units of J kmol-1.
doublereal entropy () const
Calculate the entropy in mks units of J kmol-1 K-1.
doublereal cv () const
Calculate the constant volume heat capacity in mks units of J kmol-1 K-1 at the last temperature and density.
doublereal cp () const
Calculate the constant pressure heat capacity in mks units of J kmol-1 K-1 at the last temperature and density.
doublereal molarVolume () const
Calculate the molar volume (kmol m-3) at the last temperature and density.
doublereal pressure () const
Calculates the pressure (Pascals), given the current value of the temperature and density.
doublereal density (doublereal temperature, doublereal pressure, int phase=-1, doublereal rhoguess=-1.0)
Calculates the density given the temperature and the pressure, and a guess at the density.
doublereal density_const (doublereal pressure, int phase=-1, doublereal rhoguess=-1.0) const
Calculates the density given the temperature and the pressure, and a guess at the density, while not changing the internal state.
doublereal density () const
Returns the density (kg m-3)
doublereal temperature () const
Returns the temperature (Kelvin)
doublereal coeffThermExp () const
Returns the coefficient of thermal expansion.
doublereal coeffPresExp () const
Returns the isochoric pressure derivative wrt temperature.
doublereal isothermalCompressibility () const
Returns the coefficient of isothermal compressibility for the state of the object.
doublereal dpdrho () const
Returns the value of dp / drho at constant T for the state of the object.
doublereal psat_est (doublereal temperature) const
This function returns an estimated value for the saturation pressure.
doublereal psat (doublereal temperature, int waterState=WATER_LIQUID)
This function returns the saturation pressure given the temperature as an input parameter, and sets the internal state to the saturated conditions.
doublereal densSpinodalWater () const
Return the value of the density at the water spinodal point (on the liquid side) for the current temperature.
doublereal densSpinodalSteam () const
Return the value of the density at the water spinodal point (on the gas side) for the current temperature.
int phaseState (bool checkState=false) const
Returns the Phase State flag for the current state of the object.
doublereal Tcrit () const
Returns the critical temperature of water (Kelvin)
doublereal Pcrit () const
Returns the critical pressure of water (22.064E6 Pa)
doublereal Rhocrit () const
Return the critical density of water (kg m-3)
Private Member Functions
void calcDim (doublereal temperature, doublereal rho)
Calculate the dimensionless temp and rho and store internally.
void corr (doublereal temperature, doublereal pressure, doublereal &densLiq, doublereal &densGas, doublereal &delGRT)
Utility routine in the calculation of the saturation pressure.
void corr1 (doublereal temperature, doublereal pressure, doublereal &densLiq, doublereal &densGas, doublereal &pcorr)
Utility routine in the calculation of the saturation pressure.
Private Attributes
WaterPropsIAPWSphi m_phi
pointer to the underlying object that does the calculations.
double tau = -1.0
Dimensionless temperature, tau = T_C / T.
double delta = -1.0
Dimensionless density, delta = rho / rho_c.
int iState = -30000
Current state of the system.
Detailed Description
Class for calculating the equation of state of water.
This is a helper class for WaterSSTP and PDSS_Water and does not constitute a complete implementation of a thermo phase by itself (see Thermodynamic Properties and classes WaterSSTP and PDSS_Water).
The reference is W. Wagner, A. Pruss, "The IAPWS Formulation 1995 for the Thermodynamic Properties of Ordinary Water Substance for General and Scientific Use," J. Phys. Chem. Ref. Dat, 31, 387, 2002.
This class provides a very complicated polynomial for the specific Helmholtz free energy of water, as a function of temperature and density.
\[ \frac{M\hat{f}(\rho,T)}{R T} = \phi(\delta, \tau) = \phi^o(\delta, \tau) + \phi^r(\delta, \tau) \]
where
\[ \delta = \rho / \rho_c \quad \mathrm{and} \quad \tau = T_c / T \]
The following constants are assumed
\[ T_c = 647.096\mathrm{\;K} \]
\[ \rho_c = 322 \mathrm{\;kg\,m^{-3}} \]
\[ R/M = 0.46151805 \mathrm{\;kJ\,kg^{-1}\,K^{-1}} \]
The free energy is a unique single-valued function of the temperature and density over its entire range.
Note, the base thermodynamic state for this class is the one used in the steam tables, such that the liquid at the triple point for water has the following properties:
u(273.16, rho) = 0.0
s(273.16, rho) = 0.0
psat(273.16) = 611.655 Pascal
rho(273.16, psat) = 999.793 kg m-3
Therefore, to use this class within Cantera, offsets to u() and s() must be used to put the water class onto the same basis as other thermodynamic quantities. For example, in the WaterSSTP class, these offsets are calculated in the following way. The thermodynamic base state for water is set to the NIST basis here by specifying constants EW_Offset and SW_Offset. These offsets are calculated on the fly so that the following properties hold:
Delta_Hfo_idealGas(298.15, 1bar) = -241.826 kJ/gmol
So_idealGas(298.15, 1bar) = 188.835 J/gmolK
The offsets are calculated by actually computing the above quantities and then calculating the correction factor.
This class provides an interface to the WaterPropsIAPWSphi class, which actually calculates the \(\phi^o(\delta, \tau) \) and the \(\phi^r(\delta, \tau) \) polynomials in dimensionless form.
All thermodynamic results from this class are returned in dimensional form. This is because the gas constant (and molecular weight) used within this class is allowed to be potentially different than that used elsewhere in Cantera. Therefore, everything has to be in dimensional units. Note, however, the thermodynamic basis is set to that used in the steam tables. (u = s = 0 for liquid water at the triple point).
This class is not a ThermoPhase. However, it does maintain an internal state of the object that is dependent on temperature and density. The internal state is characterized by an internally stored \(\tau\) and a \(\delta \) value, and an iState value, which indicates whether the point is a liquid, a gas, or a supercritical fluid. Along with that the \(\tau\) and a \(\delta \) values are polynomials of \(\tau\) and a \(\delta \) that are kept by the WaterPropsIAPWSphi class. Therefore, whenever \(\tau\) or \(\delta \) is changed, the function setState() must be called in order for the internal state to be kept up to date.
The class is pretty straightforward. However, one function deserves mention. The density() function calculates the density that is consistent with a particular value of the temperature and pressure. It may therefore be multivalued or potentially there may be no answer from this function. It therefore takes a phase guess and a density guess as optional parameters. If no guesses are supplied to density(), a gas phase guess is assumed. This may or may not be what is wanted. Therefore, density() should usually at least be supplied with a phase guess so that it may manufacture an appropriate density guess. density() manufactures the initial density guess, nondimensionalizes everything, and then calls WaterPropsIAPWSphi::dfind(), which does the iterative calculation to find the density condition that matches the desired input pressure.
The phase guess defines are located in the .h file. they are
WATER_GAS
WATER_LIQUID
WATER_SUPERCRIT
There are only three functions which actually change the value of the internal state of this object after it's been instantiated
setState_TD(temperature, rho)
density(temperature, pressure, phase, rhoguess)
psat(temperature, waterState);
The setState_TD() is the main function that sets the temperature and rho value. The density() function serves as a setState_TP() function, in that it sets internal state to a temperature and pressure. However, note that this is potentially multivalued. Therefore, we need to supply in addition a phase guess and a rho guess to the input temperature and pressure. The psat() function sets the internal state to the saturated liquid or saturated gas state, depending on the waterState parameter.
Because the underlying object WaterPropsIAPWSphi is privately held, you can be sure that the underlying state of this object doesn't change except due to the three function calls listed above.
Definition at line 161 of file WaterPropsIAPWS.h.
Constructor & Destructor Documentation
WaterPropsIAPWS()
WaterPropsIAPWS () default
Base constructor.
Member Function Documentation
setState_TR()
void setState_TR (doublereal temperature, doublereal rho)
Set the internal state of the object wrt temperature and density.
Parameters
temperature temperature (kelvin)
rho density (kg m-3)
Deprecated:
To be removed after Cantera 3.0; renamed to setState_TD()
Definition at line 579 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::setState_TD(), WaterPropsIAPWS::temperature(), and Cantera::warn_deprecated().
setState_TD()
void setState_TD (double temperature, double rho)
Set the internal state of the object wrt temperature and density.
Parameters
temperature temperature (kelvin)
rho density (kg m-3)
Since
New in Cantera 3.0.
Definition at line 586 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::calcDim(), WaterPropsIAPWS::delta, WaterPropsIAPWS::m_phi, WaterPropsIAPWS::tau, WaterPropsIAPWSphi::tdpolycalc(), and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::corr(), WaterPropsIAPWS::corr1(), PDSS_Water::cp_R_ref(), WaterPropsIAPWS::density(), PDSS_Water::dthermalExpansionCoeffdT(), WaterSSTP::dthermalExpansionCoeffdT(), PDSS_Water::enthalpy_RT_ref(), PDSS_Water::entropy_R_ref(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), PDSS_Water::gibbs_RT_ref(), PDSS_Water::molarVolume_ref(), WaterPropsIAPWS::psat(), WaterSSTP::satPressure(), WaterSSTP::setDensity(), PDSS_Water::setDensity(), PDSS_Water::setState_TR(), WaterPropsIAPWS::setState_TR(), WaterSSTP::setTemperature(), and PDSS_Water::setTemperature().
gibbs_mass()
double gibbs_mass () const
Get the Gibbs free energy (J/kg) at the current temperature and density.
Definition at line 592 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::gibbs_RT(), WaterPropsIAPWS::m_phi, Cantera::T_c, and WaterPropsIAPWS::tau.
Referenced by WaterSSTP::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getStandardChemPotentials(), and PDSS_Water::gibbs_mole().
enthalpy_mass()
double enthalpy_mass () const
Get the enthalpy (J/kg) at the current temperature and density.
Definition at line 597 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::enthalpy_RT(), WaterPropsIAPWS::m_phi, Cantera::T_c, and WaterPropsIAPWS::tau.
Referenced by PDSS_Water::enthalpy_mole(), PDSS_Water::enthalpy_RT_ref(), WaterSSTP::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), and PDSS_Water::gibbs_RT_ref().
intEnergy_mass()
double intEnergy_mass () const
Get the internal energy (J/kg) at the current temperature and density.
Definition at line 602 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::intEnergy_RT(), WaterPropsIAPWS::m_phi, Cantera::T_c, and WaterPropsIAPWS::tau.
Referenced by WaterSSTP::getIntEnergy_RT(), and PDSS_Water::intEnergy_mole().
entropy_mass()
double entropy_mass () const
Get the entropy (J/kg/K) at the current temperature and density.
Definition at line 607 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::entropy_R(), and WaterPropsIAPWS::m_phi.
Referenced by PDSS_Water::entropy_mole(), PDSS_Water::entropy_R_ref(), WaterSSTP::getEntropy_R(), and WaterSSTP::getEntropy_R_ref().
cv_mass()
double cv_mass () const
Get the constant volume heat capacity (J/kg/K) at the current temperature and density.
Definition at line 612 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::cv_R(), and WaterPropsIAPWS::m_phi.
Referenced by PDSS_Water::cv_mole(), and WaterSSTP::cv_mole().
cp_mass()
double cp_mass () const
Get the constant pressure heat capacity (J/kg/K) at the current temperature and density.
Definition at line 617 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::cp_R(), and WaterPropsIAPWS::m_phi.
Referenced by PDSS_Water::cp_mole(), PDSS_Water::cp_R_ref(), WaterSSTP::getCp_R(), and WaterSSTP::getCp_R_ref().
helmholtzFE()
doublereal helmholtzFE () const
Calculate the Helmholtz free energy in mks units of J kmol-1 K-1, using the last temperature and density.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 57 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::m_phi, WaterPropsIAPWSphi::phi(), Cantera::Rgas, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWS::temperature(), and Cantera::warn_deprecated().
Gibbs()
doublereal Gibbs () const
Calculate the Gibbs free energy in mks units of J kmol-1 K-1.
using the last temperature and density
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 264 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::gibbs_RT(), WaterPropsIAPWS::m_phi, Cantera::Rgas, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWS::temperature(), and Cantera::warn_deprecated().
enthalpy()
doublereal enthalpy () const
Calculate the enthalpy in mks units of J kmol-1 using the last temperature and density.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 622 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::enthalpy_RT(), WaterPropsIAPWS::m_phi, Cantera::Rgas, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWS::temperature(), and Cantera::warn_deprecated().
intEnergy()
doublereal intEnergy () const
Calculate the internal energy in mks units of J kmol-1.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 631 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::intEnergy_RT(), WaterPropsIAPWS::m_phi, Cantera::Rgas, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWS::temperature(), and Cantera::warn_deprecated().
entropy()
doublereal entropy () const
Calculate the entropy in mks units of J kmol-1 K-1.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 640 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::entropy_R(), WaterPropsIAPWS::m_phi, Cantera::Rgas, and Cantera::warn_deprecated().
cv()
doublereal cv () const
Calculate the constant volume heat capacity in mks units of J kmol-1 K-1 at the last temperature and density.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 648 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::cv_R(), WaterPropsIAPWS::m_phi, Cantera::Rgas, and Cantera::warn_deprecated().
cp()
doublereal cp () const
Calculate the constant pressure heat capacity in mks units of J kmol-1 K-1 at the last temperature and density.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 656 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWSphi::cp_R(), WaterPropsIAPWS::m_phi, Cantera::Rgas, and Cantera::warn_deprecated().
molarVolume()
doublereal molarVolume () const
Calculate the molar volume (kmol m-3) at the last temperature and density.
Deprecated:
To be removed after Cantera 3.0. This class provides mass-based values only.
Definition at line 664 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, Cantera::M_water, Cantera::Rho_c, and Cantera::warn_deprecated().
pressure()
doublereal pressure () const
Calculates the pressure (Pascals), given the current value of the temperature and density.
The density is an independent variable in the underlying equation of state
Returns
the pressure (Pascal)
Definition at line 67 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::m_phi, WaterPropsIAPWSphi::pressureM_rhoRT(), Cantera::Rho_c, Cantera::T_c, WaterPropsIAPWS::tau, and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::corr(), WaterPropsIAPWS::corr1(), WaterPropsIAPWS::density(), WaterPropsIAPWS::density_const(), PDSS_Water::pressure(), and WaterSSTP::pressure().
density() [1/2]
doublereal density (doublereal temperature, doublereal pressure, int phase = -1, doublereal rhoguess = -1.0)
Calculates the density given the temperature and the pressure, and a guess at the density.
Sets the internal state.
Note, below T_c, this is a multivalued function.
The density() function calculates the density that is consistent with a particular value of the temperature and pressure. It may therefore be multivalued or potentially there may be no answer from this function. It therefore takes a phase guess and a density guess as optional parameters. If no guesses are supplied to density(), a gas phase guess is assumed. This may or may not be what is wanted. Therefore, density() should usually at least be supplied with a phase guess so that it may manufacture an appropriate density guess. density() manufactures the initial density guess, nondimensionalizes everything, and then calls WaterPropsIAPWSphi::dfind(), which does the iterative calculation to find the density condition that matches the desired input pressure.
Parameters
temperature Kelvin
pressure Pressure in Pascals (Newton/m**2)
phase guessed phase of water; -1: no guessed phase
rhoguess guessed density of the water; -1.0 no guessed density
Returns
the density. If an error is encountered in the calculation the value of -1.0 is returned.
Definition at line 75 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWSphi::dfind(), WaterPropsIAPWS::m_phi, Cantera::P_c, WaterPropsIAPWS::pressure(), Cantera::Rho_c, WaterPropsIAPWS::setState_TD(), Cantera::T_c, WaterPropsIAPWS::tau, and WaterPropsIAPWS::temperature().
Referenced by WaterProps::coeffThermalExp_IAPWS(), PDSS_Water::cp_R_ref(), WaterProps::density_IAPWS(), PDSS_Water::dthermalExpansionCoeffdT(), WaterSSTP::dthermalExpansionCoeffdT(), PDSS_Water::enthalpy_RT_ref(), PDSS_Water::entropy_R_ref(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getStandardVolumes_ref(), PDSS_Water::gibbs_RT_ref(), WaterSSTP::initThermo(), WaterProps::isothermalCompressibility_IAPWS(), PDSS_Water::molarVolume(), PDSS_Water::molarVolume_ref(), PDSS_Water::PDSS_Water(), PDSS_Water::satPressure(), WaterSSTP::setPressure(), and PDSS_Water::setPressure().
density_const()
doublereal density_const (doublereal pressure, int phase = -1, doublereal rhoguess = -1.0) const
Calculates the density given the temperature and the pressure, and a guess at the density, while not changing the internal state.
Note, below T_c, this is a multivalued function.
The density() function calculates the density that is consistent with a particular value of the temperature and pressure. It may therefore be multivalued or potentially there may be no answer from this function. It therefore takes a phase guess and a density guess as optional parameters. If no guesses are supplied to density(), a gas phase guess is assumed. This may or may not be what is wanted. Therefore, density() should usually at least be supplied with a phase guess so that it may manufacture an appropriate density guess. density() manufactures the initial density guess, nondimensionalizes everything, and then calls WaterPropsIAPWSphi::dfind(), which does the iterative calculation to find the density condition that matches the desired input pressure.
Parameters
pressure Pressure in Pascals (Newton/m**2)
phase guessed phase of water; -1: no guessed phase
rhoguess guessed density of the water; -1.0: no guessed density
Returns
the density. If an error is encountered in the calculation the value of -1.0 is returned.
Definition at line 135 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWSphi::dfind(), WaterPropsIAPWS::m_phi, WaterPropsIAPWS::pressure(), Cantera::Rho_c, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWSphi::tdpolycalc(), and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::densSpinodalSteam(), and WaterPropsIAPWS::densSpinodalWater().
density() [2/2]
doublereal density () const
Returns the density (kg m-3)
The density is an independent variable in the underlying equation of state
Returns
the density (kg m-3)
Definition at line 189 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, and Cantera::Rho_c.
Referenced by WaterPropsIAPWS::corr(), WaterPropsIAPWS::corr1(), and WaterPropsIAPWS::psat().
temperature()
doublereal temperature () const
Returns the temperature (Kelvin)
Returns
s the internally stored temperature
Definition at line 194 of file WaterPropsIAPWS.cpp.
References Cantera::T_c, and WaterPropsIAPWS::tau.
Referenced by WaterPropsIAPWS::calcDim(), WaterPropsIAPWS::corr(), WaterPropsIAPWS::corr1(), WaterPropsIAPWS::density(), WaterPropsIAPWS::density_const(), WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), WaterPropsIAPWS::dpdrho(), WaterPropsIAPWS::enthalpy(), WaterPropsIAPWS::Gibbs(), WaterPropsIAPWS::helmholtzFE(), WaterPropsIAPWS::intEnergy(), WaterPropsIAPWS::pressure(), WaterPropsIAPWS::psat(), WaterPropsIAPWS::psat_est(), WaterPropsIAPWS::setState_TD(), and WaterPropsIAPWS::setState_TR().
coeffThermExp()
doublereal coeffThermExp () const
Returns the coefficient of thermal expansion.
alpha = d (ln V) / dT at constant P.
Returns
the coefficient of thermal expansion
Definition at line 256 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::coeffPresExp(), WaterPropsIAPWS::delta, WaterPropsIAPWS::isothermalCompressibility(), and Cantera::Rho_c.
Referenced by WaterProps::coeffThermalExp_IAPWS(), PDSS_Water::dthermalExpansionCoeffdT(), WaterSSTP::dthermalExpansionCoeffdT(), PDSS_Water::thermalExpansionCoeff(), and WaterSSTP::thermalExpansionCoeff().
coeffPresExp()
doublereal coeffPresExp () const
Returns the isochoric pressure derivative wrt temperature.
beta = M / (rho * Rgas) (d (pressure) / dT) at constant rho
Note for ideal gases this is equal to one.
beta = delta (phi0_d() + phiR_d()) - tau delta (phi0_dt() + phiR_dt())
Definition at line 251 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWSphi::dimdpdT(), WaterPropsIAPWS::m_phi, and WaterPropsIAPWS::tau.
Referenced by WaterPropsIAPWS::coeffThermExp().
isothermalCompressibility()
doublereal isothermalCompressibility () const
Returns the coefficient of isothermal compressibility for the state of the object.
kappa = - d (ln V) / dP at constant T.
units - 1/Pascal
Returns
the isothermal compressibility
Definition at line 237 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::dpdrho(), and Cantera::Rho_c.
Referenced by WaterPropsIAPWS::coeffThermExp(), PDSS_Water::isothermalCompressibility(), WaterSSTP::isothermalCompressibility(), WaterProps::isothermalCompressibility_IAPWS(), and WaterPropsIAPWS::phaseState().
dpdrho()
doublereal dpdrho () const
Returns the value of dp / drho at constant T for the state of the object.
units - Joules / kg
Returns
dpdrho
Definition at line 244 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWSphi::dimdpdrho(), WaterPropsIAPWS::m_phi, Cantera::T_c, WaterPropsIAPWS::tau, and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), and WaterPropsIAPWS::isothermalCompressibility().
psat_est()
doublereal psat_est (doublereal temperature) const
This function returns an estimated value for the saturation pressure.
It does this via a polynomial fit of the vapor pressure curve. units = (Pascals)
Parameters
temperature Input temperature (Kelvin)
Returns
the estimated saturation pressure
Definition at line 199 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), PDSS_Water::pref_safe(), and WaterPropsIAPWS::psat().
psat()
doublereal psat (doublereal temperature, int waterState = WATER_LIQUID)
This function returns the saturation pressure given the temperature as an input parameter, and sets the internal state to the saturated conditions.
Note this function will return the saturation pressure, given the temperature. It will then set the state of the system to the saturation condition. The input parameter waterState is used to either specify the liquid state or the gas state at the desired temperature and saturated pressure.
If the input temperature, T, is above T_c, this routine will set the internal state to T and the pressure to P_c. Then, return P_c.
Parameters
temperature input temperature (kelvin)
waterState integer specifying the water state
Returns
the saturation pressure. units = Pascal
Definition at line 322 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::corr(), WaterPropsIAPWS::corr1(), WaterPropsIAPWS::density(), Cantera::P_c, WaterPropsIAPWS::psat_est(), WaterPropsIAPWS::setState_TD(), Cantera::T_c, and WaterPropsIAPWS::temperature().
Referenced by PDSS_Water::satPressure(), WaterProps::satPressure(), WaterSSTP::satPressure(), and WaterSSTP::setPressure().
densSpinodalWater()
doublereal densSpinodalWater () const
Return the value of the density at the water spinodal point (on the liquid side) for the current temperature.
Returns
the density with units of kg m-3
Definition at line 404 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::density_const(), WaterPropsIAPWS::dpdrho(), WaterPropsIAPWS::m_phi, WaterPropsIAPWS::psat_est(), Cantera::Rho_c, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWSphi::tdpolycalc(), and WaterPropsIAPWS::temperature().
densSpinodalSteam()
doublereal densSpinodalSteam () const
Return the value of the density at the water spinodal point (on the gas side) for the current temperature.
Returns
the density with units of kg m-3
Definition at line 492 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::density_const(), WaterPropsIAPWS::dpdrho(), WaterPropsIAPWS::m_phi, WaterPropsIAPWS::psat_est(), Cantera::Rho_c, Cantera::T_c, WaterPropsIAPWS::tau, WaterPropsIAPWSphi::tdpolycalc(), and WaterPropsIAPWS::temperature().
phaseState()
int phaseState (bool checkState = false) const
Returns the Phase State flag for the current state of the object.
Parameters
checkState If true, this function does a complete check to see where in parameters space we are
There are three values:
WATER_GAS below the critical temperature but below the critical density
WATER_LIQUID below the critical temperature but above the critical density
WATER_SUPERCRIT above the critical temperature
Definition at line 364 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::isothermalCompressibility(), WaterPropsIAPWS::iState, WaterPropsIAPWS::m_phi, Cantera::OneAtm, Cantera::Rho_c, Cantera::T_c, WaterPropsIAPWS::tau, and WaterPropsIAPWSphi::tdpolycalc().
Referenced by WaterSSTP::phaseOfMatter(), and PDSS_Water::setPressure().
Tcrit()
doublereal Tcrit () const inline
Returns the critical temperature of water (Kelvin)
This is hard coded to the value 647.096 Kelvin
Definition at line 424 of file WaterPropsIAPWS.h.
Referenced by PDSS_Water::critTemperature(), WaterSSTP::critTemperature(), PDSS_Water::pref_safe(), WaterSSTP::setPressure(), PDSS_Water::setPressure(), and WaterSSTP::vaporFraction().
Pcrit()
doublereal Pcrit () const inline
Returns the critical pressure of water (22.064E6 Pa)
This is hard coded to the value of 22.064E6 pascals
Definition at line 432 of file WaterPropsIAPWS.h.
Referenced by PDSS_Water::critPressure(), WaterSSTP::critPressure(), and PDSS_Water::pref_safe().
Rhocrit()
doublereal Rhocrit () const inline
Return the critical density of water (kg m-3)
This is equal to 322 kg m-3.
Definition at line 440 of file WaterPropsIAPWS.h.
Referenced by PDSS_Water::critDensity(), WaterSSTP::critDensity(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), WaterSSTP::getStandardVolumes_ref(), and WaterSSTP::vaporFraction().
calcDim()
void calcDim (doublereal temperature, doublereal rho) private
Calculate the dimensionless temp and rho and store internally.
Parameters
temperature input temperature (kelvin)
rho density in kg m-3
Definition at line 40 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::delta, WaterPropsIAPWS::iState, Cantera::Rho_c, Cantera::T_c, WaterPropsIAPWS::tau, and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::setState_TD().
corr()
void corr (doublereal temperature, doublereal pressure, doublereal & densLiq, doublereal & densGas, doublereal & delGRT) private
Utility routine in the calculation of the saturation pressure.
Calculate the Gibbs free energy in mks units of J kmol-1 K-1.
Parameters
temperature temperature (kelvin)
pressure pressure (Pascal)
densLiq Output density of liquid
densGas output Density of gas
delGRT output delGRT
Definition at line 273 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::density(), WaterPropsIAPWSphi::gibbs_RT(), WaterPropsIAPWS::m_phi, WaterPropsIAPWS::pressure(), WaterPropsIAPWS::setState_TD(), and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::psat().
corr1()
void corr1 (doublereal temperature, doublereal pressure, doublereal & densLiq, doublereal & densGas, doublereal & pcorr) private
Utility routine in the calculation of the saturation pressure.
Parameters
temperature temperature (kelvin)
pressure pressure (Pascal)
densLiq Output density of liquid
densGas output Density of gas
pcorr output corrected pressure
Definition at line 297 of file WaterPropsIAPWS.cpp.
References WaterPropsIAPWS::density(), WaterPropsIAPWS::m_phi, WaterPropsIAPWSphi::phiR(), WaterPropsIAPWS::pressure(), WaterPropsIAPWS::setState_TD(), and WaterPropsIAPWS::temperature().
Referenced by WaterPropsIAPWS::psat().
Member Data Documentation
m_phi
WaterPropsIAPWSphi m_phi mutable private
pointer to the underlying object that does the calculations.
Definition at line 477 of file WaterPropsIAPWS.h.
Referenced by WaterPropsIAPWS::coeffPresExp(), WaterPropsIAPWS::corr(), WaterPropsIAPWS::corr1(), WaterPropsIAPWS::cp(), WaterPropsIAPWS::cp_mass(), WaterPropsIAPWS::cv(), WaterPropsIAPWS::cv_mass(), WaterPropsIAPWS::density(), WaterPropsIAPWS::density_const(), WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), WaterPropsIAPWS::dpdrho(), WaterPropsIAPWS::enthalpy(), WaterPropsIAPWS::enthalpy_mass(), WaterPropsIAPWS::entropy(), WaterPropsIAPWS::entropy_mass(), WaterPropsIAPWS::Gibbs(), WaterPropsIAPWS::gibbs_mass(), WaterPropsIAPWS::helmholtzFE(), WaterPropsIAPWS::intEnergy(), WaterPropsIAPWS::intEnergy_mass(), WaterPropsIAPWS::phaseState(), WaterPropsIAPWS::pressure(), and WaterPropsIAPWS::setState_TD().
tau
double tau = -1.0 private
Dimensionless temperature, tau = T_C / T.
Definition at line 480 of file WaterPropsIAPWS.h.
Referenced by WaterPropsIAPWS::calcDim(), WaterPropsIAPWS::coeffPresExp(), WaterPropsIAPWS::density(), WaterPropsIAPWS::density_const(), WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), WaterPropsIAPWS::dpdrho(), WaterPropsIAPWS::enthalpy(), WaterPropsIAPWS::enthalpy_mass(), WaterPropsIAPWS::Gibbs(), WaterPropsIAPWS::gibbs_mass(), WaterPropsIAPWS::helmholtzFE(), WaterPropsIAPWS::intEnergy(), WaterPropsIAPWS::intEnergy_mass(), WaterPropsIAPWS::phaseState(), WaterPropsIAPWS::pressure(), WaterPropsIAPWS::setState_TD(), and WaterPropsIAPWS::temperature().
delta
double delta = -1.0 mutable private
Dimensionless density, delta = rho / rho_c.
Definition at line 483 of file WaterPropsIAPWS.h.
Referenced by WaterPropsIAPWS::calcDim(), WaterPropsIAPWS::coeffPresExp(), WaterPropsIAPWS::coeffThermExp(), WaterPropsIAPWS::density(), WaterPropsIAPWS::density_const(), WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), WaterPropsIAPWS::dpdrho(), WaterPropsIAPWS::helmholtzFE(), WaterPropsIAPWS::isothermalCompressibility(), WaterPropsIAPWS::molarVolume(), WaterPropsIAPWS::phaseState(), WaterPropsIAPWS::pressure(), and WaterPropsIAPWS::setState_TD().
iState
int iState = -30000 mutable private
Current state of the system.
Definition at line 486 of file WaterPropsIAPWS.h.
Referenced by WaterPropsIAPWS::calcDim(), and WaterPropsIAPWS::phaseState().
The documentation for this class was generated from the following files:
WaterPropsIAPWS.h
WaterPropsIAPWS.cpp