Cantera: PlasmaPhase Class Reference
PlasmaPhase Class Reference
Base class for a phase with plasma properties.
#include <PlasmaPhase.h>
Public Member Functions
PlasmaPhase (const std::string &inputFile="", const std::string &id="")
Construct and initialize a PlasmaPhase object directly from an input file.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
void setElectronEnergyLevels (const double *levels, size_t length)
Set electron energy levels.
void getElectronEnergyLevels (double *levels) const
Get electron energy levels.
void setDiscretizedElectronEnergyDist (const double *levels, const double *distrb, size_t length)
Set discretized electron energy distribution.
void getElectronEnergyDistribution (double *distrb) const
Get electron energy distribution.
void setIsotropicShapeFactor (double x)
Set the shape factor of isotropic electron energy distribution.
double isotropicShapeFactor () const
The shape factor of isotropic electron energy distribution.
virtual void setElectronTemperature (double Te)
Set the internally stored electron temperature of the phase (K).
void setMeanElectronEnergy (double energy)
Set mean electron energy [eV].
std::string electronEnergyDistributionType () const
Get electron energy distribution type.
void setElectronEnergyDistributionType (const std::string &type)
Set electron energy distribution type.
std::string quadratureMethod () const
Numerical quadrature method. Method: m_quadratureMethod.
void setQuadratureMethod (const std::string &method)
Set numerical quadrature method for intergating electron energy distribution function.
double meanElectronEnergy () const
Mean electron energy [eV].
void enableNormalizeElectronEnergyDist (bool enable)
Set flag of automatically normalize electron energy distribution Flag: m_do_normalizeElectronEnergyDist.
bool normalizeElectronEnergyDistEnabled () const
Flag of automatically normalize electron energy distribution.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual double electronTemperature () const
Electron Temperature (K)
double RTe () const
Return the Gas Constant multiplied by the current electron temperature.
virtual double electronPressure () const
Electron pressure.
size_t nElectronEnergyLevels () const
Number of electron levels.
size_t electronSpeciesIndex () const
Electron Species Index.
virtual double enthalpy_mole () const
Return the Molar enthalpy. Units: J/kmol.
virtual double cp_mole () const
Molar heat capacity at constant pressure.
virtual double entropy_mole () const
Molar entropy.
virtual double gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual double intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual void getEntropy_R (double *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (double *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getGibbs_ref (double *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getStandardVolumes_ref (double *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void getChemPotentials (double *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getStandardChemPotentials (double *muStar) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getPartialMolarEnthalpies (double *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (double *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (double *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
Public Member Functions inherited from IdealGasPhase
IdealGasPhase (const std::string &inputFile="", const std::string &id="")
Construct and initialize an IdealGasPhase ThermoPhase object directly from an input file.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool isIdeal () const
Boolean indicating whether phase is ideal.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume.
virtual doublereal pressure () const
Pressure.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature and composition.
virtual void setState_DP (doublereal rho, doublereal p)
Set the density and pressure at constant composition.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual double soundSpeed () const
Return the speed of sound. Units: m/s.
virtual void getActivityConcentrations (doublereal *c) const
This method returns the array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
const vector_fp & enthalpy_RT_ref () const
Returns a reference to the dimensionless reference state enthalpy vector.
const vector_fp & gibbs_RT_ref () const
Returns a reference to the dimensionless reference state Gibbs free energy vector.
const vector_fp & entropy_R_ref () const
Returns a reference to the dimensionless reference state Entropy vector.
const vector_fp & cp_R_ref () const
Returns a reference to the dimensionless reference state Heat Capacity vector.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()=default
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
void initThermoFile (const std::string &inputFile, const std::string &id)
Initialize a ThermoPhase object using an input file.
AnyMap parameters (bool withInput=true) const
Returns the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getSpeciesParameters (const std::string &name, AnyMap &speciesNode) const
Get phase-specific parameters of a Species object such that an identical one could be reconstructed and added to this phase.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, double *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()=default
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
string nativeMode () const
Return string acronym representing the native state of a Phase.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
const vector_fp & inverseMolecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual void setMolesNoTruncate (const double *const N)
Set the state of the object with moles in [kmol].
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, for example speciesIndex.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TD (double t, double rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
virtual void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
virtual double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal temperature () const
Temperature (K).
virtual double density () const
Density (kg/m^3).
virtual double molarDensity () const
Molar density (kmol/m^3).
virtual double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (double temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (that is, a user-defined alternative species name).
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
virtual void updateThermo () const
Update the species reference state thermodynamic functions.
void checkElectronEnergyLevels () const
Check the electron energy levels.
void checkElectronEnergyDistribution () const
Check the electron energy distribution.
void updateElectronEnergyDistribution ()
Update electron energy distribution.
void setIsotropicElectronEnergyDistribution ()
Set isotropic electron energy distribution.
void updateElectronTemperatureFromEnergyDist ()
Update electron temperature (K) From energy distribution.
void normalizeElectronEnergyDistribution ()
Electron energy distribution norm.
virtual void updateThermo () const
Update the species reference state thermodynamic functions.
Protected Member Functions inherited from ThermoPhase
virtual void getParameters (AnyMap &phaseNode) const
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes
double m_isotropicShapeFactor = 2.0
size_t m_nPoints = 1001
Number of points of electron energy levels.
Eigen::ArrayXd m_electronEnergyLevels
electron energy levels [ev]. Length: m_nPoints
Eigen::ArrayXd m_electronEnergyDist
Normalized electron energy distribution vector [-] Length: m_nPoints.
size_t m_electronSpeciesIndex = npos
Index of electron species.
double m_electronTemp
Electron temperature [K].
string m_distributionType = "isotropic"
Electron energy distribution type.
string m_quadratureMethod = "simpson"
Numerical quadrature method for electron energy distribution.
bool m_do_normalizeElectronEnergyDist = true
Flag of normalizing electron energy distribution.
Protected Attributes inherited from IdealGasPhase
double m_p0 = -1.0
Reference state pressure.
vector_fp m_h0_RT
Temporary storage for dimensionless reference state enthalpies.
vector_fp m_cp0_R
Temporary storage for dimensionless reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for dimensionless reference state Gibbs energies.
vector_fp m_s0_R
Temporary storage for dimensionless reference state entropies.
vector_fp m_expg0_RT
vector_fp m_pp
Temporary array containing internally calculated partial pressures.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
double m_phi = 0.0
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary = false
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention = cSS_CONVENTION_TEMPERATURE
Contains the standard state convention.
double m_tlast = 0.0
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk = 0
Number of species in the phase.
size_t m_ndim = 3
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior = UndefElement::add
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies = false
Flag determining whether case sensitive species names are enforced.
Detailed Description
Base class for a phase with plasma properties.
This class manages the plasma properties such as electron energy distribution function (EEDF). There are two ways to define the electron distribution and electron temperature. The first method uses setElectronTemperature() to set the electron temperature which is used to calculate the electron energy distribution with isotropic-velocity model. The generalized electron energy distribution for isotropic-velocity distribution can be expressed as [1,2],
\[ f(\epsilon) = c_1 \frac{\sqrt{\epsilon}}{\epsilon_m^{3/2}} \exp(-c_2 (\frac{\epsilon}{\epsilon_m})^x), \]
where \(x = 1 \) and \(x = 2 \) correspond to the Maxwellian and Druyvesteyn (default) electron energy distribution, respectively. \(\epsilon_m = 3/2 T_e \) [eV] (mean electron energy). The second method uses setDiscretizedElectronEnergyDist() to manually set electron energy distribution and calculate electron temperature from mean electron energy, which is calculated as [3],
\[ \epsilon_m = \int_0^{\infty} \epsilon^{3/2} f(\epsilon) d\epsilon, \]
which can be calculated using trapezoidal rule,
\[ \epsilon_m = \sum_i (\epsilon^{5/2}_{i+1} - \epsilon^{5/2}_i) (f(\epsilon_{i+1}) + f(\epsilon_i)) / 2, \]
where \(i \) is the index of energy levels.
References:
[1] J. T. Gudmundsson. On the effect of the electron energy distribution on the plasma parameters of an argon discharge: a global (volume-averaged) model study. Plasma Sources Science and Technology, 10.1 (2001): 76. doi: https://doi.org/10.1088/0963-0252/10/1/310
[2] H. Khalilpour and G. Foroutan. The effects of electron energy distribution function on the plasma sheath structure in the presence of charged nanoparticles Journal of Plasma Physics 86.2 (2020). doi: https://doi.org/10.1017/S0022377820000161
[3] G. J. M. Hagelaar and L. C. Pitchford "Solving the Boltzmann equation to obtain electron transport coefficients and rate coefficients for fluid models." Plasma Sources Science and Technology 14.4 (2005): 722. doi: https://doi.org/10.1088/0963-0252/14/4/011
[4] A. Luque, "BOLOS: An open source solver for the Boltzmann equation," https://github.com/aluque/bolos.
Warning
This class is an experimental part of Cantera and may be changed or removed without notice.
Todo:
Implement electron Boltzmann equation solver to solve EEDF. https://github.com/Cantera/enhancements/issues/127
Definition at line 74 of file PlasmaPhase.h.
Constructor & Destructor Documentation
PlasmaPhase()
PlasmaPhase (const std::string & inputFile = "", const std::string & id = "") explicit
Construct and initialize a PlasmaPhase object directly from an input file.
The constructor initializes the electron energy distribution to be Druyvesteyn distribution (m_x = 2.0). The initial electron energy grid is set to a linear space which starts at 0.01 eV and ends at 1 eV with 1000 points.
Parameters
inputFile Name of the input file containing the phase definition to set up the object. If blank, an empty phase will be created.
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 14 of file PlasmaPhase.cpp.
References ThermoPhase::initThermoFile(), PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_nPoints, PlasmaPhase::setElectronTemperature(), and Phase::temperature().
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Since
Starting in Cantera 3.0, the name returned by this method corresponds to the canonical name used in the YAML input format.
Reimplemented from IdealGasPhase.
Definition at line 92 of file PlasmaPhase.h.
Referenced by PlasmaPhase::setElectronEnergyDistributionType().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing from an AnyMap phase description (or from a YAML file), setupPhase() adds all the species, stores the input data in m_input, and then calls this method to set model parameters from the data stored in m_input.
Reimplemented from ThermoPhase.
Definition at line 235 of file PlasmaPhase.cpp.
References ThermoPhase::initThermo(), PlasmaPhase::m_electronSpeciesIndex, and Cantera::npos.
setElectronEnergyLevels()
void setElectronEnergyLevels (const double * levels, size_t length)
Set electron energy levels.
Parameters
levels The vector of electron energy levels (eV). Length: m_nPoints.
length The length of the levels.
Definition at line 84 of file PlasmaPhase.cpp.
References PlasmaPhase::checkElectronEnergyLevels(), PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_nPoints, and PlasmaPhase::updateElectronEnergyDistribution().
Referenced by PlasmaPhase::setParameters().
getElectronEnergyLevels()
void getElectronEnergyLevels (double * levels) const inline
Get electron energy levels.
Parameters
levels The vector of electron energy levels (eV). Length: m_nPoints
Definition at line 106 of file PlasmaPhase.h.
References PlasmaPhase::m_electronEnergyLevels, and PlasmaPhase::m_nPoints.
setDiscretizedElectronEnergyDist()
void setDiscretizedElectronEnergyDist (const double * levels, const double * distrb, size_t length)
Set discretized electron energy distribution.
Parameters
levels The vector of electron energy levels (eV). Length: m_nPoints.
distrb The vector of electron energy distribution. Length: m_nPoints.
length The length of the vectors, which equals m_nPoints.
Definition at line 120 of file PlasmaPhase.cpp.
References PlasmaPhase::checkElectronEnergyDistribution(), PlasmaPhase::checkElectronEnergyLevels(), PlasmaPhase::m_distributionType, PlasmaPhase::m_do_normalizeElectronEnergyDist, PlasmaPhase::m_electronEnergyDist, PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_nPoints, PlasmaPhase::normalizeElectronEnergyDistribution(), and PlasmaPhase::updateElectronTemperatureFromEnergyDist().
Referenced by PlasmaPhase::setParameters().
getElectronEnergyDistribution()
void getElectronEnergyDistribution (double * distrb) const inline
Get electron energy distribution.
Parameters
distrb The vector of electron energy distribution. Length: m_nPoints.
Definition at line 123 of file PlasmaPhase.h.
References PlasmaPhase::m_electronEnergyDist, and PlasmaPhase::m_nPoints.
setIsotropicShapeFactor()
void setIsotropicShapeFactor (double x)
Set the shape factor of isotropic electron energy distribution.
Note that \(x = 1 \) and \(x = 2 \) correspond to the Maxwellian and Druyvesteyn distribution, respectively.
Parameters
x The shape factor
Definition at line 147 of file PlasmaPhase.cpp.
References PlasmaPhase::setIsotropicElectronEnergyDistribution().
Referenced by PlasmaPhase::setParameters().
isotropicShapeFactor()
double isotropicShapeFactor () const inline
The shape factor of isotropic electron energy distribution.
Definition at line 134 of file PlasmaPhase.h.
setElectronTemperature()
void setElectronTemperature (double Te) virtual
Set the internally stored electron temperature of the phase (K).
Parameters
Te Electron temperature in Kelvin
Reimplemented from Phase.
Definition at line 74 of file PlasmaPhase.cpp.
References PlasmaPhase::m_electronTemp, and PlasmaPhase::updateElectronEnergyDistribution().
Referenced by PlasmaPhase::PlasmaPhase().
setMeanElectronEnergy()
void setMeanElectronEnergy (double energy)
Set mean electron energy [eV].
This method also sets electron temperature accordingly.
Definition at line 79 of file PlasmaPhase.cpp.
References Cantera::Boltzmann, Cantera::ElectronCharge, PlasmaPhase::m_electronTemp, and PlasmaPhase::updateElectronEnergyDistribution().
Referenced by PlasmaPhase::setParameters().
electronEnergyDistributionType()
std::string electronEnergyDistributionType () const inline
Get electron energy distribution type.
Definition at line 147 of file PlasmaPhase.h.
References PlasmaPhase::m_distributionType.
setElectronEnergyDistributionType()
void setElectronEnergyDistributionType (const std::string & type)
Set electron energy distribution type.
Definition at line 47 of file PlasmaPhase.cpp.
References PlasmaPhase::m_distributionType, and PlasmaPhase::type().
quadratureMethod()
std::string quadratureMethod () const inline
Numerical quadrature method. Method: m_quadratureMethod.
Definition at line 155 of file PlasmaPhase.h.
References PlasmaPhase::m_quadratureMethod.
setQuadratureMethod()
void setQuadratureMethod (const std::string & method) inline
Set numerical quadrature method for intergating electron energy distribution function.
Method: m_quadratureMethod
Definition at line 161 of file PlasmaPhase.h.
References PlasmaPhase::m_quadratureMethod.
meanElectronEnergy()
double meanElectronEnergy () const inline
Mean electron energy [eV].
Definition at line 166 of file PlasmaPhase.h.
References Cantera::Boltzmann, Cantera::ElectronCharge, and PlasmaPhase::electronTemperature().
Referenced by PlasmaPhase::checkElectronEnergyDistribution(), PlasmaPhase::getParameters(), and PlasmaPhase::setIsotropicElectronEnergyDistribution().
enableNormalizeElectronEnergyDist()
void enableNormalizeElectronEnergyDist (bool enable) inline
Set flag of automatically normalize electron energy distribution Flag: m_do_normalizeElectronEnergyDist.
Definition at line 172 of file PlasmaPhase.h.
References PlasmaPhase::m_do_normalizeElectronEnergyDist.
Referenced by PlasmaPhase::setParameters().
normalizeElectronEnergyDistEnabled()
bool normalizeElectronEnergyDistEnabled () const inline
Flag of automatically normalize electron energy distribution.
Flag: m_do_normalizeElectronEnergyDist
Definition at line 178 of file PlasmaPhase.h.
References PlasmaPhase::m_do_normalizeElectronEnergyDist.
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Reimplemented from IdealGasPhase.
Definition at line 216 of file PlasmaPhase.cpp.
References IdealGasPhase::addSpecies(), PlasmaPhase::m_electronSpeciesIndex, Phase::m_kk, and Cantera::npos.
electronTemperature()
virtual double electronTemperature () const inline virtual
Electron Temperature (K)
Returns
The electron temperature of the phase
Reimplemented from Phase.
Definition at line 186 of file PlasmaPhase.h.
References PlasmaPhase::m_electronTemp.
Referenced by PlasmaPhase::electronPressure(), PlasmaPhase::enthalpy_mole(), PlasmaPhase::getGibbs_ref(), PlasmaPhase::getPartialMolarEnthalpies(), PlasmaPhase::getStandardVolumes_ref(), PlasmaPhase::meanElectronEnergy(), PlasmaPhase::RTe(), and PlasmaPhase::updateThermo().
RTe()
double RTe () const inline
Return the Gas Constant multiplied by the current electron temperature.
The units are Joules kmol-1
Definition at line 194 of file PlasmaPhase.h.
References PlasmaPhase::electronTemperature(), and Cantera::GasConstant.
Referenced by PlasmaPhase::getChemPotentials(), PlasmaPhase::getPartialMolarIntEnergies(), and PlasmaPhase::getStandardChemPotentials().
electronPressure()
virtual double electronPressure () const inline virtual
Electron pressure.
Units: Pa.
\[P = n_{k_e} R T_e\]
Definition at line 202 of file PlasmaPhase.h.
References Phase::concentration(), PlasmaPhase::electronTemperature(), Cantera::GasConstant, and PlasmaPhase::m_electronSpeciesIndex.
Referenced by PlasmaPhase::getEntropy_R(), PlasmaPhase::getGibbs_RT(), PlasmaPhase::getPartialMolarEntropies(), and PlasmaPhase::getStandardChemPotentials().
nElectronEnergyLevels()
size_t nElectronEnergyLevels () const inline
Number of electron levels.
Definition at line 208 of file PlasmaPhase.h.
References PlasmaPhase::m_nPoints.
electronSpeciesIndex()
size_t electronSpeciesIndex () const inline
Electron Species Index.
Definition at line 213 of file PlasmaPhase.h.
References PlasmaPhase::m_electronSpeciesIndex.
enthalpy_mole()
double enthalpy_mole () const virtual
Return the Molar enthalpy. Units: J/kmol.
For an ideal gas mixture with additional electron,
\[ \hat h(T) = \sum_{k \neq k_e} X_k \hat h^0_k(T) + X_{k_e} \hat h^0_{k_e}(T_e), \]
and is a function only of temperature. The standard-state pure-species enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See also
MultiSpeciesThermo
Reimplemented from IdealGasPhase.
Definition at line 265 of file PlasmaPhase.cpp.
References PlasmaPhase::electronTemperature(), IdealGasPhase::enthalpy_mole(), Cantera::GasConstant, PlasmaPhase::m_electronSpeciesIndex, IdealGasPhase::m_h0_RT, Phase::moleFraction(), and Phase::temperature().
cp_mole()
virtual double cp_mole () const inline virtual
Molar heat capacity at constant pressure.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat c_p(t) = \sum_k \hat c^0_{p,k}(T). \]
The reference-state pure-species heat capacities \(\hat c^0_{p,k}(T) \) are computed by the species thermodynamic property manager.
See also
MultiSpeciesThermo
Reimplemented from IdealGasPhase.
Definition at line 231 of file PlasmaPhase.h.
entropy_mole()
virtual double entropy_mole () const inline virtual
Molar entropy.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat s(T, P) = \sum_k X_k \hat s^0_k(T) - \hat R \log (P/P^0). \]
The reference-state pure-species entropies \(\hat s^0_k(T) \) are computed by the species thermodynamic property manager.
See also
MultiSpeciesThermo
Reimplemented from IdealGasPhase.
Definition at line 235 of file PlasmaPhase.h.
gibbs_mole()
virtual double gibbs_mole () const inline virtual
Molar Gibbs function. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 239 of file PlasmaPhase.h.
intEnergy_mole()
virtual double intEnergy_mole () const inline virtual
Molar internal energy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 243 of file PlasmaPhase.h.
getEntropy_R()
void getEntropy_R (double * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from IdealGasPhase.
Definition at line 325 of file PlasmaPhase.cpp.
References PlasmaPhase::electronPressure(), IdealGasPhase::entropy_R_ref(), PlasmaPhase::m_electronSpeciesIndex, Phase::m_kk, IdealGasPhase::pressure(), and ThermoPhase::refPressure().
getGibbs_RT()
void getGibbs_RT (double * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from IdealGasPhase.
Definition at line 339 of file PlasmaPhase.cpp.
References PlasmaPhase::electronPressure(), IdealGasPhase::gibbs_RT_ref(), PlasmaPhase::m_electronSpeciesIndex, Phase::m_kk, IdealGasPhase::pressure(), and ThermoPhase::refPressure().
getGibbs_ref()
void getGibbs_ref (double * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from IdealGasPhase.
Definition at line 273 of file PlasmaPhase.cpp.
References PlasmaPhase::electronTemperature(), IdealGasPhase::getGibbs_ref(), PlasmaPhase::m_electronSpeciesIndex, and Phase::temperature().
getStandardVolumes_ref()
void getStandardVolumes_ref (double * vol) const virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from IdealGasPhase.
Definition at line 279 of file PlasmaPhase.cpp.
References PlasmaPhase::electronTemperature(), IdealGasPhase::getStandardVolumes_ref(), PlasmaPhase::m_electronSpeciesIndex, and Phase::temperature().
getChemPotentials()
void getChemPotentials (double * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from IdealGasPhase.
Definition at line 309 of file PlasmaPhase.cpp.
References IdealGasPhase::getChemPotentials(), PlasmaPhase::m_electronSpeciesIndex, Phase::moleFraction(), ThermoPhase::RT(), PlasmaPhase::RTe(), and Cantera::SmallNumber.
getStandardChemPotentials()
void getStandardChemPotentials (double * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from IdealGasPhase.
Definition at line 317 of file PlasmaPhase.cpp.
References PlasmaPhase::electronPressure(), IdealGasPhase::getStandardChemPotentials(), PlasmaPhase::m_electronSpeciesIndex, IdealGasPhase::pressure(), ThermoPhase::refPressure(), ThermoPhase::RT(), and PlasmaPhase::RTe().
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (double * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from IdealGasPhase.
Definition at line 285 of file PlasmaPhase.cpp.
References PlasmaPhase::electronTemperature(), IdealGasPhase::getPartialMolarEnthalpies(), PlasmaPhase::m_electronSpeciesIndex, and Phase::temperature().
getPartialMolarEntropies()
void getPartialMolarEntropies (double * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from IdealGasPhase.
Definition at line 291 of file PlasmaPhase.cpp.
References PlasmaPhase::electronPressure(), Cantera::GasConstant, IdealGasPhase::getPartialMolarEntropies(), PlasmaPhase::m_electronSpeciesIndex, and IdealGasPhase::pressure().
getPartialMolarIntEnergies()
void getPartialMolarIntEnergies (double * ubar) const virtual
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from IdealGasPhase.
Definition at line 299 of file PlasmaPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), PlasmaPhase::m_electronSpeciesIndex, Phase::m_kk, ThermoPhase::RT(), and PlasmaPhase::RTe().
getParameters()
void getParameters (AnyMap & phaseNode) const virtual
Store the parameters of a ThermoPhase object such that an identical one could be reconstructed using the newThermo(AnyMap&) function.
This does not include user-defined fields available in input().
Reimplemented from ThermoPhase.
Definition at line 152 of file PlasmaPhase.cpp.
References ThermoPhase::getParameters(), PlasmaPhase::m_distributionType, PlasmaPhase::m_do_normalizeElectronEnergyDist, PlasmaPhase::m_electronEnergyDist, PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_nPoints, and PlasmaPhase::meanElectronEnergy().
setParameters()
void setParameters (const AnyMap & phaseNode, const AnyMap & rootNode = AnyMap()) virtual
Set equation of state parameters from an AnyMap phase description.
Phases that need additional parameters from the root node should override this method.
Reimplemented from ThermoPhase.
Definition at line 172 of file PlasmaPhase.cpp.
References AnyMap::convert(), PlasmaPhase::enableNormalizeElectronEnergyDist(), AnyMap::hasKey(), PlasmaPhase::m_distributionType, PlasmaPhase::setDiscretizedElectronEnergyDist(), PlasmaPhase::setElectronEnergyLevels(), PlasmaPhase::setIsotropicElectronEnergyDistribution(), PlasmaPhase::setIsotropicShapeFactor(), PlasmaPhase::setMeanElectronEnergy(), and ThermoPhase::setParameters().
updateThermo()
void updateThermo () const protected virtual
Update the species reference state thermodynamic functions.
This method is called each time a thermodynamic property is requested, to check whether the internal species properties within the object need to be updated. Currently, this updates the species thermo polynomial values for the current value of the temperature. A check is made to see if the temperature has changed since the last evaluation. This object does not contain any persistent data that depends on the concentration, that needs to be updated. The state object modifies its concentration dependent information at the time the setMoleFractions() (or equivalent) call is made.
Reimplemented from IdealGasPhase.
Definition at line 245 of file PlasmaPhase.cpp.
References PlasmaPhase::electronTemperature(), ValueCache::getId(), ValueCache::getScalar(), Phase::m_cache, IdealGasPhase::m_cp0_R, PlasmaPhase::m_electronSpeciesIndex, IdealGasPhase::m_g0_RT, IdealGasPhase::m_h0_RT, IdealGasPhase::m_s0_R, ThermoPhase::m_spthermo, CachedValue< T >::state1, CachedValue< T >::state2, Phase::temperature(), MultiSpeciesThermo::update_single(), and IdealGasPhase::updateThermo().
checkElectronEnergyLevels()
void checkElectronEnergyLevels () const protected
Check the electron energy levels.
The values of electron energy levels need to be positive and monotonically increasing.
Definition at line 92 of file PlasmaPhase.cpp.
References PlasmaPhase::m_electronEnergyLevels, and PlasmaPhase::m_nPoints.
Referenced by PlasmaPhase::setDiscretizedElectronEnergyDist(), and PlasmaPhase::setElectronEnergyLevels().
checkElectronEnergyDistribution()
void checkElectronEnergyDistribution () const protected
Check the electron energy distribution.
This method check the electron energy distribution for the criteria below.
The values of electron energy distribution cannot be negative.
If the last value of electron energy distribution is larger than 0.01, it will raise a warning to suggest using a higher electron energy levels.
Definition at line 103 of file PlasmaPhase.cpp.
References PlasmaPhase::m_electronEnergyDist, PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_nPoints, PlasmaPhase::meanElectronEnergy(), and Cantera::warn_user().
Referenced by PlasmaPhase::setDiscretizedElectronEnergyDist(), and PlasmaPhase::setIsotropicElectronEnergyDistribution().
updateElectronEnergyDistribution()
void updateElectronEnergyDistribution () protected
Update electron energy distribution.
Definition at line 25 of file PlasmaPhase.cpp.
References PlasmaPhase::m_distributionType, and PlasmaPhase::setIsotropicElectronEnergyDistribution().
Referenced by PlasmaPhase::setElectronEnergyLevels(), PlasmaPhase::setElectronTemperature(), and PlasmaPhase::setMeanElectronEnergy().
setIsotropicElectronEnergyDistribution()
void setIsotropicElectronEnergyDistribution () protected
Set isotropic electron energy distribution.
Definition at line 58 of file PlasmaPhase.cpp.
References PlasmaPhase::checkElectronEnergyDistribution(), PlasmaPhase::m_electronEnergyDist, PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_nPoints, and PlasmaPhase::meanElectronEnergy().
Referenced by PlasmaPhase::setIsotropicShapeFactor(), PlasmaPhase::setParameters(), and PlasmaPhase::updateElectronEnergyDistribution().
updateElectronTemperatureFromEnergyDist()
void updateElectronTemperatureFromEnergyDist () protected
Update electron temperature (K) From energy distribution.
m_electronTemp
Definition at line 138 of file PlasmaPhase.cpp.
References Cantera::Boltzmann, Cantera::ElectronCharge, PlasmaPhase::m_electronEnergyDist, PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_electronTemp, PlasmaPhase::m_quadratureMethod, and Cantera::numericalQuadrature().
Referenced by PlasmaPhase::setDiscretizedElectronEnergyDist().
normalizeElectronEnergyDistribution()
void normalizeElectronEnergyDistribution () protected
Electron energy distribution norm.
Definition at line 35 of file PlasmaPhase.cpp.
References PlasmaPhase::m_electronEnergyDist, PlasmaPhase::m_electronEnergyLevels, PlasmaPhase::m_quadratureMethod, and Cantera::numericalQuadrature().
Referenced by PlasmaPhase::setDiscretizedElectronEnergyDist().
Member Data Documentation
m_isotropicShapeFactor
double m_isotropicShapeFactor = 2.0 protected
Definition at line 307 of file PlasmaPhase.h.
m_nPoints
size_t m_nPoints = 1001 protected
Number of points of electron energy levels.
Definition at line 310 of file PlasmaPhase.h.
Referenced by PlasmaPhase::checkElectronEnergyDistribution(), PlasmaPhase::checkElectronEnergyLevels(), PlasmaPhase::getElectronEnergyDistribution(), PlasmaPhase::getElectronEnergyLevels(), PlasmaPhase::getParameters(), PlasmaPhase::nElectronEnergyLevels(), PlasmaPhase::PlasmaPhase(), PlasmaPhase::setDiscretizedElectronEnergyDist(), PlasmaPhase::setElectronEnergyLevels(), and PlasmaPhase::setIsotropicElectronEnergyDistribution().
m_electronEnergyLevels
Eigen::ArrayXd m_electronEnergyLevels protected
electron energy levels [ev]. Length: m_nPoints
Definition at line 313 of file PlasmaPhase.h.
Referenced by PlasmaPhase::checkElectronEnergyDistribution(), PlasmaPhase::checkElectronEnergyLevels(), PlasmaPhase::getElectronEnergyLevels(), PlasmaPhase::getParameters(), PlasmaPhase::normalizeElectronEnergyDistribution(), PlasmaPhase::PlasmaPhase(), PlasmaPhase::setDiscretizedElectronEnergyDist(), PlasmaPhase::setElectronEnergyLevels(), PlasmaPhase::setIsotropicElectronEnergyDistribution(), and PlasmaPhase::updateElectronTemperatureFromEnergyDist().
m_electronEnergyDist
Eigen::ArrayXd m_electronEnergyDist protected
Normalized electron energy distribution vector [-] Length: m_nPoints.
Definition at line 317 of file PlasmaPhase.h.
Referenced by PlasmaPhase::checkElectronEnergyDistribution(), PlasmaPhase::getElectronEnergyDistribution(), PlasmaPhase::getParameters(), PlasmaPhase::normalizeElectronEnergyDistribution(), PlasmaPhase::setDiscretizedElectronEnergyDist(), PlasmaPhase::setIsotropicElectronEnergyDistribution(), and PlasmaPhase::updateElectronTemperatureFromEnergyDist().
m_electronSpeciesIndex
size_t m_electronSpeciesIndex = npos protected
Index of electron species.
Definition at line 320 of file PlasmaPhase.h.
Referenced by PlasmaPhase::addSpecies(), PlasmaPhase::electronPressure(), PlasmaPhase::electronSpeciesIndex(), PlasmaPhase::enthalpy_mole(), PlasmaPhase::getChemPotentials(), PlasmaPhase::getEntropy_R(), PlasmaPhase::getGibbs_ref(), PlasmaPhase::getGibbs_RT(), PlasmaPhase::getPartialMolarEnthalpies(), PlasmaPhase::getPartialMolarEntropies(), PlasmaPhase::getPartialMolarIntEnergies(), PlasmaPhase::getStandardChemPotentials(), PlasmaPhase::getStandardVolumes_ref(), PlasmaPhase::initThermo(), and PlasmaPhase::updateThermo().
m_electronTemp
double m_electronTemp protected
Electron temperature [K].
Definition at line 323 of file PlasmaPhase.h.
Referenced by PlasmaPhase::electronTemperature(), PlasmaPhase::setElectronTemperature(), PlasmaPhase::setMeanElectronEnergy(), and PlasmaPhase::updateElectronTemperatureFromEnergyDist().
m_distributionType
string m_distributionType = "isotropic" protected
Electron energy distribution type.
Definition at line 326 of file PlasmaPhase.h.
Referenced by PlasmaPhase::electronEnergyDistributionType(), PlasmaPhase::getParameters(), PlasmaPhase::setDiscretizedElectronEnergyDist(), PlasmaPhase::setElectronEnergyDistributionType(), PlasmaPhase::setParameters(), and PlasmaPhase::updateElectronEnergyDistribution().
m_quadratureMethod
string m_quadratureMethod = "simpson" protected
Numerical quadrature method for electron energy distribution.
Definition at line 329 of file PlasmaPhase.h.
Referenced by PlasmaPhase::normalizeElectronEnergyDistribution(), PlasmaPhase::quadratureMethod(), PlasmaPhase::setQuadratureMethod(), and PlasmaPhase::updateElectronTemperatureFromEnergyDist().
m_do_normalizeElectronEnergyDist
bool m_do_normalizeElectronEnergyDist = true protected
Flag of normalizing electron energy distribution.
Definition at line 332 of file PlasmaPhase.h.
Referenced by PlasmaPhase::enableNormalizeElectronEnergyDist(), PlasmaPhase::getParameters(), PlasmaPhase::normalizeElectronEnergyDistEnabled(), and PlasmaPhase::setDiscretizedElectronEnergyDist().
The documentation for this class was generated from the following files:
PlasmaPhase.h
PlasmaPhase.cpp