Cantera: AnyValue Class Reference
AnyValue Class Reference
A wrapper for a variable whose type is determined at runtime.
#include <AnyMap.h>
Public Member Functions
bool operator== (const AnyValue &other) const
bool operator!= (const AnyValue &other) const
AnyValue & operator[] (const std::string &key)
If this AnyValue is an AnyMap, return the value stored in key.
const AnyValue & operator[] (const std::string &key) const
bool hasKey (const std::string &key) const
Returns true if this AnyValue is an AnyMap and that map contains a key with the given name.
void setKey (const std::string &key)
Set the name of the key storing this value in an AnyMap.
void propagateMetadata (shared_ptr< AnyMap > &file)
Propagate metadata to any child elements.
template<class T >
const T & as () const
Get the value of this key as the specified type.
template<class T >
T & as ()
const std::type_info & type () const
Returns the type of the held value.
std::string type_str () const
Returns a string specifying the type of the held value.
bool empty () const
Return boolean indicating whether AnyValue is empty.
template<class T >
bool is () const
Returns true if the held value is of the specified type.
template<class T >
bool isVector () const
Returns true if the held value is a vector of the specified type, such as vector<double>.
template<class T >
bool isMatrix (size_t cols=npos) const
Returns true if the held value is a matrix of the specified type and a consistent number of columns, such as vector<vector<double>>.
bool isScalar () const
Returns true if the held value is a scalar type (such as double, long int, string, or bool).
size_t vectorSize () const
Returns size of the held vector.
pair< size_t, size_t > matrixShape () const
Returns rows and columns of a matrix.
AnyValue (const std::string &value)
AnyValue (const char *value)
AnyValue & operator= (const std::string &value)
AnyValue & operator= (const char *value)
const std::string & asString () const
Return the held value, if it is a string.
bool operator== (const std::string &other) const
bool operator!= (const std::string &other) const
AnyValue (double value)
AnyValue & operator= (double value)
double & asDouble ()
Return the held value as a double, if it is a double or a long int.
const double & asDouble () const
bool operator== (const double &other) const
bool operator!= (const double &other) const
AnyValue (bool value)
AnyValue & operator= (bool value)
bool & asBool ()
Return the held value, if it is a bool.
const bool & asBool () const
AnyValue (long int value)
AnyValue (int value)
AnyValue & operator= (long int value)
AnyValue & operator= (int value)
long int & asInt ()
Return the held value, if it is a long int.
const long int & asInt () const
bool operator== (const long int &other) const
bool operator!= (const long int &other) const
bool operator== (const int &other) const
bool operator!= (const int &other) const
template<class T >
AnyValue & operator= (const std::vector< T > &value)
template<class T >
const std::vector< T > & asVector (size_t nMin=npos, size_t nMax=npos) const
Return the held value, if it is a vector of type T.
template<class T >
std::vector< T > & asVector (size_t nMin=npos, size_t nMax=npos)
AnyValue (const AnyMap &value)
AnyValue & operator= (const AnyMap &value)
AnyValue & operator= (AnyMap &&value)
template<class T >
AnyValue & operator= (const std::unordered_map< std::string, T > items)
template<class T >
AnyValue & operator= (const std::map< std::string, T > items)
template<class T >
std::map< std::string, T > asMap () const
Return the held AnyMap as a std::map where all of the values have the specified type.
std::unordered_map< std::string, const AnyMap * > asMap (const std::string &name) const
Access a vector<AnyMap> as a mapping using the value of name from each item as the key in the new mapping.
std::unordered_map< std::string, AnyMap * > asMap (const std::string &name)
AnyMap & getMapWhere (const std::string &key, const std::string &value, bool create=false)
Treating the value as vector<AnyMap>, return the item where the given key has the specified value.
const AnyMap & getMapWhere (const std::string &key, const std::string &value) const
bool hasMapWhere (const std::string &key, const std::string &value) const
Returns true when getMapWhere() would succeed.
std::pair< int, int > order () const
Return values used to determine the sort order when outputting to YAML.
void applyUnits (shared_ptr< UnitSystem > &units)
See AnyMap::applyUnits()
void setFlowStyle (bool flow=true)
See AnyMap::setFlowStyle()
template<>
bool is () const
template<>
const std::vector< AnyValue > & asVector (size_t nMin, size_t nMax) const
template<>
std::vector< AnyValue > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< double > & asVector (size_t nMin, size_t nMax) const
template<>
std::vector< double > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< vector_fp > & asVector (size_t nMin, size_t nMax) const
template<>
std::vector< vector_fp > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< AnyMap > & asVector (size_t nMin, size_t nMax) const
template<>
std::vector< AnyMap > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< AnyValue > & asVector (size_t nMin, size_t nMax) const
Implicit conversion to vector<AnyValue>
template<>
std::vector< AnyValue > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< double > & asVector (size_t nMin, size_t nMax) const
Implicit conversion of long int to double if accessed as a vector<double>
template<>
std::vector< double > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< vector_fp > & asVector (size_t nMin, size_t nMax) const
Implicit conversion of long int to double if accessed as a vector<vector<double>>
template<>
std::vector< vector_fp > & asVector (size_t nMin, size_t nMax)
template<>
const std::vector< AnyMap > & asVector (size_t nMin, size_t nMax) const
Implicit conversion of AnyMap to a vector<AnyMap> of length 1, or an empty vector<AnyValue> an empty vector<AnyMap>
template<>
std::vector< AnyMap > & asVector (size_t nMin, size_t nMax)
template<>
AnyMap & as ()
Public Member Functions inherited from AnyBase
void setLoc (int line, int column)
For values which are derived from an input file, set the line and column of this value in that file.
const AnyValue & getMetadata (const std::string &key) const
Get a value from the metadata applicable to the AnyMap tree containing this node.
Private Types
typedef bool(* Comparer) (const std::any &, const std::any &)
Private Member Functions
template<class T >
void checkSize (const std::vector< T > &v, size_t nMin, size_t nMax) const
Static Private Member Functions
template<typename T >
static bool eq_comparer (const std::any &lhs, const std::any &rhs)
Equality comparison function used when lhs is of type T
template<class T , class U >
static bool vector_eq (const std::any &lhs, const std::any &rhs)
Helper function for comparing vectors of different (but comparable) types, for example vector<double> and vector<long int>
template<class T , class U >
static bool vector2_eq (const std::any &lhs, const std::any &rhs)
Helper function for comparing nested vectors of different (but comparable) types, for example vector<vector<double>> and vector<vector<long int>>
Private Attributes
std::string m_key
Key of this value in a parent AnyMap
std::any m_value
The held value.
Comparer m_equals
Friends
bool operator== (const std::string &lhs, const AnyValue &rhs)
bool operator!= (const std::string &lhs, const AnyValue &rhs)
bool operator== (const double &lhs, const AnyValue &rhs)
bool operator!= (const double &lhs, const AnyValue &rhs)
bool operator== (const long int &lhs, const AnyValue &rhs)
bool operator!= (const long int &lhs, const AnyValue &rhs)
bool operator== (const int &lhs, const AnyValue &rhs)
bool operator!= (const int &lhs, const AnyValue &rhs)
YAML::Emitter & YAML::operator<< (YAML::Emitter &out, const AnyValue &rhs)
Quantity conversions
Assign a quantity consisting of one or more values and their corresponding units, which will be converted to a target unit system when the applyUnits() function is later called on the root of the AnyMap.
typedef std::function< void(AnyValue &, const UnitSystem &)> unitConverter
void setQuantity (double value, const std::string &units, bool is_act_energy=false)
Assign a scalar quantity with units as a string, for example {3.0, "m^2"}.
void setQuantity (double value, const Units &units)
Assign a scalar quantity with units as a Units object, for cases where the units vary and are determined dynamically, such as reaction pre-exponential factors.
void setQuantity (const vector_fp &values, const std::string &units)
Assign a vector where all the values have the same units.
void setQuantity (const AnyValue &value, const unitConverter &converter)
Assign a value of any type where the unit conversion requires a different behavior besides scaling all values by the same factor.
Additional Inherited Members
Protected Attributes inherited from AnyBase
int m_line = -1
The line where this value occurs in the input file.
int m_column = 0
If m_line >= 0, the column where this value occurs in the input file.
shared_ptr< AnyMap > m_metadata
Metadata relevant to an entire AnyMap tree, such as information about.
Detailed Description
A wrapper for a variable whose type is determined at runtime.
Instances of AnyValue are used as values in an AnyMap. Values are converted to a concrete type using the templated as() method or convenience methods such as asString() and asDouble(). See AnyMap for usage examples.
Elements are set using assignment, and the assignment operator has been overloaded for specific types so that only those types are allowed to be used in an AnyValue. The allowed types are:
AnyMap
double
long int
bool
std::string
std::vector of any of the above
Definition at line 79 of file AnyMap.h.
Member Typedef Documentation
unitConverter
typedef std::function<void(AnyValue&, const UnitSystem&)> unitConverter
Definition at line 186 of file AnyMap.h.
Comparer
typedef bool(* Comparer) (const std::any &, const std::any &) private
Definition at line 300 of file AnyMap.h.
Constructor & Destructor Documentation
AnyValue() [1/8]
AnyValue ()
Definition at line 580 of file AnyMap.cpp.
AnyValue() [2/8]
AnyValue (const std::string & value) explicit
Definition at line 706 of file AnyMap.cpp.
AnyValue() [3/8]
AnyValue (const char * value) explicit
Definition at line 711 of file AnyMap.cpp.
AnyValue() [4/8]
AnyValue (double value) explicit
Definition at line 802 of file AnyMap.cpp.
AnyValue() [5/8]
AnyValue (bool value) explicit
Definition at line 849 of file AnyMap.cpp.
AnyValue() [6/8]
AnyValue (long int value) explicit
Definition at line 870 of file AnyMap.cpp.
AnyValue() [7/8]
AnyValue (int value) explicit
Definition at line 875 of file AnyMap.cpp.
AnyValue() [8/8]
AnyValue (const AnyMap & value) explicit
Definition at line 948 of file AnyMap.cpp.
Member Function Documentation
operator==() [1/5]
bool operator== (const AnyValue & other) const
Definition at line 586 of file AnyMap.cpp.
operator!=() [1/5]
bool operator!= (const AnyValue & other) const
Definition at line 591 of file AnyMap.cpp.
operator[]() [1/2]
AnyValue & operator[] (const std::string & key)
If this AnyValue is an AnyMap, return the value stored in key.
Definition at line 596 of file AnyMap.cpp.
operator[]() [2/2]
const AnyValue & operator[] (const std::string & key) const
Definition at line 601 of file AnyMap.cpp.
hasKey()
bool hasKey (const std::string & key) const
Returns true if this AnyValue is an AnyMap and that map contains a key with the given name.
Definition at line 606 of file AnyMap.cpp.
References AnyValue::hasKey().
Referenced by AnyValue::getMapWhere(), AnyValue::hasKey(), AnyValue::hasMapWhere(), and Domain1D::setMeta().
setKey()
void setKey (const std::string & key)
Set the name of the key storing this value in an AnyMap.
Used for providing informative error messages in class InputFileError.
Definition at line 610 of file AnyMap.cpp.
References AnyValue::m_key.
Referenced by AnyMap::createForYaml(), and AnyMap::operator[]().
propagateMetadata()
void propagateMetadata (shared_ptr< AnyMap > & file)
Propagate metadata to any child elements.
Definition at line 616 of file AnyMap.cpp.
References AnyValue::is(), and AnyBase::m_metadata.
Referenced by AnyMap::createForYaml(), and AnyMap::operator[]().
as() [1/3]
const T & as
Get the value of this key as the specified type.
Definition at line 16 of file AnyMap.inl.h.
References AnyValue::asDouble(), Cantera::demangle(), AnyValue::m_key, and AnyValue::m_value.
Referenced by SolutionArray::_initExtra(), AnyValue::applyUnits(), Inlet1D::fromArray(), StFlow::fromArray(), and ArrheniusBase::setRateParameters().
as() [2/3]
T & as
Definition at line 61 of file AnyMap.inl.h.
type()
const std::type_info & type () const
Returns the type of the held value.
Definition at line 612 of file AnyMap.cpp.
References AnyValue::m_value.
Referenced by AnyValue::type_str().
type_str()
std::string type_str () const
Returns a string specifying the type of the held value.
Definition at line 632 of file AnyMap.cpp.
References Cantera::demangle(), and AnyValue::type().
Referenced by SolutionArray::_initExtra(), SolutionArray::_setExtra(), and SolutionArray::setComponent().
empty()
bool empty () const
Return boolean indicating whether AnyValue is empty.
Definition at line 636 of file AnyMap.cpp.
References AnyValue::m_value.
Referenced by ReactingSurf1D::asArray(), StFlow::getMeta(), and ArrheniusBase::setRateParameters().
is() [1/2]
bool is
Returns true if the held value is of the specified type.
Definition at line 68 of file AnyMap.inl.h.
References AnyValue::m_value.
Referenced by SolutionArray::_initExtra(), SolutionArray::_setExtra(), AnyValue::applyUnits(), AnyValue::getMapWhere(), AnyValue::hasMapWhere(), AnyValue::propagateMetadata(), ArrheniusBase::setRateParameters(), and MolalityVPSSTP::setState().
isVector()
bool isVector
Returns true if the held value is a vector of the specified type, such as vector<double>.
Since
New in Cantera 3.0.
Definition at line 75 of file AnyMap.inl.h.
References AnyValue::m_value.
Referenced by SolutionArray::_initExtra(), SolutionArray::_setExtra(), and AnyValue::matrixShape().
isMatrix()
bool isMatrix (size_t cols = npos) const
Returns true if the held value is a matrix of the specified type and a consistent number of columns, such as vector<vector<double>>.
If the number of columns is provided, a match is required.
Since
New in Cantera 3.0.
Definition at line 80 of file AnyMap.inl.h.
References AnyValue::m_value, and Cantera::npos.
isScalar()
bool isScalar () const
Returns true if the held value is a scalar type (such as double, long int, string, or bool).
Definition at line 640 of file AnyMap.cpp.
Referenced by SolutionArray::_setExtra(), and StFlow::setMeta().
vectorSize()
size_t vectorSize () const
Returns size of the held vector.
If not a vector or the type is not supported npos is returned. Types considered include vector<double>, vector<long int>, vector<string>, and vector<bool.
Since
New in Cantera 3.0.
Definition at line 644 of file AnyMap.cpp.
References Cantera::npos.
Referenced by SolutionArray::_setExtra(), and SolutionArray::setComponent().
matrixShape()
pair< size_t, size_t > matrixShape () const
Returns rows and columns of a matrix.
If the number of columns is not consistent, the number of columns is set to npos; if the type is not supported, a npos pair is returned. Types considered include vector<vector<double>>, vector<vector<long int>>, vector<vector<string>> and vector<vector<bool>>.
Since
New in Cantera 3.0.
Definition at line 660 of file AnyMap.cpp.
References AnyValue::isVector(), and Cantera::npos.
Referenced by SolutionArray::_setExtra().
operator=() [1/11]
AnyValue & operator= (const std::string & value)
Definition at line 716 of file AnyMap.cpp.
operator=() [2/11]
AnyValue & operator= (const char * value)
Definition at line 722 of file AnyMap.cpp.
asString()
const std::string & asString () const
Return the held value, if it is a string.
Definition at line 728 of file AnyMap.cpp.
Referenced by ReactingSurf1D::asArray(), StFlow::getMeta(), and MolalityVPSSTP::setState().
operator==() [2/5]
bool operator== (const std::string & other) const
Definition at line 732 of file AnyMap.cpp.
operator!=() [2/5]
bool operator!= (const std::string & other) const
Definition at line 741 of file AnyMap.cpp.
setQuantity() [1/4]
void setQuantity (double value, const std::string & units, bool is_act_energy = false)
Assign a scalar quantity with units as a string, for example {3.0, "m^2"}.
If the is_act_energy flag is set to true, the units will be converted using the special rules for activation energies.
Definition at line 758 of file AnyMap.cpp.
References AnyValue::m_value.
setQuantity() [2/4]
void setQuantity (double value, const Units & units)
Assign a scalar quantity with units as a Units object, for cases where the units vary and are determined dynamically, such as reaction pre-exponential factors.
Definition at line 763 of file AnyMap.cpp.
References AnyValue::m_value.
setQuantity() [3/4]
void setQuantity (const vector_fp & values, const std::string & units)
Assign a vector where all the values have the same units.
Definition at line 768 of file AnyMap.cpp.
References AnyValue::m_value.
setQuantity() [4/4]
void setQuantity (const AnyValue & value, const unitConverter & converter)
Assign a value of any type where the unit conversion requires a different behavior besides scaling all values by the same factor.
Definition at line 775 of file AnyMap.cpp.
References AnyValue::m_value.
operator=() [3/11]
AnyValue & operator= (double value)
Definition at line 807 of file AnyMap.cpp.
asDouble() [1/2]
double & asDouble ()
Return the held value as a double, if it is a double or a long int.
Definition at line 813 of file AnyMap.cpp.
Referenced by AnyValue::as(), Inlet1D::fromArray(), and InterfaceRateBase::setCoverageDependencies().
asDouble() [2/2]
const double & asDouble () const
Definition at line 817 of file AnyMap.cpp.
operator==() [3/5]
bool operator== (const double & other) const
Definition at line 821 of file AnyMap.cpp.
operator!=() [3/5]
bool operator!= (const double & other) const
Definition at line 832 of file AnyMap.cpp.
operator=() [4/11]
AnyValue & operator= (bool value)
Definition at line 854 of file AnyMap.cpp.
asBool() [1/2]
bool & asBool ()
Return the held value, if it is a bool.
Definition at line 860 of file AnyMap.cpp.
Referenced by StFlow::setMeta().
asBool() [2/2]
const bool & asBool () const
Definition at line 864 of file AnyMap.cpp.
operator=() [5/11]
AnyValue & operator= (long int value)
Definition at line 880 of file AnyMap.cpp.
operator=() [6/11]
AnyValue & operator= (int value)
Definition at line 886 of file AnyMap.cpp.
asInt() [1/2]
long int & asInt ()
Return the held value, if it is a long int.
Definition at line 892 of file AnyMap.cpp.
asInt() [2/2]
const long int & asInt () const
Definition at line 896 of file AnyMap.cpp.
operator==() [4/5]
bool operator== (const long int & other) const
Definition at line 900 of file AnyMap.cpp.
operator!=() [4/5]
bool operator!= (const long int & other) const
Definition at line 911 of file AnyMap.cpp.
operator==() [5/5]
bool operator== (const int & other) const
Definition at line 916 of file AnyMap.cpp.
operator!=() [5/5]
bool operator!= (const int & other) const
Definition at line 921 of file AnyMap.cpp.
operator=() [7/11]
AnyValue & operator= (const std::vector< T > & value)
Definition at line 102 of file AnyMap.inl.h.
asVector() [1/14]
const std::vector< T > & asVector (size_t nMin = npos, size_t nMax = npos) const
Return the held value, if it is a vector of type T.
If called with one argument, requires the vector to be of the specified size. If called with two arguments, requires the vector to be within the range specified by the two values, inclusive.
Definition at line 109 of file AnyMap.inl.h.
Referenced by SolutionArray::_initExtra(), Cantera::addReactions(), ChebyshevRate::getParameters(), Cantera::getReactions(), Cantera::getSpecies(), SolutionArray::readEntry(), SolutionArray::setComponent(), StFlow::setMeta(), and ArrheniusBase::setRateParameters().
asVector() [2/14]
std::vector< T > & asVector (size_t nMin = npos, size_t nMax = npos)
Definition at line 116 of file AnyMap.inl.h.
operator=() [8/11]
AnyValue & operator= (const AnyMap & value)
Definition at line 953 of file AnyMap.cpp.
operator=() [9/11]
AnyValue & operator= (AnyMap && value)
Definition at line 959 of file AnyMap.cpp.
operator=() [10/11]
AnyValue & operator= (const std::unordered_map< std::string, T > items)
Definition at line 123 of file AnyMap.inl.h.
operator=() [11/11]
AnyValue & operator= (const std::map< std::string, T > items)
Definition at line 134 of file AnyMap.inl.h.
asMap() [1/3]
std::map< std::string, T > asMap
Return the held AnyMap as a std::map where all of the values have the specified type.
Definition at line 162 of file AnyMap.inl.h.
Referenced by MolalityVPSSTP::setState().
asMap() [2/3]
std::unordered_map< std::string, const AnyMap * > asMap (const std::string & name) const
Access a vector<AnyMap> as a mapping using the value of name from each item as the key in the new mapping.
For example, for the list:
[{name: O2, weight: 32}, {name: CH4, weight: 16}]
calling asMap("name") will create a map with keys O2 and CH4.
Definition at line 965 of file AnyMap.cpp.
asMap() [3/3]
std::unordered_map< std::string, AnyMap * > asMap (const std::string & name)
Definition at line 980 of file AnyMap.cpp.
getMapWhere() [1/2]
AnyMap & getMapWhere (const std::string & key, const std::string & value, bool create = false)
Treating the value as vector<AnyMap>, return the item where the given key has the specified value.
If value is the empty string, returns the first item in the list.
If the contained type is just AnyMap rather than vector<AnyMap>, it will be treated as a vector of length 1.
If the value does not exist but the create flag is set to true, a new map with that key and value will be created and returned.
Definition at line 1024 of file AnyMap.cpp.
References AnyMap::at(), AnyValue::hasKey(), AnyValue::is(), and AnyValue::m_key.
Referenced by Cantera::newSolution().
getMapWhere() [2/2]
const AnyMap & getMapWhere (const std::string & key, const std::string & value) const
Definition at line 994 of file AnyMap.cpp.
hasMapWhere()
bool hasMapWhere (const std::string & key, const std::string & value) const
Returns true when getMapWhere() would succeed.
Definition at line 1075 of file AnyMap.cpp.
References AnyValue::hasKey(), and AnyValue::is().
order()
std::pair< int, int > order () const
Return values used to determine the sort order when outputting to YAML.
Definition at line 1098 of file AnyMap.cpp.
References AnyBase::m_column, and AnyBase::m_line.
applyUnits()
void applyUnits (shared_ptr< UnitSystem > & units)
See AnyMap::applyUnits()
Definition at line 1103 of file AnyMap.cpp.
References AnyMap::applyUnits(), AnyValue::as(), AnyMap::getBool(), AnyMap::hasKey(), AnyValue::is(), AnyValue::m_key, AnyValue::m_value, and Cantera::scale().
setFlowStyle()
void setFlowStyle (bool flow = true)
See AnyMap::setFlowStyle()
Definition at line 1200 of file AnyMap.cpp.
checkSize()
void checkSize (const std::vector< T > & v, size_t nMin, size_t nMax) const private
Definition at line 172 of file AnyMap.inl.h.
eq_comparer()
bool eq_comparer (const std::any & lhs, const std::any & rhs) static private
Equality comparison function used when lhs is of type T
Definition at line 216 of file AnyMap.inl.h.
References AssertThrowMsg.
vector_eq()
bool vector_eq (const std::any & lhs, const std::any & rhs) static private
Helper function for comparing vectors of different (but comparable) types, for example vector<double> and vector<long int>
Definition at line 187 of file AnyMap.inl.h.
vector2_eq()
bool vector2_eq (const std::any & lhs, const std::any & rhs) static private
Helper function for comparing nested vectors of different (but comparable) types, for example vector<vector<double>> and vector<vector<long int>>
Definition at line 199 of file AnyMap.inl.h.
is() [2/2]
bool is () const
Definition at line 782 of file AnyMap.cpp.
asVector() [3/14]
const std::vector< AnyValue > & asVector (size_t nMin, size_t nMax) const
Definition at line 1208 of file AnyMap.cpp.
asVector() [4/14]
std::vector< AnyValue > & asVector (size_t nMin, size_t nMax)
Definition at line 1208 of file AnyMap.cpp.
asVector() [5/14]
const std::vector< double > & asVector (size_t nMin, size_t nMax) const
Definition at line 1247 of file AnyMap.cpp.
asVector() [6/14]
std::vector< double > & asVector (size_t nMin, size_t nMax)
Definition at line 1247 of file AnyMap.cpp.
asVector() [7/14]
const std::vector< vector_fp > & asVector (size_t nMin, size_t nMax) const
Definition at line 1279 of file AnyMap.cpp.
asVector() [8/14]
std::vector< vector_fp > & asVector (size_t nMin, size_t nMax)
Definition at line 1279 of file AnyMap.cpp.
asVector() [9/14]
const std::vector< AnyMap > & asVector (size_t nMin, size_t nMax) const
Definition at line 1317 of file AnyMap.cpp.
asVector() [10/14]
std::vector< AnyMap > & asVector (size_t nMin, size_t nMax)
Definition at line 1317 of file AnyMap.cpp.
asVector() [11/14]
const std::vector< AnyValue > & asVector (size_t nMin, size_t nMax) const
Implicit conversion to vector<AnyValue>
asVector() [12/14]
const std::vector< double > & asVector (size_t nMin, size_t nMax) const
Implicit conversion of long int to double if accessed as a vector<double>
asVector() [13/14]
const std::vector< vector_fp > & asVector (size_t nMin, size_t nMax) const
Implicit conversion of long int to double if accessed as a vector<vector<double>>
asVector() [14/14]
const std::vector< AnyMap > & asVector (size_t nMin, size_t nMax) const
Implicit conversion of AnyMap to a vector<AnyMap> of length 1, or an empty vector<AnyValue> an empty vector<AnyMap>
as() [3/3]
AnyMap & as () inline
Definition at line 145 of file AnyMap.inl.h.
Friends And Related Function Documentation
operator== [1/4]
bool operator== (const std::string & lhs, const AnyValue & rhs) friend
Definition at line 746 of file AnyMap.cpp.
operator!= [1/4]
bool operator!= (const std::string & lhs, const AnyValue & rhs) friend
Definition at line 751 of file AnyMap.cpp.
operator== [2/4]
bool operator== (const double & lhs, const AnyValue & rhs) friend
Definition at line 837 of file AnyMap.cpp.
operator!= [2/4]
bool operator!= (const double & lhs, const AnyValue & rhs) friend
Definition at line 842 of file AnyMap.cpp.
operator== [3/4]
bool operator== (const long int & lhs, const AnyValue & rhs) friend
Definition at line 926 of file AnyMap.cpp.
operator!= [3/4]
bool operator!= (const long int & lhs, const AnyValue & rhs) friend
Definition at line 931 of file AnyMap.cpp.
operator== [4/4]
bool operator== (const int & lhs, const AnyValue & rhs) friend
Definition at line 936 of file AnyMap.cpp.
operator!= [4/4]
bool operator!= (const int & lhs, const AnyValue & rhs) friend
Definition at line 941 of file AnyMap.cpp.
Member Data Documentation
m_key
std::string m_key private
Key of this value in a parent AnyMap
Definition at line 295 of file AnyMap.h.
Referenced by AnyValue::applyUnits(), AnyValue::as(), AnyValue::getMapWhere(), and AnyValue::setKey().
m_value
std::any m_value private
The held value.
Definition at line 298 of file AnyMap.h.
Referenced by AnyValue::applyUnits(), AnyValue::as(), AnyValue::empty(), AnyValue::is(), AnyValue::isMatrix(), AnyValue::isVector(), AnyValue::setQuantity(), and AnyValue::type().
m_equals
Comparer m_equals mutable private
Definition at line 317 of file AnyMap.h.
The documentation for this class was generated from the following files:
AnyMap.h
AnyMap.cpp
AnyMap.inl.h